/**
 * Katalog 500 — Desery (de-1 … de-35), AFTERNOON_SNACK.
 * Lista: `prisma/catalog/katalog-500-lista.md`; generator: `scripts/lib/katalog-500-2026-09.ts`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'de-1',
    title: 'Szarlotka na kruchym cieście',
    description:
      'Klasyczna domowa szarlotka: kruche, maślane ciasto i gruba warstwa duszonych jabłek z cynamonem. Najlepsza lekko ciepła, z cukrem pudrem, na niedzielną kawę albo wizytę gości.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 120,
    servings: 8,
    ingredients: [
      ['mąka pszenna', 300, 'g'],
      ['masło', 200, 'g'],
      ['cukier puder', 90, 'g'],
      ['jajko', 2, 'szt'],
      ['proszek do pieczenia', 5, 'g'],
      ['jabłko', 1500, 'g'],
      ['cukier', 60, 'g'],
      ['cynamon', 4, 'g'],
      ['mąka ziemniaczana', 15, 'g'],
    ],
    steps: [
      'Zagnieć szybko mąkę pszenną, zimne masło pokrojone w kostkę, 80 g cukru pudru, jajka i proszek do pieczenia na gładkie ciasto. Podziel je na 2/3 i 1/3, owiń folią i schłódź w lodówce 30 minut.',
      'Jabłka obierz, usuń gniazda nasienne i zetrzyj na tarce o grubych oczkach.',
      'Przełóż jabłka do garnka, dodaj cukier i cynamon, duś 10 minut, aż zmiękną i puszczą sok. Odlej nadmiar soku, wmieszaj mąkę ziemniaczaną i ostudź.',
      'Większą część ciasta rozwałkuj lub rozpłaszcz dłońmi na dnie blachy 20×30 cm wyłożonej papierem, nakłuj widelcem i podpiecz 15 minut w 180°C (góra-dół).',
      'Rozłóż jabłka na podpieczonym spodzie, a pozostałe ciasto zetrzyj na wierzch na tarce o grubych oczkach.',
      'Piecz 45–50 minut w 180°C, aż wierzch będzie złocisty. Ostudź co najmniej 20 minut, żeby jabłka stężały.',
      'Pokrój na kwadraty i podawaj lekko ciepłą, oprószoną resztą cukru pudru.',
    ],
    photo:
      'Square slice of apple pie with golden grated shortcrust top dusted with powdered sugar and a thick layer of cinnamon apples',
    vessel: 'board',
  },
  {
    plan: 'de-2',
    title: 'Sernik na zimno z truskawkami',
    description:
      'Puszysty sernik bez pieczenia na maślanym spodzie z herbatników, przykryty truskawkami w galaretce. Lekki i orzeźwiający, idealny na ciepłe dni i przyjęcia w ogrodzie.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 300,
    servings: 8,
    ingredients: [
      ['herbatnik', 150, 'g'],
      ['masło', 70, 'g'],
      ['ser twaróg półtłusty', 750, 'g'],
      ['śmietanka 30', 200, 'ml'],
      ['cukier puder', 100, 'g'],
      ['żelatyna', 20, 'g'],

      ['truskawka', 400, 'g'],
      ['galaretka', 75, 'g'],
    ],
    steps: [
      'Herbatniki pokrusz na drobny piasek, wymieszaj z roztopionym masłem i ubij na dnie tortownicy o średnicy 24 cm. Wstaw do lodówki.',
      'Żelatynę zalej 100 ml zimnej wody na 5 minut, potem podgrzej, mieszając, aż się rozpuści (nie gotuj). Przestudź.',
      'Twaróg zmiel dwukrotnie albo zmiksuj z cukrem pudrem na gładką masę. Śmietankę ubij na sztywno.',
      'Do twarogu wlej cienkim strumieniem żelatynę, stale miksując, a potem delikatnie wmieszaj bitą śmietankę. Wyłóż masę na spód, wyrównaj i schłódź 1 godzinę.',
      'Galaretkę rozpuść w 350 ml gorącej wody i ostudź, aż zacznie gęstnieć. Truskawki umyj, odszypułkuj i przekrój na połówki.',
      'Ułóż truskawki na stężałej masie i zalej je tężejącą galaretką. Chłodź sernik co najmniej 4 godziny, najlepiej całą noc.',
      'Obejdź brzeg tortownicy nożem, zdejmij obręcz i podawaj schłodzony, krojąc nożem maczanym w gorącej wodzie.',
    ],
    photo:
      'Slice of no-bake cheesecake with biscuit crumb base, white creamy layer and glossy strawberry halves set in red jelly on top',
  },
  {
    plan: 'de-3',
    title: 'Sernik klasyczny na kruchym spodzie',
    description:
      'Domowy sernik pieczony z mielonego twarogu, gęsty i wilgotny, z nutą wanilii i cienkim kruchym spodem. Ciasto na święta i rodzinne okazje, które smakuje najlepiej na drugi dzień.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 300,
    servings: 8,
    ingredients: [
      ['mąka pszenna', 150, 'g'],
      ['masło', 130, 'g'],
      ['cukier puder', 40, 'g'],
      ['jajko', 5, 'szt'],
      ['ser twaróg półtłusty', 1000, 'g'],
      ['cukier', 180, 'g'],
      ['budyń', 40, 'g'],
      ['cukier waniliowy', 16, 'g'],
    ],
    steps: [
      'Zagnieć mąkę, 70 g zimnego masła, cukier puder i 1 jajko na kruche ciasto. Wyłóż nim dno tortownicy 24 cm, nakłuj widelcem i podpiecz 15 minut w 180°C (góra-dół).',
      'Twaróg zmiel dwukrotnie przez maszynkę albo przetrzyj przez sito, żeby masa była gładka.',
      'Utrzyj resztę miękkiego masła z cukrem i cukrem waniliowym, dodawaj po jednym pozostałe 4 jajka, a potem stopniowo twaróg i proszek budyniowy. Miksuj krótko, na niskich obrotach, tylko do połączenia.',
      'Wylej masę na podpieczony spód i wyrównaj. Zmniejsz temperaturę do 160°C.',
      'Piecz około 70 minut, aż brzegi będą ścięte, a środek lekko drżący. Wyłącz piekarnik, uchyl drzwiczki i zostaw sernik w środku na godzinę, żeby nie opadł.',
      'Ostudzony sernik chłódź w lodówce co najmniej 4 godziny, najlepiej przez noc.',
      'Kroi się go najlepiej ostrym nożem maczanym w gorącej wodzie; podawaj schłodzony, sam albo z owocami.',
    ],
    photo:
      'Tall slice of baked Polish cheesecake with pale golden top and thin shortcrust base, creamy dense white filling',
    vessel: 'board',
  },
  {
    plan: 'de-4',
    title: 'Brownie z gorzką czekoladą',
    description:
      'Mocno czekoladowe brownie z chrupiącą, popękaną skórką i wilgotnym, ciągnącym się środkiem. Wystarczy jedna miska i pół godziny pieczenia, a kwadraty dobrze znoszą transport.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 8,
    ingredients: [
      ['czekolada gorzka', 200, 'g'],
      ['masło', 150, 'g'],
      ['cukier', 180, 'g'],
      ['jajko', 3, 'szt'],
      ['mąka pszenna', 80, 'g'],
      ['kakao', 20, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra-dół), formę 20×20 cm wyłóż papierem do pieczenia.',
      'Połam czekoladę, dodaj masło i roztop w misce nad garnkiem z gotującą się wodą, mieszając. Odstaw na 5 minut, żeby przestygła.',
      'Jajka ubij z cukrem przez 3 minuty, aż masa zbieleje i zgęstnieje, a potem wmieszaj roztopioną czekoladę.',
      'Przesiej mąkę, kakao i sól, wmieszaj szpatułką tylko do połączenia składników.',
      'Przelej masę do formy i piecz 22–25 minut. Patyczek wbity w środek ma wyjść z wilgotnymi okruchami, a nie czysty.',
      'Ostudź brownie w formie co najmniej 20 minut, pokrój na 8 kawałków i podawaj.',
    ],
    photo:
      'Fudgy dark chocolate brownie squares with crackly shiny top stacked on parchment paper',
    vessel: 'board',
  },
  {
    plan: 'de-5',
    title: 'Ciasto marchewkowe z kremem serowym',
    description:
      'Wilgotne ciasto z tartą marchewką, orzechami i cynamonem, przykryte gładkim kremem z serka. Korzenne i niezbyt słodkie, świetnie trzyma świeżość przez kilka dni w lodówce.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 8,
    ingredients: [
      ['marchew', 300, 'g'],
      ['mąka pszenna', 250, 'g'],
      ['cukier brązowy', 150, 'g'],
      ['olej rzepakowy', 150, 'ml'],
      ['jajko', 3, 'szt'],
      ['proszek do pieczenia', 8, 'g'],
      ['soda oczyszczona', 5, 'g'],
      ['cynamon', 5, 'g'],
      ['orzech włoski', 60, 'g'],
      ['serek kremowy', 180, 'g'],
      ['cukier puder', 50, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 175°C (góra-dół), keksówkę lub formę 20×20 cm wyłóż papierem.',
      'Marchew obierz i zetrzyj na tarce o drobnych oczkach. Orzechy posiekaj, kilka zostaw do dekoracji.',
      'Jajka ubij z cukrem brązowym na puszystą masę, wlej cienkim strumieniem olej i dalej miksuj.',
      'Wymieszaj mąkę, proszek do pieczenia, sodę i cynamon, dodaj do masy i wymieszaj łyżką. Na koniec wmieszaj marchew i orzechy.',
      'Przelej ciasto do formy i piecz 45–50 minut, do suchego patyczka. Ostudź całkowicie na kratce.',
      'Serek kremowy utrzyj z cukrem pudrem na gładki krem, rozsmaruj na wierzchu ostudzonego ciasta.',
      'Posyp resztą orzechów, pokrój i podawaj od razu albo po schłodzeniu.',
    ],
    photo:
      'Moist carrot cake slice with visible orange flecks, thick white cream cheese frosting and chopped walnuts on top',
    vessel: 'board',
  },
  {
    plan: 'de-6',
    title: 'Ciasto ucierane ze śliwkami',
    description:
      'Maślane ciasto ucierane z połówkami węgierek, które w piekarniku zapadają się i puszczają kwaskowy sok. Sezonowy klasyk z końca lata, prosty i zawsze udany.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 80,
    servings: 8,
    ingredients: [
      ['masło', 200, 'g'],
      ['cukier', 180, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['jajko', 4, 'szt'],
      ['mąka pszenna', 280, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['śliwka', 600, 'g'],
      ['cukier puder', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra-dół), blachę 20×30 cm wyłóż papierem. Śliwki umyj, przekrój na połówki i usuń pestki.',
      'Miękkie masło utrzyj z cukrem i cukrem waniliowym na puszystą, jasną masę (około 5 minut).',
      'Dodawaj po jednym jajku, za każdym razem miksując do połączenia.',
      'Wmieszaj mąkę przesianą z proszkiem do pieczenia, krótko, tylko do połączenia. Rozsmaruj ciasto w blasze.',
      'Ułóż śliwki gęsto skórką do dołu, lekko je wciskając w ciasto.',
      'Piecz 45–50 minut, aż ciasto między śliwkami będzie złote, a patyczek suchy.',
      'Ostudź, oprósz cukrem pudrem i podawaj pokrojone w kwadraty.',
    ],
    photo:
      'Golden butter sponge cake studded with sunken purple plum halves, dusted with powdered sugar, cut into squares',
    vessel: 'board',
  },
  {
    plan: 'de-7',
    title: 'Murzynek z polewą czekoladową',
    description:
      'Wilgotne ciasto kakaowe z PRL-owskiego zeszytu z przepisami, polane lśniącą polewą z tej samej masy. Proste, tanie i zawsze znika jako pierwsze z talerza.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 8,
    ingredients: [
      ['masło', 200, 'g'],
      ['cukier', 220, 'g'],
      ['kakao', 40, 'g'],
      ['mleko', 120, 'ml'],
      ['jajko', 4, 'szt'],
      ['mąka pszenna', 280, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['cukier waniliowy', 16, 'g'],
    ],
    steps: [
      'W garnku podgrzej masło, cukier, cukier waniliowy, kakao i mleko, mieszając, aż cukier się rozpuści i powstanie gładka polewa. Odlej 1/3 masy na polewę, resztę ostudź.',
      'Nagrzej piekarnik do 180°C (góra-dół), keksówkę 30 cm wyłóż papierem.',
      'Jajka rozdziel. Do ostudzonej masy kakaowej dodaj żółtka i wymieszaj, a potem wsyp mąkę przesianą z proszkiem do pieczenia.',
      'Białka ubij na sztywno i delikatnie wmieszaj do ciasta szpatułką.',
      'Przelej ciasto do formy i piecz 40–45 minut, do suchego patyczka. Ostudź w formie.',
      'Podgrzej odlaną polewę, jeśli zgęstniała, polej nią ostudzone ciasto i odstaw, aż stężeje.',
      'Pokrój na grube kromki i podawaj do kawy lub szklanki mleka.',
    ],
    photo:
      'Slices of dark cocoa loaf cake with thick glossy chocolate glaze dripping on the sides',
    vessel: 'board',
  },
  {
    plan: 'de-8',
    title: 'Babka marmurkowa',
    description:
      'Puszysta babka piaskowa z jasno-kakaowym marmurkowym wzorem, pieczona w formie z kominem. Ciasto do kawy, które długo zostaje świeże i ładnie wygląda po przekrojeniu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 80,
    servings: 8,
    ingredients: [
      ['masło', 200, 'g'],
      ['cukier', 200, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['jajko', 4, 'szt'],
      ['mąka pszenna', 200, 'g'],
      ['mąka ziemniaczana', 100, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['mleko', 60, 'ml'],
      ['kakao', 20, 'g'],
      ['cukier puder', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 175°C (góra-dół). Formę do babki z kominem wysmaruj masłem i oprósz mąką.',
      'Miękkie masło utrzyj z cukrem i cukrem waniliowym na puszysto, potem dodawaj po jednym jajku.',
      'Obie mąki przesiej z proszkiem do pieczenia i wmieszaj do masy na zmianę z 40 ml mleka.',
      'Odłóż 1/3 ciasta do drugiej miski i wmieszaj do niej kakao oraz resztę mleka.',
      'Do formy nakładaj na zmianę łyżką jasne i ciemne ciasto, a potem przeciągnij przez nie widelcem kilka spiral, żeby powstał marmurek.',
      'Piecz 50–55 minut, do suchego patyczka. Odstaw na 10 minut i wyjmij z formy na kratkę.',
      'Ostudzoną babkę oprósz cukrem pudrem i podawaj pokrojoną w plastry.',
    ],
    photo:
      'Bundt marble cake with swirls of vanilla and cocoa sponge visible in a cut slice, dusted with powdered sugar',
    vessel: 'board',
  },
  {
    plan: 'de-9',
    title: 'Tiramisu',
    description:
      'Włoski deser z biszkoptów nasączonych kawą, przełożonych puszystym kremem z mascarpone i oprószonych kakao. Krem bez surowych jajek, robi się go bez pieczenia, a po nocy w lodówce smakuje najlepiej.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 270,
    servings: 6,
    ingredients: [
      ['kawa rozpuszczalna', 8, 'g'],

      ['ser mascarpone', 350, 'g'],
      ['śmietanka 30', 200, 'ml'],
      ['cukier puder', 60, 'g'],
      ['biszkopt', 180, 'g'],
      ['kakao', 10, 'g'],
    ],
    steps: [
      'Kawę rozpuść we wrzącej wodzie (250 ml) i całkowicie ostudź.',
      'Schłodzoną śmietankę ubij z cukrem pudrem na sztywno.',
      'Dodaj zimny mascarpone i miksuj na niskich obrotach tylko do połączenia, aż krem będzie gładki i gęsty — dłuższe miksowanie może go zważyć.',
      'Biszkopty maczaj krótko w kawie (sekunda na stronę) i ułóż warstwę na dnie naczynia 20×25 cm. Przykryj połową kremu, ułóż drugą warstwę biszkoptów i resztę kremu.',
      'Przykryj folią i chłódź co najmniej 4 godziny, najlepiej przez noc.',
      'Tuż przed podaniem oprósz obficie kakao przez sitko i nakładaj porcje łopatką.',
    ],
    photo:
      'Square portion of tiramisu with visible layers of coffee-soaked ladyfingers and mascarpone cream, heavily dusted with cocoa powder',
  },
  {
    plan: 'de-10',
    title: 'Panna cotta z musem malinowym',
    description:
      'Gładki, waniliowy krem ze śmietanki, który delikatnie drży na łyżce, polany kwaskowym musem z malin. Elegancki deser na przyjęcie, który przygotujesz dzień wcześniej.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 270,
    servings: 4,
    ingredients: [
      ['żelatyna', 10, 'g'],
      ['śmietanka 30', 400, 'ml'],
      ['mleko', 100, 'ml'],
      ['cukier', 50, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['malina mrożona', 250, 'g'],
      ['cukier puder', 20, 'g'],
    ],
    steps: [
      'Żelatynę zalej 3 łyżkami zimnego mleka i odstaw na 5 minut do napęcznienia.',
      'W garnku podgrzej śmietankę z resztą mleka, cukrem i cukrem waniliowym prawie do wrzenia, mieszając, aż cukier się rozpuści.',
      'Zdejmij z ognia, dodaj napęczniałą żelatynę i mieszaj, aż całkowicie się rozpuści.',
      'Rozlej masę do 4 szklanek lub kokilek, ostudź i chłódź co najmniej 4 godziny, aż stężeje.',
      'Maliny rozmroź, zmiksuj z cukrem pudrem i przetrzyj przez sito, żeby pozbyć się pestek.',
      'Przed podaniem polej każdą panna cottę musem malinowym i podawaj schłodzoną.',
    ],
    photo:
      'White vanilla panna cotta in a glass topped with a bright red raspberry coulis layer',
    vessel: 'bowl',
  },
  {
    plan: 'de-11',
    title: 'Pieczone jabłka z cynamonem i orzechami',
    description:
      'Całe jabłka pieczone z nadzieniem z orzechów, rodzynek i miodu, miękkie i pachnące cynamonem. Jesienny deser prawie bez pracy, świetny z łyżką gęstego jogurtu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 4,
    ingredients: [
      ['jabłko', 4, 'szt'],
      ['orzech włoski', 40, 'g'],
      ['rodzynka', 30, 'g'],
      ['miód', 30, 'g'],
      ['masło', 20, 'g'],
      ['cynamon', 3, 'g'],
      ['jogurt grecki', 100, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra-dół). Jabłka umyj, odetnij wierzch jako „czapeczkę” i wydrąż gniazda nasienne łyżeczką, nie przebijając dna.',
      'Orzechy posiekaj, wymieszaj z rodzynkami, miodem i cynamonem.',
      'Napełnij jabłka farszem, na każde połóż kawałek masła i przykryj czapeczką.',
      'Ułóż jabłka w naczyniu żaroodpornym, podlej 3 łyżkami wody i piecz 30–35 minut, aż skórka zacznie pękać, a miąższ będzie miękki.',
      'Podawaj ciepłe, polane sosem z dna naczynia, z łyżką jogurtu greckiego.',
    ],
    photo:
      'Whole baked red apple with wrinkled skin, filled with walnuts and raisins in honey, with a dollop of Greek yogurt beside it',
  },
  {
    plan: 'de-12',
    title: 'Crumble jabłkowe z owsianą kruszonką',
    description:
      'Soczyste jabłka z cynamonem pod grubą, chrupiącą kruszonką z masła, mąki i płatków owsianych. Rozgrzewający deser z jednego naczynia, gotowy w niecałą godzinę.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 4,
    ingredients: [
      ['jabłko', 600, 'g'],
      ['cytryna', 20, 'g'],
      ['cukier brązowy', 60, 'g'],
      ['cynamon', 3, 'g'],
      ['mąka pszenna', 80, 'g'],
      ['płatki owsiane', 50, 'g'],
      ['masło', 80, 'g'],
      ['jogurt grecki', 120, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra-dół). Jabłka obierz, usuń gniazda i pokrój w kostkę 1,5 cm.',
      'Wymieszaj jabłka z sokiem z cytryny, 20 g cukru brązowego i cynamonem, przełóż do naczynia żaroodpornego około 20×20 cm.',
      'W misce połącz mąkę, płatki owsiane i resztę cukru, dodaj zimne masło w kostce i rozcieraj palcami, aż powstaną grudki kruszonki.',
      'Rozsyp kruszonkę równo na jabłkach.',
      'Piecz 30–35 minut, aż kruszonka będzie złota, a sok z jabłek zacznie bulgotać na brzegach.',
      'Odstaw na 5 minut i podawaj ciepłe, z łyżką jogurtu greckiego.',
    ],
    photo:
      'Apple crumble in a ceramic baking dish with golden oat crumb topping and bubbling apple juices at the edges, spoon of Greek yogurt on top',
    vessel: 'bowl',
  },
  {
    plan: 'de-13',
    title: 'Chlebek bananowy z orzechami',
    description:
      'Wilgotna keksówka z bardzo dojrzałych bananów, lekko karmelowa, z chrupiącymi kawałkami orzechów. Dobry sposób na brązowiejące owoce, a kromka sprawdzi się też w pudełku do pracy.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 8,
    ingredients: [
      ['banan', 3, 'szt'],
      ['masło', 80, 'g'],
      ['cukier brązowy', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 220, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['soda oczyszczona', 3, 'g'],
      ['cynamon', 3, 'g'],
      ['sól', 1, 'g'],
      ['orzech włoski', 50, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 175°C (góra-dół), keksówkę około 25 cm wyłóż papierem. Masło roztop i przestudź.',
      'Banany rozgnieć widelcem na gładkie purée, dodaj cukier brązowy, jajka i roztopione masło, wymieszaj trzepaczką.',
      'W drugiej misce połącz mąkę, proszek do pieczenia, sodę, cynamon i sól, wsyp do mokrych składników i wymieszaj łyżką tylko do połączenia.',
      'Orzechy posiekaj grubo i wmieszaj do ciasta, garść zostaw na wierzch.',
      'Przelej ciasto do formy, posyp orzechami i piecz 50–55 minut, do suchego patyczka. Jeśli wierzch za szybko się rumieni, przykryj go folią.',
      'Ostudź w formie 15 minut, wyjmij na kratkę i podawaj pokrojony w grube kromki.',
    ],
    photo:
      'Sliced banana bread loaf with dark caramelized crust and walnut pieces on top, moist crumb visible',
    vessel: 'board',
  },
  {
    plan: 'de-14',
    title: 'Ciasteczka owsiane z rodzynkami',
    description:
      'Chrupiące na brzegach, miękkie w środku ciasteczka z płatków owsianych z rodzynkami i cynamonem. Gotowe w pół godziny, dobrze znoszą przechowywanie w puszce przez tydzień.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 8,
    ingredients: [
      ['masło', 120, 'g'],
      ['cukier brązowy', 100, 'g'],
      ['jajko', 1, 'szt'],
      ['płatki owsiane', 200, 'g'],
      ['mąka pszenna', 100, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['cynamon', 3, 'g'],
      ['sól', 1, 'g'],
      ['rodzynka', 60, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra-dół), dwie blachy wyłóż papierem.',
      'Miękkie masło utrzyj z cukrem brązowym, dodaj jajko i miksuj do połączenia.',
      'Wsyp płatki owsiane, mąkę, proszek do pieczenia, cynamon i sól, wymieszaj łyżką. Na koniec wmieszaj rodzynki.',
      'Formuj kulki wielkości orzecha włoskiego (około 24 sztuki), układaj z odstępami i spłaszcz dłonią na grubość 1 cm.',
      'Piecz 12–14 minut, aż brzegi będą złote, a środek jeszcze miękki — stężeje po wystudzeniu.',
      'Ostudź na blasze 5 minut, przełóż na kratkę i podawaj po 3 ciasteczka na porcję.',
    ],
    photo:
      'Stack of golden oatmeal cookies with raisins and rough oat texture on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'de-15',
    title: 'Ciastka z kawałkami czekolady',
    description:
      'Duże, maślane ciastka w stylu amerykańskim, chrupiące na brzegach i ciągnące się w środku, z grubymi kawałkami gorzkiej czekolady. Najlepsze jeszcze lekko ciepłe, do szklanki mleka.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 8,
    ingredients: [
      ['masło', 125, 'g'],
      ['cukier brązowy', 120, 'g'],
      ['cukier', 50, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 250, 'g'],
      ['soda oczyszczona', 3, 'g'],
      ['sól', 2, 'g'],
      ['czekolada gorzka', 150, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra-dół), dwie blachy wyłóż papierem. Czekoladę posiekaj nożem na kawałki wielkości groszku.',
      'Roztopione i lekko przestudzone masło wymieszaj z oboma cukrami i cukrem waniliowym, dodaj jajko i ubij trzepaczką na gładką masę.',
      'Wsyp mąkę, sodę i sól, wymieszaj łyżką, a na koniec wmieszaj czekoladę.',
      'Formuj kulki po około 40 g (16 sztuk) i układaj na blachach w dużych odstępach, bo ciastka się rozpłyną.',
      'Piecz 10–12 minut, aż brzegi się zezłocą, a środek będzie jeszcze blady i miękki.',
      'Zostaw na blasze 5 minut, przełóż na kratkę i podawaj po 2 ciastka na porcję.',
    ],
    photo:
      'Large chewy chocolate chip cookies with golden edges and melted dark chocolate chunks, one broken in half',
    vessel: 'board',
  },
  {
    plan: 'de-16',
    title: 'Domowy kisiel z wiśniami i truskawkami',
    description:
      'Prawdziwy kisiel z owoców zagęszczony mąką ziemniaczaną, bez torebki i sztucznych aromatów. Gęsty, kwaskowo-słodki, dobry na ciepło w chłodne popołudnie i schłodzony latem.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['wiśnia mrożona', 150, 'g'],
      ['truskawka mrożona', 150, 'g'],

      ['cukier', 50, 'g'],
      ['mąka ziemniaczana', 30, 'g'],
    ],
    steps: [
      'Wiśnie i truskawki wrzuć do garnka z 400 ml wody i cukrem, zagotuj i gotuj 5 minut, aż owoce zmiękną. Większe truskawki rozgnieć łyżką.',
      'Mąkę ziemniaczaną rozmieszaj dokładnie w pozostałych 100 ml zimnej wody, bez grudek.',
      'Zmniejsz ogień i wlewaj zawiesinę cienkim strumieniem do owoców, cały czas energicznie mieszając.',
      'Doprowadź do wrzenia i gotuj jeszcze minutę, aż kisiel zgęstnieje i stanie się przejrzysty.',
      'Rozlej do miseczek i podawaj ciepły albo schłodzony.',
    ],
    photo:
      'Glass bowl of thick glossy deep red fruit kisiel with whole cherries and strawberry pieces',
    vessel: 'bowl',
  },
  {
    plan: 'de-17',
    title: 'Lody bananowe z kakao i masłem orzechowym',
    description:
      'Kremowe lody z samych zamrożonych bananów, zmiksowanych z kakao i masłem orzechowym, bez maszyny i bez śmietanki. Konsystencja miękkich lodów, słodycz wyłącznie z owoców.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 250,
    servings: 2,
    ingredients: [
      ['banan', 3, 'szt'],
      ['kakao', 10, 'g'],
      ['masło orzechowe', 30, 'g'],
      ['mleko', 40, 'ml'],
    ],
    steps: [
      'Dojrzałe banany obierz, pokrój w plasterki grubości 1 cm, rozłóż na talerzu i zamroź na co najmniej 4 godziny.',
      'Zamrożone plasterki przełóż do blendera kielichowego lub malaksera, dodaj kakao i 20 g masła orzechowego.',
      'Miksuj, dolewając stopniowo mleko i zgarniając masę ze ścianek, aż powstanie gładki, kremowy krem o konsystencji lodów (2–3 minuty).',
      'Jeśli wolisz twardsze lody, przełóż masę do pojemnika i zamroź jeszcze na 30 minut.',
      'Nakładaj gałki do miseczek, polej resztą masła orzechowego i podawaj od razu.',
    ],
    photo:
      'Scoops of creamy chocolate banana nice cream in a bowl drizzled with peanut butter',
    vessel: 'bowl',
  },
  {
    plan: 'de-18',
    title: 'Kokosanki',
    description:
      'Małe ciasteczka z wiórków kokosowych i ubitych białek, chrupiące z wierzchu, a w środku wilgotne i ciągnące. Tylko trzy składniki i dobry sposób na wykorzystanie białek.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 6,
    ingredients: [
      ['jajko', 3, 'szt'],
      ['sól', 1, 'g'],
      ['cukier', 130, 'g'],
      ['wiórki kokosowe', 200, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 160°C (góra-dół), blachę wyłóż papierem. Oddziel białka od żółtek (żółtka wykorzystaj np. do budyniu lub kremu).',
      'Białka ubij ze szczyptą soli na sztywno, a potem dodawaj po łyżce cukier, miksując, aż piana będzie lśniąca.',
      'Wsyp wiórki kokosowe i delikatnie wmieszaj je szpatułką.',
      'Zwilżonymi dłońmi lub dwiema łyżeczkami formuj małe kopczyki (około 18 sztuk) i układaj je na blasze z odstępami.',
      'Piecz 18–20 minut, aż czubki i spody lekko się zezłocą.',
      'Ostudź na blasze, żeby stężały, i podawaj po 3 sztuki na porcję.',
    ],
    photo:
      'Small golden-tipped coconut macaroon mounds on parchment paper, rough shredded coconut texture',
    vessel: 'board',
  },
  {
    plan: 'de-19',
    title: 'Deser z galaretką, bitą śmietaną i owocami',
    description:
      'Kolorowy deser w pucharkach: warstwy truskawkowej galaretki z owocami i puszystej bitej śmietany. Ulubieniec dzieci z rodzinnych imienin, przygotowany z produktów z każdego sklepu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 180,
    servings: 4,
    ingredients: [
      ['galaretka', 75, 'g'],

      ['truskawka', 200, 'g'],
      ['banan', 1, 'szt'],
      ['śmietanka 30', 200, 'ml'],
      ['cukier puder', 20, 'g'],
    ],
    steps: [
      'Galaretkę rozpuść w 450 ml gorącej wody i ostudź do temperatury pokojowej.',
      'Truskawki pokrój w ćwiartki, banana w plasterki. Kilka kawałków truskawek odłóż do dekoracji.',
      'Rozłóż owoce do 4 szklanek lub pucharków, zalej galaretką i wstaw do lodówki na 2–2,5 godziny, aż stężeje.',
      'Schłodzoną śmietankę ubij z cukrem pudrem na sztywno.',
      'Nałóż bitą śmietanę na stężałą galaretkę, udekoruj odłożonymi truskawkami i podawaj od razu.',
    ],
    photo:
      'Glass cup with red strawberry jelly and fruit pieces at the bottom, topped with swirl of whipped cream and fresh strawberry',
    vessel: 'bowl',
  },
  {
    plan: 'de-20',
    title: 'Ciasto jogurtowe z borówkami',
    description:
      'Szybkie ciasto na jogurcie i oleju, mierzone jak u babci, z owocami zatopionymi w miękkim, wilgotnym cieście. Wyjdzie z każdymi sezonowymi owocami, a najładniej z borówkami.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 8,
    ingredients: [
      ['jajko', 3, 'szt'],
      ['cukier', 200, 'g'],
      ['jogurt naturalny', 250, 'g'],
      ['olej rzepakowy', 120, 'ml'],
      ['mąka pszenna', 300, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['borówka', 250, 'g'],
      ['cukier puder', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra-dół), blachę 20×30 cm wyłóż papierem. Borówki umyj i osusz.',
      'Jajka ubij z cukrem na jasną, puszystą masę (około 4 minut).',
      'Zmniejsz obroty, dodaj jogurt i olej, a potem mąkę przesianą z proszkiem do pieczenia. Miksuj tylko do połączenia.',
      'Przelej ciasto do blachy i rozsyp na wierzchu borówki.',
      'Piecz 40–45 minut, aż ciasto będzie złote, a patyczek suchy.',
      'Ostudź, oprósz cukrem pudrem i podawaj pokrojone w kwadraty.',
    ],
    photo:
      'Squares of fluffy yogurt sponge cake studded with blueberries, dusted with powdered sugar',
    vessel: 'board',
  },
  {
    plan: 'de-21',
    title: 'Sernik baskijski',
    description:
      'Hiszpański sernik bez spodu z celowo przypaloną, karmelową skórką i kremowym, niemal płynnym środkiem. Pięć składników, jedna miska i efekt jak z kawiarni.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 300,
    servings: 8,
    ingredients: [
      ['serek kremowy', 800, 'g'],
      ['cukier', 200, 'g'],
      ['jajko', 4, 'szt'],
      ['śmietanka 30', 250, 'ml'],
      ['mąka pszenna', 20, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C (góra-dół). Tortownicę 22 cm wyłóż dwoma pogniecionymi arkuszami papieru do pieczenia tak, żeby wystawały ponad brzeg.',
      'Serek kremowy w temperaturze pokojowej zmiksuj z cukrem na gładką masę.',
      'Dodawaj po jednym jajku, miksując na niskich obrotach, a potem wlej śmietankę i wsyp przesianą mąkę.',
      'Przelej masę do formy i piecz 30–35 minut, aż wierzch będzie ciemnobrązowy, niemal przypalony, a środek wyraźnie falujący przy potrząśnięciu.',
      'Ostudź sernik w formie w temperaturze pokojowej (około godziny), potem chłódź co najmniej 4 godziny.',
      'Wyjmij razem z papierem i podawaj w klinach, najlepiej 20 minut po wyjęciu z lodówki.',
    ],
    photo:
      'Wedge of Basque burnt cheesecake with dark caramelized top and creamy pale center, rustic parchment edges',
    vessel: 'board',
  },
  {
    plan: 'de-22',
    title: 'Ciasto z rabarbarem i kruszonką',
    description:
      'Maślane ciasto ucierane z kwaskowym rabarbarem i grubą warstwą chrupiącej kruszonki. Wiosenny klasyk z działki, w którym słodycz ciasta równoważy ostry smak łodyg.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 85,
    servings: 8,
    ingredients: [
      ['masło', 175, 'g'],
      ['cukier', 200, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['jajko', 3, 'szt'],
      ['jogurt naturalny', 100, 'g'],
      ['mąka pszenna', 330, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['rabarbar', 500, 'g'],
    ],
    steps: [
      'Przygotuj kruszonkę: 80 g mąki, 50 g zimnego masła i 50 g cukru rozcieraj palcami na grudki i wstaw do lodówki.',
      'Rabarbar umyj, obierz grubsze łodygi z włókien i pokrój w kawałki 1,5 cm. Nagrzej piekarnik do 180°C (góra-dół), blachę 20×30 cm wyłóż papierem.',
      'Resztę miękkiego masła utrzyj z resztą cukru i cukrem waniliowym, dodawaj po jednym jajku, a potem jogurt.',
      'Wmieszaj pozostałą mąkę przesianą z proszkiem do pieczenia i rozsmaruj ciasto w blasze.',
      'Rozłóż równo rabarbar i posyp go kruszonką.',
      'Piecz 45–50 minut, aż kruszonka będzie złota, a patyczek wbity w ciasto suchy.',
      'Ostudź w blasze i podawaj pokrojone w kwadraty.',
    ],
    photo:
      'Square slice of rhubarb cake with pink rhubarb pieces and thick golden crumble topping',
    vessel: 'board',
  },
  {
    plan: 'de-23',
    title: 'Czekoladowe ciasto z kubka',
    description:
      'Wilgotne ciasto czekoladowe pieczone w kubku w mikrofalówce z kawałkami czekolady, które roztapiają się w środku. Deser na nagłą ochotę na słodkie, gotowy w 10 minut.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 60, 'g'],
      ['kakao', 20, 'g'],
      ['cukier', 40, 'g'],
      ['proszek do pieczenia', 2, 'g'],
      ['jajko', 1, 'szt'],
      ['mleko', 60, 'ml'],
      ['olej rzepakowy', 30, 'ml'],
      ['czekolada gorzka', 20, 'g'],
    ],
    steps: [
      'W misce wymieszaj mąkę, kakao, cukier i proszek do pieczenia.',
      'Dodaj jajko, mleko i olej, wymieszaj widelcem na gładkie, gęste ciasto bez grudek.',
      'Rozdziel ciasto do dwóch dużych kubków (co najmniej 300 ml), wypełniając je najwyżej do połowy. W środek każdego wciśnij kilka kostek czekolady.',
      'Piecz każdy kubek osobno w mikrofalówce 70–90 sekund przy 800 W, aż ciasto wyrośnie, a wierzch będzie suchy, ale sprężysty.',
      'Odstaw na minutę, bo kubek jest gorący, i jedz łyżeczką prosto z kubka, póki czekolada w środku jest płynna.',
    ],
    photo:
      'Chocolate mug cake risen above the rim of a white mug, with melted dark chocolate in the center',
    vessel: 'plate',
  },
  {
    plan: 'de-24',
    title: 'Muffinki czekoladowe',
    description:
      'Puszyste, mocno kakaowe muffinki z kawałkami gorzkiej czekolady w środku i na wierzchu. Robi się je metodą dwóch misek, bez miksera, a świetnie nadają się do szkolnego pudełka.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 8,
    ingredients: [
      ['mąka pszenna', 180, 'g'],
      ['kakao', 30, 'g'],
      ['cukier', 120, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['soda oczyszczona', 2, 'g'],
      ['sól', 1, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 150, 'ml'],
      ['olej rzepakowy', 90, 'ml'],
      ['czekolada gorzka', 80, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra-dół), 8 wgłębień formy do muffinek wyłóż papilotkami. Czekoladę posiekaj na kawałki.',
      'W dużej misce wymieszaj mąkę, kakao, cukier, proszek do pieczenia, sodę i sól.',
      'W drugiej misce roztrzep jajka z mlekiem i olejem.',
      'Wlej mokre składniki do suchych i wymieszaj łyżką tylko do połączenia — grudki są w porządku. Wmieszaj 2/3 czekolady.',
      'Nałóż ciasto do papilotek do 3/4 wysokości, posyp resztą czekolady.',
      'Piecz 20–22 minuty, do suchego patyczka. Ostudź na kratce i podawaj po jednej muffince.',
    ],
    photo:
      'Dark chocolate muffins in paper cases with domed tops studded with melted chocolate chunks',
    vessel: 'board',
  },
  {
    plan: 'de-25',
    title: 'Blok czekoladowy z herbatnikami i orzechami',
    description:
      'Kultowy deser z czasów PRL-u: zastygnięta masa z mleka w proszku, kakao i masła z kawałkami herbatników, orzechów i rodzynek. Bez pieczenia, słodki i konkretny, kroi się go w cienkie plastry.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 270,
    servings: 8,
    ingredients: [
      ['masło', 150, 'g'],
      ['cukier', 120, 'g'],
      ['mleko', 80, 'ml'],
      ['kakao', 25, 'g'],
      ['mleko w proszku', 250, 'g'],
      ['herbatnik', 100, 'g'],
      ['orzech laskowy', 50, 'g'],
      ['rodzynka', 50, 'g'],
    ],
    steps: [
      'Keksówkę około 25 cm wyłóż folią spożywczą lub papierem. Herbatniki połam na kawałki wielkości 1–2 cm, orzechy przekrój na połówki.',
      'W garnku podgrzej masło, cukier i mleko, mieszając, aż cukier całkowicie się rozpuści. Zagotuj i zdejmij z ognia.',
      'Wsyp kakao i wymieszaj, a potem stopniowo dodawaj mleko w proszku, ucierając łyżką na gładką, gęstą masę bez grudek.',
      'Wmieszaj herbatniki, orzechy i rodzynki.',
      'Przełóż masę do formy, mocno dociśnij i wyrównaj. Ostudź i chłódź co najmniej 4 godziny, aż całkiem stężeje.',
      'Wyjmij blok z formy, zdejmij folię i podawaj pokrojony w plastry grubości 1,5 cm.',
    ],
    photo:
      'Slices of chocolate block fudge showing pieces of biscuits, hazelnuts and raisins in dark cocoa mass',
    vessel: 'board',
  },
  {
    plan: 'de-26',
    title: 'Ciasto na herbatnikach z budyniem i bitą śmietaną',
    description:
      'Popularne ciasto bez pieczenia: dwie warstwy herbatników przełożone budyniowym kremem na maśle i przykryte bitą śmietaną. Szybkie do zrobienia, a efektowne na rodzinne spotkania.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 280,
    servings: 8,
    ingredients: [
      ['herbatnik', 200, 'g'],
      ['mleko', 750, 'ml'],
      ['budyń', 80, 'g'],
      ['cukier', 80, 'g'],
      ['masło', 100, 'g'],
      ['śmietanka 30', 250, 'ml'],
      ['cukier puder', 20, 'g'],
      ['kakao', 5, 'g'],
    ],
    steps: [
      'Dno blachy 20×30 cm wyłóż papierem i ułóż na nim ciasno połowę herbatników.',
      'Z 150 ml mleka rozmieszaj proszek budyniowy. Resztę mleka zagotuj z cukrem, wlej zawiesinę i gotuj, mieszając, aż budyń zgęstnieje (około minuty). Przykryj folią przy powierzchni i ostudź.',
      'Miękkie masło utrzyj na puszysto, a potem dodawaj po łyżce ostudzony budyń, miksując na gładki krem. Oba składniki muszą mieć tę samą temperaturę, żeby krem się nie zważył.',
      'Wyłóż połowę kremu na herbatniki, przykryj drugą warstwą herbatników i resztą kremu.',
      'Schłodzoną śmietankę ubij z cukrem pudrem na sztywno i rozsmaruj na wierzchu.',
      'Chłódź ciasto co najmniej 4 godziny, żeby herbatniki zmiękły.',
      'Przed podaniem oprósz kakao przez sitko i pokrój ostrym nożem na kwadraty.',
    ],
    photo:
      'Square slice of no-bake layered cake with biscuit layers, yellow vanilla custard cream and whipped cream top dusted with cocoa',
    vessel: 'board',
  },
  {
    plan: 'de-27',
    title: 'Rogaliki twarogowe z dżemem',
    description:
      'Kruche, maślane rogaliki z ciasta na twarogu, zwinięte z łyżeczką dżemu i oprószone cukrem pudrem. Ciastka do kawy i do pudełka, które wychodzą delikatne i lekko listkujące.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 8,
    ingredients: [
      ['mąka pszenna', 300, 'g'],
      ['masło', 200, 'g'],
      ['ser twaróg półtłusty', 250, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['cukier puder', 50, 'g'],
      ['dżem', 150, 'g'],
    ],
    steps: [
      'Twaróg zmiel lub rozgnieć widelcem na gładko. Mąkę wymieszaj z proszkiem do pieczenia i 20 g cukru pudru.',
      'Dodaj do mąki zimne masło w kostce i posiekaj nożem na drobną kruszonkę, potem dodaj twaróg i szybko zagnieć gładkie ciasto.',
      'Podziel ciasto na 4 części, owiń folią i schłódź w lodówce 30 minut. Nagrzej piekarnik do 180°C (góra-dół), blachy wyłóż papierem.',
      'Każdą część rozwałkuj na koło grubości 3 mm i pokrój jak tort na 8 trójkątów.',
      'Na szerszym brzegu każdego trójkąta połóż pół łyżeczki gęstego dżemu i zwiń rogalik w stronę czubka, zaginając końce w półksiężyc.',
      'Układaj rogaliki czubkiem do spodu i piecz 18–20 minut, aż będą złote na spodzie.',
      'Ostudzone rogaliki oprósz obficie resztą cukru pudru i podawaj po 4 sztuki na porcję.',
    ],
    photo:
      'Small crescent pastries dusted heavily with powdered sugar, one broken open to show red jam filling',
    vessel: 'board',
  },
  {
    plan: 'de-28',
    title: 'Wiśniowiec, czyli ciasto kakaowe z wiśniami',
    description:
      'Wilgotne ciasto kakaowe gęsto przetykane kwaśnymi wiśniami, które pięknie kontrastują z ciemnym miąższem. Z mrożonych owoców zrobisz je o każdej porze roku.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 8,
    ingredients: [
      ['wiśnia mrożona', 400, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['jajko', 4, 'szt'],
      ['cukier', 180, 'g'],
      ['olej rzepakowy', 120, 'ml'],
      ['mleko', 120, 'ml'],
      ['mąka pszenna', 250, 'g'],
      ['kakao', 30, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['cukier puder', 10, 'g'],
    ],
    steps: [
      'Wiśnie rozmroź na sicie i dobrze odsącz z soku, a potem obtocz w mące ziemniaczanej, żeby nie opadły na dno.',
      'Nagrzej piekarnik do 180°C (góra-dół), blachę 20×30 cm wyłóż papierem.',
      'Jajka ubij z cukrem na jasną, puszystą masę. Na niższych obrotach wlej olej i mleko.',
      'Mąkę pszenną przesiej z kakao i proszkiem do pieczenia, dodaj do masy i wymieszaj tylko do połączenia.',
      'Przelej ciasto do blachy i rozsyp równo wiśnie.',
      'Piecz 40–45 minut, do suchego patyczka (sprawdzaj między owocami).',
      'Ostudź, oprósz cukrem pudrem i podawaj pokrojone w kwadraty.',
    ],
    photo:
      'Squares of dark chocolate sponge cake with deep red sour cherries visible on top, dusted with powdered sugar',
    vessel: 'board',
  },
  {
    plan: 'de-29',
    title: 'Tarta z budyniem i owocami',
    description:
      'Kruchy, maślany spód wypełniony gęstym budyniem waniliowym i obłożony świeżymi truskawkami, borówkami i kiwi. Kolorowa tarta na lato, która robi wrażenie na każdym stole.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 150,
    servings: 8,
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['masło', 100, 'g'],
      ['cukier puder', 40, 'g'],
      ['jajko', 1, 'szt'],
      ['mleko', 500, 'ml'],
      ['budyń', 40, 'g'],
      ['cukier', 50, 'g'],
      ['truskawka', 250, 'g'],
      ['borówka', 125, 'g'],
      ['kiwi', 2, 'szt'],
    ],
    steps: [
      'Zagnieć mąkę, zimne masło w kostce, cukier puder i jajko na gładkie ciasto, owiń folią i schłódź 30 minut.',
      'Rozwałkuj ciasto i wyłóż nim formę do tarty o średnicy 24 cm, nakłuj widelcem. Przykryj papierem, obciąż suchą fasolą i piecz 15 minut w 190°C (góra-dół), potem zdejmij obciążenie i piecz jeszcze 10 minut, aż się zezłoci. Ostudź.',
      'Z 100 ml mleka rozmieszaj proszek budyniowy. Resztę mleka zagotuj z cukrem, wlej zawiesinę i gotuj, mieszając, aż budyń zgęstnieje.',
      'Gorący budyń wylej na ostudzony spód, wyrównaj i przykryj folią przy powierzchni. Ostudź, a potem chłódź 1 godzinę.',
      'Truskawki przekrój na połówki, kiwi obierz i pokrój w plastry, borówki umyj i osusz.',
      'Ułóż owoce na stężałym budyniu w koła lub dowolny wzór i podawaj schłodzoną tartę pokrojoną w kawałki.',
    ],
    photo:
      'Fruit tart with golden shortcrust shell, vanilla custard filling and neat rows of strawberry halves, blueberries and kiwi slices',
    vessel: 'board',
  },
  {
    plan: 'de-30',
    title: 'Blondie z białą czekoladą',
    description:
      'Jasny kuzyn brownie: ciągnące się, karmelowe ciasto z brązowego cukru i masła z kawałkami białej czekolady. Bardzo słodkie i sycące, więc wystarczy mały kwadrat do kawy.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 8,
    ingredients: [
      ['masło', 150, 'g'],
      ['cukier brązowy', 180, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 200, 'g'],
      ['proszek do pieczenia', 3, 'g'],
      ['sól', 1, 'g'],
      ['czekolada biała', 120, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra-dół), formę 20×20 cm wyłóż papierem. Białą czekoladę posiekaj na kawałki.',
      'Masło roztop, przestudź 5 minut i wymieszaj trzepaczką z cukrem brązowym i cukrem waniliowym.',
      'Dodaj jajka i ubijaj trzepaczką minutę, aż masa będzie lśniąca.',
      'Wsyp mąkę, proszek do pieczenia i sól, wymieszaj szpatułką, a na koniec wmieszaj 3/4 czekolady.',
      'Rozłóż ciasto w formie, posyp resztą czekolady i piecz 25–28 minut, aż brzegi będą złote, a środek jeszcze lekko miękki.',
      'Ostudź w formie co najmniej 30 minut, pokrój na 8 kawałków i podawaj.',
    ],
    photo:
      'Golden blondie squares with chewy crackled top and visible white chocolate chunks, stacked on parchment',
    vessel: 'board',
  },
  {
    plan: 'de-31',
    title: 'Cynamonki drożdżowe z lukrem',
    description:
      'Miękkie bułeczki drożdżowe zwinięte ze słodkim, cynamonowym nadzieniem z masła i brązowego cukru, polane cienkim lukrem. Pachną na cały dom i najlepiej smakują jeszcze ciepłe.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 150,
    servings: 8,
    ingredients: [
      ['mleko', 215, 'ml'],
      ['drożdże', 20, 'g'],
      ['cukier', 50, 'g'],
      ['mąka pszenna', 400, 'g'],
      ['jajko', 1, 'szt'],
      ['masło', 120, 'g'],
      ['sól', 3, 'g'],
      ['cukier brązowy', 80, 'g'],
      ['cynamon', 10, 'g'],
      ['cukier puder', 60, 'g'],
    ],
    steps: [
      'W 200 ml letniego mleka rozpuść drożdże z łyżeczką cukru i odstaw na 10 minut, aż się spienią.',
      'W misce połącz mąkę, resztę cukru, sól, jajko, zaczyn i 60 g roztopionego, przestudzonego masła. Wyrabiaj 8–10 minut, aż ciasto będzie gładkie i elastyczne. Przykryj i odstaw w ciepłe miejsce na godzinę, aż podwoi objętość.',
      'Resztę miękkiego masła wymieszaj z cukrem brązowym i cynamonem na pastę.',
      'Rozwałkuj ciasto na prostokąt 30×40 cm, rozsmaruj nadzienie i zwiń ciasno wzdłuż dłuższego boku. Pokrój ostrym nożem na 8 plastrów.',
      'Ułóż cynamonki w formie 20×30 cm wyłożonej papierem, przykryj i odstaw na 30 minut do ponownego wyrośnięcia. Nagrzej piekarnik do 180°C (góra-dół).',
      'Piecz 22–25 minut, aż będą złote. Cukier puder utrzyj z 15 ml mleka na gęsty lukier.',
      'Polej lekko przestudzone cynamonki lukrem i podawaj ciepłe.',
    ],
    photo:
      'Swirled cinnamon rolls in a baking dish, golden brown with dark cinnamon spirals and drizzled white glaze',
    vessel: 'board',
  },
  {
    plan: 'de-32',
    title: 'Jabłka w cieście francuskim',
    description:
      'Połówki jabłek z cynamonowym cukrem owinięte paskami chrupiącego ciasta francuskiego i upieczone na złoto. Efektowny deser z gotowego ciasta, gotowy w pół godziny.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 4,
    ingredients: [
      ['ciasto francuskie', 275, 'g'],
      ['jabłko', 2, 'szt'],
      ['cukier', 30, 'g'],
      ['cynamon', 3, 'g'],
      ['jajko', 1, 'szt'],
      ['cukier puder', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół), blachę wyłóż papierem. Ciasto francuskie wyjmij z lodówki 10 minut wcześniej.',
      'Jabłka obierz, przekrój na połówki i wydrąż gniazda nasienne łyżeczką.',
      'Cukier wymieszaj z cynamonem, wsyp do zagłębień jabłek i obtocz w nim resztę owoców.',
      'Pokrój ciasto na paski szerokości 1,5 cm i owiń nimi każdą połówkę spiralnie, od dołu do czubka, lekko nakładając paski na siebie. Ułóż jabłka płaską stroną na blasze.',
      'Posmaruj ciasto roztrzepanym jajkiem i piecz 25 minut, aż będzie złote i wyrośnięte.',
      'Podawaj ciepłe, oprószone cukrem pudrem.',
    ],
    photo:
      'Apple halves wrapped in spiral strips of golden flaky puff pastry, dusted with powdered sugar',
  },
  {
    plan: 'de-33',
    title: 'Jogurtowe lody na patyku z owocami',
    description:
      'Domowe lody z gęstego jogurtu z miodem, przekładane zmiksowanymi truskawkami i całymi borówkami. Orzeźwiająca, mniej słodka alternatywa dla sklepowych lodów, lubiana przez dzieci.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 300,
    servings: 4,
    ingredients: [
      ['jogurt grecki', 450, 'g'],
      ['miód', 60, 'g'],
      ['truskawka', 250, 'g'],
      ['borówka', 100, 'g'],
    ],
    steps: [
      'Jogurt grecki wymieszaj z 40 g miodu na gładką masę.',
      'Truskawki odszypułkuj i zmiksuj z resztą miodu na gęsty mus.',
      'Do 8 foremek na lody (po około 100 ml) nakładaj na zmianę łyżką jogurt, mus truskawkowy i kilka borówek, a potem przeciągnij patyczkiem, żeby powstały smugi.',
      'Włóż patyczki i zamrażaj co najmniej 5 godzin, najlepiej przez noc.',
      'Przed podaniem zanurz foremki na kilka sekund w ciepłej wodzie, wyjmij lody i podawaj od razu, po 2 na porcję.',
    ],
    photo:
      'Frozen yogurt popsicles with pink strawberry swirls and whole blueberries on wooden sticks, lying on crushed ice',
    vessel: 'board',
  },
  {
    plan: 'de-34',
    title: 'Szybki piernik z polewą czekoladową',
    description:
      'Wilgotny, ciemny piernik bez leżakowania, pachnący miodem i korzenną przyprawą, oblany gorzką czekoladą. Zrobisz go w jeden wieczór, a na drugi dzień jest jeszcze lepszy.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 8,
    ingredients: [
      ['masło', 100, 'g'],
      ['miód', 100, 'g'],
      ['cukier brązowy', 150, 'g'],
      ['jajko', 3, 'szt'],
      ['mleko', 200, 'ml'],
      ['mąka pszenna', 300, 'g'],
      ['kakao', 20, 'g'],
      ['przyprawa do piernika', 20, 'g'],
      ['soda oczyszczona', 8, 'g'],
      ['czekolada gorzka', 80, 'g'],
    ],
    steps: [
      'W garnku roztop masło z miodem i cukrem brązowym, mieszając, aż cukier się rozpuści. Ostudź do letniej temperatury.',
      'Nagrzej piekarnik do 170°C (góra-dół), keksówkę 30 cm wyłóż papierem.',
      'Do przestudzonej masy dodaj jajka i mleko, wymieszaj trzepaczką.',
      'Mąkę przesiej z kakao, przyprawą do piernika i sodą, wsyp do mokrych składników i wymieszaj na gładkie, rzadkie ciasto.',
      'Przelej ciasto do formy i piecz 50–55 minut, do suchego patyczka. Ostudź na kratce.',
      'Czekoladę roztop w kąpieli wodnej i polej nią wierzch piernika, pozwalając spłynąć po bokach.',
      'Gdy polewa stężeje, pokrój piernik w kromki i podawaj do herbaty.',
    ],
    photo:
      'Dark spiced gingerbread loaf slices with a glossy dark chocolate glaze on top',
    vessel: 'board',
  },
  {
    plan: 'de-35',
    title: 'Pucharek z jogurtem, owocami i herbatnikami',
    description:
      'Warstwowy deser w szklance: gęsty jogurt z miodem, pokruszone herbatniki, maliny i banan. Zrobisz go w 10 minut bez gotowania, a herbatniki lekko miękną, dając smak jak z sernika.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['jogurt grecki', 300, 'g'],
      ['miód', 20, 'g'],
      ['herbatnik', 40, 'g'],
      ['banan', 1, 'szt'],
      ['malina', 100, 'g'],
    ],
    steps: [
      'Jogurt wymieszaj z miodem. Herbatniki pokrusz w dłoniach na grube okruchy.',
      'Banana obierz i pokrój w plasterki, maliny opłucz i osusz.',
      'Do dwóch szklanek nakładaj warstwami: okruchy herbatników, jogurt, banana i maliny, a potem powtórz warstwy.',
      'Odstaw na 5 minut, żeby herbatniki lekko zmiękły, albo schłódź do godziny.',
      'Podawaj od razu, udekorowane kilkoma malinami i okruchami herbatników na wierzchu.',
    ],
    photo:
      'Glass cup parfait with layers of white Greek yogurt, crushed biscuits, banana slices and fresh raspberries on top',
    vessel: 'bowl',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
