/**
 * Katalog 500 — Kolacje, część A (`ko-1` … `ko-31`).
 * Lista: `prisma/catalog/katalog-500-lista.md`, walidacja:
 * `pnpm exec tsx scripts/lib/katalog-500-2026-09.ts --part ko-a`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'ko-1',
    title: 'Sałatka cezar z kurczakiem',
    description:
      'Chrupiąca sałata rzymska z plastrami złocistego kurczaka, domowymi grzankami i parmezanem, polana kremowym sosem czosnkowo-cytrynowym. Syta, a lekka kolacja, którą łatwo spakować też do pracy.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['sałata rzymska', 250, 'g'],
      ['bagietka', 80, 'g'],
      ['ser parmezan', 30, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['majonez', 40, 'g'],
      ['jogurt naturalny', 40, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['musztarda', 5, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przekrój filet z kurczaka wzdłuż na dwa cieńsze płaty, natrzyj solą, pieprzem i łyżką oliwy.',
      'Smaż kurczaka na rozgrzanej patelni po 4–5 minut z każdej strony, aż sok w najgrubszym miejscu będzie przezroczysty; odstaw na 5 minut i pokrój w paski.',
      'Pokrój bagietkę w kostkę 1,5 cm, skrop resztą oliwy i podpiecz na suchej patelni 4–5 minut, mieszając, aż grzanki będą złote i chrupiące.',
      'Wymieszaj majonez z jogurtem, przeciśniętym czosnkiem, musztardą, sokiem z cytryny i połową startego parmezanu; dopraw pieprzem. Jeśli sos jest gęsty, rozrzedź go łyżką wody.',
      'Porwij umytą i osuszoną sałatę rzymską na duże kawałki i wymieszaj w misce z połową sosu.',
      'Wyłóż sałatę na talerze, ułóż na niej kurczaka i grzanki, polej resztą sosu i posyp pozostałym parmezanem.',
    ],
    photo:
      'Crisp romaine leaves topped with sliced golden grilled chicken breast, toasted bread croutons, creamy white dressing and shaved parmesan',
  },
  {
    plan: 'ko-2',
    title: 'Sałatka gyros warstwowa',
    description:
      'Imprezowa klasyka w wersji na kolację: kurczak w przyprawie gyros przełożony warstwami pekińskiej kapusty, kukurydzy, ogórka i pomidora pod sosem czosnkowym. Najlepsza po kilku godzinach w lodówce, kiedy warstwy się przegryzą.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['przyprawa do gyrosa', 8, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kapusta pekińska', 250, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['ogórek konserwowy', 100, 'g'],
      ['pomidor', 200, 'g'],
      ['papryka czerwona', 120, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['majonez', 50, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['ketchup', 20, 'g'],
      ['czosnek', 1, 'szt'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pokrój filet z kurczaka w paski grubości 1 cm, wymieszaj z przyprawą do gyrosa i olejem, odstaw na 10 minut.',
      'Smaż kurczaka na mocno rozgrzanej patelni 7–8 minut, mieszając, aż będzie zrumieniony i miękki w środku; przełóż na talerz i ostudź.',
      'Posiekaj drobno kapustę pekińską, pokrój w kostkę pomidora, paprykę i ogórki konserwowe, a cebulę czerwoną w cienkie piórka; odsącz kukurydzę.',
      'Wymieszaj majonez z jogurtem, ketchupem i przeciśniętym czosnkiem, dopraw pieprzem.',
      'W szklanej misce układaj warstwy: kurczak, cebula, ogórek konserwowy, kukurydza, papryka, pomidor, a na wierzch kapusta pekińska; każdą drugą warstwę posmaruj cienko sosem.',
      'Resztę sosu rozsmaruj na kapuście i wstaw sałatkę do lodówki na co najmniej godzinę.',
      'Podawaj prosto z miski, nabierając łyżką przez wszystkie warstwy naraz.',
    ],
    photo:
      'Glass bowl showing colourful layers of spiced chicken, pickles, sweet corn, red pepper, tomato and shredded napa cabbage under a creamy garlic dressing',
    vessel: 'bowl',
  },
  {
    plan: 'ko-3',
    title: 'Sałatka jarzynowa',
    description:
      'Tradycyjna sałatka z gotowanych warzyw, jajek, groszku i ogórka kiszonego w majonezie z musztardą. Smakuje jak u babci i świetnie się przechowuje, więc warto zrobić ją dzień wcześniej.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['ziemniak', 250, 'g'],
      ['marchew', 150, 'g'],
      ['pietruszka korzeń', 100, 'g'],
      ['seler korzeniowy', 80, 'g'],
      ['jajko', 3, 'szt'],
      ['groszek konserwowy', 100, 'g'],
      ['ogórek kiszony', 100, 'g'],
      ['jabłko', 100, 'g'],
      ['cebula', 40, 'g'],
      ['majonez', 60, 'g'],
      ['musztarda', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Umyj dokładnie ziemniaki, marchew, pietruszkę i seler, ugotuj je w mundurkach w osolonej wodzie do miękkości (25–30 minut; sprawdź nożem), odcedź i całkowicie ostudź.',
      'Jajka ugotuj na twardo (10 minut), schłodź w zimnej wodzie i obierz.',
      'Obierz ostudzone warzywa i pokrój je w kostkę około 0,7 cm; tak samo pokrój jajka, ogórki kiszone i obrane jabłko.',
      'Posiekaj drobno cebulę, odsącz groszek konserwowy i przełóż wszystko do dużej miski.',
      'Dodaj majonez i musztardę, dopraw solą i pieprzem, wymieszaj delikatnie i wstaw do lodówki na co najmniej 30 minut.',
      'Podawaj schłodzoną, w misce albo na liściu sałaty, z kromką pieczywa.',
    ],
    photo:
      'Classic Polish vegetable salad of diced carrot, potato, egg, green peas and pickles bound in creamy mayonnaise, served in a white bowl',
    vessel: 'bowl',
  },
  {
    plan: 'ko-4',
    title: 'Sałatka z makaronem, kurczakiem i kukurydzą',
    description:
      'Makaronowe świderki z kawałkami kurczaka, słodką kukurydzą, papryką i ogórkiem w lekkim sosie jogurtowo-majonezowym. Sycąca, wygodna do pudełka i dobra także następnego dnia.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['makaron świder', 140, 'g'],
      ['filet z kurczaka', 250, 'g'],
      ['kukurydza z puszki', 140, 'g'],
      ['papryka czerwona', 120, 'g'],
      ['ogórek konserwowy', 80, 'g'],
      ['szczypiorek', 10, 'g'],
      ['majonez', 40, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['curry', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron w osolonej wodzie al dente według czasu z opakowania, odcedź, przelej zimną wodą i odsącz.',
      'Pokrój kurczaka w kostkę 2 cm, dopraw curry, solą i pieprzem, smaż na oleju 6–7 minut, aż kawałki będą złote i nie będą różowe w środku; ostudź.',
      'Pokrój paprykę i ogórki konserwowe w drobną kostkę, odsącz kukurydzę, posiekaj szczypiorek.',
      'Wymieszaj majonez z jogurtem, dopraw solą i pieprzem.',
      'Połącz w misce makaron, kurczaka, kukurydzę, paprykę, ogórki i większość szczypiorku, dodaj sos i wymieszaj.',
      'Podawaj od razu albo po 30 minutach w lodówce, posypaną resztą szczypiorku.',
    ],
    photo:
      'Bowl of fusilli pasta salad with golden chicken cubes, yellow sweet corn, diced red pepper and pickles in a light creamy dressing, sprinkled with chives',
    vessel: 'bowl',
  },
  {
    plan: 'ko-5',
    title: 'Sałatka z indykiem, awokado i pomidorkami',
    description:
      'Soczysty indyk w słodkiej papryce na rukoli z kremowym awokado, pomidorkami koktajlowymi i prażonymi pestkami dyni. Lekka, a konkretna kolacja na ciepłe wieczory, gotowa w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['filet z indyka', 250, 'g'],
      ['awokado', 1, 'szt'],
      ['pomidor koktajlowy', 200, 'g'],
      ['rukola', 60, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['pestki dyni', 20, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['cytryna', 20, 'g'],
      ['miód', 5, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pokrój filet z indyka na plastry grubości 1,5 cm, natrzyj papryką słodką, solą, pieprzem i łyżką oliwy.',
      'Smaż indyka na rozgrzanej patelni po 3–4 minuty z każdej strony, aż będzie zrumieniony i biały w środku; odstaw na 3 minuty i pokrój w paski.',
      'Na suchej patelni praż pestki dyni 2–3 minuty, aż zaczną strzelać.',
      'Przekrój pomidorki na połówki, cebulę pokrój w cienkie piórka, a awokado w plastry i skrop je częścią soku z cytryny.',
      'Wymieszaj resztę oliwy z sokiem z cytryny, miodem i szczyptą soli.',
      'Rozłóż rukolę na talerzach, ułóż pomidorki, cebulę, awokado i indyka, polej sosem i posyp pestkami dyni.',
    ],
    photo:
      'Rocket salad with paprika-seared turkey strips, sliced green avocado, halved cherry tomatoes, red onion rings and toasted pumpkin seeds',
  },
  {
    plan: 'ko-6',
    title: 'Sałatka z kurczakiem curry i mango',
    description:
      'Kurczak w łagodnym curry z soczystym mango, ogórkiem i roszponką, polany sosem miodowo-limonkowym. Słodko-słone połączenie, które wnosi trochę egzotyki do zwykłej kolacji.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 250, 'g'],
      ['mango', 250, 'g'],
      ['roszponka', 80, 'g'],
      ['ogórek', 150, 'g'],
      ['cebula czerwona', 30, 'g'],
      ['słonecznik łuszczony', 20, 'g'],
      ['limonka', 30, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['olej rzepakowy', 10, 'ml'],
      ['miód', 10, 'g'],
      ['sos sojowy', 10, 'ml'],
      ['curry', 3, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pokrój kurczaka w paski, wymieszaj z curry, solą, pieprzem i olejem rzepakowym.',
      'Smaż kurczaka na rozgrzanej patelni 6–7 minut, aż paski będą złote i soczyste w środku; zdejmij z ognia.',
      'Na suchej patelni upraż słonecznik na złoto (2–3 minuty).',
      'Obierz mango i pokrój miąższ w kostkę 1,5 cm, ogórek w półplasterki, a cebulę w cienkie piórka.',
      'Wymieszaj oliwę z sokiem z limonki, miodem i sosem sojowym.',
      'Ułóż na talerzach roszponkę, mango, ogórek, cebulę i ciepłego kurczaka, polej sosem i posyp słonecznikiem.',
    ],
    photo:
      'Lamb’s lettuce salad with curry-golden chicken strips, bright orange mango cubes, cucumber slices, red onion and toasted sunflower seeds',
  },
  {
    plan: 'ko-7',
    title: 'Tabbouleh z kaszą bulgur, ogórkiem i miętą',
    description:
      'Bliskowschodnia sałatka z bulguru z górą natki, świeżą miętą, pomidorami i ogórkiem, skropiona cytryną i oliwą. Orzeźwiająca, wegańska i idealna na upalny wieczór albo do pudełka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['bulgur', 140, 'g'],
      ['pomidor', 250, 'g'],
      ['ogórek', 200, 'g'],
      ['natka pietruszki', 60, 'g'],
      ['mięta', 15, 'g'],
      ['cebula dymka', 30, 'g'],
      ['cytryna', 50, 'g'],
      ['oliwa z oliwek', 40, 'ml'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zalej bulgur 280 ml wrzątku z 1 g soli, przykryj i odstaw na 15 minut, aż wchłonie wodę; rozdrobnij widelcem i ostudź.',
      'Pokrój pomidory i ogórek w drobną kostkę (0,5 cm), a cebulę dymkę w cienkie krążki.',
      'Posiekaj drobno natkę pietruszki i listki mięty.',
      'Wyciśnij sok z cytryny i wymieszaj go z oliwą, resztą soli i pieprzem.',
      'Połącz bulgur z warzywami i ziołami, polej sosem i wymieszaj; odstaw na 10 minut, żeby smaki się przegryzły.',
      'Podawaj w misce, udekorowaną listkami mięty.',
    ],
    photo:
      'Bowl of tabbouleh with fluffy bulgur, lots of chopped parsley and mint, diced tomato and cucumber, spring onion and a lemon wedge',
    vessel: 'bowl',
  },
  {
    plan: 'ko-8',
    title: 'Sałatka ziemniaczana z ogórkiem kiszonym',
    description:
      'Ziemniaki w mundurkach z ogórkiem kiszonym, czerwoną cebulą, jajkiem i szczypiorkiem w lekkim sosie musztardowym. Sprawdzi się sama albo obok kiełbaski z grilla.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['ogórek kiszony', 150, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['jajko', 2, 'szt'],
      ['szczypiorek', 15, 'g'],
      ['majonez', 50, 'g'],
      ['jogurt naturalny', 80, 'g'],
      ['musztarda', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Umyj ziemniaki i ugotuj je w mundurkach w osolonej wodzie 20–25 minut, aż nóż wejdzie gładko; odcedź i przestudź.',
      'W tym czasie ugotuj jajka na twardo (10 minut), schłodź i obierz.',
      'Obierz letnie ziemniaki i pokrój je w plastry grubości 0,5 cm; ogórki kiszone i jajka pokrój w kostkę, cebulę posiekaj drobno, szczypiorek pokrój.',
      'Wymieszaj majonez z jogurtem i musztardą, dopraw pieprzem i odrobiną soli.',
      'Połącz w misce ziemniaki, ogórki, cebulę i jajka z sosem, mieszając delikatnie, żeby ziemniaki się nie rozpadły.',
      'Odstaw sałatkę na 15 minut, a przed podaniem posyp szczypiorkiem.',
    ],
    photo:
      'Potato salad with sliced potatoes, diced pickled cucumber, chopped egg and red onion in a creamy mustard dressing, topped with fresh chives',
    vessel: 'bowl',
  },
  {
    plan: 'ko-9',
    title: 'Sałatka z jajkiem, rzodkiewką i szczypiorkiem',
    description:
      'Wiosenna sałatka z jajek na twardo, chrupiącej rzodkiewki, ogórka i szczypiorku w jogurtowym sosie, podana z żytnim chlebem. Prosta, świeża i gotowa w kwadrans.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['jajko', 6, 'szt'],
      ['rzodkiewka', 150, 'g'],
      ['szczypiorek', 20, 'g'],
      ['sałata lodowa', 150, 'g'],
      ['ogórek', 150, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['majonez', 25, 'g'],
      ['musztarda', 5, 'g'],
      ['chleb żytni', 100, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj jajka na twardo (10 minut od zagotowania), przełóż do zimnej wody, obierz i pokrój w ćwiartki.',
      'Pokrój rzodkiewki w cienkie plasterki, ogórek w półplasterki, a szczypiorek drobno.',
      'Porwij sałatę lodową na kawałki wielkości kęsa.',
      'Wymieszaj jogurt z majonezem, musztardą i połową szczypiorku, dopraw solą i pieprzem.',
      'Ułóż w misce sałatę, ogórek i rzodkiewkę, na wierzchu jajka, polej sosem.',
      'Posyp resztą szczypiorku i pieprzem, podawaj z kromkami chleba żytniego.',
    ],
    photo:
      'Salad of quartered hard-boiled eggs, thinly sliced pink radishes, cucumber and iceberg lettuce with creamy yoghurt dressing and lots of chives, rye bread on the side',
    vessel: 'bowl',
  },
  {
    plan: 'ko-10',
    title: 'Sałatka z pieczoną dynią i fetą',
    description:
      'Karmelizowana w piekarniku dynia z rozmarynem na rukoli, ze słoną fetą, czerwoną cebulą i pestkami dyni, polana balsamico z miodem. Jesienna kolacja o słodko-słonym charakterze.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['dynia', 600, 'g'],
      ['ser feta', 150, 'g'],
      ['rukola', 80, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['pestki dyni', 25, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['miód', 15, 'g'],
      ['ocet balsamiczny', 15, 'ml'],
      ['rozmaryn suszony', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Obierz dynię, usuń pestki i pokrój miąższ w kostkę 2 cm.',
      'Wymieszaj dynię z 20 ml oliwy, rozmarynem, solą i pieprzem, rozłóż jedną warstwą na blasze wyłożonej papierem.',
      'Piecz 25–30 minut, w połowie przewracając, aż dynia będzie miękka i przyrumieniona na brzegach; przestudź 5 minut.',
      'W tym czasie upraż pestki dyni na suchej patelni, a cebulę pokrój w cienkie piórka.',
      'Wymieszaj resztę oliwy z octem balsamicznym i miodem.',
      'Rozłóż rukolę na talerzach, ułóż ciepłą dynię i cebulę, pokrusz fetę, polej sosem i posyp pestkami.',
    ],
    photo:
      'Roasted caramelised butternut squash cubes on rocket with crumbled white feta, red onion slivers, pumpkin seeds and a dark balsamic honey drizzle',
  },
  {
    plan: 'ko-11',
    title: 'Domowa pizza margherita',
    description:
      'Cienkie, chrupiące ciasto drożdżowe z sosem z passaty, roztopioną mozzarellą i świeżą bazylią. Klasyka, którą zrobisz w domowym piekarniku lepiej niż z dostawy — wystarczy godzina na wyrośnięcie ciasta.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['drożdże instant', 5, 'g'],

      ['oliwa z oliwek', 20, 'ml'],
      ['cukier', 3, 'g'],
      ['sól', 3, 'g'],
      ['passata pomidorowa', 150, 'ml'],
      ['czosnek', 1, 'szt'],
      ['oregano', 2, 'g'],
      ['mozzarella', 180, 'g'],
      ['bazylia', 10, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z drożdżami instant, cukrem i 2 g soli, wlej letnią wodę (160 ml) i 15 ml oliwy; wyrabiaj 8–10 minut, aż ciasto będzie gładkie i elastyczne.',
      'Przełóż ciasto do miski, przykryj ściereczką i odstaw w ciepłe miejsce na około godzinę, aż podwoi objętość.',
      'Wymieszaj passatę z przeciśniętym czosnkiem, oregano, resztą soli i oliwy.',
      'Nagrzej piekarnik z blachą w środku do maksimum (250–275°C, grzanie góra-dół). Rozciągnij ciasto dłońmi na papierze do pieczenia w cienki placek o średnicy około 32 cm.',
      'Rozsmaruj sos, zostawiając 1,5 cm brzegu, i rozłóż porwaną, osuszoną mozzarellę.',
      'Przesuń pizzę z papierem na gorącą blachę i piecz 8–10 minut, aż brzegi będą rumiane, a ser zacznie się przypiekać w plamki.',
      'Posyp pizzę świeżymi listkami bazylii, pokrój w trójkąty i podawaj od razu.',
    ],
    photo:
      'Thin homemade Margherita pizza with blistered crust, bright red tomato sauce, melted pools of mozzarella and fresh basil leaves on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'ko-12',
    title: 'Pizza na tortilli z salami i pieczarkami',
    description:
      'Błyskawiczna pizza na cienkim, chrupiącym spodzie z tortilli, z salami, pieczarkami i ciągnącą się mozzarellą. Gotowa w 20 minut, bez wyrabiania ciasta — idealna, gdy ochota na pizzę przychodzi nagle.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['passata pomidorowa', 80, 'ml'],
      ['mozzarella tarta', 100, 'g'],
      ['salami', 50, 'g'],
      ['pieczarka', 100, 'g'],
      ['cebula czerwona', 30, 'g'],
      ['oregano', 1, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C (góra-dół). Pokrój pieczarki w cienkie plasterki, a cebulę czerwoną w piórka.',
      'Wymieszaj passatę z oregano i pieprzem.',
      'Ułóż tortille na blasze wyłożonej papierem, posmaruj je cienko oliwą od spodu i sosem od góry, zostawiając 1 cm brzegu.',
      'Posyp połową mozzarelli, rozłóż salami, pieczarki i cebulę, a na wierzch resztę sera.',
      'Piecz 8–10 minut, aż brzegi tortilli będą chrupiące, a ser roztopiony i lekko zrumieniony.',
      'Pokrój każdą pizzę na 4 części i podawaj od razu, posypaną szczyptą oregano.',
    ],
    photo:
      'Crispy tortilla pizza topped with melted mozzarella, salami slices, sliced mushrooms and red onion, cut into wedges on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'ko-13',
    title: 'Burrito z mięsem mielonym i fasolą',
    description:
      'Duża tortilla zawinięta z pikantną wołowiną, czerwoną fasolą, ryżem, kukurydzą i serem cheddar, podpieczona na patelni. Sycąca kolacja w stylu tex-mex, którą łatwo zabrać w drogę.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['wołowina mielona', 200, 'g'],
      ['fasola czerwona z puszki', 150, 'g'],
      ['ryż biały', 50, 'g'],
      ['kukurydza z puszki', 60, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 1, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['płatki chili', 1, 'g'],
      ['ser cheddar', 40, 'g'],
      ['śmietana 18', 40, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż w osolonej wodzie (około 15 minut) i odcedź.',
      'Na oleju zeszklij posiekaną cebulę (3 minuty), dodaj przeciśnięty czosnek i wołowinę; smaż 6–7 minut, rozbijając mięso łopatką, aż straci różowy kolor.',
      'Dodaj kmin rzymski, paprykę, płatki chili i koncentrat, smaż minutę, potem wlej 60 ml wody, dodaj odsączoną fasolę i kukurydzę; duś 5 minut, aż sos zgęstnieje. Dopraw solą i pieprzem.',
      'Podgrzej tortille 20 sekund na suchej patelni, żeby zmiękły. Na środku każdej ułóż pas ryżu, farsz, łyżkę śmietany i starty cheddar.',
      'Złóż boki tortilli do środka i zwiń ciasno w rulon.',
      'Połóż burrito łączeniem do dołu na suchej patelni i podpiekaj po 2 minuty z każdej strony, aż będzie złote; przekrój na pół i podawaj.',
    ],
    photo:
      'Golden toasted burrito cut in half revealing spiced minced beef, red kidney beans, rice, sweet corn and melted cheddar',
  },
  {
    plan: 'ko-14',
    title: 'Fajitas z kurczakiem i papryką',
    description:
      'Paski kurczaka i kolorowej papryki smażone z cebulą w wędzonej papryce i limonce, podawane w ciepłych tortillach z jogurtem. Każdy zawija sobie sam, więc to dobra kolacja do wspólnego stołu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['papryka żółta', 160, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['tortilla pszenna', 4, 'szt'],
      ['olej rzepakowy', 20, 'ml'],
      ['limonka', 30, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['jogurt grecki', 80, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pokrój kurczaka w paski grubości 1 cm, wymieszaj z połową oleju, sokiem z połowy limonki, kminem, papryką wędzoną, czosnkiem granulowanym, solą i pieprzem; odstaw na 10 minut.',
      'Pokrój paprykę w paski 1 cm, a cebulę w grube piórka.',
      'Na mocno rozgrzanej patelni z resztą oleju smaż kurczaka 5–6 minut, aż się zrumieni; przełóż na talerz.',
      'Na tę samą patelnię wrzuć paprykę i cebulę, smaż 4–5 minut, aż zmiękną, ale zostaną lekko chrupiące. Dodaj kurczaka, skrop resztą soku z limonki i wymieszaj.',
      'Podgrzej tortille po 20 sekund z każdej strony na suchej patelni.',
      'Podawaj gorący farsz prosto z patelni z tortillami i jogurtem greckim do nakładania.',
    ],
    photo:
      'Sizzling skillet of chicken strips with red and yellow pepper and red onion, warm flour tortillas and a bowl of Greek yoghurt beside',
  },
  {
    plan: 'ko-15',
    title: 'Tacos z mielonym indykiem',
    description:
      'Chrupiąca sałata, pomidor i cheddar na pikantnym, mielonym indyku w miękkich tortillach, z kleksem jogurtu i kolendrą. Lżejsza wersja meksykańskiej klasyki, gotowa w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['indyk mielony', 250, 'g'],
      ['tortilla pszenna', 4, 'szt'],
      ['sałata lodowa', 80, 'g'],
      ['pomidor', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['ser cheddar', 40, 'g'],
      ['jogurt grecki', 80, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['oregano', 1, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Na rozgrzanym oleju smaż indyka 5–6 minut, rozbijając go łopatką, aż będzie sypki i lekko zrumieniony.',
      'Dodaj kmin, paprykę wędzoną, oregano i koncentrat, smaż minutę, wlej 50 ml wody i gotuj 3 minuty, aż sos oblepi mięso; dopraw solą, pieprzem i sokiem z połowy limonki.',
      'Poszatkuj sałatę w cienkie paski, pomidor pokrój w kostkę, a cebulę czerwoną posiekaj drobno; zetrzyj cheddar i posiekaj kolendrę.',
      'Podgrzej tortille na suchej patelni po 20 sekund z każdej strony.',
      'Na każdą tortillę nałóż sałatę, mięso, pomidor, cebulę i ser, dodaj łyżkę jogurtu greckiego.',
      'Posyp tacos kolendrą, złóż na pół i podawaj z ćwiartkami limonki.',
    ],
    photo:
      'Four soft flour tortilla tacos filled with spiced minced turkey, shredded lettuce, diced tomato, grated cheddar, yoghurt and fresh coriander, lime wedges beside',
  },
  {
    plan: 'ko-16',
    title: 'Enchiladas z kurczakiem',
    description:
      'Tortille zwinięte z kurczakiem i fasolą, zapieczone w pikantnym sosie pomidorowym pod warstwą roztopionego cheddara. Rozgrzewające danie z piekarnika, które można przygotować wcześniej i tylko zapiec.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 250, 'g'],
      ['tortilla pszenna', 4, 'szt'],
      ['fasola czerwona z puszki', 100, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 1, 'szt'],
      ['passata pomidorowa', 300, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['ser cheddar', 60, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół). Pokrój kurczaka w drobną kostkę 1 cm, a cebulę posiekaj.',
      'Na oleju zeszklij cebulę, dodaj kurczaka i smaż 5–6 minut, aż zbieleje; dodaj przeciśnięty czosnek, kmin i obie papryki, smaż jeszcze minutę.',
      'Przełóż połowę passaty do farszu, dodaj odsączoną fasolę, dopraw solą i pieprzem i duś 3 minuty.',
      'Rozłóż farsz na tortille, zwiń je ciasno i ułóż łączeniem do dołu w naczyniu żaroodpornym.',
      'Polej tortille resztą passaty doprawioną szczyptą soli i posyp startym cheddarem.',
      'Zapiekaj 15–20 minut, aż sos zacznie bulgotać, a ser będzie roztopiony i złoty.',
      'Posyp enchiladas posiekaną natką i podawaj prosto z naczynia.',
    ],
    photo:
      'Baking dish of rolled chicken enchiladas covered in bubbling red tomato sauce and golden melted cheddar, sprinkled with chopped parsley',
  },
  {
    plan: 'ko-17',
    title: 'Pita z kurczakiem gyros i warzywami',
    description:
      'Ciepła pita wypełniona kurczakiem w przyprawie gyros, chrupiącymi warzywami i czosnkowym sosem jogurtowym z koperkiem. Domowy fast food, który smakuje jak z budki, a jest dużo lżejszy.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['pita', 4, 'szt'],
      ['filet z kurczaka', 280, 'g'],
      ['przyprawa do gyrosa', 8, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sałata lodowa', 80, 'g'],
      ['pomidor', 150, 'g'],
      ['ogórek', 120, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['jogurt grecki', 120, 'g'],
      ['czosnek', 1, 'szt'],
      ['koperek', 5, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Pokrój kurczaka w cienkie paski, wymieszaj z przyprawą do gyrosa i olejem, odstaw na 10 minut.',
      'Na sos zetrzyj 30 g ogórka na tarce o grubych oczkach, odciśnij i wymieszaj z jogurtem greckim, przeciśniętym czosnkiem, posiekanym koperkiem i solą.',
      'Pokrój resztę ogórka i pomidor w półplasterki, cebulę w piórka, a sałatę poszatkuj.',
      'Smaż kurczaka na mocno rozgrzanej patelni 6–7 minut, aż paski się zrumienią na brzegach.',
      'Podgrzej pity 2–3 minuty w piekarniku nagrzanym do 180°C albo w tosterze i natnij, tworząc kieszonki.',
      'Napełnij pity sałatą, warzywami i kurczakiem, polej sosem czosnkowym i podawaj od razu.',
    ],
    photo:
      'Warm pita pockets stuffed with gyros-spiced chicken strips, lettuce, tomato, cucumber and red onion, drizzled with white garlic yoghurt sauce',
  },
  {
    plan: 'ko-18',
    title: 'Wrap z kurczakiem cezar',
    description:
      'Wszystko, co najlepsze w sałatce cezar, zawinięte w tortillę: soczysty kurczak, rzymska sałata, parmezan i kremowy sos czosnkowy. Wygodny do jedzenia w ręku i do zabrania na wynos.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['filet z kurczaka', 250, 'g'],
      ['sałata rzymska', 120, 'g'],
      ['ser parmezan', 25, 'g'],
      ['majonez', 30, 'g'],
      ['jogurt naturalny', 40, 'g'],
      ['cytryna', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['musztarda', 5, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozbij filet z kurczaka na grubość 1,5 cm, natrzyj solą, pieprzem i oliwą.',
      'Smaż na rozgrzanej patelni po 4 minuty z każdej strony, aż będzie złoty i soczysty; odstaw na 3 minuty i pokrój w paski.',
      'Wymieszaj majonez z jogurtem, przeciśniętym czosnkiem, musztardą, sokiem z cytryny i połową startego parmezanu.',
      'Pokrój sałatę rzymską w paski 2 cm i wymieszaj z połową sosu.',
      'Podgrzej tortille na suchej patelni, posmaruj resztą sosu, ułóż sałatę, kurczaka i resztę parmezanu, zawiń ciasno, podwijając boki.',
      'Przekrój wrapy ukośnie na pół i podawaj od razu.',
    ],
    photo:
      'Chicken Caesar wraps cut diagonally showing grilled chicken strips, romaine lettuce, parmesan shavings and creamy dressing inside a flour tortilla',
  },
  {
    plan: 'ko-19',
    title: 'Domowe hot dogi z ogórkiem i prażoną cebulką',
    description:
      'Gorące parówki w chrupiących bułkach z ketchupem, musztardą, ogórkiem konserwowym i prażoną cebulką. Kolacja na szybko, którą uwielbiają dzieci, a dorośli po cichu też.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['bułka do hot doga', 4, 'szt'],
      ['parówka', 4, 'szt'],
      ['ogórek konserwowy', 60, 'g'],
      ['cebula prażona', 15, 'g'],
      ['ketchup', 30, 'g'],
      ['musztarda', 20, 'g'],
      ['sałata lodowa', 40, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C. Zagotuj wodę w garnku, zdejmij z ognia i włóż parówki na 5–6 minut, aż będą gorące w środku.',
      'Natnij bułki wzdłuż, nie przecinając do końca, i podgrzewaj w piekarniku 3–4 minuty, aż skórka będzie chrupiąca.',
      'Pokrój ogórki konserwowe w drobną kostkę, a sałatę w cienkie paski.',
      'Włóż do każdej bułki trochę sałaty i odsączoną parówkę.',
      'Polej ketchupem i musztardą, posyp ogórkiem i prażoną cebulką, podawaj od razu.',
    ],
    photo:
      'Four hot dogs in toasted buns with sausages, zigzags of ketchup and yellow mustard, diced pickles and crispy fried onions',
  },
  {
    plan: 'ko-20',
    title: 'Klasyczny burger wołowy z cheddarem',
    description:
      'Soczysty kotlet z mielonej wołowiny z roztopionym cheddarem w miękkiej bułce, z sałatą, pomidorem, ogórkiem i sosem. Domowy burger bez udziwnień, gotowy w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['wołowina mielona', 300, 'g'],
      ['bułka do hamburgera', 2, 'szt'],
      ['ser cheddar', 40, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['pomidor', 120, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['ogórek konserwowy', 50, 'g'],
      ['ketchup', 20, 'g'],
      ['musztarda', 10, 'g'],
      ['majonez', 20, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Podziel wołowinę na dwie części i uformuj kotlety grubości około 1,5 cm, nieco szersze od bułki; zrób kciukiem płytkie wgłębienie na środku. Posól i popieprz z obu stron tuż przed smażeniem.',
      'Pokrój pomidor i cebulę w plastry, ogórki w plasterki wzdłuż; wymieszaj majonez z ketchupem i musztardą na sos.',
      'Rozgrzej mocno patelnię z olejem i smaż kotlety 3–4 minuty, przewróć, połóż na każdym plaster cheddara i smaż jeszcze 3 minuty pod przykryciem, aż ser się roztopi.',
      'Przekrój bułki i opiecz je przecięciem do dołu na suchej patelni przez minutę.',
      'Posmaruj spody bułek sosem, ułóż sałatę, kotlet z serem, pomidor, cebulę i ogórki, przykryj wierzchem.',
      'Podawaj od razu, z resztą sosu obok.',
    ],
    photo:
      'Classic beef burger in a toasted bun with melted cheddar, lettuce, tomato slice, red onion rings and pickles, sauce dripping at the side',
  },
  {
    plan: 'ko-21',
    title: 'Kanapka klubowa z kurczakiem i boczkiem',
    description:
      'Trzypiętrowa kanapka z opiekanego tostowego chleba z kurczakiem, chrupiącym boczkiem, pomidorem i sałatą na majonezie. Pokrojona w trójkąty i spięta wykałaczką wygląda jak z kawiarni.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['chleb tostowy', 150, 'g'],
      ['filet z kurczaka', 200, 'g'],
      ['boczek', 60, 'g'],
      ['pomidor', 120, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['majonez', 30, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przekrój filet na dwa cienkie płaty, dopraw solą i pieprzem, smaż na oleju po 3–4 minuty z każdej strony, aż będzie biały w środku; pokrój w plastry.',
      'Na tej samej patelni usmaż plastry boczku na chrupko (3–4 minuty) i odsącz na ręczniku papierowym.',
      'Opiecz 6 kromek chleba tostowego w tosterze na złoto.',
      'Pokrój pomidor w plastry, sałatę porwij na liście.',
      'Posmaruj kromki majonezem. Na pierwszej ułóż sałatę i kurczaka, przykryj drugą kromką, na niej połóż boczek, pomidor i sałatę, przykryj trzecią kromką; tak samo złóż drugą kanapkę.',
      'Przekrój każdą kanapkę po przekątnych na 4 trójkąty, spnij wykałaczkami i podawaj.',
    ],
    photo:
      'Club sandwich triangles stacked with toasted white bread, sliced chicken, crispy bacon, tomato and lettuce, held with toothpicks',
    vessel: 'board',
  },
  {
    plan: 'ko-22',
    title: 'Bruschetta z pomidorami i bazylią',
    description:
      'Opieczone kromki bagietki natarte czosnkiem, z soczystymi pomidorami, świeżą bazylią i oliwą. Włoska prostota na letni wieczór, najlepsza z dojrzałymi, pachnącymi pomidorami.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['bagietka', 250, 'g'],
      ['pomidor', 400, 'g'],
      ['bazylia', 15, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 30, 'ml'],
      ['ocet balsamiczny', 10, 'ml'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pokrój pomidory w kostkę 1 cm, usuwając najbardziej wodniste gniazda nasienne; przełóż na sitko na 5 minut, żeby odciekły.',
      'Wymieszaj pomidory z 20 ml oliwy, octem balsamicznym, posiekanym 1 ząbkiem czosnku, porwaną bazylią, solą i pieprzem.',
      'Pokrój bagietkę ukośnie na kromki grubości 1,5 cm, skrop resztą oliwy.',
      'Opiecz kromki na patelni grillowej albo w piekarniku nagrzanym do 220°C (5–6 minut), aż będą złote i chrupiące.',
      'Natrzyj gorące kromki przekrojonym drugim ząbkiem czosnku.',
      'Nałóż pomidory na grzanki tuż przed podaniem i udekoruj listkami bazylii.',
    ],
    photo:
      'Toasted baguette slices topped with glistening diced red tomatoes, torn fresh basil and a drizzle of olive oil and balsamic on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'ko-23',
    title: 'Panini z mozzarellą, szynką i pesto',
    description:
      'Chrupiąca, opieczona ciabatta z ciągnącą się mozzarellą, szynką, pomidorem i bazyliowym pesto, podana z rukolą. Ciepła kanapka w stylu włoskiego baru, którą zrobisz na patelni.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['ciabatta', 220, 'g'],
      ['mozzarella', 125, 'g'],
      ['szynka', 100, 'g'],
      ['pesto bazyliowe', 40, 'g'],
      ['pomidor', 120, 'g'],
      ['rukola', 30, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przekrój ciabattę na dwie części, a każdą z nich wzdłuż na pół.',
      'Pokrój mozzarellę i pomidor w plastry 0,5 cm, osusz je ręcznikiem papierowym.',
      'Posmaruj wnętrza pieczywa pesto, ułóż szynkę, pomidor i mozzarellę, popieprz i przykryj wierzchem.',
      'Posmaruj kanapki z zewnątrz oliwą i połóż na rozgrzanej patelni grillowej; przyciśnij je drugą, ciężką patelnią lub garnkiem.',
      'Opiekaj po 3–4 minuty z każdej strony na średnim ogniu, aż pieczywo będzie chrupiące w paski, a ser się roztopi.',
      'Przekrój panini na pół i podawaj od razu z garścią rukoli.',
    ],
    photo:
      'Grill-marked ciabatta panini cut in half with oozing melted mozzarella, ham, tomato and green pesto, served with fresh rocket',
    vessel: 'board',
  },
  {
    plan: 'ko-24',
    title: 'Tosty z tuńczykiem i serem',
    description:
      'Chrupiące tosty z pastą z tuńczyka, kukurydzy i czerwonej cebuli pod roztopionym serem żółtym. Sycąca kolacja ze spiżarni, gotowa w kwadrans.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['chleb tostowy', 160, 'g'],
      ['tuńczyk w puszce', 170, 'g'],
      ['ser żółty', 60, 'g'],
      ['kukurydza z puszki', 50, 'g'],
      ['cebula czerwona', 30, 'g'],
      ['majonez', 20, 'g'],
      ['masło', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Odsącz tuńczyka i kukurydzę, cebulę posiekaj bardzo drobno.',
      'Rozdrobnij tuńczyka widelcem i wymieszaj z kukurydzą, cebulą, majonezem i pieprzem.',
      'Posmaruj kromki chleba tostowego cienko masłem po jednej stronie.',
      'Na nieposmarowane strony połowy kromek nałóż pastę z tuńczyka i plastry sera żółtego, przykryj pozostałymi kromkami masłem na zewnątrz.',
      'Opiekaj w opiekaczu albo na patelni pod przykryciem po 2–3 minuty z każdej strony, aż tosty będą złote, a ser się roztopi.',
      'Przekrój tosty po przekątnej i podawaj na ciepło.',
    ],
    photo:
      'Golden toasted sandwiches cut diagonally with a tuna, sweet corn and red onion filling and melted yellow cheese oozing out',
  },
  {
    plan: 'ko-25',
    title: 'Wytrawne gofry z serem i szynką',
    description:
      'Chrupiące z zewnątrz, miękkie w środku gofry z serem żółtym, szynką i szczypiorkiem zapieczonymi w cieście, podane ze śmietaną. Wytrawna odmiana gofrów na ciepłą, sycącą kolację.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 150, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 200, 'ml'],
      ['masło', 30, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['ser żółty', 60, 'g'],
      ['szynka', 80, 'g'],
      ['szczypiorek', 10, 'g'],
      ['śmietana 18', 60, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Roztop masło i przestudź. Zetrzyj ser żółty na tarce o drobnych oczkach, szynkę pokrój w drobną kostkę, szczypiorek posiekaj.',
      'Wymieszaj mąkę z proszkiem do pieczenia, solą i pieprzem.',
      'W drugiej misce roztrzep jajka z mlekiem i masłem, wlej do mąki i wymieszaj rózgą tylko do połączenia składników.',
      'Wmieszaj ser, szynkę i większość szczypiorku; ciasto ma mieć konsystencję gęstej śmietany.',
      'Rozgrzej gofrownicę, posmaruj ją pędzelkiem olejem i piecz gofry po 4–5 minut, aż będą złote i przestaną parować.',
      'Podawaj gorące gofry z łyżką śmietany i resztą szczypiorku.',
    ],
    photo:
      'Golden savoury waffles studded with ham and cheese, topped with a dollop of sour cream and chopped chives',
  },
  {
    plan: 'ko-26',
    title: 'Placki z cukinii z jogurtem czosnkowym',
    description:
      'Złociste placki z tartej cukinii z koperkiem, chrupiące na brzegach i miękkie w środku, podane z gęstym jogurtem czosnkowym. Świetny sposób na sezon cukiniowy i lekką, wegetariańską kolację.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['cukinia', 500, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 70, 'g'],
      ['koperek', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 40, 'ml'],
      ['jogurt grecki', 150, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zetrzyj cukinię na tarce o grubych oczkach, wymieszaj z 2 g soli i odstaw na 10 minut; potem odciśnij mocno w dłoniach lub przez ściereczkę.',
      'Dodaj do cukinii jajka, mąkę, połowę posiekanego koperku, jeden przeciśnięty ząbek czosnku i pieprz; wymieszaj na gęstą masę.',
      'Rozgrzej na patelni część oleju i nakładaj łyżką placki grubości około 1 cm.',
      'Smaż na średnim ogniu po 3 minuty z każdej strony, aż będą złote i ścięte; odsącz na ręczniku papierowym, a kolejne partie smaż na reszcie oleju.',
      'Wymieszaj jogurt grecki z drugim przeciśniętym ząbkiem czosnku, resztą koperku i szczyptą soli.',
      'Podawaj gorące placki z jogurtem czosnkowym do maczania.',
    ],
    photo:
      'Stack of golden crispy courgette fritters flecked with dill, with a bowl of thick white garlic yoghurt dip',
  },
  {
    plan: 'ko-27',
    title: 'Pieczony kalafior z ciecierzycą i jogurtem',
    description:
      'Różyczki kalafiora i ciecierzyca pieczone w kurkumie, kminie i wędzonej papryce, aż się przyrumienią, podane z cytrynowym jogurtem i natką. Aromatyczna, wegetariańska kolacja z jednej blachy.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['kalafior', 800, 'g'],
      ['ciecierzyca z puszki', 200, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['kurkuma', 2, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C (termoobieg 200°C). Podziel kalafior na średnie różyczki, a ciecierzycę odsącz, opłucz i osusz.',
      'Wymieszaj oliwę z kurkumą, kminem, papryką wędzoną, czosnkiem granulowanym, 2 g soli i pieprzem; obtocz w tym kalafior i ciecierzycę.',
      'Rozłóż wszystko jedną warstwą na blasze wyłożonej papierem i piecz 25–30 minut, mieszając w połowie, aż kalafior będzie miękki i przypieczony na brzegach, a ciecierzyca chrupiąca.',
      'Wymieszaj jogurt grecki z przeciśniętym czosnkiem, sokiem z cytryny i resztą soli.',
      'Rozsmaruj jogurt na talerzach, ułóż na nim gorący kalafior z ciecierzycą i posyp posiekaną natką.',
    ],
    photo:
      'Golden turmeric-roasted cauliflower florets and crispy chickpeas on a swoosh of lemon garlic yoghurt, sprinkled with chopped parsley',
  },
  {
    plan: 'ko-28',
    title: 'Pieczarki faszerowane serem z bagietką',
    description:
      'Duże pieczarki wypełnione farszem z serka kremowego, podsmażonych nóżek, cebuli i czosnku, zapieczone pod chrupiącą kołderką sera i bułki tartej. Podane z bagietką tworzą ciepłą, wegetariańską kolację.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['pieczarka', 500, 'g'],
      ['serek kremowy', 100, 'g'],
      ['ser żółty', 70, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 1, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['bułka tarta', 20, 'g'],
      ['masło', 15, 'g'],
      ['bagietka', 120, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół). Oczyść duże pieczarki, wykręć nóżki i posiekaj je drobno.',
      'Na maśle zeszklij posiekaną cebulę (3 minuty), dodaj nóżki pieczarek i przeciśnięty czosnek, smaż 5 minut, aż odparuje woda; dopraw solą i pieprzem i przestudź.',
      'Wymieszaj farsz z serkiem kremowym, połową posiekanej natki i połową startego sera żółtego.',
      'Napełnij kapelusze farszem, ułóż w naczyniu żaroodpornym, posyp resztą sera wymieszaną z bułką tartą.',
      'Zapiekaj 18–20 minut, aż pieczarki zmiękną, a wierzch będzie złoty i chrupiący.',
      'Posyp resztą natki i podawaj z kromkami bagietki.',
    ],
    photo:
      'Baked stuffed mushroom caps with creamy cheese filling and a golden crispy breadcrumb top, sprinkled with parsley, baguette slices beside',
  },
  {
    plan: 'ko-29',
    title: 'Pieczone ziemniaki z boczkiem i serem',
    description:
      'Połówki ziemniaków pieczone do miękkości, zapieczone z chrupiącym boczkiem i serem, podane ze śmietaną i szczypiorkiem. Swojskie, rozgrzewające danie na chłodny wieczór.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['ziemniak', 700, 'g'],
      ['boczek', 80, 'g'],
      ['ser żółty', 80, 'g'],
      ['śmietana 18', 100, 'g'],
      ['szczypiorek', 15, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Wyszoruj ziemniaki i przekrój je wzdłuż na połówki.',
      'Natrzyj ziemniaki oliwą, solą, papryką i pieprzem, ułóż przecięciem do dołu na blasze z papierem i piecz 35–40 minut, aż będą miękkie i przyrumienione od spodu.',
      'W tym czasie pokrój boczek w kostkę i wysmaż go na suchej patelni na chrupko (5–6 minut); zetrzyj ser.',
      'Odwróć ziemniaki, lekko rozgnieć miąższ widelcem, posyp boczkiem i serem.',
      'Zapiekaj jeszcze 5–7 minut, aż ser się roztopi i zacznie rumienić.',
      'Podawaj z kleksem śmietany i posiekanym szczypiorkiem.',
    ],
    photo:
      'Roasted potato halves topped with crispy diced bacon and melted golden cheese, dollops of sour cream and chopped chives',
  },
  {
    plan: 'ko-30',
    title: 'Batat faszerowany kurczakiem i fasolą',
    description:
      'Słodki, pieczony batat wypełniony pikantnym kurczakiem z czerwoną fasolą i kukurydzą, zapieczony z cheddarem i podany z jogurtem. Kolorowe, sycące danie w stylu tex-mex.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['batat', 700, 'g'],
      ['filet z kurczaka', 200, 'g'],
      ['fasola czerwona z puszki', 120, 'g'],
      ['kukurydza z puszki', 60, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['ser cheddar', 40, 'g'],
      ['jogurt grecki', 60, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół). Wyszoruj 2 bataty, nakłuj widelcem w kilku miejscach i piecz na blasze 45–50 minut, aż będą całkiem miękkie.',
      'W tym czasie pokrój kurczaka w kostkę 1 cm, a cebulę posiekaj.',
      'Na oleju smaż cebulę 2 minuty, dodaj kurczaka, kmin, paprykę wędzoną, sól i pieprz; smaż 5–6 minut, aż mięso się zrumieni.',
      'Dodaj odsączoną fasolę i kukurydzę, podgrzewaj 2 minuty i dopraw do smaku.',
      'Natnij upieczone bataty wzdłuż, rozchyl i lekko rozgnieć miąższ; nałóż farsz, posyp startym cheddarem i zapiekaj 5 minut, aż ser się roztopi.',
      'Podawaj z łyżką jogurtu greckiego i posiekanym szczypiorkiem.',
    ],
    photo:
      'Baked orange sweet potatoes split open and stuffed with spiced chicken, red kidney beans and corn under melted cheddar, topped with yoghurt and chives',
  },
  {
    plan: 'ko-31',
    title: 'Halloumi z pieczonymi warzywami',
    description:
      'Grillowane plastry halloumi, które skrzypią pod zębami, na blasze pieczonej cukinii, bakłażana, papryki i pomidorków z ziołami prowansalskimi. Śródziemnomorska kolacja z piekarnika i patelni.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['ser halloumi', 200, 'g'],
      ['cukinia', 250, 'g'],
      ['bakłażan', 250, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 30, 'ml'],
      ['zioła prowansalskie', 3, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 210°C (termoobieg). Pokrój cukinię i bakłażana w kostkę 2 cm, paprykę w paski, a cebulę w ósemki.',
      'Wymieszaj warzywa z 25 ml oliwy, ziołami prowansalskimi, nieobranymi, lekko zgniecionymi ząbkami czosnku, solą i pieprzem; rozłóż na blasze wyłożonej papierem.',
      'Piecz 20 minut, dodaj pomidorki koktajlowe i piecz jeszcze 10 minut, aż warzywa będą miękkie i przypieczone.',
      'Pokrój halloumi na plastry grubości 1 cm i osusz ręcznikiem.',
      'Smaż ser na patelni posmarowanej resztą oliwy po 1–2 minuty z każdej strony, aż będzie złoty w paski.',
      'Rozłóż warzywa na talerzach, ułóż na nich gorące halloumi, skrop sokiem z cytryny i podawaj.',
    ],
    photo:
      'Golden pan-fried halloumi slices on colourful roasted courgette, aubergine, red pepper, red onion and blistered cherry tomatoes with a lemon wedge',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
