/**
 * Katalog 500 — Kolacje, część ko-b (pozycje ko-32 … ko-62).
 * Lista: `prisma/catalog/katalog-500-lista.md`, generator: `scripts/lib/katalog-500-2026-09.ts`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'ko-32',
    title: 'Ziemniaki zapiekane w śmietanie (gratin)',
    description:
      'Cienkie plastry ziemniaków zapiekane w śmietance z czosnkiem i gałką muszkatołową, pod złotą warstwą sera. Kremowe w środku, przyrumienione na brzegach — sycąca, rozgrzewająca kolacja na chłodny wieczór.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 80,
    servings: 2,
    ingredients: [
      ['ziemniak', 700, 'g'],
      ['śmietanka 30', 200, 'ml'],
      ['mleko', 100, 'ml'],
      ['czosnek', 2, 'szt'],
      ['masło', 10, 'g'],
      ['ser gouda', 60, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 180°C (góra–dół). Naczynie żaroodporne o pojemności ok. 1,5 l wysmaruj masłem.',
      'Ziemniaki obierz i pokrój w plastry grubości 2–3 mm, najlepiej na tarce do plastrów. Nie płucz ich — skrobia zagęści sos.',
      'W rondelku podgrzej śmietankę z mlekiem, przeciśniętym czosnkiem, gałką muszkatołową, tymiankiem, solą i pieprzem, aż zacznie parować; nie gotuj.',
      'Układaj plastry ziemniaków w naczyniu warstwami, zachodzącymi na siebie jak dachówki, i zalej gorącą śmietanką tak, by prawie je przykryła.',
      'Przykryj naczynie folią i piecz 40 minut. Zdejmij folię, posyp startą goudą i piecz jeszcze 20–25 minut, aż wierzch się zezłoci, a nóż wchodzi w ziemniaki bez oporu.',
      'Odstaw gratin na 10 minut, żeby sos zgęstniał, i podawaj prosto z naczynia, np. z zieloną sałatą.',
    ],
    photo:
      'Golden-browned potato gratin with thin layered potato slices bubbling in creamy sauce, melted cheese crust and a sprinkle of thyme, one portion scooped out',
  },
  {
    plan: 'ko-33',
    title: 'Jajka w sosie musztardowym z ziemniakami',
    description:
      'Połówki jajek na twardo w gładkim, lekko pikantnym sosie musztardowym, podane z ziemniakami i koperkiem. Domowa klasyka z dzieciństwa, tania i gotowa w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['jajko', 6, 'szt'],
      ['ziemniak', 500, 'g'],
      ['masło', 20, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['mleko', 250, 'ml'],
      ['bulion warzywny', 150, 'ml'],
      ['musztarda', 40, 'g'],
      ['cukier', 2, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, pokrój na połówki i gotuj w osolonej wodzie ok. 20 minut, aż będą miękkie.',
      'W tym czasie jajka ugotuj na twardo (10 minut od zagotowania), przełóż do zimnej wody, obierz i przekrój wzdłuż na pół.',
      'W rondelku roztop masło, wsyp mąkę i smaż, mieszając, przez minutę. Stopniowo wlewaj mleko i bulion, cały czas mieszając trzepaczką, żeby nie było grudek.',
      'Gotuj sos 3–4 minuty, aż zgęstnieje do konsystencji gęstej śmietany. Zdejmij z ognia, wmieszaj musztardę, cukier, sól i pieprz.',
      'Włóż połówki jajek do sosu i podgrzej razem minutę na małym ogniu, bez gotowania.',
      'Ziemniaki odcedź, posyp posiekanym koperkiem i podaj z jajkami polanymi sosem musztardowym.',
    ],
    photo:
      'Halved hard-boiled eggs in smooth pale yellow mustard sauce next to boiled potatoes sprinkled with fresh chopped dill',
  },
  {
    plan: 'ko-34',
    title: 'Kasza bulgur z pieczonymi warzywami i fetą',
    description:
      'Sypki bulgur wymieszany z pieczoną cukinią, papryką i czerwoną cebulą, doprawiony cytryną i natką, z kawałkami słonej fety. Dobrze smakuje na ciepło i na zimno, więc nadaje się też do pudełka na jutro.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['bulgur', 140, 'g'],
      ['bulion warzywny', 300, 'ml'],
      ['cukinia', 250, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cebula czerwona', 1, 'szt'],
      ['pomidor koktajlowy', 150, 'g'],
      ['ser feta', 100, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 210°C z termoobiegiem. Cukinię i paprykę pokrój w kostkę 2 cm, cebulę w ósemki.',
      'Warzywa wymieszaj na blasze z połową oliwy, solą i pieprzem i piecz 20–25 minut, aż zmiękną i przyrumienią się na brzegach.',
      'W tym czasie zagotuj bulion, wsyp bulgur, przykryj i gotuj na małym ogniu 10 minut. Zdejmij z ognia i zostaw pod przykryciem na 5 minut, a potem rozluźnij widelcem.',
      'Przygotuj dressing: sok z cytryny wymieszaj z resztą oliwy i przeciśniętym czosnkiem.',
      'Do bulguru dodaj pieczone warzywa, przekrojone na pół pomidorki, posiekaną natkę i dressing; wymieszaj.',
      'Nałóż kaszę na talerze i pokrusz na wierzch fetę.',
    ],
    photo:
      'Fluffy bulgur mixed with roasted zucchini, red pepper and red onion, halved cherry tomatoes, crumbled white feta and chopped parsley',
  },
  {
    plan: 'ko-35',
    title: 'Kuskus z warzywami i ciecierzycą',
    description:
      'Kuskus na bulionie z podsmażoną ciecierzycą, papryką i cukinią, pachnący kminem, kurkumą i cytryną. Roślinna kolacja gotowa w 25 minut, sycąca dzięki strączkom i dobra także na zimno.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['kasza kuskus', 140, 'g'],
      ['bulion warzywny', 250, 'ml'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['papryka żółta', 1, 'szt'],
      ['cukinia', 200, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 25, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['kurkuma', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zagotuj bulion z kurkumą, zalej nim kuskus w misce, przykryj talerzem i odstaw na 5 minut. Potem rozluźnij go widelcem.',
      'Cebulę posiekaj w kostkę, paprykę i cukinię pokrój w kostkę 1,5 cm, ciecierzycę odcedź i opłucz.',
      'Na dużej patelni rozgrzej oliwę i szklij cebulę 3 minuty. Dodaj paprykę i cukinię i smaż 6–7 minut na średnim ogniu, aż zmiękną, ale zachowają kształt.',
      'Dorzuć ciecierzycę, przeciśnięty czosnek, kmin rzymski, paprykę mieloną, sól i pieprz; smaż jeszcze 2–3 minuty, mieszając.',
      'Wymieszaj warzywa z kuskusem, skrop sokiem z cytryny i dodaj posiekaną natkę.',
      'Podawaj na ciepło, z dodatkową ćwiartką cytryny do skropienia.',
    ],
    photo:
      'Golden turmeric couscous tossed with chickpeas, diced yellow pepper and zucchini, fresh parsley and a lemon wedge on the side',
  },
  {
    plan: 'ko-36',
    title: 'Falafel pieczony z sosem jogurtowym i pitą',
    description:
      'Kulki z ciecierzycy z natką, kolendrą i kminem, pieczone zamiast smażenia, podane w picie z pomidorem i chłodnym sosem jogurtowo-ogórkowym. Chrupiące z wierzchu, miękkie w środku.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['ciecierzyca z puszki', 400, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 3, 'szt'],
      ['natka pietruszki', 20, 'g'],
      ['kolendra', 10, 'g'],
      ['kmin rzymski', 3, 'g'],
      ['mąka pszenna', 30, 'g'],
      ['proszek do pieczenia', 3, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['jogurt grecki', 150, 'g'],
      ['ogórek', 100, 'g'],
      ['pita', 2, 'szt'],
      ['pomidor', 1, 'szt'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 200°C z termoobiegiem, blachę wyłóż papierem. Ciecierzycę odcedź i dokładnie osusz ręcznikiem papierowym.',
      'W malakserze zmiel ciecierzycę z cebulą, 2 ząbkami czosnku, natką, kolendrą, kminem, solą i pieprzem na grubą pastę — ma się kleić, ale nie być gładka jak hummus.',
      'Wmieszaj mąkę i proszek do pieczenia. Mokrymi dłońmi uformuj 12–14 kulek wielkości orzecha włoskiego i lekko je spłaszcz.',
      'Ułóż falafele na blasze, posmaruj oliwą z obu stron i piecz 25 minut, w połowie przewracając, aż będą złote i chrupiące.',
      'Przygotuj sos: ogórek zetrzyj na grubych oczkach, odciśnij sok i wymieszaj z jogurtem, ostatnim przeciśniętym ząbkiem czosnku i szczyptą soli.',
      'Pity podgrzej 1–2 minuty w piekarniku, nadziej falafelami i plastrami pomidora, polej sosem jogurtowym i od razu podawaj.',
    ],
    photo:
      'Golden baked falafel balls tucked into warm pita with tomato slices, drizzled with creamy white yogurt cucumber sauce, extra falafel beside',
  },
  {
    plan: 'ko-37',
    title: 'Krem z zielonego groszku z miętą i grzankami',
    description:
      'Aksamitna, intensywnie zielona zupa z mrożonego groszku z nutą mięty i odrobiną śmietanki, podana z chrupiącymi grzankami. Słodkawa, świeża i gotowa w niecałe pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['groszek mrożony', 450, 'g'],
      ['ziemniak', 150, 'g'],
      ['cebula', 1, 'szt'],
      ['masło', 20, 'g'],
      ['bulion warzywny', 600, 'ml'],
      ['mięta', 10, 'g'],
      ['śmietanka 18', 80, 'ml'],
      ['chleb', 80, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę posiekaj, ziemniak obierz i pokrój w kostkę 1 cm.',
      'W garnku roztop masło i szklij cebulę 4 minuty. Dodaj ziemniak, zalej bulionem i gotuj 12 minut, aż ziemniak zmięknie.',
      'Wsyp groszek i gotuj jeszcze 4–5 minut od ponownego zagotowania — nie dłużej, żeby zupa została jasnozielona.',
      'W tym czasie chleb pokrój w kostkę 1,5 cm, skrop oliwą i przypiecz na suchej patelni 4–5 minut, aż grzanki będą złote i chrupiące.',
      'Do zupy dodaj większość listków mięty i zmiksuj blenderem na gładki krem. Wlej śmietankę, dopraw solą i pieprzem, podgrzej bez gotowania.',
      'Rozlej krem do misek, połóż na wierzch grzanki i kilka listków mięty.',
    ],
    photo:
      'Vibrant bright green pea soup with a swirl of cream, golden croutons and small fresh mint leaves on top',
    vessel: 'bowl',
  },
  {
    plan: 'ko-38',
    title: 'Krem z pieczonej papryki z fetą',
    description:
      'Gęsta zupa z papryki i pomidorów upieczonych do lekkiego przypalenia, z wędzoną papryką i śmietanką, podana z pokruszoną fetą i bagietką. Słodko-dymna, rozgrzewająca, idealna na jesienny wieczór.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['papryka czerwona', 4, 'szt'],
      ['pomidor', 2, 'szt'],
      ['cebula', 1, 'szt'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['bulion warzywny', 400, 'ml'],
      ['papryka wędzona mielona', 2, 'g'],
      ['śmietanka 18', 100, 'ml'],
      ['ser feta', 60, 'g'],
      ['bagietka', 100, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 220°C z termoobiegiem. Paprykę oczyść z gniazd nasiennych i pokrój na ćwiartki, pomidory i cebulę na ćwiartki, czosnek zostaw w łupinkach.',
      'Rozłóż warzywa na blasze skórką papryki do góry, skrop oliwą i piecz 25–30 minut, aż skórka papryki mocno się zrumieni i miejscami sczernieje.',
      'Z czosnku wyciśnij miąższ. Przełóż wszystkie warzywa do garnka, zalej bulionem, dodaj wędzoną paprykę i gotuj 5 minut.',
      'Zmiksuj zupę na gładki krem, wlej śmietankę, dopraw solą i pieprzem i podgrzej, nie doprowadzając do wrzenia.',
      'Bagietkę pokrój w ukośne kromki i opiecz 3 minuty w gorącym piekarniku.',
      'Rozlej krem do misek, pokrusz na wierzch fetę i podawaj z ciepłą bagietką.',
    ],
    photo:
      'Smooth deep orange-red roasted pepper soup topped with crumbled white feta and a pinch of smoked paprika, toasted baguette slices alongside',
    vessel: 'bowl',
  },
  {
    plan: 'ko-39',
    title: 'Chłodnik litewski z jajkiem i młodymi ziemniakami',
    description:
      'Różowy chłodnik z botwinki, kefiru i maślanki z chrupiącym ogórkiem, rzodkiewką i mnóstwem koperku, podany z jajkiem na twardo i młodymi ziemniakami. Orzeźwiająca kolacja na upalne dni.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['botwina', 300, 'g'],
      ['burak', 150, 'g'],
      ['kefir', 500, 'ml'],
      ['maślanka', 300, 'ml'],
      ['ogórek', 150, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['koperek', 20, 'g'],
      ['szczypiorek', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['jajko', 4, 'szt'],
      ['ziemniak młody', 300, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Buraczek z botwinki obierz i zetrzyj na grubych oczkach, łodygi pokrój w plasterki 0,5 cm, a liście posiekaj.',
      'Buraka i łodygi zalej 300 ml wody, gotuj 10 minut, dodaj liście i gotuj jeszcze 3 minuty. Dopraw sokiem z cytryny i szczyptą soli, a potem całkowicie ostudź.',
      'Ogórek i rzodkiewkę pokrój w drobną kostkę, koperek i szczypiorek posiekaj. Czosnek przeciśnij.',
      'Do zimnej botwinki wlej kefir i maślankę, dodaj ogórek, rzodkiewkę, zioła i czosnek; dopraw solą i pieprzem. Wstaw do lodówki na co najmniej godzinę.',
      'Jajka ugotuj na twardo (10 minut), ostudź i przekrój na ćwiartki. Młode ziemniaki ugotuj w mundurkach w osolonej wodzie przez 15–18 minut.',
      'Rozlej schłodzony chłodnik do misek, ułóż na wierzchu ćwiartki jajek, posyp koperkiem i podawaj z ciepłymi ziemniakami.',
    ],
    photo:
      'Bright pink chilled beet soup with diced cucumber and radish, quartered hard-boiled eggs and fresh dill on top, small boiled new potatoes on the side',
    vessel: 'bowl',
  },
  {
    plan: 'ko-40',
    title: 'Domowe nuggetsy z kurczaka z surówką z marchewki',
    description:
      'Kawałki piersi kurczaka w chrupiącej panierce z płatków kukurydzianych, pieczone w piekarniku, podane z surówką z marchewki i jabłka. Lepsze niż z fast foodu, a dzieci jedzą je bez namawiania.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 400, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 30, 'g'],
      ['płatki kukurydziane', 60, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['marchew', 200, 'g'],
      ['jabłko', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['ketchup', 40, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 210°C z termoobiegiem, blachę wyłóż papierem. Filet pokrój w kawałki ok. 3 × 4 cm, posól, popieprz i oprósz papryką i czosnkiem granulowanym.',
      'Płatki kukurydziane pokrusz w woreczku wałkiem na drobne okruchy. Przygotuj trzy talerze: z mąką, z roztrzepanym jajkiem i z płatkami.',
      'Obtaczaj kawałki kurczaka kolejno w mące, jajku i płatkach, dociskając panierkę dłonią. Ułóż na blasze i skrop olejem.',
      'Piecz 15–18 minut, w połowie przewracając, aż panierka będzie złota, a mięso w środku białe i soczyste.',
      'W tym czasie zrób surówkę: marchew i jabłko zetrzyj na tarce o grubych oczkach, skrop sokiem z cytryny i dopraw szczyptą soli.',
      'Podawaj nuggetsy od razu, z surówką i ketchupem do maczania.',
    ],
    photo:
      'Golden crispy cornflake-crusted chicken nuggets on a plate with grated carrot and apple salad and a small bowl of ketchup',
  },
  {
    plan: 'ko-41',
    title: 'Kurczak z grilla z sałatką pomidorową',
    description:
      'Soczysta pierś kurczaka marynowana w oliwie, czosnku i oregano, grillowana na patelni i podana z sałatką z pomidorów, ogórka i czerwonej cebuli. Lekka kolacja z chrupiącą bagietką do sosu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['czosnek', 2, 'szt'],
      ['oregano', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['pomidor', 3, 'szt'],
      ['ogórek', 150, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['bazylia', 10, 'g'],
      ['ocet balsamiczny', 10, 'ml'],
      ['bagietka', 100, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filet przekrój poziomo na cieńsze płaty grubości ok. 1,5 cm. Wymieszaj z 15 ml oliwy, przeciśniętym czosnkiem, oregano, papryką, solą i pieprzem; odstaw na 15 minut.',
      'Patelnię grillową rozgrzej mocno i grilluj kurczaka po 4–5 minut z każdej strony, aż będzie miał wyraźne paski, a sok wypływający po nakłuciu będzie przezroczysty.',
      'Zdejmij mięso na deskę i odstaw na 5 minut, żeby soki się rozeszły, a potem pokrój w plastry.',
      'Pomidory pokrój w cząstki, ogórek w półplasterki, cebulę w cienkie piórka. Wymieszaj z porwaną bazylią, resztą oliwy, octem balsamicznym i szczyptą soli.',
      'Bagietkę pokrój w kromki i podpiecz 1–2 minuty na tej samej patelni.',
      'Ułóż plastry kurczaka obok sałatki pomidorowej i podawaj z bagietką do zebrania sosu.',
    ],
    photo:
      'Sliced grilled chicken breast with charred grill marks next to a fresh salad of tomato wedges, cucumber, red onion and basil, baguette slices on the side',
  },
  {
    plan: 'ko-42',
    title: 'Kurczak zapiekany z pomidorem i mozzarellą',
    description:
      'Pierś kurczaka przykryta plastrami pomidora i mozzarelli, zapieczona z czosnkiem i bazylią, aż ser się rozpłynie i zarumieni. Prosta kolacja w stylu caprese na ciepło, z rukolą na talerzu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['pomidor', 2, 'szt'],
      ['mozzarella', 125, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['oregano', 1, 'g'],
      ['bazylia', 10, 'g'],
      ['rukola', 60, 'g'],
      ['ocet balsamiczny', 10, 'ml'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 200°C (góra–dół). Filety przekrój wzdłuż na dwa cieńsze płaty, natrzyj oliwą, przeciśniętym czosnkiem, oregano, solą i pieprzem.',
      'Ułóż mięso w naczyniu żaroodpornym i piecz 12 minut.',
      'Pomidory i mozzarellę pokrój w plastry grubości ok. 0,5 cm.',
      'Wyjmij naczynie, na każdym kawałku kurczaka ułóż na przemian plastry pomidora i mozzarelli. Piecz jeszcze 10–12 minut, aż ser się roztopi i lekko zezłoci.',
      'Rukolę skrop octem balsamicznym.',
      'Podawaj kurczaka posypanego świeżą bazylią, z rukolą obok, polanego sosem z naczynia.',
    ],
    photo:
      'Baked chicken breasts topped with overlapping tomato slices and melted golden mozzarella, fresh basil leaves, arugula on the side',
  },
  {
    plan: 'ko-43',
    title: 'Kotleciki z indyka i cukinii z sosem koperkowym',
    description:
      'Małe, puszyste kotleciki z mielonego indyka i startej cukinii, które zostają soczyste nawet następnego dnia. Podane z chłodnym sosem jogurtowo-koperkowym i ogórkiem — lekka kolacja, świetna też do pudełka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['indyk mielony', 400, 'g'],
      ['cukinia', 250, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 15, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['ogórek', 150, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cukinię zetrzyj na tarce o grubych oczkach, posól szczyptą soli, odstaw na 5 minut i mocno odciśnij z soku w dłoniach.',
      'W misce połącz indyka, cukinię, jajko, bułkę tartą, 1 przeciśnięty ząbek czosnku, połowę posiekanego koperku, sól i pieprz. Wyrabiaj masę 2 minuty.',
      'Zwilżonymi dłońmi formuj małe kotleciki o średnicy ok. 6 cm (wyjdzie ich ok. 10).',
      'Smaż na rozgrzanym oleju na średnim ogniu po 4–5 minut z każdej strony, aż będą złote i ścięte w środku.',
      'Wymieszaj jogurt z resztą koperku, drugim przeciśniętym ząbkiem czosnku i szczyptą soli. Ogórek pokrój w plasterki.',
      'Podawaj kotleciki z sosem koperkowym i plasterkami ogórka.',
    ],
    photo:
      'Small golden turkey and zucchini patties with a bowl of white yogurt dill sauce and fresh cucumber slices',
  },
  {
    plan: 'ko-44',
    title: 'Leniwe gołąbki w sosie pomidorowym',
    description:
      'Wszystko, co lubisz w gołąbkach — mięso, ryż i kapusta — ale bez zawijania: pulpety duszone w gęstym sosie pomidorowym z nutą majeranku. Jeszcze lepsze odgrzane następnego dnia.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['wieprzowina mielona', 300, 'g'],
      ['kapusta biała', 300, 'g'],
      ['ryż biały', 60, 'g'],
      ['cebula', 1, 'szt'],
      ['jajko', 1, 'szt'],
      ['majeranek', 2, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['passata pomidorowa', 400, 'ml'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['śmietana 18', 40, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ryż ugotuj w osolonej wodzie przez 12 minut (ma być lekko twardy) i odcedź. Kapustę poszatkuj drobno, zalej wrzątkiem na 5 minut, odcedź i odciśnij.',
      'Cebulę posiekaj i zeszklij na połowie oleju przez 4 minuty.',
      'W misce połącz mięso, ryż, kapustę, cebulę, jajko, majeranek, sól i pieprz. Wyrób masę i uformuj 8 podłużnych kotlecików.',
      'Obsmaż je na reszcie oleju po 2 minuty z każdej strony, aż się zrumienią.',
      'Passatę wymieszaj z koncentratem i 100 ml wody, zalej gołąbki, przykryj i duś na małym ogniu 25 minut. Pod koniec zahartuj śmietanę łyżką sosu i wmieszaj do garnka.',
      'Podawaj leniwe gołąbki polane sosem, posypane posiekaną natką.',
    ],
    photo:
      'Oval lazy cabbage roll patties with visible rice and cabbage in thick creamy tomato sauce, sprinkled with chopped parsley',
  },
  {
    plan: 'ko-45',
    title: 'Kiełbasa pieczona z cebulką i chlebem',
    description:
      'Nacięta śląska kiełbasa pieczona na blasze na grubej warstwie cebuli, która karmelizuje się w jej tłuszczu. Podana z musztardą, ogórkiem kiszonym i żytnim chlebem — jak z ogniska, tylko w domu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['kiełbasa śląska', 300, 'g'],
      ['cebula', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['majeranek', 1, 'g'],
      ['musztarda', 20, 'g'],
      ['ogórek kiszony', 100, 'g'],
      ['chleb żytni', 100, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 200°C (góra–dół). Cebulę pokrój w grube piórka i wymieszaj na blasze lub w naczyniu z olejem, majerankiem i pieprzem.',
      'Kiełbasę natnij ukośnie co 1,5 cm, nie przecinając do końca, i ułóż na cebuli.',
      'Piecz 25–30 minut, w połowie mieszając cebulę, aż kiełbasa się rozchyli i zrumieni, a cebula będzie miękka i złotobrązowa.',
      'Ogórki kiszone pokrój wzdłuż na ćwiartki, chleb w kromki.',
      'Podawaj kiełbasę na cebulce z musztardą, ogórkiem kiszonym i żytnim chlebem.',
    ],
    photo:
      'Scored roasted sausages with blistered skin on a bed of caramelized onions, dollop of mustard, pickled cucumber spears and rye bread slices',
  },
  {
    plan: 'ko-46',
    title: 'Ryż z kiełbasą i papryką po kreolsku',
    description:
      'Jednogarnkowy ryż duszony z wędzoną kiełbasą, papryką, selerem naciowym i pomidorami, doprawiony wędzoną papryką i oregano. Domowa wersja jambalai: rozgrzewająca, lekko pikantna, z jednym garnkiem do zmywania.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['ryż biały', 150, 'g'],
      ['kiełbasa wędzona', 200, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['papryka zielona', 1, 'szt'],
      ['seler naciowy', 60, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['bulion drobiowy', 300, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['oregano', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kiełbasę pokrój w półplasterki 0,5 cm, paprykę w kostkę 1,5 cm, seler naciowy w plasterki, cebulę posiekaj, czosnek przeciśnij.',
      'W szerokim garnku rozgrzej olej i podsmaż kiełbasę 4 minuty, aż się zrumieni. Dodaj cebulę, paprykę i seler i smaż 5 minut.',
      'Dorzuć czosnek, paprykę wędzoną, ostrą, oregano i pieprz, a po 30 sekundach wsyp suchy ryż i mieszaj minutę, aż ziarna pokryją się tłuszczem.',
      'Wlej pomidory i bulion, zagotuj, przykryj i duś na małym ogniu 18–20 minut, aż ryż wchłonie płyn i będzie miękki. Nie mieszaj w trakcie.',
      'Zdejmij z ognia, zostaw pod przykryciem na 5 minut, a potem rozluźnij widelcem.',
      'Nałóż na talerze i posyp posiekaną natką.',
    ],
    photo:
      'Reddish tomato rice with sliced smoked sausage, diced red and green peppers and celery, garnished with chopped parsley',
  },
  {
    plan: 'ko-47',
    title: 'Makaron sojowy z kurczakiem i warzywami',
    description:
      'Szklisty makaron sojowy wymieszany z kurczakiem i chrupiącymi warzywami, w sosie sojowym z czosnkiem, imbirem i olejem sezamowym. Kolacja w stylu azjatyckim w 25 minut, z jednej patelni.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['makaron sojowy', 100, 'g'],
      ['filet z kurczaka', 250, 'g'],
      ['marchew', 1, 'szt'],
      ['papryka czerwona', 1, 'szt'],
      ['kapusta pekińska', 150, 'g'],
      ['cebula dymka', 40, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos sojowy', 30, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['olej sezamowy', 5, 'ml'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Makaron zalej wrzątkiem na 5–7 minut (wg opakowania), odcedź, przelej zimną wodą i przetnij nożyczkami na krótsze kawałki.',
      'Kurczaka pokrój w cienkie paski, marchew i paprykę w słupki, kapustę w paski 1 cm, dymkę w ukośne plasterki. Czosnek i imbir drobno posiekaj.',
      'Na mocno rozgrzanej patelni lub w woku na oleju rzepakowym smaż kurczaka 4–5 minut, aż się zrumieni. Zdejmij na talerz.',
      'Na tej samej patelni smaż marchew i paprykę 3 minuty, dodaj kapustę, czosnek i imbir i smaż jeszcze 2 minuty — warzywa mają zostać chrupiące.',
      'Dodaj makaron, kurczaka, sos sojowy i olej sezamowy; mieszaj szczypcami minutę, aż makaron nasiąknie sosem.',
      'Nałóż na talerze, posyp sezamem i dymką.',
    ],
    photo:
      'Glossy glass noodles stir-fried with chicken strips, carrot and red pepper julienne and napa cabbage, sprinkled with sesame seeds and green onion',
  },
  {
    plan: 'ko-48',
    title: 'Tortellini w sosie śmietanowym z szynką i groszkiem',
    description:
      'Tortellini z serem w kremowym sosie śmietanowym z kostkami szynki, zielonym groszkiem i parmezanem. Szybka, bardzo sycąca kolacja w 20 minut, gdy nie ma siły na gotowanie.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['tortellini z serem', 300, 'g'],
      ['szynka', 100, 'g'],
      ['groszek mrożony', 100, 'g'],
      ['śmietanka 18', 150, 'ml'],
      ['masło', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['ser parmezan', 20, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zagotuj osoloną wodę i ugotuj tortellini według opakowania (zwykle 3–5 minut od wypłynięcia). Odlej 50 ml wody z gotowania i odcedź.',
      'Szynkę pokrój w kostkę 1 cm, czosnek posiekaj.',
      'Na patelni roztop masło, podsmaż szynkę 2 minuty, dodaj czosnek i smaż 30 sekund.',
      'Wsyp groszek, wlej śmietankę, dodaj gałkę i pieprz; gotuj 3 minuty, aż sos lekko zgęstnieje.',
      'Przełóż tortellini do sosu, dodaj połowę startego parmezanu i trochę wody z gotowania, jeśli sos jest za gęsty. Wymieszaj.',
      'Podawaj od razu, posypane resztą parmezanu i świeżo zmielonym pieprzem.',
    ],
    photo:
      'Cheese tortellini coated in creamy white sauce with diced ham and bright green peas, grated parmesan and black pepper on top',
  },
  {
    plan: 'ko-49',
    title: 'Makaron z łososiem i szpinakiem',
    description:
      'Tagliatelle w śmietanowym sosie z kawałkami pieczonego łososia, młodym szpinakiem, czosnkiem i skórką z cytryny. Delikatne i eleganckie danie, a przygotujesz je w niespełna pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['makaron tagliatelle', 160, 'g'],
      ['łosoś', 250, 'g'],
      ['szpinak', 150, 'g'],
      ['śmietanka 18', 150, 'ml'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['cytryna', 40, 'g'],
      ['ser parmezan', 20, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron w osolonej wodzie al dente według opakowania. Odlej 100 ml wody z gotowania i odcedź.',
      'Łososia pozbaw skóry i pokrój w kostkę 2–3 cm, posól i popieprz.',
      'Na dużej patelni rozgrzej oliwę i smaż łososia 3–4 minuty, delikatnie przewracając, aż się zetnie. Zdejmij na talerz.',
      'Na tę samą patelnię wrzuć posiekany czosnek na 30 sekund, dodaj szpinak i mieszaj, aż zwiędnie. Wlej śmietankę, dodaj otartą skórkę i 1 łyżkę soku z cytryny; gotuj 2 minuty.',
      'Dodaj makaron i łososia, wymieszaj delikatnie, w razie potrzeby rozrzedź sos wodą z makaronu.',
      'Podawaj posypane startym parmezanem i pieprzem.',
    ],
    photo:
      'Creamy tagliatelle ribbons with flaky pink salmon chunks and wilted green spinach, grated parmesan and lemon zest on top',
  },
  {
    plan: 'ko-50',
    title: 'Naleśniki z szynką i serem zapiekane',
    description:
      'Domowe naleśniki zwinięte z szynką i żółtym serem, zapieczone pod śmietaną, aż brzegi zrobią się chrupiące, a ser ciągnący. Świetny sposób na sycącą kolację, którą można przygotować wcześniej i tylko zapiec.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 125, 'g'],
      ['mleko', 250, 'ml'],
      ['jajko', 2, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['szynka', 150, 'g'],
      ['ser gouda', 100, 'g'],
      ['śmietana 18', 80, 'g'],
      ['szczypiorek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zmiksuj mąkę, mleko, jajka, 5 ml oleju, sól i 50 ml wody na gładkie ciasto o konsystencji płynnej śmietanki. Odstaw na 10 minut.',
      'Na dobrze rozgrzanej patelni posmarowanej odrobiną oleju usmaż 6 cienkich naleśników, po ok. 1 minucie z każdej strony.',
      'Piekarnik nagrzej do 200°C (góra–dół). Ser zetrzyj na grubych oczkach, szynkę pokrój w paski.',
      'Na każdym naleśniku ułóż szynkę i 2/3 sera, zwiń w rulon i ułóż ciasno w naczyniu żaroodpornym.',
      'Posmaruj naleśniki śmietaną wymieszaną z pieprzem, posyp resztą sera i zapiekaj 15 minut, aż ser się zarumieni.',
      'Podawaj gorące, posypane posiekanym szczypiorkiem.',
    ],
    photo:
      'Rolled crepes filled with ham and cheese baked in a dish under a golden bubbling cheese crust, sprinkled with chopped chives',
  },
  {
    plan: 'ko-51',
    title: 'Sałatka z kurczakiem i truskawkami',
    description:
      'Roszponka z grillowanym kurczakiem, soczystymi truskawkami, fetą i orzechami włoskimi, polana balsamicznym dressingiem z miodem. Słodko-słone połączenie na letnie wieczory, podane z bagietką.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 250, 'g'],
      ['truskawka', 250, 'g'],
      ['roszponka', 80, 'g'],
      ['ser feta', 80, 'g'],
      ['orzech włoski', 30, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ocet balsamiczny', 15, 'ml'],
      ['miód', 10, 'g'],
      ['bagietka', 80, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka przekrój poziomo na cienkie płaty, posól, popieprz i natrzyj łyżeczką oliwy. Grilluj na rozgrzanej patelni po 4 minuty z każdej strony, odstaw na 5 minut i pokrój w paski.',
      'Orzechy uprażaj na suchej patelni 2–3 minuty, aż zaczną pachnieć, i grubo posiekaj.',
      'Truskawki umyj, odszypułkuj i pokrój na ćwiartki. Roszponkę opłucz i osusz.',
      'Wymieszaj resztę oliwy z octem balsamicznym, miodem i szczyptą pieprzu.',
      'Na talerzach rozłóż roszponkę, truskawki i kurczaka, pokrusz fetę i posyp orzechami.',
      'Polej dressingiem tuż przed podaniem i podawaj z pokrojoną bagietką.',
    ],
    photo:
      'Lamb lettuce salad with sliced grilled chicken, quartered red strawberries, crumbled white feta and walnuts, drizzled with dark balsamic dressing',
  },
  {
    plan: 'ko-52',
    title: 'Sałatka z kaszą gryczaną i fetą',
    description:
      'Prażona kasza gryczana z pomidorem, ogórkiem, czerwoną cebulą, oliwkami i fetą, doprawiona cytrynowym dressingiem. Wyrazista, orzechowa w smaku i idealna do pudełka, bo z czasem tylko zyskuje.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['kasza gryczana', 120, 'g'],
      ['ser feta', 120, 'g'],
      ['pomidor', 2, 'szt'],
      ['ogórek', 200, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['cytryna', 30, 'g'],
      ['oregano', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę ugotuj w 250 ml osolonej wody pod przykryciem przez 15 minut na małym ogniu, aż wchłonie wodę. Rozłóż na talerzu i ostudź.',
      'Pomidory i ogórek pokrój w kostkę 1,5 cm, cebulę w cienkie piórka, oliwki w plasterki, natkę posiekaj.',
      'Wymieszaj oliwę z sokiem z cytryny, oregano i pieprzem.',
      'W misce połącz ostudzoną kaszę z warzywami, oliwkami, natką i dressingiem.',
      'Fetę pokrój w kostkę i delikatnie wmieszaj, żeby się nie rozpadła.',
      'Podawaj od razu albo po 30 minutach w lodówce, gdy kasza przejdzie dressingiem.',
    ],
    photo:
      'Buckwheat groats salad with diced tomato and cucumber, red onion slivers, black olive slices, cubes of feta and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'ko-53',
    title: 'Sałatka z soczewicą, pieczoną marchewką i kozim serem',
    description:
      'Zielona soczewica z pieczoną w kminie marchewką, rukolą i kawałkami koziego sera, polana miodowo-musztardowym dressingiem. Ciepła albo zimna, pożywna i roślinna w sercu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['soczewica zielona', 120, 'g'],
      ['marchew', 400, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['cebula czerwona', 60, 'g'],
      ['rukola', 60, 'g'],
      ['ser kozi', 80, 'g'],
      ['miód', 10, 'g'],
      ['musztarda', 10, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 210°C z termoobiegiem. Marchew obierz i pokrój ukośnie w plastry grubości 1 cm.',
      'Wymieszaj marchew z połową oliwy, kminem, solą i pieprzem i piecz na blasze 25 minut, aż zmięknie i przyrumieni się na brzegach.',
      'Soczewicę opłucz i gotuj w dużej ilości wody 20–25 minut, aż będzie miękka, ale nierozgotowana. Pod koniec posól i odcedź.',
      'Przygotuj dressing: wymieszaj resztę oliwy z sokiem z cytryny, miodem i musztardą. Cebulę pokrój w cienkie piórka.',
      'Wymieszaj ciepłą soczewicę z dressingiem, cebulą i posiekaną natką, a potem delikatnie z rukolą i marchewką.',
      'Nałóż sałatkę na talerze i pokrusz na wierzch kozi ser.',
    ],
    photo:
      'Green lentil salad with glossy roasted carrot coins, fresh arugula, thin red onion and crumbled white goat cheese',
    vessel: 'bowl',
  },
  {
    plan: 'ko-54',
    title: 'Sałatka nicejska z jajkiem i fasolką',
    description:
      'Klasyczna sałatka z Nicei: tuńczyk, jajka na twardo, fasolka szparagowa, młode ziemniaki, pomidory i czarne oliwki na chrupiącej sałacie, z musztardowym winegretem. Pełnowartościowa kolacja w jednej misce.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['tuńczyk w puszce', 170, 'g'],
      ['jajko', 3, 'szt'],
      ['fasolka szparagowa', 200, 'g'],
      ['ziemniak młody', 300, 'g'],
      ['pomidor', 2, 'szt'],
      ['sałata rzymska', 100, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['ocet winny', 10, 'ml'],
      ['musztarda', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki ugotuj w mundurkach w osolonej wodzie przez 15 minut. W ostatnich 5 minutach dorzuć fasolkę pozbawioną końcówek, potem odcedź i przelej zimną wodą.',
      'Jajka ugotuj na twardo (10 minut), ostudź, obierz i pokrój na ćwiartki.',
      'Przygotuj winegret: wymieszaj oliwę, ocet winny, musztardę, szczyptę soli i pieprz.',
      'Ziemniaki przekrój na połówki, pomidory pokrój w cząstki, cebulę w cienkie piórka, sałatę porwij. Tuńczyka odcedź i podziel na większe kawałki.',
      'Na talerzach ułóż sałatę, a na niej osobnymi grupami ziemniaki, fasolkę, pomidory, tuńczyka, jajka i oliwki; posyp cebulą.',
      'Polej sałatkę winegretem tuż przed podaniem.',
    ],
    photo:
      'Composed nicoise salad with romaine, tuna chunks, quartered boiled eggs, green beans, halved new potatoes, tomato wedges and black olives',
  },
  {
    plan: 'ko-55',
    title: 'Sałatka z makaronem, pesto i mozzarellą',
    description:
      'Makaronowe świderki oblepione zielonym pesto, z pomidorkami koktajlowymi, rukolą i kawałkami mozzarelli. Robi się ją w kwadrans i świetnie znosi drogę w pudełku do pracy albo na piknik.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['makaron świder', 160, 'g'],
      ['pesto bazyliowe', 50, 'g'],
      ['mozzarella', 125, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['rukola', 40, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['cytryna', 20, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron w osolonej wodzie al dente według opakowania, odcedź i przelej zimną wodą, żeby się nie sklejał.',
      'Pomidorki przekrój na połówki, mozzarellę odsącz i porwij na kawałki wielkości orzecha.',
      'Pesto rozrzedź oliwą i sokiem z cytryny, dopraw pieprzem.',
      'Makaron wymieszaj z pesto, dodaj pomidorki i mozzarellę.',
      'Tuż przed podaniem wmieszaj rukolę, żeby nie zwiędła.',
      'Podawaj od razu albo schłodzoną, z odrobiną świeżo zmielonego pieprzu na wierzchu.',
    ],
    photo:
      'Fusilli pasta salad coated in green basil pesto with halved cherry tomatoes, torn white mozzarella pieces and fresh arugula',
    vessel: 'bowl',
  },
  {
    plan: 'ko-56',
    title: 'Sałatka z brokułem, jajkiem i słonecznikiem',
    description:
      'Chrupiące różyczki brokułu z jajkami na twardo, kukurydzą, czerwoną cebulą i prażonym słonecznikiem, w lekkim sosie jogurtowo-majonezowym z czosnkiem. Prosta, tania i bardzo sycąca.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['brokuł', 400, 'g'],
      ['jajko', 4, 'szt'],
      ['kukurydza z puszki', 100, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['słonecznik łuszczony', 30, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['majonez', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Brokuł podziel na małe różyczki i gotuj w osolonej wodzie 3 minuty, aż zrobi się intensywnie zielony, ale pozostanie chrupiący. Odcedź i przelej lodowatą wodą.',
      'Jajka ugotuj na twardo (10 minut), ostudź, obierz i pokrój w kostkę.',
      'Słonecznik uprażaj na suchej patelni 2–3 minuty, aż się zezłoci.',
      'Cebulę drobno posiekaj, kukurydzę odcedź. Jogurt wymieszaj z majonezem, przeciśniętym czosnkiem, solą i pieprzem.',
      'W misce połącz brokuł, jajka, kukurydzę i cebulę, dodaj sos i delikatnie wymieszaj.',
      'Przed podaniem posyp sałatkę prażonym słonecznikiem.',
    ],
    photo:
      'Broccoli florets with chopped hard-boiled egg, yellow corn and red onion in creamy white dressing, topped with toasted sunflower seeds',
    vessel: 'bowl',
  },
  {
    plan: 'ko-57',
    title: 'Sałatka hawajska z kurczakiem i ananasem',
    description:
      'Imprezowa klasyka w wersji na kolację: podsmażony kurczak z curry, ananas, kukurydza, gouda i chrupiąca sałata lodowa w jogurtowo-majonezowym sosie. Słodko-słona, lubiana przez wszystkich.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['curry', 3, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ananas z puszki', 200, 'g'],
      ['kukurydza z puszki', 150, 'g'],
      ['ser gouda', 80, 'g'],
      ['sałata lodowa', 150, 'g'],
      ['majonez', 40, 'g'],
      ['jogurt naturalny', 80, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę 1,5 cm, oprósz połową curry, solą i pieprzem.',
      'Smaż na rozgrzanym oleju 6–7 minut, aż kawałki będą złote i upieczone w środku. Ostudź.',
      'Ananasa i kukurydzę odcedź, ananasa pokrój w kostkę. Goudę pokrój w kostkę 1 cm, sałatę posiekaj w paski.',
      'Majonez wymieszaj z jogurtem i resztą curry.',
      'W misce połącz kurczaka, ananasa, kukurydzę, ser i sałatę, dodaj sos i wymieszaj.',
      'Podawaj od razu, żeby sałata została chrupiąca, z odrobiną pieprzu na wierzchu.',
    ],
    photo:
      'Hawaiian salad with golden curry chicken cubes, pineapple chunks, sweet corn, yellow cheese cubes and shredded iceberg lettuce in creamy dressing',
    vessel: 'bowl',
  },
  {
    plan: 'ko-58',
    title: 'Sałatka z tortellini i pomidorkami',
    description:
      'Tortellini z serem wymieszane z pomidorkami koktajlowymi, ogórkiem, zielonymi oliwkami i rukolą, skropione balsamicznym winegretem i posypane parmezanem. Szybka kolacja w śródziemnomorskim klimacie.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['tortellini z serem', 250, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['ogórek', 150, 'g'],
      ['oliwka zielona', 40, 'g'],
      ['rukola', 50, 'g'],
      ['ser parmezan', 20, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ocet balsamiczny', 10, 'ml'],
      ['czosnek', 1, 'szt'],
      ['oregano', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj tortellini w osolonej wodzie według opakowania, odcedź, przelej zimną wodą i skrop odrobiną oliwy.',
      'Pomidorki przekrój na połówki, ogórek pokrój w półplasterki, oliwki w plasterki.',
      'Wymieszaj resztę oliwy z octem balsamicznym, przeciśniętym czosnkiem, oregano i pieprzem.',
      'W misce połącz tortellini, pomidorki, ogórek i oliwki, polej winegretem i wymieszaj.',
      'Przed podaniem dodaj rukolę i posyp całość startym parmezanem.',
    ],
    photo:
      'Cheese tortellini salad with halved cherry tomatoes, cucumber slices, green olive rings, arugula and shaved parmesan',
    vessel: 'bowl',
  },
  {
    plan: 'ko-59',
    title: 'Sałatka ryżowa z kurczakiem curry',
    description:
      'Złoty ryż basmati z kurczakiem w curry, ananasem, kukurydzą, papryką i dymką, połączony lekkim sosem jogurtowym. Sprawdza się na kolację, na imprezę i do pudełka — im dłużej postoi, tym lepsza.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['ryż basmati', 120, 'g'],
      ['filet z kurczaka', 250, 'g'],
      ['curry', 6, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kukurydza z puszki', 100, 'g'],
      ['ananas z puszki', 150, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cebula dymka', 30, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['majonez', 30, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ryż ugotuj w osolonej wodzie z 2 g curry na sypko (ok. 12 minut), odcedź i rozłóż na płaskim talerzu do ostygnięcia.',
      'Kurczaka pokrój w kostkę 1,5 cm, oprósz 2 g curry, solą i pieprzem i smaż na oleju 6–7 minut, aż się zrumieni. Ostudź.',
      'Paprykę pokrój w drobną kostkę, dymkę w plasterki. Ananasa i kukurydzę odcedź, ananasa pokrój w kostkę.',
      'Jogurt wymieszaj z majonezem i resztą curry.',
      'Połącz ryż, kurczaka, warzywa i ananasa, dodaj sos i wymieszaj. Wstaw do lodówki na 15 minut, żeby smaki się przegryzły.',
      'Podawaj posypane zieloną częścią dymki.',
    ],
    photo:
      'Golden curry rice salad with chicken pieces, pineapple, sweet corn, diced red pepper and sliced green onion',
    vessel: 'bowl',
  },
  {
    plan: 'ko-60',
    title: 'Sałatka z indykiem, gruszką i serem pleśniowym',
    description:
      'Plastry smażonego w tymianku indyka na roszponce z soczystą gruszką, kremowym serem pleśniowym i orzechami, polane miodowo-musztardowym dressingiem. Wykwintnie wyglądająca, a prosta kolacja na jesień.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['filet z indyka', 250, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['gruszka', 1, 'szt'],
      ['ser pleśniowy', 80, 'g'],
      ['roszponka', 80, 'g'],
      ['orzech włoski', 30, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ocet balsamiczny', 10, 'ml'],
      ['miód', 15, 'g'],
      ['musztarda', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Indyka pokrój w plastry grubości 1 cm, lekko rozbij, natrzyj tymiankiem, solą i pieprzem.',
      'Smaż na rozgrzanym oleju po 3 minuty z każdej strony, aż będzie złoty i nie będzie różowy w środku. Odstaw na 3 minuty i pokrój w paski.',
      'Orzechy uprażaj na suchej patelni 2–3 minuty i grubo posiekaj.',
      'Gruszkę umyj, usuń gniazdo nasienne i pokrój w cienkie cząstki. Ser pleśniowy pokrój w kawałki.',
      'Wymieszaj oliwę, ocet balsamiczny, miód i musztardę na gładki dressing.',
      'Na roszponce ułóż indyka, gruszkę i ser, posyp orzechami i polej dressingiem tuż przed podaniem.',
    ],
    photo:
      'Lamb lettuce topped with sliced golden turkey, thin pear wedges, chunks of blue cheese and walnuts, drizzled with honey mustard dressing',
  },
  {
    plan: 'ko-61',
    title: 'Pulled pork w bułce z coleslawem',
    description:
      'Łopatka wieprzowa pieczona powoli w przyprawach, aż rozpada się na włókna, wymieszana z sosem barbecue i podana w bułce z chrupiącym coleslawem. Zajmuje czas, ale samej pracy jest niewiele.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 240,
    servings: 2,
    ingredients: [
      ['łopatka wieprzowa', 320, 'g'],
      ['papryka wędzona mielona', 5, 'g'],
      ['czosnek granulowany', 3, 'g'],
      ['cukier brązowy', 10, 'g'],
      ['sos barbecue', 80, 'g'],
      ['bułka do hamburgera', 2, 'szt'],
      ['kapusta biała', 200, 'g'],
      ['marchew', 1, 'szt'],
      ['majonez', 20, 'g'],
      ['jogurt naturalny', 50, 'g'],
      ['ocet jabłkowy', 10, 'ml'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 150°C (góra–dół). Wymieszaj paprykę wędzoną, czosnek granulowany, cukier, 2 g soli i pieprz i natrzyj tą mieszanką łopatkę ze wszystkich stron.',
      'Włóż mięso do małego naczynia żaroodpornego, wlej na dno 100 ml wody i szczelnie przykryj pokrywką albo folią.',
      'Piecz 3–3,5 godziny, aż mięso będzie tak miękkie, że rozejdzie się pod widelcem. W połowie sprawdź, czy na dnie jest płyn, w razie potrzeby dolej wody.',
      'W tym czasie zrób coleslaw: kapustę poszatkuj bardzo cienko, marchew zetrzyj na grubych oczkach, wymieszaj z majonezem, jogurtem, octem i resztą soli. Schłódź w lodówce.',
      'Gotowe mięso rozszarp dwoma widelcami, wymieszaj z sosem barbecue i 2–3 łyżkami soku z naczynia.',
      'Bułki przekrój i opiecz przekrojem w dół na suchej patelni. Nałóż na nie mięso i coleslaw, przykryj wierzchami i podawaj.',
    ],
    photo:
      'Toasted burger bun piled high with glossy shredded barbecue pork and creamy white-orange coleslaw, extra coleslaw on the side',
    vessel: 'board',
  },
  {
    plan: 'ko-62',
    title: 'Quesadilla z kurczakiem i papryką',
    description:
      'Chrupiące tortille wypełnione przyprawionym kurczakiem, papryką, czerwoną cebulą i ciągnącą się mozzarellą, przypieczone na patelni i podane z jogurtowym dipem. Szybka kolacja do jedzenia rękami.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 4, 'szt'],
      ['filet z kurczaka', 250, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cebula czerwona', 60, 'g'],
      ['mozzarella tarta', 120, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['jogurt naturalny', 100, 'g'],
      ['limonka', 20, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w cienkie paski, oprósz papryką, kminem, solą i pieprzem. Paprykę pokrój w paski, cebulę w piórka.',
      'Na patelni rozgrzej olej i smaż kurczaka 4 minuty, dodaj paprykę i cebulę i smaż jeszcze 4 minuty, aż warzywa zmiękną.',
      'Na połowie każdej tortilli rozłóż część mozzarelli, farsz z kurczakiem i znów trochę sera, a potem złóż placek na pół.',
      'Piecz quesadille na suchej patelni na średnim ogniu po 2–3 minuty z każdej strony, dociskając łopatką, aż będą złote, a ser się roztopi.',
      'Jogurt wymieszaj z sokiem z limonki i szczyptą soli.',
      'Pokrój każdą quesadillę na 3 trójkąty i podawaj z jogurtowym dipem.',
    ],
    photo:
      'Golden crispy quesadilla triangles oozing melted cheese with chicken and red pepper strips inside, small bowl of white yogurt dip and lime wedge',
    vessel: 'board',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
