/**
 * Katalog 500 — Kolacje, część C: pozycje ko-63 … ko-94
 * z `prisma/catalog/katalog-500-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'ko-63',
    title: 'Calzone z szynką i pieczarkami',
    description:
      'Zamknięta pizza z domowego ciasta drożdżowego, a w środku szynka, podsmażone pieczarki i ciągnąca się mozzarella. Chrupiąca z wierzchu, soczysta w środku — dobra na piątkowy wieczór i do odgrzania następnego dnia.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 220, 'g'],
      ['drożdże', 10, 'g'],
      ['cukier', 3, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['sól', 3, 'g'],
      ['pieczarka', 150, 'g'],
      ['szynka', 100, 'g'],
      ['mozzarella', 100, 'g'],
      ['passata pomidorowa', 100, 'ml'],
      ['oregano', 2, 'g'],
    ],
    steps: [
      'Rozetrzyj drożdże z cukrem, zalej letnią wodą (140 ml) i odstaw na 10 minut, aż się spienią. Dodaj mąkę, 3 g soli i połowę oliwy, wyrabiaj 8 minut na gładkie, elastyczne ciasto i zostaw pod ściereczką na 45 minut do podwojenia objętości.',
      'Pieczarki pokrój w plasterki i podsmaż na pozostałej oliwie przez 6–7 minut, aż odparuje woda i lekko się zrumienią. Ostudź — szynka i ser wystarczająco dosolą farsz.',
      'Szynkę pokrój w paski, mozzarellę w kostkę, a passatę wymieszaj z oregano.',
      'Nagrzej piekarnik do 230°C (góra-dół). Podziel ciasto na 2 części i rozwałkuj każdą na placek o średnicy około 24 cm.',
      'Posmaruj połowę każdego placka sosem, zostawiając 2 cm wolnego brzegu, ułóż szynkę, pieczarki i mozzarellę. Przykryj drugą połową, a brzegi mocno zawiń i dociśnij widelcem.',
      'Przełóż calzone na blachę z papierem do pieczenia, natnij wierzch w 2 miejscach i piecz 15–18 minut, aż będzie złote i wyraźnie rumiane na spodzie.',
      'Odczekaj 3 minuty, żeby ser nie wypłynął, i podawaj całe na talerzu z odrobiną oregano na wierzchu.',
    ],
    photo:
      'Two golden half-moon calzones with crimped edges, one cut open showing ham, sliced mushrooms and melted mozzarella, dusted with oregano',
  },
  {
    plan: 'ko-64',
    title: 'Pizza capricciosa',
    description:
      'Włoska klasyka na cienkim, domowym cieście: sos pomidorowy, mozzarella, szynka, pieczarki i czarne oliwki. Pieczona w mocno nagrzanym piekarniku wychodzi chrupiąca jak z pizzerii, a robi się ją z prostych składników z marketu.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 220, 'g'],
      ['drożdże', 10, 'g'],
      ['cukier', 3, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['sól', 3, 'g'],
      ['passata pomidorowa', 120, 'ml'],
      ['oregano', 2, 'g'],
      ['mozzarella', 125, 'g'],
      ['szynka', 80, 'g'],
      ['pieczarka', 100, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Rozetrzyj drożdże z cukrem, zalej letnią wodą (140 ml) i odstaw na 10 minut. Dodaj mąkę, sól i oliwę, wyrabiaj 8 minut i zostaw w ciepłym miejscu na 45 minut.',
      'Nagrzej piekarnik z blachą w środku do 250°C (góra-dół). Passatę wymieszaj z oregano.',
      'Pieczarki pokrój w cienkie plasterki, oliwki w krążki, szynkę porwij na kawałki, a mozzarellę osusz i porwij na małe kawałki.',
      'Podziel ciasto na 2 części i rozciągnij dłońmi na cienkie placki o średnicy około 28 cm, z nieco grubszym brzegiem. Przełóż je na papier do pieczenia.',
      'Posmaruj placki sosem, rozłóż mozzarellę, szynkę, pieczarki i oliwki.',
      'Zsuń pizzę z papierem na gorącą blachę i piecz 9–11 minut, aż brzegi będą rumiane, a ser zacznie się przypiekać w plamki.',
      'Wyjmij, posyp listkami świeżej bazylii i podawaj od razu, pokrojoną w trójkąty.',
    ],
    photo:
      'Thin-crust pizza with tomato sauce, melted mozzarella, torn ham, sliced mushrooms and black olive rings, topped with fresh basil leaves',
    vessel: 'board',
  },
  {
    plan: 'ko-65',
    title: 'Lahmacun, turecka pizza z mięsem',
    description:
      'Cieniutkie placki drożdżowe pokryte pikantną pastą z mielonej wołowiny, papryki i pomidora. Po upieczeniu skrapia się je cytryną, posypuje natką i zwija w rulon — lekka, aromatyczna kolacja zamiast zwykłej pizzy.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['drożdże instant', 4, 'g'],
      ['cukier', 2, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['sól', 4, 'g'],
      ['wołowina mielona', 200, 'g'],
      ['cebula', 80, 'g'],
      ['papryka czerwona', 80, 'g'],
      ['pomidor', 1, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['płatki chili', 1, 'g'],
      ['natka pietruszki', 20, 'g'],
      ['cytryna', 30, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z drożdżami, cukrem i 2 g soli, dolej letnią wodę (120 ml) i oliwę, wyrabiaj 6–8 minut na gładkie ciasto. Odstaw pod przykryciem na 40 minut.',
      'Cebulę, paprykę, pomidor (bez gniazda nasiennego) i czosnek posiekaj bardzo drobno albo zmiksuj na grubą pastę; odciśnij nadmiar soku.',
      'Wymieszaj warzywa z mięsem, koncentratem, papryką słodką, kminem, płatkami chili, połową natki i resztą soli — ma powstać smarowna masa.',
      'Nagrzej piekarnik do 250°C (góra-dół). Podziel ciasto na 4 części i rozwałkuj każdą na bardzo cienki owal około 25 × 15 cm.',
      'Rozsmaruj masę mięsną cienko, aż do samych brzegów, i piecz placki po 2 naraz na papierze przez 8–10 minut, aż mięso będzie ścięte, a brzegi chrupiące.',
      'Skrop gorące placki sokiem z cytryny, posyp resztą posiekanej natki, zwiń w rulon i podawaj od razu.',
    ],
    photo:
      'Four thin oval flatbreads covered with a spiced red minced beef layer, sprinkled with chopped parsley, with lemon wedges on the side',
  },
  {
    plan: 'ko-66',
    title: 'Burger z chrupiącym kurczakiem',
    description:
      'Soczysty filet z kurczaka w złocistej panierce, zamknięty w miękkiej bułce z sałatą, pomidorem i sosem majonezowo-jogurtowym. Domowa wersja fast foodu na leniwy wieczór, bez frytkownicy.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 40, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['bułka do hamburgera', 2, 'szt'],
      ['majonez', 20, 'g'],
      ['jogurt naturalny', 30, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['pomidor', 1, 'szt'],
      ['ogórek konserwowy', 40, 'g'],
    ],
    steps: [
      'Przekrój filet poziomo na 2 cienkie kotlety, rozbij je przez folię na grubość około 1 cm i dopraw solą, pieprzem i papryką.',
      'Obtocz kotlety kolejno w mące, roztrzepanym jajku i bułce tartej, mocno dociskając panierkę.',
      'Rozgrzej olej na patelni i smaż kotlety na średnim ogniu po 4–5 minut z każdej strony, aż panierka będzie złota, a mięso w środku białe. Odsącz na ręczniku papierowym.',
      'Wymieszaj majonez z jogurtem. Pomidor i ogórki pokrój w plasterki, sałatę porwij.',
      'Przekrój bułki i podpiecz je przekrojem w dół na suchej patelni przez minutę.',
      'Posmaruj bułki sosem, ułóż sałatę, kotlet, pomidor i ogórki, przykryj wierzchem i podawaj od razu.',
    ],
    photo:
      'Two burgers with golden breaded chicken fillets, iceberg lettuce, tomato slices and pickles in toasted buns, creamy sauce dripping at the edge',
  },
  {
    plan: 'ko-67',
    title: 'Tacos z dorszem i surówką z czerwonej kapusty',
    description:
      'Miękkie placki pszenne z kawałkami pieczonego dorsza w wędzonej papryce, chrupiącą czerwoną kapustą i limonkowym jogurtem. Świeża, lekka kolacja, którą każdy składa sobie sam przy stole.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['dorsz', 300, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['sól', 2.5, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kapusta czerwona', 120, 'g'],
      ['limonka', 1, 'szt'],
      ['jogurt grecki', 80, 'g'],
      ['awokado', 0.5, 'szt'],
      ['kolendra', 10, 'g'],
      ['tortilla pszenna', 4, 'szt'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Dorsza osusz, pokrój na kawałki 3 × 3 cm, obtocz w oleju, papryce wędzonej, kminie, czosnku i 1,5 g soli.',
      'Rozłóż rybę na blasze z papierem i piecz 10–12 minut, aż mięso będzie matowe i zacznie rozchodzić się na płatki.',
      'W tym czasie poszatkuj kapustę bardzo cienko, skrop sokiem z połowy limonki, posól resztą soli i ugnieć dłonią, żeby zmiękła.',
      'Jogurt wymieszaj ze skórką i sokiem z drugiej połowy limonki. Awokado pokrój w plasterki, kolendrę posiekaj.',
      'Podgrzej tortille po 20 sekund z każdej strony na suchej patelni.',
      'Na każdą tortillę nałóż kapustę, dorsza i awokado, polej sosem limonkowym, posyp kolendrą i podawaj od razu.',
    ],
    photo:
      'Four soft flour tortillas filled with seasoned baked cod pieces, shredded purple cabbage, avocado slices, white lime yogurt sauce and fresh coriander',
  },
  {
    plan: 'ko-68',
    title: 'Focaccia z pomidorkami i oliwkami',
    description:
      'Puszysty, oliwny chleb włoski z dołkami wypełnionymi pomidorkami koktajlowymi, oliwkami i rozmarynem. Pachnie jak z piekarni, świetnie smakuje na ciepło i na zimno, np. na kolację na tarasie.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 150,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['drożdże', 10, 'g'],
      ['cukier', 3, 'g'],
      ['oliwa z oliwek', 40, 'ml'],
      ['sól', 4, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwka czarna', 50, 'g'],
      ['czosnek', 2, 'szt'],
      ['rozmaryn suszony', 2, 'g'],
    ],
    steps: [
      'Rozpuść drożdże z cukrem w letniej wodzie (190 ml), dodaj mąkę, 3 g soli i 15 ml oliwy. Mieszaj łyżką 3–4 minuty — ciasto ma być luźne i klejące.',
      'Przykryj miskę i odstaw na około 60 minut, aż ciasto podwoi objętość i pojawią się na nim pęcherzyki.',
      'Wysmaruj formę 20 × 30 cm 10 ml oliwy, przełóż ciasto i rozciągnij je palcami do rogów. Zostaw na 30 minut do ponownego wyrośnięcia.',
      'Nagrzej piekarnik do 220°C (góra-dół). Przekrój pomidorki na pół, a czosnek pokrój w cienkie plasterki.',
      'Naoliw palce resztą oliwy i zrób nimi głębokie dołki w cieście. Wciśnij pomidorki przekrojem do góry, oliwki i czosnek, posyp rozmarynem i resztą soli.',
      'Piecz 22–25 minut, aż wierzch będzie złoty, a spód po postukaniu wyda głuchy dźwięk. Studź na kratce 10 minut.',
      'Pokrój focaccię w prostokąty i podawaj na desce, na ciepło.',
    ],
    photo:
      'Golden dimpled focaccia studded with halved cherry tomatoes, black olives and garlic slices, sprinkled with rosemary and flaky salt, cut into squares',
    vessel: 'board',
  },
  {
    plan: 'ko-69',
    title: 'Grzanki z kozim serem, miodem i orzechami',
    description:
      'Chrupiąca bagietka zapiekana z plastrami koziego sera, polana miodem i posypana orzechami, podana z rukolą w balsamicznym winegrecie. Słodko-słony duet, który przygotujesz w kwadrans na elegancką kolację we dwoje.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['bagietka', 200, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['ser kozi', 150, 'g'],
      ['miód', 20, 'g'],
      ['orzech włoski', 20, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['rukola', 40, 'g'],
      ['ocet balsamiczny', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół z grzałką górną). Bagietkę pokrój ukośnie w kromki grubości 1,5 cm i skrop połową oliwy.',
      'Podpiecz kromki 4 minuty, aż lekko stwardnieją.',
      'Ser kozi pokrój w plastry, ułóż na grzankach, posyp tymiankiem i zapiekaj 5–6 minut, aż ser zmięknie i zacznie się rumienić.',
      'Orzechy podpraż na suchej patelni 2–3 minuty i posiekaj grubo.',
      'Rukolę wymieszaj z resztą oliwy, octem balsamicznym i pieprzem.',
      'Polej gorące grzanki miodem, posyp orzechami i podawaj od razu z rukolą obok.',
    ],
    photo:
      'Toasted baguette slices topped with melted golden goat cheese, drizzled with honey and chopped walnuts, served with dressed arugula',
  },
  {
    plan: 'ko-70',
    title: 'Wrap z łososiem wędzonym i serkiem',
    description:
      'Tortilla posmarowana serkiem z koperkiem i cytryną, zawinięta z wędzonym łososiem, ogórkiem i rukolą. Kolacja bez gotowania, gotowa w dziesięć minut — świetna też do pudełka na następny dzień.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['serek kremowy', 100, 'g'],
      ['koperek', 5, 'g'],
      ['cytryna', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['łosoś wędzony', 150, 'g'],
      ['ogórek', 120, 'g'],
      ['cebula czerwona', 30, 'g'],
      ['rukola', 30, 'g'],
    ],
    steps: [
      'Posiekaj koperek i wymieszaj z serkiem, startą skórką i sokiem z cytryny oraz pieprzem.',
      'Ogórek pokrój w cienkie słupki, a cebulę w piórka.',
      'Podgrzej tortille po 15 sekund z każdej strony na suchej patelni, żeby zmiękły i nie pękały przy zwijaniu.',
      'Rozsmaruj serek na całych tortillach, na dolnej połowie ułóż rukolę, łososia, ogórek i cebulę.',
      'Zawiń boki do środka i zwiń ciasno od dołu w rulon.',
      'Przekrój każdy wrap ukośnie na pół i podawaj od razu albo zawinięty w folię do pudełka.',
    ],
    photo:
      'Two tortilla wraps cut diagonally, showing pink smoked salmon, cream cheese with dill, cucumber sticks and arugula',
  },
  {
    plan: 'ko-71',
    title: 'Zapiekany bakłażan z mozzarellą (parmigiana)',
    description:
      'Warstwy podpieczonego bakłażana, gęstego sosu pomidorowego z bazylią, mozzarelli i parmezanu, zapiekane na złoto. Włoskie danie z jednego naczynia, które w smaku przypomina lasagne, a obywa się bez makaronu.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['bakłażan', 600, 'g'],
      ['sól', 3, 'g'],
      ['oliwa z oliwek', 40, 'ml'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 400, 'ml'],
      ['cukier', 2, 'g'],
      ['oregano', 1, 'g'],
      ['bazylia', 10, 'g'],
      ['mozzarella', 125, 'g'],
      ['ser parmezan', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Bakłażany pokrój wzdłuż w plastry grubości 1 cm, posól 2 g soli i odstaw na 20 minut; potem osusz ręcznikiem papierowym.',
      'Nagrzej piekarnik do 220°C (termoobieg). Posmaruj plastry 30 ml oliwy, ułóż na blasze z papierem i piecz 20 minut, aż zmiękną i się zrumienią.',
      'W tym czasie zeszklij posiekaną cebulę i czosnek na reszcie oliwy (5 minut), wlej passatę, dodaj cukier, oregano, resztę soli i pieprz. Gotuj 10 minut, aż sos zgęstnieje, i wmieszaj połowę porwanej bazylii.',
      'Zmniejsz temperaturę do 190°C. W naczyniu żaroodpornym układaj warstwami sos, bakłażana, pokrojoną mozzarellę i starty parmezan — zakończ sosem, mozzarellą i parmezanem.',
      'Zapiekaj 25 minut, aż sos zacznie bulgotać na brzegach, a ser będzie złoty.',
      'Odstaw na 10 minut, żeby warstwy się związały, i podawaj posypane resztą bazylii.',
    ],
    photo:
      'Baked eggplant parmigiana in a ceramic dish, layers of eggplant and red tomato sauce under bubbling golden mozzarella and parmesan, fresh basil on top',
  },
  {
    plan: 'ko-72',
    title: 'Cukinia faszerowana kaszą bulgur i fetą',
    description:
      'Łódki z cukinii wypełnione bulgurem z pomidorem, czosnkiem, natką i kawałkami fety, zapieczone do miękkości. Sycąca, wegetariańska kolacja o śródziemnomorskim charakterze, dobra także na zimno.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['cukinia', 600, 'g'],
      ['bulgur', 80, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['pomidor', 1, 'szt'],
      ['ser feta', 120, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['oregano', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj bulgur w 160 ml wody z 1 g soli (10 minut pod przykryciem), aż wchłonie wodę.',
      'Nagrzej piekarnik do 200°C (góra-dół). Przekrój cukinie wzdłuż i wydrąż łyżeczką środek, zostawiając ścianki grubości 1 cm; miąższ posiekaj.',
      'Na połowie oliwy zeszklij posiekaną cebulę i czosnek, dodaj miąższ cukinii i pokrojony w kostkę pomidor. Smaż 5 minut, aż odparuje nadmiar soku.',
      'Wymieszaj warzywa z bulgurem, oregano, posiekaną natką (odłóż trochę do posypania), pieprzem i 2/3 pokruszonej fety.',
      'Posól wnętrza cukinii resztą soli, napełnij farszem, posyp resztą fety, skrop pozostałą oliwą i piecz 25 minut, aż cukinia będzie miękka przy nakłuciu.',
      'Podawaj po 2 łódki na osobę, posypane natką.',
    ],
    photo:
      'Four baked zucchini boats filled with bulgur, diced tomato and herbs, topped with golden crumbled feta and chopped parsley',
  },
  {
    plan: 'ko-73',
    title: 'Pomidory faszerowane kuskusem i serem',
    description:
      'Duże pomidory wypełnione kuskusem z ziołami, czosnkiem i żółtym serem, pieczone, aż skórka lekko się zmarszczy. Soczyste, pachnące i proste — idealne pod koniec lata, gdy pomidory są najlepsze.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['pomidor', 4, 'szt'],
      ['kasza kuskus', 80, 'g'],
      ['bulion warzywny', 120, 'ml'],
      ['cebula', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['ser gouda', 80, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['bazylia suszona', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra-dół). Odetnij pomidorom wierzch z szypułką (zachowaj jako pokrywki) i wydrąż środek łyżeczką; miąższ posiekaj.',
      'Zalej kuskus gorącym bulionem, przykryj na 5 minut, a potem rozdrobnij widelcem.',
      'Na oliwie zeszklij posiekaną cebulę i czosnek, dodaj miąższ pomidorów i duś 5 minut, aż zgęstnieje.',
      'Wymieszaj kuskus z sosem, bazylią, posiekaną natką, pieprzem i 2/3 startego sera. Wnętrza pomidorów oprósz solą.',
      'Napełnij pomidory farszem, posyp resztą sera, przykryj pokrywkami i piecz w naczyniu żaroodpornym 20 minut, aż ser się roztopi, a skórka pomidorów zmarszczy.',
      'Podawaj po 2 pomidory na osobę, skropione sokiem, który zebrał się w naczyniu.',
    ],
    photo:
      'Four roasted red tomatoes stuffed with herbed couscous and melted cheese, tomato caps leaning on the side, parsley sprinkled over',
  },
  {
    plan: 'ko-74',
    title: 'Placki z brokułu i sera z sosem jogurtowym',
    description:
      'Zielone placuszki z posiekanego brokułu, jajek i żółtego sera, rumiane z zewnątrz i miękkie w środku, z chłodnym sosem jogurtowym ze szczypiorkiem. Dobry sposób na przemycenie warzyw na kolację.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['brokuł', 400, 'g'],
      ['jajko', 2, 'szt'],
      ['ser żółty', 80, 'g'],
      ['mąka pszenna', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['szczypiorek', 5, 'g'],
    ],
    steps: [
      'Podziel brokuł na różyczki i gotuj w osolonej wodzie (2 g soli) przez 4 minuty. Odcedź, ostudź i posiekaj drobno.',
      'Wymieszaj brokuł z jajkami, startym serem, mąką, przeciśniętym czosnkiem, pieprzem i szczyptą soli — masa ma być gęsta.',
      'Rozgrzej olej na patelni i nakładaj łyżką placki o średnicy 8 cm, lekko je spłaszczając.',
      'Smaż na średnim ogniu po 3 minuty z każdej strony, aż będą złote i ścięte w środku. Odsącz na ręczniku papierowym.',
      'Jogurt wymieszaj z posiekanym szczypiorkiem i resztą soli.',
      'Podawaj placki gorące, z sosem jogurtowym obok.',
    ],
    photo:
      'Stack of golden-green broccoli and cheese fritters on a plate with a small bowl of white yogurt sauce sprinkled with chives',
  },
  {
    plan: 'ko-75',
    title: 'Burgery z czerwonej fasoli',
    description:
      'Wegetariańskie kotlety z czerwonej fasoli z kminem i wędzoną papryką, podsmażone na chrupko i podane w bułce z serem cheddar, sałatą i pomidorem. Sycące jak mięsne, a gotowe w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['fasola czerwona z puszki', 300, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 1, 'szt'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['sól', 2, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 40, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['ser cheddar', 40, 'g'],
      ['bułka do hamburgera', 2, 'szt'],
      ['sałata lodowa', 30, 'g'],
      ['pomidor', 1, 'szt'],
      ['ketchup', 20, 'g'],
    ],
    steps: [
      'Fasolę odcedź, przepłucz i dokładnie osusz, a potem rozgnieć tłuczkiem, zostawiając trochę całych ziaren.',
      'Cebulę i czosnek posiekaj bardzo drobno i dodaj do fasoli razem z kminem, papryką, solą, jajkiem i bułką tartą. Wymieszaj i odstaw na 10 minut, żeby bułka wchłonęła wilgoć.',
      'Mokrymi dłońmi uformuj 2 kotlety grubości 2 cm, nieco szersze od bułek.',
      'Smaż na rozgrzanym oleju po 4 minuty z każdej strony, aż będą chrupiące. Pod koniec połóż na każdym plaster cheddara i przykryj patelnię na minutę, żeby ser się roztopił.',
      'Przekrój bułki i podpiecz je na suchej patelni. Pomidor pokrój w plastry.',
      'Posmaruj bułki ketchupem, ułóż sałatę, kotlet z serem i pomidor, przykryj i podawaj.',
    ],
    photo:
      'Two bean burgers with dark red-brown patties, melted cheddar, lettuce and tomato slices in sesame-free buns on a plate',
  },
  {
    plan: 'ko-76',
    title: 'Kalafior po polsku z jajkiem i bułką tartą',
    description:
      'Cały kalafior ugotowany al dente, polany masłem zrumienionym z bułką tartą i posypany siekanym jajkiem oraz koperkiem. Staropolska klasyka, która z dwoma jajkami na osobę robi się pełną, ciepłą kolacją.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['kalafior', 700, 'g'],
      ['sól', 3, 'g'],
      ['jajko', 4, 'szt'],
      ['masło', 50, 'g'],
      ['bułka tarta', 50, 'g'],
      ['koperek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kalafior oczyść z liści, podziel na duże różyczki i gotuj w osolonej wodzie (2 g soli) przez 8–10 minut, aż nóż wejdzie łatwo, ale różyczki się nie rozpadają. Odcedź.',
      'Jajka ugotuj na twardo (9 minut), ostudź w zimnej wodzie, obierz i posiekaj drobno.',
      'Na patelni roztop masło, wsyp bułkę tartą i smaż, mieszając, 3–4 minuty, aż będzie złota i zapachnie orzechowo. Dopraw resztą soli i pieprzem.',
      'Ułóż kalafior na talerzach i polej go gorącym masłem z bułką.',
      'Posyp siekanym jajkiem i koperkiem, podawaj od razu.',
    ],
    photo:
      'Cauliflower florets covered with golden buttery breadcrumbs, chopped hard-boiled egg and fresh dill on a white plate',
  },
  {
    plan: 'ko-77',
    title: 'Pieczarki w śmietanie z pieczywem',
    description:
      'Pieczarki duszone z cebulą na maśle i zabielone gęstą śmietaną, z natką i pieprzem, podane z kromkami świeżego chleba do maczania. Domowy, kremowy sos w dwadzieścia minut.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['pieczarka', 500, 'g'],
      ['cebula', 100, 'g'],
      ['masło', 20, 'g'],
      ['śmietana 18', 150, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['chleb', 140, 'g'],
    ],
    steps: [
      'Pieczarki pokrój w grube plastry, a cebulę w drobną kostkę.',
      'Na maśle zeszklij cebulę (4 minuty), dodaj pieczarki i smaż na dużym ogniu 8–10 minut, aż puszczą sok, a potem go odparują i zaczną się rumienić.',
      'Śmietanę wymieszaj z mąką na gładko, dodaj 2 łyżki gorącego sosu z patelni, a potem wlej do pieczarek.',
      'Duś 3 minuty, mieszając, aż sos zgęstnieje; dopraw solą i pieprzem.',
      'Podawaj posypane posiekaną natką, z kromkami chleba obok.',
    ],
    photo:
      'Creamy sautéed mushrooms in sour cream sauce sprinkled with chopped parsley and black pepper, with slices of rustic bread on the side',
  },
  {
    plan: 'ko-78',
    title: 'Młode ziemniaki z koperkiem i kefirem',
    description:
      'Młode ziemniaki prosto z garnka, polane roztopionym masłem i obsypane koperkiem, z zimnym kefirem do popijania. Najprostsza letnia kolacja, która smakuje dzieciństwem.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['ziemniak młody', 700, 'g'],
      ['sól', 3, 'g'],
      ['masło', 25, 'g'],
      ['koperek', 15, 'g'],
      ['kefir', 500, 'ml'],
    ],
    steps: [
      'Ziemniaki dokładnie wyszoruj szczoteczką pod bieżącą wodą — młodych nie trzeba obierać.',
      'Wrzuć je do wrzącej, osolonej wody i gotuj 15–20 minut, aż nóż wejdzie w nie bez oporu.',
      'Odcedź, przełóż z powrotem do garnka, dodaj masło i połowę posiekanego koperku, przykryj i potrząśnij garnkiem, żeby ziemniaki się nim pokryły.',
      'Kefir schłodź w lodówce i rozlej do szklanek.',
      'Podawaj ziemniaki posypane resztą koperku, z zimnym kefirem obok.',
    ],
    photo:
      'Bowl of small boiled new potatoes glistening with melted butter and covered in chopped fresh dill, with a glass of cold kefir beside',
  },
  {
    plan: 'ko-79',
    title: 'Pęczotto z grzybami',
    description:
      'Polska odpowiedź na risotto: pęczak gotowany powoli w bulionie z pieczarkami i suszonymi grzybami, wykończony masłem i parmezanem. Kremowe, jędrne i bardzo aromatyczne — idealne na chłodny wieczór.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 55,
    servings: 2,
    ingredients: [
      ['grzyb suszony', 10, 'g'],
      ['kasza jęczmienna', 150, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['masło', 20, 'g'],
      ['pieczarka', 250, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['bulion warzywny', 700, 'ml'],
      ['ser parmezan', 30, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Suszone grzyby zalej 150 ml wrzątku na 15 minut, potem posiekaj; wodę z moczenia zachowaj. Bulion podgrzej.',
      'W szerokim garnku rozgrzej oliwę z połową masła, zeszklij posiekaną cebulę i czosnek (4 minuty). Dodaj pokrojone pieczarki i tymianek, smaż 6 minut, aż się zrumienią.',
      'Wsyp pęczak (kaszę jęczmienną), smaż minutę, wlej wodę z grzybów i dodaj posiekane grzyby.',
      'Dolewaj gorący bulion po chochli, mieszając co chwilę, i gotuj 30–35 minut, aż kasza będzie miękka, ale jędrna, a całość kremowa.',
      'Zdejmij z ognia, wmieszaj resztę masła i starty parmezan, dopraw pieprzem (soli zwykle nie trzeba — bulion i parmezan są słone); odstaw na 2 minuty.',
      'Podawaj w głębokich talerzach, posypane natką i odrobiną parmezanu.',
    ],
    photo:
      'Creamy pearl barley risotto with browned mushrooms and dried porcini pieces, topped with grated parmesan and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'ko-80',
    title: 'Ratatouille z bagietką',
    description:
      'Prowansalski gulasz z bakłażana, cukinii, papryki i pomidorów, duszony na oliwie z ziołami, aż warzywa staną się miękkie i słodkie. Z chrupiącą bagietką to sycąca, roślinna kolacja, a nazajutrz smakuje jeszcze lepiej.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['oliwa z oliwek', 40, 'ml'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['bakłażan', 300, 'g'],
      ['cukinia', 300, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['papryka żółta', 1, 'szt'],
      ['pomidor', 3, 'szt'],
      ['zioła prowansalskie', 3, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['bazylia', 10, 'g'],
      ['bagietka', 150, 'g'],
    ],
    steps: [
      'Bakłażana, cukinię i paprykę pokrój w kostkę 2 cm, cebulę w piórka, czosnek w plasterki, a pomidory sparz, obierz i posiekaj.',
      'W szerokim garnku rozgrzej połowę oliwy i podsmaż bakłażana 6–7 minut, aż zmięknie i się zrumieni; odłóż na talerz.',
      'Na reszcie oliwy zeszklij cebulę i czosnek, dodaj paprykę i smaż 5 minut, potem cukinię na kolejne 3 minuty.',
      'Dodaj pomidory, bakłażana, zioła prowansalskie, sól i pieprz. Duś pod przykryciem na małym ogniu 25 minut, mieszając od czasu do czasu, aż warzywa będą miękkie, ale nie rozpadnięte.',
      'Zdejmij z ognia i wmieszaj połowę porwanej bazylii.',
      'Podawaj w głębokich talerzach, posypane resztą bazylii, z kromkami bagietki do wycierania sosu.',
    ],
    photo:
      'Colorful ratatouille stew of eggplant, zucchini, red and yellow peppers in tomato sauce with fresh basil, baguette slices on the side',
    vessel: 'bowl',
  },
  {
    plan: 'ko-81',
    title: 'Krem z pieczarek z grzankami',
    description:
      'Aksamitna zupa z podsmażonych pieczarek, zagęszczona ziemniakiem i zabielona śmietanką, z czosnkowymi grzankami na wierzchu. Rozgrzewa w chłodne wieczory i bez problemu odgrzewa się na drugi dzień.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['masło', 20, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['pieczarka', 500, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['ziemniak', 200, 'g'],
      ['bulion warzywny', 600, 'ml'],
      ['śmietanka 18', 100, 'ml'],
      ['pieprz czarny', 1, 'g'],
      ['chleb', 100, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Na maśle zeszklij posiekaną cebulę i 1 ząbek czosnku. Dodaj pokrojone pieczarki (kilka plasterków odłóż do dekoracji) i tymianek, smaż 8 minut, aż odparują i się zrumienią.',
      'Dodaj obranego ziemniaka pokrojonego w kostkę, zalej bulionem i gotuj 15 minut, aż ziemniak będzie miękki.',
      'W tym czasie pokrój chleb w kostkę 1,5 cm, wymieszaj z oliwą i przeciśniętym drugim ząbkiem czosnku i podpiecz na patelni 5–6 minut na złoto. Na tej samej patelni podsmaż odłożone plasterki pieczarek.',
      'Zmiksuj zupę blenderem na gładki krem, wlej śmietankę, podgrzej bez gotowania i dopraw pieprzem — bulion zwykle wystarczająco soli zupę.',
      'Podawaj w miseczkach z grzankami, plasterkami pieczarek i posiekaną natką.',
    ],
    photo:
      'Bowl of smooth beige mushroom cream soup topped with golden garlic croutons, sautéed mushroom slices and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'ko-82',
    title: 'Gazpacho z grzankami',
    description:
      'Hiszpański chłodnik z dojrzałych pomidorów, ogórka i papryki, zmiksowany z oliwą, czosnkiem i odrobiną octu. Orzeźwia w upalne wieczory, a grzanki dodają mu chrupkości i sytości.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 140,
    servings: 2,
    ingredients: [
      ['pomidor', 800, 'g'],
      ['ogórek', 200, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cebula czerwona', 50, 'g'],
      ['czosnek', 2, 'szt'],
      ['chleb', 100, 'g'],
      ['oliwa z oliwek', 40, 'ml'],
      ['ocet winny', 15, 'ml'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Pomidory sparz, obierz i pokrój na ćwiartki. Ogórek obierz, paprykę oczyść z gniazda nasiennego; po 2 łyżki drobnej kostki z ogórka i papryki odłóż do podania.',
      'Namocz połowę chleba bez skórki w 50 ml zimnej wody przez 5 minut.',
      'Zmiksuj pomidory, ogórek, paprykę, cebulę, czosnek i namoczony chleb z 30 ml oliwy, octem, solą i pieprzem na gładką zupę. Jeśli jest za gęsta, dolej trochę zimnej wody.',
      'Przelej do dzbanka i chłodź w lodówce co najmniej 2 godziny.',
      'Tuż przed podaniem pokrój resztę chleba w kostkę i zrumień na suchej patelni 4–5 minut.',
      'Rozlej gazpacho do misek, posyp odłożonymi warzywami, grzankami i bazylią, skrop resztą oliwy.',
    ],
    photo:
      'Bowl of chilled bright red gazpacho garnished with diced cucumber and pepper, golden croutons, basil leaves and a drizzle of olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'ko-83',
    title: 'Szaszłyki z kurczaka z tzatziki i pitą',
    description:
      'Kawałki kurczaka marynowane w cytrynie, czosnku i oregano, nadziane na patyczki z papryką, cukinią i cebulą, podane z gęstym tzatziki i ciepłą pitą. Smak greckiej tawerny z piekarnika albo grilla.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 20, 'g'],
      ['czosnek', 3, 'szt'],
      ['oregano', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cukinia', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['jogurt grecki', 200, 'g'],
      ['ogórek', 150, 'g'],
      ['koperek', 5, 'g'],
      ['pita', 2, 'szt'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę 3 cm i wymieszaj z oliwą, sokiem z cytryny, 2 przeciśniętymi ząbkami czosnku, oregano, papryką, 2 g soli i pieprzem. Marynuj 20 minut (albo dłużej w lodówce).',
      'Na tzatziki zetrzyj ogórek na tarce o grubych oczkach, posól szczyptą soli, odstaw na 5 minut i mocno odciśnij. Wymieszaj z jogurtem, trzecim ząbkiem czosnku i posiekanym koperkiem.',
      'Paprykę, cukinię i cebulę pokrój na kawałki 3 cm i nadziewaj na patyczki na przemian z kurczakiem.',
      'Piecz szaszłyki pod grillem piekarnika w 230°C albo na patelni grillowej 12–15 minut, obracając co kilka minut, aż kurczak będzie zrumieniony i w środku biały.',
      'Pitę podgrzej po minucie z każdej strony na suchej patelni.',
      'Podawaj szaszłyki z tzatziki i ciepłą pitą pokrojoną w trójkąty.',
    ],
    photo:
      'Grilled chicken skewers with red pepper, zucchini and red onion, a bowl of creamy tzatziki with dill and warm pita triangles',
  },
  {
    plan: 'ko-84',
    title: 'Kurczak cajun z kolbą kukurydzy',
    description:
      'Filet z kurczaka w pikantnej, wędzonej mieszance przypraw w stylu cajun, zrumieniony na patelni i podany z gotowaną kolbą kukurydzy w maśle i limonce. Kolacja w klimacie amerykańskiego Południa.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['kukurydza', 2, 'szt'],
      ['filet z kurczaka', 350, 'g'],
      ['papryka wędzona mielona', 4, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['oregano', 1, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['masło', 20, 'g'],
      ['limonka', 1, 'szt'],
    ],
    steps: [
      'Kolby kukurydzy oczyść i gotuj w wodzie bez soli 15–20 minut, aż ziarna będą miękkie.',
      'Wymieszaj paprykę wędzoną, czosnek granulowany, oregano, tymianek, ostrą paprykę, 2 g soli i pieprz.',
      'Przekrój filet poziomo na 2 cieńsze kotlety, natrzyj oliwą i mieszanką przypraw z obu stron.',
      'Smaż na mocno rozgrzanej patelni po 5–6 minut z każdej strony, aż przyprawy się przypieką na ciemno, a mięso w najgrubszym miejscu będzie białe. Odstaw na 3 minuty.',
      'Gorące kolby posmaruj masłem, posyp resztą soli i skrop sokiem z połowy limonki.',
      'Podawaj kurczaka pokrojonego w plastry, z kolbą kukurydzy i ćwiartkami limonki.',
    ],
    photo:
      'Sliced cajun-spiced chicken breast with a dark red crust next to a buttery corn on the cob and lime wedges',
  },
  {
    plan: 'ko-85',
    title: 'Pierś z indyka w ziołach z pieczonymi warzywami',
    description:
      'Soczysta pierś z indyka natarta czosnkiem i ziołami prowansalskimi, pieczona na jednej blasze z ziemniakami, marchewką, cukinią i papryką. Mało zmywania, dużo smaku — obiad na kolację bez stania przy garach.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['filet z indyka', 350, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['czosnek', 3, 'szt'],
      ['zioła prowansalskie', 3, 'g'],
      ['rozmaryn suszony', 1, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['ziemniak', 400, 'g'],
      ['marchew', 150, 'g'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cebula czerwona', 100, 'g'],
    ],
    steps: [
      'Wymieszaj 15 ml oliwy z przeciśniętym czosnkiem, połową ziół, rozmarynem, 1,5 g soli i pieprzem; natrzyj indyka i odstaw na czas przygotowania warzyw.',
      'Nagrzej piekarnik do 200°C (termoobieg). Ziemniaki pokrój w ćwiartki, marchew w grube plastry, cukinię i paprykę w kostkę 3 cm, a cebulę w ósemki.',
      'Wymieszaj ziemniaki i marchew z połową pozostałej oliwy, resztą ziół i soli, rozłóż na blasze i piecz 15 minut.',
      'Dodaj na blachę cukinię, paprykę i cebulę skropione resztą oliwy, a na środku połóż indyka.',
      'Piecz 25–30 minut, aż warzywa będą miękkie i przypieczone, a sok z nakłutego mięsa przezroczysty. Odstaw indyka na 5 minut przed krojeniem.',
      'Pokrój pierś w plastry i podawaj na warzywach, polaną sokiem z blachy.',
    ],
    photo:
      'Sliced herb-crusted roast turkey breast on a bed of roasted potatoes, carrots, zucchini, red pepper and red onion wedges',
  },
  {
    plan: 'ko-86',
    title: 'Domowy pasztet z indyka z pieczywem',
    description:
      'Delikatny pasztet z udźca indyka i wątróbki, pieczony z warzywami, majerankiem i zielem angielskim, podany na razowym chlebie z ogórkiem kiszonym. Domowy smak bez konserwantów, a resztka świetnie sprawdzi się na kanapki.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 180,
    servings: 2,
    ingredients: [
      ['udziec z indyka', 250, 'g'],
      ['wątróbka drobiowa', 80, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['cebula', 80, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['masło', 15, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 25, 'g'],
      ['majeranek', 2, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 2, 'g'],
      ['chleb żytni', 150, 'g'],
      ['ogórek kiszony', 60, 'g'],
    ],
    steps: [
      'Indyka pokrój w kostkę, marchew i pietruszkę w plastry, cebulę na ćwiartki. Zalej 400 ml wody, dodaj liść laurowy i ziele angielskie, gotuj pod przykryciem 50 minut, aż mięso będzie bardzo miękkie.',
      'Na ostatnie 10 minut dodaj oczyszczoną wątróbkę. Odcedź, zachowując wywar; usuń liść i ziele.',
      'Zmiel mięso z warzywami dwa razy w maszynce albo zmiksuj blenderem na gładko. Dodaj jajko, bułkę tartą, roztopione masło, majeranek, gałkę, sól, pieprz i 80 ml wywaru — masa ma być gęsta, ale wilgotna.',
      'Nagrzej piekarnik do 180°C (góra-dół). Przełóż masę do małej keksówki (około 18 cm) wyłożonej papierem i wyrównaj.',
      'Piecz 45–50 minut, aż wierzch się zrumieni, a pasztet odejdzie od brzegów formy. Studź w formie co najmniej 40 minut, najlepiej schłodź w lodówce.',
      'Pokrój pasztet w plastry i podawaj na kromkach chleba żytniego z plasterkami ogórka kiszonego.',
    ],
    photo:
      'Slices of homemade golden-brown turkey pâté on rye bread with pickled cucumber slices, the rest of the loaf on a board behind',
    vessel: 'board',
  },
  {
    plan: 'ko-87',
    title: 'Ryż z mielonym indykiem i fasolką po azjatycku',
    description:
      'Mielony indyk podsmażony z czosnkiem i imbirem, glazurowany sosem sojowym z miodem, z chrupiącą fasolką szparagową na jaśminowym ryżu. Szybkie danie z woka, które spokojnie zabierzesz do pracy.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['ryż jaśminowy', 140, 'g'],
      ['fasolka szparagowa', 250, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['indyk mielony', 300, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 10, 'g'],
      ['płatki chili', 1, 'g'],
      ['sos sojowy', 30, 'ml'],
      ['miód', 10, 'g'],
      ['olej sezamowy', 10, 'ml'],
      ['cebula dymka', 30, 'g'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Ryż przepłucz i ugotuj w 250 ml wody pod przykryciem na małym ogniu przez 12 minut, potem odstaw na 5 minut.',
      'Fasolce odetnij końcówki, pokrój na 4-centymetrowe kawałki i blanszuj 3 minuty we wrzątku, a potem przelej zimną wodą.',
      'Na mocno rozgrzanym oleju rzepakowym smaż indyka 6–7 minut, rozbijając go łopatką, aż się zrumieni i zrobi sypki.',
      'Dodaj posiekany czosnek, starty imbir i płatki chili, smaż minutę, a potem wrzuć fasolkę i smaż kolejne 2 minuty.',
      'Wlej sos sojowy wymieszany z miodem, smaż, aż sos oblepi mięso, i na koniec skrop olejem sezamowym.',
      'Podawaj na ryżu, posypane pokrojoną dymką i sezamem.',
    ],
    photo:
      'Bowl of jasmine rice topped with glazed browned minced turkey and green beans, sprinkled with sliced spring onion and sesame seeds',
    vessel: 'bowl',
  },
  {
    plan: 'ko-88',
    title: 'Klopsiki szwedzkie z ziemniakami i żurawiną',
    description:
      'Małe, delikatne klopsiki z wołowiny i wieprzowiny z nutą ziela angielskiego i gałki, w kremowym sosie śmietanowym, podane z ziemniakami i słodko-kwaśną żurawiną. Szwedzki klasyk, który w domu wychodzi lepiej niż w meblowej stołówce.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['ziemniak', 400, 'g'],
      ['sól', 3.5, 'g'],
      ['bułka tarta', 25, 'g'],
      ['mleko', 40, 'ml'],
      ['wołowina mielona', 150, 'g'],
      ['wieprzowina mielona chuda', 150, 'g'],
      ['cebula', 60, 'g'],
      ['jajko', 1, 'szt'],
      ['zioło angielskie', 1, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['masło', 15, 'g'],
      ['mąka pszenna', 15, 'g'],
      ['bulion drobiowy', 250, 'ml'],
      ['śmietanka 18', 80, 'ml'],
      ['sos żurawinowy', 40, 'g'],
      ['natka pietruszki', 5, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i gotuj w osolonej wodzie (1 g soli) około 20 minut, aż będą miękkie.',
      'Bułkę tartą zalej mlekiem. Cebulę zetrzyj na drobnej tarce i dodaj razem z namoczoną bułką do obu rodzajów mięsa. Dodaj jajko, zmielone ziele angielskie, gałkę, resztę soli i pieprz, wyrób gładką masę.',
      'Mokrymi dłońmi formuj klopsiki wielkości orzecha włoskiego (wyjdzie ich około 20).',
      'Na maśle smaż klopsiki partiami 6–7 minut, obracając, aż będą zrumienione ze wszystkich stron i ścięte w środku. Odłóż na talerz.',
      'Do tłuszczu na patelni wsyp mąkę, smaż minutę, a potem stopniowo wlewaj bulion, mieszając trzepaczką. Dodaj śmietankę, gotuj 3 minuty, aż sos zgęstnieje, i włóż klopsiki na 2 minuty.',
      'Podawaj klopsiki w sosie z ziemniakami posypanymi natką i łyżką sosu żurawinowego obok.',
    ],
    photo:
      'Small browned meatballs in creamy light brown gravy with boiled potatoes sprinkled with parsley and a spoonful of red cranberry sauce',
  },
  {
    plan: 'ko-89',
    title: 'Currywurst z pieczonymi frytkami',
    description:
      'Berliński przysmak z ulicznej budki: plastry podsmażonej kiełbasy w gęstym, pikantnym sosie pomidorowym z curry, oprószone curry i podane z frytkami z piekarnika. Szybka, konkretna kolacja na piątkowy wieczór.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['frytka mrożona', 300, 'g'],
      ['kiełbasa śląska', 200, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['cebula', 60, 'g'],
      ['curry', 5, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['ketchup', 80, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C (termoobieg), rozłóż frytki w jednej warstwie na blasze z papierem i piecz 20–25 minut, obracając w połowie, aż będą złote i chrupiące.',
      'Kiełbasę pokrój ukośnie w plastry grubości 1 cm i podsmaż na oleju 5–6 minut, aż się zrumieni. Przełóż na talerz.',
      'Na tej samej patelni zeszklij drobno posiekaną cebulę (3 minuty), dodaj 4 g curry i paprykę, smaż 30 sekund, aż zapachną.',
      'Wlej ketchup z wodą (50 ml), gotuj 3–4 minuty, aż sos zgęstnieje, i włóż kiełbasę na minutę, żeby się podgrzała.',
      'Nałóż kiełbasę z sosem obok frytek, oprósz resztą curry i podawaj od razu.',
    ],
    photo:
      'Sliced sausage pieces smothered in thick red curry ketchup sauce dusted with yellow curry powder, next to a pile of golden fries',
  },
  {
    plan: 'ko-90',
    title: 'Pieczone sajgonki z kurczakiem i warzywami',
    description:
      'Chrupiące sajgonki z papieru ryżowego z farszem z mielonego kurczaka, makaronu ryżowego, marchewki i kapusty pekińskiej, pieczone zamiast smażone w głębokim tłuszczu. Maczane w słodkim sosie chili znikają w mgnieniu oka.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['makaron ryżowy', 40, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['kurczak mielony', 250, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 5, 'g'],
      ['marchew', 100, 'g'],
      ['kapusta pekińska', 150, 'g'],
      ['cebula dymka', 20, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['papier ryżowy', 70, 'g'],
      ['sos chili słodki', 50, 'g'],
    ],
    steps: [
      'Makaron ryżowy zalej wrzątkiem na 5 minut, odcedź i pokrój nożyczkami na krótkie kawałki. Marchew zetrzyj na tarce o grubych oczkach, kapustę poszatkuj cienko, dymkę posiekaj.',
      'Na 5 ml oleju smaż kurczaka 5 minut, rozbijając go łopatką. Dodaj czosnek i starty imbir, a potem marchew i kapustę; smaż 3 minuty, aż warzywa zmiękną i odparuje woda.',
      'Zdejmij z ognia, wmieszaj makaron, dymkę i sos sojowy. Ostudź farsz przez 10 minut.',
      'Nagrzej piekarnik do 210°C (termoobieg). Każdy arkusz papieru ryżowego zanurz na 5 sekund w ciepłej wodzie, połóż na desce, nałóż 2 łyżki farszu, zawiń boki i zwiń ciasno w rulon. Wyjdzie około 10 sajgonek.',
      'Ułóż sajgonki na blasze z papierem, posmaruj resztą oleju ze wszystkich stron i piecz 20–25 minut, obracając w połowie, aż będą złote i chrupiące.',
      'Podawaj gorące, ze słodkim sosem chili do maczania.',
    ],
    photo:
      'Golden crispy baked spring rolls arranged on a plate, one cut in half showing chicken, carrot and glass noodle filling, with a bowl of sweet chili sauce',
  },
  {
    plan: 'ko-91',
    title: 'Makaron z groszkiem i boczkiem',
    description:
      'Wstążki makaronu w lekkim sosie śmietanowym z chrupiącym boczkiem, słodkim zielonym groszkiem i parmezanem. Gotowy w dwadzieścia minut, prosty jak carbonara i równie trudny do odmówienia sobie dokładki.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['makaron tagliatelle', 160, 'g'],
      ['sól', 3, 'g'],
      ['boczek', 80, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['groszek mrożony', 200, 'g'],
      ['śmietanka 18', 80, 'ml'],
      ['ser parmezan', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nastaw wodę na makaron, osól ją i ugotuj tagliatelle al dente według instrukcji na opakowaniu. Przed odcedzeniem odlej 100 ml wody z gotowania.',
      'Boczek pokrój w paski i smaż na suchej patelni 5–6 minut, aż wytopi tłuszcz i będzie chrupiący.',
      'Dodaj posiekaną cebulę i czosnek, smaż 3 minuty, a potem wsyp groszek prosto z zamrażarki i duś 4 minuty.',
      'Wlej śmietankę, zagotuj i przełóż makaron na patelnię. Wymieszaj, dolewając wodę z gotowania, aż sos będzie gładki i oblepi wstążki.',
      'Zdejmij z ognia, wmieszaj połowę startego parmezanu i dopraw pieprzem.',
      'Podawaj od razu, posypane resztą parmezanu i świeżo zmielonym pieprzem.',
    ],
    photo:
      'Tagliatelle ribbons in light cream sauce with crispy bacon strips, bright green peas, grated parmesan and cracked black pepper',
  },
  {
    plan: 'ko-92',
    title: 'Makaron z pieczoną fetą i pomidorkami',
    description:
      'Kostka fety pieczona w otoczeniu pomidorków koktajlowych, czosnku i oliwy, która po wyjęciu z piekarnika zamienia się w kremowy sos do makaronu. Hit internetu, który naprawdę działa i wymaga pięciu minut pracy.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['pomidor koktajlowy', 400, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 30, 'ml'],
      ['oregano', 1, 'g'],
      ['płatki chili', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['ser feta', 200, 'g'],
      ['makaron penne', 160, 'g'],
      ['bazylia', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół). Wsyp pomidorki i obrane ząbki czosnku do naczynia żaroodpornego, polej oliwą, posyp oregano, chili i pieprzem i wymieszaj.',
      'Połóż fetę w całości na środku naczynia i piecz 30 minut, aż pomidorki popękają, a ser zmięknie i lekko się zrumieni.',
      'W tym czasie ugotuj penne al dente w niesolonej wodzie (feta jest wystarczająco słona) i odlej 50 ml wody z gotowania.',
      'Rozgnieć widelcem fetę, pomidorki i czosnek i wymieszaj na gładki, kremowy sos, w razie potrzeby rozrzedzając go wodą z makaronu.',
      'Wrzuć makaron do naczynia i dokładnie wymieszaj, żeby każda rurka była pokryta sosem.',
      'Podawaj posypane listkami świeżej bazylii.',
    ],
    photo:
      'Penne pasta tossed in creamy orange-pink baked feta and burst cherry tomato sauce, garnished with fresh basil leaves',
  },
  {
    plan: 'ko-93',
    title: 'Kopytka smażone z boczkiem i cebulą',
    description:
      'Domowe kopytka z ziemniaków, najpierw ugotowane, potem przysmażone na złoto z chrupiącym boczkiem i słodką, zeszkloną cebulą. Sycąca, rustykalna kolacja, a przy okazji najlepszy sposób na wczorajsze kopytka.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['sól', 3, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 120, 'g'],
      ['boczek', 80, 'g'],
      ['cebula', 150, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['szczypiorek', 10, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i ugotuj w osolonej wodzie (2 g soli) do miękkości, około 20 minut. Odcedź, przeciśnij przez praskę i całkowicie ostudź.',
      'Do ziemniaków dodaj jajko, resztę soli i mąkę, szybko zagnieć gładkie, lekko klejące ciasto.',
      'Podziel ciasto na 4 części, z każdej uformuj wałek grubości 2,5 cm, spłaszcz go lekko i tnij ukośnie na kopytka długości 2 cm.',
      'Wrzucaj kopytka partiami do wrzącej wody i gotuj 2 minuty od wypłynięcia. Wyjmij łyżką cedzakową.',
      'Boczek pokrój w kostkę i wytop na dużej patelni (5 minut), dodaj cebulę pokrojoną w piórka i smaż 5 minut, aż się zeszkli. Wrzuć kopytka i smaż 6–8 minut, aż będą zrumienione z kilku stron.',
      'Dopraw pieprzem i podawaj posypane posiekanym szczypiorkiem.',
    ],
    photo:
      'Pan-fried golden potato dumplings with crispy bacon cubes and caramelised onion, sprinkled with chopped chives',
  },
  {
    plan: 'ko-94',
    title: 'Mintaj w sosie koperkowym z ziemniakami',
    description:
      'Delikatne filety z mintaja obsmażone na złoto i podane w aksamitnym sosie śmietanowo-koperkowym z nutą cytryny, z gotowanymi ziemniakami. Lekka, domowa ryba na kolację, gotowa w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['sól', 4, 'g'],
      ['mintaj', 400, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['mąka pszenna', 35, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['masło', 20, 'g'],
      ['bulion warzywny', 150, 'ml'],
      ['śmietanka 18', 100, 'ml'],
      ['cytryna', 20, 'g'],
      ['koperek', 20, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i gotuj w osolonej wodzie (2 g soli) około 20 minut, aż będą miękkie.',
      'Mintaja osusz, pokrój na 4 kawałki, dopraw 1 g soli i pieprzem, a potem obtocz w 15 g mąki.',
      'Smaż rybę na rozgrzanym oleju po 3 minuty z każdej strony, aż będzie złota i zacznie się rozwarstwiać. Przełóż na talerz.',
      'W rondelku roztop masło, dodaj resztę mąki i smaż minutę. Stopniowo wlewaj bulion, mieszając trzepaczką, potem śmietankę; gotuj 3 minuty, aż sos zgęstnieje.',
      'Dopraw sos sokiem z cytryny i resztą soli, zdejmij z ognia i wmieszaj posiekany koperek (odłóż trochę do posypania).',
      'Podawaj rybę polaną sosem koperkowym, z ziemniakami posypanymi koperkiem.',
    ],
    photo:
      'Golden pan-fried pollock fillets covered with creamy white dill sauce, boiled potatoes with dill and a lemon wedge on the side',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
