/**
 * Katalog 500 — część ob-a: obiady ob-1 … ob-34 z `prisma/catalog/katalog-500-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'ob-1',
    title: 'Zupa pieczarkowa z ziemniakami',
    description:
      'Gęsta, kremowa zupa z podsmażonych pieczarek, ziemniaków i warzyw korzeniowych, zabielona śmietaną i posypana koperkiem. Sycący obiad na chłodny dzień, podany z kromką chleba.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['pieczarka', 400, 'g'],
      ['ziemniak', 350, 'g'],
      ['marchew', 80, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['cebula', 100, 'g'],
      ['masło', 20, 'g'],
      ['bulion warzywny', 700, 'ml'],
      ['śmietana 18', 120, 'g'],
      ['koperek', 10, 'g'],
      ['chleb', 80, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz cebulę, marchew, pietruszkę i ziemniaki. Cebulę posiekaj w drobną kostkę, marchew i pietruszkę zetrzyj na tarce o grubych oczkach, ziemniaki pokrój w kostkę 1,5 cm, a pieczarki w cienkie plasterki.',
      'Rozgrzej masło w garnku i zeszklij cebulę przez 3 minuty. Dodaj pieczarki i smaż na dużym ogniu 8–10 minut, aż odparuje woda i zaczną się rumienić.',
      'Wlej bulion warzywny i 200 ml wody, dodaj marchew, pietruszkę i ziemniaki. Gotuj pod przykryciem na małym ogniu 15–20 minut, aż ziemniaki będą miękkie.',
      'Zahartuj śmietanę kilkoma łyżkami gorącej zupy, wlej do garnka i podgrzej, nie doprowadzając do wrzenia.',
      'Dopraw pieprzem (bulion jest już słony), wmieszaj posiekany koperek.',
      'Nalej zupę do misek i podawaj z kromką chleba.',
    ],
    photo:
      'Creamy beige mushroom soup with sliced mushrooms, potato cubes and grated carrot, sprinkled with fresh dill, a slice of bread on the side',
    vessel: 'bowl',
  },
  {
    plan: 'ob-2',
    title: 'Kapuśniak z kiszonej kapusty na żeberkach',
    description:
      'Kwaśna, rozgrzewająca zupa z kiszonej kapusty gotowana na wieprzowych żeberkach, z ziemniakami, majerankiem i kminkiem. Im dłużej postoi, tym lepsza — świetna na drugi dzień.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['żeberko wieprzowe', 400, 'g'],
      ['kapusta kiszona', 400, 'g'],
      ['ziemniak', 300, 'g'],
      ['marchew', 80, 'g'],
      ['cebula', 100, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['majeranek', 2, 'g'],
      ['kminek', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pokrój żeberka na pojedyncze kości, zalej 1,3 l zimnej wody, dodaj liść laurowy i ziele angielskie i gotuj na małym ogniu 45 minut, zbierając szumowiny.',
      'Kapustę kiszoną odciśnij i posiekaj nożem na krótsze kawałki. Dodaj ją do wywaru razem z kminkiem i gotuj 20 minut.',
      'Obierz ziemniaki i marchew, pokrój ziemniaki w kostkę 1,5 cm, a marchew w półplasterki. Dodaj do garnka i gotuj 15 minut, aż ziemniaki zmiękną.',
      'Cebulę posiekaj i zeszklij na oleju na złoto przez 5 minut, a potem przełóż do zupy.',
      'Wyjmij żeberka, obierz mięso z kości i wrzuć je z powrotem do garnka. Dopraw majerankiem roztartym w dłoniach, solą i pieprzem — sól dodawaj ostrożnie, bo kapusta jest słona.',
      'Podawaj gorący kapuśniak w głębokich talerzach, z kawałkami mięsa na wierzchu.',
    ],
    photo:
      'Golden sauerkraut soup with shredded cabbage, potato cubes, carrot slices and tender pieces of pork rib meat, dusted with dried marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'ob-3',
    title: 'Barszcz ukraiński',
    description:
      'Rubinowy barszcz z burakami, kapustą, fasolą i ziemniakami, zakwaszony octem i podany z łyżką śmietany. Dużo warzyw w jednym garnku i solidny obiad bez mięsa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['burak', 300, 'g'],
      ['kapusta biała', 200, 'g'],
      ['ziemniak', 250, 'g'],
      ['fasola biała z puszki', 200, 'g'],
      ['marchew', 80, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['bulion warzywny', 800, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['ocet jabłkowy', 10, 'ml'],
      ['cukier', 5, 'g'],
      ['śmietana 18', 60, 'g'],
      ['koperek', 8, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz warzywa. Buraki, marchew i pietruszkę pokrój w słupki 0,5 cm, ziemniaki w kostkę 1,5 cm, kapustę poszatkuj, cebulę posiekaj, a czosnek przeciśnij.',
      'Zagotuj bulion z 300 ml wody, wrzuć ziemniaki, marchew, pietruszkę i kapustę i gotuj 10 minut.',
      'W tym czasie na oleju podsmaż cebulę 3 minuty, dodaj buraki i koncentrat pomidorowy, skrop octem i duś 8 minut, mieszając.',
      'Przełóż buraki do garnka, dodaj odsączoną fasolę i czosnek i gotuj jeszcze 10–15 minut, aż wszystkie warzywa będą miękkie.',
      'Dopraw cukrem i pieprzem tak, by barszcz był słodko-kwaśny.',
      'Nalej do misek, na każdą porcję połóż łyżkę śmietany i posyp posiekanym koperkiem.',
    ],
    photo:
      'Deep ruby red borscht with strips of beetroot, cabbage, white beans and potato, a dollop of sour cream and chopped dill on top',
    vessel: 'bowl',
  },
  {
    plan: 'ob-4',
    title: 'Zupa jarzynowa na podudziach z kurczaka',
    description:
      'Klarowna zupa z mnóstwem warzyw — kalafiorem, fasolką, groszkiem i ziemniakami — gotowana na podudziach, z mięsem w talerzu. Lekka, a sycąca, lubiana przez dzieci.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 2,
    ingredients: [
      ['podudzie z kurczaka', 4, 'szt'],
      ['ziemniak', 300, 'g'],
      ['marchew', 150, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['seler korzeniowy', 80, 'g'],
      ['por', 100, 'g'],
      ['kalafior', 200, 'g'],
      ['fasolka szparagowa', 100, 'g'],
      ['groszek mrożony', 80, 'g'],
      ['masło', 10, 'g'],
      ['śmietana 12', 60, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Podudzia zalej 1,5 l zimnej wody, dodaj liść laurowy, ziele angielskie i zieloną część pora. Gotuj na małym ogniu 40 minut, zbierając szumowiny.',
      'Obierz ziemniaki, marchew, pietruszkę i seler i pokrój je w kostkę 1 cm. Kalafior podziel na małe różyczki, fasolkę pokrój na 2-centymetrowe kawałki, białą część pora na półplasterki.',
      'Wyjmij podudzia i przyprawy. Do wywaru wrzuć marchew, pietruszkę, seler i ziemniaki i gotuj 10 minut.',
      'Dodaj kalafior, fasolkę, groszek i por i gotuj jeszcze 8–10 minut, aż warzywa będą miękkie, ale nie rozgotowane.',
      'Obierz mięso z podudzi i wrzuć do zupy. Wmieszaj masło i zahartowaną śmietanę, dopraw solą i pieprzem.',
      'Podawaj posypaną posiekaną natką pietruszki.',
    ],
    photo:
      'Light golden vegetable soup with cauliflower florets, green beans, peas, carrot and potato cubes and shredded chicken, topped with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'ob-5',
    title: 'Grochówka z kiełbasą',
    description:
      'Gęsta zupa z łuskanego grochu z wędzoną kiełbasą, boczkiem i majerankiem. Tradycyjny, bardzo sycący obiad, który po odgrzaniu jest jeszcze lepszy.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 100,
    servings: 2,
    ingredients: [
      ['groch łuskany', 160, 'g'],
      ['kiełbasa wędzona', 160, 'g'],
      ['boczek', 40, 'g'],
      ['ziemniak', 200, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['majeranek', 3, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Groch przepłucz, zalej 1,5 l wody, dodaj liść laurowy i ziele angielskie i gotuj pod przykryciem na małym ogniu 45 minut, aż zacznie się rozpadać.',
      'Obierz ziemniaki, marchew i pietruszkę i pokrój w kostkę 1 cm. Dodaj do grochu i gotuj 15 minut.',
      'Boczek pokrój w drobną kostkę i wytop na patelni. Dodaj posiekaną cebulę i kiełbasę w półplasterkach i smaż 5 minut, aż się zrumienią.',
      'Przełóż zawartość patelni do garnka, dodaj przeciśnięty czosnek i gotuj jeszcze 10 minut, często mieszając, bo zupa lubi przywierać.',
      'Dopraw majerankiem roztartym w dłoniach, pieprzem i ewentualnie solą — kiełbasa i boczek są już słone.',
      'Podawaj gęstą grochówkę w głębokich talerzach, z kiełbasą na wierzchu.',
    ],
    photo:
      'Thick golden-yellow split pea soup with slices of smoked sausage and crispy bacon bits, diced carrot and potato, sprinkled with marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'ob-6',
    title: 'Zupa fasolowa z kiełbasą',
    description:
      'Treściwa zupa z białej fasoli z kiełbasą, warzywami i koncentratem pomidorowym, doprawiona majerankiem. Szybsza wersja na fasoli z puszki, bez nocnego moczenia.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['fasola biała z puszki', 480, 'g'],
      ['kiełbasa wędzona', 150, 'g'],
      ['ziemniak', 200, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['majeranek', 3, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki, marchew i pietruszkę i pokrój w kostkę 1 cm. Zalej 1,2 l wody, dodaj liść laurowy i ziele angielskie i gotuj 15 minut.',
      'Na oleju podsmaż posiekaną cebulę i kiełbasę pokrojoną w półplasterki przez 5 minut, aż kiełbasa się zrumieni.',
      'Przełóż kiełbasę z cebulą do garnka, dodaj odsączoną i przepłukaną fasolę, koncentrat pomidorowy i przeciśnięty czosnek.',
      'Gotuj 10 minut na małym ogniu. Chochlę fasoli rozgnieć widelcem i wmieszaj z powrotem — zupa zgęstnieje.',
      'Dopraw majerankiem, pieprzem i solą do smaku.',
      'Podawaj gorącą, posypaną szczyptą majeranku.',
    ],
    photo:
      'Hearty reddish bean soup with white beans, sausage half-moons, diced carrot and potato, sprinkled with dried marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'ob-7',
    title: 'Zupa koperkowa z ryżem',
    description:
      'Delikatna zupa na rosole z podudzi, z dużą ilością świeżego koperku, ryżem i śmietaną. Łagodna i aromatyczna — dobra na lekki, ale syty obiad.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 2,
    ingredients: [
      ['podudzie z kurczaka', 4, 'szt'],
      ['ryż biały', 80, 'g'],
      ['marchew', 120, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['seler korzeniowy', 60, 'g'],
      ['por', 80, 'g'],
      ['koperek', 40, 'g'],
      ['śmietana 18', 100, 'g'],
      ['masło', 10, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Podudzia zalej 1,5 l zimnej wody, dodaj liść laurowy i ziele angielskie i gotuj na małym ogniu 40 minut, zbierając szumowiny.',
      'Obierz marchew, pietruszkę i seler i zetrzyj na tarce o grubych oczkach, pora pokrój w cienkie półplasterki. Ryż przepłucz na sitku.',
      'Wyjmij podudzia i przyprawy, do wywaru wsyp ryż i warzywa. Gotuj 15 minut, aż ryż będzie miękki.',
      'Obierz mięso z kości i wrzuć do zupy. Koperek posiekaj drobno razem z łodyżkami i dodaj razem z masłem.',
      'Zahartuj śmietanę kilkoma łyżkami zupy i wlej do garnka. Podgrzej bez gotowania, dopraw solą i pieprzem.',
      'Podawaj od razu, posypaną resztą świeżego koperku.',
    ],
    photo:
      'Pale creamy dill soup with rice, grated carrot and shredded chicken, generously topped with chopped fresh green dill',
    vessel: 'bowl',
  },
  {
    plan: 'ob-8',
    title: 'Zupa szczawiowa z jajkiem',
    description:
      'Orzeźwiająco kwaśna zupa ze świeżego szczawiu z ziemniakami, zabielona śmietaną i podana z połówkami jajka na twardo. Wiosenny klasyk, gotowy w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['szczaw', 250, 'g'],
      ['ziemniak', 400, 'g'],
      ['jajko', 4, 'szt'],
      ['bulion drobiowy', 800, 'ml'],
      ['masło', 15, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['śmietana 18', 100, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki, pokrój w kostkę 1,5 cm, zalej bulionem z 300 ml wody i gotuj 15 minut, aż zmiękną.',
      'Jajka ugotuj na twardo (10 minut), ostudź w zimnej wodzie, obierz i przekrój na połówki.',
      'Szczaw umyj, oberwij twarde łodygi i posiekaj. Na maśle w rondelku duś go 2–3 minuty, aż zmieni kolor na oliwkowy.',
      'Przełóż szczaw do garnka i gotuj 5 minut.',
      'Śmietanę wymieszaj z mąką na gładko, zahartuj gorącą zupą, wlej do garnka i zagotuj raz, mieszając. Dopraw pieprzem.',
      'Nalej do misek, do każdej włóż dwie połówki jajka i posyp posiekanym szczypiorkiem.',
    ],
    photo:
      'Olive green creamy sorrel soup with potato cubes and halved hard-boiled eggs showing bright yellow yolks, sprinkled with chives',
    vessel: 'bowl',
  },
  {
    plan: 'ob-9',
    title: 'Minestrone z fasolą i makaronem',
    description:
      'Włoska zupa warzywna z pomidorami, cukinią, fasolą i drobnym makaronem, podana z parmezanem i bazylią. Kolorowa, gęsta i sycąca — sprawdza się też odgrzana w pudełku.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['fasola biała z puszki', 240, 'g'],
      ['makaron kolanka', 80, 'g'],
      ['cukinia', 200, 'g'],
      ['marchew', 100, 'g'],
      ['seler naciowy', 80, 'g'],
      ['fasolka szparagowa', 100, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['bulion warzywny', 600, 'ml'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ser parmezan', 30, 'g'],
      ['bazylia', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę, marchew i seler naciowy pokrój w kostkę 0,5 cm, cukinię w kostkę 1 cm, fasolkę na 2-centymetrowe kawałki, czosnek posiekaj.',
      'Na oliwie w garnku podsmaż cebulę, marchew i seler przez 6 minut, dodaj czosnek i smaż jeszcze minutę.',
      'Dodaj pomidory z puszki, bulion i 300 ml wody, zagotuj. Wrzuć fasolkę i cukinię i gotuj 10 minut.',
      'Wsyp makaron i dodaj odsączoną fasolę. Gotuj 8–10 minut, aż makaron będzie al dente.',
      'Dopraw pieprzem, wmieszaj połowę porwanej bazylii.',
      'Podawaj posypaną startym parmezanem i resztą bazylii.',
    ],
    photo:
      'Thick tomato minestrone with white beans, small elbow pasta, zucchini, green beans and carrot, topped with grated parmesan and fresh basil leaves',
    vessel: 'bowl',
  },
  {
    plan: 'ob-10',
    title: 'Krem z kalafiora z grzankami',
    description:
      'Aksamitny krem z kalafiora i ziemniaków ze śmietanką i nutą gałki muszkatołowej, podany z chrupiącymi grzankami i pestkami dyni. Łagodny w smaku i gotowy w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['kalafior', 700, 'g'],
      ['ziemniak', 200, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 20, 'g'],
      ['bulion warzywny', 600, 'ml'],
      ['śmietanka 18', 100, 'ml'],
      ['gałka muszkatołowa', 1, 'g'],
      ['chleb', 120, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['pestki dyni', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kalafior podziel na różyczki, ziemniaki obierz i pokrój w kostkę, cebulę i czosnek posiekaj.',
      'Na maśle zeszklij cebulę przez 4 minuty, dodaj czosnek, kalafior i ziemniaki i smaż 2 minuty.',
      'Zalej bulionem z 200 ml wody i gotuj pod przykryciem 20 minut, aż warzywa będą bardzo miękkie.',
      'W tym czasie pokrój chleb w kostkę 1,5 cm, skrop oliwą i zrumień na suchej patelni przez 5–6 minut. Na końcu podpraż na niej pestki dyni przez 2 minuty.',
      'Zmiksuj zupę blenderem na gładki krem, wlej śmietankę i podgrzej. Dopraw gałką muszkatołową i pieprzem — bulion wystarczy za sól.',
      'Podawaj w miseczkach z grzankami i pestkami dyni na wierzchu.',
    ],
    photo:
      'Smooth ivory cauliflower cream soup topped with golden bread croutons, toasted pumpkin seeds and a drizzle of olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'ob-11',
    title: 'Krem z marchewki z imbirem i mlekiem kokosowym',
    description:
      'Pomarańczowy, jedwabisty krem z marchwi z rozgrzewającym imbirem i mlekiem kokosowym, podany z pestkami dyni i pieczywem. Słodkawy, lekko pikantny i świetny do pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['marchew', 600, 'g'],
      ['ziemniak', 150, 'g'],
      ['cebula', 100, 'g'],
      ['imbir', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['bulion warzywny', 600, 'ml'],
      ['mleko kokosowe z puszki', 150, 'ml'],
      ['kurkuma', 1, 'g'],
      ['pestki dyni', 20, 'g'],
      ['chleb', 100, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz marchew i ziemniaki i pokrój w plasterki 1 cm. Cebulę posiekaj, imbir i czosnek zetrzyj na drobnej tarce.',
      'Na oleju zeszklij cebulę przez 4 minuty, dodaj imbir, czosnek i kurkumę i smaż 1 minutę, aż zapachną.',
      'Dodaj marchew i ziemniaki, zalej bulionem z 200 ml wody i gotuj pod przykryciem 20–25 minut, aż marchew będzie miękka.',
      'Wlej mleko kokosowe (odlej 2 łyżki do dekoracji) i zmiksuj blenderem na gładki krem. Dopraw pieprzem.',
      'Pestki dyni upraż na suchej patelni przez 2–3 minuty.',
      'Rozlej krem do misek, skrop odłożonym mlekiem kokosowym, posyp pestkami i podawaj z pieczywem.',
    ],
    photo:
      'Vivid orange carrot ginger cream soup with a swirl of coconut milk and toasted pumpkin seeds, slices of bread beside the bowl',
    vessel: 'bowl',
  },
  {
    plan: 'ob-12',
    title: 'Krem z cukinii z fetą i grzankami',
    description:
      'Zielony, lekki krem z cukinii zagęszczony ziemniakiem i serkiem, podany z pokruszoną fetą i grzankami. Dobry sposób na letni nadmiar cukinii — gotowy w 35 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['cukinia', 800, 'g'],
      ['ziemniak', 250, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 20, 'g'],
      ['bulion warzywny', 500, 'ml'],
      ['serek kanapkowy', 80, 'g'],
      ['ser feta', 60, 'g'],
      ['chleb', 100, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['koperek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cukinię pokrój w półplasterki (nie obieraj — skórka daje kolor), ziemniaki obierz i pokrój w kostkę, cebulę i czosnek posiekaj.',
      'Na maśle zeszklij cebulę przez 4 minuty, dodaj czosnek, cukinię i ziemniaki i smaż 3 minuty.',
      'Zalej bulionem z 200 ml wody i gotuj 15 minut, aż ziemniaki będą miękkie.',
      'Chleb pokrój w kostkę, skrop oliwą i zrumień na patelni przez 5 minut, mieszając.',
      'Dodaj do zupy serek kanapkowy i zmiksuj na gładki krem. Dopraw pieprzem — soli nie trzeba, bo bulion i feta są słone.',
      'Podawaj z pokruszoną fetą, grzankami i posiekanym koperkiem.',
    ],
    photo:
      'Pale green zucchini cream soup topped with crumbled white feta, golden croutons and chopped dill',
    vessel: 'bowl',
  },
  {
    plan: 'ob-13',
    title:
      'Kotlet z piersi kurczaka w panierce z ziemniakami i surówką z marchwi',
    description:
      'Soczysty kotlet z rozbitej piersi kurczaka w chrupiącej panierce, podany z ziemniakami z koperkiem i surówką z marchwi i jabłka. Niedzielny klasyk, który zrobisz w niecałą godzinę.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 20, 'g'],
      ['bułka tarta', 40, 'g'],
      ['olej rzepakowy', 40, 'ml'],
      ['ziemniak', 500, 'g'],
      ['masło', 10, 'g'],
      ['koperek', 5, 'g'],
      ['marchew', 200, 'g'],
      ['jabłko', 150, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki, zalej osoloną wodą i gotuj 20 minut do miękkości.',
      'Filet przekrój poziomo na 2 cieńsze kotlety, przykryj folią i rozbij tłuczkiem na grubość 1 cm. Posól i popieprz z obu stron.',
      'Przygotuj trzy talerze: z mąką, roztrzepanym jajkiem i bułką tartą. Obtocz kotlety kolejno w mące, jajku i bułce, dociskając panierkę.',
      'Rozgrzej 35 ml oleju na patelni i smaż kotlety na średnim ogniu 4–5 minut z każdej strony, aż będą złote, a sok przy nakłuciu przezroczysty. Odsącz na ręczniku papierowym.',
      'Marchew i jabłko zetrzyj na tarce o drobnych oczkach, skrop sokiem z cytryny i resztą oleju, dopraw szczyptą soli.',
      'Ziemniaki odcedź, polej roztopionym masłem i posyp koperkiem. Podawaj z kotletem i surówką.',
    ],
    photo:
      'Golden breaded chicken cutlet with boiled potatoes glazed with butter and dill, and a bright orange grated carrot and apple salad',
  },
  {
    plan: 'ob-14',
    title: 'Kotlet de volaille z ziemniakami i mizerią',
    description:
      'Zwinięta pierś kurczaka z masłem koperkowym w środku, smażona w złocistej panierce, z ziemniakami i mizerią. Po przekrojeniu wypływa aromatyczne masło — efekt jak z dawnej restauracji, ale w domu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 320, 'g'],
      ['masło', 30, 'g'],
      ['koperek', 10, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 20, 'g'],
      ['bułka tarta', 50, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['ziemniak', 500, 'g'],
      ['ogórek', 250, 'g'],
      ['śmietana 12', 60, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Miękkie masło wymieszaj z połową posiekanego koperku, uformuj 2 wałeczki i schowaj do zamrażarki na 15 minut.',
      'Filet przekrój na 2 płaty, rozbij przez folię na cienkie kotlety (0,5 cm), posól i popieprz. Na każdym połóż wałeczek masła i zwiń ciasno, zakładając boki do środka, by masło nie wyciekło.',
      'Obtocz roladki w mące, jajku i bułce tartej, potem jeszcze raz w jajku i bułce — podwójna panierka trzyma masło w środku.',
      'Obierz ziemniaki i ugotuj w osolonej wodzie przez 20 minut.',
      'Smaż kotlety na oleju na średnim ogniu 10–12 minut, obracając, aż będą złote ze wszystkich stron. Dopiecz 5 minut w piekarniku nagrzanym do 180°C (góra–dół).',
      'Ogórek pokrój w cienkie plasterki, lekko posól, odciśnij i wymieszaj ze śmietaną i pieprzem. Podawaj kotlety z ziemniakami posypanymi resztą koperku i mizerią.',
    ],
    photo:
      'Golden breaded chicken Kiev cut open with melted herb butter flowing out, boiled potatoes with dill and a creamy cucumber salad',
  },
  {
    plan: 'ob-15',
    title: 'Pieczone udka z ziemniakami',
    description:
      'Udka w paprykowo-czosnkowej marynacie pieczone na jednej blasze z ziemniakami i czerwoną cebulą. Chrupiąca skórka, miękkie mięso i zero stania przy garach.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 2,
    ingredients: [
      ['udko z kurczaka', 2, 'szt'],
      ['ziemniak', 600, 'g'],
      ['cebula czerwona', 1, 'szt'],
      ['czosnek', 3, 'szt'],
      ['olej rzepakowy', 20, 'ml'],
      ['papryka słodka mielona', 4, 'g'],
      ['majeranek', 2, 'g'],
      ['zioła prowansalskie', 2, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg 190°C).',
      'Wymieszaj połowę oleju z przeciśniętym czosnkiem, papryką, majerankiem, 2 g soli i pieprzem. Natrzyj udka marynatą, także pod skórą.',
      'Ziemniaki obierz (albo wyszoruj) i pokrój w ósemki, cebulę w grube piórka. Wymieszaj z resztą oleju, ziołami prowansalskimi i solą.',
      'Rozłóż ziemniaki i cebulę na blasze, na nich połóż udka skórą do góry.',
      'Piecz 45–50 minut, aż skórka będzie chrupiąca, a sok przy kości przezroczysty. W połowie przemieszaj ziemniaki.',
      'Podawaj udka z ziemniakami, posypane posiekaną natką pietruszki.',
    ],
    photo:
      'Two roasted chicken legs with crispy paprika-red skin on a bed of golden potato wedges and red onion, sprinkled with parsley',
  },
  {
    plan: 'ob-16',
    title: 'Pulpety w sosie koperkowym z ziemniakami',
    description:
      'Miękkie pulpety z chudej wieprzowiny gotowane w bulionie i podane w kremowym sosie koperkowym z ziemniakami. Łagodne, domowe danie, które lubią i dorośli, i dzieci.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['wieprzowina mielona chuda', 300, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 30, 'g'],
      ['cebula', 60, 'g'],
      ['bulion warzywny', 600, 'ml'],
      ['śmietana 18', 100, 'g'],
      ['mąka pszenna', 15, 'g'],
      ['koperek', 25, 'g'],
      ['ziemniak', 500, 'g'],
      ['masło', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę zetrzyj na drobnej tarce. Wymieszaj mięso z cebulą, jajkiem, bułką tartą, 1 g soli i pieprzem i wyrabiaj ręką 2 minuty.',
      'Mokrymi dłońmi uformuj kulki wielkości orzecha włoskiego (ok. 12 sztuk).',
      'Zagotuj bulion, włóż pulpety i gotuj na małym ogniu pod przykryciem 20 minut.',
      'W tym czasie obierz ziemniaki i ugotuj je w osolonej wodzie przez 20 minut, odcedź i polej masłem.',
      'Śmietanę wymieszaj z mąką na gładko, zahartuj gorącym bulionem i wlej do garnka. Gotuj 2 minuty, aż sos zgęstnieje, wmieszaj posiekany koperek i dopraw pieprzem.',
      'Podawaj pulpety w sosie z ziemniakami, posypane resztą koperku.',
    ],
    photo:
      'Round pork meatballs in a pale creamy dill sauce flecked with green, served with buttered boiled potatoes',
  },
  {
    plan: 'ob-17',
    title: 'Zrazy wołowe zawijane z kaszą gryczaną',
    description:
      'Cienkie plastry wołowiny zwinięte z boczkiem, ogórkiem kiszonym i cebulą, długo duszone w gęstym sosie i podane z kaszą gryczaną. Świąteczny w charakterze obiad, który warto zrobić w weekend.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 130,
    servings: 2,
    ingredients: [
      ['wołowina', 400, 'g'],
      ['boczek', 60, 'g'],
      ['ogórek kiszony', 80, 'g'],
      ['cebula', 150, 'g'],
      ['musztarda', 20, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['kasza gryczana', 140, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wołowinę (udziec lub zrazową) pokrój w poprzek włókien na 4 plastry grubości 1 cm i rozbij tłuczkiem przez folię na cienkie płaty. Posól i popieprz.',
      'Każdy płat posmaruj musztardą, ułóż na brzegu plaster boczku, słupek ogórka kiszonego i piórka połowy cebuli. Zwiń ciasno i spnij wykałaczką.',
      'Obtocz zrazy w części mąki i obsmaż na rozgrzanym oleju z każdej strony na brązowo, około 6 minut.',
      'Dodaj resztę cebuli w piórkach, liść laurowy i ziele angielskie, wlej 500 ml gorącej wody i duś pod przykryciem na małym ogniu 90 minut, aż mięso będzie miękkie. W razie potrzeby dolewaj wody.',
      'Kaszę przepłucz, wsyp do 300 ml osolonej wrzącej wody i gotuj pod przykryciem 15 minut, a potem odstaw na 10 minut.',
      'Resztę mąki rozmieszaj w odrobinie zimnej wody i zagęść sos, gotując 2 minuty. Wyjmij wykałaczki i podawaj zrazy w sosie z kaszą.',
    ],
    photo:
      'Two beef roulades in glossy dark brown gravy, one sliced to show bacon and pickle filling, served with fluffy buckwheat groats',
  },
  {
    plan: 'ob-18',
    title: 'Karkówka duszona z cebulą i ziemniakami',
    description:
      'Plastry karkówki duszone powoli w słodkim sosie z dużej ilości cebuli i majeranku, podane z ziemniakami i ogórkiem kiszonym. Mięso rozpada się pod widelcem.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 100,
    servings: 2,
    ingredients: [
      ['karkówka', 350, 'g'],
      ['cebula', 300, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['mąka pszenna', 10, 'g'],
      ['majeranek', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['ziemniak', 500, 'g'],
      ['ogórek kiszony', 100, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Karkówkę pokrój na 4 plastry grubości 1,5 cm, lekko rozbij, natrzyj solą, pieprzem i majerankiem. Obtocz w mące.',
      'Obsmaż mięso na rozgrzanym oleju po 2 minuty z każdej strony, aż się zrumieni.',
      'Cebulę pokrój w grube piórka i wrzuć na patelnię obok mięsa. Smaż 5 minut, dodaj liść laurowy i ziele angielskie.',
      'Wlej 300 ml gorącej wody, przykryj i duś na małym ogniu 70 minut, aż mięso będzie miękkie, a cebula rozpadnie się w gęsty sos.',
      'Pod koniec duszenia obierz ziemniaki i ugotuj je w osolonej wodzie przez 20 minut.',
      'Podawaj karkówkę z sosem cebulowym, ziemniakami i ogórkiem kiszonym pokrojonym w plasterki.',
    ],
    photo:
      'Tender braised pork neck slices smothered in soft golden onion gravy, boiled potatoes and sliced pickled cucumber on the side',
  },
  {
    plan: 'ob-19',
    title: 'Żeberka pieczone w miodzie z ziemniakami',
    description:
      'Wieprzowe żeberka w glazurze z miodu, sosu sojowego i czosnku, pieczone do miękkości razem z ziemniakami. Lepkie, słodko-słone i idealne na weekendowy obiad.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 120,
    servings: 2,
    ingredients: [
      ['żeberko wieprzowe', 550, 'g'],
      ['miód', 30, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['czosnek', 3, 'szt'],
      ['musztarda', 15, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['ziemniak', 500, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['rozmaryn suszony', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wymieszaj miód, sos sojowy, przeciśnięty czosnek, musztardę, paprykę i pieprz. Żeberka pokrój na porcje po 2–3 kości i natrzyj połową glazury.',
      'Nagrzej piekarnik do 170°C (góra–dół). Ułóż żeberka w naczyniu żaroodpornym, podlej 100 ml wody, przykryj folią i piecz 60 minut.',
      'Ziemniaki pokrój w ćwiartki, wymieszaj z olejem, rozmarynem i solą.',
      'Zdejmij folię, posmaruj żeberka resztą glazury, dookoła rozłóż ziemniaki i zwiększ temperaturę do 200°C.',
      'Piecz jeszcze 35–40 minut, raz przewracając ziemniaki i polewając żeberka sosem z naczynia, aż mięso będzie ciemnozłote i lepkie.',
      'Podawaj żeberka z ziemniakami, polane sosem z dna naczynia.',
    ],
    photo:
      'Sticky honey-glazed pork ribs with dark caramelized edges, roasted potato quarters with rosemary around them',
  },
  {
    plan: 'ob-20',
    title: 'Schab pieczony z ziemniakami i surówką z kapusty',
    description:
      'Kawałek schabu natarty czosnkiem, majerankiem i musztardą, upieczony w całości i podany w plastrach z ziemniakami i chrupiącą surówką z białej kapusty. Wystarczy go wstawić do piekarnika.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['schab wieprzowy', 400, 'g'],
      ['czosnek', 3, 'szt'],
      ['majeranek', 3, 'g'],
      ['musztarda', 10, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['ziemniak', 500, 'g'],
      ['masło', 10, 'g'],
      ['koperek', 5, 'g'],
      ['kapusta biała', 250, 'g'],
      ['marchew', 80, 'g'],
      ['jabłko', 100, 'g'],
      ['ocet jabłkowy', 10, 'ml'],
      ['cukier', 3, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wymieszaj przeciśnięty czosnek, majeranek, musztardę, 15 ml oleju, 2 g soli i pieprz. Natrzyj schab i odstaw na 15 minut.',
      'Nagrzej piekarnik do 180°C (góra–dół). Obsmaż schab na suchej, rozgrzanej patelni ze wszystkich stron przez 4 minuty, przełóż do naczynia żaroodpornego i podlej 100 ml wody.',
      'Piecz 50 minut, polewając co 15 minut sosem z naczynia. Mięso jest gotowe, gdy w środku ma 68°C albo sok jest przezroczysty. Odstaw na 10 minut przed krojeniem.',
      'W tym czasie obierz ziemniaki i ugotuj je w osolonej wodzie przez 20 minut.',
      'Kapustę poszatkuj cienko, pognieć z szczyptą soli, dodaj startą marchew i jabłko, resztę oleju, ocet i cukier. Wymieszaj.',
      'Pokrój schab w plastry, polej sosem z pieczenia. Podawaj z ziemniakami z masłem i koperkiem oraz surówką.',
    ],
    photo:
      'Juicy slices of roast pork loin with pan juices, boiled potatoes with butter and dill, and a fresh white cabbage and carrot slaw',
  },
  {
    plan: 'ob-21',
    title: 'Pieczeń rzymska z jajkiem i ziemniakami',
    description:
      'Pieczony klops z mielonego mięsa z ukrytymi w środku jajkami na twardo, podany w plastrach z ziemniakami i ogórkiem kiszonym. Na zimno świetnie smakuje też w kanapkach.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 80,
    servings: 2,
    ingredients: [
      ['wieprzowina i wołowina mielona', 300, 'g'],
      ['jajko', 3, 'szt'],
      ['bułka', 40, 'g'],
      ['mleko', 60, 'ml'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['majeranek', 2, 'g'],
      ['bułka tarta', 15, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ziemniak', 500, 'g'],
      ['ogórek kiszony', 100, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dwa jajka ugotuj na twardo (10 minut), ostudź i obierz. Bułkę namocz w mleku, cebulę posiekaj i zeszklij na połowie oleju.',
      'Nagrzej piekarnik do 180°C (góra–dół). Do mięsa dodaj odciśniętą bułkę, cebulę, surowe jajko, przeciśnięty czosnek, majeranek, 2 g soli i pieprz. Wyrabiaj 3 minuty.',
      'Połowę masy rozłóż w keksówce wysmarowanej resztą oleju i posypanej bułką tartą, ułóż jajka wzdłuż, przykryj resztą mięsa i wyrównaj.',
      'Piecz 50 minut, aż wierzch się zrumieni, a sok będzie przezroczysty. Odstaw na 10 minut przed krojeniem.',
      'W tym czasie obierz ziemniaki i ugotuj je w osolonej wodzie przez 20 minut.',
      'Pokrój pieczeń w grube plastry tak, by w każdym było widać jajko. Podawaj z ziemniakami i ogórkiem kiszonym.',
    ],
    photo:
      'Thick slices of baked meatloaf with a hard-boiled egg in the centre of each slice, boiled potatoes and pickled cucumber on the side',
  },
  {
    plan: 'ob-22',
    title: 'Wątróbka drobiowa z cebulką, jabłkiem i ziemniakami',
    description:
      'Delikatna wątróbka krótko smażona na maśle z karmelizowaną cebulą i plasterkami jabłka, podana z ziemniakami. Tani, szybki obiad bogaty w żelazo.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['wątróbka drobiowa', 400, 'g'],
      ['cebula', 300, 'g'],
      ['jabłko', 150, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['masło', 20, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['majeranek', 2, 'g'],
      ['ziemniak', 500, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki i ugotuj je w osolonej wodzie przez 20 minut.',
      'Wątróbkę opłucz, osusz i oczyść z błon, większe kawałki przekrój na pół. Cebulę pokrój w piórka, jabłko w cząstki.',
      'Na oleju smaż cebulę na średnim ogniu 10 minut, aż się skarmelizuje. Dodaj jabłko i smaż 3 minuty, przełóż na talerz.',
      'Wątróbkę obtocz w mące i smaż na maśle na dużym ogniu po 2–3 minuty z każdej strony — w środku ma być lekko różowa. Sol dopiero na końcu, bo inaczej stwardnieje.',
      'Wróć cebulę i jabłko na patelnię, posyp majerankiem, posól, popieprz i podgrzej razem minutę.',
      'Podawaj wątróbkę z cebulą i jabłkiem oraz ziemniakami posypanymi koperkiem.',
    ],
    photo:
      'Pan-fried chicken livers with caramelized onion and golden apple wedges, boiled potatoes with dill on the side',
  },
  {
    plan: 'ob-23',
    title: 'Bigos z kiełbasą i suszonymi grzybami',
    description:
      'Długo duszony bigos z kiszonej i słodkiej kapusty z wieprzowiną, kiełbasą, suszonymi grzybami i śliwkami. Głęboki, lekko wędzony smak, który rośnie z każdym odgrzaniem.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 150,
    servings: 2,
    ingredients: [
      ['kapusta kiszona', 400, 'g'],
      ['kapusta biała', 400, 'g'],
      ['łopatka wieprzowa', 150, 'g'],
      ['kiełbasa wędzona', 120, 'g'],
      ['boczek', 50, 'g'],
      ['grzyb suszony', 10, 'g'],
      ['śliwka suszona', 40, 'g'],
      ['cebula', 150, 'g'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['majeranek', 2, 'g'],
      ['chleb', 60, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby zalej 200 ml wrzątku i odstaw na 20 minut. Kapustę kiszoną odciśnij i posiekaj, białą poszatkuj.',
      'Kapustę kiszoną zalej 300 ml wody, dodaj liść laurowy i ziele angielskie i gotuj 30 minut. Dodaj białą kapustę i gotuj kolejne 20 minut.',
      'Łopatkę pokrój w kostkę 1,5 cm, boczek i kiełbasę w kostkę. Na oleju wytop boczek, obsmaż łopatkę, dodaj posiekaną cebulę i kiełbasę i smaż 8 minut.',
      'Przełóż mięso do kapusty. Dodaj pokrojone grzyby z wodą z moczenia, pokrojone śliwki i koncentrat pomidorowy.',
      'Duś pod przykryciem na małym ogniu 60 minut, często mieszając, aż bigos będzie ciemny i gęsty. Dopraw majerankiem i pieprzem — soli zwykle nie trzeba.',
      'Podawaj gorący bigos z kromką chleba.',
    ],
    photo:
      'Dark brown hunter stew of braised sauerkraut with chunks of pork, smoked sausage and mushrooms, a slice of rustic bread alongside',
  },
  {
    plan: 'ob-24',
    title: 'Placki po węgiersku',
    description:
      'Chrupiące placki ziemniaczane polane paprykowym gulaszem wieprzowym i łyżką śmietany. Dwa ulubione dania w jednym — porządny, rozgrzewający obiad.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['łopatka wieprzowa', 250, 'g'],
      ['cebula', 200, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['papryka słodka mielona', 5, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['ziemniak', 600, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 40, 'g'],
      ['olej rzepakowy', 35, 'ml'],
      ['śmietana 12', 60, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Łopatkę pokrój w kostkę 2 cm. Obsmaż na 10 ml oleju, dodaj 150 g posiekanej cebuli, czosnek i obie papryki mielone i smaż 3 minuty.',
      'Dodaj koncentrat, 400 ml wody i 2 g soli i duś pod przykryciem 50 minut. Na ostatnie 15 minut dodaj paprykę pokrojoną w paski.',
      'Ziemniaki i resztę cebuli zetrzyj na drobnej tarce, odciśnij nadmiar soku na sitku. Dodaj jajko, mąkę, resztę soli i pieprz i wymieszaj.',
      'Na rozgrzanym oleju smaż duże, cienkie placki na średnim ogniu po 3–4 minuty z każdej strony, aż będą złote i chrupiące. Odsącz na ręczniku papierowym.',
      'Sprawdź gulasz — mięso ma być miękkie, a sos gęsty. W razie potrzeby odparuj go bez pokrywki.',
      'Na każdy talerz połóż placek, nałóż gulasz, złóż placek na pół i dodaj łyżkę śmietany.',
    ],
    photo:
      'Large golden crispy potato pancake folded over a rich red paprika pork goulash with pepper strips, topped with a spoonful of sour cream',
  },
  {
    plan: 'ob-25',
    title: 'Papryka faszerowana mięsem i ryżem w sosie pomidorowym',
    description:
      'Czerwone papryki nadziane mielonym mięsem z ryżem, pieczone w sosie pomidorowym z oregano. Soczyste i sycące, a następnego dnia równie dobre z pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 2,
    ingredients: [
      ['papryka czerwona', 4, 'szt'],
      ['wieprzowina i wołowina mielona', 250, 'g'],
      ['ryż biały', 60, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 400, 'ml'],
      ['olej rzepakowy', 10, 'ml'],
      ['oregano', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['śmietana 12', 40, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ryż ugotuj w osolonej wodzie przez 10 minut (ma być lekko twardy) i odcedź. Cebulę posiekaj i zeszklij na oleju z czosnkiem.',
      'Wymieszaj mięso z ryżem, połową cebuli, papryką mieloną, 2 g soli, pieprzem i połową natki.',
      'Paprykom odetnij czubki, wydrąż gniazda nasienne. Napełnij je farszem, lekko ubijając, i przykryj odciętymi czubkami.',
      'Nagrzej piekarnik do 190°C (góra–dół). Passatę wymieszaj z resztą cebuli, oregano i szczyptą soli, wlej do naczynia żaroodpornego i ustaw w nim papryki.',
      'Przykryj folią i piecz 35 minut, zdejmij folię i piecz jeszcze 15 minut, aż papryki zmiękną i lekko się przypieką.',
      'Wmieszaj śmietanę w sos z naczynia. Podawaj papryki polane sosem i posypane resztą natki.',
    ],
    photo:
      'Four red bell peppers stuffed with meat and rice, lids slightly charred, sitting in a creamy tomato sauce sprinkled with parsley',
  },
  {
    plan: 'ob-26',
    title: 'Kopytka z sosem pieczarkowym',
    description:
      'Domowe kopytka z ziemniaków i mąki podane z gęstym sosem ze smażonych pieczarek i śmietany. Klasyk kuchni bezmięsnej, który syci na długo.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 70,
    servings: 2,
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['mąka pszenna', 170, 'g'],
      ['jajko', 1, 'szt'],
      ['pieczarka', 400, 'g'],
      ['cebula', 100, 'g'],
      ['masło', 20, 'g'],
      ['śmietana 18', 150, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i ugotuj w osolonej wodzie przez 20 minut. Odcedź, odparuj i przeciśnij przez praskę, a potem całkowicie ostudź.',
      'Do ziemniaków dodaj jajko, mąkę i szczyptę soli i szybko zagnieć gładkie, lekko klejące ciasto.',
      'Podziel ciasto na 4 części, z każdej uformuj wałek grubości 2,5 cm, lekko spłaszcz i tnij ukośnie na kopytka.',
      'Pieczarki pokrój w plasterki, cebulę w kostkę. Na maśle zeszklij cebulę, dodaj pieczarki i smaż 10 minut, aż się zrumienią. Dodaj śmietanę, posól, popieprz i gotuj 3 minuty, aż sos zgęstnieje.',
      'Kopytka wrzucaj partiami do osolonego wrzątku i gotuj 2 minuty od wypłynięcia. Wyjmuj łyżką cedzakową.',
      'Podawaj kopytka polane sosem pieczarkowym i posypane posiekaną natką.',
    ],
    photo:
      'Diamond-shaped potato dumplings covered with a creamy mushroom sauce with sliced mushrooms, sprinkled with chopped parsley',
  },
  {
    plan: 'ob-27',
    title: 'Kluski śląskie z gulaszem wołowym',
    description:
      'Miękkie kluski z charakterystycznym dołeczkiem podane z długo duszonym gulaszem wołowym w gęstym, paprykowym sosie. Śląski obiad niedzielny w wersji na dwie osoby.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 130,
    servings: 2,
    ingredients: [
      ['gulasz wołowy', 350, 'g'],
      ['cebula', 150, 'g'],
      ['marchew', 80, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['papryka słodka mielona', 4, 'g'],
      ['mąka pszenna', 15, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['ziemniak', 500, 'g'],
      ['mąka ziemniaczana', 125, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Mięso pokrój w kostkę 2,5 cm, obtocz w mące pszennej i obsmaż partiami na rozgrzanym oleju na brązowo.',
      'Dodaj posiekaną cebulę i startą marchew, smaż 5 minut. Wmieszaj paprykę i koncentrat, wlej 500 ml gorącej wody, dodaj liść laurowy, ziele, 2 g soli i pieprz.',
      'Duś pod przykryciem na małym ogniu 90 minut, aż wołowina będzie miękka, a sos gęsty. Dolewaj wody, jeśli za bardzo odparuje.',
      'W tym czasie ugotuj obrane ziemniaki w osolonej wodzie (20 minut), przeciśnij przez praskę i ostudź. Wyrównaj masę w misce, odejmij ćwiartkę, w to miejsce wsyp mąkę ziemniaczaną i zagnieć gładkie ciasto.',
      'Formuj kulki wielkości orzecha włoskiego, spłaszcz i zrób kciukiem dołek. Gotuj partiami w osolonym wrzątku 2–3 minuty od wypłynięcia.',
      'Podawaj kluski polane gulaszem — sos zbiera się w dołeczkach.',
    ],
    photo:
      'Round Silesian potato dumplings with a thumbprint dimple, served with chunks of beef goulash in thick glossy paprika gravy',
  },
  {
    plan: 'ob-28',
    title: 'Łazanki z kapustą kiszoną i kiełbasą',
    description:
      'Kwadratowe łazanki wymieszane z duszoną kiszoną kapustą, podsmażoną kiełbasą i cebulką, doprawione kminkiem. Proste, tanie i bardzo sycące danie jednogarnkowe.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['makaron łazanki', 180, 'g'],
      ['kapusta kiszona', 300, 'g'],
      ['kiełbasa wędzona', 150, 'g'],
      ['cebula', 150, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kminek', 1, 'g'],
      ['majeranek', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
    ],
    steps: [
      'Kapustę odciśnij i posiekaj. Zalej 200 ml wody, dodaj kminek i duś pod przykryciem 25 minut, aż zmięknie i woda prawie odparuje.',
      'Kiełbasę pokrój w kostkę, cebulę w piórka. Podsmaż je na oleju przez 8 minut, aż się zrumienią.',
      'Łazanki ugotuj w osolonej wodzie al dente według opakowania i odcedź.',
      'Połącz kapustę z kiełbasą i cebulą, dodaj makaron i smaż razem 3–4 minuty, mieszając.',
      'Dopraw majerankiem i pieprzem — soli zwykle nie trzeba.',
      'Podawaj gorące, posypane posiekaną natką.',
    ],
    photo:
      'Square pasta pieces tossed with golden braised sauerkraut, browned sausage cubes and onion, sprinkled with parsley',
  },
  {
    plan: 'ob-29',
    title: 'Gzik z ziemniakami',
    description:
      'Wielkopolski twarożek ze śmietaną, rzodkiewką, szczypiorkiem i cebulką, podany z gorącymi ziemniakami w mundurkach. Chłodny, kremowy i lekki obiad na ciepłe dni.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['ser twaróg półtłusty', 400, 'g'],
      ['śmietana 18', 100, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['szczypiorek', 20, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['masło', 15, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki dokładnie wyszoruj szczoteczką i ugotuj w mundurkach w osolonej wodzie przez 25 minut, aż nóż wejdzie gładko.',
      'Twaróg rozgnieć widelcem ze śmietaną na gęstą, kremową masę.',
      'Rzodkiewkę pokrój w drobną kostkę, cebulę posiekaj bardzo drobno, szczypiorek pokrój.',
      'Wmieszaj warzywa do twarogu, dopraw solą i pieprzem i odstaw do lodówki do czasu podania.',
      'Ziemniaki odcedź, przekrój na pół i posmaruj masłem, posyp koperkiem.',
      'Podawaj gorące ziemniaki z dużą porcją zimnego gziku.',
    ],
    photo:
      'Boiled jacket potatoes halved with melting butter and dill next to a generous mound of white quark spread with diced radish and chives',
  },
  {
    plan: 'ob-30',
    title: 'Krokiety z kapustą i grzybami',
    description:
      'Cienkie naleśniki zwinięte z farszem z kiszonej kapusty, pieczarek i suszonych grzybów, panierowane i usmażone na złoto. Świąteczny smak na zwykły dzień, także do zamrożenia.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 150, 'g'],
      ['mleko', 250, 'ml'],
      ['jajko', 3, 'szt'],
      ['kapusta kiszona', 350, 'g'],
      ['grzyb suszony', 15, 'g'],
      ['pieczarka', 200, 'g'],
      ['cebula', 100, 'g'],
      ['bułka tarta', 60, 'g'],
      ['olej rzepakowy', 50, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby zalej 150 ml wrzątku na 20 minut. Kapustę odciśnij, posiekaj i gotuj z wodą z grzybów 25 minut, aż zmięknie. Grzyby posiekaj.',
      'Cebulę i pieczarki pokrój drobno i smaż na 10 ml oleju 10 minut. Dodaj kapustę i grzyby, smaż, aż farsz będzie suchy. Dopraw pieprzem i ostudź.',
      'Zmiksuj mąkę, mleko, 2 jajka, 100 ml wody i szczyptę soli na gładkie ciasto. Usmaż 6–8 cienkich naleśników na patelni przetartej olejem, tylko z jednej strony do ścięcia.',
      'Na usmażonej stronie każdego naleśnika połóż 2 łyżki farszu, zwiń boki do środka i zroluj ciasno jak krokiet.',
      'Obtocz krokiety w roztrzepanym ostatnim jajku, a potem w bułce tartej. Smaż na reszcie oleju na średnim ogniu po 3 minuty z każdej strony, aż będą złote i chrupiące.',
      'Podawaj od razu, po 3–4 krokiety na porcję.',
    ],
    photo:
      'Golden breaded pancake croquettes, one cut open to show a dark sauerkraut and mushroom filling',
  },
  {
    plan: 'ob-31',
    title: 'Spaghetti carbonara',
    description:
      'Makaron w kremowym sosie z żółtek i parmezanu z chrupiącym boczkiem i dużą ilością czarnego pieprzu — bez śmietany. Gotowe w 20 minut, a smakuje jak we włoskiej trattorii.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['makaron spaghetti', 200, 'g'],
      ['boczek', 100, 'g'],
      ['jajko', 3, 'szt'],
      ['ser parmezan', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['pieprz czarny', 2, 'g'],
      ['sól', 3, 'g'],
    ],
    steps: [
      'Zagotuj 2 l wody z solą i ugotuj spaghetti al dente według opakowania. Przed odcedzeniem odlej 100 ml wody z gotowania.',
      'Boczek pokrój w paski 0,5 cm i wytop na suchej patelni z lekko zgniecionym ząbkiem czosnku na średnim ogniu przez 6–8 minut, aż będzie chrupiący. Wyjmij czosnek.',
      'W misce wymieszaj 1 całe jajko i 2 żółtka z drobno startym parmezanem (odłóż łyżkę do posypania) i dużą ilością świeżo mielonego pieprzu.',
      'Zdejmij patelnię z ognia, wrzuć odcedzony makaron i wymieszaj z boczkiem i tłuszczem.',
      'Odczekaj 30 sekund, wlej masę jajeczną i energicznie mieszaj, dolewając po łyżce wody z makaronu, aż powstanie gładki, kremowy sos — jajka nie mogą się ściąć.',
      'Podawaj od razu, posypane resztą parmezanu i pieprzem.',
    ],
    photo:
      'Glossy spaghetti carbonara coated in a creamy yellow egg and cheese sauce with crispy bacon pieces, grated parmesan and cracked black pepper',
  },
  {
    plan: 'ob-32',
    title: 'Spaghetti aglio e olio z natką i parmezanem',
    description:
      'Makaron z oliwą, złocistym czosnkiem i płatkami chili, wykończony świeżą natką i parmezanem. Danie z kilku składników, które zawsze masz w domu — gotowe w kwadrans.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['makaron spaghetti', 200, 'g'],
      ['oliwa z oliwek', 45, 'ml'],
      ['czosnek', 5, 'szt'],
      ['płatki chili', 1, 'g'],
      ['natka pietruszki', 20, 'g'],
      ['ser parmezan', 40, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj spaghetti w osolonej wodzie al dente według opakowania. Odlej 100 ml wody z gotowania.',
      'Czosnek pokrój w cienkie plasterki, natkę posiekaj drobno.',
      'Na patelnię wlej oliwę, wrzuć czosnek i płatki chili i podgrzewaj na małym ogniu 3–4 minuty, aż czosnek będzie jasnozłoty — nie dopuść, by się przypalił, bo zgorzknieje.',
      'Przełóż odcedzony makaron na patelnię, dolej 50 ml wody z gotowania i mieszaj minutę, aż oliwa zemulguje w lekki sos.',
      'Wmieszaj natkę i dopraw pieprzem.',
      'Podawaj od razu, posypane startym parmezanem.',
    ],
    photo:
      'Spaghetti glistening with olive oil, golden garlic slices, red chili flakes and plenty of chopped parsley, topped with grated parmesan',
  },
  {
    plan: 'ob-33',
    title: 'Tagliatelle z kurczakiem i suszonymi pomidorami',
    description:
      'Wstążki makaronu w kremowym sosie śmietanowym z kawałkami kurczaka, suszonymi pomidorami i szpinakiem. Szybki makaron na obiad w 30 minut, który dobrze znosi odgrzewanie.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['makaron tagliatelle', 180, 'g'],
      ['filet z kurczaka', 300, 'g'],
      ['pomidor suszony w oleju', 60, 'g'],
      ['śmietanka 18', 150, 'ml'],
      ['czosnek', 2, 'szt'],
      ['szpinak', 60, 'g'],
      ['ser parmezan', 20, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filet pokrój w paski 1 cm, dopraw solą, pieprzem i oregano. Suszone pomidory odsącz i pokrój w paski, czosnek posiekaj.',
      'Ugotuj makaron w osolonej wodzie al dente według opakowania.',
      'Na rozgrzanej oliwie smaż kurczaka 5–6 minut, aż się zrumieni i będzie upieczony w środku.',
      'Dodaj czosnek i pomidory, smaż minutę. Wlej śmietankę i gotuj 2–3 minuty, aż sos lekko zgęstnieje, a potem wrzuć szpinak, by zwiądł.',
      'Dodaj odcedzony makaron i połowę startego parmezanu, wymieszaj. Jeśli sos jest za gęsty, rozrzedź go łyżką wody z makaronu.',
      'Podawaj posypane resztą parmezanu i świeżo mielonym pieprzem.',
    ],
    photo:
      'Tagliatelle ribbons in a creamy sauce with golden chicken strips, deep red sun-dried tomatoes and wilted spinach, dusted with parmesan',
  },
  {
    plan: 'ob-34',
    title: 'Lasagne bolognese',
    description:
      'Warstwy makaronu przełożone mięsnym sosem bolognese i beszamelem, zapieczone z mozzarellą i parmezanem na złotą skórkę. Robi się ją chwilę, ale to obiad, na który się czeka.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 2,
    ingredients: [
      ['makaron lasagne', 120, 'g'],
      ['wieprzowina i wołowina mielona', 220, 'g'],
      ['cebula', 80, 'g'],
      ['marchew', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 400, 'ml'],
      ['oliwa z oliwek', 5, 'ml'],
      ['oregano', 2, 'g'],
      ['masło', 20, 'g'],
      ['mąka pszenna', 25, 'g'],
      ['mleko', 300, 'ml'],
      ['gałka muszkatołowa', 1, 'g'],
      ['mozzarella', 50, 'g'],
      ['ser parmezan', 20, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę, marchew i czosnek posiekaj drobno i podsmaż na oliwie 5 minut. Dodaj mięso i smaż, rozbijając grudki, aż straci różowy kolor.',
      'Wlej passatę, dodaj oregano, 2 g soli i pieprz i duś na małym ogniu 25 minut, aż sos zgęstnieje.',
      'Beszamel: roztop masło, wsyp mąkę i smaż minutę. Stopniowo wlewaj zimne mleko, cały czas mieszając trzepaczką, i gotuj 3–4 minuty do zgęstnienia. Dopraw gałką muszkatołową i solą.',
      'Nagrzej piekarnik do 190°C (góra–dół). W małym naczyniu (ok. 20 × 15 cm) układaj warstwy: odrobina sosu, płaty makaronu, sos mięsny, beszamel — powtórz 3 razy, kończąc beszamelem.',
      'Posyp porwaną mozzarellą i startym parmezanem. Piecz 35–40 minut, aż makaron będzie miękki, a wierzch złoty i bąbelkujący.',
      'Odstaw na 10 minut, żeby warstwy się związały, pokrój na 2 porcje i podawaj.',
    ],
    photo:
      'A generous square of layered lasagne with visible meat ragu and white béchamel, bubbling golden mozzarella crust on top',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
