/**
 * Katalog 500 — Obiady, pozycje ob-35 … ob-68 z `prisma/catalog/katalog-500-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'ob-35',
    title: 'Makaron z pesto, indykiem i pomidorkami',
    description:
      'Penne w zielonym pesto bazyliowym z podsmażonymi kawałkami indyka i pomidorkami koktajlowymi, które lekko puszczają sok. Obiad w 25 minut, równie dobry na ciepło, jak następnego dnia z pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['makaron penne', 160, 'g'],
      ['filet z indyka', 300, 'g'],
      ['pesto bazyliowe', 60, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['ser parmezan', 20, 'g'],
      ['bazylia', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj penne al dente w osolonej wodzie (ok. 10 minut), przed odcedzeniem odlej pół szklanki wody z gotowania.',
      'Pokrój filet z indyka w kostkę 2 cm, dopraw solą i pieprzem. Smaż na rozgrzanej oliwie 6–7 minut, aż mięso będzie złote i nie będzie różowe w środku.',
      'Dodaj posiekany czosnek i przekrojone na pół pomidorki koktajlowe, smaż 2 minuty, aż zaczną mięknąć.',
      'Wrzuć odcedzony makaron, dodaj pesto i 3–4 łyżki wody z gotowania, wymieszaj na małym ogniu, aż sos oblepi makaron.',
      'Podawaj od razu, posypane startym parmezanem i listkami bazylii.',
    ],
    photo:
      'Penne pasta coated in green basil pesto with golden turkey cubes and blistered halved cherry tomatoes, topped with grated parmesan and fresh basil leaves',
    vessel: 'bowl',
  },
  {
    plan: 'ob-36',
    title: 'Mac and cheese z zapieczoną kruszonką',
    description:
      'Kolanka zapieczone w gęstym sosie serowym z cheddara na maśle i mleku, pod chrupiącą warstwą bułki tartej. Sycące, kremowe danie, które dzieci jedzą bez namawiania.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['makaron kolanka', 160, 'g'],
      ['ser cheddar', 130, 'g'],
      ['mleko', 350, 'ml'],
      ['masło', 25, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['musztarda', 5, 'g'],
      ['bułka tarta', 15, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Ugotuj kolanka w osolonej wodzie 2 minuty krócej, niż podaje opakowanie, i odcedź.',
      'W garnku roztop 20 g masła, wsyp mąkę i smaż, mieszając, przez minutę. Wlewaj stopniowo mleko, cały czas mieszając trzepaczką, i gotuj 3–4 minuty, aż sos zgęstnieje.',
      'Zdejmij z ognia, wmieszaj 100 g startego cheddara, musztardę, gałkę muszkatołową, sól i pieprz; mieszaj, aż ser się roztopi.',
      'Połącz sos z makaronem i przełóż do żaroodpornego naczynia. Posyp resztą cheddara, bułką tartą wymieszaną z pozostałym roztopionym masłem i papryką.',
      'Zapiekaj 15 minut, aż wierzch się zrumieni, a sos zacznie bulgotać przy brzegach.',
      'Odstaw na 5 minut, żeby sos się ustabilizował, i podawaj prosto z naczynia.',
    ],
    photo:
      'Baked macaroni and cheese in a dish with bubbling orange cheddar sauce and a golden crunchy breadcrumb crust, a portion scooped out showing creamy elbows',
  },
  {
    plan: 'ob-37',
    title: 'Gnocchi w sosie pomidorowym z mozzarellą',
    description:
      'Miękkie kluseczki ziemniaczane w gęstym sosie z passaty z czosnkiem i bazylią, zapieczone pod roztopioną mozzarellą. Obiad niemal bez krojenia, gotowy w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['gnocchi', 450, 'g'],
      ['passata pomidorowa', 400, 'ml'],
      ['mozzarella', 125, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['oregano', 1, 'g'],
      ['cukier', 3, 'g'],
      ['bazylia', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C z termoobiegiem. Cebulę posiekaj w drobną kostkę, czosnek przeciśnij.',
      'Na oliwie w żaroodpornej patelni zeszklij cebulę (4 minuty), dodaj czosnek i smaż jeszcze pół minuty.',
      'Wlej passatę, dodaj oregano, cukier, sól i pieprz, gotuj na małym ogniu 8 minut, aż sos zgęstnieje.',
      'Wrzuć gnocchi prosto z opakowania, wymieszaj i duś 3 minuty, aż zmiękną w sosie.',
      'Rozłóż na wierzchu porwaną mozzarellę i zapiekaj 7–8 minut, aż ser się roztopi i zacznie rumienić.',
      'Podawaj posypane listkami świeżej bazylii.',
    ],
    photo:
      'Potato gnocchi in thick red tomato sauce under melted browned mozzarella patches in a skillet, scattered with fresh basil leaves',
  },
  {
    plan: 'ob-38',
    title: 'Makaron ryżowy z kurczakiem i orzeszkami',
    description:
      'Szybki makaron z woka: szerokie wstążki ryżowe, chrupiące warzywa i kurczak w sosie sojowo-miodowym z limonką, posypane prażonymi orzeszkami. Słodko, słono i lekko kwaśno.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['makaron ryżowy', 140, 'g'],
      ['filet z kurczaka', 300, 'g'],
      ['orzeszek ziemny', 40, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['marchew', 100, 'g'],
      ['cebula dymka', 40, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos sojowy', 30, 'ml'],
      ['miód', 15, 'g'],
      ['limonka', 30, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['płatki chili', 1, 'g'],
    ],
    steps: [
      'Makaron zalej wrzątkiem i odstaw na czas podany na opakowaniu (zwykle 5–8 minut), potem odcedź i przelej zimną wodą.',
      'Wymieszaj sos sojowy, miód, sok z limonki i płatki chili. Kurczaka pokrój w cienkie paski, paprykę w słupki, marchew w cienkie zapałki, dymkę w ukośne kawałki; czosnek i imbir posiekaj.',
      'Orzeszki upraż na suchej patelni 3 minuty, aż się zezłocą, i grubo posiekaj.',
      'Na mocno rozgrzanym oleju smaż kurczaka 4–5 minut, aż się zrumieni. Dodaj czosnek, imbir, paprykę i marchew, smaż 3 minuty — warzywa mają zostać chrupkie.',
      'Wrzuć makaron i wlej sos, mieszaj 1–2 minuty, aż makaron go wchłonie.',
      'Podawaj posypane orzeszkami i dymką, z ćwiartką limonki.',
    ],
    photo:
      'Stir-fried flat rice noodles with chicken strips, red pepper and carrot matchsticks, topped with chopped roasted peanuts, sliced spring onion and a lime wedge',
    vessel: 'bowl',
  },
  {
    plan: 'ob-39',
    title: 'Kurczak słodko-kwaśny z ananasem i ryżem',
    description:
      'Chrupiące kawałki kurczaka w lekkiej panierce, obtoczone błyszczącym sosem z ananasa, papryki i octu. Domowa wersja dania z chińskiego baru, bez gotowego sosu ze słoika.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka ziemniaczana', 35, 'g'],
      ['ananas z puszki', 150, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['papryka zielona', 100, 'g'],
      ['cebula', 80, 'g'],
      ['ketchup', 40, 'g'],
      ['ocet jabłkowy', 20, 'ml'],
      ['cukier brązowy', 15, 'g'],
      ['sos sojowy', 15, 'ml'],
      ['olej rzepakowy', 30, 'ml'],
      ['ryż jaśminowy', 140, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ugotuj ryż w osolonej wodzie według opakowania (ok. 12 minut).',
      'Kurczaka pokrój w kostkę 2–3 cm, obtocz w roztrzepanym jajku, a potem w 25 g mąki ziemniaczanej.',
      'Smaż kurczaka partiami na 25 ml gorącego oleju 5–6 minut, aż będzie złoty i chrupiący; odłóż na ręcznik papierowy.',
      'Wymieszaj ketchup, ocet, cukier, sos sojowy, 100 ml soku z puszki ananasa i resztę mąki ziemniaczanej.',
      'Na pozostałym oleju smaż cebulę i paprykę pokrojone w kostkę 2 minuty, dodaj kawałki ananasa i wlej sos. Gotuj, mieszając, aż zgęstnieje i zrobi się szklisty (ok. 1 minuty).',
      'Wrzuć kurczaka, szybko wymieszaj i od razu podawaj z ryżem, zanim panierka zmięknie.',
    ],
    photo:
      'Crispy chicken pieces glazed in glossy orange sweet and sour sauce with pineapple chunks, red and green pepper, served next to a mound of white jasmine rice',
  },
  {
    plan: 'ob-40',
    title: 'Gyros z kurczaka z frytkami i sosem czosnkowym',
    description:
      'Paski kurczaka mocno doprawione przyprawą do gyrosa, pieczone frytki i gęsty sos czosnkowy na jogurcie greckim, do tego pomidor i ogórek. Domowy talerz jak z budki, tylko lżejszy.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['przyprawa do gyrosa', 8, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['frytka mrożona', 300, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['ogórek', 150, 'g'],
      ['pomidor', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w cienkie paski, wymieszaj z przyprawą do gyrosa i 10 ml oleju, odstaw na 15 minut.',
      'Nagrzej piekarnik do 220°C z termoobiegiem, rozłóż frytki na blasze w jednej warstwie i piecz 20–25 minut, przewracając w połowie, aż będą złote.',
      'Sos: wymieszaj jogurt z przeciśniętym czosnkiem, posiekanym koperkiem, 50 g startego ogórka (odciśniętego z soku), solą i pieprzem.',
      'Resztę ogórka pokrój w półplasterki, pomidora w ósemki, cebulę w cienkie piórka.',
      'Smaż kurczaka na pozostałym oleju na mocnym ogniu 6–7 minut, aż brzegi się przypieką.',
      'Ułóż na talerzach frytki i gyros, obok warzywa, i polej wszystko sosem czosnkowym.',
    ],
    photo:
      'Spiced gyros chicken strips with golden fries, sliced tomato, cucumber and red onion, drizzled with thick white garlic yogurt sauce sprinkled with dill',
  },
  {
    plan: 'ob-41',
    title: 'Kurczak w miodzie i musztardzie z pieczonymi ziemniakami',
    description:
      'Udka pieczone w glazurze z miodu, musztardy i czosnku, obok ćwiartki ziemniaków z rozmarynem z tej samej blachy. Skórka wychodzi lepka i chrupiąca, a zmywania prawie nie ma.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['udko z kurczaka', 2, 'szt'],
      ['miód', 25, 'g'],
      ['musztarda', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['ziemniak', 500, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['rozmaryn suszony', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Wymieszaj miód, musztardę, przeciśnięty czosnek, paprykę, 2 g soli i pieprz.',
      'Udka osusz ręcznikiem, natnij skórę w 2–3 miejscach i dokładnie posmaruj połową glazury.',
      'Ziemniaki umyj i pokrój w ćwiartki ze skórką, wymieszaj z oliwą, rozmarynem i resztą soli.',
      'Rozłóż ziemniaki na blasze, na środku ułóż udka skórą do góry i piecz 25 minut.',
      'Posmaruj udka resztą glazury, przewróć ziemniaki i piecz kolejne 20–25 minut, aż skórka będzie ciemnozłota, a sok przy kości przezroczysty.',
      'Podawaj udka z ziemniakami, polane sosem z blachy i posypane posiekaną natką.',
    ],
    photo:
      'Two glossy honey mustard glazed chicken legs with caramelized skin on roasted potato wedges with rosemary, sprinkled with chopped parsley',
  },
  {
    plan: 'ob-42',
    title: 'Kurczak w pomidorach z papryką i ryżem',
    description:
      'Kawałki kurczaka duszone z czerwoną papryką i cebulą w sosie z krojonych pomidorów, lekko podbitym wędzoną papryką. Proste jednogarnkowe danie, idealne do pudełka na dwa dni.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['papryka żółta', 150, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['papryka wędzona mielona', 1, 'g'],
      ['oregano', 1, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['ryż biały', 140, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż w osolonej wodzie według opakowania (ok. 15 minut).',
      'Kurczaka pokrój w kostkę 2–3 cm, oprósz obiema paprykami, solą i pieprzem. Obsmaż na oleju 4 minuty, aż się zrumieni.',
      'Dodaj cebulę w kostce i paprykę w paskach, smaż 4 minuty, pod koniec dorzuć przeciśnięty czosnek.',
      'Wlej pomidory z puszki, dodaj oregano i duś pod przykryciem 12–15 minut, aż papryka zmięknie, a sos zgęstnieje.',
      'Spróbuj i w razie potrzeby dopraw solą i pieprzem.',
      'Podawaj z ryżem, posypane posiekaną natką.',
    ],
    photo:
      'Chicken pieces stewed with red and yellow pepper strips in chunky tomato sauce beside fluffy white rice, garnished with chopped parsley',
  },
  {
    plan: 'ob-43',
    title: 'Gulasz z indyka z pieczarkami i kaszą gryczaną',
    description:
      'Kawałki udźca z indyka duszone z pieczarkami, marchewką i papryką w łagodnym sosie zabielanym śmietaną. Jesienny obiad, który podany z kaszą gryczaną syci na długo.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['udziec z indyka', 400, 'g'],
      ['pieczarka', 250, 'g'],
      ['cebula', 100, 'g'],
      ['marchew', 100, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['śmietana 18', 60, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['majeranek', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['kasza gryczana', 130, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Indyka pokrój w kostkę 3 cm, oprósz mąką, solą i pieprzem. Obsmaż na 15 ml oleju z każdej strony na złoto i przełóż do garnka.',
      'Na reszcie oleju podsmaż cebulę w kostce, a potem pieczarki w ćwiartkach, aż odparują i się zrumienią (ok. 6 minut).',
      'Przełóż warzywa do mięsa, dodaj marchew w plasterkach, paprykę, majeranek i liść laurowy. Wlej wodę do połowy wysokości mięsa i duś pod przykryciem 35 minut, aż indyk będzie miękki.',
      'W tym czasie ugotuj kaszę: wsyp do 260 ml osolonego wrzątku i gotuj pod przykryciem 15 minut na małym ogniu.',
      'Śmietanę zahartuj kilkoma łyżkami gorącego sosu, wlej do gulaszu i zagotuj. Wyjmij liść laurowy.',
      'Podawaj gulasz na kaszy gryczanej.',
    ],
    photo:
      'Turkey stew with browned mushrooms and carrot slices in creamy paprika sauce served over brown buckwheat groats',
  },
  {
    plan: 'ob-44',
    title: 'Sznycle z indyka z ziemniakami i fasolką szparagową',
    description:
      'Cienko rozbite plastry piersi indyka w chrupiącej panierce, do tego młode ziemniaki z koperkiem i fasolka z masłem i bułką tartą. Klasyczny niedzielny talerz w lżejszym wydaniu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 20, 'g'],
      ['bułka tarta', 50, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['ziemniak', 500, 'g'],
      ['fasolka szparagowa', 250, 'g'],
      ['masło', 15, 'g'],
      ['koperek', 5, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki, pokrój na równe kawałki i gotuj w osolonej wodzie 20 minut do miękkości.',
      'Filet pokrój na 4 plastry, rozbij tłuczkiem przez folię na grubość 0,5 cm, dopraw solą i pieprzem.',
      'Panieruj kotlety kolejno w mące, roztrzepanym jajku i bułce tartej (odłóż 5 g bułki do fasolki).',
      'Smaż na rozgrzanym oleju 3 minuty z każdej strony, aż panierka będzie złota; odsącz na ręczniku papierowym.',
      'Fasolkę bez końcówek gotuj w osolonej wodzie 6–7 minut, odcedź i wymieszaj z masłem zrumienionym z odłożoną bułką tartą.',
      'Podawaj sznycle z ćwiartką cytryny, ziemniakami posypanymi koperkiem i fasolką.',
    ],
    photo:
      'Two golden breaded turkey schnitzels with a lemon wedge, boiled potatoes sprinkled with dill and green beans topped with buttery breadcrumbs',
  },
  {
    plan: 'ob-45',
    title: 'Roladki z indyka ze szpinakiem i fetą z ziemniakami',
    description:
      'Plastry piersi indyka zwinięte z czosnkowym szpinakiem i słoną fetą, obsmażone i dopieczone w piekarniku. Na przekroju wyglądają efektownie, a robi się je bez trudu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['filet z indyka', 350, 'g'],
      ['szpinak', 100, 'g'],
      ['ser feta', 70, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ziemniak', 500, 'g'],
      ['masło', 10, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra–dół). Obierz ziemniaki i nastaw do gotowania w osolonej wodzie na 20 minut.',
      'Na 5 ml oliwy podsmaż posiekany czosnek, dodaj szpinak i mieszaj 1–2 minuty, aż zwiędnie. Odciśnij z wody i wymieszaj z pokruszoną fetą.',
      'Filet przekrój na 4 cienkie płaty, rozbij przez folię na grubość 0,5 cm, dopraw solą, pieprzem i papryką.',
      'Rozłóż farsz na płatach, zwiń ciasno i spnij wykałaczkami.',
      'Obsmaż roladki na reszcie oliwy z każdej strony po 2 minuty, przełóż do naczynia z pomidorkami i piecz 15 minut, aż indyk będzie jędrny, a sok przezroczysty.',
      'Wyjmij wykałaczki, pokrój roladki ukośnie na pół i podawaj z ziemniakami z masłem i pieczonymi pomidorkami.',
    ],
    photo:
      'Turkey roulades cut in half showing a green spinach and white feta filling, with boiled buttered potatoes and roasted cherry tomatoes',
  },
  {
    plan: 'ob-46',
    title: 'Szaszłyki z indyka z warzywami i ryżem',
    description:
      'Kawałki indyka marynowane w czosnku i papryce, nabite na patyczki na zmianę z papryką, cukinią i czerwoną cebulą, pieczone w piekarniku albo na grillu. Do tego sypki ryż i jogurtowy sos.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['filet z indyka', 350, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cukinia', 150, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 3, 'g'],
      ['oregano', 1, 'g'],
      ['cytryna', 20, 'g'],
      ['ryż basmati', 140, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Indyka pokrój w kostkę 3 cm i wymieszaj z oliwą, 1 przeciśniętym ząbkiem czosnku, papryką, oregano, sokiem z cytryny, solą i pieprzem. Odstaw na 20 minut.',
      'Paprykę pokrój w kwadraty 3 cm, cukinię w półplastry 1 cm, cebulę w ósemki.',
      'Nabijaj na patyczki na przemian mięso i warzywa. Nagrzej piekarnik do 220°C z funkcją grilla.',
      'Piecz szaszłyki na kratce nad blachą 18–20 minut, obracając w połowie, aż mięso będzie przypieczone na brzegach.',
      'W tym czasie ugotuj ryż według opakowania, a jogurt wymieszaj z drugim przeciśniętym ząbkiem czosnku i szczyptą soli.',
      'Podawaj szaszłyki na ryżu, polane sosem jogurtowym.',
    ],
    photo:
      'Turkey skewers with charred red pepper, zucchini and red onion pieces laid on white basmati rice with a small bowl of garlic yogurt sauce',
  },
  {
    plan: 'ob-47',
    title: 'Strogonow wołowy z kaszą gryczaną',
    description:
      'Cienkie paski wołowiny z pieczarkami i ogórkiem kiszonym w śmietanowym sosie z musztardą i papryką. Polska wersja klasyka — lekko kwaskowa, idealna do kaszy gryczanej.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['wołowina', 350, 'g'],
      ['pieczarka', 200, 'g'],
      ['cebula', 100, 'g'],
      ['ogórek kiszony', 100, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['musztarda', 10, 'g'],
      ['śmietana 18', 100, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['kasza gryczana', 130, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wołowinę pokrój w poprzek włókien w paski 1 × 5 cm, oprósz mąką, solą i pieprzem. Smaż partiami na gorącym oleju po 2 minuty, aż się zrumieni, i odłóż.',
      'Na tej samej patelni zeszklij cebulę w piórkach, dodaj pokrojone w plasterki pieczarki i smaż 6 minut, aż odparują.',
      'Dodaj koncentrat, paprykę i 200 ml wody, wróć mięso i duś pod przykryciem 20 minut, aż wołowina zmięknie.',
      'W tym czasie ugotuj kaszę w 260 ml osolonej wody pod przykryciem (15 minut).',
      'Wmieszaj do sosu ogórki pokrojone w słupki, musztardę i śmietanę, podgrzej, nie gotując.',
      'Podawaj strogonow na kaszy, posypany natką.',
    ],
    photo:
      'Beef stroganoff strips with sliced mushrooms and pickled cucumber in creamy pinkish sauce over buckwheat groats, sprinkled with chopped parsley',
  },
  {
    plan: 'ob-48',
    title: 'Ryba po grecku z ziemniakami',
    description:
      'Smażone kawałki dorsza pod gęstą warstwą duszonej marchewki, pietruszki i selera w pomidorowym sosie z zielem angielskim. Na ciepło z ziemniakami to pełny obiad, a na zimno jest jeszcze lepsza.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['dorsz', 350, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['olej rzepakowy', 35, 'ml'],
      ['marchew', 200, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['seler korzeniowy', 80, 'g'],
      ['cebula', 100, 'g'],
      ['koncentrat pomidorowy', 50, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['cukier', 3, 'g'],
      ['ziemniak', 400, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Marchew, pietruszkę i seler zetrzyj na tarce o dużych oczkach, cebulę pokrój w cienkie piórka.',
      'Na 15 ml oleju zeszklij cebulę, dodaj starte warzywa, ziele angielskie, liść laurowy i 100 ml wody. Duś pod przykryciem 15 minut, aż zmiękną.',
      'Wmieszaj koncentrat, cukier, sól i pieprz, duś jeszcze 5 minut bez przykrycia; sos ma być gęsty i słodko-kwaśny.',
      'Nastaw obrane ziemniaki do gotowania w osolonej wodzie (20 minut).',
      'Dorsza pokrój na 4 kawałki, osusz, dopraw solą i pieprzem, obtocz w mące i smaż na reszcie oleju po 3 minuty z każdej strony na złoto.',
      'Ułóż rybę na talerzach, przykryj warstwą warzyw w pomidorach (bez liścia laurowego) i podawaj z ziemniakami.',
    ],
    photo:
      'Fried cod pieces covered with a thick layer of shredded carrot, parsley root and celery in orange tomato sauce, served with boiled potatoes',
  },
  {
    plan: 'ob-49',
    title: 'Domowe paluszki rybne z frytkami',
    description:
      'Paski dorsza w chrupiącej panierce z bułki tartej, pieczone frytki i szybki sos tatarski na jogurcie z ogórkiem kiszonym. Wersja, którą chętnie zjedzą też dzieci, a ryba jest w niej prawdziwa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['dorsz', 350, 'g'],
      ['mąka pszenna', 25, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 60, 'g'],
      ['olej rzepakowy', 35, 'ml'],
      ['frytka mrożona', 300, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['majonez', 20, 'g'],
      ['ogórek kiszony', 60, 'g'],
      ['koperek', 5, 'g'],
      ['cytryna', 30, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C z termoobiegiem i piecz frytki rozłożone w jednej warstwie 20–25 minut, przewracając w połowie.',
      'Dorsza osusz i pokrój w paski 2 × 8 cm, dopraw solą, pieprzem i odrobiną soku z cytryny.',
      'Obtaczaj paski w mące, roztrzepanym jajku i bułce tartej, dociskając panierkę dłonią.',
      'Smaż na rozgrzanym oleju po 2 minuty z każdej strony, aż będą złote; odsącz na ręczniku papierowym.',
      'Sos: wymieszaj jogurt, majonez, drobno posiekany ogórek kiszony i koperek, dopraw pieprzem.',
      'Podawaj paluszki z frytkami, sosem tatarskim i cząstką cytryny.',
    ],
    photo:
      'Golden breaded homemade fish fingers with oven fries, a small bowl of creamy tartar sauce with pickles and dill, and a lemon wedge',
  },
  {
    plan: 'ob-50',
    title: 'Pstrąg pieczony z koperkiem i ziemniakami',
    description:
      'Cały pstrąg upieczony z plastrami cytryny, czosnkiem i koperkiem w środku, z delikatnym, soczystym mięsem odchodzącym od ości. Obok ziemniaki pieczone na tej samej blasze.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['pstrąg', 2, 'szt'],
      ['cytryna', 60, 'g'],
      ['koperek', 15, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 20, 'g'],
      ['ziemniak', 600, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Ziemniaki pokrój w plastry 1 cm, wymieszaj z oliwą, papryką i połową soli, rozłóż na blasze i piecz 15 minut.',
      'Pstrągi opłucz, osusz, natnij skórę 3 razy z każdej strony. Natrzyj w środku i na zewnątrz resztą soli i pieprzem.',
      'Do brzucha każdej ryby włóż plasterki cytryny, ząbek czosnku w plasterkach, gałązki koperku i kawałek masła.',
      'Przesuń ziemniaki na brzegi, ułóż pstrągi na środku blachy i piecz 20–25 minut, aż oko zbieleje, a mięso łatwo odejdzie od ości.',
      'Podawaj rybę z ziemniakami, polaną sokiem z blachy i posypaną świeżym koperkiem.',
    ],
    photo:
      'Whole roasted trout with crispy scored skin, stuffed with lemon slices and dill, beside golden roasted potato slices on a plate',
  },
  {
    plan: 'ob-51',
    title: 'Kotlety rybne z ziemniakami i surówką z marchewki',
    description:
      'Soczyste kotlety z mielonego mintaja z cebulką, koperkiem i namoczoną bułką, smażone na złoto. Z ziemniakami i surówką z marchewki to tani, domowy obiad rybny na każdy dzień.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['mintaj', 400, 'g'],
      ['bułka', 40, 'g'],
      ['mleko', 50, 'ml'],
      ['jajko', 1, 'szt'],
      ['cebula', 80, 'g'],
      ['koperek', 10, 'g'],
      ['bułka tarta', 30, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['ziemniak', 500, 'g'],
      ['marchew', 200, 'g'],
      ['jabłko', 100, 'g'],
      ['cytryna', 15, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki i gotuj w osolonej wodzie 20 minut. Bułkę namocz w mleku.',
      'Mintaja pokrój i zmiel albo drobno posiekaj nożem. Dodaj odciśniętą bułkę, jajko, drobno startą cebulę, połowę koperku, sól i pieprz; wyrób gładką masę.',
      'Mokrymi dłońmi uformuj 6 kotletów, obtocz je w bułce tartej.',
      'Smaż na rozgrzanym oleju na średnim ogniu 4 minuty z każdej strony, aż będą złote i sprężyste.',
      'Marchew i jabłko zetrzyj na tarce o drobnych oczkach, skrop sokiem z cytryny i posól szczyptą soli.',
      'Podawaj kotlety z ziemniakami posypanymi resztą koperku i surówką.',
    ],
    photo:
      'Golden fried fish patties with boiled potatoes sprinkled with dill and a bright orange grated carrot and apple salad',
  },
  {
    plan: 'ob-52',
    title: 'Zupa grzybowa z łazankami',
    description:
      'Aromatyczny wywar z suszonych grzybów i pieczarek na warzywach korzeniowych, zabielany śmietaną i podany z kwadratowymi łazankami. Smak świątecznej grzybowej na zwykły dzień.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 2,
    ingredients: [
      ['grzyb suszony', 25, 'g'],
      ['pieczarka', 250, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['seler korzeniowy', 60, 'g'],
      ['cebula', 100, 'g'],
      ['masło', 20, 'g'],
      ['śmietana 18', 100, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['makaron łazanki', 120, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Suszone grzyby opłucz i namocz w 300 ml ciepłej wody na co najmniej 30 minut.',
      'Marchew, pietruszkę i seler obierz, zalej 1,2 l wody, dodaj ziele angielskie i liść laurowy, gotuj 20 minut. Dodaj grzyby razem z wodą z moczenia i gotuj kolejne 20 minut.',
      'Wyjmij grzyby i pokrój w paski, warzywa korzeniowe pokrój w kostkę (albo wyjmij). Na maśle zrumień cebulę w kostce i pieczarki w plasterkach (8 minut), przełóż do zupy razem z grzybami i warzywami.',
      'W osobnym garnku ugotuj łazanki w osolonej wodzie al dente i odcedź.',
      'Śmietanę wymieszaj z mąką i kilkoma łyżkami gorącego wywaru, wlej do zupy i zagotuj. Dopraw solą i pieprzem, wyjmij liść laurowy.',
      'Nałóż łazanki do talerzy, zalej gorącą zupą i posyp natką.',
    ],
    photo:
      'Creamy light brown mushroom soup with sliced wild and button mushrooms and square pasta pieces, garnished with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'ob-53',
    title: 'Zupa cebulowa z grzankami serowymi',
    description:
      'Cebula powoli karmelizowana na maśle aż do ciemnego złota, zalana bulionem z tymiankiem i zapieczona pod grzanką z roztopionym serem. Słodkawa, głęboka w smaku i bardzo rozgrzewająca.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 2,
    ingredients: [
      ['cebula', 600, 'g'],
      ['masło', 30, 'g'],
      ['cukier', 5, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['bulion drobiowy', 400, 'ml'],
      ['czosnek', 2, 'szt'],
      ['tymianek suszony', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['bagietka', 100, 'g'],
      ['ser gouda', 100, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę pokrój w cienkie piórka. Roztop masło w szerokim garnku, dodaj cebulę i cukier, smaż na średnio-małym ogniu 35–40 minut, często mieszając, aż będzie miękka i ciemnozłota.',
      'Dodaj posiekany czosnek, oprósz mąką i smaż, mieszając, 1 minutę.',
      'Wlewaj stopniowo bulion i 400 ml wody, dodaj tymianek i liść laurowy, gotuj pod przykryciem 15 minut. Dopraw pieprzem (sól zwykle niepotrzebna — bulion i ser są słone).',
      'Nagrzej piekarnik z funkcją grilla do 230°C. Bagietkę pokrój w kromki 1,5 cm, gęsto posyp startą goudą.',
      'Przelej zupę do żaroodpornych miseczek, połóż na wierzchu grzanki i zapiekaj 4–5 minut, aż ser się roztopi i zarumieni.',
      'Podawaj od razu, uważając na gorące naczynia.',
    ],
    photo:
      'French onion soup in a bowl topped with a baguette slice covered in bubbling browned melted cheese, caramelized onion visible at the edges',
    vessel: 'bowl',
  },
  {
    plan: 'ob-54',
    title: 'Zupa z zielonej soczewicy z kiełbasą',
    description:
      'Gęsta, rozgrzewająca zupa z zielonej soczewicy z warzywami, pomidorami i plastrami podsmażonej wędzonej kiełbasy, doprawiona kminem i majerankiem. Jeszcze lepsza następnego dnia.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 55,
    servings: 2,
    ingredients: [
      ['soczewica zielona', 140, 'g'],
      ['kiełbasa wędzona', 120, 'g'],
      ['cebula', 100, 'g'],
      ['marchew', 120, 'g'],
      ['seler korzeniowy', 60, 'g'],
      ['ziemniak', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['majeranek', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Soczewicę przepłucz na sitku. Kiełbasę pokrój w półplasterki, cebulę, marchew, seler i ziemniaki w kostkę 1 cm.',
      'W garnku podsmaż kiełbasę na oleju 3–4 minuty, aż puści tłuszcz i się zrumieni; połowę odłóż na talerz.',
      'Dodaj cebulę, marchew i seler, smaż 5 minut. Wsyp kmin i przeciśnięty czosnek, smaż pół minuty.',
      'Dodaj soczewicę, ziemniaki, liść laurowy i 1,2 l wody, gotuj pod przykryciem 30 minut, aż soczewica będzie miękka.',
      'Wlej pomidory, dodaj majeranek i odłożoną kiełbasę, gotuj 5 minut. Dopraw solą i pieprzem.',
      'Podawaj posypaną natką, najlepiej z kromką chleba.',
    ],
    photo:
      'Thick green lentil soup with carrot and potato cubes, tomato pieces and browned smoked sausage half-moons, sprinkled with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'ob-55',
    title: 'Kartoflanka z kiełbasą i majerankiem',
    description:
      'Gęsta zupa ziemniaczana na warzywach z porem, podsmażoną kiełbasą i dużą ilością majeranku, lekko zabielona śmietaną. Tania, sycąca i taka jak u babci.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['kiełbasa wędzona', 120, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['seler korzeniowy', 50, 'g'],
      ['por', 80, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 10, 'g'],
      ['śmietana 18', 60, 'g'],
      ['majeranek', 3, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['chleb żytni', 60, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Marchew, pietruszkę i seler obierz i pokrój w kostkę, zalej 1,2 l wody, dodaj ziele angielskie i liść laurowy, gotuj 15 minut.',
      'Ziemniaki obierz, pokrój w kostkę 1,5 cm i dodaj do wywaru, gotuj 15 minut.',
      'W tym czasie na maśle podsmaż kiełbasę w kostce, cebulę i pora w półplastrach (6 minut), na koniec dodaj przeciśnięty czosnek.',
      'Przełóż kiełbasę z warzywami do zupy, wsyp majeranek roztarty w dłoniach i gotuj 5 minut. Część ziemniaków rozgnieć tłuczkiem o ścianki garnka, żeby zupa zgęstniała.',
      'Śmietanę zahartuj kilkoma łyżkami zupy i wlej do garnka. Dopraw solą i pieprzem, wyjmij liść laurowy.',
      'Podawaj z kromką żytniego chleba.',
    ],
    photo:
      'Thick creamy potato soup with sausage cubes, carrot and leek pieces, sprinkled with dried marjoram, with a slice of rye bread on the side',
    vessel: 'bowl',
  },
  {
    plan: 'ob-56',
    title: 'Zupa z pulpetami i ziemniakami',
    description:
      'Klarowna zupa warzywna z małymi, delikatnymi pulpecikami z mięsa mielonego, ziemniakami i dużą ilością koperku. Lekka, a jednocześnie sycąca — ulubiona zupa wielu dzieci.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['wieprzowina i wołowina mielona', 250, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 20, 'g'],
      ['cebula', 80, 'g'],
      ['ziemniak', 300, 'g'],
      ['marchew', 120, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['seler korzeniowy', 50, 'g'],
      ['koperek', 10, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Marchew, pietruszkę i seler obierz i pokrój w kostkę, zalej 1,2 l wody, dodaj ziele angielskie i liść laurowy, gotuj 15 minut.',
      'Mięso wymieszaj z jajkiem, bułką tartą, bardzo drobno posiekaną cebulą, 2 g soli i pieprzem. Mokrymi dłońmi uformuj pulpeciki wielkości orzecha włoskiego.',
      'Dodaj do zupy ziemniaki w kostce 1,5 cm i gotuj 5 minut.',
      'Wkładaj pulpety pojedynczo do gotującej się zupy i gotuj na małym ogniu 15 minut, aż wypłyną i będą ścięte w środku. Zbieraj szumowiny łyżką.',
      'Dopraw solą i pieprzem, wyjmij liść laurowy i wsyp posiekany koperek.',
      'Podawaj gorącą, z kilkoma pulpetami w każdym talerzu.',
    ],
    photo:
      'Clear golden vegetable soup with small meatballs, potato and carrot cubes, generously sprinkled with fresh chopped dill',
    vessel: 'bowl',
  },
  {
    plan: 'ob-57',
    title: 'Zupa z indykiem i kaszą jaglaną',
    description:
      'Lekka, a treściwa zupa na udźcu z indyka z warzywami korzeniowymi i kaszą jaglaną, która lekko ją zagęszcza. Delikatna w smaku, dobra na chłodne dni i na lekki żołądek.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['udziec z indyka', 350, 'g'],
      ['kasza jaglana', 70, 'g'],
      ['marchew', 150, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['seler korzeniowy', 60, 'g'],
      ['por', 80, 'g'],
      ['ziemniak', 200, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Indyka pokrój w kostkę 2 cm, zalej 1,3 l zimnej wody, zagotuj i zbierz szumowiny. Dodaj ziele angielskie i liść laurowy, gotuj na małym ogniu 25 minut.',
      'Marchew, pietruszkę i seler pokrój w kostkę 1 cm, por w półplastry, ziemniaki w kostkę 1,5 cm.',
      'Kaszę jaglaną przepłucz na sitku gorącą wodą, żeby nie była gorzka.',
      'Dodaj warzywa, ziemniaki i kaszę do zupy, gotuj 20 minut, aż kasza i warzywa będą miękkie.',
      'Dopraw solą i pieprzem, wyjmij liść laurowy.',
      'Podawaj posypaną świeżo posiekaną natką.',
    ],
    photo:
      'Light golden turkey soup with turkey cubes, diced carrot, leek and yellow millet grains, generously sprinkled with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'ob-58',
    title: 'Zupa meksykańska z mięsem mielonym',
    description:
      'Gęsta, lekko pikantna zupa z mielonej wołowiny, czerwonej fasoli, kukurydzy i papryki w pomidorowym wywarze z kminem. Pełnowartościowy obiad w jednym garnku, dobry na imprezę.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['wołowina mielona', 250, 'g'],
      ['fasola czerwona z puszki', 200, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['oregano', 1, 'g'],
      ['śmietana 18', 40, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę i paprykę pokrój w kostkę 1 cm, czosnek przeciśnij. Fasolę i kukurydzę odcedź i przepłucz.',
      'W garnku rozgrzej olej i smaż mięso 6–7 minut, rozbijając je łopatką, aż będzie brązowe i sypkie.',
      'Dodaj cebulę i paprykę, smaż 4 minuty. Wsyp kmin, obie papryki, oregano i czosnek, smaż pół minuty, dodaj koncentrat.',
      'Wlej pomidory i 700 ml wody, gotuj pod przykryciem 15 minut.',
      'Dodaj fasolę i kukurydzę, gotuj jeszcze 5 minut. Dopraw solą i pieprzem.',
      'Podawaj z łyżką śmietany na wierzchu.',
    ],
    photo:
      'Hearty red Mexican soup with ground beef, kidney beans, sweet corn and pepper pieces, topped with a dollop of sour cream',
    vessel: 'bowl',
  },
  {
    plan: 'ob-59',
    title: 'Zupa tajska z kurczakiem i mleczkiem kokosowym',
    description:
      'Kremowy, lekko pikantny bulion z mleczkiem kokosowym, curry, imbirem i chili, z kurczakiem, pieczarkami i makaronem ryżowym. Świeżość dodają limonka, kolendra i dymka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['mleko kokosowe z puszki', 200, 'ml'],
      ['curry', 6, 'g'],
      ['papryczka chili', 15, 'g'],
      ['bulion drobiowy', 500, 'ml'],
      ['makaron ryżowy', 80, 'g'],
      ['pieczarka', 150, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['sos sojowy', 15, 'ml'],
      ['limonka', 30, 'g'],
      ['cukier brązowy', 5, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['cebula dymka', 30, 'g'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w cienkie paski, pieczarki w plasterki, paprykę w paski; imbir, czosnek i papryczkę chili (bez pestek, jeśli wolisz łagodniej) drobno posiekaj.',
      'W garnku na oleju smaż czosnek, imbir i chili 1 minutę, wsyp curry i smaż jeszcze pół minuty, aż zacznie pachnieć.',
      'Wlej bulion, 300 ml wody i mleczko kokosowe, zagotuj. Dodaj kurczaka, pieczarki i paprykę, gotuj na małym ogniu 8 minut.',
      'Makaron zalej wrzątkiem w osobnej misce na czas z opakowania i odcedź.',
      'Dopraw zupę sosem sojowym, cukrem i sokiem z limonki; smak ma być słony, lekko słodki i kwaśny.',
      'Rozłóż makaron do misek, zalej zupą i posyp dymką oraz listkami kolendry.',
    ],
    photo:
      'Creamy orange Thai coconut curry soup with chicken strips, mushrooms and rice noodles, topped with sliced spring onion, fresh coriander and a lime wedge',
    vessel: 'bowl',
  },
  {
    plan: 'ob-60',
    title: 'Zupa szpinakowa z jajkiem',
    description:
      'Aksamitna zupa ze świeżego szpinaku z ziemniakami i czosnkiem, zabielana śmietaną i doprawiona gałką muszkatołową, podana z połówkami jajka na twardo. Zielona, delikatna i sycąca.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['szpinak', 300, 'g'],
      ['ziemniak', 400, 'g'],
      ['cebula', 100, 'g'],
      ['marchew', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 20, 'g'],
      ['bulion warzywny', 300, 'ml'],
      ['śmietana 18', 100, 'g'],
      ['jajko', 4, 'szt'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Jajka ugotuj na twardo (9 minut), ostudź w zimnej wodzie i obierz.',
      'Na maśle zeszklij cebulę w kostce (4 minuty), dodaj posiekany czosnek i smaż pół minuty.',
      'Dodaj ziemniaki i marchew w kostce 1,5 cm, wlej bulion i 600 ml wody, gotuj 15 minut do miękkości.',
      'Wrzuć umyty szpinak i gotuj 2 minuty, aż zwiędnie. Zmiksuj zupę blenderem na gładko.',
      'Wmieszaj śmietanę, dopraw gałką muszkatołową, solą i pieprzem, podgrzej, nie gotując.',
      'Podawaj z przekrojonymi na pół jajkami i świeżo zmielonym pieprzem.',
    ],
    photo:
      'Smooth vivid green spinach cream soup with a swirl of cream and two halved hard-boiled eggs showing yellow yolks, dusted with black pepper',
    vessel: 'bowl',
  },
  {
    plan: 'ob-61',
    title: 'Paprykarz z kurczaka z kluseczkami',
    description:
      'Węgierski klasyk: kurczak duszony z cebulą i czerwoną papryką w aksamitnym sosie z dużą ilością słodkiej papryki i śmietany. Do tego drobne kluseczki kładzione, które świetnie zbierają sos.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['cebula', 150, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['czosnek', 1, 'szt'],
      ['papryka słodka mielona', 8, 'g'],
      ['koncentrat pomidorowy', 15, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['śmietana 18', 100, 'g'],
      ['mąka pszenna', 150, 'g'],
      ['jajko', 1, 'szt'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę 3 cm, dopraw solą i pieprzem. Obsmaż na oleju 4 minuty i odłóż.',
      'Na tym samym tłuszczu duś cebulę w drobnej kostce 6–7 minut, aż będzie miękka i złota. Dodaj paprykę w paskach i czosnek, smaż 3 minuty.',
      'Zdejmij garnek z ognia, wsyp słodką paprykę (żeby się nie przypaliła), dodaj koncentrat i 250 ml wody. Włóż kurczaka i duś pod przykryciem 15 minut.',
      'Kluseczki: wymieszaj mąkę, jajko, szczyptę soli i ok. 90 ml wody na gęste, lepkie ciasto. Nabieraj je łyżeczką i wrzucaj małe porcje do osolonego wrzątku; gotuj 2–3 minuty od wypłynięcia i odcedź.',
      'Śmietanę zahartuj gorącym sosem i wmieszaj do paprykarza, podgrzej, nie gotując.',
      'Podawaj paprykarz z kluseczkami, posypany natką.',
    ],
    photo:
      'Chicken paprikash in a velvety deep orange-red paprika cream sauce with small irregular egg dumplings, garnished with chopped parsley',
  },
  {
    plan: 'ob-62',
    title: 'Kurczak w sosie cytrynowym z ryżem',
    description:
      'Złociste kotleciki z piersi kurczaka w maślanym sosie z cytryną, czosnkiem i natką. Kwaskowy, świeży smak, który dobrze komponuje się z sypkim ryżem basmati.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['masło', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['cytryna', 80, 'g'],
      ['bulion drobiowy', 200, 'ml'],
      ['śmietanka 18', 50, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['ryż basmati', 140, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż w osolonej wodzie według opakowania (ok. 12 minut).',
      'Filet przekrój poziomo na 4 cienkie płaty, dopraw solą i pieprzem, obtocz w mące (odłóż łyżeczkę mąki).',
      'Smaż na oleju z połową masła po 3 minuty z każdej strony, aż mięso będzie złote i ścięte w środku; odłóż na talerz.',
      'Na patelni roztop resztę masła, podsmaż posiekany czosnek, oprósz odłożoną mąką. Wlej bulion i sok z połówki cytryny, gotuj 3 minuty, aż sos zgęstnieje.',
      'Wmieszaj śmietankę i starte cienko 2–3 plasterki skórki z cytryny, włóż kurczaka i podgrzej 2 minuty, polewając sosem.',
      'Podawaj z ryżem, posypane natką, z plasterkami pozostałej cytryny.',
    ],
    photo:
      'Golden pan-fried chicken cutlets in glossy lemon butter sauce with parsley and lemon slices, served with white basmati rice',
  },
  {
    plan: 'ob-63',
    title: 'Kurczak po prowansalsku z ziemniakami',
    description:
      'Udka pieczone z ziemniakami, cukinią, czerwoną cebulą, pomidorkami i czarnymi oliwkami, obficie posypane ziołami prowansalskimi i czosnkiem. Cały obiad z jednej blachy.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['udko z kurczaka', 2, 'szt'],
      ['ziemniak', 400, 'g'],
      ['cukinia', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['czosnek', 4, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['zioła prowansalskie', 4, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Udka natrzyj połową oliwy, 2 g ziół, solą i pieprzem.',
      'Ziemniaki pokrój w ćwiartki, cukinię w grube półplastry, cebulę w ósemki. Wymieszaj z resztą oliwy, ziół i soli oraz nieobranymi ząbkami czosnku.',
      'Rozłóż warzywa na blasze, ułóż na nich udka skórą do góry i piecz 30 minut.',
      'Dodaj pomidorki i oliwki, skrop wszystko sokiem z cytryny i piecz jeszcze 15–20 minut, aż skórka będzie chrupiąca, a ziemniaki miękkie.',
      'Podawaj udka na warzywach z blachy; upieczony czosnek wyciśnij ze skórki na mięso.',
    ],
    photo:
      'Roasted chicken legs with herbes de Provence on a tray of potato wedges, zucchini, red onion, burst cherry tomatoes and black olives with roasted garlic cloves',
  },
  {
    plan: 'ob-64',
    title: 'Kurczak tikka masala z ryżem',
    description:
      'Kawałki kurczaka marynowane w jogurcie z garam masalą, przypieczone i duszone w gęstym, kremowym sosie pomidorowym z imbirem i czosnkiem. Łagodne, aromatyczne curry do ryżu basmati.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['jogurt naturalny', 80, 'g'],
      ['garam masala', 6, 'g'],
      ['kurkuma', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 15, 'g'],
      ['cebula', 120, 'g'],
      ['passata pomidorowa', 300, 'ml'],
      ['śmietanka 30', 60, 'ml'],
      ['masło', 15, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ryż basmati', 140, 'g'],
      ['kolendra', 5, 'g'],
      ['sól', 3, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę 3 cm i wymieszaj z jogurtem, połową garam masali, kurkumą, 1 przeciśniętym ząbkiem czosnku i 2 g soli. Odstaw na co najmniej 20 minut.',
      'Rozgrzej olej na dużej patelni i przysmaż kurczaka partiami 2–3 minuty z każdej strony, aż brzegi się przypieką; odłóż.',
      'Na maśle smaż cebulę w drobnej kostce 7 minut, aż się zezłoci. Dodaj resztę czosnku, starty imbir, kmin, paprykę i resztę garam masali, smaż 1 minutę.',
      'Wlej passatę, gotuj 8 minut, wróć kurczaka i duś 8–10 minut, aż mięso będzie ścięte w środku. W tym czasie ugotuj ryż według opakowania.',
      'Wmieszaj śmietankę, zagotuj i dopraw resztą soli.',
      'Podawaj z ryżem basmati, posypane listkami kolendry.',
    ],
    photo:
      'Chicken tikka masala pieces in thick creamy orange tomato sauce with a swirl of cream and fresh coriander, next to fluffy basmati rice',
  },
  {
    plan: 'ob-65',
    title: 'Kurczak kung pao z ryżem',
    description:
      'Pikantny kurczak z woka z prażonymi orzeszkami, papryką i dymką w lepkim sosie sojowym z octem i odrobiną cukru. Szybki chiński klasyk, który robisz w kwadrans od pokrojenia.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['mąka ziemniaczana', 15, 'g'],
      ['sos sojowy', 40, 'ml'],
      ['ocet jabłkowy', 15, 'ml'],
      ['cukier brązowy', 10, 'g'],
      ['orzeszek ziemny', 40, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cebula dymka', 50, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 10, 'g'],
      ['płatki chili', 2, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['olej sezamowy', 5, 'ml'],
      ['ryż jaśminowy', 140, 'g'],
    ],
    steps: [
      'Ugotuj ryż według opakowania (ok. 12 minut).',
      'Kurczaka pokrój w kostkę 2 cm, wymieszaj z 15 ml sosu sojowego i 10 g mąki ziemniaczanej, odstaw na 10 minut.',
      'Sos: wymieszaj resztę sosu sojowego, ocet, cukier, resztę mąki i 60 ml wody.',
      'Na mocno rozgrzanym oleju smaż kurczaka 4–5 minut, aż się zrumieni. Dodaj płatki chili, posiekany czosnek i imbir, paprykę w kostce i białą część dymki, smaż 2 minuty.',
      'Wlej sos i mieszaj, aż zgęstnieje i oblepi kurczaka (1 minuta). Wmieszaj orzeszki i olej sezamowy.',
      'Podawaj z ryżem, posypane zieloną częścią dymki.',
    ],
    photo:
      'Kung pao chicken cubes with roasted peanuts, red pepper pieces and spring onion in glossy dark sauce, served with white jasmine rice',
  },
  {
    plan: 'ob-66',
    title: 'Kurczak pieczony w całości z ziemniakami',
    description:
      'Mały kurczak natarty masłem czosnkowo-ziołowym, pieczony na złotą, chrupiącą skórkę na łóżku z ziemniaków i cebuli, które przejmują jego sok. Niedzielny obiad bez wysiłku.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 100,
    servings: 2,
    ingredients: [
      ['kurczak cały', 1000, 'g'],
      ['ziemniak', 400, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 4, 'szt'],
      ['masło', 15, 'g'],
      ['cytryna', 50, 'g'],
      ['papryka słodka mielona', 4, 'g'],
      ['majeranek', 2, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra–dół). Kurczaka (ok. 1 kg) osusz ręcznikiem papierowym.',
      'Wymieszaj miękkie masło z 2 przeciśniętymi ząbkami czosnku, papryką, majerankiem, tymiankiem, 3 g soli i pieprzem. Natrzyj kurczaka z zewnątrz i pod skórą na piersi, do środka włóż połówkę cytryny i 2 ząbki czosnku.',
      'Ziemniaki pokrój w ćwiartki, cebulę w grube plastry, posól resztą soli i rozłóż w naczyniu żaroodpornym.',
      'Połóż kurczaka na warzywach piersią do góry i piecz ok. 70 minut, polewając co 20 minut wytopionym sokiem, aż skórka będzie złota, a sok przy nakłuciu uda przezroczysty.',
      'Wyjmij kurczaka i odstaw na 10 minut pod folią, żeby mięso odpoczęło.',
      'Podziel kurczaka na ćwiartki i podawaj z ziemniakami i cebulą z naczynia, skropione sokiem z cytryny.',
    ],
    photo:
      'Whole golden roast chicken with crispy paprika-herb skin in a baking dish on roasted potato wedges and onion slices, with lemon halves',
  },
  {
    plan: 'ob-67',
    title: 'Kotlety pożarskie z ziemniakami i mizerią',
    description:
      'Delikatne kotlety z mielonej piersi kurczaka z namoczoną bułką i kawałkiem zimnego masła w środku, w chrupiącej panierce. Soczyste i miękkie, podane z ziemniakami i mizerią.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['bułka', 40, 'g'],
      ['mleko', 60, 'ml'],
      ['masło', 25, 'g'],
      ['bułka tarta', 40, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['ziemniak', 500, 'g'],
      ['ogórek', 250, 'g'],
      ['śmietana 18', 60, 'g'],
      ['koperek', 10, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki i gotuj w osolonej wodzie 20 minut. Bułkę namocz w mleku.',
      'Kurczaka zmiel albo posiekaj nożem bardzo drobno. Wymieszaj z odciśniętą bułką, gałką muszkatołową, 2 g soli i pieprzem, wyrabiaj 2 minuty, aż masa się skleja.',
      'Podziel masę na 4 części, na każdą połóż kostkę zimnego masła (ok. 4 g), zlep w owalny kotlet i obtocz w bułce tartej.',
      'Smaż na średnim ogniu na oleju z resztą masła 5 minut z każdej strony, aż będą złote i sprężyste w środku.',
      'Mizeria: ogórka pokrój w cienkie plasterki, posól, po 5 minutach odlej sok i wymieszaj ze śmietaną i połową koperku.',
      'Podawaj kotlety z ziemniakami posypanymi koperkiem i mizerią.',
    ],
    photo:
      'Two golden breaded chicken Pozharsky cutlets with boiled potatoes sprinkled with dill and a bowl of creamy cucumber salad',
  },
  {
    plan: 'ob-68',
    title: 'Pieczeń z indyka z ziemniakami i buraczkami',
    description:
      'Pierś z indyka upieczona w całości w marynacie z musztardy, czosnku i majeranku, krojona w soczyste plastry i polana sosem z pieczenia. Do tego ziemniaki i ciepłe buraczki na maśle.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['filet z indyka', 400, 'g'],
      ['musztarda', 15, 'g'],
      ['czosnek', 2, 'szt'],
      ['majeranek', 2, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cebula', 100, 'g'],
      ['ziemniak', 500, 'g'],
      ['burak', 400, 'g'],
      ['masło', 15, 'g'],
      ['ocet jabłkowy', 10, 'ml'],
      ['cukier', 3, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Buraki umyj i ugotuj w skórce do miękkości (ok. 40 minut). Filet natrzyj musztardą, przeciśniętym czosnkiem, majerankiem, oliwą, 3 g soli i pieprzem; odstaw na czas gotowania buraków.',
      'Nagrzej piekarnik do 180°C (góra–dół). Ułóż filet w naczyniu na cebuli pokrojonej w plastry, podlej 100 ml wody.',
      'Piecz 35–40 minut, polewając co 15 minut sosem, aż mięso będzie w środku jędrne (72°C) i puści przezroczysty sok. Odstaw na 10 minut pod folią.',
      'W tym czasie ugotuj obrane ziemniaki w osolonej wodzie (20 minut).',
      'Buraki obierz i zetrzyj na dużych oczkach, podgrzej z masłem, octem, cukrem i szczyptą soli.',
      'Pokrój pieczeń w plastry 1 cm i podawaj z ziemniakami, buraczkami i sosem z cebulą z naczynia.',
    ],
    photo:
      'Sliced roast turkey breast with golden mustard crust and pan juices with onions, boiled potatoes and warm grated beetroot on the side',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
