/**
 * Katalog 500 — obiady, część C: pozycje ob-69 … ob-101 z
 * `prisma/catalog/katalog-500-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'ob-69',
    title: 'Duszony udziec z indyka z warzywami i ziemniakami',
    description:
      'Kawałki udźca z indyka duszone powoli z marchewką, pietruszką i selerem w lekko zagęszczonym sosie z majerankiem. Mięso robi się miękkie i soczyste, a sos aż prosi się o ziemniaki. Niedzielny obiad bez stania przy garach.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    ingredients: [
      ['udziec z indyka', 450, 'g'],
      ['marchew', 150, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['seler korzeniowy', 80, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['mąka pszenna', 10, 'g'],
      ['bulion drobiowy', 300, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['majeranek', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['ziemniak', 400, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Udziec pokrój w kostkę 3 cm, oprósz solą, pieprzem, papryką i mąką.',
      'Rozgrzej olej w szerokim garnku i obsmaż mięso partiami na rumiano z każdej strony, około 5 minut.',
      'Dodaj pokrojoną w piórka cebulę i przeciśnięty czosnek, smaż 2 minuty. Wlej bulion, dorzuć liść laurowy i ziele angielskie, przykryj i duś na małym ogniu 30 minut.',
      'Marchew, pietruszkę i seler obierz i pokrój w grube plastry. Dodaj do mięsa z majerankiem i duś pod przykryciem jeszcze 30 minut, aż warzywa i mięso będą miękkie, a sos lekko gęsty.',
      'W tym czasie obierz ziemniaki, pokrój na ćwiartki i ugotuj w osolonej wodzie do miękkości, około 20 minut.',
      'Wyjmij liść laurowy i ziele, dopraw sos solą i pieprzem. Podaj indyka z warzywami i sosem obok ziemniaków posypanych posiekaną natką.',
    ],
    photo:
      'Chunks of braised turkey leg in glossy golden-brown gravy with carrot, parsley root and celery slices, boiled potatoes sprinkled with chopped parsley on the side',
  },
  {
    plan: 'ob-70',
    title: 'Indyk po chińsku z warzywami i ryżem',
    description:
      'Paski indyka w chrupiącej panierce z mąki ziemniaczanej, przesmażone z warzywami w sosie sojowo-imbirowym z odrobiną miodu. Szybciej niż dostawa z baru, a smakuje podobnie. Dobrze znosi odgrzanie w pudełku.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['mieszanka chińska mrożona', 400, 'g'],
      ['ryż jaśminowy', 140, 'g'],
      ['sos sojowy', 30, 'ml'],
      ['miód', 10, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 20, 'ml'],
      ['cebula dymka', 20, 'g'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Ryż wypłucz i ugotuj w lekko osolonej wodzie według opakowania, około 12 minut.',
      'Indyka pokrój w cienkie paski i obtocz w mące ziemniaczanej.',
      'W małej miseczce wymieszaj sos sojowy, miód, starty imbir, przeciśnięty czosnek i 50 ml wody.',
      'Rozgrzej olej w woku lub dużej patelni i smaż indyka na mocnym ogniu 4–5 minut, aż się zezłoci. Przełóż na talerz.',
      'Na tę samą patelnię wrzuć zamrożoną mieszankę warzyw i smaż 5–6 minut, mieszając, aż odparuje woda, a warzywa zostaną lekko chrupiące.',
      'Wróć indyka na patelnię, wlej sos i gotuj minutę, aż zgęstnieje i oblepi mięso.',
      'Podaj z ryżem, posyp pokrojoną dymką i sezamem.',
    ],
    photo:
      'Glossy stir-fried turkey strips with bamboo shoots, carrots, mushrooms and green beans next to a mound of white jasmine rice, sprinkled with sesame seeds and green onion',
  },
  {
    plan: 'ob-71',
    title: 'Cannelloni z indykiem i szpinakiem',
    description:
      'Rurki makaronu nadziane mielonym indykiem ze szpinakiem, zapieczone w pomidorowym sosie pod ciągnącą się mozzarellą. Farsz wkładasz na surowo, więc makaronu nie trzeba wcześniej gotować. Idealne na weekend i do pudełka na następny dzień.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 70,
    servings: 2,
    ingredients: [
      ['makaron cannelloni', 150, 'g'],
      ['indyk mielony', 300, 'g'],
      ['szpinak mrożony', 250, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['passata pomidorowa', 400, 'ml'],
      ['mozzarella tarta', 80, 'g'],
      ['oregano', 1, 'g'],
      ['bazylia suszona', 1, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra-dół). Szpinak rozmroź i dokładnie odciśnij z wody.',
      'Na połowie oliwy zeszklij drobno posiekaną cebulę i czosnek, 3 minuty. Dodaj szpinak, dopraw gałką, szczyptą soli i pieprzem, smaż 2 minuty i przestudź.',
      'W misce wymieszaj indyka ze szpinakiem, 1 g soli i pieprzem. Napełnij farszem surowe rurki cannelloni, najłatwiej łyżeczką albo rękawem z odciętym rogiem.',
      'Passatę wymieszaj z oregano, bazylią, resztą oliwy i szczyptą soli. Jedną trzecią wlej do naczynia żaroodpornego.',
      'Ułóż rurki ciasno obok siebie, zalej resztą sosu tak, by makaron był w całości przykryty, i posyp mozzarellą.',
      'Przykryj folią i piecz 30 minut, potem zdejmij folię i zapiekaj jeszcze 15 minut, aż ser się zrumieni, a makaron będzie miękki po nakłuciu nożem.',
      'Odstaw na 5 minut, żeby sos się ustabilizował, i podawaj po 3–4 rurki na talerz.',
    ],
    photo:
      'Baked cannelloni tubes filled with turkey and spinach in rich red tomato sauce under bubbling golden melted mozzarella, one tube cut open showing green filling',
  },
  {
    plan: 'ob-72',
    title: 'Burrito bowl z indykiem',
    description:
      'Miska z ryżem, przyprawionym po meksykańsku indykiem, czerwoną fasolą, kukurydzą i świeżymi warzywami, z awokado i jogurtem zamiast śmietany. Wszystko, co lubisz w burrito, tylko bez zawijania. Świetnie sprawdza się do pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['ryż biały', 120, 'g'],
      ['filet z indyka', 300, 'g'],
      ['fasola czerwona z puszki', 200, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['pomidor', 1, 'szt'],
      ['cebula czerwona', 0.5, 'szt'],
      ['awokado', 1, 'szt'],
      ['limonka', 1, 'szt'],
      ['jogurt grecki', 60, 'g'],
      ['kolendra', 5, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż w osolonej wodzie według opakowania i wymieszaj z sokiem z połowy limonki.',
      'Indyka pokrój w kostkę 2 cm, obtocz w kminie, papryce wędzonej, czosnku granulowanym, 2 g soli i pieprzu.',
      'Rozgrzej olej na patelni i smaż indyka 6–7 minut, aż się zrumieni i nie będzie różowy w środku. Pod koniec dorzuć paprykę pokrojoną w paski i smaż jeszcze 2 minuty.',
      'Fasolę i kukurydzę odsącz i przepłucz. Pomidor pokrój w kostkę, cebulę posiekaj drobno, awokado pokrój w plastry i skrop sokiem z drugiej połowy limonki.',
      'Jogurt wymieszaj ze szczyptą soli i posiekaną łodyżką kolendry.',
      'Do misek nałóż ryż, a obok w sektorach indyka z papryką, fasolę, kukurydzę, pomidor z cebulą i awokado. Na środek połóż łyżkę jogurtu i posyp listkami kolendry.',
    ],
    photo:
      'Bowl with white rice, spiced browned turkey cubes with red pepper strips, red kidney beans, yellow corn, diced tomato, sliced avocado, a dollop of white yogurt and fresh cilantro, lime wedge',
    vessel: 'bowl',
  },
  {
    plan: 'ob-73',
    title: 'Pilaw z indykiem i marchewką',
    description:
      'Jednogarnkowy ryż basmati duszony z indykiem, grubą warstwą marchewki i całymi ząbkami czosnku, doprawiony kminem i kurkumą. Każde ziarenko jest osobno i przesiąknięte smakiem mięsa. Dobry na chłodny dzień i do pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['udziec z indyka', 350, 'g'],
      ['ryż basmati', 150, 'g'],
      ['marchew', 250, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 4, 'szt'],
      ['olej rzepakowy', 25, 'ml'],
      ['bulion drobiowy', 350, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['kurkuma', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['rodzynka', 20, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ryż wypłucz w kilku wodach, aż woda będzie przejrzysta, i odsącz. Indyka pokrój w kostkę 2–3 cm, marchew w grube słupki, cebulę w piórka.',
      'W szerokim garnku z grubym dnem rozgrzej olej i obsmaż indyka na mocnym ogniu 5 minut. Dodaj cebulę i smaż, aż się zezłoci.',
      'Dorzuć marchew, kmin, kurkumę, paprykę, sól i pieprz, smaż 5 minut, mieszając.',
      'Wyrównaj warstwę i wysyp na nią ryż, nie mieszając. Wciśnij w ryż nieobrane ząbki czosnku i rozsyp rodzynki.',
      'Zalej gorącym bulionem tak, by przykrył ryż na 1 cm. Przykryj i gotuj na najmniejszym ogniu 20 minut, aż ryż wchłonie płyn.',
      'Zdejmij z ognia, odstaw pod przykryciem na 10 minut, potem delikatnie wymieszaj od dna.',
      'Nałóż na talerze z ząbkami czosnku na wierzchu i posyp posiekaną natką.',
    ],
    photo:
      'Golden-yellow basmati rice pilaf with turkey chunks, long carrot sticks, raisins and whole soft garlic cloves on top, sprinkled with chopped parsley',
  },
  {
    plan: 'ob-74',
    title: 'Schab w sosie musztardowym z ziemniakami',
    description:
      'Plastry schabu krótko obsmażone i dogotowane w kremowym sosie ze śmietany i musztardy z cebulką. Sos jest łagodny, z lekką ostrością, a mięso pozostaje soczyste. Klasyczny domowy obiad na co dzień.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['schab wieprzowy', 350, 'g'],
      ['mąka pszenna', 15, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['cebula', 1, 'szt'],
      ['bulion drobiowy', 150, 'ml'],
      ['musztarda', 30, 'g'],
      ['śmietana 18', 100, 'g'],
      ['majeranek', 1, 'g'],
      ['ziemniak', 400, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, pokrój na ćwiartki i ugotuj w osolonej wodzie do miękkości, około 20 minut.',
      'Schab pokrój w 4 plastry grubości 1,5 cm, lekko rozbij przez folię, oprósz solą, pieprzem i mąką.',
      'Rozgrzej olej na patelni i smaż mięso po 2 minuty z każdej strony, aż się zrumieni. Przełóż na talerz.',
      'Na tę samą patelnię wrzuć cebulę pokrojoną w piórka i smaż 4 minuty do zeszklenia. Wlej bulion i zeskrob przysmażone resztki z dna.',
      'Wmieszaj musztardę i majeranek, połóż schab z powrotem, przykryj i duś na małym ogniu 8 minut.',
      'Zdejmij z ognia, wmieszaj śmietanę i podgrzej chwilę, nie doprowadzając do wrzenia. Dopraw solą i pieprzem.',
      'Podaj schab polany sosem z ziemniakami posypanymi posiekanym koperkiem.',
    ],
    photo:
      'Seared pork loin slices covered in creamy pale-yellow mustard sauce with soft onion, boiled potatoes sprinkled with fresh dill on the side',
  },
  {
    plan: 'ob-75',
    title: 'Golonka pieczona z kapustą',
    description:
      'Golonka najpierw gotowana z zielem i liściem laurowym, a potem pieczona z musztardą i czosnkiem, aż skórka zrobi się chrupiąca. Podawana na duszonej kapuście kiszonej z kminkiem. Sycący obiad na zimny weekend.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 180,
    servings: 2,
    ingredients: [
      ['golonka wieprzowa', 800, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 3, 'szt'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['majeranek', 2, 'g'],
      ['musztarda', 20, 'g'],
      ['kapusta kiszona', 250, 'g'],
      ['kminek', 1, 'g'],
      ['cukier', 5, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Golonkę umyj, włóż do garnka z połową cebuli, liściem laurowym, zielem i solą, zalej wodą i gotuj pod przykryciem na małym ogniu 1,5 godziny, aż mięso zacznie odchodzić od kości. Zachowaj 200 ml wywaru.',
      'Nagrzej piekarnik do 200°C (termoobieg). Czosnek przeciśnij i wymieszaj z musztardą, majerankiem i pieprzem.',
      'Osusz golonkę, natnij skórę w kratkę i posmaruj pastą musztardową. Włóż do naczynia żaroodpornego, podlej 100 ml wywaru i piecz 45 minut, aż skórka się zrumieni i zrobi chrupiąca.',
      'W tym czasie kapustę odciśnij, lekko posiekaj i wrzuć do garnka z resztą wywaru, drugą połową cebuli pokrojoną w kostkę i kminkiem. Duś pod przykryciem 30 minut, aż zmięknie.',
      'Dopraw kapustę cukrem i pieprzem i odparuj nadmiar płynu, żeby była wilgotna, ale nie wodnista.',
      'Golonkę przekrój na pół wzdłuż kości i podawaj na kapuście, z łyżką musztardy obok.',
    ],
    photo:
      'Roasted pork knuckle with crackling golden-brown scored skin sitting on a bed of braised sauerkraut with caraway seeds, a spoon of mustard on the side',
  },
  {
    plan: 'ob-76',
    title: 'Szaszłyki wieprzowe z cebulą i pieczonymi ziemniakami',
    description:
      'Szaszłyki z karkówki przekładanej boczkiem, cebulą i papryką, marynowane w czosnku i majeranku, pieczone w piekarniku razem z ziemniakami. Smakują jak z grilla, a robisz je o każdej porze roku.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['karkówka', 320, 'g'],
      ['boczek', 50, 'g'],
      ['cebula', 1.5, 'szt'],
      ['papryka czerwona', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 20, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['majeranek', 1, 'g'],
      ['ziemniak', 300, 'g'],
      ['rozmaryn suszony', 1, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Karkówkę pokrój w kostkę 3 cm. Wymieszaj z połową oleju, przeciśniętym czosnkiem, papryką słodką, majerankiem, 1,5 g soli i pieprzem; odstaw na 15 minut.',
      'Nagrzej piekarnik do 220°C (termoobieg). Ziemniaki umyj, pokrój w ósemki ze skórką, wymieszaj z resztą oleju, rozmarynem i resztą soli, rozłóż na jednej połowie blachy.',
      'Cebulę pokrój w ósemki, paprykę w kwadraty 3 cm, boczek w plasterki 2 cm.',
      'Nabijaj na patyczki na przemian mięso, boczek, cebulę i paprykę, ciasno, ale bez zgniatania.',
      'Połóż szaszłyki na drugiej połowie blachy i piecz 30–35 minut, w połowie obracając, aż mięso będzie zrumienione, a ziemniaki chrupiące na brzegach.',
      'Podaj szaszłyki na ziemniakach, polane sokiem z blachy.',
    ],
    photo:
      'Two pork skewers with browned pork chunks, bacon, charred onion and red pepper pieces lying on crispy roasted potato wedges with rosemary',
  },
  {
    plan: 'ob-77',
    title: 'Kiełbasa z kapustą zasmażaną i ziemniakami',
    description:
      'Kiszona kapusta duszona z kminkiem i zasmażką, z przysmażoną kiełbasą w plastrach, obok ziemniaki z koperkiem. Prosty, swojski obiad jak u babci, gotowy w trzy kwadranse.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['kiełbasa', 160, 'g'],
      ['kapusta kiszona', 200, 'g'],
      ['cebula', 1, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['mąka pszenna', 15, 'g'],
      ['kminek', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['cukier', 5, 'g'],
      ['ziemniak', 450, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kapustę lekko odciśnij i posiekaj. Włóż do garnka z liściem laurowym, zielem i kminkiem, zalej 250 ml wody i duś pod przykryciem 25 minut.',
      'Ziemniaki obierz i ugotuj w wodzie z solą do miękkości, około 20 minut.',
      'Kiełbasę pokrój w plastry, cebulę w kostkę. Na patelni rozgrzej olej, podsmaż kiełbasę 3 minuty, dodaj cebulę i smaż, aż się zezłoci.',
      'Oprósz kiełbasę z cebulą mąką i smaż jeszcze minutę, mieszając, żeby powstała zasmażka.',
      'Przełóż zawartość patelni do kapusty, wymieszaj i gotuj 5 minut, aż sos zgęstnieje. Dopraw cukrem i pieprzem, wyjmij liść laurowy.',
      'Podaj kapustę z kiełbasą obok ziemniaków posypanych koperkiem.',
    ],
    photo:
      'Golden fried sauerkraut with browned sausage slices and onion, boiled potatoes sprinkled with fresh dill on the side',
  },
  {
    plan: 'ob-78',
    title: 'Kaszanka pieczona z cebulką i ziemniakami',
    description:
      'Kaszanka zapiekana na blasze na miękkiej, słodkawej cebuli, a obok pieczone ziemniaki z majerankiem. Z kiszonym ogórkiem smakuje najlepiej. Tani, szybki obiad, który robi się właściwie sam.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['kaszanka', 300, 'g'],
      ['cebula', 2, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['ziemniak', 500, 'g'],
      ['majeranek', 2, 'g'],
      ['ogórek kiszony', 80, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg).',
      'Ziemniaki umyj, pokrój w kostkę 2 cm ze skórką, wymieszaj z połową oleju, solą i połową majeranku. Rozłóż na blasze i piecz 15 minut.',
      'Cebulę pokrój w grube piórka i wymieszaj z resztą oleju, majerankiem i pieprzem.',
      'Kaszankę pokrój w kawałki 5 cm (albo zostaw w całości i natnij osłonkę w kilku miejscach).',
      'Przesuń ziemniaki na bok, rozłóż cebulę i ułóż na niej kaszankę. Piecz 25 minut, aż kaszanka będzie chrupiąca z wierzchu, a cebula miękka i przyrumieniona.',
      'Podaj kaszankę na cebuli z ziemniakami i ogórkiem kiszonym pokrojonym w plastry.',
    ],
    photo:
      'Roasted black pudding pieces with crispy casing on soft caramelized onions, golden roasted potato cubes and pickled cucumber slices on the side',
  },
  {
    plan: 'ob-79',
    title: 'Wołowina z brokułem po chińsku z ryżem',
    description:
      'Cienkie paski wołowiny smażone błyskawicznie z różyczkami brokułu w lśniącym sosie sojowym z czosnkiem i imbirem. Brokuł zostaje jędrny i zielony, a mięso miękkie. Obiad w pół godziny, dobry też na drugi dzień.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['wołowina', 300, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['brokuł', 350, 'g'],
      ['ryż jaśminowy', 140, 'g'],
      ['sos sojowy', 30, 'ml'],
      ['miód', 10, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 10, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['cebula dymka', 20, 'g'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Ryż wypłucz i ugotuj według opakowania, około 12 minut.',
      'Wołowinę pokrój w poprzek włókien w paski grubości 3–4 mm i wymieszaj z mąką ziemniaczaną i 1 łyżką sosu sojowego.',
      'Brokuł podziel na małe różyczki i blanszuj 2 minuty we wrzącej wodzie, potem odcedź.',
      'Wymieszaj resztę sosu sojowego z miodem, przeciśniętym czosnkiem, startym imbirem i 60 ml wody.',
      'Rozgrzej olej w woku do dymienia i smaż wołowinę partiami po 1,5 minuty, aż się zrumieni. Dorzuć brokuł, wlej sos i smaż minutę, aż zgęstnieje i oblepi składniki.',
      'Podaj na ryżu, posyp sezamem i pokrojoną dymką.',
    ],
    photo:
      'Thin glossy beef strips with bright green broccoli florets in dark soy-ginger sauce beside white jasmine rice, topped with sesame seeds and sliced green onion',
  },
  {
    plan: 'ob-80',
    title: 'Stek wołowy z frytkami z piekarnika i sałatą',
    description:
      'Wołowy stek usmażony na mocno rozgrzanej patelni i polany masłem z czosnkiem i rozmarynem, z chrupiącymi frytkami z piekarnika i świeżą sałatą. Domowa wersja klasyka z knajpy, bez frytkownicy.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['wołowina', 360, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['masło', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['rozmaryn suszony', 1, 'g'],
      ['frytka mrożona', 300, 'g'],
      ['sałata lodowa', 120, 'g'],
      ['pomidor', 1, 'szt'],
      ['ogórek', 0.5, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Wyjmij steki (2 plastry rostbefu albo antrykotu grubości 2,5 cm) z lodówki 30 minut przed smażeniem. Nagrzej piekarnik do 220°C (termoobieg).',
      'Rozłóż frytki w jednej warstwie na blasze z papierem i piecz 20–25 minut, w połowie przewracając, aż będą złote i chrupiące. Posól po wyjęciu.',
      'Steki osusz ręcznikiem, posmaruj olejem i dopraw solą. Rozgrzej patelnię (najlepiej żeliwną) do dymienia i smaż po 3 minuty z każdej strony dla średnio wysmażonego mięsa.',
      'Pod koniec dodaj masło, zgnieciony czosnek i rozmaryn, i przez minutę polewaj steki pieniącym się masłem łyżką.',
      'Zdejmij steki na deskę, oprósz pieprzem i odstaw na 5 minut, żeby soki się rozeszły.',
      'Sałatę porwij, pomidor pokrój w cząstki, ogórek w plastry. Skrop oliwą i sokiem z cytryny, posól.',
      'Pokrój steki w poprzek włókien i podaj z frytkami i sałatą, polane masłem z patelni.',
    ],
    photo:
      'Sliced medium-rare beef steak with pink center glazed with garlic butter, golden oven fries and a fresh salad of iceberg lettuce, tomato wedges and cucumber',
  },
  {
    plan: 'ob-81',
    title: 'Kofta z mielonej wołowiny z ryżem i tzatziki',
    description:
      'Podłużne kotleciki z wołowiny z cebulą, natką i kminem rzymskim, zrumienione na patelni, z ryżem basmati i chłodnym tzatziki z ogórkiem. Korzenne, soczyste i świeże zarazem. Dobre do pudełka, tzatziki spakuj osobno.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['wołowina mielona', 300, 'g'],
      ['cebula', 0.5, 'szt'],
      ['czosnek', 3, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['cynamon', 0.5, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ryż basmati', 120, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['ogórek', 0.5, 'szt'],
      ['koperek', 5, 'g'],
      ['cytryna', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż w lekko osolonej wodzie według opakowania.',
      'Ogórek zetrzyj na grubych oczkach, posól szczyptą i po 5 minutach mocno odciśnij. Wymieszaj z jogurtem, 1 przeciśniętym ząbkiem czosnku, posiekanym koperkiem, sokiem z cytryny i szczyptą soli. Wstaw do lodówki.',
      'Cebulę zetrzyj na drobnych oczkach, natkę posiekaj. Wymieszaj z mięsem, resztą czosnku, kminem, papryką, cynamonem, solą i pieprzem; wyrabiaj ręką 2 minuty.',
      'Wilgotnymi dłońmi uformuj 8 podłużnych kotlecików długości około 8 cm.',
      'Rozgrzej olej na patelni i smaż koftę 8–10 minut, obracając, aż będzie zrumieniona ze wszystkich stron i sprężysta w środku.',
      'Podaj koftę na ryżu z dużą łyżką tzatziki, posypaną resztą natki.',
    ],
    photo:
      'Browned elongated beef kofta kebabs on fluffy basmati rice with a generous spoon of white tzatziki with grated cucumber and dill, chopped parsley on top',
  },
  {
    plan: 'ob-82',
    title: 'Makaron udon z wołowiną i warzywami',
    description:
      'Grube, sprężyste kluski udon przesmażone z paskami wołowiny, papryką, marchewką i kapustą pekińską w sosie sojowym z imbirem. Sycąca miska w stylu azjatyckiego baru, gotowa w niecałe pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['makaron udon', 140, 'g'],
      ['wołowina', 250, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['marchew', 1, 'szt'],
      ['kapusta pekińska', 150, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos sojowy', 15, 'ml'],
      ['miód', 10, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Makaron ugotuj według opakowania (zwykle 8–10 minut), przelej zimną wodą i odsącz.',
      'Wołowinę pokrój w cienkie paski w poprzek włókien. Paprykę pokrój w paski, marchew w cienkie słupki, kapustę w paski 1 cm, dymkę w ukośne kawałki.',
      'Wymieszaj sos sojowy z miodem, startym imbirem, przeciśniętym czosnkiem i 3 łyżkami wody.',
      'Rozgrzej połowę oleju w woku i smaż wołowinę na mocnym ogniu 2 minuty, aż się zrumieni. Przełóż na talerz.',
      'Wlej resztę oleju, wrzuć marchew i paprykę, smaż 3 minuty. Dodaj kapustę i białą część dymki, smaż 1 minutę.',
      'Dodaj makaron, wołowinę i sos, mieszaj 2 minuty, aż makaron się podgrzeje i pokryje sosem.',
      'Podaj w miskach, posypane sezamem i zieloną częścią dymki.',
    ],
    photo:
      'Thick glossy udon noodles tossed with beef strips, red pepper, carrot matchsticks and napa cabbage in soy sauce, topped with sesame seeds and green onion',
    vessel: 'bowl',
  },
  {
    plan: 'ob-83',
    title: 'Zapiekanka pasterska z mieloną wołowiną',
    description:
      'Warstwa wołowiny duszonej z marchewką, groszkiem i koncentratem pomidorowym pod puszystym puree ziemniaczanym, zapieczona z cheddarem na złoto. Brytyjski klasyk, który w polskiej kuchni czuje się jak w domu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 2,
    ingredients: [
      ['wołowina mielona', 300, 'g'],
      ['cebula', 1, 'szt'],
      ['marchew', 1, 'szt'],
      ['groszek mrożony', 100, 'g'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['bulion warzywny', 150, 'ml'],
      ['tymianek suszony', 1, 'g'],
      ['ziemniak', 500, 'g'],
      ['masło', 20, 'g'],
      ['mleko', 80, 'ml'],
      ['ser cheddar', 40, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, pokrój i ugotuj w osolonej wodzie do miękkości, około 20 minut. Nagrzej piekarnik do 200°C (góra-dół).',
      'Na suchej, rozgrzanej patelni smaż wołowinę 5 minut, rozbijając grudki, aż się zrumieni. Dodaj posiekaną cebulę i startą marchew, smaż 5 minut.',
      'Wmieszaj koncentrat i mąkę, smaż minutę. Wlej bulion, dodaj tymianek, sól i pieprz, duś 10 minut. Pod koniec wmieszaj groszek — farsz ma być gęsty, nie wodnisty.',
      'Ugotowane ziemniaki odcedź, rozgnieć z masłem i ciepłym mlekiem na gładkie puree, dopraw solą.',
      'Farsz przełóż do naczynia żaroodpornego, rozprowadź na nim puree i zrób widelcem rowki. Posyp startym cheddarem.',
      'Zapiekaj 20–25 minut, aż wierzch będzie złoty, a sos zacznie bulgotać na brzegach. Odstaw na 5 minut i podawaj.',
    ],
    photo:
      "Portion of shepherd's pie showing a layer of minced beef with peas and carrots under fluffy mashed potato with a golden crust of melted cheddar",
  },
  {
    plan: 'ob-84',
    title: 'Penne arrabbiata z parmezanem',
    description:
      'Rurki makaronu w ostrym sosie z pomidorów, czosnku i chili, zrobionym na dobrej oliwie. Mało składników, dużo smaku i ognia. Na szybki obiad, gdy lodówka jest prawie pusta, a spiżarnia nie.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['makaron penne', 200, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['czosnek', 3, 'szt'],
      ['płatki chili', 1, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['ser parmezan', 40, 'g'],
      ['sól', 3, 'g'],
    ],
    steps: [
      'Zagotuj dużo wody z solą i ugotuj makaron al dente według opakowania. Odlej pół szklanki wody z gotowania.',
      'W tym czasie na patelni podgrzej oliwę z pokrojonym w plasterki czosnkiem i płatkami chili na małym ogniu, aż czosnek zacznie się złocić, około 2 minut.',
      'Wlej pomidory, dopraw szczyptą soli i gotuj 10–12 minut, aż sos zgęstnieje.',
      'Przełóż makaron do sosu, dodaj kilka łyżek wody z gotowania i mieszaj minutę, aż sos oblepi rurki.',
      'Wmieszaj połowę posiekanej natki i podawaj posypane startym parmezanem i resztą natki.',
    ],
    photo:
      'Penne pasta coated in spicy red tomato sauce with visible chili flakes and sliced garlic, topped with grated parmesan and chopped parsley',
  },
  {
    plan: 'ob-85',
    title: 'Makaron ze szpinakiem i gorgonzolą',
    description:
      'Wstążki tagliatelle w kremowym sosie z gorgonzoli i śmietanki ze świeżym szpinakiem, posypane prażonymi orzechami włoskimi. Wyrazisty, lekko pikantny ser równoważy łagodny szpinak. Gotowe w kwadrans.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['makaron tagliatelle', 180, 'g'],
      ['szpinak', 200, 'g'],
      ['ser gorgonzola', 100, 'g'],
      ['śmietanka 18', 150, 'ml'],
      ['czosnek', 2, 'szt'],
      ['masło', 10, 'g'],
      ['orzech włoski', 20, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron w osolonej wodzie al dente według opakowania.',
      'Orzechy posiekaj grubo i upraż na suchej patelni 2–3 minuty, aż zapachną. Odsyp.',
      'Na tej samej patelni rozpuść masło, podsmaż przeciśnięty czosnek przez 30 sekund i wrzuć szpinak. Mieszaj 2 minuty, aż zwiędnie.',
      'Wlej śmietankę, dodaj pokruszoną gorgonzolę i gałkę muszkatołową, podgrzewaj, mieszając, aż ser się rozpuści, a sos lekko zgęstnieje, około 3 minut. Dopraw pieprzem.',
      'Dodaj odcedzony makaron i wymieszaj, w razie potrzeby rozrzedź sos łyżką wody z gotowania.',
      'Podaj od razu, posypany prażonymi orzechami i świeżo mielonym pieprzem.',
    ],
    photo:
      'Tagliatelle ribbons in creamy pale gorgonzola sauce with wilted dark green spinach, topped with toasted chopped walnuts and cracked black pepper',
  },
  {
    plan: 'ob-86',
    title: 'Makaron z kiełbasą i pomidorami',
    description:
      'Świderki z podsmażoną kiełbasą śląską w gęstym sosie pomidorowym z cebulą, papryką i oregano. Tani obiad z tego, co zwykle jest w domu, który lubią i dzieci, i dorośli. Świetnie odgrzewa się następnego dnia.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['makaron świder', 180, 'g'],
      ['kiełbasa śląska', 150, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['oregano', 1, 'g'],
      ['bazylia', 5, 'g'],
      ['ser parmezan', 20, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron w osolonej wodzie al dente według opakowania.',
      'Kiełbasę pokrój w półplasterki, cebulę w kostkę. Na rozgrzanym oleju smaż kiełbasę 3–4 minuty, aż się zrumieni.',
      'Dodaj cebulę i przeciśnięty czosnek, smaż 3 minuty. Oprósz papryką i oregano.',
      'Wlej pomidory i gotuj sos 10 minut, aż zgęstnieje. Dopraw pieprzem.',
      'Wymieszaj sos z odcedzonym makaronem.',
      'Podaj posypany startym parmezanem i listkami bazylii.',
    ],
    photo:
      'Fusilli pasta in thick tomato sauce with browned half-moon sausage slices and onion, topped with grated parmesan and fresh basil leaves',
  },
  {
    plan: 'ob-87',
    title: 'Spaghetti z klopsikami w sosie pomidorowym',
    description:
      'Miękkie klopsiki z mięsa wieprzowo-wołowego duszone w gęstym sosie z passaty z bazylią, podane na spaghetti z parmezanem. Rodzinny klasyk, który warto zrobić w podwójnej ilości — klopsiki świetnie się mrożą.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['wieprzowina i wołowina mielona', 250, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 25, 'g'],
      ['cebula', 0.5, 'szt'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['passata pomidorowa', 500, 'ml'],
      ['cukier', 3, 'g'],
      ['oregano', 1, 'g'],
      ['bazylia', 5, 'g'],
      ['makaron spaghetti', 150, 'g'],
      ['ser parmezan', 20, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę zetrzyj na drobnych oczkach. Wymieszaj mięso z jajkiem, bułką tartą, cebulą, 1 przeciśniętym ząbkiem czosnku, 2 g soli i pieprzem.',
      'Wilgotnymi dłońmi uformuj 12 klopsików wielkości orzecha włoskiego.',
      'Rozgrzej oliwę w szerokim rondlu i obsmaż klopsiki ze wszystkich stron, około 5 minut. Dodaj resztę przeciśniętego czosnku i smaż 30 sekund.',
      'Wlej passatę, dodaj cukier, oregano i resztę soli. Przykryj i duś na małym ogniu 20 minut, delikatnie obracając klopsiki.',
      'W tym czasie ugotuj spaghetti w osolonej wodzie al dente.',
      'Wymieszaj makaron z częścią sosu, nałóż na talerze, na wierzch połóż klopsiki z resztą sosu, posyp startym parmezanem i listkami bazylii.',
    ],
    photo:
      'Spaghetti topped with round browned meatballs in thick red tomato sauce, sprinkled with grated parmesan and fresh basil leaves',
  },
  {
    plan: 'ob-88',
    title: 'Makaron z kremowym sosem dyniowym',
    description:
      'Penne w aksamitnym sosie z pieczonej dyni, śmietanki i parmezanu, doprawionym gałką muszkatołową i tymiankiem, z chrupiącymi pestkami dyni. Jesienny obiad w pomarańczowym kolorze, bez mięsa i bez nudy.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['dynia', 400, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['masło', 15, 'g'],
      ['bulion warzywny', 150, 'ml'],
      ['śmietanka 18', 100, 'ml'],
      ['ser parmezan', 40, 'g'],
      ['makaron penne', 180, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['pestki dyni', 15, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dynię obierz, usuń pestki i pokrój w kostkę 2 cm. Cebulę posiekaj.',
      'Na maśle zeszklij cebulę z przeciśniętym czosnkiem, 3 minuty. Dodaj dynię i tymianek, smaż 3 minuty.',
      'Wlej bulion, przykryj i duś 15 minut, aż dynia będzie zupełnie miękka.',
      'W tym czasie ugotuj makaron w osolonej wodzie al dente, a pestki upraż na suchej patelni.',
      'Dynię zmiksuj blenderem ze śmietanką na gładki sos, wmieszaj połowę startego parmezanu, gałkę, sól i pieprz. Jeśli jest za gęsty, rozrzedź wodą z makaronu.',
      'Wymieszaj makaron z sosem i podaj posypany resztą parmezanu i uprażonymi pestkami dyni.',
    ],
    photo:
      'Penne pasta coated in smooth bright orange creamy pumpkin sauce, topped with grated parmesan and toasted green pumpkin seeds',
  },
  {
    plan: 'ob-89',
    title: 'Makaron z truskawkami i śmietaną',
    description:
      'Świderki z zimnym sosem z rozgniecionych truskawek, śmietany i jogurtu greckiego, lekko osłodzonym cukrem waniliowym. Letni obiad z dzieciństwa, gotowy w kwadrans — idealny w upalny dzień w sezonie na truskawki.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['makaron świder', 180, 'g'],
      ['truskawka', 400, 'g'],
      ['śmietana 18', 100, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['cukier', 20, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ugotuj makaron al dente w lekko osolonej wodzie według opakowania i odcedź.',
      'Truskawki umyj i odszypułkuj. Kilka ładnych owoców pokrój w ćwiartki do dekoracji.',
      'Resztę truskawek rozgnieć widelcem albo krótko zmiksuj z cukrem i cukrem waniliowym — mogą zostać kawałki.',
      'Wmieszaj śmietanę i jogurt grecki, aż powstanie różowy sos.',
      'Podaj ciepły makaron polany zimnym sosem truskawkowym, z ćwiartkami truskawek na wierzchu.',
    ],
    photo:
      'Fusilli pasta covered with creamy pink strawberry and sour cream sauce, topped with fresh strawberry quarters',
  },
  {
    plan: 'ob-90',
    title: 'Paella z kurczakiem i kiełbasą chorizo',
    description:
      'Ryż gotowany na jednej patelni z kurczakiem, pikantną kiełbasą chorizo, papryką i groszkiem, zabarwiony kurkumą i wędzoną papryką. Hiszpański klimat z produktów z osiedlowego sklepu, podany prosto z patelni z cytryną.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['ryż arborio', 160, 'g'],
      ['filet z kurczaka', 250, 'g'],
      ['kiełbasa chorizo', 60, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cebula', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['groszek mrożony', 100, 'g'],
      ['bulion drobiowy', 300, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kurkuma', 1, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę 2 cm i dopraw solą, pieprzem i połową papryki wędzonej. Chorizo pokrój w półplasterki, paprykę w paski, cebulę w kostkę.',
      'Na dużej patelni rozgrzej oliwę i smaż chorizo 2 minuty, aż puści czerwony tłuszcz. Dodaj kurczaka i smaż 5 minut, aż się zrumieni.',
      'Dodaj cebulę, paprykę i przeciśnięty czosnek, smaż 3 minuty. Wsyp ryż, resztę papryki wędzonej i kurkumę, mieszaj minutę.',
      'Wlej pomidory, gorący bulion i wodę (200 ml), wyrównaj powierzchnię i gotuj bez mieszania na małym ogniu 18 minut.',
      'Rozsyp groszek na wierzchu, przykryj i gotuj jeszcze 5 minut, aż ryż wchłonie płyn i będzie miękki. Zdejmij z ognia i odstaw na 5 minut.',
      'Podaj prosto z patelni, posypaną natką, z cząstkami cytryny do skropienia.',
    ],
    photo:
      'Golden-yellow paella in a pan with chicken pieces, red chorizo slices, red pepper strips and green peas, lemon wedges and chopped parsley on top',
  },
  {
    plan: 'ob-91',
    title: 'Risotto z dynią i parmezanem',
    description:
      'Kremowe risotto z kawałkami dyni, która częściowo rozpada się w ryżu i barwi go na pomarańczowo, wykończone masłem i parmezanem. Otulające, jesienne danie na spokojny obiad w domu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['ryż arborio', 160, 'g'],
      ['dynia', 400, 'g'],
      ['cebula', 1, 'szt'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['masło', 25, 'g'],
      ['bulion warzywny', 500, 'ml'],
      ['ser parmezan', 60, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['pestki dyni', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dynię obierz i pokrój w kostkę 1,5 cm, cebulę posiekaj drobno. Bulion połącz z wodą (300 ml), podgrzej i trzymaj na małym ogniu.',
      'W szerokim rondlu rozgrzej oliwę z połową masła, zeszklij cebulę z przeciśniętym czosnkiem, 3 minuty. Dodaj dynię i tymianek, smaż 5 minut.',
      'Wsyp ryż i mieszaj 2 minuty, aż ziarna staną się szkliste na brzegach.',
      'Wlewaj gorący bulion po jednej chochli, mieszając często i dolewając kolejną, gdy poprzednia się wchłonie. Gotuj tak 18–20 minut, aż ryż będzie kremowy, ale lekko twardy w środku.',
      'Zdejmij z ognia, wmieszaj resztę masła, większość startego parmezanu, gałkę i pieprz. Przykryj i odstaw na 2 minuty.',
      'Podaj na płytkich talerzach, posypane resztą parmezanu i uprażonymi na suchej patelni pestkami dyni.',
    ],
    photo:
      'Creamy orange pumpkin risotto with soft pumpkin cubes, topped with shaved parmesan, toasted pumpkin seeds and black pepper',
  },
  {
    plan: 'ob-92',
    title: 'Łosoś w miodzie i sosie sojowym z ryżem',
    description:
      'Kawałki łososia glazurowane na patelni w słodko-słonym sosie z miodu, soi, czosnku i imbiru, z ryżem jaśminowym i brokułem na parze. Błyszcząca glazura i soczysta ryba w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['łosoś', 300, 'g'],
      ['miód', 20, 'g'],
      ['sos sojowy', 30, 'ml'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ryż jaśminowy', 140, 'g'],
      ['brokuł', 250, 'g'],
      ['sezam', 5, 'g'],
      ['cebula dymka', 15, 'g'],
    ],
    steps: [
      'Ugotuj ryż według opakowania. Brokuł podziel na różyczki i ugotuj na parze 5–6 minut, aż będzie jędrny.',
      'Wymieszaj miód, sos sojowy, przeciśnięty czosnek i starty imbir.',
      'Łososia osusz i pokrój na 2 kawałki. Rozgrzej olej na patelni i smaż rybę skórą do dołu 4 minuty, potem odwróć i smaż 2 minuty.',
      'Wlej sos i gotuj 1–2 minuty, polewając łososia łyżką, aż glazura zgęstnieje i zacznie błyszczeć. Nie przegrzej, bo miód się przypali.',
      'Podaj łososia na ryżu z brokułem, polanego resztą glazury z patelni, posypanego sezamem i pokrojoną dymką.',
    ],
    photo:
      'Honey-soy glazed salmon fillet with sticky caramelized surface on white jasmine rice with steamed broccoli, sprinkled with sesame seeds and green onion',
  },
  {
    plan: 'ob-93',
    title: 'Dorsz duszony w pomidorach z ziemniakami',
    description:
      'Kawałki dorsza duszone w sosie z pomidorów, papryki, czosnku i czarnych oliwek, podane z gotowanymi ziemniakami. Delikatna, rozpadająca się ryba i aromatyczny sos w stylu śródziemnomorskim. Lekki obiad bez smażenia.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['dorsz', 350, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['cebula', 1, 'szt'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['oliwka czarna', 30, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['oregano', 1, 'g'],
      ['ziemniak', 400, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i ugotuj w osolonej wodzie do miękkości, około 20 minut.',
      'Cebulę pokrój w kostkę, paprykę w paski, czosnek w plasterki. Na oliwie w głębokiej patelni smaż je 5 minut, aż zmiękną.',
      'Dodaj paprykę mieloną i oregano, wlej pomidory i gotuj 8 minut, aż sos zgęstnieje. Wrzuć przekrojone oliwki.',
      'Dorsza pokrój na 4 kawałki, posól i popieprz. Włóż do sosu, przykryj i duś na małym ogniu 8–10 minut, aż ryba będzie biała i zacznie się rozdzielać na płatki.',
      'Podaj dorsza w sosie z ziemniakami, posypanego posiekaną natką.',
    ],
    photo:
      'White cod pieces flaking apart in chunky tomato sauce with red pepper strips and black olives, boiled potatoes and chopped parsley on the side',
  },
  {
    plan: 'ob-94',
    title: 'Makrela pieczona z ziemniakami i cytryną',
    description:
      'Cała makrela pieczona z czosnkiem, cytryną i koperkiem na blasze z ziemniakami w plasterkach. Tłusta ryba robi się soczysta, a skórka chrupiąca. Tani i bardzo sycący obiad, bogaty w kwasy omega-3.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 55,
    servings: 2,
    ingredients: [
      ['makrela', 2, 'szt'],
      ['ziemniak', 500, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 1, 'szt'],
      ['czosnek', 3, 'szt'],
      ['koperek', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['cebula czerwona', 1, 'szt'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Ziemniaki umyj i pokrój w plastry grubości 5 mm, cebulę w piórka.',
      'Wymieszaj ziemniaki i cebulę z połową oliwy, papryką, 2 g soli i pieprzem, rozłóż na blasze i piecz 15 minut.',
      'Makrele umyj i osusz, natnij skórę ukośnie 3 razy z każdej strony. Natrzyj w środku i na zewnątrz resztą soli, pieprzem i przeciśniętym czosnkiem.',
      'Do brzucha każdej ryby włóż 2 plasterki cytryny i gałązki koperku. Posmaruj ryby resztą oliwy.',
      'Połóż makrele na ziemniakach i piecz 20–25 minut, aż skórka będzie złota, a mięso przy kręgosłupie białe i łatwo odchodzące od ości.',
      'Podaj rybę z ziemniakami, skrop sokiem z reszty cytryny i posyp posiekanym koperkiem.',
    ],
    photo:
      'Whole roasted mackerel with golden scored skin, lemon slices and dill in the belly, lying on crispy roasted potato slices with red onion',
  },
  {
    plan: 'ob-95',
    title: 'Pierogi z serem na słodko ze śmietaną',
    description:
      'Domowe pierogi z cienkiego ciasta z twarogowym nadzieniem z wanilią, podane z masłem i kleksem śmietany. Łagodne, lekko słodkie i bardzo polskie. Część możesz od razu zamrozić na później.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 75,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ser twaróg półtłusty', 350, 'g'],
      ['jajko', 1, 'szt'],
      ['cukier', 25, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['masło', 15, 'g'],
      ['śmietana 18', 50, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Z mąki, ciepłej wody (110 ml), oleju i soli zagnieć gładkie, elastyczne ciasto, około 5 minut. Przykryj miską i odstaw na 20 minut.',
      'Twaróg zmiel albo rozgnieć widelcem, wymieszaj z jajkiem, cukrem i cukrem waniliowym na gęstą masę.',
      'Ciasto rozwałkuj cienko (2 mm) na oprószonym mąką blacie i wykrawaj szklanką krążki o średnicy 7 cm.',
      'Na każdy krążek nałóż łyżeczkę nadzienia, złóż na pół i dokładnie zlep brzegi, żeby pierogi nie pękły przy gotowaniu. Wyjdzie około 24 sztuk.',
      'Gotuj partiami w dużym garnku osolonej wody: od wypłynięcia jeszcze 2 minuty. Wyjmuj łyżką cedzakową.',
      'Podaj pierogi polane roztopionym masłem, z łyżką śmietany na wierzchu.',
    ],
    photo:
      'Boiled half-moon dumplings with sweet white cheese filling glistening with melted butter, a dollop of sour cream on top',
  },
  {
    plan: 'ob-96',
    title: 'Pierogi z jagodami ze śmietaną i cukrem',
    description:
      'Pierogi z delikatnego ciasta pełne słodkich jagód, które przy gryzieniu puszczają fioletowy sok, podane ze śmietaną i cukrem. Smak lata z lasu — w sezonie ze świeżych owoców, zimą z mrożonych.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 75,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 220, 'g'],
      ['jajko', 1, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['jagoda', 350, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['cukier', 30, 'g'],
      ['śmietana 18', 150, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Z mąki, jajka, ciepłej wody (100 ml), oleju i soli zagnieć gładkie ciasto. Przykryj i odstaw na 20 minut.',
      'Jagody przebierz, umyj i dokładnie osusz (mrożonych nie rozmrażaj). Wymieszaj z mąką ziemniaczaną i 10 g cukru tuż przed lepieniem, żeby nie puściły soku.',
      'Ciasto rozwałkuj cienko i wykrawaj krążki szklanką o średnicy 7–8 cm.',
      'Na każdy krążek nałóż łyżkę jagód, złóż i bardzo starannie zlep brzegi. Wyjdzie około 20 pierogów.',
      'Gotuj partiami w osolonej wodzie: od wypłynięcia jeszcze 2–3 minuty. Wyjmuj ostrożnie łyżką cedzakową.',
      'Śmietanę wymieszaj z cukrem waniliowym. Podaj pierogi polane śmietaną i posypane resztą cukru.',
    ],
    photo:
      'Boiled dumplings with dark purple blueberry juice seeping through the dough, topped with white sweet sour cream and a sprinkle of sugar, a few blueberries around',
  },
  {
    plan: 'ob-97',
    title: 'Kluski na parze z sosem jagodowym',
    description:
      'Puszyste drożdżowe kluski gotowane na parze, podane z ciepłym sosem z jagód. Miękkie jak chmurka w środku, z lekko słodkim smakiem. Słodki obiad, na który czeka się z przyjemnością, dobry też na podwieczorek.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['mleko', 130, 'ml'],
      ['drożdże', 15, 'g'],
      ['cukier', 45, 'g'],
      ['jajko', 1, 'szt'],
      ['masło', 25, 'g'],
      ['sól', 1, 'g'],
      ['jagoda', 300, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['jogurt grecki', 100, 'g'],
    ],
    steps: [
      'Drożdże rozetrzyj z 1 łyżeczką cukru i połową letniego mleka, odstaw na 10 minut, aż zaczną pienić.',
      'Do mąki dodaj zaczyn, resztę mleka, jajko, 20 g cukru, sól i roztopione, przestudzone masło. Wyrabiaj 8 minut na gładkie, lekko klejące się ciasto. Przykryj i odstaw w ciepłe miejsce na 45–60 minut, aż podwoi objętość.',
      'Podziel ciasto na 8 kulek, ułóż na oprószonej mąką stolnicy, przykryj ściereczką i odstaw na 15 minut.',
      'Na garnek z gotującą się wodą nałóż gazę lub parowar, posmaruj olejem lub masłem i gotuj kluski pod przykryciem 12–15 minut, nie uchylając pokrywki. Gotowe są sprężyste i suche po nakłuciu patyczkiem.',
      'Jagody zagotuj z resztą cukru i 50 ml wody. Mąkę ziemniaczaną rozmieszaj w 3 łyżkach zimnej wody, wlej do jagód i zagotuj, mieszając, aż sos zgęstnieje.',
      'Podaj gorące kluski polane sosem jagodowym, z łyżką jogurtu greckiego obok.',
    ],
    photo:
      'Fluffy white steamed yeast dumplings drizzled with glossy dark purple blueberry sauce, a spoon of white Greek yogurt on the side',
  },
  {
    plan: 'ob-98',
    title: 'Knedle ze śliwkami z masłem i bułką tartą',
    description:
      'Ziemniaczane kluski skrywające całą śliwkę z cynamonem, polane masłem ze zrumienioną bułką tartą i posypane cukrem. Jesienny klasyk z czasów, gdy śliwki węgierki zalewają targi. Ciasto jest miękkie, a owoc soczysty i lekko kwaśny.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 80,
    servings: 2,
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['mąka pszenna', 130, 'g'],
      ['mąka ziemniaczana', 30, 'g'],
      ['jajko', 1, 'szt'],
      ['śliwka', 300, 'g'],
      ['cynamon', 1, 'g'],
      ['cukier', 30, 'g'],
      ['masło', 25, 'g'],
      ['bułka tarta', 25, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, ugotuj w osolonej wodzie do miękkości, odcedź, dobrze odparuj i przeciśnij przez praskę. Ostudź całkowicie.',
      'Do ziemniaków dodaj mąkę pszenną, ziemniaczaną i jajko, szybko zagnieć miękkie, niekleiste ciasto.',
      'Śliwki umyj, natnij z boku i wyjmij pestki. Do każdej włóż szczyptę cynamonu i odrobinę cukru (łącznie 10 g).',
      'Ciasto podziel na tyle kawałków, ile masz śliwek (około 10). Każdy spłaszcz na dłoni, owiń nim śliwkę i uformuj gładką kulę bez pęknięć.',
      'Gotuj knedle partiami w dużym garnku osolonej wody: od wypłynięcia jeszcze 5 minut. Wyjmuj łyżką cedzakową.',
      'Na patelni roztop masło i zrumień w nim bułkę tartą, 2–3 minuty. Podaj knedle polane masłem z bułką i posypane resztą cukru.',
    ],
    photo:
      'Round potato dumplings, one cut open revealing a dark purple plum inside, topped with golden buttery breadcrumbs and a sprinkle of sugar',
  },
  {
    plan: 'ob-99',
    title: 'Kotlety jaglane z warzywami i sosem jogurtowym',
    description:
      'Chrupiące z zewnątrz kotlety z kaszy jaglanej, marchewki, papryki i sera żółtego, podane z sosem jogurtowym z koperkiem. Bezmięsne, ale syte; na zimno też smakują, więc nadają się do pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['kasza jaglana', 130, 'g'],
      ['marchew', 1, 'szt'],
      ['papryka czerwona', 0.5, 'szt'],
      ['cebula', 1, 'szt'],
      ['czosnek', 1, 'szt'],
      ['jajko', 2, 'szt'],
      ['ser żółty', 60, 'g'],
      ['bułka tarta', 40, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['jogurt grecki', 120, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę przepłucz gorącą wodą i ugotuj w 300 ml osolonej wody pod przykryciem 15 minut, aż wchłonie wodę. Przestudź.',
      'Cebulę i paprykę posiekaj drobno, marchew zetrzyj. Podsmaż na 5 ml oleju z przeciśniętym czosnkiem 5 minut, aż zmiękną.',
      'Wymieszaj kaszę z warzywami, jajkami, startym serem, 20 g bułki tartej, posiekaną natką, papryką, solą i pieprzem. Masa ma dać się formować; jeśli jest za luźna, dodaj bułki.',
      'Uformuj 8 kotletów, obtocz je w pozostałej bułce tartej.',
      'Smaż na reszcie oleju na średnim ogniu po 3–4 minuty z każdej strony, aż będą złote i chrupiące.',
      'Jogurt wymieszaj z posiekanym koperkiem i szczyptą soli. Podaj kotlety z sosem jogurtowym.',
    ],
    photo:
      'Golden crispy millet patties with visible bits of carrot and red pepper, a bowl of white yogurt dill sauce on the side',
  },
  {
    plan: 'ob-100',
    title: 'Fasolka szparagowa z bułką tartą, jajkiem i ziemniakami',
    description:
      'Fasolka szparagowa po polsku: ugotowana al dente i polana masłem z zezłoconą bułką tartą i posiekanym jajkiem, z młodymi ziemniakami z koperkiem. Letni, lekki obiad z warzywniaka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['fasolka szparagowa', 600, 'g'],
      ['jajko', 4, 'szt'],
      ['masło', 40, 'g'],
      ['bułka tarta', 40, 'g'],
      ['ziemniak młody', 400, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki wyszoruj i ugotuj w osolonej wodzie w skórce, 15–20 minut.',
      'Jajka ugotuj na twardo (10 minut), ostudź w zimnej wodzie, obierz i posiekaj drobno.',
      'Fasolce obetnij końcówki i gotuj w osolonej wodzie 6–8 minut, aż będzie miękka, ale wciąż jędrna. Odcedź.',
      'Na patelni roztop masło, wsyp bułkę tartą i smaż, mieszając, 2–3 minuty, aż się zezłoci. Zdejmij z ognia i wmieszaj posiekane jajka, szczyptę soli i pieprz.',
      'Podaj fasolkę posypaną masłem z bułką i jajkiem, obok ziemniaki posypane posiekanym koperkiem.',
    ],
    photo:
      'Green beans topped with golden buttered breadcrumbs and chopped hard-boiled egg, young potatoes with fresh dill on the side',
  },
  {
    plan: 'ob-101',
    title: 'Kapusta z grochem i skwarkami',
    description:
      'Kiszona kapusta duszona z rozgotowanym grochem łuskanym, doprawiona majerankiem i okrasą z boczku z cebulką. Tradycyjne danie z polskiej wsi i wigilijnego stołu, gęste i treściwe. Na drugi dzień smakuje jeszcze lepiej.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 120,
    servings: 2,
    ingredients: [
      ['groch łuskany', 150, 'g'],
      ['kapusta kiszona', 300, 'g'],
      ['boczek', 60, 'g'],
      ['cebula', 1, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['kminek', 1, 'g'],
      ['majeranek', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Groch przepłucz i namocz na noc w zimnej wodzie (czas moczenia nie jest wliczony). Odcedź, zalej świeżą wodą i gotuj bez soli 45–60 minut, aż się rozpadnie.',
      'Kapustę lekko odciśnij i posiekaj. Włóż do garnka z liściem laurowym, zielem i kminkiem, zalej 300 ml wody i duś pod przykryciem 40 minut, aż zmięknie.',
      'Boczek pokrój w kostkę i wytop na patelni z olejem na złote skwarki. Dodaj posiekaną cebulę i smaż, aż się zezłoci.',
      'Groch odcedź z nadmiaru wody i wymieszaj z kapustą. Dodaj połowę skwarek z cebulą i majeranek, duś razem 10 minut, mieszając, aż całość zgęstnieje.',
      'Dopraw pieprzem i usuń liść laurowy. Soli zwykle nie trzeba, bo słoność daje kapusta i boczek.',
      'Podaj na talerzach polane resztą skwarek z cebulą.',
    ],
    photo:
      'Thick mixture of sauerkraut and yellow mashed split peas topped with crispy golden bacon bits and fried onion, sprinkled with marjoram',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
