/**
 * Katalog 500 — Przekąski (pr-1 … pr-35), mealType SNACK.
 * Lista: `prisma/catalog/katalog-500-lista.md`, generator: `../katalog-500-2026-09.ts`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'pr-1',
    title: 'Guacamole z nachosami',
    description:
      'Gęsta pasta z dojrzałego awokado z limonką, pomidorem, czerwoną cebulą i kolendrą, do tego chrupiące nachosy. Szybka przekąska na wieczór z filmem albo na stół dla gości.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['awokado', 2, 'szt'],
      ['limonka', 30, 'g'],
      ['pomidor', 1, 'szt'],
      ['cebula czerwona', 30, 'g'],
      ['kolendra', 5, 'g'],
      ['papryczka chili', 5, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 1, 'g'],
      ['chips kukurydziany', 50, 'g'],
    ],
    steps: [
      'Pomidor przekrój, wyjmij łyżeczką gniazda nasienne i pokrój miąższ w kostkę 0,5 cm. Cebulę i chili (bez pestek) posiekaj bardzo drobno, kolendrę posiekaj.',
      'Awokado przekrój, usuń pestki i wyjmij miąższ łyżką do miski.',
      'Rozgnieć awokado widelcem na grubą pastę — małe kawałki mogą zostać. Od razu wlej sok z limonki, żeby pasta nie ściemniała.',
      'Dodaj przeciśnięty przez praskę czosnek, cebulę, chili, pomidor i kolendrę, posól i wymieszaj. Spróbuj i w razie potrzeby dodaj jeszcze limonki.',
      'Przełóż guacamole do miseczki, obłóż nachosami i podawaj od razu, posypane odrobiną kolendry.',
    ],
    photo:
      'Chunky bright green guacamole with diced tomato, red onion and cilantro leaves in the centre, surrounded by golden triangular corn tortilla chips',
    vessel: 'bowl',
  },
  {
    plan: 'pr-2',
    title: 'Nachos zapiekane z serem i salsą',
    description:
      'Chipsy kukurydziane zapieczone pod warstwą roztopionego cheddara, polane świeżą salsą pomidorową i kleksami śmietany. Ciepła, ciągnąca się przekąska do dzielenia na spotkanie przy meczu.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['chips kukurydziany', 70, 'g'],
      ['ser cheddar', 50, 'g'],
      ['pomidor', 1, 'szt'],
      ['cebula czerwona', 30, 'g'],
      ['papryczka chili', 5, 'g'],
      ['kolendra', 5, 'g'],
      ['limonka', 10, 'g'],
      ['sól', 1, 'g'],
      ['śmietana 18', 40, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C z termoobiegiem.',
      'Przygotuj salsę: pomidor pokrój w kostkę 0,5 cm, cebulę i chili (bez pestek) posiekaj drobno, kolendrę posiekaj. Wymieszaj z sokiem z limonki i solą.',
      'Ser cheddar zetrzyj na tarce o grubych oczkach.',
      'Rozłóż nachosy w naczyniu żaroodpornym albo na blasze z papierem, zachodzące na siebie. Posyp połową sera, ułóż drugą warstwę chipsów i posyp resztą sera.',
      'Zapiekaj 5–6 minut, aż ser całkiem się roztopi i zacznie bąbelkować na brzegach.',
      'Od razu wyłóż na chipsy salsę, dodaj kilka kleksów śmietany i podawaj na ciepło, posypane kolendrą.',
    ],
    photo:
      'Golden corn tortilla chips covered with melted orange cheddar, topped with fresh diced tomato salsa, red onion, dollops of sour cream and cilantro',
    vessel: 'board',
  },
  {
    plan: 'pr-3',
    title: 'Frytki z piekarnika z dipem czosnkowym',
    description:
      'Grube frytki pieczone na blasze z odrobiną oleju i papryki — chrupiące z zewnątrz, miękkie w środku. Do maczania gęsty sos czosnkowy na jogurcie greckim.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 2, 'g'],
      ['jogurt grecki', 100, 'g'],
      ['majonez', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['natka pietruszki', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C z termoobiegiem, blachę wyłóż papierem do pieczenia.',
      'Ziemniaki obierz (albo dokładnie wyszoruj) i pokrój w słupki grubości 1 cm. Namocz 10 minut w zimnej wodzie, odcedź i bardzo dokładnie osusz ręcznikiem.',
      'Wymieszaj ziemniaki z olejem, papryką i połową soli. Rozłóż na blasze w jednej warstwie, tak żeby się nie stykały.',
      'Piecz 30–35 minut, po 15 minutach przewróć. Frytki są gotowe, gdy są złote i chrupiące na brzegach.',
      'W czasie pieczenia przygotuj dip: jogurt wymieszaj z majonezem, przeciśniętym czosnkiem, posiekaną natką, pieprzem i szczyptą soli. Odstaw do lodówki.',
      'Frytki posyp resztą soli i podawaj od razu, z miseczką dipu czosnkowego.',
    ],
    photo:
      'Thick golden oven-baked potato fries dusted with paprika, with a small bowl of white garlic yogurt dip sprinkled with chopped parsley',
  },
  {
    plan: 'pr-4',
    title: 'Pieczone skrzydełka BBQ',
    description:
      'Skrzydełka kurczaka pieczone na chrupko z wędzoną papryką, a na koniec glazurowane sosem barbecue z miodem. Lepiące się, słodko-dymne — do jedzenia palcami przy meczu albo na imprezę.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 55,
    servings: 2,
    ingredients: [
      ['skrzydełko z kurczaka', 500, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['papryka wędzona mielona', 2, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sos barbecue', 50, 'g'],
      ['miód', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 210°C z termoobiegiem, blachę wyłóż papierem, a na niej postaw kratkę, jeśli masz.',
      'Skrzydełka osusz ręcznikiem papierowym, rozetnij w stawie na dwie części, końcówki możesz odciąć.',
      'Wymieszaj skrzydełka z olejem, papryką wędzoną, czosnkiem granulowanym, solą i pieprzem. Ułóż na kratce w jednej warstwie.',
      'Piecz 35 minut, w połowie przewracając, aż skórka będzie złota i chrupiąca.',
      'Wymieszaj sos barbecue z miodem. Wyjmij skrzydełka, obtocz w sosie w misce i wróć na blachę na 8–10 minut, aż sos się skarmelizuje i zacznie lepić.',
      'Podawaj od razu na ciepło, z papierowymi serwetkami pod ręką.',
    ],
    photo:
      'Sticky glazed chicken wings coated in dark glossy barbecue sauce with caramelised edges, piled high',
  },
  {
    plan: 'pr-5',
    title: 'Paluszki z ciasta francuskiego z serem',
    description:
      'Skręcone paluszki z ciasta francuskiego z żółtym serem, sezamem i papryką, pieczone na złoto. Chrupią i się łamią, więc znikają z talerza szybciej, niż zdążysz je ostudzić.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 6,
    ingredients: [
      ['ciasto francuskie', 275, 'g'],
      ['ser żółty', 60, 'g'],
      ['jajko', 1, 'szt'],
      ['sezam', 5, 'g'],
      ['papryka słodka mielona', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół), blachę wyłóż papierem. Ser zetrzyj drobno.',
      'Rozwiń ciasto francuskie na papierze, na którym było zwinięte. Jajko roztrzep i posmaruj nim cały płat.',
      'Posyp połowę płata serem i papryką, przykryj drugą połową i mocno dociśnij wałkiem.',
      'Pokrój ciasto w paski szerokości 1,5 cm. Każdy pasek skręć kilka razy jak sprężynkę i ułóż na blasze.',
      'Posmaruj wierzch resztą jajka i posyp sezamem.',
      'Piecz 14–16 minut, aż paluszki będą złote i wyraźnie wyrośnięte. Podawaj lekko przestudzone, same albo z ulubionym dipem.',
    ],
    photo:
      'Golden twisted puff pastry cheese straws sprinkled with sesame seeds and paprika, stacked on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'pr-6',
    title: 'Parówki w cieście francuskim',
    description:
      'Parówki zawinięte spiralnie w paski ciasta francuskiego, posmarowane jajkiem i posypane sezamem. Imprezowa klasyka, którą dzieci jedzą z ketchupem, a dorośli z musztardą.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 6,
    ingredients: [
      ['ciasto francuskie', 275, 'g'],
      ['parówka', 6, 'szt'],
      ['jajko', 1, 'szt'],
      ['sezam', 5, 'g'],
      ['ketchup', 60, 'g'],
      ['musztarda', 20, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół), blachę wyłóż papierem.',
      'Rozwiń ciasto francuskie i pokrój wzdłuż dłuższego boku na 6 pasków szerokości ok. 3 cm.',
      'Parówki osusz ręcznikiem. Każdą owiń spiralnie paskiem ciasta tak, żeby końce parówki wystawały, a zakładki lekko na siebie nachodziły.',
      'Ułóż parówki na blasze łączeniem do dołu, posmaruj roztrzepanym jajkiem i posyp sezamem.',
      'Piecz 18–20 minut, aż ciasto będzie złote i chrupiące.',
      'Podawaj ciepłe, z miseczkami ketchupu i musztardy do maczania.',
    ],
    photo:
      'Golden puff pastry wrapped sausages with spiral pattern and sesame seeds, served with small bowls of ketchup and mustard',
    vessel: 'board',
  },
  {
    plan: 'pr-7',
    title: 'Pizzerinki z ciasta francuskiego z salami',
    description:
      'Małe kwadraty ciasta francuskiego z sosem pomidorowym, mozzarellą, salami i oregano. Smakują jak pizza, a robi się je w pół godziny — dobre na imprezę urodzinową i do pudełka.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 6,
    ingredients: [
      ['ciasto francuskie', 275, 'g'],
      ['passata pomidorowa', 60, 'ml'],
      ['oregano', 1, 'g'],
      ['mozzarella tarta', 100, 'g'],
      ['salami', 50, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół), blachę wyłóż papierem.',
      'Rozwiń ciasto i pokrój na 12 kwadratów. Przełóż je na blachę z odstępami, każdy nakłuj kilka razy widelcem w środku, zostawiając 1 cm wolnego brzegu.',
      'Passatę wymieszaj z oregano i rozsmaruj po łyżeczce na każdym kwadracie, bez brzegów.',
      'Posyp mozzarellą, a salami pokrój w ćwiartki plastrów i ułóż na serze.',
      'Piecz 15–17 minut, aż brzegi urosną i się zezłocą, a ser się roztopi.',
      'Podawaj ciepłe, z listkami świeżej bazylii na wierzchu.',
    ],
    photo:
      'Twelve small square puff pastry pizzas with puffed golden edges, tomato sauce, melted mozzarella, salami pieces and fresh basil leaves',
    vessel: 'board',
  },
  {
    plan: 'pr-8',
    title: 'Chleb czosnkowy z serem',
    description:
      'Bagietka nacięta i przełożona masłem czosnkowym z natką, zapieczona pod ciągnącą się mozzarellą. Pachnie na całe mieszkanie i świetnie pasuje do wieczoru z filmem albo grilla.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 4,
    ingredients: [
      ['bagietka', 250, 'g'],
      ['masło', 50, 'g'],
      ['czosnek', 3, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
      ['mozzarella tarta', 80, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół). Masło wyjmij wcześniej z lodówki, żeby zmiękło.',
      'Czosnek przeciśnij przez praskę, natkę posiekaj drobno. Utrzyj z masłem i solą na gładką pastę.',
      'Bagietkę natnij w poprzek co 2 cm, nie dokrawając do spodu.',
      'Rozsmaruj masło czosnkowe w nacięciach i cienko na wierzchu, a w nacięcia i na górę wsyp mozzarellę.',
      'Owiń bagietkę luźno folią aluminiową, zostawiając odkryty wierzch, i piecz 10 minut, potem odkryj i piecz jeszcze 5 minut, aż ser się zezłoci.',
      'Podawaj od razu, odrywając kromki po nacięciach, posypane resztą natki.',
    ],
    photo:
      'Sliced baguette filled with garlic herb butter and golden melted mozzarella between the cuts, sprinkled with chopped parsley',
    vessel: 'board',
  },
  {
    plan: 'pr-9',
    title: 'Klasyczne jajka faszerowane z musztardą',
    description:
      'Połówki jajek na twardo z kremowym farszem z żółtek, majonezu i musztardy, posypane szczypiorkiem i papryką. Wielkanocna klasyka, która sprawdza się też jako przekąska na każdy dzień.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['jajko', 4, 'szt'],
      ['majonez', 20, 'g'],
      ['musztarda', 10, 'g'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
    ],
    steps: [
      'Jajka włóż do wrzącej wody i gotuj 10 minut, potem przełóż do zimnej wody na 5 minut i obierz.',
      'Przekrój jajka wzdłuż na połówki i ostrożnie wyjmij żółtka do miski.',
      'Rozgnieć żółtka widelcem, dodaj majonez, musztardę, sól i pieprz, utrzyj na gładki krem. Wmieszaj połowę posiekanego szczypiorku.',
      'Nałóż farsz łyżeczką albo szprycą z powrotem do białek, formując kopczyki.',
      'Posyp resztą szczypiorku i szczyptą papryki, schłodź chwilę w lodówce i podawaj.',
    ],
    photo:
      'Eight deviled egg halves with piped pale yellow mustard filling, dusted with red paprika and chopped chives',
  },
  {
    plan: 'pr-10',
    title: 'Tzatziki z warzywami do maczania',
    description:
      'Gęsty sos z jogurtu greckiego z tartym ogórkiem, czosnkiem i koperkiem, do tego chrupiące słupki marchewki, papryki, selera i ogórka. Lekka, orzeźwiająca przekąska, która dobrze znosi pudełko.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['jogurt grecki', 200, 'g'],
      ['ogórek', 1, 'szt'],
      ['czosnek', 1, 'szt'],
      ['koperek', 5, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['marchew', 2, 'szt'],
      ['papryka czerwona', 1, 'szt'],
      ['seler naciowy', 100, 'g'],
    ],
    steps: [
      'Odetnij połowę ogórka i zetrzyj ją na tarce o grubych oczkach. Posól szczyptą soli, odstaw na 5 minut i mocno odciśnij z soku w dłoniach.',
      'Jogurt wymieszaj z odciśniętym ogórkiem, przeciśniętym czosnkiem, posiekanym koperkiem, pieprzem i resztą soli.',
      'Przełóż tzatziki do miseczki i polej oliwą. Schłodź w lodówce przynajmniej 10 minut, żeby smaki się połączyły.',
      'Marchew obierz, a marchew, paprykę, seler naciowy i drugą połowę ogórka pokrój w słupki długości ok. 8 cm.',
      'Podawaj tzatziki w miseczce na środku, otoczone słupkami warzyw do maczania.',
    ],
    photo:
      'A bowl of thick white tzatziki with grated cucumber, dill and a drizzle of olive oil, surrounded by carrot, red pepper, celery and cucumber sticks',
  },
  {
    plan: 'pr-11',
    title: 'Prażona ciecierzyca z papryką',
    description:
      'Ciecierzyca z puszki upieczona na chrupko z wędzoną papryką, czosnkiem i kuminem. Słona, sycąca i pełna białka — zdrowsza alternatywa chipsów, dobra do chrupania przy pracy.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['ciecierzyca z puszki', 240, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C z termoobiegiem, blachę wyłóż papierem.',
      'Ciecierzycę odcedź, przepłucz i bardzo dokładnie osusz ręcznikiem — zdejmij przy tym luźne skórki. Im suchsza, tym bardziej chrupie.',
      'Rozłóż ciecierzycę na blasze i piecz 20 minut bez przypraw.',
      'Wymieszaj oliwę z papryką, czosnkiem, kuminem i solą, polej nią ciecierzycę na blasze i dokładnie obtocz.',
      'Piecz jeszcze 12–15 minut, potrząsając blachą w połowie, aż ziarna będą złote i suche w środku.',
      'Ostudź na blasze — dopiero wtedy stają się naprawdę chrupiące. Podawaj w miseczce.',
    ],
    photo:
      'Crunchy roasted chickpeas coated in red smoked paprika, piled in a small bowl with a few scattered around',
    vessel: 'bowl',
  },
  {
    plan: 'pr-12',
    title: 'Pieczone paluszki z mozzarelli z sosem pomidorowym',
    description:
      'Słupki mozzarelli w podwójnej panierce, pieczone zamiast smażenia — chrupiące na zewnątrz, ciągnące się w środku. Podane z ciepłym sosem pomidorowym do maczania.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['mozzarella', 150, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 40, 'g'],
      ['oregano', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['sos pomidorowy', 80, 'g'],
    ],
    steps: [
      'Mozzarellę w kostce pokrój w słupki grubości ok. 1,5 cm.',
      'Przygotuj trzy talerze: z mąką, z roztrzepanym jajkiem i z bułką tartą wymieszaną z oregano i papryką.',
      'Obtocz każdy słupek w mące, jajku i bułce, a potem jeszcze raz w jajku i bułce — podwójna panierka nie pozwoli serowi wyciec.',
      'Ułóż paluszki na talerzu i zamroź na 30 minut. W tym czasie nagrzej piekarnik do 220°C z termoobiegiem.',
      'Przełóż paluszki na blachę z papierem, skrop olejem i piecz 7–9 minut, aż panierka się zezłoci, a ser zacznie mięknąć.',
      'Sos pomidorowy podgrzej w rondelku. Podawaj paluszki od razu, z miseczką ciepłego sosu.',
    ],
    photo:
      'Golden breaded mozzarella sticks, one pulled apart showing stretchy melted cheese, with a small bowl of red tomato dipping sauce',
  },
  {
    plan: 'pr-13',
    title: 'Koreczki z serem, szynką i ogórkiem',
    description:
      'Kolorowe koreczki na wykałaczkach: kostki żółtego sera, zwinięta szynka, ogórek konserwowy i pomidorki koktajlowe. Przekąska na zimno bez gotowania, gotowa w dziesięć minut na każde przyjęcie.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['ser żółty', 100, 'g'],
      ['szynka', 100, 'g'],
      ['ogórek konserwowy', 100, 'g'],
      ['pomidor koktajlowy', 100, 'g'],
    ],
    steps: [
      'Ser żółty w bloku pokrój w kostki ok. 2 cm.',
      'Ogórki konserwowe osusz i pokrój w grube plastry, pomidorki koktajlowe przekrój na pół.',
      'Plastry szynki przekrój wzdłuż na paski i każdy zwiń w ciasny rulonik albo złóż w harmonijkę.',
      'Nabijaj na wykałaczki kolejno: pomidorek, szynkę, ogórek i na koniec kostkę sera jako podstawę.',
      'Ustaw koreczki na desce serem do dołu i podawaj od razu albo schłodzone.',
    ],
    photo:
      'Party skewers with yellow cheese cubes, rolled ham, pickled cucumber slices and halved cherry tomatoes standing upright',
    vessel: 'board',
  },
  {
    plan: 'pr-14',
    title: 'Ślimaczki z tortilli z serkiem i szpinakiem',
    description:
      'Tortille posmarowane serkiem kremowym z czosnkiem, wyłożone świeżym szpinakiem, zwinięte i pokrojone w plastry. Zimna przekąska bez gotowania, którą łatwo zrobić wcześniej i zabrać w pudełku.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['serek kremowy', 100, 'g'],
      ['czosnek', 1, 'szt'],
      ['pieprz czarny', 1, 'g'],
      ['szpinak', 50, 'g'],
    ],
    steps: [
      'Serek kremowy wymieszaj z przeciśniętym czosnkiem i pieprzem.',
      'Szpinak umyj i bardzo dokładnie osusz, większe liście porwij.',
      'Rozsmaruj serek równą warstwą na obu tortillach, aż do brzegów.',
      'Wyłóż szpinak na serek, zostawiając 2 cm wolnego brzegu, i ciasno zwiń każdą tortillę w rulon.',
      'Owiń rulony folią spożywczą i schłodź 30 minut w lodówce, żeby się związały.',
      'Odetnij nierówne końce i pokrój rulony ostrym nożem w plastry grubości 2 cm. Podawaj ułożone przekrojem do góry.',
    ],
    photo:
      'Round tortilla pinwheels with white cream cheese and green spinach swirls, arranged cut side up in rows',
    vessel: 'board',
  },
  {
    plan: 'pr-15',
    title: 'Pieczone krążki cebulowe z ketchupem',
    description:
      'Grube plastry cebuli w chrupiącej panierce z bułki tartej, pieczone w piekarniku zamiast w głębokim tłuszczu. Słodkie w środku, złote z zewnątrz, z ketchupem do maczania.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['cebula', 2, 'szt'],
      ['mąka pszenna', 30, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 50, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['ketchup', 40, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C z termoobiegiem, blachę wyłóż papierem.',
      'Cebule obierz i pokrój w plastry grubości 1 cm, rozdziel na pojedyncze krążki (najmniejsze środki zostaw na inny dzień).',
      'Mąkę wymieszaj z solą, jajko roztrzep, a bułkę tartą wymieszaj z papryką i olejem, aż będzie wilgotna jak mokry piasek.',
      'Obtaczaj każdy krążek kolejno w mące, jajku i bułce, dociskając panierkę palcami.',
      'Ułóż krążki na blasze w jednej warstwie i piecz 15–18 minut, przewracając po 10 minutach, aż będą złote i chrupiące.',
      'Podawaj od razu, z miseczką ketchupu.',
    ],
    photo:
      'Golden crispy breaded onion rings stacked loosely, with a small bowl of red ketchup on the side',
  },
  {
    plan: 'pr-16',
    title: 'Chipsy z jarmużu z papryką',
    description:
      'Liście jarmużu upieczone na cienkie, kruche płatki z oliwą, solą i odrobiną czosnku. Rozpadają się w ustach jak chipsy, a są prawie samą zieleniną — przekąska do chrupania bez wyrzutów.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['jarmuż', 150, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 1, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 150°C z termoobiegiem, dwie blachy wyłóż papierem.',
      'Jarmuż umyj i bardzo dokładnie osusz — mokre liście zamiast chrupać, będą się dusić. Wytnij twarde łodygi, liście porwij na kawałki wielkości chipsów.',
      'Wmasuj w liście oliwę dłońmi, tak żeby każdy był cienko pokryty, i posyp czosnkiem oraz papryką.',
      'Rozłóż jarmuż na blachach w jednej warstwie, bez nakładania.',
      'Piecz 15–20 minut, obracając blachy w połowie. Chipsy są gotowe, gdy są suche i szeleszczą, zanim zaczną brązowieć.',
      'Posyp solą dopiero po upieczeniu i podawaj od razu w misce.',
    ],
    photo:
      'Crispy dark green baked kale chips lightly dusted with paprika and sea salt, piled in a bowl',
    vessel: 'bowl',
  },
  {
    plan: 'pr-17',
    title: 'Mini szaszłyki caprese',
    description:
      'Pomidorki koktajlowe, kawałki mozzarelli i listki bazylii na wykałaczkach, skropione oliwą i octem balsamicznym. Włoskie połączenie w wersji na jeden kęs — szybkie, kolorowe i zawsze znika pierwsze.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['pomidor koktajlowy', 200, 'g'],
      ['mozzarella', 125, 'g'],
      ['bazylia', 10, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['ocet balsamiczny', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Mozzarellę odsącz z zalewy, osusz i pokrój w kostkę ok. 2 cm.',
      'Pomidorki koktajlowe umyj i osusz, większe przekrój na pół.',
      'Nabijaj na wykałaczki kolejno pomidorek, listek bazylii i kostkę mozzarelli.',
      'Ułóż szaszłyki na talerzu, posól i popieprz.',
      'Tuż przed podaniem skrop oliwą i octem balsamicznym, udekoruj resztą bazylii.',
    ],
    photo:
      'Mini caprese skewers with red cherry tomatoes, white mozzarella cubes and fresh basil leaves, drizzled with olive oil and dark balsamic',
  },
  {
    plan: 'pr-18',
    title: 'Koktajl zielony ze szpinakiem, jabłkiem i bananem',
    description:
      'Gładki, jasnozielony koktajl ze świeżego szpinaku, słodkiego jabłka i banana z nutą cytryny. Szpinaku prawie nie czuć, za to jest orzeźwiająco — dobry na popołudniowy spadek energii.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    ingredients: [
      ['szpinak', 50, 'g'],
      ['jabłko', 1, 'szt'],
      ['banan', 1, 'szt'],
      ['cytryna', 10, 'g'],
    ],
    steps: [
      'Szpinak dokładnie umyj. Jabłko umyj, usuń gniazdo nasienne i pokrój w ćwiartki (skórkę możesz zostawić).',
      'Banana obierz i połam na kawałki.',
      'Włóż do blendera szpinak, jabłko, banana, sok z cytryny i wodę (200 ml).',
      'Miksuj ok. 1 minuty na najwyższych obrotach, aż koktajl będzie całkiem gładki, bez widocznych kawałków liści.',
      'Rozlej do dwóch szklanek i wypij od razu, póki jest jasnozielony i świeży.',
    ],
    photo:
      'Smooth bright green spinach, apple and banana smoothie filling the vessel, garnished with a thin apple slice and a small spinach leaf',
    vessel: 'bowl',
  },
  {
    plan: 'pr-19',
    title: 'Batoniki owsiane z bakaliami',
    description:
      'Domowe batoniki z płatków owsianych, miodu i masła z rodzynkami, morelami, żurawiną i orzechami. Chrupiące na brzegach, lekko ciągnące w środku — do plecaka, na wycieczkę i do biura.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 8,
    ingredients: [
      ['płatki owsiane', 200, 'g'],
      ['miód', 80, 'g'],
      ['masło', 50, 'g'],
      ['rodzynka', 40, 'g'],
      ['morela suszona', 40, 'g'],
      ['żurawina suszona', 30, 'g'],
      ['orzech włoski', 40, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 170°C (góra-dół). Formę ok. 20 × 20 cm wyłóż papierem do pieczenia.',
      'Morele pokrój w paski, orzechy posiekaj grubo.',
      'W rondelku rozpuść masło z miodem na małym ogniu, aż się połączą — nie gotuj.',
      'W misce wymieszaj płatki, rodzynki, morele, żurawinę, orzechy i cynamon. Wlej masło z miodem i mieszaj, aż wszystkie płatki będą oblepione.',
      'Przełóż masę do formy i mocno dociśnij łyżką albo dnem szklanki, żeby była zbita i równa.',
      'Piecz 20–25 minut, aż brzegi będą złotobrązowe. Wystudź całkowicie w formie (ok. 30 minut), dopiero wtedy pokrój ostrym nożem na 8 batoników i podawaj.',
    ],
    photo:
      'Golden baked oat bars with visible raisins, dried apricot pieces, red cranberries and walnuts, cut into rectangles and stacked',
    vessel: 'board',
  },
  {
    plan: 'pr-20',
    title: 'Orzechy prażone w miodzie',
    description:
      'Mieszanka orzechów włoskich, laskowych i migdałów prażona na patelni w miodzie z masłem, cynamonem i szczyptą soli. Słodko-słone, chrupiące — na zimowe popołudnie albo do słoika na prezent.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    ingredients: [
      ['orzech włoski', 50, 'g'],
      ['orzech laskowy', 50, 'g'],
      ['migdał', 50, 'g'],
      ['masło', 10, 'g'],
      ['miód', 30, 'g'],
      ['cynamon', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Przygotuj arkusz papieru do pieczenia rozłożony na blacie.',
      'Wsyp orzechy i migdały na suchą patelnię i praż na średnim ogniu 5–6 minut, często mieszając, aż zaczną pachnieć.',
      'Dodaj masło, a gdy się rozpuści, wlej miód i wsyp cynamon. Mieszaj bez przerwy 2–3 minuty, aż miód zacznie się karmelizować i oblepi orzechy.',
      'Od razu przełóż orzechy na papier, rozdziel łyżką na pojedyncze sztuki i posyp solą.',
      'Zostaw do całkowitego wystygnięcia (ok. 10 minut), aż karmel stwardnieje. Podawaj w miseczce albo przechowuj w szczelnym słoiku.',
    ],
    photo:
      'Glossy honey roasted walnuts, hazelnuts and almonds with a caramelised coating and flakes of salt, piled in a small bowl',
    vessel: 'bowl',
  },
  {
    plan: 'pr-21',
    title: 'Mini pizze z cukinii',
    description:
      'Grube plastry cukinii zapieczone jak pizzerki: z passatą, mozzarellą, oregano i bazylią. Lekka, ciepła przekąska bez ciasta, gotowa w dwadzieścia minut.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['cukinia', 350, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['passata pomidorowa', 60, 'ml'],
      ['oregano', 1, 'g'],
      ['mozzarella tarta', 80, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C z termoobiegiem, blachę wyłóż papierem.',
      'Cukinię pokrój ukośnie w plastry grubości 1 cm, żeby były jak największe. Osusz ręcznikiem.',
      'Ułóż plastry na blasze, posmaruj oliwą, posól i popieprz. Podpiecz 8 minut, aż lekko zmiękną.',
      'Passatę wymieszaj z oregano i nałóż po łyżeczce na każdy plaster, posyp mozzarellą.',
      'Zapiekaj 6–8 minut, aż ser się roztopi i zacznie rumienić.',
      'Podawaj od razu, z listkami bazylii na wierzchu.',
    ],
    photo:
      'Round zucchini slices topped with tomato sauce and bubbling golden melted mozzarella, garnished with fresh basil leaves',
  },
  {
    plan: 'pr-22',
    title: 'Chipsy z buraka z tymiankiem',
    description:
      'Cieniutkie plasterki buraka suszone w piekarniku na chrupiące, rubinowe chipsy z tymiankiem i solą. Lekko słodkie i ziemiste — ładnie wyglądają w misce na stole.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['burak', 400, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['tymianek suszony', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 150°C z termoobiegiem, dwie blachy wyłóż papierem.',
      'Buraki obierz (najlepiej w rękawiczkach) i pokrój na mandolinie albo ostrym nożem w plasterki grubości 1–2 mm.',
      'Osusz plasterki ręcznikiem papierowym, wymieszaj z oliwą i tymiankiem.',
      'Rozłóż je na blachach w jednej warstwie, bez nakładania.',
      'Piecz 35–45 minut, zamieniając blachy w połowie. Wyjmuj plasterki, które są już suche i pofalowane na brzegach — dopieczone chipsy chrupią dopiero po ostudzeniu.',
      'Posyp solą, ostudź na blasze 10 minut i podawaj w misce.',
    ],
    photo:
      'Thin crispy deep ruby red beetroot chips with curled edges, sprinkled with dried thyme and sea salt',
    vessel: 'bowl',
  },
  {
    plan: 'pr-23',
    title: 'Wytrawne muffinki z serem i szynką',
    description:
      'Puszyste wytrawne muffinki z kawałkami szynki, żółtym serem i szczypiorkiem. Dobre na ciepło i na zimno — do pudełka, na piknik albo zamiast kanapki do pracy.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 6,
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 180, 'ml'],
      ['olej rzepakowy', 60, 'ml'],
      ['ser żółty', 80, 'g'],
      ['szynka', 80, 'g'],
      ['szczypiorek', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra-dół), formę na 12 muffinek wyłóż papilotkami.',
      'Ser zetrzyj na tarce o grubych oczkach (garść zostaw do posypania), szynkę pokrój w kostkę 0,5 cm, szczypiorek posiekaj.',
      'W jednej misce wymieszaj mąkę, proszek do pieczenia, sól i pieprz. W drugiej roztrzep jajka z mlekiem i olejem.',
      'Wlej mokre składniki do suchych i wymieszaj łyżką tylko do połączenia — grudki mogą zostać. Wmieszaj ser, szynkę i szczypiorek.',
      'Nałóż ciasto do papilotek do 3/4 wysokości, posyp resztą sera.',
      'Piecz 20–22 minuty, aż muffinki urosną i się zezłocą, a patyczek wbity w środek wyjdzie suchy. Podawaj ciepłe albo ostudzone, po dwie na porcję.',
    ],
    photo:
      'Golden savory muffins with melted cheese tops and visible ham cubes and chives, one broken open showing a fluffy crumb',
    vessel: 'board',
  },
  {
    plan: 'pr-24',
    title: 'Pierożki z ciasta francuskiego ze szpinakiem i fetą',
    description:
      'Chrupiące trójkąty z ciasta francuskiego z farszem ze szpinaku, czosnku i słonej fety. Smakują jak greckie spanakopita, a robi się je z gotowego ciasta — na ciepło i na zimno.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 6,
    ingredients: [
      ['szpinak', 200, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['czosnek', 2, 'szt'],
      ['ser feta', 100, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['ciasto francuskie', 275, 'g'],
      ['jajko', 1, 'szt'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół), blachę wyłóż papierem.',
      'Na patelni rozgrzej oliwę, dodaj posiekany czosnek i szpinak. Duś 3–4 minuty, aż liście zwiędną, a woda odparuje. Przełóż na sitko, odciśnij i ostudź.',
      'Szpinak posiekaj, wymieszaj z pokruszoną fetą i pieprzem. Soli nie dodawaj — feta jest wystarczająco słona.',
      'Rozwiń ciasto i pokrój na 12 kwadratów. Na każdy nałóż łyżkę farszu, złóż po przekątnej w trójkąt i dokładnie zlep brzegi widelcem.',
      'Ułóż pierożki na blasze, posmaruj roztrzepanym jajkiem i natnij każdy nożem na wierzchu.',
      'Piecz 18–20 minut, aż będą złote i wyrośnięte. Podawaj ciepłe, po dwa na porcję.',
    ],
    photo:
      'Golden flaky puff pastry triangles with fork-crimped edges, one cut open showing a green spinach and white feta filling',
    vessel: 'board',
  },
  {
    plan: 'pr-25',
    title: 'Bułeczki serowe z twarogiem',
    description:
      'Szybkie bułeczki na proszku do pieczenia z twarogiem i żółtym serem, bez czekania na drożdże. Miękkie w środku, z rumianą serową skórką — do zupy, na śniadanie albo do pudełka.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 8,
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['sól', 3, 'g'],
      ['masło', 40, 'g'],
      ['ser twaróg półtłusty', 200, 'g'],
      ['ser żółty', 80, 'g'],
      ['mleko', 50, 'ml'],
      ['jajko', 1, 'szt'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół), blachę wyłóż papierem.',
      'W misce wymieszaj mąkę, proszek do pieczenia i sól. Dodaj zimne masło pokrojone w kostkę i rozetrzyj palcami na kruszonkę.',
      'Ser żółty zetrzyj na grubych oczkach, 2 łyżki odłóż. Do miski dodaj twaróg, resztę żółtego sera, mleko i połowę roztrzepanego jajka.',
      'Szybko zagnieć miękkie ciasto — tylko do połączenia, żeby bułeczki nie wyszły twarde.',
      'Podziel ciasto na 8 części, uformuj kulki i ułóż na blasze w odstępach. Posmaruj resztą jajka i posyp odłożonym serem.',
      'Piecz 20–22 minuty, aż będą złote i puste w środku przy opukaniu spodu. Podawaj ciepłe, same albo z masłem.',
    ],
    photo:
      'Eight round golden cheese buns with crispy melted cheese tops, one torn open showing a soft white crumb',
    vessel: 'board',
  },
  {
    plan: 'pr-26',
    title: 'Salsa z mango z chipsami z tortilli',
    description:
      'Soczysta salsa z mango, pomidora, czerwonej cebuli, chili i kolendry z sokiem z limonki, do tego domowe chipsy z pieczonej tortilli. Słodko-ostra, świeża przekąska na letnie popołudnie.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 1, 'g'],
      ['mango', 1, 'szt'],
      ['pomidor', 1, 'szt'],
      ['cebula czerwona', 40, 'g'],
      ['papryczka chili', 5, 'g'],
      ['kolendra', 10, 'g'],
      ['limonka', 20, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C z termoobiegiem. Tortille posmaruj cienko oliwą, pokrój każdą na 8 trójkątów i rozłóż na blasze z papierem.',
      'Piecz 7–9 minut, aż trójkąty będą złote i sztywne. Posyp połową soli i ostudź — stwardnieją jeszcze bardziej.',
      'Mango obierz, odkrój miąższ od pestki i pokrój w kostkę 1 cm. Pomidor pokrój w podobną kostkę, odrzucając gniazda nasienne.',
      'Cebulę i chili (bez pestek) posiekaj drobno, kolendrę posiekaj.',
      'Wymieszaj mango, pomidor, cebulę, chili i kolendrę z sokiem z limonki i resztą soli. Odstaw na 5 minut, żeby puściła sok.',
      'Podawaj salsę w miseczce z chipsami z tortilli do nabierania.',
    ],
    photo:
      'A bowl of colorful mango salsa with orange mango cubes, red tomato, red onion and green cilantro, with golden baked tortilla chips around it',
    vessel: 'bowl',
  },
  {
    plan: 'pr-27',
    title: 'Pasta z pieczonego bakłażana z pitą',
    description:
      'Kremowa, dymna pasta z upieczonego bakłażana z tahini, czosnkiem i cytryną, w stylu baba ganoush. Podana z ciepłą pitą — sycąca przekąska, która świetnie trzyma się w lodówce.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['bakłażan', 1, 'szt'],
      ['tahini', 25, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['kmin rzymski', 1, 'g'],
      ['sól', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['pita', 2, 'szt'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C (góra-dół). Bakłażana nakłuj widelcem w kilku miejscach i połóż na blasze.',
      'Piecz 40–45 minut, obracając w połowie, aż skórka się pomarszczy i przypali, a miąższ zrobi się zupełnie miękki.',
      'Przekrój bakłażana, wyjmij miąższ łyżką na sitko i odstaw na 5 minut, żeby odciekł gorzki sok.',
      'Rozgnieć miąższ widelcem albo krótko zmiksuj z tahini, przeciśniętym czosnkiem, sokiem z cytryny, kuminem, solą i połową oliwy.',
      'Pitę podgrzej 2 minuty w gorącym piekarniku i pokrój w trójkąty.',
      'Przełóż pastę do miseczki, zrób łyżką zagłębienie, polej resztą oliwy i posyp natką. Podawaj z ciepłą pitą.',
    ],
    photo:
      'Creamy smoky grey-beige eggplant dip with a swirl of olive oil and chopped parsley, served with warm pita triangles',
    vessel: 'bowl',
  },
  {
    plan: 'pr-28',
    title: 'Edamame z czosnkiem i chili',
    description:
      'Strączki edamame obsmażone na oleju sezamowym z czosnkiem, sosem sojowym i płatkami chili. Wyciska się je zębami prosto ze strączków — zabawna, białkowa przekąska gotowa w dziesięć minut.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['edamame', 250, 'g'],
      ['sól', 1, 'g'],
      ['olej sezamowy', 5, 'ml'],
      ['czosnek', 3, 'szt'],
      ['sos sojowy', 10, 'ml'],
      ['płatki chili', 1, 'g'],
    ],
    steps: [
      'Zagotuj wodę z połową soli, wrzuć mrożone edamame i gotuj 4–5 minut. Odcedź i osusz.',
      'Czosnek posiekaj drobno.',
      'Na dużej patelni rozgrzej olej sezamowy, wrzuć czosnek i smaż 30 sekund, aż zacznie pachnieć — nie przypal go.',
      'Dodaj edamame, sos sojowy i płatki chili, smaż 2 minuty, mieszając, aż strączki się błyszczą i lekko przypieką.',
      'Przełóż do miski, posyp resztą soli i podawaj na ciepło, z drugą miseczką na puste strączki.',
    ],
    photo:
      'Glossy bright green edamame pods tossed with golden minced garlic and red chili flakes, piled in a bowl',
    vessel: 'bowl',
  },
  {
    plan: 'pr-29',
    title: 'Camembert z piekarnika z żurawiną',
    description:
      'Cały krążek camemberta zapieczony, aż środek zrobi się płynny, podany z sosem żurawinowym, miodem, orzechami i grzankami z bagietki. Przekąska na zimowy wieczór we dwoje.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['ser camembert', 120, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['sos żurawinowy', 40, 'g'],
      ['miód', 10, 'g'],
      ['orzech włoski', 15, 'g'],
      ['bagietka', 100, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra-dół).',
      'Camembert wyjmij z opakowania, połóż w małym naczyniu żaroodpornym albo na papierze. Natnij wierzch w kratkę na głębokość 3 mm i posyp tymiankiem.',
      'Piecz 12–15 minut, aż ser będzie miękki i wypukły, a środek płynny przy dotknięciu.',
      'W tym czasie pokrój bagietkę w ukośne kromki grubości 1 cm i opiecz je na blasze obok sera przez ostatnie 6 minut. Orzechy posiekaj grubo.',
      'Na gorący ser wyłóż sos żurawinowy, skrop miodem i posyp orzechami.',
      'Podawaj od razu, z grzankami do nabierania roztopionego sera.',
    ],
    photo:
      'Whole baked camembert with scored golden top, topped with red cranberry sauce, honey and chopped walnuts, surrounded by toasted baguette slices',
    vessel: 'board',
  },
  {
    plan: 'pr-30',
    title: 'Paluszki z cukinii w panierce z dipem jogurtowym',
    description:
      'Słupki cukinii w chrupiącej panierce z bułki tartej i parmezanu, pieczone na złoto. Do maczania czosnkowy dip jogurtowy — przekąska, po którą chętnie sięgają nawet przeciwnicy warzyw.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['cukinia', 400, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 50, 'g'],
      ['ser parmezan', 20, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['sól', 1, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['jogurt grecki', 100, 'g'],
      ['czosnek', 1, 'szt'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C z termoobiegiem, blachę wyłóż papierem.',
      'Cukinię pokrój w słupki 1 × 1 × 8 cm i dokładnie osusz ręcznikiem papierowym.',
      'Na trzech talerzach przygotuj: mąkę z solą, roztrzepane jajko i bułkę tartą wymieszaną z drobno startym parmezanem i czosnkiem granulowanym.',
      'Obtaczaj słupki kolejno w mące, jajku i panierce, układaj na blasze w odstępach i skrop oliwą.',
      'Piecz 18–20 minut, przewracając w połowie, aż panierka będzie złota i chrupiąca.',
      'Jogurt wymieszaj z przeciśniętym czosnkiem i szczyptą soli. Podawaj paluszki gorące, z dipem w miseczce.',
    ],
    photo:
      'Golden breaded zucchini fries with parmesan crust, stacked on a plate with a small bowl of white garlic yogurt dip',
  },
  {
    plan: 'pr-31',
    title: 'Domowe krakersy serowe',
    description:
      'Kruche, maślane krakersy z dużą ilością cheddara i szczyptą papryki, wykrawane w małe kwadraciki. Pachną serem, chrupią jak ze sklepu i dobrze trzymają się w puszce przez tydzień.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 6,
    ingredients: [
      ['ser cheddar', 100, 'g'],
      ['mąka pszenna', 150, 'g'],
      ['masło', 60, 'g'],
      ['sól', 2, 'g'],
      ['papryka słodka mielona', 1, 'g'],
    ],
    steps: [
      'Ser cheddar zetrzyj drobno. Masło pokrój w kostkę i trzymaj w lodówce do ostatniej chwili.',
      'W misce albo w malakserze połącz mąkę, sól, paprykę, ser i zimne masło, aż powstanie kruszonka.',
      'Dodawaj stopniowo zimną wodę (ok. 30 ml), łyżka po łyżce, i zagnieć krótko gładkie ciasto. Owiń folią i schłódź 20 minut.',
      'Nagrzej piekarnik do 180°C (góra-dół), blachy wyłóż papierem.',
      'Rozwałkuj ciasto na grubość 3 mm, pokrój radełkiem w kwadraty 3 × 3 cm i ułóż na blachach. Każdy nakłuj na środku patyczkiem.',
      'Piecz 12–15 minut, aż brzegi się zezłocą. Ostudź na kratce — krakersy chrupią po wystygnięciu. Podawaj w miseczce.',
    ],
    photo:
      'Small square golden-orange cheese crackers with a hole in the middle, piled loosely on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'pr-32',
    title: 'Roladki z grillowanej cukinii z serkiem',
    description:
      'Cienkie plastry cukinii podsmażone na patelni grillowej, posmarowane serkiem z czosnkiem i bazylią, zwinięte z suszonym pomidorem. Elegancka, a prosta przekąska na zimno.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['cukinia', 300, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 1, 'g'],
      ['serek kremowy', 100, 'g'],
      ['czosnek', 1, 'szt'],
      ['bazylia', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['pomidor suszony w oleju', 30, 'g'],
    ],
    steps: [
      'Cukinię pokrój wzdłuż obieraczką albo nożem w plastry grubości 3 mm (wyjdzie ok. 10–12 pasków). Posmaruj je cienko oliwą i posól.',
      'Rozgrzej patelnię grillową i smaż plastry po 1–2 minuty z każdej strony, aż będą miękkie i z wyraźnymi paskami. Ostudź na talerzu.',
      'Serek wymieszaj z przeciśniętym czosnkiem, posiekaną bazylią (kilka listków zostaw) i pieprzem.',
      'Pomidory suszone odsącz z oleju i pokrój w cienkie paski.',
      'Każdy plaster cukinii posmaruj serkiem, na jednym końcu połóż pasek pomidora i ciasno zwiń.',
      'Ustaw roladki na talerzu, spinając wykałaczką te, które się rozwijają, i podawaj z listkami bazylii.',
    ],
    photo:
      'Grilled zucchini roll-ups with char marks, filled with white cream cheese and sun-dried tomato strips, garnished with basil leaves',
  },
  {
    plan: 'pr-33',
    title: 'Chipsy jabłkowe z piekarnika z cynamonem',
    description:
      'Cieniutkie plasterki jabłek suszone powoli w piekarniku z cynamonem, aż zrobią się chrupiące. Naturalnie słodkie, bez cukru — przekąska dla dzieci i do pracy zamiast ciastek.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 150,
    servings: 2,
    ingredients: [
      ['jabłko', 3, 'szt'],
      ['cytryna', 10, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 100°C z termoobiegiem, dwie blachy wyłóż papierem.',
      'Jabłka umyj, wytnij gniazda nasienne wykrawaczem albo nożem i pokrój w poprzek na plasterki grubości 1–2 mm (najlepiej na mandolinie).',
      'Skrop plasterki sokiem z cytryny, żeby nie ściemniały, i rozłóż na blachach w jednej warstwie. Oprósz cynamonem przez sitko.',
      'Susz 1,5–2 godziny, przewracając plasterki po godzinie. Drzwiczki piekarnika możesz uchylić łyżką, żeby uchodziła para.',
      'Wyłącz piekarnik i zostaw chipsy w środku na 15 minut, aż całkiem wyschną — po wystygnięciu mają chrupać.',
      'Podawaj w misce albo przechowuj w szczelnym słoiku do tygodnia.',
    ],
    photo:
      'Thin crispy round apple chips with a star-shaped core pattern, lightly dusted with cinnamon, piled in a bowl',
    vessel: 'bowl',
  },
  {
    plan: 'pr-34',
    title: 'Koktajl kefirowy z jagodami',
    description:
      'Fioletowy koktajl z kefiru i jagód, lekko dosłodzony miodem. Kwaskowaty, orzeźwiający i sycący — dobry na upalne popołudnie albo po treningu.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    ingredients: [
      ['kefir', 400, 'ml'],
      ['jagoda', 150, 'g'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Jagody przebierz i opłucz na sitku (możesz użyć mrożonych — koktajl będzie od razu zimny). Kilka odłóż do dekoracji.',
      'Włóż jagody do blendera, dodaj miód i wlej schłodzony kefir.',
      'Miksuj ok. 30 sekund, aż koktajl będzie gładki i jednolicie fioletowy.',
      'Spróbuj i jeśli jagody były kwaśne, dodaj odrobinę miodu i zmiksuj jeszcze raz.',
      'Rozlej do dwóch szklanek, na wierzch wrzuć odłożone jagody i podawaj od razu.',
    ],
    photo:
      'Thick purple blueberry kefir smoothie topped with a few whole fresh blueberries',
    vessel: 'bowl',
  },
  {
    plan: 'pr-35',
    title: 'Mini klopsiki z indyka z dipem jogurtowym',
    description:
      'Małe, soczyste klopsiki z mielonego indyka z majerankiem, pieczone w piekarniku, podane z chłodnym dipem z jogurtu, ogórka i koperku. Białkowa przekąska na wykałaczkach, dobra też do pudełka.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['indyk mielony', 250, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 30, 'g'],
      ['cebula', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['majeranek', 1, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['ogórek', 80, 'g'],
      ['koperek', 5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C z termoobiegiem, blachę wyłóż papierem i posmaruj połową oleju.',
      'Cebulę zetrzyj na drobnych oczkach, czosnek przeciśnij przez praskę.',
      'W misce wymieszaj indyka z jajkiem, bułką tartą, cebulą, czosnkiem, majerankiem, połową soli i pieprzem. Wyrabiaj ręką 2 minuty, aż masa się zwiąże.',
      'Wilgotnymi dłońmi formuj kulki wielkości orzecha włoskiego (ok. 20 sztuk), ułóż na blasze i skrop resztą oleju.',
      'Piecz 15–18 minut, przewracając w połowie, aż klopsiki się zrumienią i w środku nie będą już różowe.',
      'Ogórek zetrzyj na grubych oczkach i odciśnij, wymieszaj z jogurtem, posiekanym koperkiem i resztą soli. Podawaj klopsiki na wykałaczkach z dipem w miseczce.',
    ],
    photo:
      'Small golden-brown turkey meatballs on toothpicks next to a bowl of creamy white yogurt dip with grated cucumber and dill',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
