/**
 * Katalog 500 — Śniadania, część A: pozycje sn-1 … sn-30 z
 * `prisma/catalog/katalog-500-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'sn-1',
    title: 'Jajecznica na boczku',
    description:
      'Puszysta jajecznica usmażona na wytopionym, chrupiącym boczku, ze szczypiorkiem i kromką żytniego chleba. Syte, weekendowe śniadanie z jednej patelni, gotowe w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['boczek', 80, 'g'],
      ['jajko', 5, 'szt'],
      ['szczypiorek', 10, 'g'],
      ['chleb żytni', 100, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Boczek pokrój w kostkę około 1 cm i wrzuć na zimną patelnię. Smaż na średnim ogniu 5–6 minut, aż tłuszcz się wytopi, a kostki będą złote i chrupiące.',
      'Jajka wbij do miski, dopraw solą i pieprzem i roztrzep widelcem tylko do połączenia żółtek z białkami.',
      'Zmniejsz ogień, wlej jajka na boczek i mieszaj szpatułką od brzegów do środka przez 2–3 minuty.',
      'Zdejmij patelnię z ognia, gdy jajecznica jest ścięta, ale wciąż lekko wilgotna — dojdzie na ciepłej patelni.',
      'Posiekaj szczypiorek, posyp nim jajecznicę i podawaj od razu z kromkami chleba żytniego.',
    ],
    photo:
      'Soft fluffy scrambled eggs with crispy golden bacon cubes, sprinkled with chopped chives, with slices of dark rye bread on the side',
  },
  {
    plan: 'sn-2',
    title: 'Jajecznica z kiełbasą i cebulką',
    description:
      'Wiejska jajecznica z podsmażoną kiełbasą i słodką, zeszkloną cebulką. Domowy klasyk na sobotni poranek albo po treningu, najlepszy z pajdą świeżego chleba.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['kiełbasa wędzona', 100, 'g'],
      ['cebula', 100, 'g'],
      ['masło', 10, 'g'],
      ['jajko', 5, 'szt'],
      ['szczypiorek', 5, 'g'],
      ['chleb', 100, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę pokrój w drobną kostkę, a kiełbasę w półplasterki grubości około 5 mm.',
      'Na patelni rozgrzej masło, wrzuć cebulę i smaż 3 minuty, aż się zeszkli. Dodaj kiełbasę i podsmażaj kolejne 3–4 minuty, aż lekko się zrumieni.',
      'Jajka roztrzep w misce ze szczyptą soli i pieprzem.',
      'Wlej jajka na patelnię, zmniejsz ogień i mieszaj delikatnie 2–3 minuty, aż się zetną, ale pozostaną kremowe.',
      'Posyp posiekanym szczypiorkiem i podawaj z kromkami chleba.',
    ],
    photo:
      'Rustic scrambled eggs with browned smoked sausage half-moons and golden onion, topped with chives, with a thick slice of bread',
  },
  {
    plan: 'sn-3',
    title: 'Jajka na miękko z grzankami z masłem',
    description:
      'Jajka na miękko z płynnym żółtkiem i chrupiące paski grzanek z masłem do maczania. Proste, ciepłe śniadanie, które przygotujesz w dziesięć minut, zanim zaparzy się kawa.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['jajko', 4, 'szt'],
      ['chleb', 120, 'g'],
      ['masło', 20, 'g'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'W garnku zagotuj tyle wody, żeby przykryła jajka. Jajka wyjęte wcześniej z lodówki włóż łyżką do wrzątku i gotuj dokładnie 5,5 minuty.',
      'W tym czasie opiecz kromki chleba w tosterze albo na suchej patelni po 2 minuty z każdej strony, aż będą złote.',
      'Grzanki posmaruj masłem i pokrój w paski szerokości 2 cm.',
      'Jajka przełóż na chwilę do zimnej wody, włóż do kieliszków i ostrożnie zetnij czubki nożem.',
      'Posól i popieprz żółtka, posyp szczypiorkiem i podawaj z paskami grzanek do maczania.',
    ],
    photo:
      'Two soft-boiled eggs in egg cups with runny orange yolks, next to buttered toast soldiers and a sprinkle of chives',
  },
  {
    plan: 'sn-4',
    title: 'Jajka w koszulce na toście z serkiem i rukolą',
    description:
      'Chrupiący tost posmarowany serkiem kremowym, garść rukoli i jajko w koszulce, z którego wypływa żółtko. Elegancko wygląda, a wymaga tylko garnka wody i odrobiny wprawy.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['chleb tostowy', 100, 'g'],
      ['serek kremowy', 60, 'g'],
      ['rukola', 20, 'g'],
      ['jajko', 4, 'szt'],
      ['ocet winny', 15, 'ml'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'W szerokim garnku zagotuj 1,5 l wody, dodaj ocet i zmniejsz ogień tak, żeby woda tylko lekko drgała.',
      'Każde jajko wbij najpierw do filiżanki. Zamieszaj wodę, tworząc wir, i wlej jajko na jego środek. Gotuj 3 minuty, aż białko się zetnie, a żółtko zostanie miękkie; wyjmij łyżką cedzakową na ręcznik papierowy.',
      'W tym czasie opiecz kromki chleba tostowego na złoto.',
      'Tosty posmaruj serkiem kremowym i przykryj rukolą.',
      'Na każdym toście połóż jajko, posól, popieprz, posyp posiekanym szczypiorkiem i podawaj od razu.',
    ],
    photo:
      'Toasted bread slices spread with white cream cheese, topped with arugula and soft poached eggs, cracked pepper and chives',
  },
  {
    plan: 'sn-5',
    title: 'Jajka zapiekane w kokilkach ze szpinakiem i serem',
    description:
      'Jajka zapieczone w kokilkach na kremowym szpinaku z czosnkiem, pod warstwą roztopionego sera. Wygląda odświętnie, a do piekarnika wkładasz wszystko w dziesięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['masło', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['szpinak', 150, 'g'],
      ['śmietanka 18', 40, 'ml'],
      ['gałka muszkatołowa', 1, 'g'],
      ['jajko', 4, 'szt'],
      ['ser żółty', 40, 'g'],
      ['chleb', 80, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 190°C (góra-dół). Dwie kokilki posmaruj odrobiną masła.',
      'Na patelni rozpuść resztę masła, wrzuć przeciśnięty czosnek, a po 30 sekundach szpinak. Duś 2–3 minuty, aż zwiędnie i odparuje woda.',
      'Wlej śmietankę, dopraw solą, pieprzem i gałką muszkatołową, gotuj minutę i rozłóż szpinak do kokilek.',
      'W szpinaku zrób dołki i wbij do każdej kokilki po 2 jajka. Posyp startym serem żółtym.',
      'Piecz 12–14 minut, aż białka się zetną, a żółtka pozostaną miękkie w środku.',
      'Podawaj prosto z kokilek z kromkami chleba do maczania.',
    ],
    photo:
      'Baked eggs in white ramekins on a bed of creamy spinach, covered with melted golden cheese, with bread slices beside',
  },
  {
    plan: 'sn-6',
    title: 'Jajka pieczone w pomidorach z mozzarellą',
    description:
      'Duże pomidory wydrążone i zapieczone z jajkiem w środku, pod plasterkiem mozzarelli i bazylią. Soczyste, lekkie śniadanie w stylu włoskim, najlepsze latem z chrupiącą bagietką.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['pomidor', 500, 'g'],
      ['jajko', 4, 'szt'],
      ['mozzarella', 60, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 1, 'g'],
      ['bazylia', 5, 'g'],
      ['bagietka', 80, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 200°C (góra-dół). Z 4 dużych pomidorów odetnij czubki i łyżeczką wydrąż środki, zostawiając ścianki grubości około 1 cm.',
      'Pomidory posól od środka, odwróć na 5 minut do góry dnem, żeby odciekł sok, i ułóż w naczyniu żaroodpornym posmarowanym oliwą.',
      'Do każdego pomidora wbij jajko, dopraw solą, pieprzem i oregano.',
      'Piecz 18–20 minut, aż białko się zetnie. Na ostatnie 5 minut połóż na wierzchu plasterki mozzarelli.',
      'Posyp listkami bazylii, skrop resztą oliwy i podawaj z kromkami bagietki.',
    ],
    photo:
      'Four baked red tomatoes filled with eggs and melted mozzarella, topped with fresh basil leaves, with sliced baguette alongside',
  },
  {
    plan: 'sn-7',
    title: 'Omlet z cukinią i serem żółtym',
    description:
      'Złocisty omlet z podsmażonymi plasterkami cukinii i ciągnącym się serem żółtym. Dobry sposób na sezonową cukinię i szybkie, sycące śniadanie w dni powszednie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['cukinia', 200, 'g'],
      ['masło', 10, 'g'],
      ['jajko', 5, 'szt'],
      ['mleko', 30, 'ml'],
      ['ser żółty', 50, 'g'],
      ['szczypiorek', 5, 'g'],
      ['chleb', 80, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cukinię przekrój wzdłuż na pół i pokrój w cienkie półplasterki. Ser zetrzyj na tarce o grubych oczkach.',
      'Na patelni o średnicy około 24 cm rozpuść połowę masła i smaż połowę cukinii 3–4 minuty, aż zmięknie i lekko się zezłoci; posól.',
      'Jajka roztrzep z mlekiem, solą i pieprzem. Wlej połowę masy na cukinię i smaż pod przykryciem na małym ogniu 3–4 minuty, aż wierzch się zetnie.',
      'Posyp połowę omletu połową sera, złóż na pół i zsuń na talerz. Tak samo usmaż drugi omlet z reszty składników.',
      'Posyp omlety szczypiorkiem i podawaj z chlebem.',
    ],
    photo:
      'Golden folded omelette filled with sautéed zucchini slices and melted yellow cheese, garnished with chives, with a slice of bread',
  },
  {
    plan: 'sn-8',
    title: 'Omlet po meksykańsku z papryką i kukurydzą',
    description:
      'Pikantny omlet z czerwoną papryką, kukurydzą, czerwoną cebulą i cheddarem, doprawiony kuminem, podany z ciepłą tortillą. Kolorowe śniadanie, które budzi lepiej niż kawa.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['olej rzepakowy', 10, 'ml'],
      ['cebula czerwona', 50, 'g'],
      ['papryka czerwona', 1, 'szt'],
      ['kukurydza z puszki', 80, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['jajko', 5, 'szt'],
      ['ser cheddar', 40, 'g'],
      ['kolendra', 5, 'g'],
      ['tortilla pszenna', 2, 'szt'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Paprykę oczyść i pokrój w kostkę 1 cm, cebulę posiekaj drobno, kukurydzę odsącz.',
      'Na patelni rozgrzej olej, smaż cebulę i paprykę 4 minuty, aż zmiękną. Dodaj kukurydzę, kmin i słodką paprykę i smaż jeszcze minutę.',
      'Jajka roztrzep z solą i pieprzem, wlej na warzywa i smaż pod przykryciem na małym ogniu 4–5 minut, aż wierzch się zetnie.',
      'Posyp startym cheddarem, przykryj na minutę, żeby ser się roztopił, i przekrój omlet na pół.',
      'Tortille podgrzej na suchej patelni po 20 sekund z każdej strony.',
      'Posyp omlet posiekaną kolendrą i podawaj z ciepłymi tortillami.',
    ],
    photo:
      'Fluffy omelette studded with red bell pepper, sweet corn and red onion, topped with melted cheddar and cilantro, warm tortillas on the side',
  },
  {
    plan: 'sn-9',
    title: 'Omlet biszkoptowy na słodko z dżemem',
    description:
      'Wysoki, puszysty omlet na ubitej pianie z białek, złożony z dżemem i oprószony cukrem pudrem. Smak dzieciństwa, który wychodzi z patelni lekki jak biszkopt.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['jajko', 4, 'szt'],
      ['cukier', 15, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['mleko', 30, 'ml'],
      ['mąka pszenna', 30, 'g'],
      ['masło', 10, 'g'],
      ['dżem', 60, 'g'],
      ['cukier puder', 5, 'g'],
    ],
    steps: [
      'Oddziel żółtka od białek. Białka ubij mikserem na sztywną pianę, pod koniec dodając stopniowo cukier.',
      'Żółtka wymieszaj z cukrem waniliowym, mlekiem i mąką na gładką masę, a potem delikatnie wmieszaj ją szpatułką do piany, żeby nie opadła.',
      'Na patelni o średnicy 24 cm rozpuść połowę masła, wyłóż połowę masy i wyrównaj. Smaż pod przykryciem na małym ogniu 4–5 minut, aż spód będzie złoty, a wierzch przestanie się kleić.',
      'Posmaruj połowę omletu połową dżemu, złóż na pół i zsuń na talerz. Tak samo usmaż drugi omlet.',
      'Oprósz omlety cukrem pudrem przez sitko i podawaj od razu, póki są wysokie.',
    ],
    photo:
      'Tall fluffy golden soufflé omelette folded over red fruit jam, dusted with powdered sugar',
  },
  {
    plan: 'sn-10',
    title: 'Omlet owsiany z bananem i jogurtem',
    description:
      'Omlet z płatków owsianych, jajek i rozgniecionego banana, smażony na maśle i podany z jogurtem i miodem. Słodki bez dodatku cukru, sycący na długo, dobry przed pracą albo treningiem.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 60, 'g'],
      ['mleko', 100, 'ml'],
      ['banan', 1, 'szt'],
      ['jajko', 3, 'szt'],
      ['cynamon', 1, 'g'],
      ['masło', 5, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Płatki owsiane zalej mlekiem i odstaw na 5 minut, żeby zmiękły.',
      'Połowę banana rozgnieć widelcem, drugą połowę pokrój w plasterki.',
      'Do płatków dodaj jajka, rozgnieciony banan i cynamon i wymieszaj na gęstą masę.',
      'Na patelni rozpuść masło, wlej masę i wyrównaj. Smaż pod przykryciem na małym ogniu 5 minut, przewróć przy pomocy talerza i smaż jeszcze 2–3 minuty, aż będzie ścięty w środku.',
      'Pokrój omlet na pół, połóż na nim jogurt i plasterki banana, polej miodem i podawaj.',
    ],
    photo:
      'Golden oat omelette topped with a dollop of white yogurt, fresh banana slices and a drizzle of honey, dusted with cinnamon',
  },
  {
    plan: 'sn-11',
    title: 'Frittata z ziemniakami i cebulą',
    description:
      'Gruba frittata z cienko pokrojonymi ziemniakami i słodką cebulą, dopieczona w piekarniku pod parmezanem. Smakuje na ciepło i na zimno, więc resztę zabierzesz do pracy.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['ziemniak', 300, 'g'],
      ['cebula', 1, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['jajko', 6, 'szt'],
      ['ser parmezan', 20, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 190°C (góra-dół). Ziemniaki obierz i pokrój w plasterki grubości 3 mm, cebulę w cienkie piórka.',
      'Na patelni z metalową rączką rozgrzej oliwę, wrzuć ziemniaki i cebulę, posól i smaż pod przykryciem 12–15 minut, mieszając co kilka minut, aż ziemniaki będą miękkie i lekko zrumienione.',
      'Jajka roztrzep z pieprzem i połową startego parmezanu, wlej na ziemniaki i potrząśnij patelnią, żeby masa się rozeszła.',
      'Smaż na małym ogniu 3 minuty, aż brzegi się zetną, posyp resztą parmezanu i wstaw do piekarnika na 10–12 minut, aż środek będzie sprężysty.',
      'Odstaw na 3 minuty, pokrój w trójkąty, posyp posiekaną natką i podawaj.',
    ],
    photo:
      'Thick golden potato and onion frittata in a cast-iron pan, one wedge cut out, sprinkled with parmesan and chopped parsley',
  },
  {
    plan: 'sn-12',
    title: 'Frittata z brokułem i fetą',
    description:
      'Zielona frittata z różyczkami brokułu, czerwoną cebulą i słoną fetą, zapieczona do puszystości. Dużo białka i warzyw na start dnia, a kawałek świetnie znosi pudełko.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['brokuł', 250, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cebula czerwona', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['jajko', 6, 'szt'],
      ['ser feta', 80, 'g'],
      ['chleb', 80, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 190°C (góra-dół). Brokuł podziel na małe różyczki i gotuj w osolonej wodzie 3 minuty, a potem odcedź.',
      'Na patelni z metalową rączką rozgrzej oliwę, podsmaż pokrojoną w piórka cebulę i przeciśnięty czosnek przez 2 minuty. Dodaj brokuł i smaż minutę.',
      'Jajka roztrzep z pieprzem i szczyptą soli (feta jest słona), wlej na warzywa i pokrusz na wierzch fetę.',
      'Smaż na małym ogniu 3 minuty, aż brzegi się zetną, i przełóż patelnię do piekarnika na 10–12 minut, aż frittata wyrośnie i będzie ścięta w środku.',
      'Pokrój w trójkąty i podawaj z kromką chleba.',
    ],
    photo:
      'Puffy golden frittata with bright green broccoli florets, red onion and crumbled white feta in a skillet, cut into wedges',
  },
  {
    plan: 'sn-13',
    title: 'Zielona szakszuka ze szpinakiem i cukinią',
    description:
      'Szakszuka w zielonej wersji: jajka ścięte w duszonej cukinii ze szpinakiem, dymką i czosnkiem, z pokruszoną fetą i szczyptą chili. Lżejsza niż pomidorowa, a równie aromatyczna.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['oliwa z oliwek', 20, 'ml'],
      ['cebula dymka', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['cukinia', 250, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['szpinak', 150, 'g'],
      ['jajko', 4, 'szt'],
      ['ser feta', 50, 'g'],
      ['płatki chili', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['bagietka', 100, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dymkę pokrój w krążki, czosnek posiekaj, cukinię zetrzyj na tarce o grubych oczkach albo pokrój w kostkę 1 cm.',
      'Na dużej patelni rozgrzej oliwę, smaż dymkę i czosnek minutę. Dodaj cukinię i kmin i smaż 5 minut, aż zmięknie.',
      'Wrzuć szpinak garściami i duś 2–3 minuty, aż zwiędnie. Dopraw solą i pieprzem.',
      'Zrób w warzywach 4 dołki, wbij do nich jajka i gotuj pod przykryciem na małym ogniu 6–8 minut, aż białka się zetną, a żółtka pozostaną płynne.',
      'Pokrusz na wierzch fetę, posyp płatkami chili i natką. Podawaj prosto z patelni z kromkami bagietki.',
    ],
    photo:
      'Green shakshuka in a skillet with wilted spinach and zucchini, four sunny egg yolks, crumbled feta, chili flakes and parsley, baguette slices aside',
  },
  {
    plan: 'sn-14',
    title: 'Tost z jajkiem w środku',
    description:
      'Kromka tostowego chleba z wyciętą dziurką, w którą wbijasz jajko i smażysz wszystko razem na maśle. Chrupiący chleb i miękkie żółtko w jednym, a do tego świeży pomidor.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['chleb tostowy', 100, 'g'],
      ['masło', 20, 'g'],
      ['jajko', 4, 'szt'],
      ['pomidor', 1, 'szt'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'W środku każdej z 4 kromek wytnij szklanką otwór o średnicy około 6 cm; wycięte krążki zostaw.',
      'Na dużej patelni rozpuść połowę masła na średnim ogniu i połóż 2 kromki oraz krążki. Smaż 1–2 minuty, aż spód się zezłoci.',
      'Przewróć kromki, dodaj pod nie trochę masła i wbij jajko do każdego otworu. Posól i smaż pod przykryciem 3–4 minuty, aż białko się zetnie. Tak samo usmaż drugą parę.',
      'Pomidor pokrój w ósemki, posól.',
      'Tosty posyp pieprzem i szczypiorkiem, podawaj z pomidorem i chrupiącymi krążkami do maczania w żółtku.',
    ],
    photo:
      'Golden buttered toast slices with fried eggs set in their centers, runny yolks, chives, toasted bread circles and tomato wedges beside',
  },
  {
    plan: 'sn-15',
    title: 'Tost z szynką, serem i jajkiem sadzonym',
    description:
      'Zapiekany tost z musztardą, szynką i roztopionym serem, zwieńczony jajkiem sadzonym. Domowa wersja francuskiego croque madame — sycąca, ciepła i gotowa w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['chleb tostowy', 100, 'g'],
      ['musztarda', 10, 'g'],
      ['szynka', 60, 'g'],
      ['ser żółty', 60, 'g'],
      ['masło', 15, 'g'],
      ['jajko', 2, 'szt'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dwie kromki chleba posmaruj cienko musztardą, połóż na nich szynkę i połowę sera w plasterkach, przykryj pozostałymi kromkami.',
      'Na patelni rozpuść 10 g masła i smaż tosty na średnim ogniu po 2–3 minuty z każdej strony, dociskając łopatką, aż będą złote.',
      'Na wierzchu tostów rozłóż resztę sera i przykryj patelnię na minutę, żeby się roztopił. Przełóż tosty na talerze.',
      'Na tej samej patelni rozpuść resztę masła i usmaż 2 jajka sadzone, aż białko się zetnie, a żółtko pozostanie płynne. Posól.',
      'Połóż jajko na każdym toście, oprósz pieprzem i szczypiorkiem i podawaj od razu.',
    ],
    photo:
      'Golden grilled ham and cheese sandwich with melted cheese on top and a sunny-side-up fried egg, sprinkled with chives and black pepper',
  },
  {
    plan: 'sn-16',
    title: 'Fasolka w sosie pomidorowym na grzance z jajkiem sadzonym',
    description:
      'Gorąca fasolka w sosie pomidorowym z wędzoną papryką na chrupiącej grzance, przykryta jajkiem sadzonym. Tanie, rozgrzewające śniadanie, które syci aż do obiadu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['fasola w sosie pomidorowym', 400, 'g'],
      ['papryka wędzona mielona', 1, 'g'],
      ['chleb', 120, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['jajko', 2, 'szt'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Fasolkę przełóż do rondelka, dodaj wędzoną paprykę i podgrzewaj na małym ogniu 5 minut, mieszając, aż sos zacznie bulgotać.',
      'Kromki chleba opiecz w tosterze albo na suchej patelni na złoto.',
      'Na patelni rozgrzej olej i usmaż 2 jajka sadzone, 3–4 minuty, aż białko się zetnie, a żółtko zostanie płynne. Posól i popieprz.',
      'Na każdą grzankę wyłóż gorącą fasolkę z sosem i przykryj jajkiem.',
      'Posyp posiekaną natką i podawaj od razu, póki grzanka jest chrupiąca.',
    ],
    photo:
      'Toasted bread piled with baked beans in glossy tomato sauce, topped with a fried egg with runny yolk and chopped parsley',
  },
  {
    plan: 'sn-17',
    title: 'Pieczarki na toście z serem',
    description:
      'Pieczarki smażone na maśle z czosnkiem, tymiankiem i łyżką śmietany, zapieczone z serem na grzance. Leśny, maślany smak na ciepło, bardzo tanio i bez mięsa.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['pieczarka', 300, 'g'],
      ['cebula', 50, 'g'],
      ['masło', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['tymianek suszony', 1, 'g'],
      ['śmietana 18', 30, 'g'],
      ['chleb', 120, 'g'],
      ['ser żółty', 60, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pieczarki oczyść i pokrój w plasterki, cebulę posiekaj drobno, a czosnek przeciśnij przez praskę.',
      'Na dużej patelni rozpuść masło, podsmaż cebulę 2 minuty, dodaj pieczarki i smaż na mocnym ogniu 6–8 minut, aż odparuje woda i się zrumienią.',
      'Dodaj czosnek i tymianek, smaż 30 sekund, wmieszaj śmietanę, dopraw solą i pieprzem i zdejmij z ognia.',
      'Kromki chleba opiecz w tosterze, ułóż na blasze, wyłóż na nie pieczarki i posyp startym serem żółtym.',
      'Zapiekaj pod grillem piekarnika w 220°C 4–5 minut, aż ser się roztopi i zarumieni.',
      'Posyp posiekaną natką i podawaj na ciepło.',
    ],
    photo:
      'Open-faced toasts topped with creamy sautéed mushrooms under bubbling golden melted cheese, sprinkled with chopped parsley',
    vessel: 'board',
  },
  {
    plan: 'sn-18',
    title: 'Zapiekanka chlebowa z jajkiem i szynką',
    description:
      'Kostki czerstwego chleba nasączone jajkami z mlekiem, przełożone szynką i dymką i zapieczone pod serem. Najlepszy sposób na wczorajszy chleb i ciepłe, rodzinne śniadanie w weekend.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['masło', 5, 'g'],
      ['chleb', 150, 'g'],
      ['szynka', 80, 'g'],
      ['cebula dymka', 30, 'g'],
      ['jajko', 4, 'szt'],
      ['mleko', 200, 'ml'],
      ['papryka słodka mielona', 1, 'g'],
      ['ser żółty', 50, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 180°C (góra-dół). Naczynie żaroodporne o pojemności około 1 l wysmaruj masłem.',
      'Chleb pokrój w kostkę 2 cm, szynkę w paski, a dymkę w krążki. Ułóż wszystko warstwami w naczyniu.',
      'Jajka roztrzep z mlekiem, papryką i pieprzem (szynka i ser są słone) i zalej chleb. Dociśnij łyżką i odstaw na 10 minut, żeby chleb nasiąknął.',
      'Posyp startym serem żółtym i piecz 25–30 minut, aż masa się zetnie, a wierzch będzie złoty i chrupiący.',
      'Odstaw na 5 minut, pokrój na porcje i podawaj na ciepło.',
    ],
    photo:
      'Golden baked savory bread pudding in a ceramic dish with ham strips, green onion and a crispy melted cheese crust, one portion scooped out',
  },
  {
    plan: 'sn-19',
    title: 'Śniadanie po angielsku z kiełbaskami, jajkiem i fasolką',
    description:
      'Talerz jak z angielskiego pubu: zrumienione kiełbaski, jajko sadzone, fasolka w sosie pomidorowym, pieczarki, grillowany pomidor i tost. Obfite śniadanie na leniwą niedzielę.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['kiełbasa biała', 160, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['pieczarka', 120, 'g'],
      ['pomidor', 1, 'szt'],
      ['fasola w sosie pomidorowym', 200, 'g'],
      ['jajko', 2, 'szt'],
      ['chleb tostowy', 50, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kiełbasę pokrój na 4 kawałki, nakłuj widelcem i smaż na połowie oleju na średnim ogniu 12–15 minut, obracając, aż będzie zrumieniona i dopieczona w środku.',
      'W tym czasie pieczarki przekrój na ćwiartki, a pomidor na pół. Dołóż je na patelnię obok kiełbasy (pomidor przekrojem w dół) i smaż 5–6 minut; oprósz pieprzem.',
      'Fasolkę podgrzej w rondelku na małym ogniu przez 5 minut.',
      'Na drugiej patelni rozgrzej resztę oleju i usmaż 2 jajka sadzone, aż białko się zetnie, a żółtko pozostanie płynne.',
      'Kromki chleba opiecz w tosterze i przekrój po przekątnej.',
      'Na talerzach ułóż kiełbaski, jajko, fasolkę, pieczarki, pomidor i tost i podawaj od razu.',
    ],
    photo:
      'Full English breakfast plate with browned sausages, sunny-side-up egg, baked beans in tomato sauce, sautéed mushrooms, grilled tomato half and toast triangles',
  },
  {
    plan: 'sn-20',
    title: 'Kanapka na ciepło z jajkiem, boczkiem i serem',
    description:
      'Chrupiąca kajzerka z plasterkami smażonego boczku, jajkiem, roztopionym cheddarem, sałatą i pomidorem. Śniadaniowa kanapka jak z food trucka, zrobiona w domu w piętnaście minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['boczek', 60, 'g'],
      ['jajko', 2, 'szt'],
      ['ser cheddar', 40, 'g'],
      ['bułka kajzerka', 2, 'szt'],
      ['masło', 5, 'g'],
      ['ketchup', 15, 'g'],
      ['sałata lodowa', 20, 'g'],
      ['pomidor', 60, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Boczek w plasterkach smaż na suchej patelni 3–4 minuty, obracając, aż będzie chrupiący. Odłóż na ręcznik papierowy.',
      'Na wytopionym tłuszczu usmaż 2 jajka; przebij żółtka, żeby się rozlały, i smaż 2 minuty z każdej strony. Popieprz, połóż na nich cheddar i przykryj patelnię na minutę, aż ser się roztopi.',
      'Bułki przekrój, posmaruj cienko masłem i opiecz przekrojem w dół na patelni przez minutę.',
      'Pomidor pokrój w plasterki, sałatę porwij na kawałki.',
      'Dolne połówki bułek posmaruj ketchupem, ułóż sałatę, pomidor, jajko z serem i boczek, przykryj wierzchem bułki i podawaj na ciepło.',
    ],
    photo:
      'Warm toasted kaiser roll sandwich with crispy bacon, fried egg with melted cheddar, lettuce and tomato slice, cut in half',
    vessel: 'board',
  },
  {
    plan: 'sn-21',
    title: 'Rogaliki z szynką i serem zapiekane',
    description:
      'Maślane rogaliki przekrojone, wypełnione szynką, serem i pomidorem, zapieczone w piekarniku, aż ser zacznie się ciągnąć. Ciepłe, chrupiące śniadanie na weekend, gotowe w dwadzieścia minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['rogalik', 3, 'szt'],
      ['szynka', 60, 'g'],
      ['ser żółty', 60, 'g'],
      ['pomidor', 1, 'szt'],
      ['oregano', 1, 'g'],
      ['rukola', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 190°C (góra-dół), blachę wyłóż papierem do pieczenia.',
      'Rogaliki przekrój wzdłuż, nie docinając do końca, żeby otwierały się jak książka.',
      'Pomidor pokrój w cienkie plasterki, ser w plasterki.',
      'Do każdego rogalika włóż szynkę, pomidor i ser, oprósz oregano i pieprzem i lekko dociśnij.',
      'Zapiekaj 8–10 minut, aż rogaliki będą chrupiące, a ser się roztopi.',
      'Podawaj od razu, z garścią rukoli.',
    ],
    photo:
      'Golden flaky croissants filled with ham, tomato slices and melted cheese, baked until crisp, with fresh arugula on the side',
    vessel: 'board',
  },
  {
    plan: 'sn-22',
    title: 'Pancakes z syropem klonowym i borówkami',
    description:
      'Grube, puszyste amerykańskie placuszki smażone na maśle, polane syropem klonowym i obsypane świeżymi borówkami. Śniadanie na leniwy weekend, gotowe szybciej niż zamówienie z dowozem.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 120, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['cukier', 10, 'g'],
      ['sól', 1, 'g'],
      ['jajko', 1, 'szt'],
      ['mleko', 150, 'ml'],
      ['masło', 15, 'g'],
      ['syrop klonowy', 30, 'g'],
      ['borówka', 125, 'g'],
    ],
    steps: [
      'W misce wymieszaj mąkę, proszek do pieczenia, cukier i sól.',
      'W drugiej misce roztrzep jajko z mlekiem i 10 g roztopionego masła. Wlej do suchych składników i wymieszaj łyżką tylko do połączenia — grudki są w porządku.',
      'Patelnię rozgrzej na średnim ogniu i przetrzyj resztą masła. Nakładaj po 2 łyżki ciasta na placek.',
      'Smaż około 2 minut, aż na wierzchu pojawią się pęcherzyki, przewróć i smaż jeszcze minutę, aż będą złote i wyrośnięte.',
      'Ułóż pancakes w stosiki, obsyp borówkami, polej syropem klonowym i podawaj od razu.',
    ],
    photo:
      'Tall stack of fluffy golden pancakes drizzled with glossy maple syrup, topped with fresh blueberries',
  },
  {
    plan: 'sn-23',
    title: 'Racuchy z jabłkami',
    description:
      'Puszyste racuchy drożdżowe z kawałkami jabłka i cynamonem, smażone na złoto i oprószone cukrem pudrem. Smak niedzieli u babci, najlepsze prosto z patelni.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    ingredients: [
      ['mleko', 150, 'ml'],
      ['drożdże', 10, 'g'],
      ['cukier', 15, 'g'],
      ['mąka pszenna', 150, 'g'],
      ['jajko', 1, 'szt'],
      ['sól', 1, 'g'],
      ['jabłko', 2, 'szt'],
      ['cynamon', 1, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['cukier puder', 10, 'g'],
    ],
    steps: [
      'Mleko podgrzej do temperatury ciała, rozpuść w nim drożdże i łyżeczkę cukru. Odstaw na 5 minut, aż zacznie się pienić.',
      'Do miski wsyp mąkę, dodaj resztę cukru, sól, jajko i rozczyn i wymieszaj łyżką na gęste, lepkie ciasto. Przykryj ściereczką i odstaw w ciepłe miejsce na 30 minut, aż podwoi objętość.',
      'Jabłka obierz, usuń gniazda nasienne i pokrój w kostkę 1 cm albo w cienkie plasterki. Wymieszaj z cynamonem i delikatnie wmieszaj do wyrośniętego ciasta.',
      'Na patelni rozgrzej część oleju na średnim ogniu. Nakładaj łyżką placki grubości około 1 cm i smaż po 2–3 minuty z każdej strony, aż będą złote i upieczone w środku; w razie potrzeby dolewaj oleju.',
      'Odsącz racuchy na ręczniku papierowym.',
      'Podawaj na ciepło, obficie oprószone cukrem pudrem.',
    ],
    photo:
      'Golden fluffy yeast pancakes with visible apple pieces, generously dusted with powdered sugar and a pinch of cinnamon',
  },
  {
    plan: 'sn-24',
    title: 'Gofry z jogurtem greckim i owocami',
    description:
      'Chrupiące z zewnątrz, miękkie w środku domowe gofry z gęstym jogurtem greckim, truskawkami, borówkami i miodem. Śniadanie jak z nadmorskiej budki, tylko lżejsze niż z bitą śmietaną.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 120, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['cukier', 10, 'g'],
      ['sól', 1, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 180, 'ml'],
      ['masło', 25, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['truskawka', 150, 'g'],
      ['borówka', 60, 'g'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Gofrownicę rozgrzej. Masło roztop i przestudź.',
      'W misce wymieszaj mąkę, proszek do pieczenia, cukier i sól. Dodaj jajka, mleko i roztopione masło i wymieszaj trzepaczką na gładkie, gęste ciasto.',
      'Nakładaj ciasto do gofrownicy i piecz każdą partię 3–4 minuty, aż gofry będą złote i przestanie z nich uchodzić para.',
      'Truskawki umyj, odszyp i przekrój na ćwiartki; borówki opłucz.',
      'Na ciepłe gofry wyłóż jogurt grecki, ułóż truskawki i borówki i polej miodem. Podawaj od razu.',
    ],
    photo:
      'Crisp golden Belgian-style waffles topped with thick white Greek yogurt, fresh quartered strawberries, blueberries and a honey drizzle',
  },
  {
    plan: 'sn-25',
    title: 'Naleśniki z bananem i masłem orzechowym',
    description:
      'Cienkie naleśniki posmarowane masłem orzechowym i zwinięte z plasterkami banana, z nutą cynamonu. Słodkie, sycące śniadanie, które smakuje dzieciom i dorosłym.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 100, 'g'],
      ['jajko', 1, 'szt'],
      ['mleko', 200, 'ml'],
      ['sól', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['masło orzechowe', 40, 'g'],
      ['banan', 2, 'szt'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Mąkę, jajko, mleko, wodę gazowaną (50 ml) i sól zmiksuj albo wymieszaj trzepaczką na gładkie, rzadkie ciasto. Wmieszaj połowę oleju i odstaw na 10 minut.',
      'Patelnię do naleśników rozgrzej na średnim ogniu i przetrzyj ją ręcznikiem nasączonym resztą oleju.',
      'Wlewaj po pół chochli ciasta, rozprowadzaj ruchem patelni i smaż około minuty, aż brzegi się zezłocą; przewróć i smaż jeszcze 30 sekund. Wyjdzie około 6 naleśników.',
      'Banany obierz i pokrój w plasterki.',
      'Każdy ciepły naleśnik posmaruj cienko masłem orzechowym, ułóż plasterki banana, oprósz cynamonem i zwiń w rulon albo złóż w trójkąt. Podawaj od razu.',
    ],
    photo:
      'Thin rolled crepes filled with peanut butter and banana slices, cut diagonally, dusted with cinnamon, extra banana on top',
  },
  {
    plan: 'sn-26',
    title: 'Leniwe z masłem i cynamonem',
    description:
      'Miękkie kluski z twarogu polane masłem zrumienionym z bułką tartą i posypane cukrem z cynamonem. Klasyka z mlecznego baru, prosta, tania i bogata w białko.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['ser twaróg półtłusty', 250, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 80, 'g'],
      ['sól', 1, 'g'],
      ['masło', 20, 'g'],
      ['bułka tarta', 15, 'g'],
      ['cukier', 15, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Twaróg rozgnieć widelcem albo przeciśnij przez praskę, dodaj jajko i szczyptę soli i wymieszaj na gładko.',
      'Dosyp mąkę i szybko zagnieć miękkie ciasto — nie wyrabiaj długo, żeby kluski nie były twarde.',
      'Ciasto podziel na 2 części, na oprószonym mąką blacie uformuj wałki grubości około 3 cm, lekko spłaszcz i tnij ukośnie na kawałki szerokości 2 cm.',
      'Wrzucaj kluski do dużego garnka osolonego wrzątku, zamieszaj i gotuj 2–3 minuty od wypłynięcia. Wyjmij łyżką cedzakową.',
      'Na patelni rozpuść masło, dodaj bułkę tartą i smaż 1–2 minuty, aż się zezłoci. Cukier wymieszaj z cynamonem.',
      'Leniwe polej masłem z bułką tartą, posyp cukrem z cynamonem i podawaj na ciepło.',
    ],
    photo:
      'Soft Polish cottage cheese dumplings drizzled with golden buttered breadcrumbs and sprinkled with cinnamon sugar',
  },
  {
    plan: 'sn-27',
    title: 'Placuszki dyniowe z cynamonem',
    description:
      'Pomarańczowe, wilgotne placuszki z puree z dyni, pachnące cynamonem i imbirem, podane z jogurtem greckim i miodem. Jesienne śniadanie, gdy na targu pojawiają się pierwsze dynie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['dynia', 250, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 80, 'ml'],
      ['cukier', 10, 'g'],
      ['mąka pszenna', 100, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['cynamon', 2, 'g'],
      ['imbir mielony', 1, 'g'],
      ['sól', 1, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['jogurt grecki', 100, 'g'],
      ['miód', 20, 'g'],
    ],
    steps: [
      'Dynię obierz, usuń pestki i pokrój w kostkę 2 cm. Gotuj w niewielkiej ilości wody pod przykryciem 12–15 minut, aż będzie miękka, odcedź dokładnie i rozgnieć na gładkie puree. Przestudź.',
      'Do puree dodaj jajka, mleko i cukier i wymieszaj trzepaczką.',
      'Wsyp mąkę, proszek do pieczenia, cynamon, imbir i sól i wymieszaj na gęste ciasto.',
      'Na patelni rozgrzej część oleju na średnim ogniu, nakładaj po łyżce ciasta i smaż placuszki po 2 minuty z każdej strony, aż będą rumiane i sprężyste; dolewaj oleju w razie potrzeby.',
      'Podawaj ciepłe z łyżką jogurtu greckiego, polane miodem.',
    ],
    photo:
      'Stack of orange pumpkin pancakes dusted with cinnamon, topped with thick Greek yogurt and a honey drizzle',
  },
  {
    plan: 'sn-28',
    title: 'Syrniki ze śmietaną i dżemem',
    description:
      'Rumiane twarogowe placuszki po ukraińsku, chrupiące na zewnątrz i kremowe w środku, podane ze śmietaną i dżemem. Białkowe śniadanie na słodko, które zjadasz do ostatniego okruszka.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['ser twaróg półtłusty', 300, 'g'],
      ['jajko', 1, 'szt'],
      ['cukier', 20, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['sól', 1, 'g'],
      ['mąka pszenna', 60, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['śmietana 18', 80, 'g'],
      ['dżem', 50, 'g'],
    ],
    steps: [
      'Twaróg dokładnie rozgnieć widelcem albo zmiel, żeby nie było grudek.',
      'Dodaj jajko, cukier, cukier waniliowy, szczyptę soli i 50 g mąki i wymieszaj na gęstą, lekko lepką masę.',
      'Resztę mąki wysyp na talerz. Zwilżonymi dłońmi formuj kulki wielkości orzecha włoskiego, obtaczaj w mące i spłaszczaj na placuszki grubości 1,5 cm.',
      'Na patelni rozgrzej olej na średnim ogniu i smaż syrniki po 3 minuty z każdej strony, aż będą złote i sprężyste. Na koniec przykryj patelnię na minutę, żeby dogrzały się w środku.',
      'Podawaj ciepłe z łyżką śmietany i dżemu.',
    ],
    photo:
      'Golden fried Ukrainian cottage cheese pancakes with a dollop of sour cream and red berry jam',
  },
  {
    plan: 'sn-29',
    title: 'Owsianka z pieczonym jabłkiem i cynamonem',
    description:
      'Kremowa owsianka na mleku z połówkami jabłek upieczonymi z miodem i cynamonem, posypana orzechami włoskimi. Smakuje jak szarlotka w misce i rozgrzewa w chłodne poranki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['jabłko', 2, 'szt'],
      ['miód', 20, 'g'],
      ['cynamon', 2, 'g'],
      ['płatki owsiane', 80, 'g'],
      ['mleko', 400, 'ml'],
      ['orzech włoski', 20, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 190°C (góra-dół). Jabłka przekrój na pół, wytnij gniazda nasienne i ułóż przekrojem do góry w małym naczyniu żaroodpornym.',
      'Jabłka skrop połową miodu, posyp połową cynamonu i piecz 20–25 minut, aż będą miękkie i zaczną puszczać sok.',
      'W tym czasie płatki owsiane zalej mlekiem w rondelku, dodaj resztę cynamonu i gotuj na małym ogniu 5–6 minut, mieszając, aż owsianka zgęstnieje.',
      'Orzechy włoskie podpraż na suchej patelni 2–3 minuty i posiekaj grubo.',
      'Owsiankę przełóż do misek, na wierzchu połóż pieczone jabłka z sokiem, posyp orzechami i polej resztą miodu.',
    ],
    photo:
      'Creamy oatmeal in a bowl topped with two soft baked apple halves glazed with honey and cinnamon, and chopped toasted walnuts',
    vessel: 'bowl',
  },
  {
    plan: 'sn-30',
    title: 'Owsianka pieczona z malinami',
    description:
      'Zapiekana owsianka z bananem i malinami, która w piekarniku zamienia się w miękkie, owsiane ciasto z soczystymi owocami. Pyszna na ciepło i na zimno, więc przyda się też do pudełka.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['masło', 5, 'g'],
      ['banan', 1, 'szt'],
      ['jajko', 1, 'szt'],
      ['mleko', 250, 'ml'],
      ['miód', 20, 'g'],
      ['płatki owsiane', 100, 'g'],
      ['proszek do pieczenia', 3, 'g'],
      ['cynamon', 1, 'g'],
      ['malina', 150, 'g'],
      ['migdał', 15, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 180°C (góra-dół). Naczynie żaroodporne o boku około 20 cm wysmaruj masłem.',
      'Banana rozgnieć widelcem w misce, dodaj jajko, mleko i połowę miodu i wymieszaj trzepaczką.',
      'Wsyp płatki owsiane, proszek do pieczenia i cynamon i wymieszaj. Przelej masę do naczynia.',
      'Na wierzchu rozłóż maliny, lekko je wciskając, i posyp posiekanymi migdałami.',
      'Piecz 25–30 minut, aż owsianka się zetnie, a wierzch będzie złoty.',
      'Odstaw na 5 minut, nałóż do misek i polej resztą miodu.',
    ],
    photo:
      'Golden baked oatmeal in a ceramic dish with juicy red raspberries pressed into the top and chopped almonds, one portion scooped out',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
