/**
 * Katalog 500 — część `sn-b`: śniadania, pozycje sn-31 … sn-60 listy
 * `prisma/catalog/katalog-500-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'sn-31',
    title: 'Owsianka z gruszką i orzechami włoskimi',
    description:
      'Kremowa owsianka na mleku z plastrami gruszki podgrzanej z miodem i cynamonem oraz uprażonymi orzechami włoskimi. Jesienne śniadanie, które grzeje i syci do obiadu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['mleko', 400, 'ml'],
      ['gruszka', 1, 'szt'],
      ['orzech włoski', 30, 'g'],
      ['miód', 15, 'g'],
      ['cynamon', 1, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Orzechy włoskie połam na mniejsze kawałki i praż na suchej patelni 2–3 minuty, aż zaczną pachnieć; przełóż na talerzyk.',
      'Do rondla wlej mleko, wsyp płatki owsiane i szczyptę soli, zagotuj i gotuj na małym ogniu 5–6 minut, często mieszając, aż owsianka zgęstnieje.',
      'Gruszkę umyj, usuń gniazdo nasienne i pokrój w cienkie plasterki.',
      'Na tej samej patelni podgrzej plasterki gruszki z miodem i cynamonem przez 2–3 minuty, aż lekko zmiękną i się zeszklą.',
      'Przełóż owsiankę do misek, ułóż na wierzchu gruszkę z sosem z patelni i posyp prażonymi orzechami.',
    ],
    photo:
      'Creamy oatmeal topped with fanned glazed pear slices, toasted walnut pieces and a drizzle of honey with cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'sn-32',
    title: 'Owsianka ze śliwkami i cynamonem',
    description:
      'Owsianka na mleku z szybkim kompotem ze śliwek duszonych z cynamonem i brązowym cukrem, podana z łyżką jogurtu. Najlepsza pod koniec lata, gdy śliwki są słodkie i miękkie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['mleko', 400, 'ml'],
      ['śliwka', 200, 'g'],
      ['cukier brązowy', 10, 'g'],
      ['cynamon', 2, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Śliwki umyj, przekrój na pół, usuń pestki i pokrój każdą połówkę na ćwiartki.',
      'Wrzuć śliwki do małego rondelka z cukrem brązowym, połową cynamonu i 2 łyżkami wody; duś pod przykryciem 6–8 minut, aż puszczą sok i zmiękną, ale nie rozpadną się całkiem.',
      'W drugim rondlu zagotuj mleko ze szczyptą soli, wsyp płatki owsiane i gotuj na małym ogniu 5–6 minut, mieszając, aż owsianka będzie gęsta.',
      'Wmieszaj do owsianki resztę cynamonu.',
      'Rozłóż owsiankę do misek, na środek nałóż jogurt naturalny, a obok ciepłe śliwki z sokiem.',
    ],
    photo:
      'Oatmeal topped with glossy stewed purple plum quarters in their syrup, a dollop of white yogurt and a dusting of cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'sn-33',
    title: 'Owsianka na wytrawnie z jajkiem i szpinakiem',
    description:
      'Płatki owsiane ugotowane na bulionie z czosnkiem i szpinakiem, z parmezanem i jajkiem w koszulce na wierzchu. Wytrawna, rozgrzewająca miska dla tych, którzy rano nie lubią na słodko.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['bulion warzywny', 350, 'ml'],
      ['szpinak', 100, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['jajko', 2, 'szt'],
      ['ser parmezan', 20, 'g'],
      ['pestki dyni', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Czosnek posiekaj drobno i podsmaż na oliwie w rondlu przez 30 sekund, aż zacznie pachnieć.',
      'Wlej bulion warzywny, zagotuj, wsyp płatki owsiane i gotuj na małym ogniu 5 minut, mieszając.',
      'Dodaj szpinak i gotuj jeszcze 1–2 minuty, aż liście zwiędną; zdejmij z ognia i wmieszaj połowę startego parmezanu oraz pieprz.',
      'W osobnym garnku zagotuj wodę, zmniejsz ogień tak, by ledwo mrugała, zamieszaj wir i wbij po kolei jajka; gotuj 3 minuty, aż białko się zetnie, a żółtko zostanie płynne.',
      'Pestki dyni upraż na suchej patelni przez 2 minuty.',
      'Przełóż owsiankę do misek, na każdej połóż jajko w koszulce, posyp resztą parmezanu, pestkami dyni i świeżo mielonym pieprzem.',
    ],
    photo:
      'Savory green oatmeal with wilted spinach topped with a poached egg with runny yolk, grated parmesan, toasted pumpkin seeds and black pepper',
    vessel: 'bowl',
  },
  {
    plan: 'sn-34',
    title: 'Musli Bircher z tartym jabłkiem i orzechami',
    description:
      'Szwajcarska owsianka na zimno: płatki namoczone w jogurcie i mleku z tartym jabłkiem, rodzynkami i orzechami laskowymi. Przygotujesz ją wieczorem, a rano wystarczy wyjąć z lodówki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 90, 'g'],
      ['jogurt naturalny', 200, 'g'],
      ['mleko', 150, 'ml'],
      ['jabłko', 1, 'szt'],
      ['cytryna', 10, 'g'],
      ['rodzynka', 20, 'g'],
      ['orzech laskowy', 25, 'g'],
      ['miód', 10, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'W misce wymieszaj płatki owsiane z jogurtem naturalnym, mlekiem, rodzynkami i cynamonem.',
      'Jabłko umyj i zetrzyj ze skórką na tarce o grubych oczkach, od razu skrop sokiem z cytryny, żeby nie ściemniało, i wmieszaj do płatków.',
      'Przykryj miskę i wstaw do lodówki na co najmniej 30 minut, a najlepiej na całą noc — płatki wchłoną płyn i zmiękną.',
      'Orzechy laskowe posiekaj grubo i upraż na suchej patelni 2–3 minuty.',
      'Rano zamieszaj musli (jeśli jest za gęste, dolej łyżkę mleka), rozłóż do misek, polej miodem i posyp orzechami.',
    ],
    photo:
      'Creamy bircher muesli with grated apple and raisins in a bowl, topped with chopped toasted hazelnuts and a drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'sn-35',
    title: 'Jaglanka czekoladowa z gruszką',
    description:
      'Kasza jaglana ugotowana na mleku z kakao i miodem na gęsty, czekoladowy krem, podana z soczystą gruszką i orzechami laskowymi. Smakuje jak deser, a jest pełnowartościowym śniadaniem.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['kasza jaglana', 100, 'g'],
      ['mleko', 450, 'ml'],
      ['kakao', 15, 'g'],
      ['miód', 20, 'g'],
      ['gruszka', 1, 'szt'],
      ['orzech laskowy', 15, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz na sitku najpierw zimną, potem wrzącą wodą — zniknie goryczka.',
      'Wsyp kaszę do rondla, wlej mleko, dodaj szczyptę soli i zagotuj; gotuj pod przykryciem na małym ogniu 15 minut, mieszając od czasu do czasu, aż kasza wchłonie mleko.',
      'Wmieszaj kakao i miód, a następnie zmiksuj kaszę blenderem na gładki krem (albo zostaw ziarnistą, jeśli wolisz).',
      'Gruszkę umyj, usuń gniazdo nasienne i pokrój w kostkę; orzechy laskowe posiekaj grubo.',
      'Przełóż jaglankę do misek, ułóż na wierzchu gruszkę i posyp orzechami.',
    ],
    photo:
      'Smooth dark chocolate millet porridge topped with diced fresh pear and chopped hazelnuts',
    vessel: 'bowl',
  },
  {
    plan: 'sn-36',
    title: 'Kasza jaglana z musem z mango i jogurtem',
    description:
      'Delikatna jaglanka na mleku przykryta warstwą musu z dojrzałego mango z limonką, z jogurtem greckim i wiórkami kokosowymi. Słoneczne, owocowe śniadanie, które da się zabrać w słoiku.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['kasza jaglana', 100, 'g'],
      ['mleko', 400, 'ml'],
      ['mango', 1, 'szt'],
      ['limonka', 20, 'g'],
      ['miód', 10, 'g'],
      ['jogurt grecki', 100, 'g'],
      ['wiórki kokosowe', 10, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz na sitku zimną, a potem wrzącą wodą.',
      'Zagotuj mleko ze szczyptą soli, wsyp kaszę i gotuj pod przykryciem na małym ogniu 15 minut, aż wchłonie mleko i będzie miękka.',
      'Mango obierz, odkrój miąższ od pestki i zmiksuj z sokiem z limonki i miodem na gładki mus; odłóż kilka kostek do dekoracji.',
      'Wiórki kokosowe upraż na suchej patelni przez minutę, aż się lekko zezłocą.',
      'Rozłóż kaszę do misek, polej musem z mango, dodaj po łyżce jogurtu greckiego, kostki mango i posyp wiórkami.',
    ],
    photo:
      'Creamy millet porridge covered with bright orange mango puree, a spoon of white greek yogurt, mango cubes and toasted coconut flakes',
    vessel: 'bowl',
  },
  {
    plan: 'sn-37',
    title: 'Kasza manna na mleku z sokiem malinowym',
    description:
      'Gładka, gęsta kasza manna na mleku z odrobiną masła i wanilii, polana malinowym sokiem i świeżymi malinami. Smak dzieciństwa gotowy w dziesięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['mleko', 500, 'ml'],
      ['kasza manna', 70, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['masło', 10, 'g'],
      ['syrop malinowy', 40, 'ml'],
      ['malina', 80, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Mleko zagotuj w rondlu ze szczyptą soli i cukrem waniliowym, uważając, żeby nie wykipiało.',
      'Zmniejsz ogień i wsypuj kaszę mannę cienkim strumieniem, cały czas mieszając trzepaczką, żeby nie powstały grudki.',
      'Gotuj 3–4 minuty, mieszając, aż kasza zgęstnieje; zdejmij z ognia i wmieszaj masło.',
      'Przelej kaszę do misek i odstaw na minutę, aż na wierzchu lekko się zetnie.',
      'Polej każdą porcję sokiem malinowym i udekoruj świeżymi malinami.',
    ],
    photo:
      'Smooth white semolina porridge drizzled with bright red raspberry syrup and topped with fresh raspberries',
    vessel: 'bowl',
  },
  {
    plan: 'sn-38',
    title: 'Ryż na mleku z jabłkami i cynamonem',
    description:
      'Kremowy ryż gotowany powoli na mleku z wanilią, podany z jabłkami podsmażonymi na maśle z cynamonem. Ciepłe, słodkie śniadanie na chłodny poranek, dobre też na zimno z lodówki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['ryż biały', 100, 'g'],
      ['mleko', 600, 'ml'],
      ['cukier waniliowy', 8, 'g'],
      ['jabłko', 2, 'szt'],
      ['masło', 10, 'g'],
      ['cukier', 15, 'g'],
      ['cynamon', 2, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Ryż przepłucz na sitku zimną wodą.',
      'W rondlu z grubym dnem zagotuj mleko z cukrem waniliowym i szczyptą soli, wsyp ryż i gotuj pod przykryciem na najmniejszym ogniu 25–30 minut, co kilka minut mieszając, aż ziarna zmiękną, a ryż będzie kremowy.',
      'W tym czasie jabłka obierz, usuń gniazda nasienne i pokrój w kostkę 1 cm.',
      'Na patelni rozpuść masło, dodaj jabłka, cukier i cynamon; smaż 5–6 minut, mieszając, aż jabłka zmiękną i się skarmelizują.',
      'Rozłóż ryż do misek, na wierzch nałóż ciepłe jabłka z sosem i oprósz szczyptą cynamonu.',
    ],
    photo:
      'Creamy rice pudding topped with golden caramelized apple cubes in cinnamon butter sauce, dusted with cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'sn-39',
    title: 'Domowa granola z jogurtem i owocami',
    description:
      'Chrupiąca granola upieczona z płatków owsianych, orzechów laskowych i pestek dyni z miodem, podana z jogurtem naturalnym, truskawkami i borówkami. Pachnie cynamonem i nie ma w niej nic zbędnego.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 80, 'g'],
      ['orzech laskowy', 20, 'g'],
      ['pestki dyni', 15, 'g'],
      ['miód', 25, 'g'],
      ['olej kokosowy', 15, 'g'],
      ['cynamon', 1, 'g'],
      ['sól', 0.5, 'g'],
      ['jogurt naturalny', 300, 'g'],
      ['truskawka', 150, 'g'],
      ['borówka', 80, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 160°C (góra–dół), blachę wyłóż papierem do pieczenia.',
      'Orzechy laskowe posiekaj grubo. W misce wymieszaj płatki owsiane, orzechy, pestki dyni, cynamon i szczyptę soli.',
      'Olej kokosowy rozpuść z miodem w rondelku, wlej do suchych składników i dokładnie wymieszaj, aż wszystko się lekko sklei.',
      'Rozłóż masę cienką warstwą na blasze i piecz 15–18 minut, mieszając w połowie, aż granola będzie złota; wyjmij i ostudź — chrupkość złapie dopiero po wystygnięciu.',
      'Truskawki umyj, usuń szypułki i pokrój na ćwiartki; borówki opłucz.',
      'Nałóż jogurt naturalny do misek, posyp granolą i ułóż na wierzchu truskawki i borówki.',
    ],
    photo:
      'White natural yogurt topped with golden clustered homemade granola with hazelnuts and pumpkin seeds, quartered strawberries and blueberries',
    vessel: 'bowl',
  },
  {
    plan: 'sn-40',
    title: 'Jogurt grecki z miodem, orzechami i gruszką',
    description:
      'Gęsty jogurt grecki z gruszką skarmelizowaną na maśle z miodem i chrupiącymi orzechami włoskimi. Śniadanie w pięć minut, które wygląda jak deser z kawiarni.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['jogurt grecki', 350, 'g'],
      ['gruszka', 1, 'szt'],
      ['masło', 10, 'g'],
      ['miód', 25, 'g'],
      ['orzech włoski', 40, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Gruszkę umyj, przekrój na ćwiartki, usuń gniazdo nasienne i pokrój w cząstki grubości 1 cm.',
      'Na patelni rozpuść masło, ułóż cząstki gruszki i smaż 2 minuty z każdej strony; dodaj połowę miodu i cynamon, podgrzewaj jeszcze minutę, aż gruszka się zeszkli.',
      'Orzechy włoskie połam i wrzuć na patelnię na ostatnią minutę, żeby się uprażyły.',
      'Jogurt grecki rozłóż do misek, robiąc łyżką zagłębienie na środku.',
      'Ułóż na jogurcie ciepłą gruszkę z orzechami, polej sosem z patelni i resztą miodu.',
    ],
    photo:
      'Thick white greek yogurt topped with golden caramelized pear wedges, toasted walnuts and a drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'sn-41',
    title: 'Twarożek ze szczypiorkiem i rzodkiewką na żytnim chlebie',
    description:
      'Twaróg rozgnieciony z jogurtem, mnóstwem szczypiorku i chrupiącej rzodkiewki, podany na kromkach żytniego chleba z masłem. Klasyczne polskie śniadanie na wiosnę i lato.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['ser twaróg półtłusty', 250, 'g'],
      ['jogurt naturalny', 60, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['szczypiorek', 15, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 160, 'g'],
      ['masło', 10, 'g'],
    ],
    steps: [
      'Twaróg rozgnieć widelcem w misce i wymieszaj z jogurtem naturalnym na kremową, lekko grudkowatą pastę.',
      'Rzodkiewki umyj, odetnij końcówki; większość pokrój w drobną kostkę, a 3–4 zostaw w plasterkach do dekoracji.',
      'Szczypiorek posiekaj drobno.',
      'Wmieszaj do twarogu kostkę z rzodkiewki i szczypiorek, dopraw solą i pieprzem.',
      'Kromki chleba żytniego cienko posmaruj masłem, nałóż twarożek, udekoruj plasterkami rzodkiewki i szczyptą szczypiorku.',
    ],
    photo:
      'Slices of dark rye bread topped with white cottage cheese spread speckled with green chives and diced red radish, garnished with radish slices',
  },
  {
    plan: 'sn-42',
    title: 'Serek wiejski z pomidorem i szczypiorkiem',
    description:
      'Serek wiejski z soczystym pomidorem, szczypiorkiem i świeżo mielonym pieprzem, podany z chrupiącą grahamką z masłem. Lekkie, białkowe śniadanie bez gotowania, gotowe w pięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    ingredients: [
      ['serek wiejski', 400, 'g'],
      ['pomidor', 2, 'szt'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 0.5, 'g'],
      ['bułka grahamka', 2, 'szt'],
      ['masło', 10, 'g'],
    ],
    steps: [
      'Pomidory umyj, usuń zielone gniazda i pokrój w kostkę 1 cm; lekko posól.',
      'Szczypiorek posiekaj drobno.',
      'Serek wiejski przełóż do misek, wymieszaj z połową pomidorów i szczypiorku.',
      'Na wierzch wyłóż resztę pomidorów, posyp szczypiorkiem i świeżo mielonym pieprzem.',
      'Grahamki przekrój, posmaruj masłem i podawaj obok serka.',
    ],
    photo:
      'Cottage cheese in a bowl topped with diced red tomatoes, chopped chives and black pepper, with a halved buttered graham roll beside',
    vessel: 'bowl',
  },
  {
    plan: 'sn-43',
    title: 'Kanapki z pieczoną piersią indyka i żurawiną',
    description:
      'Domowa pieczona pierś z indyka z czosnkiem i majerankiem, pokrojona w plastry i ułożona na chlebie z serkiem, sałatą i sosem żurawinowym. Zamiast sklepowej wędliny — soczysta i bez konserwantów.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['filet z indyka', 250, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['czosnek', 1, 'szt'],
      ['majeranek', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb pełnoziarnisty', 160, 'g'],
      ['serek kremowy', 40, 'g'],
      ['sałata rzymska', 40, 'g'],
      ['sos żurawinowy', 40, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 200°C (góra–dół). Czosnek przeciśnij przez praskę i wymieszaj z olejem, majerankiem, papryką, solą i pieprzem.',
      'Natrzyj filet z indyka marynatą ze wszystkich stron, ułóż w małym naczyniu żaroodpornym.',
      'Piecz 25 minut, aż mięso w najgrubszym miejscu będzie białe, a wypływający sok przezroczysty.',
      'Wyjmij indyka, przykryj folią i odstaw na 10 minut, żeby soki się rozeszły; potem pokrój w cienkie plastry w poprzek włókien.',
      'Kromki chleba posmaruj serkiem kremowym, ułóż liście sałaty rzymskiej i plastry indyka.',
      'Na każdą kanapkę nałóż łyżeczkę sosu żurawinowego i podawaj od razu.',
    ],
    photo:
      'Open-faced wholegrain sandwiches with cream cheese, romaine leaves, thin slices of roast turkey breast and glossy red cranberry sauce',
    vessel: 'board',
  },
  {
    plan: 'sn-44',
    title: 'Pasta z pieczonego indyka z jajkiem i ogórkiem kiszonym',
    description:
      'Pieczony filet z indyka posiekany z jajkami na twardo, ogórkiem kiszonym i szczypiorkiem, związany odrobiną majonezu i jogurtu. Sycąca pasta do chleba, która w lodówce postoi dwa dni.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    ingredients: [
      ['filet z indyka', 200, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['majeranek', 1, 'g'],
      ['jajko', 2, 'szt'],
      ['ogórek kiszony', 80, 'g'],
      ['szczypiorek', 10, 'g'],
      ['majonez', 20, 'g'],
      ['jogurt naturalny', 40, 'g'],
      ['musztarda', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 160, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 200°C (góra–dół). Filet z indyka natrzyj olejem, majerankiem, solą i pieprzem, zawiń luźno w folię aluminiową i piecz 25 minut; ostudź w folii.',
      'W tym czasie jajka ugotuj na twardo (9 minut od zagotowania), przełóż do zimnej wody, obierz.',
      'Ostudzonego indyka pokrój w bardzo drobną kostkę (albo zmiel krótko w malakserze); jajka i ogórka kiszonego posiekaj drobno.',
      'Szczypiorek posiekaj. Wymieszaj majonez z jogurtem naturalnym i musztardą.',
      'Połącz indyka, jajka, ogórka i szczypiorek z sosem, dopraw solą i pieprzem do smaku.',
      'Nałóż pastę grubo na kromki chleba żytniego i posyp resztką szczypiorku.',
    ],
    photo:
      'Rye bread slices spread thickly with chunky turkey and egg paste with bits of pickled cucumber and green chives',
    vessel: 'board',
  },
  {
    plan: 'sn-45',
    title: 'Pasta z białej fasoli z czosnkiem i koperkiem',
    description:
      'Aksamitna pasta z białej fasoli z czosnkiem, cytryną, oliwą i dużą ilością koperku, podana na chlebie z plastrami pomidora. Roślinne, sycące smarowidło, które zrobisz blenderem w pięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['fasola biała z puszki', 240, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 15, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['koperek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb pełnoziarnisty', 160, 'g'],
      ['pomidor', 1, 'szt'],
    ],
    steps: [
      'Fasolę białą odsącz na sitku i przepłucz zimną wodą.',
      'Zmiksuj fasolę z czosnkiem, sokiem z cytryny, oliwą i 2 łyżkami zimnej wody na gładką pastę.',
      'Koperek posiekaj drobno i wmieszaj do pasty, zostawiając szczyptę do posypania; dopraw solą i pieprzem.',
      'Pomidora pokrój w cienkie plastry.',
      'Nałóż pastę na kromki chleba pełnoziarnistego, połóż plastry pomidora, posyp koperkiem i świeżo mielonym pieprzem.',
    ],
    photo:
      'Wholegrain bread slices spread with creamy white bean dip flecked with dill, topped with tomato slices and fresh dill sprigs',
    vessel: 'board',
  },
  {
    plan: 'sn-46',
    title: 'Pasta z wędzonej makreli z twarożkiem',
    description:
      'Wędzona makrela rozgnieciona z twarogiem, czerwoną cebulą, cytryną i szczypiorkiem — wyrazista, lekko dymna pasta na żytni chleb z ogórkiem. Bogata w białko i tłuszcze omega-3, gotowa w dziesięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['makrela wędzona', 150, 'g'],
      ['ser twaróg półtłusty', 150, 'g'],
      ['jogurt naturalny', 30, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['cytryna', 10, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 140, 'g'],
      ['ogórek', 100, 'g'],
    ],
    steps: [
      'Makrelę obierz ze skóry i dokładnie wybierz wszystkie ości, mięso rozdrobnij widelcem.',
      'Cebulę czerwoną posiekaj bardzo drobno, szczypiorek pokrój.',
      'Twaróg rozgnieć w misce z jogurtem naturalnym, dodaj makrelę, cebulę, sok z cytryny i większość szczypiorku; wymieszaj na grudkowatą pastę i dopraw pieprzem (soli nie trzeba — ryba jest słona).',
      'Ogórka pokrój w cienkie plasterki.',
      'Nałóż pastę na kromki chleba żytniego, ułóż plasterki ogórka i posyp resztą szczypiorku.',
    ],
    photo:
      'Dark rye bread topped with pale smoked mackerel and cottage cheese spread with red onion bits, cucumber slices and chives',
    vessel: 'board',
  },
  {
    plan: 'sn-47',
    title: 'Kanapki z pastą z pieczonej papryki i fetą',
    description:
      'Słodka pieczona papryka zmiksowana z orzechami włoskimi, czosnkiem i wędzoną papryką na intensywnie czerwoną pastę, podana na chlebie z pokruszoną fetą i rukolą. Świetna też jako dip do pudełka.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    ingredients: [
      ['papryka czerwona', 2, 'szt'],
      ['orzech włoski', 20, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka wędzona mielona', 1, 'g'],
      ['sól', 0.5, 'g'],
      ['chleb pełnoziarnisty', 160, 'g'],
      ['ser feta', 80, 'g'],
      ['rukola', 20, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 220°C (góra–dół). Paprykę przekrój na połówki, usuń gniazda nasienne i ułóż skórą do góry na blasze z papierem.',
      'Piecz 25 minut, aż skórka sczernieje i zacznie odchodzić; przełóż paprykę do miski, przykryj talerzem na 5 minut, potem zdejmij skórkę.',
      'Orzechy włoskie upraż na suchej patelni przez 2 minuty.',
      'Zmiksuj paprykę z orzechami, czosnkiem, oliwą, wędzoną papryką i solą na gęstą pastę.',
      'Kromki chleba posmaruj grubo pastą, posyp pokruszoną fetą i ułóż kilka listków rukoli.',
    ],
    photo:
      'Wholegrain bread slices with vivid red roasted pepper spread, crumbled white feta cheese and fresh green rocket leaves',
    vessel: 'board',
  },
  {
    plan: 'sn-48',
    title: 'Bajgiel z serkiem, szynką i rukolą',
    description:
      'Przypieczony bajgiel przełożony serkiem kremowym, szynką, plastrami pomidora, czerwoną cebulą i rukolą. Sycąca kanapka, którą łatwo zawinąć w papier i zjeść w drodze do pracy.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['bajgiel', 2, 'szt'],
      ['serek kremowy', 60, 'g'],
      ['szynka', 100, 'g'],
      ['pomidor', 1, 'szt'],
      ['cebula czerwona', 20, 'g'],
      ['rukola', 30, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Bajgle przekrój poziomo na pół i opiecz w tosterze albo na suchej patelni 1–2 minuty, aż się lekko zarumienią.',
      'Pomidora pokrój w plastry, cebulę czerwoną w cienkie piórka.',
      'Dolne i górne połówki bajgli posmaruj grubo serkiem kremowym i oprósz pieprzem.',
      'Na dolnych połówkach ułóż szynkę, plastry pomidora, cebulę i garść rukoli.',
      'Przykryj górnymi połówkami, lekko dociśnij i przekrój na pół — podawaj od razu.',
    ],
    photo:
      'Toasted bagel sandwich with cream cheese, pink ham slices, tomato, red onion and green rocket, cut in half to show the layers',
    vessel: 'board',
  },
  {
    plan: 'sn-49',
    title: 'Tost z masłem orzechowym i bananem',
    description:
      'Chrupiące tosty z pełnoziarnistego chleba z grubą warstwą masła orzechowego, plasterkami banana, miodem i cynamonem. Szybka dawka energii przed treningiem albo długim dniem.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    ingredients: [
      ['chleb pełnoziarnisty', 140, 'g'],
      ['masło orzechowe', 50, 'g'],
      ['banan', 2, 'szt'],
      ['miód', 10, 'g'],
      ['cynamon', 1, 'g'],
      ['nasiona chia', 5, 'g'],
    ],
    steps: [
      'Kromki chleba pełnoziarnistego opiecz w tosterze na złoto.',
      'Jeszcze ciepłe posmaruj grubo masłem orzechowym — lekko się rozpuści.',
      'Banany obierz i pokrój w plasterki grubości 5 mm.',
      'Ułóż plasterki banana na tostach, polej cienko miodem.',
      'Posyp cynamonem i nasionami chia, podawaj od razu.',
    ],
    photo:
      'Golden wholegrain toasts spread with peanut butter, topped with overlapping banana slices, honey drizzle, cinnamon and chia seeds',
    vessel: 'board',
  },
  {
    plan: 'sn-50',
    title: 'Tost z ricottą, miodem i gruszką',
    description:
      'Opieczony chleb orkiszowy z kremową ricottą, cienkimi plastrami gruszki, orzechami włoskimi i miodem, doprawiony szczyptą pieprzu. Połączenie słodkiego i łagodnie pikantnego na leniwe śniadanie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['chleb orkiszowy', 140, 'g'],
      ['ser ricotta', 200, 'g'],
      ['gruszka', 1, 'szt'],
      ['orzech włoski', 20, 'g'],
      ['miód', 20, 'g'],
      ['pieprz czarny', 0.5, 'g'],
    ],
    steps: [
      'Kromki chleba orkiszowego opiecz w tosterze albo na suchej patelni, aż będą chrupiące.',
      'Orzechy włoskie posiekaj grubo i upraż na suchej patelni przez 2 minuty.',
      'Gruszkę umyj, usuń gniazdo nasienne i pokrój w cienkie plastry.',
      'Tosty posmaruj grubą warstwą ricotty i ułóż na niej plastry gruszki.',
      'Polej miodem, posyp orzechami i odrobiną świeżo mielonego pieprzu.',
    ],
    photo:
      'Toasted spelt bread topped with creamy white ricotta, thin pear slices, chopped walnuts and a golden honey drizzle',
    vessel: 'board',
  },
  {
    plan: 'sn-51',
    title: 'Jajecznica z pieczarkami i cebulką',
    description:
      'Puszysta jajecznica na maśle z podsmażonymi na złoto pieczarkami i cebulą, posypana szczypiorkiem i podana z chlebem. Domowy klasyk, który wychodzi zawsze.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['pieczarka', 250, 'g'],
      ['cebula', 80, 'g'],
      ['masło', 15, 'g'],
      ['jajko', 5, 'szt'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['szczypiorek', 10, 'g'],
      ['chleb', 100, 'g'],
    ],
    steps: [
      'Pieczarki oczyść i pokrój w plasterki, cebulę w drobną kostkę.',
      'Na patelni rozpuść masło, zeszklij cebulę przez 3 minuty, dodaj pieczarki i smaż na średnim ogniu 6–7 minut, aż odparuje woda i zaczną się rumienić; dopraw połową soli.',
      'Jajka roztrzep w misce z resztą soli i pieprzem.',
      'Zmniejsz ogień, wlej jajka na pieczarki i mieszaj szpatułką od brzegów do środka przez 2–3 minuty; zdejmij z ognia, gdy jajecznica jest ścięta, ale jeszcze wilgotna.',
      'Przełóż na talerze, posyp posiekanym szczypiorkiem i podawaj z kromkami chleba.',
    ],
    photo:
      'Soft fluffy scrambled eggs with golden sautéed mushroom slices and onion, sprinkled with chives, with slices of bread on the side',
  },
  {
    plan: 'sn-52',
    title: 'Jajecznica z łososiem wędzonym i koperkiem',
    description:
      'Kremowa jajecznica ścinana powoli na maśle, wymieszana z płatkami wędzonego łososia i świeżym koperkiem, podana na żytnim chlebie. Odświętne śniadanie na weekend bez wysiłku.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['jajko', 5, 'szt'],
      ['masło', 15, 'g'],
      ['łosoś wędzony', 100, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 100, 'g'],
    ],
    steps: [
      'Łososia wędzonego porwij na paski szerokości 2 cm, koperek posiekaj drobno.',
      'Jajka roztrzep z odrobiną soli (łosoś jest słony) i pieprzem.',
      'Na patelni na małym ogniu rozpuść masło, wlej jajka i mieszaj szpatułką przez 3–4 minuty, aż zaczną się ścinać w miękkie, kremowe grudki.',
      'Zdejmij patelnię z ognia, dodaj łososia i większość koperku, delikatnie wymieszaj — ciepło jajek wystarczy, żeby łosoś się ogrzał.',
      'Kromki chleba żytniego opiecz, nałóż na nie jajecznicę i posyp resztą koperku oraz pieprzem.',
    ],
    photo:
      'Creamy scrambled eggs folded with pink smoked salmon ribbons and fresh dill, served on toasted rye bread with black pepper',
  },
  {
    plan: 'sn-53',
    title: 'Jajka po turecku z jogurtem czosnkowym',
    description:
      'Jajka w koszulce na chłodnym jogurcie z czosnkiem, polane gorącym masłem z papryką — turecki çılbır w domowej wersji. Do maczania chrupiąca ciabatta.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['jogurt grecki', 250, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 1, 'g'],
      ['ocet jabłkowy', 15, 'ml'],
      ['jajko', 4, 'szt'],
      ['masło', 25, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['koperek', 5, 'g'],
      ['ciabatta', 120, 'g'],
    ],
    steps: [
      'Jogurt grecki wyjmij z lodówki 10 minut wcześniej, wymieszaj z przeciśniętym przez praskę czosnkiem i solą, rozsmaruj na dwóch głębokich talerzach.',
      'W szerokim garnku zagotuj wodę z octem jabłkowym, zmniejsz ogień, aż woda będzie ledwo mrugać.',
      'Każde jajko wbij najpierw do filiżanki, zamieszaj w wodzie wir i wpuść jajko na środek; gotuj 3 minuty, wyjmij łyżką cedzakową i odsącz na ręczniku papierowym. Tak samo ugotuj pozostałe.',
      'W rondelku rozpuść masło, zdejmij z ognia i wmieszaj obie papryki — masło zabarwi się na czerwono.',
      'Ciabattę pokrój na kromki i opiecz na suchej patelni.',
      'Ułóż po dwa jajka na jogurcie, polej paprykowym masłem, posyp posiekanym koperkiem i podawaj z ciabattą.',
    ],
    photo:
      'Two poached eggs on a bed of white garlic yogurt drizzled with bright red paprika butter, sprinkled with dill, with toasted ciabatta slices',
  },
  {
    plan: 'sn-54',
    title: 'Jajka sadzone na szpinaku z czosnkiem',
    description:
      'Młody szpinak szybko podduszony z czosnkiem i gałką muszkatołową, z dwoma jajkami sadzonymi o płynnych żółtkach. Lekkie, zielone śniadanie z grzanką do wycierania talerza.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['oliwa z oliwek', 15, 'ml'],
      ['czosnek', 2, 'szt'],
      ['szpinak', 300, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['jajko', 4, 'szt'],
      ['chleb pełnoziarnisty', 100, 'g'],
    ],
    steps: [
      'Czosnek pokrój w cienkie plasterki, szpinak opłucz i osusz.',
      'Na dużej patelni rozgrzej oliwę, podsmaż czosnek przez 30 sekund, aż zacznie pachnieć (nie rumień go mocno).',
      'Wrzuć szpinak garściami i mieszaj 2–3 minuty, aż zwiędnie; dopraw połową soli, pieprzem i startą gałką muszkatołową.',
      'Zrób w szpinaku cztery dołki i wbij do nich jajka, posól białka resztą soli.',
      'Przykryj patelnię i smaż na małym ogniu 3–4 minuty, aż białka się zetną, a żółtka pozostaną płynne.',
      'Chleb opiecz w tosterze; podawaj jajka ze szpinakiem prosto z patelni z grzankami.',
    ],
    photo:
      'Four sunny-side-up eggs with runny yolks nestled in garlicky wilted spinach, with toasted wholegrain bread on the side',
  },
  {
    plan: 'sn-55',
    title: 'Jajka w majonezie ze szczypiorkiem',
    description:
      'Połówki jajek na twardo pod kołderką majonezu, obsypane szczypiorkiem, na liściach sałaty z pomidorem. Świąteczny klasyk, który świetnie sprawdza się też w zwykły poranek z kajzerką.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['jajko', 6, 'szt'],
      ['majonez', 40, 'g'],
      ['szczypiorek', 10, 'g'],
      ['sałata rzymska', 40, 'g'],
      ['pomidor', 1, 'szt'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['bułka kajzerka', 2, 'szt'],
    ],
    steps: [
      'Jajka włóż do garnka z zimną wodą, zagotuj i gotuj 9 minut; przełóż do zimnej wody na 5 minut, potem obierz.',
      'Liście sałaty rzymskiej umyj, osusz i ułóż na talerzach; pomidora pokrój w ósemki i dołóż obok.',
      'Jajka przekrój wzdłuż na połówki i ułóż na sałacie żółtkiem do góry.',
      'Każdą połówkę posól, popieprz i przykryj łyżeczką majonezu.',
      'Posyp obficie drobno posiekanym szczypiorkiem i podawaj z kajzerkami.',
    ],
    photo:
      'Halved hard-boiled eggs covered with mayonnaise and chopped chives arranged on romaine lettuce with tomato wedges and a crusty roll',
  },
  {
    plan: 'sn-56',
    title: 'Omlet z serkiem wiejskim i szczypiorkiem',
    description:
      'Puszysty omlet z jajek wymieszanych z serkiem wiejskim, który w środku robi się kremowy, z mnóstwem szczypiorku. Dużo białka przy niewielu kaloriach — dobry start aktywnego dnia.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['jajko', 5, 'szt'],
      ['serek wiejski', 200, 'g'],
      ['szczypiorek', 15, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['masło', 10, 'g'],
      ['pomidor', 1, 'szt'],
      ['chleb żytni', 80, 'g'],
    ],
    steps: [
      'Jajka roztrzep w misce z solą i pieprzem, wmieszaj serek wiejski i większość posiekanego szczypiorku.',
      'Na patelni o średnicy 20–22 cm rozpuść połowę masła na średnim ogniu.',
      'Wlej połowę masy, przykryj i smaż 4–5 minut, aż spód się zrumieni, a wierzch prawie zetnie; złóż omlet na pół i przesuń na talerz.',
      'Tak samo usmaż drugi omlet na reszcie masła.',
      'Pomidora pokrój w plastry. Podawaj omlety posypane szczypiorkiem, z pomidorem i kromką chleba żytniego.',
    ],
    photo:
      'Folded golden omelette with creamy cottage cheese curds and green chives peeking out, with tomato slices and a slice of rye bread',
  },
  {
    plan: 'sn-57',
    title: 'Omlet z suszonymi pomidorami i bazylią',
    description:
      'Omlet z suszonymi pomidorami, parmezanem i świeżą bazylią — śródziemnomorski smak z produktów, które zwykle stoją w szafce. Podany z chrupiącą bagietką.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['jajko', 6, 'szt'],
      ['mleko', 30, 'ml'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['pomidor suszony w oleju', 50, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['ser parmezan', 20, 'g'],
      ['bazylia', 10, 'g'],
      ['bagietka', 80, 'g'],
    ],
    steps: [
      'Pomidory suszone odsącz z oleju i pokrój w cienkie paski; liście bazylii porwij, kilka zostaw całych.',
      'Jajka roztrzep z mlekiem, solą, pieprzem i połową startego parmezanu.',
      'Na patelni rozgrzej połowę oliwy, wlej połowę masy jajecznej i posyp połową pomidorów.',
      'Smaż pod przykryciem na małym ogniu 3–4 minuty, aż wierzch się zetnie; rozłóż na połowie omletu połowę bazylii, złóż i zsuń na talerz. Drugi omlet usmaż tak samo.',
      'Posyp omlety resztą parmezanu i całymi listkami bazylii, podawaj z pokrojoną bagietką.',
    ],
    photo:
      'Folded yellow omelette filled with red sun-dried tomato strips and fresh basil, topped with grated parmesan, with baguette slices',
  },
  {
    plan: 'sn-58',
    title: 'Jajka zapiekane w bułce z szynką i serem',
    description:
      'Wydrążone kajzerki wyłożone szynką, z jajkiem i żółtym serem, zapieczone na chrupko z płynnym żółtkiem w środku. Efektowne śniadanie na weekend z tego, co jest w lodówce.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['bułka kajzerka', 4, 'szt'],
      ['masło', 10, 'g'],
      ['szynka', 60, 'g'],
      ['jajko', 4, 'szt'],
      ['ser żółty', 40, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['szczypiorek', 5, 'g'],
    ],
    steps: [
      'Piekarnik nagrzej do 190°C (góra–dół), blachę wyłóż papierem.',
      'Z każdej kajzerki odetnij wierzch i wydrąż środek, zostawiając ścianki i spód grubości ok. 1 cm; wnętrze posmaruj cienko masłem.',
      'Wyłóż bułki plastrami szynki tak, żeby utworzyły miseczkę, a do środka wbij po jednym jajku; posól i popieprz.',
      'Posyp brzegi startym serem żółtym, ułóż bułki na blasze (odcięte wierzchy połóż obok).',
      'Piecz 15–18 minut, aż białko się zetnie, a żółtko pozostanie lekko płynne — przy 20 minutach będzie ścięte.',
      'Posyp posiekanym szczypiorkiem i podawaj od razu, z przypieczonymi wierzchami bułek do maczania.',
    ],
    photo:
      'Four crusty rolls hollowed out and baked with ham, a whole egg with glossy yolk and melted golden cheese, sprinkled with chives',
    vessel: 'board',
  },
  {
    plan: 'sn-59',
    title: 'Ziemniaki z patelni z kiełbasą i jajkiem sadzonym',
    description:
      'Rumiane kostki ziemniaków z kiełbasą i cebulą, doprawione papryką i majerankiem, z jajkiem sadzonym na wierzchu i ogórkiem kiszonym. Porządne, sycące śniadanie na długi dzień pracy.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['sól', 1, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['cebula', 1, 'szt'],
      ['kiełbasa', 130, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['majeranek', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['jajko', 2, 'szt'],
      ['szczypiorek', 5, 'g'],
      ['ogórek kiszony', 60, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i pokrój w kostkę 1,5 cm; wrzuć do wrzącej wody i gotuj 6 minut, potem dokładnie odsącz.',
      'Cebulę pokrój w piórka, kiełbasę w półplasterki grubości 5 mm.',
      'Na dużej patelni rozgrzej większość oleju, wyłóż ziemniaki jedną warstwą i smaż 10–12 minut, obracając co kilka minut, aż będą złote i chrupiące.',
      'Dodaj cebulę i kiełbasę, smaż jeszcze 5 minut; dopraw papryką, majerankiem, solą i pieprzem.',
      'Na małej patelni na reszcie oleju usmaż dwa jajka sadzone, aż białka się zetną, a żółtka zostaną płynne.',
      'Rozłóż ziemniaki na talerze, na każdej porcji połóż jajko, posyp szczypiorkiem i podawaj z ogórkiem kiszonym.',
    ],
    photo:
      'Golden crispy potato cubes pan-fried with sausage half-moons and onion, topped with a fried egg and chives, pickled cucumber on the side',
  },
  {
    plan: 'sn-60',
    title: 'Parówki na ciepło z pieczywem i warzywami',
    description:
      'Parówki podgrzane w gorącej wodzie, podane z musztardą, ketchupem, chlebem z masłem i talerzem świeżych warzyw. Szybkie śniadanie jak z dzieciństwa, lepsze dzięki porcji chrupiących dodatków.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['parówka', 4, 'szt'],
      ['chleb', 120, 'g'],
      ['masło', 10, 'g'],
      ['musztarda', 20, 'g'],
      ['ketchup', 20, 'g'],
      ['pomidor', 1, 'szt'],
      ['ogórek', 150, 'g'],
      ['papryka czerwona', 0.5, 'szt'],
      ['rzodkiewka', 60, 'g'],
    ],
    steps: [
      'Zagotuj wodę w garnku, zdejmij z ognia, włóż parówki i zostaw pod przykryciem na 5 minut — nie gotuj ich, bo pękną.',
      'W tym czasie pomidora pokrój w ósemki, ogórka w plastry, paprykę w paski, a rzodkiewki przekrój na połówki.',
      'Kromki chleba posmaruj cienko masłem.',
      'Parówki wyjmij łyżką cedzakową i osusz ręcznikiem papierowym.',
      'Podawaj parówki z musztardą i ketchupem, chlebem z masłem i ułożonymi obok warzywami.',
    ],
    photo:
      'Four warm pink frankfurters with dollops of mustard and ketchup, buttered bread slices and fresh tomato wedges, cucumber slices, red pepper strips and radishes',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
