/**
 * Katalog 500 — Śniadania, część C: pozycje sn-61 … sn-90
 * z `prisma/catalog/katalog-500-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const DEFS: Def[] = [
  {
    plan: 'sn-61',
    title: 'Tosty francuskie na wytrawnie z serem i szczypiorkiem',
    description:
      'Kromki chleba tostowego namoczone w jajku z mlekiem, usmażone na maśle i sklejone plastrem roztopionego sera. Chrupiące z wierzchu, miękkie w środku — dobry sposób na wczorajsze pieczywo w leniwy weekend.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['chleb tostowy', 150, 'g'],
      ['jajko', 3, 'szt'],
      ['mleko', 80, 'ml'],
      ['ser żółty', 60, 'g'],
      ['szczypiorek', 10, 'g'],
      ['masło', 20, 'g'],
      ['pomidor', 1, 'szt'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Posiekaj drobno szczypiorek, odłóż łyżkę do posypania. Ser pokrój w cienkie plasterki.',
      'W głębokim talerzu roztrzep jajka z mlekiem, solą, pieprzem i resztą szczypiorku.',
      'Rozgrzej połowę masła na patelni na średnim ogniu. Zanurzaj kromki chleba w masie jajecznej po kilka sekund z każdej strony, aż nasiąkną, ale się nie rozpadną.',
      'Smaż tosty po 2–3 minuty z każdej strony na złoty kolor, w razie potrzeby dokładając masła.',
      'Na połowę gorących tostów połóż ser, przykryj drugą kromką i przytrzymaj pod pokrywką minutę, aż ser się roztopi.',
      'Pokrój pomidor w plastry. Przekrój tosty po skosie, posyp szczypiorkiem i podaj z pomidorem.',
    ],
    photo:
      'Golden pan-fried savory French toast sandwiches cut diagonally with melted yellow cheese oozing out, sprinkled with chopped chives, tomato slices on the side',
  },
  {
    plan: 'sn-62',
    title: 'Pieczone pomidorki z fetą na grzance',
    description:
      'Koktajlowe pomidorki pieczone z oliwą, czosnkiem i oregano, aż pękną i puszczą sok, rozgniecione na chrupiącej grzance z kruszoną fetą. Śniadanie w klimacie śródziemnomorskim, najlepsze latem, gdy pomidory są najsłodsze.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['pomidor koktajlowy', 300, 'g'],
      ['ser feta', 100, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['czosnek', 2, 'szt'],
      ['oregano', 1, 'g'],
      ['miód', 5, 'g'],
      ['chleb pełnoziarnisty', 160, 'g'],
      ['bazylia', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Czosnek obierz i pokrój w plasterki.',
      'Pomidorki ułóż w małym naczyniu żaroodpornym, polej oliwą i miodem, dodaj czosnek, oregano i pieprz, wymieszaj.',
      'Piecz 18–20 minut, aż skórki popękają, a na dnie zbierze się sok.',
      'W tym czasie opiecz kromki chleba w tosterze albo na suchej patelni, aż będą chrupiące.',
      'Połóż grzanki na talerzach, nałóż pomidorki razem z sokiem i lekko rozgnieć je widelcem.',
      'Pokrusz na wierzch fetę, posyp listkami bazylii i od razu podawaj.',
    ],
    photo:
      'Toasted wholegrain bread topped with blistered roasted cherry tomatoes in their juices, crumbled white feta and fresh basil leaves',
  },
  {
    plan: 'sn-63',
    title: 'Tost z camembertem, żurawiną i orzechami',
    description:
      'Chrupiący tost z roztopionym camembertem, słodko-kwaśną żurawiną i garścią prażonych orzechów włoskich, podany z rukolą. Połączenie jak z deski serów, a gotowe w kwadrans — na śniadanie od święta.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['chleb tostowy', 150, 'g'],
      ['masło', 10, 'g'],
      ['ser camembert', 120, 'g'],
      ['sos żurawinowy', 40, 'g'],
      ['orzech włoski', 20, 'g'],
      ['rukola', 30, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C z termoobiegiem. Orzechy upraż na suchej patelni przez 2–3 minuty i posiekaj grubo.',
      'Kromki chleba posmaruj cienko masłem i ułóż na blasze wyłożonej papierem.',
      'Camembert pokrój w plastry grubości ok. 1 cm i rozłóż na chlebie.',
      'Zapiekaj 6–8 minut, aż ser się rozleje, a brzegi chleba zezłocą.',
      'Na każdy tost nałóż łyżeczkę sosu żurawinowego, posyp orzechami i pieprzem.',
      'Podawaj od razu z garścią rukoli na talerzu.',
    ],
    photo:
      'Toasted bread slices with melted camembert, glossy red cranberry sauce and chopped walnuts, a handful of rocket leaves on the side',
  },
  {
    plan: 'sn-64',
    title: 'Kanapki z łososiem wędzonym, serkiem i koperkiem',
    description:
      'Żytni chleb posmarowany serkiem z koperkiem i cytryną, z plastrami wędzonego łososia, ogórkiem i czerwoną cebulą. Klasyczne połączenie, które nie wymaga gotowania i wygląda jak ze śniadaniowej karty.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['chleb żytni', 160, 'g'],
      ['serek kremowy', 60, 'g'],
      ['łosoś wędzony', 120, 'g'],
      ['koperek', 8, 'g'],
      ['cytryna', 15, 'g'],
      ['ogórek', 0.5, 'szt'],
      ['cebula czerwona', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Posiekaj koperek, zostaw kilka gałązek do dekoracji.',
      'Serek wymieszaj z koperkiem, kilkoma kroplami soku z cytryny i pieprzem.',
      'Ogórek pokrój w cienkie plastry, a cebulę w bardzo cienkie półplasterki.',
      'Kromki chleba posmaruj grubo serkiem, ułóż plastry ogórka i pofalowane plastry łososia.',
      'Na wierzch połóż cebulę i gałązki koperku, skrop resztą soku z cytryny i podawaj.',
    ],
    photo:
      'Open rye bread sandwiches spread with cream cheese, topped with pink smoked salmon ribbons, cucumber slices, thin red onion and dill sprigs',
    vessel: 'board',
  },
  {
    plan: 'sn-65',
    title: 'Kanapki z polędwicą z indyka i serkiem ziołowym',
    description:
      'Pełnoziarnisty chleb z domowym serkiem ziołowym z natki i czosnku, chudą wędliną z indyka i chrupiącymi warzywami. Lekkie, sycące kanapki, które świetnie znoszą drogę w pudełku do pracy.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['chleb pełnoziarnisty', 160, 'g'],
      ['serek kanapkowy', 80, 'g'],
      ['natka pietruszki', 8, 'g'],
      ['szczypiorek', 5, 'g'],
      ['czosnek', 1, 'szt'],
      ['wędlina drobiowa', 120, 'g'],
      ['sałata rzymska', 40, 'g'],
      ['pomidor', 1, 'szt'],
      ['rzodkiewka', 50, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Natkę i szczypiorek posiekaj drobno, czosnek przeciśnij przez praskę.',
      'Wymieszaj serek kanapkowy z ziołami, czosnkiem i pieprzem.',
      'Pomidor i rzodkiewki pokrój w plasterki, liście sałaty umyj i osusz.',
      'Kromki chleba posmaruj serkiem ziołowym, ułóż sałatę i plastry polędwicy z indyka.',
      'Na wierzch połóż pomidor i rzodkiewkę, oprósz pieprzem i podawaj.',
    ],
    photo:
      'Wholegrain bread sandwiches with herbed cream cheese, romaine lettuce, folded slices of turkey breast ham, tomato and radish rounds',
    vessel: 'board',
  },
  {
    plan: 'sn-66',
    title: 'Wrap śniadaniowy z indykiem, jajkiem i szpinakiem',
    description:
      'Tortilla zawinięta z puszystą jajecznicą, szpinakiem, polędwicą z indyka i roztopionym serem, na koniec przyrumieniona na patelni. Śniadanie do ręki, które można zjeść w drodze albo zapakować na później.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['jajko', 4, 'szt'],
      ['szpinak', 60, 'g'],
      ['wędlina drobiowa', 80, 'g'],
      ['ser żółty', 30, 'g'],
      ['masło', 10, 'g'],
      ['pomidor', 1, 'szt'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pomidor pokrój w kostkę, wędlinę w paski, ser zetrzyj na tarce o grubych oczkach.',
      'Na patelni roztop masło, wrzuć szpinak i mieszaj 1 minutę, aż zwiędnie.',
      'Wbij jajka, dopraw solą i pieprzem, mieszaj na małym ogniu 2–3 minuty, aż jajecznica się zetnie, ale zostanie wilgotna.',
      'Tortille podgrzej chwilę na suchej patelni. Na środku każdej rozłóż jajecznicę ze szpinakiem, paski indyka, pomidor i ser.',
      'Zawiń boki do środka i zroluj ciasno. Połóż wrapy łączeniem w dół na patelni i przyrumień po minucie z każdej strony.',
      'Przekrój po skosie i podawaj na ciepło.',
    ],
    photo:
      'Two golden toasted tortilla wraps cut diagonally showing scrambled eggs, wilted spinach, turkey strips, diced tomato and melted cheese',
  },
  {
    plan: 'sn-67',
    title: 'Pasta serowa z jajkiem na chlebie żytnim',
    description:
      'Tarta żółty ser, posiekane jajka na twardo, odrobina majonezu i czosnku — pasta jak z domowego stołu, gęsta i wyrazista. Zrób ją wieczorem, a rano wystarczy posmarować chleb.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    ingredients: [
      ['jajko', 4, 'szt'],
      ['ser żółty', 80, 'g'],
      ['majonez', 20, 'g'],
      ['jogurt naturalny', 30, 'g'],
      ['musztarda', 5, 'g'],
      ['czosnek', 1, 'szt'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 160, 'g'],
    ],
    steps: [
      'Jajka ugotuj na twardo (10 minut od zagotowania), przelej zimną wodą i obierz.',
      'Ser zetrzyj na tarce o drobnych oczkach, jajka posiekaj drobno albo zetrzyj.',
      'Czosnek przeciśnij przez praskę, szczypiorek posiekaj.',
      'Wymieszaj ser, jajka, majonez, jogurt, musztardę, czosnek i większość szczypiorku; dopraw pieprzem. Pasta ma być gęsta i dać się smarować.',
      'Posmaruj pastą kromki chleba żytniego, posyp resztą szczypiorku i podawaj.',
    ],
    photo:
      'Rye bread slices generously spread with pale yellow grated cheese and egg paste, sprinkled with fresh chopped chives',
    vessel: 'board',
  },
  {
    plan: 'sn-68',
    title: 'Pasta z sardynek z jajkiem i cebulką',
    description:
      'Sardynki z puszki rozgniecione z jajkiem na twardo, czerwoną cebulką i cytryną — tania, pożywna pasta pełna ryby. Z żytnim chlebem i kiszonym ogórkiem to śniadanie, które trzyma do obiadu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['sardynka w oleju', 120, 'g'],
      ['jajko', 2, 'szt'],
      ['cebula czerwona', 50, 'g'],
      ['jogurt naturalny', 30, 'g'],
      ['cytryna', 10, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 160, 'g'],
      ['ogórek kiszony', 60, 'g'],
    ],
    steps: [
      'Jajka ugotuj na twardo (10 minut), ostudź w zimnej wodzie i obierz.',
      'Sardynki odsącz z oleju i rozgnieć widelcem w misce razem z ośćmi, które są miękkie.',
      'Cebulę posiekaj w drobną kostkę, jajka i natkę posiekaj.',
      'Dodaj do sardynek jajka, cebulę, jogurt, sok z cytryny i natkę, dopraw pieprzem i wymieszaj na grubą pastę.',
      'Nałóż pastę na kromki chleba i podawaj z kiszonym ogórkiem pokrojonym w plastry.',
    ],
    photo:
      'Rye bread topped with coarse sardine and egg spread flecked with red onion and parsley, pickled cucumber slices alongside',
    vessel: 'board',
  },
  {
    plan: 'sn-69',
    title: 'Pasta z twarogu z pomidorem i bazylią',
    description:
      'Twaróg utarty z jogurtem, czosnkiem i oliwą, z kawałkami świeżego pomidora i dużą ilością bazylii. Letnia wersja klasycznego białego serka, lekka i pełna białka — do grahamki albo chrupiącego pieczywa.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['ser twaróg półtłusty', 200, 'g'],
      ['jogurt naturalny', 40, 'g'],
      ['pomidor', 1, 'szt'],
      ['bazylia', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['bułka grahamka', 2, 'szt'],
    ],
    steps: [
      'Twaróg rozgnieć widelcem z jogurtem na gładką, puszystą masę.',
      'Pomidor przekrój, wydrąż łyżeczką nasiona i pokrój miąższ w drobną kostkę.',
      'Bazylię porwij lub posiekaj, czosnek przeciśnij przez praskę.',
      'Wmieszaj do twarogu pomidor, bazylię, czosnek i oliwę, dopraw solą i pieprzem.',
      'Przekrój grahamki, posmaruj grubo pastą i podawaj z listkiem bazylii na wierzchu.',
    ],
    photo:
      'Halved graham rolls spread with white cottage cheese paste speckled with diced red tomato and green basil, topped with a basil leaf',
    vessel: 'board',
  },
  {
    plan: 'sn-70',
    title: 'Pasta z awokado i białego sera z rzodkiewką',
    description:
      'Dojrzałe awokado rozgniecione z twarogiem, cytryną i czosnkiem na kremową, zieloną pastę. Chrupiąca rzodkiewka i szczypta chili dodają świeżości — sycące śniadanie na pełnoziarnistym chlebie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['awokado', 1, 'szt'],
      ['ser twaróg półtłusty', 150, 'g'],
      ['cytryna', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['rzodkiewka', 60, 'g'],
      ['płatki chili', 0.5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb pełnoziarnisty', 160, 'g'],
    ],
    steps: [
      'Awokado przekrój, usuń pestkę i wybierz miąższ łyżką do miski.',
      'Dodaj twaróg, sok z cytryny i przeciśnięty czosnek, rozgnieć widelcem na gładką pastę; dopraw solą i pieprzem.',
      'Rzodkiewki pokrój w cienkie plasterki.',
      'Kromki chleba opiecz w tosterze, jeśli lubisz chrupiące.',
      'Posmaruj chleb pastą, ułóż rzodkiewkę, posyp płatkami chili i podawaj.',
    ],
    photo:
      'Wholegrain toast spread with pale green avocado and white cheese paste, topped with thin pink radish slices and red chili flakes',
    vessel: 'board',
  },
  {
    plan: 'sn-71',
    title: 'Pasta z soczewicy i suszonych pomidorów',
    description:
      'Czerwona soczewica ugotowana do miękkości i zmiksowana z suszonymi pomidorami, czosnkiem i kminem. Gęsta, lekko słodkawa pasta roślinna, która w lodówce wytrzyma trzy dni — idealna na kanapki na cały tydzień.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['soczewica czerwona', 100, 'g'],
      ['pomidor suszony w oleju', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 10, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['chleb żytni', 160, 'g'],
    ],
    steps: [
      'Soczewicę przepłucz na sitku, zalej 250 ml wody i gotuj pod przykryciem 12–15 minut, aż się rozpadnie i wchłonie wodę. Ostudź.',
      'Suszone pomidory odsącz z zalewy i pokrój grubo, czosnek obierz.',
      'Zmiksuj soczewicę z pomidorami, czosnkiem, oliwą, sokiem z cytryny, kminem, papryką, solą i pieprzem na gładką pastę. Jeśli jest za gęsta, dodaj łyżkę wody.',
      'Natkę posiekaj i wmieszaj do pasty, zostawiając trochę do posypania.',
      'Posmaruj pastą kromki chleba żytniego, posyp natką i podawaj.',
    ],
    photo:
      'Rye bread slices with a thick orange-red lentil and sun-dried tomato spread, sprinkled with chopped parsley and paprika',
    vessel: 'board',
  },
  {
    plan: 'sn-72',
    title: 'Kanapki z pastą z pieczonego buraka i fetą',
    description:
      'Pieczony burak zmiksowany z orzechami włoskimi i czosnkiem na intensywnie różową pastę, podany na żytnim chlebie z kruszoną fetą i rukolą. Słodko-słone i ziemiste — buraki upiecz dzień wcześniej, a rano złożysz kanapki w pięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 2,
    ingredients: [
      ['burak', 300, 'g'],
      ['orzech włoski', 20, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['cytryna', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 160, 'g'],
      ['ser feta', 80, 'g'],
      ['rukola', 20, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Buraki umyj, zawiń każdy w folię aluminiową i piecz 50–60 minut, aż nóż wejdzie w nie bez oporu.',
      'Ostudź buraki, obierz ze skórki i pokrój w kostkę.',
      'Zmiksuj buraki z orzechami, czosnkiem, oliwą, sokiem z cytryny, solą i pieprzem na gładką pastę.',
      'Posmaruj grubo kromki chleba pastą buraczaną.',
      'Pokrusz na wierzch fetę, połóż kilka listków rukoli i podawaj.',
    ],
    photo:
      'Rye bread topped with vivid magenta roasted beetroot spread, crumbled white feta and fresh rocket leaves',
    vessel: 'board',
  },
  {
    plan: 'sn-73',
    title: 'Szybkie bułeczki jogurtowe z sezamem',
    description:
      'Miękkie bułeczki na jogurcie i proszku do pieczenia, bez drożdży i bez czekania na wyrastanie. Z piekarnika wychodzą po 20 minutach, puszyste w środku i chrupiące od sezamu — wystarczy masło albo ulubiony dodatek.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['jogurt grecki', 180, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['sól', 1.5, 'g'],
      ['jajko', 1, 'szt'],
      ['sezam', 5, 'g'],
      ['masło', 15, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół), blachę wyłóż papierem do pieczenia.',
      'W misce wymieszaj mąkę, proszek do pieczenia i sól. Dodaj jogurt i zagnieć krótko miękkie, lekko klejące ciasto — nie wyrabiaj go długo.',
      'Podziel ciasto na 6 części, dłońmi oprószonymi mąką uformuj kulki i ułóż je na blasze.',
      'Jajko roztrzep, posmaruj nim bułeczki i posyp sezamem.',
      'Piecz 18–20 minut, aż będą złote, a stuknięte od spodu zabrzmią głucho.',
      'Przestudź kilka minut na kratce, przekrój i podawaj ciepłe z masłem.',
    ],
    photo:
      'Six small round golden bread rolls with glossy egg-washed tops sprinkled with sesame seeds, one split open with butter',
    vessel: 'board',
  },
  {
    plan: 'sn-74',
    title: 'Placuszki jogurtowe z jagodami',
    description:
      'Grube, puszyste placuszki na jogurcie naturalnym z jagodami, które pękają przy smażeniu i barwią ciasto na fioletowo. Słodkie śniadanie z sezonu, równie dobre z mrożonych owoców zimą.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['jogurt naturalny', 250, 'g'],
      ['mąka pszenna', 130, 'g'],
      ['jajko', 2, 'szt'],
      ['cukier', 15, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['sól', 0.5, 'g'],
      ['jagoda', 150, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['cukier puder', 5, 'g'],
    ],
    steps: [
      'W misce wymieszaj jogurt z jajkami i cukrem.',
      'Dodaj mąkę, proszek do pieczenia i sól, wymieszaj łyżką tylko do połączenia — ciasto ma być gęste, grudki nie szkodzą.',
      'Delikatnie wmieszaj dwie trzecie jagód.',
      'Rozgrzej patelnię z cienką warstwą oleju na średnim ogniu. Nakładaj łyżką placuszki wielkości dłoni i smaż 2 minuty, aż na wierzchu pojawią się pęcherzyki, potem przewróć i smaż jeszcze minutę.',
      'Usmażone placuszki odkładaj na talerz, w razie potrzeby dolewając odrobinę oleju.',
      'Podawaj ciepłe, posypane resztą jagód i oprószone cukrem pudrem.',
    ],
    photo:
      'Stack of thick fluffy golden pancakes studded with bursting blueberries, dusted with powdered sugar and scattered fresh berries',
  },
  {
    plan: 'sn-75',
    title: 'Placuszki marchewkowe z cynamonem i rodzynkami',
    description:
      'Placuszki z tartej marchewki, jogurtu i cynamonu, smakujące jak ciasto marchewkowe w wersji z patelni. Wilgotne w środku, lekko słodkie, podane z gęstym jogurtem greckim — dobry sposób na warzywa w śniadaniu dla dzieci.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    ingredients: [
      ['marchew', 200, 'g'],
      ['mąka pszenna', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['jogurt naturalny', 100, 'g'],
      ['cukier brązowy', 20, 'g'],
      ['cynamon', 3, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['sól', 0.5, 'g'],
      ['rodzynka', 20, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['jogurt grecki', 100, 'g'],
    ],
    steps: [
      'Marchew obierz i zetrzyj na tarce o drobnych oczkach. Rodzynki zalej na 5 minut gorącą wodą i odsącz.',
      'W misce roztrzep jajka z jogurtem naturalnym i cukrem brązowym.',
      'Dodaj mąkę, proszek do pieczenia, cynamon i sól, wymieszaj na gęste ciasto, a na koniec wmieszaj marchew i rodzynki.',
      'Rozgrzej olej na patelni na średnim ogniu, nakładaj łyżką niewielkie placuszki i lekko je spłaszcz.',
      'Smaż po 2–3 minuty z każdej strony, aż będą rumiane i ścięte w środku.',
      'Podawaj ciepłe z łyżką jogurtu greckiego, oprószone szczyptą cynamonu.',
    ],
    photo:
      'Golden-orange carrot fritters flecked with grated carrot and raisins, topped with a dollop of thick Greek yogurt and a dusting of cinnamon',
  },
  {
    plan: 'sn-76',
    title: 'Naleśniki owsiane z jabłkiem i miodem',
    description:
      'Cienkie naleśniki ze zmiksowanych płatków owsianych i mleka, nadziane jabłkami podsmażonymi z cynamonem. Bez białej mąki, delikatnie orzechowe w smaku, podane z jogurtem i strużką miodu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['mleko', 250, 'ml'],
      ['jajko', 2, 'szt'],
      ['sól', 0.5, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['jabłko', 2, 'szt'],
      ['cynamon', 2, 'g'],
      ['miód', 20, 'g'],
      ['jogurt naturalny', 100, 'g'],
    ],
    steps: [
      'Zmiksuj płatki owsiane z mlekiem, jajkami i solą na gładkie ciasto. Odstaw na 10 minut, żeby płatki napęczniały.',
      'W tym czasie obierz jabłka, pokrój w kostkę i podsmaż na suchej patelni z cynamonem i połową miodu przez 5–6 minut, aż zmiękną.',
      'Patelnię do naleśników posmaruj cienko olejem i rozgrzej. Wlewaj po chochli ciasta, rozprowadź ruchem patelni i smaż około 1,5 minuty, aż brzegi się zezłocą; przewróć i smaż jeszcze pół minuty.',
      'Przed każdym kolejnym naleśnikiem przetrzyj patelnię papierem nasączonym olejem. Wyjdzie 6 naleśników.',
      'Na każdy naleśnik nałóż jabłka, złóż w trójkąt.',
      'Podawaj z jogurtem naturalnym, polane resztą miodu.',
    ],
    photo:
      'Folded oat crepes filled with golden cinnamon apple cubes, topped with a spoon of white yogurt and a drizzle of honey',
  },
  {
    plan: 'sn-77',
    title: 'Zapiekane naleśniki z serem i rodzynkami',
    description:
      'Naleśniki nadziane słodkim twarogiem z rodzynkami i wanilią, zapieczone na maśle, aż brzegi zrobią się chrupiące. Smak dzieciństwa na niedzielne śniadanie — naleśniki możesz usmażyć dzień wcześniej.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    ingredients: [
      ['mąka pszenna', 100, 'g'],
      ['mleko', 250, 'ml'],
      ['jajko', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['ser twaróg półtłusty', 200, 'g'],
      ['rodzynka', 30, 'g'],
      ['cukier', 15, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['masło', 10, 'g'],
    ],
    steps: [
      'Zmiksuj mąkę z mlekiem, jednym jajkiem i połową oleju na gładkie, rzadkie ciasto. Odstaw na 10 minut.',
      'Usmaż 6 cienkich naleśników na patelni przecieranej resztą oleju, po około minucie z każdej strony.',
      'Rodzynki sparz wrzątkiem i odsącz. Twaróg rozgnieć widelcem z drugim jajkiem, cukrem i cukrem waniliowym, wmieszaj rodzynki.',
      'Nagrzej piekarnik do 180°C (góra–dół). Na każdy naleśnik nałóż farsz, zawiń boki i zroluj w krokiety.',
      'Ułóż naleśniki w naczyniu żaroodpornym wysmarowanym częścią masła, na wierzchu rozłóż wiórki reszty masła.',
      'Zapiekaj 15 minut, aż naleśniki się zarumienią, a brzegi będą chrupiące. Podawaj ciepłe.',
    ],
    photo:
      'Baked golden rolled crepes with crispy edges in a baking dish, one cut open to show sweet white cheese filling with raisins',
  },
  {
    plan: 'sn-78',
    title: 'Zupa mleczna z kluskami lanymi',
    description:
      'Gorące, lekko słodkie mleko z delikatnymi kluskami lanymi z jajka i mąki — śniadanie z babcinej kuchni. Rozgrzewa w chłodne poranki i jest gotowe w kwadrans z tego, co zawsze masz w domu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['mleko', 800, 'ml'],
      ['mąka pszenna', 60, 'g'],
      ['jajko', 1, 'szt'],
      ['sól', 1, 'g'],
      ['cukier', 15, 'g'],
      ['masło', 10, 'g'],
    ],
    steps: [
      'Mleko wlej do garnka z grubym dnem, dodaj cukier i zagotuj na średnim ogniu, uważając, żeby nie wykipiało.',
      'W miseczce roztrzep jajko ze szczyptą soli, dodaj mąkę i 2 łyżki wody; wymieszaj na gładkie ciasto gęstości gęstej śmietany.',
      'Zmniejsz ogień, żeby mleko tylko mrugało. Wlewaj ciasto cienką strużką z łyżki, cały czas powoli mieszając mleko.',
      'Gotuj kluski 2–3 minuty, aż wypłyną i się zetną.',
      'Zdejmij z ognia, dodaj masło i podawaj gorącą zupę w miskach.',
    ],
    photo:
      'Bowl of warm creamy milk soup with small irregular pale egg drop noodles and a melting knob of butter',
    vessel: 'bowl',
  },
  {
    plan: 'sn-79',
    title: 'Kasza manna czekoladowa z bananem',
    description:
      'Gęsta, kremowa kasza manna ugotowana na mleku z kakao, podana z plastrami banana i startą gorzką czekoladą. Smakuje jak deser, a syci na długo — ulubione śniadanie dzieci i nie tylko.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['mleko', 600, 'ml'],
      ['kasza manna', 70, 'g'],
      ['kakao', 10, 'g'],
      ['cukier', 15, 'g'],
      ['banan', 2, 'szt'],
      ['czekolada gorzka', 10, 'g'],
    ],
    steps: [
      'Wlej do garnka mleko, odlej 100 ml do kubka i wymieszaj w nim kakao z cukrem na gładko.',
      'Resztę mleka zagotuj, wlej mleko z kakao i ponownie doprowadź do wrzenia.',
      'Wsypuj kaszę cienkim strumieniem, cały czas mieszając trzepaczką, żeby nie było grudek.',
      'Gotuj na małym ogniu 3–4 minuty, mieszając, aż kasza zgęstnieje.',
      'Banany pokrój w plasterki, czekoladę zetrzyj na tarce.',
      'Przełóż kaszę do misek, ułóż banana i posyp startą czekoladą.',
    ],
    photo:
      'Bowl of smooth chocolate semolina porridge topped with fresh banana slices and dark chocolate shavings',
    vessel: 'bowl',
  },
  {
    plan: 'sn-80',
    title: 'Kuskus na słodko z owocami i miodem',
    description:
      'Kuskus zaparzony na gorącym mleku z cynamonem i miodem, podany z truskawkami, borówkami, bananem i prażonymi migdałami. Gotowy w dziesięć minut bez gotowania — lekka odmiana owsianki na letnie poranki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['kasza kuskus', 120, 'g'],
      ['mleko', 250, 'ml'],
      ['masło', 5, 'g'],
      ['cynamon', 1, 'g'],
      ['miód', 25, 'g'],
      ['truskawka', 150, 'g'],
      ['borówka', 100, 'g'],
      ['banan', 1, 'szt'],
      ['migdał', 20, 'g'],
    ],
    steps: [
      'Mleko zagotuj z masłem i cynamonem.',
      'Kuskus wsyp do miski, zalej gorącym mlekiem, przykryj talerzem i odstaw na 5 minut.',
      'W tym czasie upraż migdały na suchej patelni i posiekaj grubo. Truskawki przekrój na ćwiartki, banana pokrój w plastry.',
      'Spulchnij kuskus widelcem i wmieszaj połowę miodu.',
      'Przełóż do misek, ułóż truskawki, borówki i banana, posyp migdałami i polej resztą miodu.',
    ],
    photo:
      'Bowl of fluffy sweet couscous topped with quartered strawberries, blueberries, banana slices, toasted almonds and a honey drizzle',
    vessel: 'bowl',
  },
  {
    plan: 'sn-81',
    title: 'Owsianka tropikalna z mango i kokosem',
    description:
      'Kremowa owsianka gotowana na mleku kokosowym z wodą, podana z soczystym mango, prażonymi wiórkami i skórką z limonki. Smak wakacji w zwykły wtorek, a przy tym bez grama nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['mleko kokosowe z puszki', 100, 'ml'],
      ['sól', 0.5, 'g'],
      ['mango', 250, 'g'],
      ['wiórki kokosowe', 15, 'g'],
      ['limonka', 15, 'g'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Do garnka wsyp płatki, wlej mleko kokosowe i 350 ml wody, dodaj szczyptę soli.',
      'Gotuj na małym ogniu 5–6 minut, często mieszając, aż owsianka będzie kremowa.',
      'W tym czasie upraż wiórki kokosowe na suchej patelni na złoty kolor, cały czas mieszając.',
      'Mango obierz, odkrój miąższ od pestki i pokrój w kostkę. Z limonki zetrzyj skórkę i wyciśnij sok.',
      'Wmieszaj do owsianki miód i sok z limonki, przełóż do misek.',
      'Ułóż na wierzchu mango, posyp wiórkami i skórką z limonki.',
    ],
    photo:
      'Bowl of creamy coconut oatmeal topped with bright yellow mango cubes, golden toasted coconut flakes and grated lime zest',
    vessel: 'bowl',
  },
  {
    plan: 'sn-82',
    title: 'Owsianka marchewkowa z orzechami włoskimi',
    description:
      'Owsianka z tartą marchewką, cynamonem, imbirem i gałką muszkatołową — smakuje jak ciasto marchewkowe na łyżce. Rodzynki i syrop klonowy ją słodzą, a prażone orzechy dodają chrupkości.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 90, 'g'],
      ['mleko', 500, 'ml'],
      ['marchew', 150, 'g'],
      ['cynamon', 2, 'g'],
      ['imbir mielony', 1, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['rodzynka', 20, 'g'],
      ['orzech włoski', 25, 'g'],
      ['syrop klonowy', 20, 'g'],
    ],
    steps: [
      'Marchew obierz i zetrzyj na tarce o drobnych oczkach.',
      'W garnku połącz płatki, mleko, marchew, rodzynki, cynamon, imbir i gałkę muszkatołową.',
      'Gotuj na małym ogniu 7–8 minut, mieszając, aż płatki zmiękną, a marchew straci surowość.',
      'Orzechy upraż na suchej patelni i posiekaj grubo.',
      'Przełóż owsiankę do misek, posyp orzechami i polej syropem klonowym.',
    ],
    photo:
      'Bowl of orange-flecked carrot cake oatmeal with raisins, topped with toasted chopped walnuts and a drizzle of maple syrup',
    vessel: 'bowl',
  },
  {
    plan: 'sn-83',
    title: 'Owsianka dyniowa z cynamonem i pestkami dyni',
    description:
      'Owsianka z musem z dyni, cynamonem i imbirem, kremowa i pomarańczowa jak jesienny liść. Łyżka gęstego jogurtu i chrupiące pestki dyni dopełniają miskę — najlepsza w sezonie na hokkaido.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['dynia', 200, 'g'],
      ['płatki owsiane', 90, 'g'],
      ['mleko', 450, 'ml'],
      ['cynamon', 3, 'g'],
      ['imbir mielony', 1, 'g'],
      ['syrop klonowy', 20, 'g'],
      ['jogurt grecki', 100, 'g'],
      ['pestki dyni', 20, 'g'],
    ],
    steps: [
      'Dynię obierz (hokkaido nie trzeba), usuń pestki i pokrój w kostkę 2 cm. Gotuj pod przykryciem z 50 ml wody 10–12 minut do miękkości, potem rozgnieć widelcem na mus.',
      'Do garnka z musem dodaj płatki, mleko, cynamon i imbir.',
      'Gotuj na małym ogniu 5–6 minut, mieszając, aż owsianka zgęstnieje. Wmieszaj połowę syropu klonowego.',
      'Pestki dyni upraż na suchej patelni, aż zaczną strzelać.',
      'Przełóż owsiankę do misek, dodaj po łyżce jogurtu greckiego, posyp pestkami, szczyptą cynamonu i polej resztą syropu.',
    ],
    photo:
      'Bowl of bright orange pumpkin oatmeal with a swirl of white Greek yogurt, toasted green pumpkin seeds and a dusting of cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'sn-84',
    title: 'Owsianka czekoladowa z wiśniami',
    description:
      'Owsianka na mleku z kakao, zwieńczona ciepłymi wiśniami, które puszczają kwaskowaty sok, i kawałkami gorzkiej czekolady. Połączenie jak w szwarcwaldzkim torcie, tylko na śniadanie i w wersji do łyżki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 90, 'g'],
      ['mleko', 450, 'ml'],
      ['kakao', 15, 'g'],
      ['sól', 0.5, 'g'],
      ['miód', 15, 'g'],
      ['wiśnia mrożona', 200, 'g'],
      ['czekolada gorzka', 15, 'g'],
    ],
    steps: [
      'W garnku wymieszaj płatki, kakao i sól, wlej mleko i zamieszaj, żeby kakao się rozpuściło.',
      'Gotuj na małym ogniu 5–6 minut, mieszając, aż owsianka zgęstnieje. Na koniec wmieszaj miód.',
      'W małym rondelku podgrzej wiśnie z 2 łyżkami wody przez 3–4 minuty, aż puszczą sok.',
      'Czekoladę posiekaj na drobne kawałki.',
      'Przełóż owsiankę do misek, nałóż wiśnie z sokiem i posyp czekoladą, która lekko się roztopi.',
    ],
    photo:
      'Bowl of dark chocolate oatmeal topped with glossy warm red cherries in their juice and chunks of melting dark chocolate',
    vessel: 'bowl',
  },
  {
    plan: 'sn-85',
    title: 'Owsianka ze skyrem i truskawkami',
    description:
      'Owsianka z nasionami chia wymieszana z gęstym skyrem, co daje kremową konsystencję i sporo białka. Świeże truskawki i odrobina miodu sprawiają, że smakuje lekko i owocowo — dobra przed treningiem.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 12,
    servings: 2,
    ingredients: [
      ['płatki owsiane', 80, 'g'],
      ['mleko', 300, 'ml'],
      ['nasiona chia', 10, 'g'],
      ['skyr naturalny', 300, 'g'],
      ['truskawka', 200, 'g'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Płatki i nasiona chia zalej mlekiem w garnku i gotuj na małym ogniu 4–5 minut, mieszając.',
      'Zdejmij z ognia i odstaw na 2 minuty, żeby lekko przestygła.',
      'Truskawki umyj, odszypułkuj i pokrój w plasterki.',
      'Wmieszaj do owsianki połowę skyru i miód.',
      'Przełóż do misek, na wierzch nałóż resztę skyru i truskawki.',
    ],
    photo:
      'Bowl of creamy oatmeal with chia seeds topped with a thick white dollop of skyr and fresh sliced red strawberries',
    vessel: 'bowl',
  },
  {
    plan: 'sn-86',
    title: 'Jaglanka z pieczonymi śliwkami',
    description:
      'Kremowa kasza jaglana na mleku z miodem, podana z połówkami śliwek upieczonymi z cynamonem i brązowym cukrem. Jesienne, rozgrzewające śniadanie, w którym śliwki robią za gęsty, słodko-kwaśny sos.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    ingredients: [
      ['kasza jaglana', 90, 'g'],
      ['mleko', 500, 'ml'],
      ['miód', 20, 'g'],
      ['śliwka', 300, 'g'],
      ['cukier brązowy', 10, 'g'],
      ['cynamon', 2, 'g'],
      ['migdał', 15, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Śliwki przekrój na pół i usuń pestki.',
      'Ułóż śliwki w naczyniu przekrojem do góry, posyp cukrem brązowym i cynamonem. Piecz 20 minut, aż zmiękną i puszczą sok.',
      'Kaszę jaglaną przepłucz na sitku gorącą wodą, żeby nie była gorzka.',
      'Zagotuj mleko, wsyp kaszę i gotuj pod przykryciem na małym ogniu 15 minut, co jakiś czas mieszając, aż będzie miękka i kremowa. Wmieszaj miód.',
      'Migdały posiekaj grubo.',
      'Przełóż jaglankę do misek, ułóż pieczone śliwki, polej sokiem z naczynia i posyp migdałami.',
    ],
    photo:
      'Bowl of creamy pale yellow millet porridge topped with roasted plum halves in dark purple syrup and chopped almonds',
    vessel: 'bowl',
  },
  {
    plan: 'sn-87',
    title: 'Kasza gryczana z jajkiem sadzonym i koperkiem',
    description:
      'Sypka kasza gryczana z podsmażoną na maśle cebulką, jajkiem sadzonym i dużą ilością koperku, z kiszonym ogórkiem obok. Wytrawne, bardzo sycące śniadanie w polskim stylu — dobre też z wczorajszej kaszy.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    ingredients: [
      ['kasza gryczana', 120, 'g'],
      ['sól', 2, 'g'],
      ['cebula', 1, 'szt'],
      ['masło', 15, 'g'],
      ['jajko', 4, 'szt'],
      ['koperek', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['ogórek kiszony', 100, 'g'],
    ],
    steps: [
      'Kaszę wsyp do 250 ml osolonej wrzącej wody, gotuj pod przykryciem na małym ogniu 12–15 minut, aż wchłonie wodę. Odstaw pod pokrywką na 5 minut.',
      'Cebulę pokrój w drobną kostkę i zeszklij na połowie masła przez 5 minut, aż się zezłoci.',
      'Dodaj do cebuli kaszę, wymieszaj i podgrzewaj 2 minuty; dopraw pieprzem.',
      'Na drugiej patelni roztop resztę masła i usmaż 4 jajka sadzone, aż białko się zetnie, a żółtko zostanie płynne.',
      'Koperek posiekaj, ogórki pokrój w plastry.',
      'Nałóż kaszę na talerze, połóż po dwa jajka, obficie posyp koperkiem i podawaj z ogórkiem kiszonym.',
    ],
    photo:
      'Plate of brown buckwheat groats with golden fried onion, two sunny-side-up eggs with runny yolks, lots of chopped dill and pickled cucumber slices',
  },
  {
    plan: 'sn-88',
    title: 'Parfait jogurtowe z musem truskawkowym i granolą',
    description:
      'Warstwy gęstego jogurtu greckiego, świeżego musu truskawkowego i chrupiącej granoli podane w szklance albo miseczce. Wygląda jak deser z kawiarni, a składa się w pięć minut — można przygotować wieczorem, granolę dosyp rano.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['truskawka', 250, 'g'],
      ['miód', 15, 'g'],
      ['jogurt grecki', 300, 'g'],
      ['granola', 70, 'g'],
      ['mięta', 3, 'g'],
    ],
    steps: [
      'Odłóż 4 ładne truskawki do dekoracji. Resztę zmiksuj z miodem na gładki mus.',
      'Jogurt grecki wymieszaj, żeby był kremowy.',
      'Do szklanek lub miseczek nakładaj warstwami: łyżkę granoli, jogurt, mus truskawkowy — i powtórz.',
      'Na wierzch nałóż odrobinę jogurtu i resztę granoli.',
      'Udekoruj przekrojonymi truskawkami i listkami mięty, podawaj od razu, póki granola chrupie.',
    ],
    photo:
      'Glass cups with layers of white Greek yogurt, pink strawberry puree and golden granola, topped with halved strawberries and mint leaves',
    vessel: 'bowl',
  },
  {
    plan: 'sn-89',
    title: 'Serek wiejski z owocami, orzechami i miodem',
    description:
      'Serek wiejski z borówkami, malinami i bananem, polany miodem i posypany orzechami włoskimi. Śniadanie bez gotowania, pełne białka, które złożysz w trzy minuty — także do pudełka na drugie śniadanie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    ingredients: [
      ['serek wiejski', 400, 'g'],
      ['borówka', 100, 'g'],
      ['malina', 100, 'g'],
      ['banan', 1, 'szt'],
      ['orzech włoski', 20, 'g'],
      ['miód', 20, 'g'],
    ],
    steps: [
      'Owoce umyj i osusz na ręczniku papierowym, banana pokrój w plastry.',
      'Orzechy posiekaj grubo.',
      'Serek wiejski przełóż do dwóch misek.',
      'Ułóż na nim borówki, maliny i banana, posyp orzechami i polej miodem.',
    ],
    photo:
      'Bowl of white cottage cheese curds topped with blueberries, raspberries, banana slices, chopped walnuts and a honey drizzle',
    vessel: 'bowl',
  },
  {
    plan: 'sn-90',
    title: 'Miska smoothie z mango i kokosem',
    description:
      'Gęste smoothie z mango, mrożonego banana i skyru z mlekiem kokosowym, jedzone łyżką z miski. Na wierzchu granola, kiwi, chia i wiórki kokosowe — kolorowe, orzeźwiające śniadanie na ciepłe dni.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    ingredients: [
      ['mango', 300, 'g'],
      ['banan', 2, 'szt'],
      ['skyr naturalny', 150, 'g'],
      ['mleko kokosowe z puszki', 60, 'ml'],
      ['granola', 40, 'g'],
      ['kiwi', 1, 'szt'],
      ['nasiona chia', 10, 'g'],
      ['wiórki kokosowe', 10, 'g'],
    ],
    steps: [
      'Wieczorem obierz banany, pokrój w plastry i zamroź; mango może być świeże albo mrożone, pokrojone w kostkę.',
      'Zmiksuj mango, mrożone banany, skyr i mleko kokosowe na gęsty, gładki krem. Jeśli blender nie daje rady, dolej łyżkę wody.',
      'Kiwi obierz i pokrój w półplasterki.',
      'Przełóż smoothie do misek i wyrównaj łyżką.',
      'Ułóż w paskach granolę, kiwi, nasiona chia i wiórki kokosowe, podawaj od razu.',
    ],
    photo:
      'Bowl of thick bright yellow mango smoothie topped with neat rows of granola, green kiwi slices, chia seeds and coconut flakes',
    vessel: 'bowl',
  },
];

export const ADDITIONS: IngredientAddition[] = [];
