/**
 * Katalog 1000 — część DE-a: desery i podwieczorki DE-001 … DE-024 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ─── Boże Narodzenie ───
  {
    plan: 'DE-001',
    title: 'Makowiec zawijany',
    description:
      'Klasyczna rolada z maślanego ciasta drożdżowego z grubą warstwą masy makowej z orzechami, polana cytrynowym lukrem. Ciasto, bez którego trudno wyobrazić sobie wigilijny i świąteczny stół.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'HARD',
    prepTimeMinutes: 180,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['CHRISTMAS_EVE', 'CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['mąka pszenna', 350, 'g'],
      ['drożdże', 25, 'g'],
      ['mleko', 120, 'ml'],
      ['cukier', 60, 'g'],
      ['masło', 60, 'g'],
      ['jajko', 2, 'szt'],
      ['sól', 1, 'g'],
      ['masa makowa', 450, 'g'],
      ['orzech włoski', 30, 'g'],
      ['cukier puder', 60, 'g'],
      ['cytryna', 15, 'g'],
    ],
    steps: [
      'Podgrzej mleko do letniej temperatury, rozkrusz w nim drożdże z łyżeczką cukru i odstaw na 10 minut, aż zaczyn się spieni.',
      'Do miski wsyp mąkę, resztę cukru i sól, dodaj jajka, zaczyn i roztopione, przestudzone masło. Wyrabiaj 10 minut do gładkiego, elastycznego ciasta.',
      'Przykryj miskę ściereczką i odstaw w ciepłe miejsce na około 1 godzinę, aż ciasto podwoi objętość.',
      'Orzechy posiekaj i wymieszaj z masą makową.',
      'Rozwałkuj ciasto na prostokąt 30 × 40 cm, rozsmaruj masę makową, zostawiając 2 cm wolnego brzegu, i zwiń ciasno wzdłuż dłuższego boku.',
      'Zawiń roladę luźno w papier do pieczenia, ułóż łączeniem do dołu na blasze i odstaw na 20 minut do napuszenia. Piecz w piekarniku nagrzanym do 180°C przez 40–45 minut, aż wierzch będzie złoty.',
      'Wystudź makowiec, utrzyj cukier puder z sokiem z cytryny na gęsty lukier i polej nim wierzch.',
    ],
    photo:
      'Two thick slices of Polish poppy seed roll showing tight spirals of dark poppy seed and walnut filling in golden yeast dough, with white lemon icing on the golden crust',
  },
  {
    plan: 'DE-002',
    title: 'Piernik staropolski dojrzewający',
    description:
      'Ciemny, korzenny piernik z miodowego ciasta, które dojrzewa kilka tygodni w chłodzie, przełożony powidłami i oblany gorzką czekoladą. Po upieczeniu mięknie i z każdym dniem smakuje lepiej.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'HARD',
    prepTimeMinutes: 180,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['miód', 250, 'g'],
      ['cukier', 100, 'g'],
      ['masło', 80, 'g'],
      ['mąka pszenna', 450, 'g'],
      ['jajko', 3, 'szt'],
      ['przyprawa do piernika', 20, 'g'],
      ['soda oczyszczona', 8, 'g'],
      ['mleko', 60, 'ml'],
      ['dżem', 200, 'g'],
      ['czekolada gorzka', 80, 'g'],
    ],
    steps: [
      'Co najmniej 3 tygodnie przed świętami podgrzej w garnku miód z cukrem i masłem, aż cukier się rozpuści, i wystudź.',
      'Do przestudzonej masy wsyp mąkę i przyprawę do piernika, dodaj jajka oraz sodę rozpuszczoną w mleku. Wyrabiaj 10 minut do gładkiego ciasta.',
      'Przełóż ciasto do kamionkowego naczynia albo słoika, przykryj ściereczką i odstaw w chłodne miejsce (lodówka albo spiżarnia) na 3–6 tygodni.',
      'W dniu pieczenia podziel ciasto na 3 części i rozwałkuj każdą na placek wielkości blachy 24 × 35 cm wyłożonej papierem.',
      'Piecz każdy placek w piekarniku nagrzanym do 180°C przez 12–15 minut, aż będzie sprężysty. Wystudź na kratce.',
      'Przełóż blaty powidłami, obciąż lekko deską i zostaw na 2–3 dni, żeby zmiękły.',
      'Roztop czekoladę w kąpieli wodnej, polej piernik i odstaw do zastygnięcia polewy.',
    ],
    photo:
      'A slice of layered dark Polish gingerbread cake with three spiced dark brown layers and thin plum jam between them, covered with a glossy dark chocolate glaze',
  },
  {
    plan: 'DE-003',
    title: 'Pierniczki lukrowane',
    description:
      'Miękkie, miodowe pierniczki z korzenną przyprawą, wykrawane w gwiazdki, choinki i serca, a potem ozdobione białym lukrem. Idealne do wspólnego pieczenia z dziećmi i na świąteczne prezenty.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL', 'LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 400, 'g'],
      ['miód', 150, 'g'],
      ['masło', 80, 'g'],
      ['cukier puder', 230, 'g'],
      ['jajko', 1, 'szt'],
      ['przyprawa do piernika', 15, 'g'],
      ['kakao', 10, 'g'],
      ['soda oczyszczona', 5, 'g'],
      ['cytryna', 20, 'g'],
    ],
    steps: [
      'Podgrzej miód z masłem, aż masło się rozpuści, i odstaw do przestudzenia.',
      'Wymieszaj mąkę z 80 g cukru pudru, przyprawą do piernika, kakao i sodą. Dodaj miód z masłem i jajko, zagnieć gładkie ciasto.',
      'Rozwałkuj ciasto na grubość 4 mm i wykrawaj foremkami pierniczki. Układaj je na blasze wyłożonej papierem do pieczenia.',
      'Piecz w piekarniku nagrzanym do 180°C przez 8–10 minut, aż lekko urosną. Wystudź na kratce.',
      'Utrzyj resztę cukru pudru z sokiem z cytryny na gęsty lukier, przełóż do woreczka z uciętym rogiem i ozdób pierniczki.',
      'Odstaw na 1 godzinę do zastygnięcia lukru. Przechowuj w puszce, z kawałkiem jabłka pierniczki szybciej zmiękną.',
    ],
    photo:
      'A few dark brown gingerbread cookies shaped like stars, Christmas trees and hearts, decorated with fine white lemon icing patterns',
    vessel: 'board',
  },
  {
    plan: 'DE-004',
    title: 'Sernik krakowski z kratką',
    description:
      'Gęsty, waniliowy sernik z twarogu z rodzynkami i kandyzowaną skórką pomarańczową, przykryty kruchą kratką. Tradycyjny świąteczny wypiek, który po nocy w lodówce kroi się idealnie równo.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 150,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['CHRISTMAS'],
    equipment: ['OVEN'],
    ingredients: [
      ['ser twaróg półtłusty', 800, 'g'],
      ['cukier', 150, 'g'],
      ['jajko', 6, 'szt'],
      ['masło', 130, 'g'],
      ['budyń', 40, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['rodzynka', 60, 'g'],
      ['skórka pomarańczowa kandyzowana', 40, 'g'],
      ['mąka pszenna', 180, 'g'],
      ['cukier puder', 50, 'g'],
      ['proszek do pieczenia', 5, 'g'],
    ],
    steps: [
      'Zagnieć kruche ciasto z mąki, 70 g zimnego masła, cukru pudru, proszku do pieczenia i 1 jajka. Zawiń w folię i schłodź 30 minut w lodówce.',
      'Twaróg zmiel dwukrotnie przez maszynkę albo przetrzyj przez sito.',
      'Utrzyj 60 g miękkiego masła z cukrem i cukrem waniliowym, dodawaj po jednym 5 jajek, potem twaróg i budyń w proszku. Wmieszaj rodzynki i skórkę pomarańczową.',
      'Formę 24 × 24 cm wyłóż papierem, wlej masę serową i wyrównaj.',
      'Ciasto rozwałkuj, pokrój w paski szerokości 1 cm i ułóż na serniku w kratkę.',
      'Piecz w piekarniku nagrzanym do 170°C przez 60–70 minut, aż środek przestanie falować. Wystudź przy uchylonych drzwiczkach, a potem schłódź w lodówce przez noc.',
    ],
    photo:
      'Square slice of dense vanilla cheesecake studded with raisins and candied orange peel, topped with a golden shortcrust lattice',
  },
  {
    plan: 'DE-005',
    title: 'Kutia z makiem, miodem i bakaliami',
    description:
      'Tradycyjna wigilijna kutia z pszenicy, zmielonego maku i miodu, pełna rodzynek, orzechów, migdałów, moreli i fig. Słodki, kremowy deser, który najlepiej smakuje po kilku godzinach przegryzania się.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 120,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'DESSERT',
    occasions: ['CHRISTMAS_EVE'],
    equipment: ['BLENDER'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['pszenica łuskana', 150, 'g'],
      ['mak', 120, 'g'],
      ['miód', 80, 'g'],
      ['rodzynka', 40, 'g'],
      ['orzech włoski', 40, 'g'],
      ['migdał', 30, 'g'],
      ['morela suszona', 40, 'g'],
      ['figi suszone', 40, 'g'],
      ['skórka pomarańczowa kandyzowana', 20, 'g'],
    ],
    steps: [
      'Pszenicę namocz w zimnej wodzie na noc, odcedź i gotuj w świeżej wodzie na małym ogniu 60–70 minut do miękkości. Odcedź i wystudź.',
      'Mak zalej wrzącą wodą i odstaw na 30 minut, potem odcedź na gęstym sitku i zmiksuj blenderem na gładką masę (2–3 minuty).',
      'Rodzynki sparz wrzątkiem, morele i figi pokrój w kostkę, orzechy i migdały posiekaj.',
      'Roztop miód w rondelku na małym ogniu, żeby był płynny.',
      'Wymieszaj pszenicę z makiem, miodem, bakaliami i skórką pomarańczową. Schłódź co najmniej 1 godzinę przed podaniem.',
    ],
    photo:
      'Polish kutia of cooked wheat berries in dark ground poppy seed and honey, mixed with raisins, chopped walnuts, almonds, diced dried apricots, figs and candied orange peel',
    vessel: 'bowl',
  },
  {
    plan: 'DE-006',
    title: 'Kluski z makiem',
    description:
      'Wigilijny deser z krótkiego makaronu łazanki wymieszanego ze słodkim makiem na mleku, miodem, rodzynkami i orzechami. Prostszy od kutii, a równie świąteczny i szybko znika z talerzy.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'DESSERT',
    occasions: ['CHRISTMAS_EVE'],
    equipment: ['BLENDER'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['makaron łazanki', 250, 'g'],
      ['mak', 100, 'g'],
      ['mleko', 100, 'ml'],
      ['miód', 60, 'g'],
      ['rodzynka', 40, 'g'],
      ['orzech włoski', 30, 'g'],
      ['masło', 20, 'g'],
      ['cukier waniliowy', 8, 'g'],
    ],
    steps: [
      'Mak zalej gorącym mlekiem i odstaw na 20 minut, potem zmiksuj blenderem razem z mlekiem na gęstą masę.',
      'Rodzynki sparz wrzątkiem, a orzechy posiekaj.',
      'Na patelni roztop masło, dodaj mak, miód i cukier waniliowy. Smaż na małym ogniu 5 minut, mieszając, aż masa się zagęści.',
      'Ugotuj makaron al dente według instrukcji na opakowaniu, odcedź i przelej zimną wodą.',
      'Wymieszaj makaron z makiem, rodzynkami i orzechami. Podawaj na zimno albo lekko ciepłe.',
    ],
    photo:
      'Short square pasta pieces coated in dark sweet poppy seed and honey, mixed with golden raisins and chopped walnuts',
    vessel: 'bowl',
  },
  {
    plan: 'DE-007',
    title: 'Keks z bakaliami',
    description:
      'Maślane ciasto z keksówki gęsto wypełnione rodzynkami, morelami, żurawiną, orzechami i kandyzowaną skórką pomarańczową. Długo zachowuje świeżość, więc można upiec je kilka dni przed świętami.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['masło', 180, 'g'],
      ['cukier', 170, 'g'],
      ['jajko', 4, 'szt'],
      ['proszek do pieczenia', 8, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['rodzynka', 80, 'g'],
      ['morela suszona', 60, 'g'],
      ['żurawina suszona', 50, 'g'],
      ['skórka pomarańczowa kandyzowana', 40, 'g'],
      ['orzech włoski', 50, 'g'],
    ],
    steps: [
      'Morele pokrój w kostkę, orzechy posiekaj. Wymieszaj wszystkie bakalie i obtocz je w 2 łyżkach mąki, żeby nie opadły na dno.',
      'Miękkie masło utrzyj z cukrem i cukrem waniliowym na puszystą masę (5 minut), potem dodawaj po jednym jajku.',
      'Wmieszaj resztę mąki przesianej z proszkiem do pieczenia, a na końcu bakalie.',
      'Przełóż ciasto do keksówki 25 cm wyłożonej papierem do pieczenia i wyrównaj.',
      'Piecz w piekarniku nagrzanym do 170°C przez 55–60 minut, do suchego patyczka. Wystudź w formie 15 minut, potem na kratce.',
    ],
    photo:
      'Two slices of golden loaf cake packed with raisins, dried apricots, cranberries, walnuts and candied orange peel, showing a colourful fruit-studded crumb',
  },
  {
    plan: 'DE-008',
    title: 'Drożdżowe ślimaczki z makiem',
    description:
      'Mięciutkie drożdżowe ślimaczki zawijane z masą makową i polane cytrynowym lukrem. Mniejsza, szybsza wersja makowca, idealna do kawy w zimowe popołudnie.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 120,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    seasons: ['WINTER'],
    occasions: ['CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 400, 'g'],
      ['drożdże', 25, 'g'],
      ['mleko', 180, 'ml'],
      ['cukier', 60, 'g'],
      ['masło', 60, 'g'],
      ['jajko', 1, 'szt'],
      ['sól', 1, 'g'],
      ['masa makowa', 300, 'g'],
      ['cukier puder', 60, 'g'],
      ['cytryna', 10, 'g'],
    ],
    steps: [
      'Rozkrusz drożdże w letnim mleku z łyżeczką cukru i odstaw na 10 minut.',
      'Wymieszaj mąkę z resztą cukru i solą, dodaj zaczyn, jajko i roztopione masło. Wyrabiaj 8–10 minut, przykryj i odstaw na 1 godzinę do wyrośnięcia.',
      'Rozwałkuj ciasto na prostokąt 30 × 40 cm, rozsmaruj masę makową i zwiń w rulon wzdłuż dłuższego boku.',
      'Pokrój rulon na 16 plastrów, ułóż je na blasze wyłożonej papierem i odstaw na 20 minut do napuszenia.',
      'Piecz w piekarniku nagrzanym do 180°C przez 20–25 minut, aż się zezłocą.',
      'Utrzyj cukier puder z sokiem z cytryny i polej lukrem lekko przestudzone ślimaczki.',
    ],
    photo:
      'Two golden yeast pinwheel buns with dark poppy seed swirls, drizzled with thin white lemon icing',
    vessel: 'board',
  },

  // ─── Wielkanoc ───
  {
    plan: 'DE-009',
    title: 'Mazurek kajmakowy',
    description:
      'Kruchy, maślany placek pokryty grubą warstwą kajmaku i ozdobiony orzechami, migdałami i suszoną żurawiną. Słodki symbol wielkanocnego stołu, który łatwo przygotować dzień wcześniej.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['EASTER'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['masło', 150, 'g'],
      ['cukier puder', 70, 'g'],
      ['jajko', 2, 'szt'],
      ['proszek do pieczenia', 3, 'g'],
      ['masa kajmakowa', 400, 'g'],
      ['orzech włoski', 40, 'g'],
      ['migdał', 30, 'g'],
      ['żurawina suszona', 30, 'g'],
    ],
    steps: [
      'Posiekaj zimne masło z mąką, cukrem pudrem i proszkiem do pieczenia, dodaj jajka i szybko zagnieć kruche ciasto. Schłódź 30 minut w lodówce.',
      'Rozwałkuj ciasto na prostokąt 25 × 35 cm, przełóż na blachę z papierem, z resztek uformuj wałeczek i ułóż go wzdłuż brzegów. Nakłuj spód widelcem.',
      'Piecz w piekarniku nagrzanym do 180°C przez 18–20 minut, aż spód się zezłoci. Wystudź.',
      'Masę kajmakową rozmieszaj, żeby była gładka, i rozsmaruj na spodzie.',
      'Ułóż na kajmaku orzechy, migdały i żurawinę we wzór, odstaw na 1 godzinę do stężenia.',
    ],
    photo:
      'A rectangular piece of Polish mazurek with a golden shortcrust base and a thick glossy caramel dulce de leche layer, decorated with walnut halves, almonds and red dried cranberries',
  },
  {
    plan: 'DE-010',
    title: 'Babka drożdżowa wielkanocna',
    description:
      'Wysoka, puszysta babka na drożdżach z rodzynkami i skórką pomarańczową, polana białym lukrem. Wielkanocna klasyka, która pachnie masłem i wanilią na cały dom.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'HARD',
    prepTimeMinutes: 210,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['EASTER'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['mąka pszenna', 500, 'g'],
      ['drożdże', 30, 'g'],
      ['mleko', 200, 'ml'],
      ['cukier', 110, 'g'],
      ['masło', 120, 'g'],
      ['jajko', 4, 'szt'],
      ['cukier waniliowy', 16, 'g'],
      ['sól', 2, 'g'],
      ['rodzynka', 60, 'g'],
      ['skórka pomarańczowa kandyzowana', 30, 'g'],
      ['cukier puder', 80, 'g'],
      ['cytryna', 15, 'g'],
    ],
    steps: [
      'Rozkrusz drożdże w 100 ml letniego mleka z łyżką cukru i 2 łyżkami mąki. Odstaw na 15 minut, aż zaczyn się spieni.',
      'Jajka utrzyj z resztą cukru i cukrem waniliowym na jasną masę.',
      'Do mąki z solą dodaj zaczyn, jajka i resztę mleka. Wyrabiaj 10 minut, potem stopniowo dodawaj roztopione, przestudzone masło i wyrabiaj, aż ciasto zacznie odchodzić od ręki.',
      'Wmieszaj rodzynki i skórkę pomarańczową, przykryj i odstaw na 1,5 godziny do podwojenia objętości.',
      'Przełóż ciasto do wysmarowanej masłem formy na babkę (do 1/3 wysokości) i odstaw na 40 minut, aż dorośnie do 2/3 formy.',
      'Piecz w piekarniku nagrzanym do 175°C przez 45–50 minut. Wystudź w formie 10 minut, potem na kratce.',
      'Utrzyj cukier puder z sokiem z cytryny i polej wystudzoną babkę.',
    ],
    photo:
      'A thick slice of Easter yeast babka with white lemon icing running over the golden top, showing a fluffy yellow crumb dotted with raisins and candied orange peel',
  },
  {
    plan: 'DE-011',
    title: 'Babka cytrynowa ucierana',
    description:
      'Wilgotna babka ucierana na maśle, z mąką ziemniaczaną, dużą ilością skórki i soku z cytryny oraz kwaskowatym lukrem. Szybsza od drożdżowej i zawsze się udaje.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 80,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['EASTER'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['masło', 200, 'g'],
      ['cukier', 200, 'g'],
      ['jajko', 5, 'szt'],
      ['mąka pszenna', 200, 'g'],
      ['mąka ziemniaczana', 100, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['cytryna', 150, 'g'],
      ['cukier puder', 80, 'g'],
    ],
    steps: [
      'Z cytryn zetrzyj skórkę i wyciśnij sok. Formę na babkę wysmaruj masłem i oprósz mąką.',
      'Miękkie masło utrzyj z cukrem na puszystą masę (5 minut), dodawaj po jednym jajku, ucierając po każdym.',
      'Wmieszaj obie mąki przesiane z proszkiem do pieczenia, skórkę i 3 łyżki soku z cytryny.',
      'Przełóż ciasto do formy i piecz w piekarniku nagrzanym do 175°C przez 45–50 minut, do suchego patyczka.',
      'Wystudź babkę, utrzyj cukier puder z resztą soku z cytryny na lukier i polej wierzch. Posyp odrobiną skórki.',
    ],
    photo:
      'A thick slice of golden lemon babka with a fine pale yellow crumb, topped with thick white lemon glaze and a sprinkle of fresh yellow lemon zest',
  },
  {
    plan: 'DE-012',
    title: 'Pascha z twarogu i bakalii',
    description:
      'Wielkanocny deser bez pieczenia z tłustego twarogu, masła i śmietanki ze słodkimi żółtkami, pełen rodzynek, moreli, migdałów i skórki pomarańczowej. Formowany w piramidkę i schłodzony przez noc.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 520,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'DESSERT',
    occasions: ['EASTER'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['ser twaróg tłusty', 800, 'g'],
      ['masło', 100, 'g'],
      ['cukier puder', 100, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['jajko', 3, 'szt'],
      ['śmietanka 30', 100, 'ml'],
      ['rodzynka', 60, 'g'],
      ['morela suszona', 50, 'g'],
      ['skórka pomarańczowa kandyzowana', 40, 'g'],
      ['migdał', 40, 'g'],
    ],
    steps: [
      'Twaróg zmiel dwukrotnie przez maszynkę albo przetrzyj przez sito.',
      'W rondelku wymieszaj jajka ze śmietanką, cukrem pudrem i cukrem waniliowym. Podgrzewaj na małym ogniu 5–6 minut, ciągle mieszając, aż masa zgęstnieje, ale nie zagotuje się. Wystudź.',
      'Miękkie masło utrzyj na puszysto, dodawaj po łyżce twarogu, a na końcu wlej przestudzony krem.',
      'Morele pokrój w kostkę, migdały posiekaj. Wmieszaj je do masy razem z rodzynkami i skórką pomarańczową.',
      'Durszlak albo formę wyłóż podwójną gazą, przełóż masę, przykryj brzegami gazy i obciąż talerzykiem.',
      'Wstaw do lodówki na co najmniej 8 godzin, żeby odciekła i stężała. Odwróć na talerz i zdejmij gazę.',
    ],
    photo:
      'A thick slice of dense creamy white Easter cheese pascha studded with raisins, candied orange peel, diced dried apricots and chopped almonds',
  },
  {
    plan: 'DE-013',
    title: 'Mazurek pomarańczowy z bakaliami',
    description:
      'Kruchy mazurek z kwaskowatym, złotym kremem z pomarańczy, obsypany migdałami, figami, rodzynkami i kandyzowaną skórką. Świeższa, owocowa odmiana wielkanocnego mazurka.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['EASTER'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['masło', 150, 'g'],
      ['cukier puder', 70, 'g'],
      ['jajko', 2, 'szt'],
      ['proszek do pieczenia', 3, 'g'],
      ['pomarańcza', 400, 'g'],
      ['cukier', 120, 'g'],
      ['mąka ziemniaczana', 20, 'g'],
      ['migdał', 40, 'g'],
      ['rodzynka', 30, 'g'],
      ['figi suszone', 40, 'g'],
      ['skórka pomarańczowa kandyzowana', 30, 'g'],
    ],
    steps: [
      'Posiekaj zimne masło z mąką, cukrem pudrem i proszkiem do pieczenia, dodaj jajka i zagnieć kruche ciasto. Schłódź 30 minut.',
      'Rozwałkuj ciasto na prostokąt 25 × 35 cm, przełóż na blachę z papierem, z resztek zrób brzeg. Piecz w piekarniku nagrzanym do 180°C przez 18–20 minut i wystudź.',
      'Z pomarańczy zetrzyj skórkę i wyciśnij sok (ok. 200 ml). Zagotuj sok ze skórką i cukrem.',
      'Mąkę ziemniaczaną rozmieszaj w 3 łyżkach zimnej wody, wlej do gotującego się soku i gotuj, mieszając, 1–2 minuty, aż krem zgęstnieje. Przestudź 10 minut.',
      'Rozsmaruj krem na spodzie. Figi pokrój w paski i ułóż na wierzchu z migdałami, rodzynkami i skórką pomarańczową.',
      'Odstaw na 1 godzinę do stężenia kremu.',
    ],
    photo:
      'A rectangular piece of golden shortcrust mazurek covered with glossy bright orange curd, decorated with almonds, strips of dried fig, raisins and candied orange peel',
  },

  // ─── Sezonowe ───
  {
    plan: 'DE-014',
    title: 'Ciasto biszkoptowe z rabarbarem i bezą',
    description:
      'Lekki biszkopt z kwaskowatym rabarbarem pod chrupiącą, złocistą bezą. Wiosenne ciasto, w którym słodycz bezy idealnie równoważy cierpkość pierwszych łodyg rabarbaru.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    seasons: ['SPRING'],
    equipment: ['OVEN'],
    ingredients: [
      ['jajko', 7, 'szt'],
      ['cukier', 270, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['mąka pszenna', 150, 'g'],
      ['mąka ziemniaczana', 40, 'g'],
      ['proszek do pieczenia', 4, 'g'],
      ['rabarbar', 500, 'g'],
    ],
    steps: [
      'Rabarbar umyj, obierz grubsze łodygi i pokrój w kawałki 2 cm.',
      'Oddziel 3 białka od żółtek. 4 całe jajka i 3 żółtka ubij z 120 g cukru i cukrem waniliowym na jasną, puszystą masę (8 minut).',
      'Delikatnie wmieszaj szpatułką mąkę pszenną, 30 g mąki ziemniaczanej i proszek do pieczenia. Przelej ciasto do blachy 24 × 30 cm wyłożonej papierem.',
      'Rozłóż rabarbar na cieście i piecz w piekarniku nagrzanym do 180°C przez 25 minut.',
      'W tym czasie ubij 3 białka na sztywno, dodając stopniowo 150 g cukru, a na koniec resztę mąki ziemniaczanej.',
      'Rozsmaruj bezę na podpieczonym cieście, zmniejsz temperaturę do 150°C i piecz jeszcze 25–30 minut, aż beza będzie chrupiąca i lekko złota. Wystudź przed krojeniem.',
    ],
    photo:
      'Square slice of light sponge cake with pink rhubarb pieces under a thick crisp golden meringue topping',
  },
  {
    plan: 'DE-015',
    title: 'Mus z rabarbaru z jogurtem',
    description:
      'Warstwowy deser z różowego musu z rabarbaru i truskawek przekładanego gęstym jogurtem greckim. Lekki, orzeźwiający i gotowy w pół godziny, a przy tym zupełnie bez glutenu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'DESSERT',
    seasons: ['SPRING'],
    equipment: ['BLENDER'],
    ingredients: [
      ['rabarbar', 500, 'g'],
      ['truskawka', 150, 'g'],
      ['miód', 60, 'g'],
      ['jogurt grecki', 400, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['mięta', 3, 'g'],
    ],
    steps: [
      'Rabarbar umyj, obierz i pokrój w kawałki, truskawki przekrój na pół. Kilka truskawek odłóż do dekoracji.',
      'Duś rabarbar z truskawkami, miodem i 3 łyżkami wody pod przykryciem przez 10 minut, aż się rozpadnie.',
      'Zmiksuj owoce blenderem na gładki mus i schłódź 15 minut.',
      'Jogurt wymieszaj z cukrem waniliowym.',
      'Układaj w pucharkach warstwy jogurtu i musu, na wierzchu połóż truskawki i listki mięty.',
    ],
    photo:
      'Smooth pink rhubarb and strawberry mousse layered with thick white Greek yogurt, topped with halved fresh strawberries and a few mint leaves',
    vessel: 'cup',
  },
  {
    plan: 'DE-016',
    title: 'Drożdżówka z jagodami',
    description:
      'Puszyste drożdżowe bułeczki z soczystymi jagodami i maślaną kruszonką. Letni wypiek, który przywołuje smak drożdżówek z osiedlowej piekarni.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 130,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    seasons: ['SUMMER'],
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 520, 'g'],
      ['drożdże', 25, 'g'],
      ['mleko', 200, 'ml'],
      ['cukier', 130, 'g'],
      ['masło', 120, 'g'],
      ['jajko', 2, 'szt'],
      ['sól', 1, 'g'],
      ['jagoda', 400, 'g'],
      ['mąka ziemniaczana', 15, 'g'],
    ],
    steps: [
      'Rozkrusz drożdże w letnim mleku z łyżeczką cukru i odstaw na 10 minut.',
      'Do 450 g mąki dodaj 80 g cukru, sól, jajka, zaczyn i 70 g roztopionego masła. Wyrabiaj 10 minut, przykryj i odstaw na 1 godzinę do wyrośnięcia.',
      'Resztę mąki, cukru i zimnego masła rozetrzyj palcami na kruszonkę. Jagody wymieszaj z mąką ziemniaczaną.',
      'Podziel ciasto na 8 części, uformuj kule i spłaszcz je na blasze z papierem. Zrób w środku każdej zagłębienie.',
      'Nałóż jagody, posyp kruszonką i odstaw na 20 minut do napuszenia.',
      'Piecz w piekarniku nagrzanym do 180°C przez 20–25 minut, aż drożdżówki się zezłocą.',
    ],
    photo:
      'Two round golden yeast buns with a centre of juicy dark blueberries, topped with buttery crumble',
    vessel: 'board',
  },
  {
    plan: 'DE-017',
    title: 'Tarta z truskawkami i kremem',
    description:
      'Krucha, maślana tarta wypełniona puszystym kremem z mascarpone i śmietanki, ułożona świeżymi truskawkami. Efektowny letni deser, który wymaga pieczenia tylko spodu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    seasons: ['SUMMER'],
    equipment: ['OVEN'],
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['masło', 110, 'g'],
      ['cukier puder', 110, 'g'],
      ['jajko', 1, 'szt'],
      ['ser mascarpone', 250, 'g'],
      ['śmietanka 30', 150, 'ml'],
      ['cukier waniliowy', 16, 'g'],
      ['truskawka', 500, 'g'],
    ],
    steps: [
      'Posiekaj zimne masło z mąką i 50 g cukru pudru, dodaj jajko i szybko zagnieć ciasto. Schłódź 30 minut.',
      'Wylep ciastem formę do tarty o średnicy 26 cm, nakłuj spód widelcem, przykryj papierem i obciąż fasolą.',
      'Piecz w piekarniku nagrzanym do 190°C przez 15 minut, zdejmij obciążenie i piecz jeszcze 10 minut do zezłocenia. Wystudź.',
      'Ubij zimną śmietankę z mascarpone, resztą cukru pudru i cukrem waniliowym na sztywny krem.',
      'Rozsmaruj krem na spodzie, ułóż na nim przekrojone na pół truskawki i schłódź 30 minut przed krojeniem.',
    ],
    photo:
      'A slice of golden shortcrust tart filled with thick white mascarpone cream and topped with neatly arranged halved fresh red strawberries',
  },
  {
    plan: 'DE-018',
    title: 'Lody jogurtowe z truskawkami',
    description:
      'Domowe lody z truskawek, gęstego jogurtu greckiego i miodu, bez maszyny do lodów. Lekki, owocowy deser na upał, który dzieci chętnie jedzą zamiast sklepowych lodów.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 260,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DESSERT',
    seasons: ['SUMMER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['truskawka', 400, 'g'],
      ['jogurt grecki', 300, 'g'],
      ['miód', 50, 'g'],
      ['cytryna', 20, 'g'],
    ],
    steps: [
      'Truskawki umyj i odszypułkuj. Kilka pokrój w kostkę i odłóż.',
      'Zmiksuj blenderem resztę truskawek z jogurtem, miodem i sokiem z cytryny na gładką masę.',
      'Wmieszaj pokrojone truskawki, przelej masę do płaskiego pojemnika i wstaw do zamrażarki.',
      'Przez pierwsze 2 godziny co 30 minut przemieszaj lody widelcem, żeby nie powstały kryształki lodu. Zamrażaj łącznie 4 godziny.',
      'Przed podaniem odstaw na 10 minut w temperaturze pokojowej i nakładaj gałki łyżką zanurzoną w ciepłej wodzie.',
    ],
    photo:
      'Two scoops of pale pink strawberry frozen yogurt with visible red strawberry pieces, garnished with fresh strawberry halves',
    vessel: 'bowl',
  },
  {
    plan: 'DE-019',
    title: 'Tarta ze śliwkami i migdałami',
    description:
      'Krucha tarta z migdałowym kremem frangipane i gęsto ułożonymi połówkami śliwek, które w piekarniku puszczają ciemny, lekko kwaśny sok. Jesienny deser do kawy albo herbaty z cynamonem.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    seasons: ['AUTUMN'],
    equipment: ['OVEN', 'BLENDER'],
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['masło', 170, 'g'],
      ['cukier', 110, 'g'],
      ['jajko', 2, 'szt'],
      ['migdał', 100, 'g'],
      ['śliwka', 500, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Posiekaj 120 g zimnego masła z mąką i 40 g cukru, dodaj 1 jajko i zagnieć ciasto. Schłódź 30 minut.',
      'Wylep ciastem formę do tarty o średnicy 26 cm i podpiecz w piekarniku nagrzanym do 190°C przez 12 minut.',
      'Migdały zmiel blenderem na mąkę. Utrzyj resztę masła i cukru, dodaj drugie jajko i zmielone migdały.',
      'Śliwki umyj, przekrój na pół i wydryluj.',
      'Rozsmaruj krem migdałowy na spodzie, ułóż ciasno śliwki przeciętą stroną do góry i posyp cynamonem.',
      'Piecz w piekarniku w 180°C przez 35–40 minut, aż krem się zezłoci. Wystudź przed krojeniem.',
    ],
    photo:
      'A slice of rustic shortcrust tart with golden almond frangipane and tightly arranged purple plum halves with glossy dark juices, dusted with cinnamon',
  },
  {
    plan: 'DE-020',
    title: 'Pieczone gruszki z cynamonem i jogurtem',
    description:
      'Połówki gruszek pieczone z miodem i cynamonem, podane z chłodnym jogurtem greckim i chrupiącymi orzechami. Lekki, rozgrzewający deser na jesienne wieczory, naturalnie bez glutenu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DESSERT',
    seasons: ['AUTUMN'],
    equipment: ['OVEN'],
    ingredients: [
      ['gruszka', 600, 'g'],
      ['miód', 40, 'g'],
      ['cynamon', 3, 'g'],
      ['orzech włoski', 30, 'g'],
      ['jogurt grecki', 200, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C. Gruszki umyj, przekrój na pół i wydrąż łyżeczką gniazda nasienne.',
      'Ułóż gruszki przeciętą stroną do góry w naczyniu żaroodpornym, polej miodem i posyp cynamonem.',
      'Piecz 20–25 minut, aż gruszki zmiękną i lekko się skarmelizują.',
      'Orzechy posiekaj i podpraż 3 minuty na suchej patelni.',
      'Podawaj ciepłe gruszki z łyżką jogurtu, polane sokiem z naczynia i posypane orzechami.',
    ],
    photo:
      'Two warm roasted pear halves glazed with honey and cinnamon, served with a dollop of thick white Greek yogurt and toasted chopped walnuts',
  },
  {
    plan: 'DE-021',
    title: 'Ciasto dyniowe z cynamonem',
    description:
      'Wilgotne, pomarańczowe ciasto z pieczonej dyni z cynamonem i imbirem, z orzechami i cienką warstwą kremu z serka. Najlepszy sposób na wykorzystanie jesiennej dyni.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 100,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    seasons: ['AUTUMN'],
    equipment: ['OVEN', 'BLENDER'],
    ingredients: [
      ['dynia', 400, 'g'],
      ['mąka pszenna', 250, 'g'],
      ['cukier brązowy', 150, 'g'],
      ['olej rzepakowy', 120, 'ml'],
      ['jajko', 3, 'szt'],
      ['proszek do pieczenia', 8, 'g'],
      ['soda oczyszczona', 3, 'g'],
      ['cynamon', 6, 'g'],
      ['imbir mielony', 2, 'g'],
      ['orzech włoski', 50, 'g'],
      ['serek kremowy', 150, 'g'],
      ['cukier puder', 40, 'g'],
    ],
    steps: [
      'Dynię obierz, pokrój w kostkę i upiecz w piekarniku w 200°C przez 25 minut do miękkości. Zmiksuj blenderem na puree i wystudź.',
      'Ubij jajka z cukrem brązowym, wlej olej i dodaj puree z dyni.',
      'Wmieszaj mąkę przesianą z proszkiem, sodą, cynamonem i imbirem, a na końcu posiekane orzechy.',
      'Przełóż ciasto do formy 22 × 30 cm wyłożonej papierem i piecz w piekarniku w 180°C przez 35–40 minut, do suchego patyczka.',
      'Wystudź ciasto. Serek kremowy utrzyj z cukrem pudrem i rozsmaruj cienko na wierzchu.',
    ],
    photo:
      'A square slice of moist orange spiced pumpkin cake flecked with chopped walnuts, topped with a thin layer of white cream cheese frosting',
  },
  {
    plan: 'DE-022',
    title: 'Muffinki dyniowe',
    description:
      'Puszyste muffinki z puree dyniowym i przyprawą do piernika, z chrupiącymi pestkami dyni na wierzchu. Szybki jesienny wypiek do pudełka i na podwieczorek dla całej rodziny.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    seasons: ['AUTUMN'],
    equipment: ['OVEN', 'BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['dynia', 300, 'g'],
      ['mąka pszenna', 220, 'g'],
      ['cukier brązowy', 120, 'g'],
      ['olej rzepakowy', 80, 'ml'],
      ['jajko', 2, 'szt'],
      ['mleko', 100, 'ml'],
      ['proszek do pieczenia', 10, 'g'],
      ['przyprawa do piernika', 6, 'g'],
      ['pestki dyni', 30, 'g'],
    ],
    steps: [
      'Dynię pokrój w kostkę i ugotuj na parze 15 minut do miękkości. Zmiksuj blenderem na puree i przestudź.',
      'W jednej misce wymieszaj mąkę, proszek do pieczenia, cukier brązowy i przyprawę do piernika.',
      'W drugiej roztrzep jajka z olejem, mlekiem i puree z dyni.',
      'Połącz obie masy łyżką, tylko do zwilżenia składników, i nałóż do 12 papilotek w formie na muffinki. Posyp pestkami dyni.',
      'Piecz w piekarniku nagrzanym do 180°C przez 22–25 minut, do suchego patyczka. Wystudź na kratce.',
    ],
    photo:
      'Two golden orange pumpkin muffins with domed tops sprinkled with green pumpkin seeds, in paper liners',
    vessel: 'board',
  },
  {
    plan: 'DE-023',
    title: 'Ciasto pomarańczowe na oliwie',
    description:
      'Wilgotne ciasto w stylu śródziemnomorskim, pieczone na oliwie z oliwek z dużą ilością skórki i soku z pomarańczy. Pachnie zimowymi cytrusami i długo pozostaje świeże.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['pomarańcza', 300, 'g'],
      ['oliwa z oliwek', 150, 'ml'],
      ['mąka pszenna', 250, 'g'],
      ['cukier', 180, 'g'],
      ['jajko', 3, 'szt'],
      ['jogurt naturalny', 100, 'g'],
      ['proszek do pieczenia', 10, 'g'],
      ['cukier puder', 20, 'g'],
    ],
    steps: [
      'Z pomarańczy zetrzyj skórkę i wyciśnij sok. Formę o średnicy 24 cm wyłóż papierem do pieczenia.',
      'Ubij jajka z cukrem i skórką pomarańczową na jasną masę (5 minut).',
      'Cienkim strumieniem wlewaj oliwę, dalej miksując, potem dodaj jogurt i sok z pomarańczy.',
      'Wmieszaj szpatułką mąkę przesianą z proszkiem do pieczenia i przelej ciasto do formy.',
      'Piecz w piekarniku nagrzanym do 175°C przez 40–45 minut, do suchego patyczka. Wystudź i oprósz cukrem pudrem.',
    ],
    photo:
      'A wedge of golden olive oil orange cake dusted with powdered sugar, showing a moist yellow crumb flecked with orange zest',
  },
  {
    plan: 'DE-024',
    title: 'Ciasto korzenne z jabłkami',
    description:
      'Maślane ciasto z przyprawą do piernika, miodem i rodzynkami, gęsto przełożone kawałkami jabłek. Zimowy wypiek, który pachnie jak świąteczna kuchnia, a robi się go bez miksera.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 80,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['jabłko', 600, 'g'],
      ['mąka pszenna', 250, 'g'],
      ['cukier brązowy', 150, 'g'],
      ['masło', 150, 'g'],
      ['jajko', 3, 'szt'],
      ['miód', 40, 'g'],
      ['przyprawa do piernika', 12, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['rodzynka', 50, 'g'],
    ],
    steps: [
      'Jabłka obierz, usuń gniazda nasienne i pokrój w kostkę 1,5 cm.',
      'Roztop masło z miodem i cukrem brązowym, przestudź 10 minut, potem wmieszaj rózgą jajka.',
      'Dodaj mąkę przesianą z proszkiem do pieczenia i przyprawą do piernika, wymieszaj do połączenia.',
      'Wmieszaj jabłka i rodzynki, przełóż ciasto do formy 22 × 30 cm wyłożonej papierem.',
      'Piecz w piekarniku nagrzanym do 175°C przez 45–50 minut, do suchego patyczka. Wystudź w formie.',
    ],
    photo:
      'Two square slices of dark spiced honey cake with visible chunks of baked apple and raisins, lightly glossy golden-brown top',
  },
];
