/**
 * Katalog 1000 — część DE-b: desery i podwieczorki DE-025 … DE-047 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Fit i wegańskie ──
  {
    plan: 'DE-025',
    title: 'Brownie z fasoli',
    description:
      'Wilgotne, mocno czekoladowe brownie, w którym mąkę zastępuje zmiksowana czarna fasola. Nikt nie zgadnie, z czego jest — a przy tym jest wegańskie, bez glutenu i sycące dzięki białku i błonnikowi.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['OVEN', 'BLENDER'],
    ingredients: [
      ['fasola czarna z puszki', 250, 'g'],
      ['kakao', 40, 'g'],
      ['syrop klonowy', 100, 'g'],
      ['cukier brązowy', 50, 'g'],
      ['olej kokosowy', 60, 'g'],
      ['siemię lniane', 15, 'g'],
      ['czekolada gorzka', 80, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C (góra–dół) i wyłóż formę 20 × 20 cm papierem do pieczenia.',
      'Zmiel siemię lniane, zalej 45 ml wody i odstaw na 5 minut, aż zgęstnieje.',
      'Fasolę odcedź i dokładnie przepłucz. Rozpuść olej kokosowy, a czekoladę posiekaj.',
      'Zmiksuj w blenderze fasolę, siemię, olej, syrop klonowy, cukier brązowy, kakao, proszek do pieczenia i sól na gładką masę.',
      'Wmieszaj łyżką posiekaną czekoladę, przełóż masę do formy i wyrównaj.',
      'Piecz 25 minut — środek ma zostać lekko wilgotny. Wystudź w formie, a potem pokrój na 8 kwadratów.',
    ],
    photo:
      'Dark fudgy black bean brownie squares with a crackly top and melted dark chocolate chunks, stacked on a plate',
  },
  {
    plan: 'DE-026',
    title: 'Sernik z kaszy jaglanej',
    description:
      'Kremowy „sernik” z kaszy jaglanej ugotowanej na mleku kokosowym, z cytryną, na spodzie z daktyli i migdałów, podany z malinami. Smakuje jak klasyczny sernik, a jest wegański i bez glutenu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 240,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['OVEN', 'BLENDER'],
    ingredients: [
      ['migdał', 100, 'g'],
      ['daktyl suszony', 120, 'g'],
      ['kasza jaglana', 200, 'g'],
      ['mleko kokosowe z puszki', 400, 'ml'],
      ['syrop klonowy', 100, 'g'],
      ['cytryna', 100, 'g'],
      ['cukier waniliowy', 16, 'g'],
      ['mąka ziemniaczana', 30, 'g'],
      ['malina mrożona', 200, 'g'],
    ],
    steps: [
      'Przepłucz kaszę jaglaną wrzątkiem, wsyp do garnka, wlej mleko kokosowe i 300 ml wody. Gotuj pod przykryciem na małym ogniu 20 minut, aż zmięknie, i lekko przestudź.',
      'Migdały zmiel w blenderze, dodaj daktyle i miksuj, aż masa zacznie się sklejać. Wyłóż nią dno tortownicy 22 cm i dociśnij.',
      'Z cytryny zetrzyj skórkę i wyciśnij sok. Zmiksuj ciepłą kaszę z syropem klonowym, cukrem waniliowym, sokiem i skórką z cytryny oraz mąką ziemniaczaną na gładki krem.',
      'Wylej masę na spód i piecz w piekarniku nagrzanym do 170°C przez 45 minut.',
      'Wystudź sernik w uchylonym piekarniku, a potem schłodź w lodówce co najmniej 2 godziny.',
      'Maliny podgrzej krótko w rondelku, aż puszczą sok, rozłóż na serniku i pokrój na 8 kawałków.',
    ],
    photo:
      'Slice of pale creamy millet cheesecake on a dark date and almond crust, topped with glossy warm raspberries',
  },
  {
    plan: 'DE-027',
    title: 'Ciasteczka owsiane z bananem bez cukru',
    description:
      'Miękkie ciasteczka z płatków owsianych i dojrzałych bananów, z rodzynkami, słonecznikiem i cynamonem. Słodzą je tylko owoce, więc to dobry podwieczorek dla dzieci — gotowe w pół godziny.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['banan', 2, 'szt'],
      ['płatki owsiane', 150, 'g'],
      ['rodzynka', 40, 'g'],
      ['słonecznik łuszczony', 20, 'g'],
      ['olej kokosowy', 20, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C i wyłóż blachę papierem do pieczenia.',
      'Obierz banany i rozgnieć je widelcem na gładką masę. Dodaj roztopiony olej kokosowy i cynamon.',
      'Wsyp płatki owsiane, rodzynki i słonecznik, wymieszaj i odstaw na 5 minut, żeby płatki nasiąkły.',
      'Nabieraj masę łyżką, formuj 16 kulek i spłaszczaj je na blasze na grubość 1 cm.',
      'Piecz 15–18 minut, aż brzegi się zezłocą. Ostudź na blasze — po wystygnięciu ciasteczka stężeją.',
    ],
    photo:
      'Soft round banana oat cookies with raisins and sunflower seeds, golden edges, scattered on a plate',
  },
  {
    plan: 'DE-028',
    title: 'Mus czekoladowy z aquafaby',
    description:
      'Lekki, puszysty mus z gorzkiej czekolady, w którym białka zastępuje ubita woda z ciecierzycy. Wegański, bez glutenu i zaskakująco podobny do klasycznego musu, podany ze świeżymi malinami.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 150,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DESSERT',
    ingredients: [
      ['woda z ciecierzycy', 150, 'ml'],
      ['czekolada gorzka', 150, 'g'],
      ['cukier puder', 20, 'g'],
      ['cytryna', 5, 'g'],
      ['malina', 100, 'g'],
    ],
    steps: [
      'Czekoladę połam i rozpuść w misce nad garnkiem z gotującą się wodą. Odstaw, aż będzie letnia.',
      'Wodę z ciecierzycy przelej do wysokiej miski, dodaj kilka kropel soku z cytryny i ubijaj mikserem na najwyższych obrotach 6–8 minut na sztywną pianę.',
      'Pod koniec ubijania dosypuj po łyżce cukru pudru, aż piana będzie lśniąca.',
      'Wlej czekoladę do piany cienkim strumieniem i delikatnie wmieszaj szpatułką, żeby jej nie odpowietrzyć.',
      'Przełóż mus do 4 pucharków i schłódź w lodówce 2 godziny. Podawaj z malinami.',
    ],
    photo:
      'Airy dark chocolate mousse in small glass cups, topped with fresh raspberries and a light dusting of cocoa',
    vessel: 'bowl',
  },
  {
    plan: 'DE-029',
    title: 'Batoniki proteinowe bez pieczenia',
    description:
      'Ciągnące batoniki z płatków owsianych, białka w proszku i masła orzechowego, polane gorzką czekoladą. Robisz je w kwadrans bez piekarnika, a zapas w lodówce ratuje po treningu i w pracy.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 75,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    features: ['LUNCHBOX'],
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['białko w proszku', 90, 'g'],
      ['masło orzechowe', 60, 'g'],
      ['miód', 40, 'g'],
      ['mleko', 60, 'ml'],
      ['czekolada gorzka', 30, 'g'],
    ],
    steps: [
      'Wyłóż małą formę (ok. 15 × 20 cm) papierem do pieczenia.',
      'Masło orzechowe i miód podgrzej w rondelku 1 minutę, aż się rozrzedzą.',
      'W misce wymieszaj płatki owsiane z białkiem w proszku, dodaj masło orzechowe z miodem i mleko. Zagnieć gęstą, klejącą masę.',
      'Przełóż masę do formy i mocno dociśnij łyżką na grubość 1,5 cm.',
      'Rozpuść czekoladę w kąpieli wodnej i polej nią wierzch cienkimi paskami.',
      'Schłódź w lodówce co najmniej godzinę, potem pokrój na 8 batoników. Przechowuj w lodówce do 5 dni.',
    ],
    photo:
      'Chewy oat protein bars with peanut butter, drizzled with thin stripes of dark chocolate, cut and stacked on a board',
    vessel: 'board',
  },
  {
    plan: 'DE-030',
    title: 'Sernik proteinowy ze skyru na zimno',
    description:
      'Chłodny sernik na bazie skyru i chudego twarogu, na spodzie z migdałów i daktyli, z truskawkami na wierzchu. Bez pieczenia i bez glutenu, a dzięki skyrowi lekki i bardzo bogaty w białko.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 300,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    ingredients: [
      ['migdał', 50, 'g'],
      ['daktyl suszony', 50, 'g'],
      ['skyr naturalny', 800, 'g'],
      ['ser twaróg chudy', 250, 'g'],
      ['miód', 60, 'g'],
      ['cytryna', 30, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['żelatyna', 20, 'g'],
      ['truskawka', 250, 'g'],
    ],
    steps: [
      'Zmiel migdały, dodaj daktyle i miksuj, aż masa się sklei. Wyłóż nią dno tortownicy 22 cm, dociśnij i wstaw do lodówki.',
      'Żelatynę zalej 100 ml zimnej wody, odstaw na 10 minut, a potem podgrzej, mieszając, aż się rozpuści (nie gotuj).',
      'Twaróg zmiel albo zmiksuj ze skyrem, miodem, cukrem waniliowym i sokiem z cytryny na gładki krem.',
      'Do ciepłej żelatyny wmieszaj 3 łyżki kremu, a potem wlej ją cienkim strumieniem do reszty masy, cały czas miksując.',
      'Wylej masę na spód, ułóż na wierzchu przekrojone truskawki i schłódź w lodówce co najmniej 4 godziny.',
    ],
    photo:
      'Slice of white no-bake skyr cheesecake on a thin almond date crust, topped with halved fresh strawberries',
  },
  {
    plan: 'DE-031',
    title: 'Galaretka z owocami i jogurtem',
    description:
      'Warstwowy deser w pucharkach: kremowy jogurt z miodem, a na nim truskawkowa galaretka z truskawkami i borówkami. Lekki, orzeźwiający i bez glutenu — dzieci go uwielbiają.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 180,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'DESSERT',
    ingredients: [
      ['galaretka', 75, 'g'],
      ['jogurt naturalny', 300, 'g'],
      ['miód', 20, 'g'],
      ['truskawka', 150, 'g'],
      ['borówka', 100, 'g'],
    ],
    steps: [
      'Rozpuść galaretkę w 400 ml gorącej wody (o 100 ml mniej niż na opakowaniu) i odstaw do przestudzenia.',
      'Jogurt wymieszaj z miodem i rozłóż do 4 pucharków. Wstaw je na 15 minut do zamrażarki, żeby jogurt lekko stężał.',
      'Truskawki pokrój w ćwiartki i razem z borówkami ułóż na jogurcie.',
      'Zalej owoce chłodną, ale jeszcze płynną galaretką.',
      'Schłódź w lodówce 2–3 godziny, aż galaretka całkiem stężeje.',
    ],
    photo:
      'Layered dessert glasses with white yogurt at the bottom and clear red strawberry jelly filled with strawberries and blueberries',
    vessel: 'bowl',
  },
  {
    plan: 'DE-032',
    title: 'Tiramisu fit ze skyrem',
    description:
      'Lżejsza wersja tiramisu: biszkopty nasączone kawą przełożone kremem ze skyru i chudego twarogu, oprószone kakao. Smak klasyka przy połowie tłuszczu i dużej porcji białka.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 200,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DESSERT',
    ingredients: [
      ['biszkopt', 100, 'g'],
      ['kawa rozpuszczalna', 6, 'g'],
      ['skyr naturalny', 500, 'g'],
      ['ser twaróg chudy', 200, 'g'],
      ['miód', 40, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['kakao', 10, 'g'],
    ],
    steps: [
      'Rozpuść kawę w 200 ml gorącej wody i ostudź.',
      'Twaróg zmiksuj ze skyrem, miodem i cukrem waniliowym na gładki, gęsty krem.',
      'Biszkopty krótko maczaj w kawie i ułóż połowę na dnie 4 pucharków albo małego naczynia.',
      'Przykryj połową kremu, ułóż resztę nasączonych biszkoptów i zakończ warstwą kremu.',
      'Schłódź w lodówce co najmniej 3 godziny, a przed podaniem oprósz kakao przez sitko.',
    ],
    photo:
      'Layered tiramisu in glass cups with coffee-soaked sponge fingers, thick white skyr cream and a dusting of cocoa powder',
    vessel: 'bowl',
  },
  {
    plan: 'DE-033',
    title: 'Budyń kokosowy z ananasem',
    description:
      'Gładki domowy budyń na mleku kokosowym i migdałowym, zagęszczony mąką ziemniaczaną, z soczystym ananasem i prażonymi wiórkami. Wegański, bez glutenu i gotowy w kwadrans.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DESSERT',
    ingredients: [
      ['mleko kokosowe z puszki', 200, 'ml'],
      ['mleko migdałowe', 300, 'ml'],
      ['mąka ziemniaczana', 35, 'g'],
      ['cukier', 30, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['ananas', 250, 'g'],
      ['wiórki kokosowe', 10, 'g'],
    ],
    steps: [
      'Odlej 100 ml mleka migdałowego i rozmieszaj w nim mąkę ziemniaczaną na gładko.',
      'Resztę mleka migdałowego, mleko kokosowe, cukier i cukier waniliowy zagotuj w garnku.',
      'Wlej zawiesinę z mąką, energicznie mieszając, i gotuj 1–2 minuty, aż budyń zgęstnieje.',
      'Wiórki kokosowe upraż na suchej patelni na złoto, a ananasa obierz i pokrój w drobną kostkę.',
      'Przełóż budyń do 4 pucharków, ułóż ananasa i posyp wiórkami. Podawaj ciepły albo schłodzony.',
    ],
    photo:
      'Smooth white coconut pudding in glass cups topped with bright yellow diced pineapple and golden toasted coconut flakes',
    vessel: 'bowl',
  },
  {
    plan: 'DE-034',
    title: 'Muffinki bananowe bez cukru',
    description:
      'Puszyste muffinki z mąki pełnoziarnistej, słodzone tylko dojrzałymi bananami, z borówkami w środku. Dobre na podwieczorek i do szkolnego pudełka — dzieci nie zauważą, że nie ma w nich cukru.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['banan', 3, 'szt'],
      ['jajko', 2, 'szt'],
      ['olej rzepakowy', 50, 'ml'],
      ['jogurt naturalny', 100, 'g'],
      ['mąka pełnoziarnista', 150, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['cynamon', 2, 'g'],
      ['borówka', 100, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C i wyłóż formę na muffinki 8 papilotkami.',
      'Banany rozgnieć widelcem na gładko, dodaj jajka, olej i jogurt, wymieszaj trzepaczką.',
      'W drugiej misce połącz mąkę pełnoziarnistą z proszkiem do pieczenia i cynamonem.',
      'Wsyp suche składniki do mokrych i wymieszaj łyżką tylko do połączenia. Na koniec delikatnie wmieszaj borówki.',
      'Rozłóż ciasto do papilotek i piecz 22–25 minut, aż patyczek wbity w środek będzie suchy. Ostudź na kratce.',
    ],
    photo:
      'Golden wholemeal banana muffins in paper cases with juicy blueberries bursting through the domed tops',
  },
  {
    plan: 'DE-035',
    title: 'Budyń jaglany z malinami',
    description:
      'Aksamitny budyń z kaszy jaglanej ugotowanej na mleku migdałowym i zmiksowanej z malinami na różowy krem. Wegański i bez glutenu, naturalnie słodki i sycący na popołudnie.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DESSERT',
    equipment: ['BLENDER'],
    ingredients: [
      ['kasza jaglana', 60, 'g'],
      ['mleko migdałowe', 400, 'ml'],
      ['syrop klonowy', 20, 'g'],
      ['malina', 150, 'g'],
      ['migdał', 15, 'g'],
    ],
    steps: [
      'Przepłucz kaszę jaglaną na sitku gorącą wodą, żeby pozbyć się goryczki.',
      'Wsyp kaszę do garnka, wlej mleko migdałowe i gotuj na małym ogniu pod przykryciem 18 minut, aż będzie bardzo miękka.',
      'Przełóż gorącą kaszę do blendera, dodaj syrop klonowy i połowę malin, zmiksuj na gładki krem.',
      'Migdały posiekaj i upraż krótko na suchej patelni.',
      'Przelej budyń do 2 pucharków, ułóż resztę malin i posyp migdałami.',
    ],
    photo:
      'Smooth pink millet raspberry pudding in two glass cups topped with whole raspberries and toasted chopped almonds',
    vessel: 'bowl',
  },
  // ── Kuchnie świata ──
  {
    plan: 'DE-036',
    title: 'Flan — karmelowy krem jajeczny',
    description:
      'Hiszpański krem jajeczny pieczony w kąpieli wodnej pod warstwą płynnego karmelu. Aksamitny, delikatnie waniliowy i bez glutenu, a wymaga tylko jajek, mleka i cukru.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 300,
    servings: 6,
    cuisine: 'SPANISH',
    dishType: 'DESSERT',
    equipment: ['OVEN'],
    ingredients: [
      ['cukier', 150, 'g'],
      ['jajko', 4, 'szt'],
      ['mleko', 500, 'ml'],
      ['cukier waniliowy', 16, 'g'],
      ['cytryna', 10, 'g'],
    ],
    steps: [
      'W rondelku rozpuść 100 g cukru na średnim ogniu, bez mieszania, aż zrobi się bursztynowy karmel. Od razu wylej go na dno formy o średnicy 20 cm i rozprowadź.',
      'Mleko podgrzej ze skórką otartą z cytryny i cukrem waniliowym, nie dopuszczając do wrzenia, i przestudź 10 minut.',
      'Jajka roztrzep z resztą cukru, wlej ciepłe mleko, cały czas mieszając, i przecedź masę przez sitko na karmel.',
      'Wstaw formę do większego naczynia, wlej do niego gorącą wodę do połowy wysokości formy i piecz w piekarniku nagrzanym do 160°C przez 50 minut, aż środek się zetnie.',
      'Wystudź, a potem schłódź w lodówce co najmniej 3 godziny. Obwiedź nożem brzegi i odwróć flan na talerz, żeby karmel spłynął.',
    ],
    photo:
      'Glossy golden caramel flan unmolded on a plate, smooth custard with amber caramel sauce pooling around it',
  },
  {
    plan: 'DE-037',
    title: 'Ryż na mleku z musem truskawkowym',
    description:
      'Kremowy ryż gotowany na mleku z wanilią, podany z chłodnym musem ze świeżych truskawek. Letni smak dzieciństwa, bez glutenu, dobry na ciepło i prosto z lodówki.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'DESSERT',
    seasons: ['SUMMER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['ryż biały', 100, 'g'],
      ['mleko', 600, 'ml'],
      ['cukier', 40, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['truskawka', 300, 'g'],
    ],
    steps: [
      'Przepłucz ryż, wsyp do garnka z mlekiem i zagotuj, mieszając.',
      'Zmniejsz ogień do minimum, dodaj cukier waniliowy i gotuj pod przykryciem 30 minut, co kilka minut mieszając, aż ryż będzie miękki i kremowy.',
      'W tym czasie umyj truskawki, oderwij szypułki i zmiksuj je w blenderze z cukrem na gładki mus.',
      'Przełóż ryż do 4 miseczek i polej musem truskawkowym.',
    ],
    photo:
      'Creamy rice pudding in bowls topped with a bright red fresh strawberry mousse and a halved strawberry',
    vessel: 'bowl',
  },
  {
    plan: 'DE-038',
    title: 'Churros z sosem czekoladowym',
    description:
      'Chrupiące hiszpańskie churros z ciasta parzonego, obtoczone w cukrze z cynamonem i maczane w gęstym sosie z gorzkiej czekolady. W airfryerze wychodzą złote bez głębokiego smażenia.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 4,
    cuisine: 'SPANISH',
    dishType: 'CAKE',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['masło', 40, 'g'],
      ['cukier', 50, 'g'],
      ['sól', 1, 'g'],
      ['mąka pszenna', 150, 'g'],
      ['jajko', 1, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['cynamon', 3, 'g'],
      ['czekolada gorzka', 80, 'g'],
      ['śmietanka 30', 100, 'ml'],
    ],
    steps: [
      'W garnku zagotuj 250 ml wody z masłem, 20 g cukru i solą. Zdejmij z ognia, wsyp mąkę naraz i energicznie mieszaj, aż powstanie gładka kula ciasta.',
      'Przestudź ciasto 5 minut, wbij jajko i miksuj, aż się połączy. Przełóż do rękawa z gwiazdkową końcówką.',
      'Wyciskaj na papier do pieczenia paski długości 10 cm i spryskaj je olejem.',
      'Piecz w airfryerze w 190°C przez 10–12 minut, aż będą złote i chrupiące. W piekarniku: 200°C, termoobieg, 18–20 minut.',
      'Wymieszaj resztę cukru z cynamonem i obtocz w nim gorące churros.',
      'Śmietankę podgrzej do wrzenia, zdejmij z ognia, dodaj połamaną czekoladę i mieszaj, aż sos będzie gładki. Podawaj churros z sosem do maczania.',
    ],
    photo:
      'Golden ridged churros coated in cinnamon sugar next to a small cup of thick glossy dark chocolate dipping sauce',
  },
  {
    plan: 'DE-039',
    title: 'Crostata z dżemem morelowym',
    description:
      'Włoska tarta z maślanego kruchego ciasta z cytrynową nutą, wypełniona dżemem morelowym i przykryta charakterystyczną kratką. Prosta, elegancka i świetna do popołudniowej kawy.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 8,
    cuisine: 'ITALIAN',
    dishType: 'CAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['masło', 125, 'g'],
      ['cukier puder', 80, 'g'],
      ['jajko', 2, 'szt'],
      ['cytryna', 20, 'g'],
      ['proszek do pieczenia', 4, 'g'],
      ['sól', 1, 'g'],
      ['dżem', 300, 'g'],
    ],
    steps: [
      'Mąkę wymieszaj z cukrem pudrem, proszkiem do pieczenia, solą i skórką otartą z cytryny. Dodaj zimne masło w kostce i posiekaj nożem na kruszonkę.',
      'Dodaj jajka i szybko zagnieć gładkie ciasto. Owiń folią i schłódź w lodówce 30 minut.',
      'Nagrzej piekarnik do 180°C. Dwie trzecie ciasta rozwałkuj i wyłóż nim formę do tarty 24 cm razem z brzegami.',
      'Rozsmaruj na spodzie dżem morelowy. Z reszty ciasta wytnij paski i ułóż je na dżemie w kratkę.',
      'Piecz 30–35 minut, aż ciasto będzie złociste. Wystudź w formie przed krojeniem na 8 kawałków.',
    ],
    photo:
      'Golden Italian crostata with a shortcrust lattice top over glossy orange apricot jam, one slice cut out',
  },
  {
    plan: 'DE-040',
    title: 'Kheer — indyjski pudding ryżowy z kardamonem',
    description:
      'Indyjski pudding z ryżu basmati powoli gotowanego w mleku, aż zgęstnieje, pachnący kardamonem, z migdałami i rodzynkami. Kremowy, rozgrzewający i bez glutenu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 4,
    cuisine: 'INDIAN',
    dishType: 'DESSERT',
    ingredients: [
      ['ryż basmati', 60, 'g'],
      ['mleko', 1000, 'ml'],
      ['cukier', 60, 'g'],
      ['kardamon mielony', 2, 'g'],
      ['migdał', 25, 'g'],
      ['rodzynka', 25, 'g'],
    ],
    steps: [
      'Przepłucz ryż i namocz go w zimnej wodzie na 20 minut, potem odcedź.',
      'Zagotuj mleko w garnku z grubym dnem, wsyp ryż i gotuj na małym ogniu 35–40 minut, często mieszając, aż mleko zgęstnieje, a ryż się rozpadnie.',
      'Dodaj cukier, kardamon i rodzynki, gotuj jeszcze 5 minut.',
      'Migdały pokrój w słupki. Rozlej kheer do miseczek i posyp migdałami — podawaj ciepły albo schłodzony.',
    ],
    photo:
      'Creamy Indian kheer rice pudding in bowls garnished with slivered almonds, plump raisins and a pinch of ground cardamom',
    vessel: 'bowl',
  },
  {
    plan: 'DE-041',
    title: 'Ryż kokosowy z mango',
    description:
      'Tajski deser z ryżu jaśminowego nasączonego słodkim mlekiem kokosowym, z plastrami dojrzałego mango i sezamem. Wegański, bez glutenu i prosty, a smakuje jak z ulicznego straganu w Bangkoku.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 4,
    cuisine: 'THAI',
    dishType: 'DESSERT',
    ingredients: [
      ['ryż jaśminowy', 150, 'g'],
      ['mleko kokosowe z puszki', 250, 'ml'],
      ['cukier', 40, 'g'],
      ['sól', 1, 'g'],
      ['mango', 400, 'g'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Przepłucz ryż kilka razy, aż woda będzie przejrzysta. Ugotuj go w 250 ml wody pod przykryciem na małym ogniu przez 15 minut.',
      'W rondelku podgrzej 200 ml mleka kokosowego z cukrem i solą, aż cukier się rozpuści.',
      'Wlej słodkie mleko do gorącego ryżu, wymieszaj, przykryj i odstaw na 15 minut, żeby ryż je wchłonął.',
      'Sezam upraż na suchej patelni. Mango obierz i pokrój w plastry.',
      'Nałóż ryż na talerzyki, ułóż obok mango, polej resztą mleka kokosowego i posyp sezamem.',
    ],
    photo:
      'Mound of glossy coconut sticky rice with fanned slices of ripe yellow mango, drizzled coconut cream and toasted sesame seeds',
  },
  {
    plan: 'DE-042',
    title: 'Cookies z czekoladą',
    description:
      'Amerykańskie ciastka z chrupiącym brzegiem i miękkim środkiem, pełne kawałków mlecznej czekolady. Ciasto robi się w kwadrans, a pieką się 10 minut — idealne do wspólnego pieczenia z dziećmi.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 8,
    cuisine: 'AMERICAN',
    dishType: 'CAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['masło', 125, 'g'],
      ['cukier brązowy', 120, 'g'],
      ['cukier', 50, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 220, 'g'],
      ['soda oczyszczona', 3, 'g'],
      ['sól', 1, 'g'],
      ['czekolada mleczna', 150, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C i wyłóż dwie blachy papierem do pieczenia.',
      'Miękkie masło utrzyj mikserem z cukrem brązowym, cukrem i cukrem waniliowym na puszystą masę, potem dodaj jajko.',
      'Wsyp mąkę wymieszaną z sodą i solą i połącz łyżką. Czekoladę posiekaj na kawałki i wmieszaj do ciasta.',
      'Formuj 16 kulek wielkości orzecha włoskiego i układaj na blachach w odstępach 5 cm.',
      'Piecz 10–12 minut, aż brzegi się zezłocą, a środek będzie jeszcze miękki. Zostaw na blasze na 5 minut, potem przełóż na kratkę.',
    ],
    photo:
      'Stack of golden chocolate chip cookies with crisp edges, soft centres and melting milk chocolate chunks',
  },
  // ── Grill i impreza ──
  {
    plan: 'DE-043',
    title: 'Banany z grilla z czekoladą',
    description:
      'Banany pieczone na grillu w skórce, nadziewane mleczną czekoladą, która roztapia się w środku, posypane orzechami. Najprostszy deser z grilla — dzieci jedzą go łyżeczką prosto ze skórki.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DESSERT',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['banan', 4, 'szt'],
      ['czekolada mleczna', 60, 'g'],
      ['orzech laskowy', 20, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Natnij banany wzdłuż przez skórkę po wewnętrznej stronie łuku, nie przecinając dolnej skórki, i lekko rozchyl.',
      'Czekoladę połam na kostki i wciśnij w nacięcia. Orzechy laskowe posiekaj.',
      'Owiń każdego banana folią aluminiową i połóż na ruszcie rozgrzanego grilla. Grilluj 8–10 minut, aż czekolada się roztopi, a skórka ściemnieje.',
      'Na patelni grillowej: piecz banany w folii pod przykryciem na średnim ogniu 10–12 minut.',
      'Rozchyl folię, posyp banany orzechami i szczyptą cynamonu i podawaj od razu z łyżeczkami.',
    ],
    photo:
      'Grilled bananas in blackened peels split open, filled with melted milk chocolate and sprinkled with chopped hazelnuts',
  },
  {
    plan: 'DE-044',
    title: 'Brzoskwinie z grilla z jogurtem i miodem',
    description:
      'Połówki brzoskwiń grillowane, aż się skarmelizują, podane z gęstym jogurtem greckim, miodem, miętą i prażonymi migdałami. Lekki, letni deser na koniec grillowania, bez glutenu.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DESSERT',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['brzoskwinia', 500, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['cynamon', 1, 'g'],
      ['jogurt grecki', 200, 'g'],
      ['miód', 30, 'g'],
      ['migdał', 20, 'g'],
      ['mięta', 3, 'g'],
    ],
    steps: [
      'Przekrój brzoskwinie na pół, usuń pestki i posmaruj przekrojone strony cienko olejem.',
      'Połóż je przekrojem w dół na ruszcie rozgrzanego grilla i grilluj 4–5 minut, aż pojawią się ciemne paski, potem odwróć i grilluj jeszcze 2 minuty.',
      'Na patelni grillowej: smaż brzoskwinie przekrojem w dół na mocno rozgrzanej patelni 4–5 minut.',
      'Migdały posiekaj i upraż na suchej patelni lub na brzegu grilla.',
      'Ułóż brzoskwinie na talerzu, nałóż do każdej łyżkę jogurtu greckiego, polej miodem, oprósz cynamonem i posyp migdałami i listkami mięty.',
    ],
    photo:
      'Caramelised grilled peach halves with char marks, dollops of thick Greek yogurt, drizzled honey, chopped almonds and mint leaves',
  },
  {
    plan: 'DE-045',
    title: 'Babeczki z kremem na imprezę',
    description:
      'Waniliowe babeczki z puszystym kremem mascarpone i świeżymi malinami na czubku. Efektowne na urodziny i przyjęcia, a przy tym proste — dzieci mogą same dekorować swoje.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 8,
    cuisine: 'AMERICAN',
    dishType: 'CAKE',
    occasions: ['PARTY'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['masło', 100, 'g'],
      ['cukier', 120, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 100, 'ml'],
      ['mąka pszenna', 180, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['ser mascarpone', 200, 'g'],
      ['śmietanka 30', 100, 'ml'],
      ['cukier puder', 50, 'g'],
      ['malina', 80, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C i wyłóż formę na muffinki 8 papilotkami.',
      'Miękkie masło utrzyj z cukrem i cukrem waniliowym na puszystą masę, dodawaj po jednym jajku, a potem mleko.',
      'Wsyp mąkę wymieszaną z proszkiem do pieczenia i wymieszaj tylko do połączenia. Rozłóż ciasto do papilotek do 2/3 wysokości.',
      'Piecz 20–22 minuty, aż patyczek będzie suchy, i całkowicie wystudź na kratce.',
      'Zimną śmietankę ubij z mascarpone i cukrem pudrem na sztywny krem, przełóż do rękawa z gwiazdkową końcówką.',
      'Wyciśnij krem na babeczki i udekoruj każdą malinami.',
    ],
    photo:
      'Vanilla cupcakes with tall swirls of white mascarpone frosting, each topped with fresh raspberries, arranged on a plate',
  },
  {
    plan: 'DE-046',
    title: 'Sernik na zimno z galaretką',
    description:
      'Klasyk polskich przyjęć: puszysta masa serowa na maślanym spodzie z herbatników, pod warstwą truskawek zatopionych w galaretce. Bez pieczenia, najlepiej przygotować go dzień wcześniej.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 360,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    occasions: ['PARTY'],
    ingredients: [
      ['herbatnik', 150, 'g'],
      ['masło', 60, 'g'],
      ['ser twaróg półtłusty', 500, 'g'],
      ['śmietanka 30', 200, 'ml'],
      ['cukier puder', 80, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['żelatyna', 15, 'g'],
      ['galaretka', 75, 'g'],
      ['truskawka', 250, 'g'],
    ],
    steps: [
      'Herbatniki pokrusz na drobno, wymieszaj z roztopionym masłem, wyłóż na dno tortownicy 22 cm, dociśnij i wstaw do lodówki.',
      'Żelatynę zalej 80 ml zimnej wody na 10 minut, potem podgrzej, aż się rozpuści, i lekko przestudź.',
      'Twaróg zmiel albo zmiksuj z cukrem pudrem i cukrem waniliowym. Śmietankę ubij na sztywno.',
      'Do żelatyny wmieszaj 2 łyżki masy serowej, wlej ją do reszty masy, a na koniec delikatnie połącz z bitą śmietaną. Wyłóż na spód i schłódź 2 godziny.',
      'Galaretkę rozpuść w 400 ml gorącej wody i ostudź, aż zacznie gęstnieć. Truskawki pokrój na połówki i ułóż na stężałej masie.',
      'Zalej truskawki galaretką i schłódź sernik co najmniej 3 godziny, najlepiej przez noc.',
    ],
    photo:
      'Slice of no-bake cheesecake with a biscuit crumb base, fluffy white cheese layer and a glossy red jelly top with halved strawberries',
  },
  {
    plan: 'DE-047',
    title: 'Brownie z orzechami włoskimi',
    description:
      'Klasyczne, gęste brownie z gorzkiej czekolady i masła, z chrupiącymi orzechami włoskimi, upieczone w airfryerze w małej formie. Szybko i bez nagrzewania dużego piekarnika.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['czekolada gorzka', 120, 'g'],
      ['masło', 100, 'g'],
      ['cukier', 120, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 60, 'g'],
      ['kakao', 15, 'g'],
      ['sól', 1, 'g'],
      ['orzech włoski', 60, 'g'],
    ],
    steps: [
      'Rozpuść czekoladę z masłem w misce nad garnkiem z gotującą się wodą i lekko przestudź.',
      'Jajka ubij z cukrem trzepaczką na jasną masę, wlej czekoladę i wymieszaj.',
      'Wsyp przesianą mąkę z kakao i solą, połącz łyżką. Orzechy włoskie posiekaj grubo i wmieszaj do ciasta.',
      'Przełóż ciasto do formy 18 cm wyłożonej papierem, pasującej do kosza airfryera.',
      'Piecz w airfryerze w 160°C przez 25 minut, aż wierzch się zetnie, a środek zostanie lekko wilgotny. W piekarniku: 175°C, góra–dół, 25–30 minut.',
      'Wystudź w formie co najmniej 30 minut i pokrój na 6 kawałków.',
    ],
    photo:
      'Fudgy square pieces of dark chocolate brownie with a shiny crackled top and chopped walnuts, on a plate',
  },
];
