/**
 * Katalog 1000 — część DS-a: drugie śniadania i lunchboxy DS-001 … DS-029 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Sałatki do pudełka ──
  {
    plan: 'DS-001',
    title: 'Sałatka z bulgurem, ciecierzycą i fetą',
    description:
      'Sycąca sałatka z bulguru, ciecierzycy, ogórka i pomidorków z kruszoną fetą, natką i cytrynowym dressingiem z oregano. Robisz ją raz, a w lodówce trzyma się świetnie przez kilka dni.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 4,
    cuisine: 'GREEK',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['bulgur', 150, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['ser feta', 150, 'g'],
      ['ogórek', 250, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['natka pietruszki', 20, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['cytryna', 60, 'g'],
      ['oregano', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wsyp bulgur do garnka, zalej 300 ml wrzącej wody, przykryj i odstaw na 15 minut, aż wchłonie płyn. Rozdziel widelcem i ostudź.',
      'Ciecierzycę odcedź i przepłucz na sitku.',
      'Ogórek pokrój w kostkę, pomidorki koktajlowe przekrój na ćwiartki, cebulę czerwoną posiekaj drobno, a natkę pietruszki posiekaj.',
      'Z cytryny wyciśnij sok i wymieszaj go z oliwą, oregano i pieprzem.',
      'Połącz bulgur z ciecierzycą i warzywami, polej dressingiem i wymieszaj. Na wierzch pokrusz fetę.',
      'Rozłóż do pudełek i przechowuj w lodówce do 3 dni.',
    ],
    photo:
      'Fluffy bulgur salad with chickpeas, diced cucumber, quartered cherry tomatoes, red onion, chopped parsley and crumbled white feta',
    vessel: 'bowl',
  },
  {
    plan: 'DS-002',
    title: 'Sałatka z makaronem orzo, pomidorami i mozzarellą',
    description:
      'Makaron orzo w kształcie ziaren ryżu z pomidorkami koktajlowymi, mozzarellą, rukolą i świeżą bazylią, skropiony oliwą i octem balsamicznym. Włoski smak lata w pudełku do pracy.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron orzo', 120, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['mozzarella', 125, 'g'],
      ['rukola', 40, 'g'],
      ['bazylia', 10, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ocet balsamiczny', 10, 'ml'],
      ['czosnek', 1, 'szt'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron orzo w osolonej wodzie al dente według opakowania, zwykle 8–9 minut. Odcedź, przelej zimną wodą i odsącz.',
      'Pomidorki koktajlowe przekrój na połówki, a mozzarellę pokrój w kostkę.',
      'Czosnek przeciśnij przez praskę i wymieszaj z oliwą, octem balsamicznym i pieprzem.',
      'Połącz makaron z pomidorkami, mozzarellą i rukolą, polej sosem i wymieszaj.',
      'Na koniec dodaj porwane listki bazylii i przełóż sałatkę do pudełek.',
    ],
    photo:
      'Orzo pasta salad with halved red cherry tomatoes, white mozzarella cubes, peppery rocket leaves and fresh basil glistening with olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'DS-003',
    title: 'Naleśniki zapiekane z kurczakiem i szpinakiem',
    description:
      'Cienkie naleśniki zwinięte z farszem z kurczaka, szpinaku i czosnku, zapieczone pod warstwą mozzarelli. Sycący, białkowy posiłek, który dobrze znosi odgrzewanie w pracy.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 250, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['filet z kurczaka', 300, 'g'],
      ['szpinak', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['mozzarella tarta', 50, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Wymieszaj trzepaczką mąkę, jajka, mleko i szczyptę soli na gładkie ciasto i odstaw na 10 minut.',
      'Rozgrzej patelnię, posmaruj ją cienko olejem i usmaż 4 cienkie naleśniki, po około 1 minucie z każdej strony.',
      'Kurczaka pokrój w drobną kostkę, dopraw pieprzem i resztą soli, a potem smaż na pozostałym oleju 6–7 minut, aż się zrumieni.',
      'Dodaj przeciśnięty czosnek i szpinak, smaż jeszcze 2 minuty, aż liście zwiędną.',
      'Rozgrzej piekarnik do 200°C. Nałóż farsz na naleśniki, zwiń je w rulony i ułóż w naczyniu żaroodpornym.',
      'Posyp naleśniki mozzarellą i zapiekaj 12–15 minut, aż ser się rozpuści i lekko zrumieni.',
    ],
    photo:
      'Two rolled crepes stuffed with diced golden chicken and wilted spinach, baked side by side under a layer of melted, lightly browned mozzarella',
  },
  {
    plan: 'DS-004',
    title: 'Sałatka z kurczakiem, kaszą pęczak i ogórkiem',
    description:
      'Pęczak z pieczonym kurczakiem, chrupiącym ogórkiem, dymką i koperkiem w lekkim sosie jogurtowo-musztardowym. Porządna porcja białka, a ugotowana raz starcza na kilka dni.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza pęczak', 150, 'g'],
      ['filet z kurczaka', 500, 'g'],
      ['ogórek', 400, 'g'],
      ['cebula dymka', 50, 'g'],
      ['koperek', 20, 'g'],
      ['jogurt naturalny', 200, 'g'],
      ['musztarda', 10, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ugotuj kaszę pęczak w 500 ml wody pod przykryciem przez 25–30 minut, aż będzie miękka. Odcedź i ostudź.',
      'Kurczaka natrzyj solą i pieprzem, smaż na oleju 5–6 minut z każdej strony. Odstaw na 5 minut i pokrój w kostkę.',
      'Ogórek pokrój w kostkę, dymkę w cienkie plasterki, a koperek posiekaj.',
      'Wymieszaj jogurt naturalny z musztardą i połową koperku.',
      'Połącz kaszę, kurczaka i warzywa, polej sosem i wymieszaj. Posyp resztą koperku.',
      'Rozłóż do pudełek i trzymaj w lodówce do 3 dni.',
    ],
    photo:
      'Pearl barley salad with golden seared chicken cubes, diced green cucumber, sliced spring onion and dill in a creamy yogurt dressing',
    vessel: 'bowl',
  },
  {
    plan: 'DS-005',
    title: 'Sałatka z komosy ryżowej, czarną fasolą i awokado',
    description:
      'Komosa ryżowa z czarną fasolą, kukurydzą, pomidorkami i awokado, doprawiona limonką, kolendrą i kuminem. Kolorowa, roślinna i sycąca sałatka w meksykańskim stylu, bez glutenu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['komosa ryżowa', 100, 'g'],
      ['fasola czarna z puszki', 240, 'g'],
      ['awokado', 1, 'szt'],
      ['kukurydza z puszki', 100, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['kolendra', 10, 'g'],
      ['limonka', 60, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Przepłucz komosę ryżową na sitku, zalej 200 ml wody i gotuj pod przykryciem 15 minut. Ostudź.',
      'Fasolę i kukurydzę odcedź i przepłucz.',
      'Pomidorki przekrój na ćwiartki, cebulę posiekaj drobno, a awokado pokrój w kostkę i od razu skrop sokiem z połowy limonki.',
      'Resztę soku z limonki wymieszaj z oliwą, kuminem, solą i posiekaną kolendrą.',
      'Połącz komosę z fasolą, kukurydzą, pomidorkami i cebulą, polej dressingiem, a na wierzchu ułóż awokado.',
    ],
    photo:
      'Quinoa salad with black beans, yellow sweet corn, cherry tomatoes and red onion in a lime and coriander dressing, topped with green avocado cubes',
    vessel: 'bowl',
  },
  {
    plan: 'DS-006',
    title: 'Burrito z batatem i czarną fasolą',
    description:
      'Duże tortille wypełnione pieczonym batatem z wędzoną papryką, czarną fasolą, kukurydzą i świeżą salsą pomidorową. Roślinne, sycące burrito, które zawinięte w folię wygodnie zabierzesz do pracy.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['batat', 300, 'g'],
      ['fasola czarna z puszki', 200, 'g'],
      ['kukurydza z puszki', 80, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['pomidor', 150, 'g'],
      ['sałata rzymska', 40, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['limonka', 30, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 210°C. Batata obierz i pokrój w kostkę 1,5 cm, wymieszaj z olejem, wędzoną papryką i kuminem.',
      'Rozłóż batata na blasze wyłożonej papierem i piecz 25 minut, aż będzie miękki i przyrumieniony.',
      'Fasolę i kukurydzę odcedź, fasolę lekko rozgnieć widelcem. Pomidor pokrój w drobną kostkę i wymieszaj z posiekaną cebulą i sokiem z limonki na świeżą salsę. Sałatę pokrój w paski.',
      'Podgrzej tortille na suchej patelni po 20 sekund z każdej strony.',
      'Na środek każdej tortilli nałóż fasolę, batata, kukurydzę, salsę i sałatę. Podwiń boki i zwiń ciasno burrito.',
      'Do pudełka zawiń każde burrito w papier lub folię i przekrój na pół.',
    ],
    photo:
      'Wheat tortilla burrito cut in half showing orange roasted sweet potato cubes, black beans, yellow corn, lettuce and fresh diced tomato salsa',
    vessel: 'board',
  },
  {
    plan: 'DS-007',
    title: 'Sałatka grecka z kurczakiem i kaszą',
    description:
      'Klasyczna sałatka grecka z ogórkiem, pomidorem, oliwkami i fetą, wzbogacona grillowanym kurczakiem i kaszą jęczmienną. Pełnowartościowy lunch z dużą porcją białka.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza jęczmienna', 80, 'g'],
      ['filet z kurczaka', 300, 'g'],
      ['ogórek', 200, 'g'],
      ['pomidor', 200, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['ser feta', 60, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 30, 'g'],
      ['oregano', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj kaszę jęczmienną w 250 ml wody pod przykryciem przez 15–20 minut. Odcedź i ostudź.',
      'Kurczaka natrzyj połową oregano i pieprzem, smaż na rozgrzanej patelni grillowej skropionej 1 łyżeczką oliwy po 5–6 minut z każdej strony. Pokrój w paski.',
      'Ogórek i pomidor pokrój w dużą kostkę, cebulę w piórka, a oliwki przekrój na połówki.',
      'Z cytryny wyciśnij sok i wymieszaj z resztą oliwy i oregano.',
      'Połącz kaszę z warzywami i oliwkami, polej dressingiem, ułóż kurczaka i pokrusz na wierzch fetę.',
    ],
    photo:
      'Greek salad with pearl barley, sliced grilled chicken, chunky cucumber and tomato, black olives, red onion and crumbled feta sprinkled with oregano',
    vessel: 'bowl',
  },
  {
    plan: 'DS-008',
    title: 'Sałatka z kuskusem, pieczonymi warzywami i hummusem',
    description:
      'Kuskus z pieczoną cukinią, papryką i czerwoną cebulą, podany z kremowym hummusem, natką i cytryną. Roślinny lunch pełen smaku, który równie dobrze smakuje na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza kuskus', 120, 'g'],
      ['cukinia', 250, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['hummus', 100, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 220°C. Cukinię i paprykę pokrój w kostkę, cebulę w ósemki.',
      'Wymieszaj warzywa z oliwą, papryką słodką i solą, rozłóż na blasze i piecz 20–25 minut, mieszając w połowie.',
      'Kuskus zalej 180 ml wrzącej wody, przykryj na 5 minut, potem rozdziel widelcem.',
      'Połącz kuskus z pieczonymi warzywami, skrop sokiem z cytryny i wymieszaj z posiekaną natką.',
      'Przełóż do pudełek, a obok każdej porcji nałóż hummus.',
    ],
    photo:
      'Couscous salad with roasted golden zucchini, red pepper and red onion, chopped parsley and a generous dollop of creamy hummus next to the salad',
    vessel: 'bowl',
  },
  {
    plan: 'DS-009',
    title: 'Pieczony indyk z ryżem i warzywami',
    description:
      'Filet z indyka pieczony w papryce i tymianku razem z brokułem, marchewką i papryką, podany z ryżem basmati. Chudy, pożywny obiad do pudełka, który przygotujesz na kilka dni naraz.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z indyka', 600, 'g'],
      ['ryż basmati', 140, 'g'],
      ['brokuł', 400, 'g'],
      ['marchew', 300, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 3, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Indyka natrzyj połową oliwy, papryką słodką, czosnkiem granulowanym, tymiankiem, pieprzem i solą.',
      'Marchew pokrój w słupki, paprykę w paski, a brokuł podziel na różyczki. Wymieszaj warzywa z resztą oliwy.',
      'Ułóż indyka na środku blachy, a warzywa dookoła. Piecz 25–30 minut, aż mięso będzie soczyste i upieczone w środku.',
      'W tym czasie ugotuj ryż basmati w 280 ml wody pod przykryciem przez 12 minut.',
      'Odstaw indyka na 5 minut i pokrój w plastry.',
      'Rozłóż ryż, warzywa i indyka do 4 pudełek i przechowuj w lodówce do 4 dni.',
    ],
    photo:
      'Sliced roasted turkey breast with paprika crust next to fluffy basmati rice, roasted broccoli florets, carrot sticks and red pepper strips',
  },
  {
    plan: 'DS-010',
    title: 'Sałatka z fasolką szparagową, jajkiem i ziemniakami',
    description:
      'Letnia sałatka z młodych ziemniaków, zielonej fasolki, jajek na twardo i pomidorków w musztardowym winegrecie z koperkiem. Prosta, sycąca i świetna na ciepłe dni.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SALAD',
    seasons: ['SUMMER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['ziemniak młody', 400, 'g'],
      ['fasolka szparagowa', 250, 'g'],
      ['jajko', 4, 'szt'],
      ['pomidor koktajlowy', 150, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['koperek', 10, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['musztarda', 10, 'g'],
      ['ocet jabłkowy', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ziemniaki wyszoruj, przekrój na połówki i gotuj w osolonej wodzie 15–18 minut. Odcedź i ostudź.',
      'Fasolce odetnij końce i gotuj ją 6 minut, a potem przelej zimną wodą.',
      'Jajka gotuj 9 minut, ostudź w zimnej wodzie, obierz i pokrój w ćwiartki.',
      'Wymieszaj oliwę z musztardą, octem jabłkowym, pieprzem i posiekanym koperkiem.',
      'Połącz ziemniaki, fasolkę, pomidorki przekrojone na pół i posiekaną cebulę, polej winegretem, a na wierzchu ułóż jajka.',
    ],
    photo:
      'Summer salad of halved baby potatoes, bright green beans, quartered hard-boiled eggs, cherry tomatoes and dill in a mustard vinaigrette',
    vessel: 'bowl',
  },
  {
    plan: 'DS-011',
    title: 'Sałatka z młodych ziemniaków, szparagów i rzodkiewki',
    description:
      'Wiosenna sałatka z młodych ziemniaków, zielonych szparagów i chrupiącej rzodkiewki z dymką, koperkiem i prażonym słonecznikiem. Świeża, roślinna i pełna sezonowych smaków.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SALAD',
    seasons: ['SPRING'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['ziemniak młody', 400, 'g'],
      ['szparagi', 250, 'g'],
      ['rzodkiewka', 150, 'g'],
      ['cebula dymka', 40, 'g'],
      ['koperek', 10, 'g'],
      ['słonecznik łuszczony', 20, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['musztarda', 10, 'g'],
      ['ocet jabłkowy', 10, 'ml'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ziemniaki wyszoruj i gotuj w osolonej wodzie 15–18 minut. Odcedź, ostudź i przekrój na połówki.',
      'Szparagom odłam zdrewniałe końce, pokrój je na 3 cm kawałki i gotuj 3 minuty, potem przelej zimną wodą.',
      'Słonecznik upraż na suchej patelni przez 3 minuty.',
      'Rzodkiewki pokrój w plasterki, dymkę i koperek posiekaj.',
      'Wymieszaj oliwę z musztardą i octem jabłkowym. Połącz ziemniaki ze szparagami, rzodkiewką, dymką i koperkiem, polej sosem, wymieszaj i posyp słonecznikiem.',
    ],
    photo:
      'Spring salad with halved new potatoes, green asparagus pieces, thin pink radish slices, spring onion, dill and toasted sunflower seeds',
    vessel: 'bowl',
  },
  {
    plan: 'DS-012',
    title: 'Sałatka z kaszą gryczaną, kurczakiem i pieczarkami',
    description:
      'Kasza gryczana z podsmażonymi pieczarkami i kurczakiem, ogórkiem kiszonym i roszponką. Jesienna, aromatyczna sałatka z dużą porcją białka, dobra na ciepło i na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SALAD',
    seasons: ['AUTUMN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza gryczana', 80, 'g'],
      ['filet z kurczaka', 280, 'g'],
      ['pieczarka', 250, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['ogórek kiszony', 100, 'g'],
      ['roszponka', 50, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['majeranek', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj kaszę gryczaną w 170 ml wody pod przykryciem przez 15 minut, potem odstaw.',
      'Kurczaka pokrój w kostkę, dopraw solą i pieprzem, smaż na połowie oleju 6–7 minut, aż się zrumieni. Przełóż na talerz.',
      'Na tej samej patelni rozgrzej resztę oleju i smaż pokrojone pieczarki z cebulą przez 6 minut, na koniec dodaj majeranek.',
      'Ogórki kiszone pokrój w kostkę, natkę posiekaj.',
      'Połącz kaszę z kurczakiem, pieczarkami, ogórkami i roszponką, posyp natką.',
    ],
    photo:
      'Buckwheat salad with golden chicken cubes, browned sliced mushrooms with onion, diced pickled cucumber, lamb lettuce and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'DS-013',
    title: 'Makaron z kurczakiem i brokułem w sosie jogurtowym',
    description:
      'Penne z soczystym kurczakiem i brokułem w lekkim, czosnkowym sosie z jogurtu greckiego i parmezanu. Kremowy makaron z dużą porcją białka, który dobrze odgrzewa się w pracy.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron penne', 140, 'g'],
      ['filet z kurczaka', 300, 'g'],
      ['brokuł', 300, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['ser parmezan', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron penne w osolonej wodzie według opakowania. Na 4 minuty przed końcem wrzuć do garnka różyczki brokułu, potem odcedź, zachowując pół szklanki wody.',
      'Kurczaka pokrój w kostkę, dopraw pieprzem i smaż na oleju 6–7 minut, aż się zrumieni.',
      'Dodaj przeciśnięty czosnek i smaż jeszcze minutę.',
      'Zdejmij patelnię z ognia, wmieszaj jogurt grecki, tarty parmezan i 3–4 łyżki wody z makaronu.',
      'Połącz sos z makaronem i brokułem, dopraw pieprzem i przełóż do pudełek.',
    ],
    photo:
      'Penne pasta with chicken pieces and bright green broccoli florets coated in a creamy white yogurt and parmesan sauce',
    vessel: 'bowl',
  },
  {
    plan: 'DS-014',
    title: 'Sałatka z arbuzem, fetą i miętą',
    description:
      'Soczysty arbuz ze słoną fetą, ogórkiem, czerwoną cebulą i świeżą miętą, skropiony limonką i oliwą. Orzeźwiająca, lekka sałatka na upalne dni, gotowa w kilka minut.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'SALAD',
    seasons: ['SUMMER'],
    ingredients: [
      ['arbuz', 500, 'g'],
      ['ser feta', 100, 'g'],
      ['ogórek', 150, 'g'],
      ['cebula czerwona', 30, 'g'],
      ['mięta', 10, 'g'],
      ['limonka', 30, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['pestki dyni', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Arbuza obierz ze skórki, usuń pestki i pokrój w kostkę 2 cm.',
      'Ogórek pokrój w półplasterki, a cebulę czerwoną w cienkie piórka.',
      'Ułóż arbuza, ogórek i cebulę na talerzu, pokrusz na wierzch fetę.',
      'Skrop sokiem z limonki i oliwą, posyp listkami mięty, pestkami dyni i świeżo mielonym pieprzem.',
    ],
    photo:
      'Juicy red watermelon cubes with crumbled white feta, cucumber half-moons, thin red onion slivers, fresh mint leaves and pumpkin seeds',
  },
  {
    plan: 'DS-015',
    title: 'Sałatka z kurczakiem, kukurydzą i czarną fasolą',
    description:
      'Kurczak w wędzonej papryce i kuminie z czarną fasolą, kukurydzą, papryką i chrupiącą sałatą rzymską, doprawiony limonką i kolendrą. Białkowa sałatka w meksykańskim stylu, bez glutenu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 280, 'g'],
      ['fasola czarna z puszki', 200, 'g'],
      ['kukurydza z puszki', 120, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['sałata rzymska', 80, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['limonka', 40, 'g'],
      ['kolendra', 10, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Kurczaka natrzyj wędzoną papryką, kuminem, solą i łyżeczką oliwy. Smaż na rozgrzanej patelni po 5–6 minut z każdej strony, odstaw na 5 minut i pokrój w paski.',
      'Fasolę i kukurydzę odcedź i przepłucz.',
      'Paprykę pokrój w kostkę, cebulę posiekaj drobno, a sałatę rzymską pokrój w paski.',
      'Wymieszaj sok z limonki z resztą oliwy i posiekaną kolendrą.',
      'Połącz warzywa z fasolą i kukurydzą, polej dressingiem i ułóż na wierzchu kurczaka.',
    ],
    photo:
      'Mexican salad of romaine lettuce, black beans, sweet corn, diced red pepper and red onion in a lime and coriander dressing, topped with smoky paprika chicken strips',
    vessel: 'bowl',
  },
  {
    plan: 'DS-016',
    title: 'Sałatka z soczewicą, pomidorkami i fetą',
    description:
      'Zielona soczewica ugotowana al dente z pomidorkami koktajlowymi, ogórkiem, czerwoną cebulą i fetą w cytrynowym dressingu z oregano. Bezmięsna sałatka z dużą porcją roślinnego białka.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica zielona', 140, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['ser feta', 100, 'g'],
      ['ogórek', 150, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['cytryna', 30, 'g'],
      ['oregano', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przepłucz soczewicę, zalej 600 ml wody i gotuj 20–25 minut, aż będzie miękka, ale nie rozpadnie się. Odcedź i ostudź.',
      'Pomidorki przekrój na połówki, ogórek pokrój w kostkę, a cebulę i natkę posiekaj.',
      'Z cytryny wyciśnij sok i wymieszaj z oliwą, oregano i pieprzem.',
      'Połącz soczewicę z warzywami, polej dressingiem i wymieszaj.',
      'Na wierzch pokrusz fetę i przełóż sałatkę do pudełek.',
    ],
    photo:
      'Green lentil salad with halved cherry tomatoes, diced cucumber, red onion, chopped parsley and crumbled white feta cheese',
    vessel: 'bowl',
  },
  {
    plan: 'DS-017',
    title: 'Ryż z tofu, marchewką i sosem sezamowym',
    description:
      'Chrupiące kostki tofu z marchewką i edamame na ryżu jaśminowym, polane sosem z tahini, sosu sojowego, imbiru i czosnku. Roślinny lunch z dużą porcją białka, gotowy na kilka dni.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tofu', 600, 'g'],
      ['ryż jaśminowy', 180, 'g'],
      ['marchew', 300, 'g'],
      ['edamame', 300, 'g'],
      ['tahini', 30, 'g'],
      ['sos sojowy', 40, 'ml'],
      ['olej rzepakowy', 20, 'ml'],
      ['olej sezamowy', 10, 'ml'],
      ['czosnek', 2, 'szt'],
      ['imbir', 15, 'g'],
      ['cebula dymka', 40, 'g'],
      ['sezam', 10, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy w 360 ml wody pod przykryciem przez 12 minut, potem odstaw na 5 minut.',
      'Tofu odsącz, osusz ręcznikiem papierowym i pokrój w kostkę. Smaż na oleju rzepakowym na dużej patelni 8–10 minut, obracając, aż zrobi się złote i chrupiące.',
      'Marchew pokrój w cienkie słupki i dorzuć do tofu razem z edamame. Smaż 4 minuty.',
      'Wymieszaj tahini z sosem sojowym, olejem sezamowym, startym imbirem, przeciśniętym czosnkiem i 3 łyżkami ciepłej wody na gładki sos.',
      'Polej tofu i warzywa sosem, wymieszaj i podgrzewaj minutę.',
      'Rozłóż ryż do 4 pudełek, nałóż tofu z warzywami i posyp sezamem oraz pokrojoną dymką. Przechowuj w lodówce do 4 dni.',
    ],
    photo:
      'Jasmine rice topped with golden crispy tofu cubes, carrot matchsticks and green edamame in a glossy sesame sauce, sprinkled with sesame seeds and spring onion',
    vessel: 'bowl',
  },

  // ── Do pudełka na ciepło ──
  {
    plan: 'DS-018',
    title: 'Curry z soczewicą i batatem',
    description:
      'Gęste, rozgrzewające curry z czerwonej soczewicy i batata na mleku kokosowym z pomidorami, imbirem i garam masalą, z garścią szpinaku na koniec. Roślinny lunch, który następnego dnia smakuje jeszcze lepiej.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 4,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica czerwona', 200, 'g'],
      ['batat', 500, 'g'],
      ['mleko kokosowe z puszki', 200, 'ml'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['cebula', 150, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 15, 'g'],
      ['curry', 8, 'g'],
      ['garam masala', 4, 'g'],
      ['kurkuma', 2, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['szpinak', 100, 'g'],
      ['kolendra', 10, 'g'],
      ['sól', 3, 'g'],
    ],
    steps: [
      'Cebulę posiekaj i smaż na oleju w dużym garnku 5 minut. Dodaj przeciśnięty czosnek, starty imbir, curry, garam masalę i kurkumę, smaż minutę.',
      'Batata obierz i pokrój w kostkę 2 cm. Soczewicę przepłucz na sitku.',
      'Wrzuć do garnka batata i soczewicę, dodaj pomidory, mleko kokosowe i 400 ml wody. Zagotuj.',
      'Gotuj na małym ogniu pod przykryciem 20–25 minut, mieszając od czasu do czasu, aż soczewica się rozpadnie, a batat zmięknie.',
      'Wmieszaj szpinak i sól, gotuj jeszcze 2 minuty.',
      'Rozłóż do pudełek i posyp posiekaną kolendrą. W lodówce curry wytrzyma 4 dni.',
    ],
    photo:
      'Thick creamy golden-orange red lentil and sweet potato curry with soft sweet potato cubes and wilted spinach, sprinkled with fresh chopped coriander',
    vessel: 'bowl',
  },
  {
    plan: 'DS-019',
    title: 'Sałatka makaronowa z tuńczykiem, oliwkami i pomidorami',
    description:
      'Makaron świderki z tuńczykiem, czarnymi oliwkami, pomidorkami koktajlowymi i rukolą w cytrynowej oliwie z bazylią. Szybka sałatka w śródziemnomorskim stylu, która nie nudzi się w pudełku.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron świder', 140, 'g'],
      ['tuńczyk w puszce', 170, 'g'],
      ['oliwka czarna', 50, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['rukola', 40, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 30, 'g'],
      ['bazylia', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron świderki al dente według opakowania, odcedź i przelej zimną wodą.',
      'Tuńczyka odsącz i rozdziel widelcem na kawałki.',
      'Pomidorki przekrój na połówki, oliwki na plasterki, a cebulę posiekaj drobno.',
      'Wymieszaj oliwę z sokiem z cytryny i pieprzem.',
      'Połącz makaron z tuńczykiem, oliwkami, pomidorkami, cebulą i rukolą, polej sosem i posyp porwaną bazylią.',
    ],
    photo:
      'Fusilli pasta salad with flaked tuna, sliced black olives, halved cherry tomatoes, rocket leaves and fresh basil',
    vessel: 'bowl',
  },
  {
    plan: 'DS-020',
    title: 'Miska z ryżem, krewetkami, ogórkiem i sosem sezamowym',
    description:
      'Ryż jaśminowy z krewetkami smażonymi z czosnkiem i imbirem, świeżym ogórkiem, marchewką i edamame, polany sosem sezamowym z limonką. Kolorowa miska w stylu azjatyckim, bez nabiału.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ryż jaśminowy', 140, 'g'],
      ['krewetka', 250, 'g'],
      ['ogórek', 200, 'g'],
      ['marchew', 100, 'g'],
      ['edamame', 100, 'g'],
      ['sos sojowy', 12, 'ml'],
      ['olej sezamowy', 10, 'ml'],
      ['olej rzepakowy', 10, 'ml'],
      ['sezam', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['imbir', 10, 'g'],
      ['limonka', 30, 'g'],
      ['cebula dymka', 20, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy w 280 ml wody pod przykryciem przez 12 minut, potem odstaw na 5 minut.',
      'Edamame gotuj 4 minuty we wrzącej wodzie i odcedź.',
      'Rozgrzej olej rzepakowy, wrzuć przeciśnięty czosnek i połowę startego imbiru, a po 30 sekundach krewetki. Smaż 2–3 minuty, aż zróżowieją.',
      'Wymieszaj sos sojowy z olejem sezamowym, sokiem z limonki i resztą imbiru.',
      'Ogórek pokrój w półplasterki, a marchew zetrzyj na grubych oczkach lub pokrój w cienkie słupki.',
      'Rozłóż ryż do misek lub pudełek, ułóż krewetki, ogórek, marchew i edamame, polej sosem i posyp sezamem oraz dymką.',
    ],
    photo:
      'Jasmine rice topped with pink sauteed shrimp, cucumber half-moons, shredded orange carrot, green edamame, sesame seeds and spring onion with a glossy sesame dressing',
    vessel: 'bowl',
  },
  {
    plan: 'DS-021',
    title: 'Kuskus z krewetkami, papryką i natką',
    description:
      'Kuskus z krewetkami podsmażonymi na oliwie z czosnkiem i chili, słodką czerwoną i żółtą papryką oraz dużą ilością natki i cytryny. Szybki, lekki lunch bez nabiału, dobry na ciepło i na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza kuskus', 130, 'g'],
      ['krewetka', 250, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['papryka żółta', 160, 'g'],
      ['natka pietruszki', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 50, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['płatki chili', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Kuskus wsyp do miski, dodaj sól, zalej 200 ml wrzącej wody, przykryj i odstaw na 5 minut. Rozdziel widelcem.',
      'Paprykę czerwoną i żółtą pokrój w kostkę i smaż na połowie oliwy 5 minut.',
      'Dodaj resztę oliwy, przeciśnięty czosnek, płatki chili, paprykę słodką i krewetki. Smaż 2–3 minuty, aż krewetki zróżowieją.',
      'Wymieszaj kuskus z krewetkami i papryką, skrop sokiem z cytryny.',
      'Na koniec wmieszaj posiekaną natkę pietruszki i przełóż do pudełek.',
    ],
    photo:
      'Fluffy couscous with pink paprika garlic shrimp, diced red and yellow bell pepper, a pinch of chili flakes and plenty of chopped green parsley',
    vessel: 'bowl',
  },

  // ── Wrapy, kanapki i tortille ──
  {
    plan: 'DS-022',
    title: 'Wrap z kurczakiem tikka i sosem jogurtowym',
    description:
      'Tortilla z kurczakiem marynowanym w jogurcie i indyjskich przyprawach, chrupiącymi warzywami i chłodzącym sosem z jogurtu, ogórka i mięty. Białkowy wrap z charakterem, idealny do pudełka.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['filet z kurczaka', 300, 'g'],
      ['jogurt naturalny', 200, 'g'],
      ['garam masala', 4, 'g'],
      ['kurkuma', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['ogórek', 100, 'g'],
      ['sałata rzymska', 50, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['mięta', 5, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['cytryna', 20, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Wymieszaj połowę jogurtu z garam masalą, kurkumą, papryką, startym imbirem, przeciśniętym czosnkiem, sokiem z cytryny i solą.',
      'Kurczaka pokrój w paski, obtocz w marynacie i odstaw na 15 minut.',
      'Smaż kurczaka na oleju na mocno rozgrzanej patelni 6–7 minut, aż się przyrumieni.',
      'Ogórek zetrzyj na grubych oczkach, odciśnij i wymieszaj z resztą jogurtu i posiekaną miętą.',
      'Podgrzej tortille na suchej patelni. Posmaruj je sosem jogurtowym, ułóż sałatę, cebulę w piórkach i kurczaka, a potem ciasno zwiń.',
    ],
    photo:
      'Wheat tortilla wrap cut diagonally showing orange spiced chicken tikka strips, romaine lettuce, red onion and a creamy cucumber mint yogurt sauce',
    vessel: 'board',
  },
  {
    plan: 'DS-023',
    title: 'Kanapka z hummusem buraczanym, fetą i rukolą',
    description:
      'Żytni chleb posmarowany różowym hummusem z buraka i ciecierzycy, z pokruszoną fetą, rukolą i prażonymi pestkami dyni. Efektowna, sycąca kanapka bez mięsa na drugie śniadanie.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['chleb żytni', 140, 'g'],
      ['ciecierzyca z puszki', 150, 'g'],
      ['burak', 150, 'g'],
      ['tahini', 15, 'g'],
      ['cytryna', 20, 'g'],
      ['czosnek', 1, 'szt'],
      ['kmin rzymski', 1, 'g'],
      ['ser feta', 40, 'g'],
      ['rukola', 30, 'g'],
      ['pestki dyni', 15, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
    ],
    steps: [
      'Użyj ugotowanego buraka (może być gotowy, pakowany próżniowo) i pokrój go w kostkę. Ciecierzycę odcedź.',
      'Zblenduj buraka z ciecierzycą, tahini, sokiem z cytryny, czosnkiem, kuminem i oliwą na gładką pastę, w razie potrzeby dodaj łyżkę wody.',
      'Pestki dyni upraż na suchej patelni przez 2–3 minuty.',
      'Kromki chleba żytniego posmaruj grubo hummusem buraczanym, ułóż rukolę, pokrusz fetę i posyp pestkami dyni.',
    ],
    photo:
      'Rye bread slices spread thickly with vivid pink beetroot hummus, topped with rocket leaves, crumbled white feta and toasted pumpkin seeds',
    vessel: 'board',
  },
  {
    plan: 'DS-024',
    title: 'Tortilla zwijana z jajkiem, szpinakiem i fetą',
    description:
      'Cienki omlet ze szpinakiem usmażony razem z tortillą, z fetą i pomidorem w środku, zwinięty w ciasny rulon. Ciepłe albo zimne, sycące drugie śniadanie, które łatwo zapakować.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['jajko', 4, 'szt'],
      ['szpinak', 100, 'g'],
      ['ser feta', 45, 'g'],
      ['pomidor', 150, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Roztrzep jajka z pieprzem, a szpinak posiekaj grubo i wmieszaj do jajek.',
      'Rozgrzej połowę oleju na patelni o średnicy tortilli, wlej połowę masy jajecznej i rozprowadź po dnie.',
      'Gdy spód zacznie się ścinać, po około minucie, połóż na wierzchu tortillę, dociśnij i smaż jeszcze minutę. Odwróć i podgrzewaj 30 sekund.',
      'Zsuń tortillę omletem do góry, posyp połową pokruszonej fety i ułóż plasterki pomidora. Zwiń ciasno.',
      'Powtórz z drugą tortillą, a do pudełka przekrój każdą na pół.',
    ],
    photo:
      'A rolled wheat tortilla wrap cut in half revealing a thin spinach omelette layer, crumbled white feta and red tomato slices',
    vessel: 'board',
  },
  {
    plan: 'DS-025',
    title: 'Pita z pastą z ciecierzycy i warzywami',
    description:
      'Ciepła pita wypełniona domową pastą z ciecierzycy, tahini i cytryny oraz świeżym ogórkiem, pomidorem, papryką i sałatą. Roślinne, sycące drugie śniadanie, które łatwo zabrać ze sobą.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['pita', 120, 'g'],
      ['ciecierzyca z puszki', 200, 'g'],
      ['tahini', 20, 'g'],
      ['cytryna', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['kmin rzymski', 1, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka słodka mielona', 1, 'g'],
      ['ogórek', 100, 'g'],
      ['pomidor', 120, 'g'],
      ['papryka czerwona', 80, 'g'],
      ['sałata rzymska', 40, 'g'],
      ['cebula czerwona', 30, 'g'],
    ],
    steps: [
      'Ciecierzycę odcedź, zachowując 3 łyżki zalewy.',
      'Zblenduj ciecierzycę z tahini, sokiem z cytryny, czosnkiem, kuminem, oliwą i zalewą na gładką pastę.',
      'Ogórek, pomidor i paprykę pokrój w paski, cebulę w cienkie piórka, a sałatę porwij.',
      'Podgrzej pity na suchej patelni po 30 sekund z każdej strony i natnij je z boku, tworząc kieszonki.',
      'Posmaruj wnętrze grubo pastą, włóż warzywa i posyp papryką słodką.',
    ],
    photo:
      'A warm pita pocket spread with creamy chickpea paste and stuffed with crisp cucumber, tomato and red pepper strips, torn lettuce and thin red onion, dusted with paprika',
    vessel: 'board',
  },
  {
    plan: 'DS-026',
    title: 'Kanapka z tofu, awokado i kiełkami',
    description:
      'Pełnoziarnisty chleb z rozgniecionym awokado, podsmażonym wędzonym tofu, pomidorem i świeżymi kiełkami. Roślinna kanapka z dużą porcją białka i zdrowych tłuszczów.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['chleb pełnoziarnisty', 160, 'g'],
      ['tofu wędzone', 150, 'g'],
      ['awokado', 1, 'szt'],
      ['kiełki', 30, 'g'],
      ['pomidor', 120, 'g'],
      ['cytryna', 20, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['pieprz czarny', 1, 'g'],
      ['płatki chili', 1, 'g'],
    ],
    steps: [
      'Tofu wędzone pokrój w plastry grubości 0,5 cm i smaż na oleju po 2 minuty z każdej strony, aż się zrumieni.',
      'Awokado rozgnieć widelcem z sokiem z cytryny, pieprzem i płatkami chili.',
      'Pomidor pokrój w plasterki.',
      'Posmaruj kromki chleba pastą z awokado, ułóż tofu i pomidor, a na wierzchu garść kiełków. Przykryj drugą kromką.',
    ],
    photo:
      'Wholegrain bread sandwich layered with smashed green avocado, golden smoked tofu slices, tomato and a tuft of fresh sprouts',
    vessel: 'board',
  },
  {
    plan: 'DS-027',
    title: 'Bagietka z kurczakiem, mozzarellą i pesto',
    description:
      'Chrupiąca bagietka z soczystym kurczakiem, mozzarellą, pomidorem i rukolą, posmarowana bazyliowym pesto. Włoska kanapka z dużą porcją białka, która syci na długo.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['bagietka', 140, 'g'],
      ['filet z kurczaka', 250, 'g'],
      ['mozzarella', 100, 'g'],
      ['pesto bazyliowe', 25, 'g'],
      ['pomidor', 120, 'g'],
      ['rukola', 30, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['oregano', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka rozbij lekko na grubość 1,5 cm, natrzyj oliwą, oregano i pieprzem.',
      'Smaż na rozgrzanej patelni grillowej po 4–5 minut z każdej strony, odstaw na 5 minut i pokrój w plastry.',
      'Bagietkę przekrój na 2 części, a każdą wzdłuż na pół.',
      'Posmaruj wnętrze pesto, ułóż rukolę, plastry pomidora, mozzarelli i kurczaka, a potem złóż kanapki.',
    ],
    photo:
      'Crusty baguette sandwich with sliced grilled chicken, white mozzarella, tomato slices, rocket leaves and bright green basil pesto',
    vessel: 'board',
  },
  {
    plan: 'DS-028',
    title: 'Tortilla z fasolą, ryżem i salsą',
    description:
      'Tortilla z pikantną czerwoną fasolą, ryżem, papryką i salsą pomidorową, z chrupiącą sałatą, kolendrą i odrobiną chili. Roślinny, sycący lunch w meksykańskim stylu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['ryż biały', 70, 'g'],
      ['fasola czerwona z puszki', 170, 'g'],
      ['salsa pomidorowa', 50, 'g'],
      ['pomidor', 150, 'g'],
      ['papryka czerwona', 120, 'g'],
      ['cebula', 50, 'g'],
      ['papryczka chili', 10, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sałata lodowa', 50, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Ugotuj ryż w 140 ml wody pod przykryciem przez 12 minut.',
      'Cebulę i paprykę pokrój w kostkę i smaż na oleju 5 minut. Dodaj kumin i wędzoną paprykę, smaż 30 sekund.',
      'Wrzuć odcedzoną fasolę i salsę, podgrzewaj 3 minuty, lekko rozgniatając fasolę.',
      'Wymieszaj ryż z sokiem z limonki i posiekaną kolendrą.',
      'Pomidor pokrój w kostkę, a papryczkę chili posiekaj drobno.',
      'Podgrzej tortille, nałóż ryż, fasolę, pomidor, chili i poszatkowaną sałatę, a potem zwiń ciasno.',
    ],
    photo:
      'Rolled wheat tortilla cut in half showing red kidney beans, white rice with coriander, diced red pepper, tomato salsa and shredded lettuce',
    vessel: 'board',
  },
  {
    plan: 'DS-029',
    title: 'Kanapka z pieczoną papryką, hummusem i rukolą',
    description:
      'Ciabatta z kremowym hummusem, słodką pieczoną czerwoną papryką i pieprzną rukolą. Prosta roślinna kanapka o śródziemnomorskim smaku, gotowa w niecałe pół godziny.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['ciabatta', 160, 'g'],
      ['papryka czerwona', 320, 'g'],
      ['hummus', 100, 'g'],
      ['rukola', 30, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 230°C. Paprykę pokrój w szerokie paski, wymieszaj z oliwą, oregano i pieprzem.',
      'Rozłóż paprykę na blasze skórką do góry i piecz 15–18 minut, aż zmięknie i lekko się przypali.',
      'Ciabattę przekrój na 2 części, a każdą wzdłuż na pół. Podpiecz krótko w piekarniku przez 2 minuty.',
      'Posmaruj pieczywo hummusem, ułóż ciepłą paprykę i rukolę, a potem złóż kanapki.',
    ],
    photo:
      'Toasted ciabatta sandwich with creamy hummus, soft charred roasted red pepper strips and fresh rocket leaves',
    vessel: 'board',
  },
];
