/**
 * Katalog 1000 — część DS-b: drugie śniadania i lunchboxy DS-030 … DS-057 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'DS-030',
    title: 'Tortilla z hummusem, marchewką i szpinakiem',
    description:
      'Pszenna tortilla posmarowana gęstym hummusem, z tartą marchewką, młodym szpinakiem i prażonymi pestkami dyni. Zwija się w pięć minut, nie rozmięka w pudełku i syci do obiadu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['hummus', 100, 'g'],
      ['marchew', 150, 'g'],
      ['szpinak', 60, 'g'],
      ['pestki dyni', 15, 'g'],
      ['cytryna', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Podpraż pestki dyni na suchej patelni przez 2–3 minuty, aż zaczną pękać.',
      'Obierz marchew i zetrzyj ją na tarce o grubych oczkach, skrop sokiem z cytryny i dopraw pieprzem.',
      'Rozłóż tortille i posmaruj każdą połową hummusu, zostawiając wolny brzeg.',
      'Ułóż na hummusie liście szpinaku, marchewkę i pestki dyni.',
      'Zawiń ciasno boki i zroluj tortille, przekrój na pół i zapakuj w papier albo do pudełka.',
    ],
    photo:
      'Wheat tortilla wrap cut in half showing layers of beige hummus, bright grated carrot, fresh baby spinach and toasted pumpkin seeds',
  },
  {
    plan: 'DS-031',
    title: 'Mini tortille z kurczakiem i guacamole',
    description:
      'Zwinięte tortille z przyprawionym kurczakiem i domowym guacamole z limonką i kolendrą, pokrojone w małe ruloniki. Sprawdzą się na imprezowym stole i w pudełku do pracy.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 4,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    occasions: ['PARTY'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 4, 'szt'],
      ['filet z kurczaka', 300, 'g'],
      ['awokado', 2, 'szt'],
      ['limonka', 30, 'g'],
      ['pomidor', 120, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['kolendra', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Pokrój filet z kurczaka w cienkie paski, oprósz papryką, kminem rzymskim i połową soli.',
      'Rozgrzej olej na patelni i smaż kurczaka na średnim ogniu 6–7 minut, aż się zrumieni i będzie upieczony w środku. Odstaw do przestygnięcia.',
      'Rozgnieć miąższ awokado widelcem z sokiem z limonki i resztą soli. Dodaj drobno posiekaną cebulę, pomidor bez gniazd nasiennych pokrojony w kostkę i posiekaną kolendrę.',
      'Posmaruj tortille guacamole, ułóż paski kurczaka i ciasno zroluj.',
      'Pokrój każdy rulon na 5–6 kawałków i spnij wykałaczkami albo ułóż ciasno w pudełku.',
    ],
    photo:
      'Bite-sized tortilla pinwheels filled with green guacamole and golden spiced chicken strips, pinned with toothpicks and garnished with cilantro',
    vessel: 'board',
  },
  {
    plan: 'DS-032',
    title: 'Muffinki wytrawne z cukinią i fetą',
    description:
      'Wilgotne, wytrawne muffinki z tartą cukinią, kawałkami fety i koperkiem. Pieczesz raz, a masz przekąskę do pudełka na kilka dni — dobrze smakują też na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['jajko', 2, 'szt'],
      ['jogurt naturalny', 150, 'g'],
      ['olej rzepakowy', 60, 'ml'],
      ['cukinia', 250, 'g'],
      ['ser feta', 120, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['koperek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra–dół) i wyłóż formę na 12 muffinek papilotkami.',
      'Zetrzyj cukinię na tarce o grubych oczkach, odciśnij mocno w dłoniach z nadmiaru soku.',
      'W misce roztrzep jajka z jogurtem i olejem, dodaj cukinię, pokruszoną fetę, posiekany koperek i pieprz.',
      'Wsyp mąkę z proszkiem do pieczenia i wymieszaj łyżką tylko do połączenia składników.',
      'Nałóż ciasto do papilotek do 3/4 wysokości i piecz 22–25 minut, aż patyczek wbity w środek będzie suchy.',
      'Wystudź muffinki na kratce i przechowuj w lodówce w szczelnym pudełku do 3 dni.',
    ],
    photo:
      'Golden savory muffins with visible green zucchini shreds and white feta crumbs, one broken open to show a moist crumb flecked with dill',
    vessel: 'board',
  },
  {
    plan: 'DS-033',
    title: 'Mini frittaty z szynką i warzywami',
    description:
      'Małe frittaty pieczone w foremkach do muffinek, z szynką, czerwoną papryką, szpinakiem i odrobiną żółtego sera. Wygodne do pudełka, sycące i gotowe do jedzenia na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 3,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['jajko', 6, 'szt'],
      ['szynka', 100, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['szpinak', 50, 'g'],
      ['ser żółty', 30, 'g'],
      ['szczypiorek', 10, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C i posmaruj olejem 12 wgłębień formy do muffinek.',
      'Pokrój szynkę i paprykę w drobną kostkę, posiekaj szpinak i szczypiorek.',
      'Roztrzep jajka z pieprzem, dodaj warzywa, szynkę i starty ser żółty.',
      'Rozlej masę do foremek do 2/3 wysokości.',
      'Piecz 18–20 minut, aż frittaty urosną i będą ścięte w środku. Wystudź 5 minut przed wyjęciem z formy.',
    ],
    photo:
      'Mini egg frittatas baked in muffin shape, golden tops studded with red pepper, pink ham cubes, spinach and chives',
  },
  {
    plan: 'DS-034',
    title: 'Placuszki szpinakowe z serem',
    description:
      'Zielone placuszki ze szpinakiem, jajkiem i startym żółtym serem, smażone na złoto. Dzieci lubią je za kolor i łagodny smak, a w pudełku dobrze znoszą kilka godzin.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    features: ['LUNCHBOX'],
    ingredients: [
      ['szpinak', 150, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 80, 'g'],
      ['mleko', 100, 'ml'],
      ['ser żółty', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Sparz szpinak wrzątkiem na sitku, odciśnij i drobno posiekaj.',
      'Roztrzep jajka z mlekiem, dodaj przeciśnięty czosnek, sól i szpinak.',
      'Wsyp mąkę i starty ser żółty, wymieszaj na gęste ciasto.',
      'Rozgrzej olej na patelni i nakładaj łyżką małe placuszki. Smaż po 2–3 minuty z każdej strony na średnim ogniu.',
      'Odsącz placuszki na ręczniku papierowym i wystudź przed zapakowaniem do pudełka.',
    ],
    photo:
      'Stack of small bright green spinach pancakes with golden edges and melted cheese spots, served on a plate with a few fresh spinach leaves',
  },
  {
    plan: 'DS-035',
    title: 'Paszteciki z ciasta francuskiego z pieczarkami',
    description:
      'Chrupiące paszteciki z ciasta francuskiego z farszem z duszonych pieczarek, cebuli i majeranku. Dobre na imprezę, do barszczu i do pudełka — smakują także na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['ciasto francuskie', 275, 'g'],
      ['pieczarka', 400, 'g'],
      ['cebula', 110, 'g'],
      ['jajko', 1, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['majeranek', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Posiekaj drobno cebulę i pieczarki. Zeszklij cebulę na oleju, dodaj pieczarki i smaż 10–12 minut, aż odparuje cały płyn.',
      'Dopraw farsz solą, pieprzem, majerankiem i posiekaną natką, wystudź.',
      'Nagrzej piekarnik do 200°C. Rozwiń ciasto francuskie i przekrój wzdłuż na dwa pasy.',
      'Rozłóż farsz wzdłuż każdego pasa, zawiń ciasto w rulon i dociśnij brzeg. Pokrój rulony na kawałki szerokości 3 cm.',
      'Ułóż paszteciki na blasze z papierem, posmaruj roztrzepanym jajkiem.',
      'Piecz 18–20 minut, aż będą złote i wyraźnie wyrośnięte.',
    ],
    photo:
      'Golden flaky puff pastry rolls cut into pieces, showing a dark mushroom and onion filling with parsley, arranged on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'DS-036',
    title: 'Pierożki pieczone z soczewicą i ziemniakami',
    description:
      'Pieczone pierożki z kruchego ciasta na oleju, nadziewane purée z ziemniaków i czerwonej soczewicy z podsmażoną cebulą i majerankiem. Roślinne, sycące i wygodne do jedzenia w ręku.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 70,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'DUMPLINGS',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 250, 'g'],
      ['olej rzepakowy', 50, 'ml'],
      ['soczewica czerwona', 100, 'g'],
      ['ziemniak', 300, 'g'],
      ['cebula', 110, 'g'],
      ['mleko sojowe', 20, 'ml'],
      ['majeranek', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 3, 'g'],
    ],
    steps: [
      'Ugotuj obrane ziemniaki w osolonej wodzie do miękkości, 20 minut. W drugim garnku gotuj soczewicę w 250 ml wody 12–15 minut, aż się rozpadnie.',
      'Zeszklij posiekaną cebulę na 10 ml oleju. Rozgnieć ziemniaki z soczewicą, dodaj cebulę, majeranek, pieprz i szczyptę soli, wystudź.',
      'Zagnieć ciasto z mąki, 40 ml oleju, reszty soli i około 120 ml ciepłej wody. Odstaw pod ściereczką na 15 minut.',
      'Nagrzej piekarnik do 200°C. Rozwałkuj ciasto na grubość 2–3 mm i wykrawaj szklanką krążki.',
      'Nakładaj na krążki po łyżeczce farszu, sklej brzegi widelcem i ułóż pierożki na blasze z papierem.',
      'Posmaruj pierożki mlekiem sojowym i piecz 20–25 minut, aż będą złote.',
    ],
    photo:
      'Golden baked half-moon dumplings with fork-crimped edges, one cut open to show an orange lentil and potato filling',
  },
  {
    plan: 'DS-037',
    title: 'Batony owsiane z orzechami i daktylami',
    description:
      'Domowe batony z płatków owsianych, daktyli i dwóch rodzajów orzechów, słodzone tylko owocami i odrobiną syropu klonowego. Trzymają się w pudełku cały tydzień i smakują dzieciom.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['płatki owsiane', 200, 'g'],
      ['daktyl suszony', 150, 'g'],
      ['orzech włoski', 50, 'g'],
      ['orzech laskowy', 40, 'g'],
      ['syrop klonowy', 50, 'g'],
      ['olej kokosowy', 40, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Zalej daktyle 100 ml gorącej wody na 10 minut, potem rozgnieć je widelcem razem z wodą na gęstą pastę.',
      'Nagrzej piekarnik do 180°C i wyłóż papierem formę 20 × 20 cm.',
      'Posiekaj grubo orzechy. W misce wymieszaj płatki owsiane, orzechy i cynamon.',
      'Rozpuść olej kokosowy z syropem klonowym, wlej do miski razem z pastą daktylową i dokładnie wymieszaj.',
      'Przełóż masę do formy, mocno dociśnij łyżką i piecz 20–25 minut, aż brzegi się zrumienią.',
      'Wystudź całkowicie w formie, pokrój na 8 batonów i przechowuj w szczelnym pudełku do tygodnia.',
    ],
    photo:
      'Rectangular golden oat bars packed with chopped walnuts, hazelnuts and sticky date pieces, stacked on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'DS-038',
    title: 'Kulki proteinowe z masłem orzechowym i płatkami owsianymi',
    description:
      'Kulki bez pieczenia z płatków owsianych, masła orzechowego, białka w proszku i kakao, słodzone miodem. Szybka porcja białka do pudełka, na trening albo zamiast batonika ze sklepu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'BITES',
    features: ['LUNCHBOX'],
    ingredients: [
      ['płatki owsiane', 80, 'g'],
      ['masło orzechowe', 60, 'g'],
      ['białko w proszku', 60, 'g'],
      ['miód', 20, 'g'],
      ['kakao', 10, 'g'],
      ['mleko', 50, 'ml'],
    ],
    steps: [
      'Zmiksuj połowę płatków owsianych na drobną mąkę albo rozgnieć je w moździerzu.',
      'W misce wymieszaj zmielone i całe płatki, białko w proszku i kakao.',
      'Dodaj masło orzechowe, miód i mleko, zagnieć ręką na zwartą, lekko klejącą masę. Jeśli się kruszy, dodaj łyżkę mleka.',
      'Formuj wilgotnymi dłońmi 12 kulek wielkości orzecha włoskiego.',
      'Schłodź kulki w lodówce przez 10 minut i przechowuj w pudełku do 5 dni.',
    ],
    photo:
      'Round cocoa-brown protein balls with visible oat flakes, a few cut in half, arranged in a small pile on a plate',
  },
  {
    plan: 'DS-039',
    title: 'Drożdżowe bułeczki z serem i szynką',
    description:
      'Miękkie bułeczki z ciasta drożdżowego zawijane z szynką i żółtym serem, pieczone do złotego koloru. Idealne do szkolnego pudełka, bo smakują tak samo dobrze na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 120,
    servings: 8,
    cuisine: 'POLISH',
    dishType: 'CAKE',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['mąka pszenna', 400, 'g'],
      ['drożdże', 20, 'g'],
      ['mleko', 200, 'ml'],
      ['masło', 40, 'g'],
      ['jajko', 2, 'szt'],
      ['cukier', 10, 'g'],
      ['sól', 4, 'g'],
      ['ser żółty', 120, 'g'],
      ['szynka', 120, 'g'],
    ],
    steps: [
      'Rozkrusz drożdże do letniego mleka z cukrem i odstaw na 10 minut, aż się spienią.',
      'Wsyp do miski mąkę i sól, dodaj zaczyn, jedno jajko i roztopione masło. Wyrabiaj 8–10 minut na gładkie, elastyczne ciasto.',
      'Przykryj miskę ściereczką i odstaw w ciepłe miejsce na 1 godzinę, aż ciasto podwoi objętość.',
      'Podziel ciasto na 8 części, każdą rozpłaszcz, ułóż plaster szynki i starty ser, zawiń i uformuj bułeczkę łączeniem do spodu.',
      'Ułóż bułeczki na blasze z papierem, przykryj i odstaw na 20 minut. Nagrzej piekarnik do 190°C.',
      'Posmaruj bułeczki roztrzepanym drugim jajkiem i piecz 18–20 minut, aż będą złote.',
    ],
    photo:
      'Soft golden glossy yeast buns, one torn open to reveal pink ham and melted yellow cheese inside, on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'DS-040',
    title: 'Chia z jogurtem i musem z malin w słoiku',
    description:
      'Warstwowy deser w słoiku: pudding chia na jogurcie i mleku, a na nim świeży mus z rozgniecionych malin z miodem. Przygotujesz go wieczorem, a rano zabierasz gotowy do pracy.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'YOGURT',
    seasons: ['SUMMER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['nasiona chia', 40, 'g'],
      ['jogurt naturalny', 300, 'g'],
      ['mleko', 100, 'ml'],
      ['malina', 200, 'g'],
      ['miód', 20, 'g'],
    ],
    steps: [
      'Wymieszaj jogurt z mlekiem i połową miodu, wsyp nasiona chia i dokładnie połącz.',
      'Odstaw na 10 minut, wymieszaj ponownie, żeby nasiona się nie zbiły, i rozłóż do dwóch słoików.',
      'Rozgnieć widelcem 150 g malin z resztą miodu na gęsty mus.',
      'Wyłóż mus na pudding chia, na wierzch połóż pozostałe całe maliny.',
      'Zakręć słoiki i wstaw do lodówki co najmniej na 4 godziny albo na noc.',
    ],
    photo:
      'Glass jar with a creamy white chia yogurt pudding layer topped with vivid pink raspberry puree and whole fresh raspberries',
    vessel: 'cup',
  },
  {
    plan: 'DS-041',
    title: 'Owsianka nocna z kakao i wiśniami w słoiku',
    description:
      'Płatki owsiane namoczone przez noc w mleku z jogurtem i kakao, z kwaśnymi wiśniami na wierzchu. Smakuje jak ciasto czekoladowo-wiśniowe, a w lodówce wytrzymuje dwa, trzy dni.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    features: ['LUNCHBOX'],
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['mleko', 250, 'ml'],
      ['jogurt naturalny', 100, 'g'],
      ['kakao', 15, 'g'],
      ['wiśnia mrożona', 150, 'g'],
      ['miód', 20, 'g'],
    ],
    steps: [
      'Wymieszaj w misce mleko, jogurt, kakao i miód, aż kakao całkiem się rozpuści.',
      'Wsyp płatki owsiane, wymieszaj i przełóż do dwóch słoików.',
      'Na wierzch wyłóż wiśnie prosto z zamrażarki — rozmrożą się w lodówce i puszczą sok.',
      'Zakręć słoiki i odstaw do lodówki na noc, najmniej na 6 godzin. Przechowuj do 3 dni.',
    ],
    photo:
      'Glass jar of chocolate overnight oats with a dark cocoa layer topped with glossy red sour cherries and their juice',
    vessel: 'cup',
  },
  {
    plan: 'DS-042',
    title: 'Serek wiejski z ogórkiem, rzodkiewką i koperkiem',
    description:
      'Serek wiejski wymieszany z chrupiącym ogórkiem, rzodkiewką, koperkiem i szczypiorkiem. Wiosenna klasyka na szybko: dużo białka, świeży smak i gotowe w dziesięć minut.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'YOGURT',
    seasons: ['SPRING'],
    ingredients: [
      ['serek wiejski', 400, 'g'],
      ['ogórek', 150, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['koperek', 10, 'g'],
      ['szczypiorek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Umyj ogórek i rzodkiewki, pokrój ogórek w drobną kostkę, a rzodkiewki w cienkie plasterki.',
      'Posiekaj drobno koperek i szczypiorek.',
      'Wymieszaj serek wiejski z warzywami i ziołami, dopraw świeżo mielonym pieprzem.',
      'Przełóż do misek albo pudełek i podawaj od razu, dopóki warzywa są chrupiące.',
    ],
    photo:
      'Cottage cheese mixed with diced green cucumber, pink radish slices, chopped dill and chives, with cracked black pepper on top',
    vessel: 'bowl',
  },
  {
    plan: 'DS-043',
    title: 'Twarożek z pieczoną dynią, miodem i orzechami',
    description:
      'Kremowy twarożek z jogurtem, podany z karmelizowaną w piekarniku dynią, miodem, cynamonem i chrupiącymi orzechami włoskimi. Jesienne, rozgrzewające drugie śniadanie na słodko.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'YOGURT',
    seasons: ['AUTUMN'],
    equipment: ['OVEN'],
    ingredients: [
      ['ser twaróg półtłusty', 250, 'g'],
      ['jogurt naturalny', 60, 'g'],
      ['dynia', 300, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['cynamon', 1, 'g'],
      ['miód', 20, 'g'],
      ['orzech włoski', 30, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Obierz dynię i pokrój ją w kostkę 2 cm.',
      'Wymieszaj dynię z olejem i cynamonem, rozłóż na blasze z papierem i piecz 20–25 minut, aż zmięknie i zrumieni się na brzegach.',
      'Rozgnieć twaróg widelcem z jogurtem na gładką, kremową masę.',
      'Posiekaj orzechy i podpraż je 2 minuty na suchej patelni.',
      'Przełóż twarożek do miseczek, ułóż ciepłą albo przestudzoną dynię, polej miodem i posyp orzechami.',
    ],
    photo:
      'Creamy white quark cheese topped with caramelized orange roasted pumpkin cubes, drizzled honey and chopped toasted walnuts',
    vessel: 'bowl',
  },
  {
    plan: 'DS-044',
    title: 'Skyr z pieczonymi śliwkami i cynamonem',
    description:
      'Gęsty skyr z ciepłymi śliwkami upieczonymi z miodem i cynamonem, posypany płatkami migdałów. Jesienne śliwki robią tu za deser, a skyr daje solidną porcję białka.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'YOGURT',
    seasons: ['AUTUMN'],
    equipment: ['OVEN'],
    ingredients: [
      ['skyr naturalny', 400, 'g'],
      ['śliwka', 300, 'g'],
      ['miód', 15, 'g'],
      ['cynamon', 2, 'g'],
      ['migdał', 15, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Przekrój śliwki na połówki i usuń pestki.',
      'Ułóż śliwki w naczyniu żaroodpornym przekrojem do góry, polej miodem i posyp cynamonem.',
      'Piecz 15–18 minut, aż śliwki zmiękną i puszczą syrop.',
      'Posiekaj migdały i podpraż je krótko na suchej patelni.',
      'Rozłóż skyr do misek, ułóż śliwki z syropem i posyp migdałami.',
    ],
    photo:
      'Thick white skyr topped with glossy purple roasted plum halves in cinnamon syrup and toasted chopped almonds',
    vessel: 'bowl',
  },
  {
    plan: 'DS-045',
    title: 'Jogurt kokosowy z mango i granolą',
    description:
      'Roślinny jogurt kokosowy z soczystym mango, chrupiącą granolą i świeżą miętą, skropiony limonką. Tropikalne, lekkie drugie śniadanie bez nabiału, gotowe w pięć minut.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'YOGURT',
    ingredients: [
      ['jogurt kokosowy', 300, 'g'],
      ['mango', 200, 'g'],
      ['granola', 60, 'g'],
      ['limonka', 15, 'g'],
      ['mięta', 3, 'g'],
    ],
    steps: [
      'Obierz mango i pokrój miąższ w kostkę, skrop sokiem z limonki.',
      'Rozłóż jogurt kokosowy do dwóch miseczek albo słoików.',
      'Ułóż na jogurcie mango, a granolę posyp tuż przed jedzeniem, żeby została chrupiąca.',
      'Udekoruj listkami mięty.',
    ],
    photo:
      'White coconut yogurt topped with bright yellow mango cubes, crunchy golden granola clusters and fresh mint leaves',
    vessel: 'bowl',
  },
  {
    plan: 'DS-046',
    title: 'Sałatka owocowa z miętą i limonką',
    description:
      'Letnia sałatka z arbuza, truskawek, brzoskwiń i borówek, skropiona limonką i syropem klonowym, z posiekaną miętą. Orzeźwia w upał i nie obciąża przed obiadem.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    seasons: ['SUMMER'],
    ingredients: [
      ['arbuz', 300, 'g'],
      ['truskawka', 200, 'g'],
      ['brzoskwinia', 200, 'g'],
      ['borówka', 100, 'g'],
      ['limonka', 30, 'g'],
      ['syrop klonowy', 10, 'g'],
      ['mięta', 5, 'g'],
    ],
    steps: [
      'Pokrój arbuz w kostkę, usuwając pestki. Truskawki przekrój na ćwiartki, brzoskwinie pokrój w cząstki.',
      'Wymieszaj w misce owoce razem z borówkami.',
      'Zetrzyj skórkę z limonki, wyciśnij sok i połącz z syropem klonowym.',
      'Polej owoce sosem, dodaj posiekaną miętę i delikatnie wymieszaj. Schłódź 10 minut przed podaniem.',
    ],
    photo:
      'Colorful fruit salad of red watermelon cubes, strawberries, peach wedges and blueberries with fresh mint and lime zest',
    vessel: 'bowl',
  },
  {
    plan: 'DS-047',
    title: 'Zimowa sałatka owocowa z pomarańczą, granatem i kiwi',
    description:
      'Zimowa sałatka z soczystej pomarańczy, kiwi i jabłka, obsypana rubinowymi pestkami granatu i szczyptą cynamonu. Porcja witaminy C w sezonie, gdy letnich owoców brak.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    seasons: ['WINTER'],
    ingredients: [
      ['pomarańcza', 360, 'g'],
      ['kiwi', 210, 'g'],
      ['jabłko', 150, 'g'],
      ['granat', 150, 'g'],
      ['syrop klonowy', 10, 'g'],
      ['cynamon', 1, 'g'],
      ['mięta', 3, 'g'],
    ],
    steps: [
      'Obierz pomarańcze ze skórki i białej błonki, pokrój w plastry, a potem na ćwiartki. Zbierz wypływający sok.',
      'Obierz kiwi i pokrój w półplasterki, jabłko pokrój w cienkie cząstki.',
      'Wyłuskaj pestki z granatu, uderzając łyżką w przekrojoną połówkę nad miską.',
      'Wymieszaj sok z pomarańczy z syropem klonowym i cynamonem, polej owoce i posyp granatem oraz listkami mięty.',
    ],
    photo:
      'Winter fruit salad with orange segments, green kiwi half-moons, apple slices and ruby pomegranate seeds dusted with cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'DS-048',
    title: 'Twarożek z truskawkami i bazylią',
    description:
      'Chudy twarożek utarty z jogurtem i miodem, podany z truskawkami i świeżą bazylią. Nieoczywiste, a bardzo letnie połączenie, które daje dużo białka przy niewielu kaloriach.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'YOGURT',
    seasons: ['SUMMER'],
    ingredients: [
      ['ser twaróg chudy', 250, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['truskawka', 250, 'g'],
      ['miód', 15, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Rozgnieć twaróg widelcem z jogurtem i połową miodu na kremową masę.',
      'Umyj truskawki, usuń szypułki i pokrój je w ćwiartki.',
      'Porwij listki bazylii i wymieszaj z truskawkami oraz resztą miodu.',
      'Przełóż twarożek do miseczek i wyłóż na wierzch truskawki z bazylią.',
    ],
    photo:
      'Creamy white quark topped with quartered red strawberries glazed with honey and torn fresh green basil leaves',
    vessel: 'bowl',
  },
  {
    plan: 'DS-049',
    title: 'Jajka na twardo z warzywami i sosem jogurtowym',
    description:
      'Jajka na twardo z kolorowymi warzywami do chrupania i gęstym sosem z jogurtu greckiego z czosnkiem i koperkiem. Lekki, białkowy zestaw, który bez problemu przeżyje dzień w pudełku.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['jajko', 4, 'szt'],
      ['jogurt grecki', 100, 'g'],
      ['ogórek', 150, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['rzodkiewka', 80, 'g'],
      ['koperek', 5, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Włóż jajka do wrzącej wody i gotuj 9 minut, potem przełóż do zimnej wody na 5 minut i obierz.',
      'Wymieszaj jogurt grecki z przeciśniętym czosnkiem, posiekanym koperkiem, solą i pieprzem.',
      'Pokrój ogórek i paprykę w słupki, rzodkiewki przekrój na pół, pomidorki zostaw w całości.',
      'Przekrój jajka na połówki i ułóż w pudełku z warzywami, a sos przełóż do osobnego pojemnika.',
    ],
    photo:
      'Halved hard-boiled eggs with bright yolks next to cucumber and red pepper sticks, cherry tomatoes, radishes and a small bowl of dill yogurt dip',
  },
  {
    plan: 'DS-050',
    title: 'Tofu pieczone z sosem sojowym i sezamem',
    description:
      'Kostki tofu w glazurze z sosu sojowego, czosnku, imbiru i syropu klonowego, upieczone na chrupko razem z brokułem i posypane sezamem. Roślinne białko do pudełka, dobre na ciepło i na zimno.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['tofu', 400, 'g'],
      ['brokuł', 200, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['syrop klonowy', 10, 'g'],
      ['olej sezamowy', 10, 'ml'],
      ['mąka ziemniaczana', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['imbir', 10, 'g'],
      ['sezam', 10, 'g'],
    ],
    steps: [
      'Odsącz tofu, owiń ręcznikiem papierowym i dociśnij na 10 minut, a potem pokrój w kostkę 2 cm. Nagrzej piekarnik do 210°C.',
      'Obtocz kostki tofu w mące ziemniaczanej i rozłóż na blasze z papierem razem z różyczkami brokuła skropionymi połową oleju sezamowego.',
      'Piecz 20 minut, w połowie przewracając tofu na drugą stronę.',
      'Wymieszaj sos sojowy, syrop klonowy, resztę oleju, przeciśnięty czosnek i starty imbir.',
      'Polej tofu i brokuł sosem, wymieszaj na blasze i piecz jeszcze 5 minut, aż glazura się zetnie.',
      'Posyp sezamem i podawaj od razu albo przełóż do pudełek po przestudzeniu.',
    ],
    photo:
      'Crispy golden tofu cubes in a glossy soy glaze with roasted broccoli florets, sprinkled with white sesame seeds',
  },
  {
    plan: 'DS-051',
    title: 'Roladki z szynki z twarożkiem i ogórkiem',
    description:
      'Plastry szynki zwinięte z twarożkiem ze szczypiorkiem i słupkiem świeżego ogórka. Przekąska na dziesięć minut, bez pieczywa, z dużą porcją białka i prawie bez węglowodanów.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BITES',
    ingredients: [
      ['szynka', 120, 'g'],
      ['ser twaróg półtłusty', 200, 'g'],
      ['ogórek', 120, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgnieć twaróg widelcem, wymieszaj z posiekanym szczypiorkiem i pieprzem.',
      'Pokrój ogórek wzdłuż w cienkie słupki długości plastra szynki.',
      'Rozłóż plastry szynki, posmaruj każdy twarożkiem i połóż na brzegu słupek ogórka.',
      'Zwiń ciasno roladki i ułóż łączeniem do dołu na talerzu albo w pudełku.',
    ],
    photo:
      'Pink ham roll-ups filled with white herbed quark and crisp cucumber sticks, arranged in a row and sprinkled with chives',
  },
  {
    plan: 'DS-052',
    title: 'Hummus z pieczonej dyni z warzywami',
    description:
      'Pomarańczowy hummus z pieczonej dyni, ciecierzycy i tahini z kminem rzymskim, podany ze słupkami marchewki, ogórka i papryki. Jesienna wersja klasyki, idealna do pudełka.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DIP',
    seasons: ['AUTUMN'],
    equipment: ['OVEN', 'BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['dynia', 300, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['tahini', 30, 'g'],
      ['cytryna', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['sól', 1, 'g'],
      ['marchew', 150, 'g'],
      ['ogórek', 150, 'g'],
      ['papryka czerwona', 150, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Obierz dynię, pokrój w kostkę i piecz na blasze z papierem 25 minut, aż będzie miękka.',
      'Odsącz i przepłucz ciecierzycę.',
      'Zmiksuj blenderem dynię, ciecierzycę, tahini, sok z cytryny, czosnek, kmin rzymski, sól i oliwę na gładką pastę. Jeśli jest za gęsta, dodaj 2–3 łyżki zimnej wody.',
      'Pokrój marchew, ogórek i paprykę w słupki.',
      'Przełóż hummus do pudełek i zapakuj obok warzywa do maczania.',
    ],
    photo:
      'Bright orange pumpkin hummus swirled with olive oil and cumin, surrounded by carrot, cucumber and red pepper sticks',
    vessel: 'bowl',
  },
  {
    plan: 'DS-053',
    title: 'Kurczak tandoori z sosem raita na zimno',
    description:
      'Kurczak marynowany w jogurcie z garam masalą, kurkumą i czosnkiem, upieczony w piekarniku i podany na zimno z orzeźwiającą raitą z ogórka i mięty. Białkowy lunch do pudełka po indyjsku.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['jogurt naturalny', 200, 'g'],
      ['garam masala', 4, 'g'],
      ['kurkuma', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['cytryna', 20, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ogórek', 150, 'g'],
      ['mięta', 5, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Wymieszaj połowę jogurtu z garam masalą, kurkumą, papryką, przeciśniętym czosnkiem, startym imbirem, sokiem z cytryny, olejem i połową soli.',
      'Pokrój kurczaka w duże kawałki, obtocz w marynacie i odstaw do lodówki na co najmniej 30 minut.',
      'Nagrzej piekarnik do 220°C. Rozłóż kurczaka na blasze z papierem i piecz 18–20 minut, aż się zrumieni na brzegach.',
      'Zetrzyj ogórek, odciśnij z soku i wymieszaj z resztą jogurtu, posiekaną miętą i szczyptą soli.',
      'Wystudź kurczaka i zapakuj do pudełka z raitą w osobnym pojemniku.',
    ],
    photo:
      'Orange-red tandoori chicken pieces with charred edges next to a bowl of creamy cucumber mint raita garnished with mint leaves',
  },
  {
    plan: 'DS-054',
    title: 'Koreczki z mozzarellą, pomidorkami i bazylią',
    description:
      'Klasyczne włoskie caprese na wykałaczkach: kulki mozzarelli, pomidorki koktajlowe i listki bazylii skropione oliwą i octem balsamicznym. Kolorowe, szybkie i zawsze znikają z imprezowego stołu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 4,
    cuisine: 'ITALIAN',
    dishType: 'BITES',
    occasions: ['PARTY'],
    ingredients: [
      ['mozzarella', 250, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['bazylia', 10, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['ocet balsamiczny', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Odsącz mozzarellę z zalewy. Jeśli masz dużą kulkę, pokrój ją w kostkę wielkości pomidorka.',
      'Umyj pomidorki koktajlowe i osusz je, oberwij listki bazylii.',
      'Nabijaj na wykałaczki kolejno pomidorek, listek bazylii i kawałek mozzarelli.',
      'Ułóż koreczki na półmisku, skrop oliwą i octem balsamicznym, oprósz świeżo mielonym pieprzem.',
    ],
    photo:
      'Caprese skewers with red cherry tomatoes, white mozzarella balls and green basil leaves drizzled with olive oil and balsamic glaze on a board',
    vessel: 'board',
  },
  {
    plan: 'DS-055',
    title: 'Sałatka jajeczna z awokado i szczypiorkiem',
    description:
      'Posiekane jajka na twardo połączone z kremowym awokado, jogurtem greckim, musztardą i dużą ilością szczypiorku. Pożywna, sycąca sałatka bez majonezu, którą można jeść łyżką albo z sałatą.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    ingredients: [
      ['jajko', 6, 'szt'],
      ['awokado', 1, 'szt'],
      ['jogurt grecki', 80, 'g'],
      ['musztarda', 5, 'g'],
      ['cytryna', 15, 'g'],
      ['szczypiorek', 15, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj jajka na twardo przez 9 minut, schłodź w zimnej wodzie i obierz.',
      'Rozgnieć połowę awokado z jogurtem, musztardą, sokiem z cytryny, solą i pieprzem na gładki sos.',
      'Pokrój jajka i drugą połowę awokado w kostkę, posiekaj szczypiorek.',
      'Delikatnie wymieszaj jajka i awokado z sosem oraz szczypiorkiem, podawaj od razu albo schłodzone.',
    ],
    photo:
      'Chunky egg salad with chopped boiled eggs, green avocado cubes and plenty of fresh chives in a creamy pale green dressing',
    vessel: 'bowl',
  },
  {
    plan: 'DS-056',
    title: 'Kotleciki z indyka i cukinii na zimno z dipem',
    description:
      'Soczyste kotleciki z mielonego indyka z tartą cukinią i koperkiem, podawane na zimno z czosnkowym dipem z jogurtu greckiego. Porcja na kilka dni, która w lodówce nie traci smaku.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['indyk mielony', 500, 'g'],
      ['cukinia', 250, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 15, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['jogurt grecki', 200, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zetrzyj cukinię na tarce o drobnych oczkach, posól szczyptą soli, odstaw na 5 minut i mocno odciśnij.',
      'Wymieszaj indyka z cukinią, jajkiem, bułką tartą, jednym przeciśniętym ząbkiem czosnku, połową koperku, resztą soli i pieprzem.',
      'Formuj wilgotnymi dłońmi małe kotleciki wielkości orzecha włoskiego, lekko je spłaszczając.',
      'Smaż na rozgrzanym oleju na średnim ogniu po 4 minuty z każdej strony, aż będą złote i upieczone w środku.',
      'Wymieszaj jogurt grecki z drugim ząbkiem czosnku i resztą posiekanego koperku.',
      'Wystudź kotleciki, przechowuj w lodówce do 3 dni i podawaj z dipem.',
    ],
    photo:
      'Small golden turkey and zucchini patties with green herb flecks next to a bowl of white garlic dill yogurt dip',
  },
  {
    plan: 'DS-057',
    title: 'Sałatka makaronowa z szynką i groszkiem',
    description:
      'Domowa sałatka z makaronu świderki, szynki, groszku, kukurydzy i jajek w sosie z majonezu i jogurtu. Imprezowa klasyka, która dobrze znosi noc w lodówce i drogę w pudełku.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'SALAD',
    occasions: ['PARTY'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron świder', 200, 'g'],
      ['szynka', 150, 'g'],
      ['groszek mrożony', 200, 'g'],
      ['kukurydza z puszki', 150, 'g'],
      ['ogórek konserwowy', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['majonez', 60, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron al dente według instrukcji na opakowaniu, przelej zimną wodą i odsącz.',
      'Ugotuj jajka na twardo przez 9 minut, schłodź, obierz i pokrój w kostkę.',
      'Wrzuć groszek do wrzątku na 3 minuty i odsącz. Pokrój szynkę i ogórki konserwowe w kostkę, odsącz kukurydzę.',
      'Wymieszaj majonez z jogurtem, pieprzem i posiekanym szczypiorkiem.',
      'Połącz w dużej misce makaron, szynkę, jajka, warzywa i sos. Schłódź 20 minut przed podaniem.',
    ],
    photo:
      'Creamy pasta salad with spiral pasta, pink ham cubes, green peas, yellow corn, chopped egg and chives',
    vessel: 'bowl',
  },
];
