/**
 * Katalog 1000 — część KO-a: kolacje KO-001 … KO-029 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'KO-001',
    title: 'Sałatka z kurczakiem, grejpfrutem i awokado',
    description:
      'Soczysty kurczak z patelni na roszponce z cząstkami grejpfruta, kremowym awokado i czerwoną cebulą, skropiony miodowym winegretem. Świeża, zimowa kolacja, która syci, a nie obciąża.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    seasons: ['WINTER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 250, 'g'],
      ['grejpfrut', 300, 'g'],
      ['awokado', 1, 'szt'],
      ['roszponka', 60, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['miód', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filet z kurczaka przekrój wzdłuż na dwa cieńsze kotlety, dopraw solą i pieprzem.',
      'Rozgrzej patelnię z połową oliwy i smaż kurczaka po 5 minut z każdej strony, aż będzie złoty i upieczony w środku. Odstaw na 5 minut i pokrój w paski.',
      'Grejpfruta obierz na żywo nożem i wykrój cząstki bez błonek, zbierając sok do miseczki.',
      'Do soku z grejpfruta dodaj resztę oliwy, miód i szczyptę pieprzu, wymieszaj na winegret.',
      'Awokado pokrój w plastry, cebulę w cienkie piórka. Na roszponce ułóż grejpfruta, awokado, cebulę i kurczaka, polej winegretem.',
    ],
    photo:
      'Plate of lamb lettuce topped with sliced golden chicken breast, pink grapefruit segments, avocado slices and thin red onion rings',
  },
  {
    plan: 'KO-002',
    title: 'Tosty z hummusem, jajkiem i rukolą',
    description:
      'Chrupiące tosty z pełnoziarnistego chleba grubo posmarowane hummusem, z jajkiem na miękko, pomidorem i rukolą. Szybka, sycąca kolacja z tego, co zwykle jest w lodówce.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    ingredients: [
      ['chleb pełnoziarnisty', 160, 'g'],
      ['hummus', 80, 'g'],
      ['jajko', 4, 'szt'],
      ['rukola', 40, 'g'],
      ['pomidor', 150, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['papryka słodka mielona', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zagotuj wodę w garnku, włóż jajka łyżką i gotuj 6 minut, potem przełóż je do zimnej wody i obierz.',
      'W tym czasie opiecz kromki chleba w tosterze albo na suchej patelni po 2 minuty z każdej strony.',
      'Posmaruj tosty grubo hummusem i ułóż na nich plasterki pomidora oraz garść rukoli.',
      'Przekrój jajka na pół, połóż na tostach, skrop oliwą i posyp słodką papryką i pieprzem.',
    ],
    photo:
      'Toasted wholegrain bread slices spread with hummus, topped with tomato slices, arugula and halved soft-boiled eggs with jammy yolks dusted with paprika',
    vessel: 'board',
  },
  {
    plan: 'KO-003',
    title: 'Zupa krem z pomidorów z bazylią',
    description:
      'Aksamitny krem z pomidorów z puszki, duszonych z cebulą, czosnkiem i marchewką, zmiksowany z odrobiną mleka kokosowego i świeżą bazylią. Rozgrzewająca, lekka kolacja na cały rok.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    equipment: ['BLENDER'],
    ingredients: [
      ['pomidor krojony z puszki', 800, 'g'],
      ['cebula', 110, 'g'],
      ['czosnek', 2, 'szt'],
      ['marchew', 75, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['mleko kokosowe z puszki', 60, 'ml'],
      ['bazylia', 15, 'g'],
      ['cukier', 5, 'g'],
      ['pestki dyni', 20, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, marchew zetrzyj na tarce o grubych oczkach.',
      'Rozgrzej oliwę w garnku i duś cebulę z marchewką 6 minut, dodaj czosnek i smaż jeszcze minutę.',
      'Wlej pomidory z puszki i 300 ml wody, dodaj cukier, sól i pieprz. Gotuj pod przykryciem 20 minut.',
      'Dodaj większość liści bazylii i mleko kokosowe, zmiksuj blenderem na gładki krem.',
      'Pestki dyni podpraż na suchej patelni 2 minuty. Podawaj zupę posypaną pestkami i resztą bazylii.',
    ],
    photo:
      'Smooth bright red tomato cream soup with a swirl of coconut milk, fresh basil leaves and toasted pumpkin seeds',
    vessel: 'bowl',
  },
  {
    plan: 'KO-004',
    title: 'Sałatka z pieczonym łososiem, ogórkiem i koperkiem',
    description:
      'Kawałki pieczonego łososia na chrupiącej sałacie rzymskiej z ogórkiem, rzodkiewką i koperkowym sosem jogurtowym. Lekka, świeża kolacja pełna dobrego tłuszczu z ryby.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    equipment: ['OVEN'],
    ingredients: [
      ['łosoś', 250, 'g'],
      ['ogórek', 250, 'g'],
      ['sałata rzymska', 100, 'g'],
      ['rzodkiewka', 80, 'g'],
      ['koperek', 10, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['cytryna', 30, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Łososia połóż na blasze z papierem, skrop oliwą, dopraw solą i pieprzem i piecz 15 minut.',
      'W tym czasie porwij sałatę, ogórek pokrój w półplasterki, a rzodkiewki w cienkie plasterki.',
      'Wymieszaj jogurt z posiekanym koperkiem, sokiem z cytryny i szczyptą pieprzu.',
      'Upieczonego łososia podziel widelcem na duże kawałki.',
      'Ułóż warzywa na talerzach, na wierzch połóż łososia i polej sosem koperkowym.',
    ],
    photo:
      'Crisp romaine salad with cucumber half-moons, thin radish slices, flaked pink roasted salmon and creamy dill yogurt dressing',
  },
  {
    plan: 'KO-005',
    title: 'Wrap z indykiem, fasolą i salsą na ciepło',
    description:
      'Pełnoziarnista tortilla zwinięta z mielonym indykiem duszonym z czerwoną fasolą, papryką i kminem, z pomidorową salsą i świeżym pomidorem. Szybka meksykańska kolacja, która daje dużo białka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['tortilla pełnoziarnista', 120, 'g'],
      ['indyk mielony', 250, 'g'],
      ['fasola czerwona z puszki', 120, 'g'],
      ['salsa pomidorowa', 50, 'g'],
      ['pomidor', 120, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['cebula', 50, 'g'],
      ['sałata rzymska', 40, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
    ],
    steps: [
      'Cebulę posiekaj, paprykę pokrój w kostkę, pomidora w plasterki, fasolę odcedź i przepłucz.',
      'Rozgrzej olej na patelni, smaż cebulę 3 minuty, dodaj indyka i smaż 6 minut, rozbijając mięso łopatką.',
      'Dodaj paprykę, kmin i wędzoną paprykę, smaż 3 minuty, potem wmieszaj fasolę i połowę salsy i podgrzewaj jeszcze 3 minuty.',
      'Tortille podgrzej na suchej patelni po 30 sekund z każdej strony.',
      'Na każdą tortillę połóż sałatę, plasterki pomidora, farsz z indyka i resztę salsy, zawiń ciasno i przekrój na pół.',
    ],
    photo:
      'Two halved wholegrain tortilla wraps filled with spiced ground turkey, red kidney beans, diced pepper, lettuce and tomato salsa',
  },
  {
    plan: 'KO-006',
    title: 'Zupa krem z cukinii z serkiem',
    description:
      'Delikatny, jasnozielony krem z letniej cukinii i ziemniaka, zmiksowany z kremowym serkiem i koperkiem, podany z prażonymi pestkami dyni. Lekka kolacja na ciepłe wieczory.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SUMMER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['cukinia', 700, 'g'],
      ['ziemniak', 200, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 10, 'g'],
      ['serek kremowy', 60, 'g'],
      ['koperek', 10, 'g'],
      ['pestki dyni', 20, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, ziemniaka obierz i pokrój w kostkę, cukinię pokrój w półplasterki.',
      'Rozpuść masło w garnku i zeszklij cebulę przez 4 minuty, dodaj czosnek i smaż minutę.',
      'Dodaj ziemniaka i cukinię, wlej 600 ml wody, dopraw solą i gotuj 15 minut, aż ziemniak zmięknie.',
      'Zdejmij garnek z ognia, dodaj serek i koperek i zmiksuj blenderem na gładki krem. Dopraw pieprzem.',
      'Pestki dyni podpraż na suchej patelni i posyp nimi zupę przed podaniem.',
    ],
    photo:
      'Pale green zucchini cream soup with a swirl of cream cheese, chopped dill and toasted pumpkin seeds',
    vessel: 'bowl',
  },
  {
    plan: 'KO-007',
    title: 'Sałatka caprese z pełnoziarnistą grzanką',
    description:
      'Dojrzałe pomidory i mozzarella przełożone liśćmi bazylii, skropione oliwą i octem balsamicznym, z chrupiącą grzanką nacieraną czosnkiem. Włoska klasyka na letnią kolację w kwadrans.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SALAD',
    seasons: ['SUMMER'],
    ingredients: [
      ['pomidor', 400, 'g'],
      ['mozzarella', 200, 'g'],
      ['bazylia', 15, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ocet balsamiczny', 10, 'ml'],
      ['chleb pełnoziarnisty', 120, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pomidory i mozzarellę pokrój w plastry grubości około 1 cm.',
      'Układaj je na talerzach na zmianę, przekładając liśćmi bazylii. Posyp solą i pieprzem.',
      'Kromki chleba opiecz na suchej patelni po 2 minuty z każdej strony, natrzyj przekrojonym czosnkiem i skrop 5 ml oliwy.',
      'Resztę oliwy wymieszaj z octem balsamicznym i polej sałatkę. Podawaj z ciepłą grzanką.',
    ],
    photo:
      'Alternating slices of ripe red tomato and white mozzarella with fresh basil leaves, drizzled with olive oil and balsamic, with a toasted wholegrain bread slice',
  },
  {
    plan: 'KO-008',
    title: 'Kasza jaglana z warzywami z patelni i jajkiem',
    description:
      'Puszysta kasza jaglana wymieszana z podsmażoną cukinią, papryką i pomidorkami, podana z jajkami sadzonymi i szczypiorkiem. Kolorowa kolacja z jednej patelni, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    ingredients: [
      ['kasza jaglana', 100, 'g'],
      ['jajko', 4, 'szt'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['szczypiorek', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz gorącą wodą, zalej 250 ml wrzątku, posól i gotuj pod przykryciem 15 minut.',
      'W tym czasie pokrój cebulę w piórka, cukinię i paprykę w kostkę, a pomidorki przekrój na pół.',
      'Rozgrzej 10 ml oliwy na dużej patelni, smaż cebulę, cukinię i paprykę 7 minut. Dodaj pomidorki i słodką paprykę, smaż jeszcze 2 minuty.',
      'Wmieszaj ugotowaną kaszę do warzyw i dopraw pieprzem.',
      'Na drugiej patelni z resztą oliwy usmaż jajka sadzone przez 3–4 minuty. Podawaj kaszę z jajkami, posypaną szczypiorkiem.',
    ],
    photo:
      'Golden millet mixed with sauteed zucchini, red pepper and halved cherry tomatoes, topped with two sunny-side-up eggs and chopped chives',
  },
  {
    plan: 'KO-009',
    title: 'Kotlety z komosy ryżowej i warzyw',
    description:
      'Chrupiące z zewnątrz kotleciki z komosy ryżowej, startej marchewki i cukinii, związane mąką z ciecierzycy i doprawione kminem. Wegańska, lekka kolacja, dobra też na zimno do pudełka.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['komosa ryżowa', 100, 'g'],
      ['marchew', 100, 'g'],
      ['cukinia', 150, 'g'],
      ['cebula', 60, 'g'],
      ['mąka z ciecierzycy', 40, 'g'],
      ['czosnek', 2, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['rukola', 40, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Komosę przepłucz na sitku, zalej 200 ml wody, posól i gotuj pod przykryciem 15 minut. Odstaw do przestygnięcia.',
      'Marchew i cukinię zetrzyj na tarce o grubych oczkach, cukinię mocno odciśnij z soku. Cebulę, czosnek i natkę posiekaj drobno.',
      'Połącz komosę z warzywami, mąką z ciecierzycy, kminem i wędzoną papryką, wyrabiaj ręką 1 minutę i odstaw na 10 minut.',
      'Uformuj mokrymi dłońmi 8 płaskich kotlecików.',
      'Rozgrzej olej na patelni i smaż kotlety na średnim ogniu po 4 minuty z każdej strony, aż się zrumienią.',
      'Podawaj z rukolą i przekrojonymi pomidorkami koktajlowymi.',
    ],
    photo:
      'Golden crispy quinoa and vegetable patties with visible grated carrot, served with fresh arugula and halved cherry tomatoes',
  },
  {
    plan: 'KO-010',
    title: 'Kurczak z warzywami z patelni z sosem jogurtowym',
    description:
      'Kawałki kurczaka smażone z brokułem, cukinią i papryką, podane z chłodnym sosem jogurtowym z czosnkiem i koperkiem. Szybka, lekka kolacja z dużą porcją białka i warzyw.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['brokuł', 200, 'g'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę, dopraw słodką papryką, połową soli i pieprzem.',
      'Brokuł podziel na małe różyczki, cukinię i paprykę pokrój w kostkę, a cebulę w piórka.',
      'Rozgrzej oliwę na dużej patelni i smaż kurczaka 6 minut, aż się zrumieni. Zdejmij go na talerz.',
      'Na tę samą patelnię wrzuć warzywa, posól i smaż 6–7 minut, mieszając, aż będą chrupiąco-miękkie. Dodaj kurczaka i podgrzej razem 2 minuty.',
      'Jogurt wymieszaj z przeciśniętym czosnkiem i posiekanym koperkiem. Podawaj kurczaka z warzywami polanego sosem.',
    ],
    photo:
      'Golden chicken cubes with bright green broccoli florets, zucchini and red pepper, with a dollop of white garlic dill yogurt sauce',
  },
  {
    plan: 'KO-011',
    title: 'Placki dyniowe na słono z jogurtem',
    description:
      'Pomarańczowe placki z tartej dyni z dymką, czosnkiem i gałką muszkatołową, usmażone na złoto i podane z gęstym jogurtem. Jesienna kolacja, którą lubią także dzieci.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PANCAKES',
    seasons: ['AUTUMN'],
    ingredients: [
      ['dynia', 400, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 80, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['gałka muszkatołowa', 1, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['jogurt grecki', 150, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dynię obierz i zetrzyj na tarce o grubych oczkach, lekko odciśnij z soku.',
      'Dymkę posiekaj, odłóż łyżkę szczypioru do posypania. Resztę dodaj do dyni razem z jajkami, przeciśniętym czosnkiem, gałką, solą i pieprzem.',
      'Wsyp mąkę i wymieszaj na gęste ciasto.',
      'Rozgrzej olej na patelni i nakładaj po łyżce ciasta. Smaż placki na średnim ogniu po 3–4 minuty z każdej strony, aż będą złote.',
      'Podawaj z jogurtem greckim posypanym odłożoną dymką.',
    ],
    photo:
      'Stack of golden orange savory pumpkin fritters with a dollop of thick Greek yogurt and chopped spring onion greens',
  },
  {
    plan: 'KO-012',
    title: 'Zupa krem z selera z gruszką',
    description:
      'Kremowa zupa z selera korzeniowego ugotowanego z gruszką i ziemniakiem, zmiksowana z mlekiem kokosowym i doprawiona gałką. Delikatnie słodka, rozgrzewająca kolacja na zimowy wieczór.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    seasons: ['WINTER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['seler korzeniowy', 500, 'g'],
      ['gruszka', 250, 'g'],
      ['ziemniak', 150, 'g'],
      ['cebula', 100, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['mleko kokosowe z puszki', 60, 'ml'],
      ['gałka muszkatołowa', 1, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['pestki dyni', 15, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Seler i ziemniaka obierz i pokrój w kostkę. Gruszkę obierz, usuń gniazdo nasienne i pokrój, odkładając kilka cienkich plasterków do dekoracji. Cebulę posiekaj.',
      'Rozgrzej oliwę w garnku i zeszklij cebulę przez 4 minuty.',
      'Dodaj seler, ziemniaka, gruszkę i tymianek, wlej 700 ml wody, posól i gotuj pod przykryciem 25 minut, aż seler będzie miękki.',
      'Wlej mleko kokosowe, dodaj gałkę i pieprz, zmiksuj blenderem na gładki krem.',
      'Podawaj z plasterkami gruszki i pestkami dyni podprażonymi na suchej patelni.',
    ],
    photo:
      'Ivory celeriac and pear cream soup garnished with thin fresh pear slices, toasted pumpkin seeds and a pinch of thyme',
    vessel: 'bowl',
  },
  {
    plan: 'KO-013',
    title: 'Zapiekane tortille z fasolą i serem',
    description:
      'Kukurydziane tortille zwinięte z czarną fasolą, kukurydzą i papryką, polane sosem pomidorowym i zapieczone pod ciągnącą się mozzarellą. Meksykańska kolacja w pół godziny, która znika z blachy w kilka minut.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['tortilla kukurydziana', 6, 'szt'],
      ['fasola czarna z puszki', 200, 'g'],
      ['kukurydza z puszki', 80, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula', 80, 'g'],
      ['passata pomidorowa', 200, 'ml'],
      ['oregano', 1, 'g'],
      ['mozzarella tarta', 100, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Cebulę posiekaj, paprykę pokrój w kostkę, fasolę i kukurydzę odcedź.',
      'Rozgrzej olej na patelni, smaż cebulę i paprykę 5 minut, dodaj kmin i wędzoną paprykę, a potem fasolę i kukurydzę. Podgrzewaj 3 minuty, lekko rozgniatając część fasoli.',
      'Rozłóż farsz na tortille, zwiń je i ułóż ciasno w naczyniu żaroodpornym łączeniem do dołu.',
      'Passatę wymieszaj z oregano, polej nią tortille i posyp mozzarellą. Zapiekaj 12–15 minut, aż ser się roztopi i zrumieni.',
      'Posyp posiekaną kolendrą i podawaj od razu.',
    ],
    photo:
      'Baking dish of rolled corn tortillas filled with black beans and corn, covered in tomato sauce and bubbling golden melted mozzarella, sprinkled with cilantro',
  },
  {
    plan: 'KO-014',
    title: 'Zupa krem z marchewki z imbirem',
    description:
      'Słodka marchewka ugotowana z ziemniakiem, świeżym imbirem i szczyptą kurkumy, zmiksowana z mlekiem kokosowym na aksamitny krem. Rozgrzewająca, lekka kolacja bez nabiału.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    equipment: ['BLENDER'],
    ingredients: [
      ['marchew', 600, 'g'],
      ['ziemniak', 150, 'g'],
      ['cebula', 100, 'g'],
      ['imbir', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['mleko kokosowe z puszki', 80, 'ml'],
      ['kurkuma', 1, 'g'],
      ['słonecznik łuszczony', 20, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Marchew i ziemniaka obierz i pokrój w plastry, cebulę posiekaj, imbir i czosnek zetrzyj na drobnej tarce.',
      'Rozgrzej olej w garnku, zeszklij cebulę przez 4 minuty, dodaj imbir, czosnek i kurkumę i smaż 1 minutę.',
      'Dodaj marchew i ziemniaka, wlej 700 ml wody, posól i gotuj pod przykryciem 20 minut, aż marchew będzie miękka.',
      'Wlej mleko kokosowe i zmiksuj blenderem na gładki krem.',
      'Słonecznik podpraż na suchej patelni. Podawaj zupę posypaną słonecznikiem i posiekaną natką.',
    ],
    photo:
      'Vivid orange carrot ginger cream soup with a swirl of coconut milk, toasted sunflower seeds and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'KO-015',
    title: 'Pieczony kurczak z salsą z mango i ryżem',
    description:
      'Kurczak pieczony w wędzonej papryce i kminie, podany z ryżem basmati i świeżą salsą z mango, limonki, chili i kolendry. Soczysta, kolorowa kolacja po meksykańsku z dużą porcją białka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['ryż basmati', 100, 'g'],
      ['mango', 250, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['limonka', 60, 'g'],
      ['papryczka chili', 15, 'g'],
      ['kolendra', 10, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Kurczaka natrzyj oliwą, wędzoną papryką, kminem, przeciśniętym czosnkiem i połową soli.',
      'Ułóż filety w naczyniu żaroodpornym i piecz 20–22 minuty. Po wyjęciu odstaw na 5 minut i pokrój w plastry.',
      'W tym czasie ugotuj ryż w osolonej wodzie według instrukcji na opakowaniu, około 12 minut.',
      'Mango obierz i pokrój w drobną kostkę, cebulę i chili posiekaj drobno. Wymieszaj z sokiem z limonki i posiekaną kolendrą.',
      'Podawaj kurczaka na ryżu, z salsą z mango na wierzchu.',
    ],
    photo:
      'Sliced paprika-roasted chicken breast on fluffy basmati rice topped with bright mango salsa with red onion, chili and cilantro, lime wedge on the side',
  },
  {
    plan: 'KO-016',
    title: 'Kurczak z warzywami na parze z sosem sojowym',
    description:
      'Delikatny kurczak, brokuł, marchewka i fasolka ugotowane na parze, polane sosem sojowym z imbirem, czosnkiem i olejem sezamowym. Lekka kolacja z odrobiną jaśminowego ryżu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['brokuł', 250, 'g'],
      ['marchew', 150, 'g'],
      ['fasolka szparagowa', 150, 'g'],
      ['ryż jaśminowy', 50, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej sezamowy', 5, 'ml'],
      ['sezam', 10, 'g'],
      ['cebula dymka', 20, 'g'],
    ],
    steps: [
      'Ugotuj ryż w wodzie według instrukcji na opakowaniu, około 12 minut.',
      'Kurczaka pokrój w paski, brokuł podziel na różyczki, marchew pokrój w słupki, a fasolce odetnij końce.',
      'Zagotuj wodę w garnku z sitkiem lub parowarem. Gotuj kurczaka z marchewką i fasolką na parze pod przykryciem 8 minut, dodaj brokuł i gotuj jeszcze 5 minut.',
      'Wymieszaj sos sojowy z startym imbirem, przeciśniętym czosnkiem, olejem sezamowym i 2 łyżkami wody.',
      'Sezam podpraż na suchej patelni. Ułóż kurczaka i warzywa obok ryżu, polej sosem i posyp sezamem i posiekaną dymką.',
    ],
    photo:
      'Steamed chicken strips with bright green broccoli, green beans and carrot sticks glazed with soy ginger sauce, sesame seeds, spring onion and a small mound of jasmine rice',
  },
  {
    plan: 'KO-017',
    title: 'Fasola z tuńczykiem po toskańsku',
    description:
      'Biała fasola z tuńczykiem, czerwoną cebulą, pomidorkami i natką, skropiona oliwą i cytryną, jak w toskańskich trattoriach. Kolacja bez gotowania w kwadrans, lekka i pełna białka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['fasola biała z puszki', 340, 'g'],
      ['tuńczyk w puszce', 150, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['rukola', 40, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Fasolę odcedź na sitku i przepłucz zimną wodą. Tuńczyka odsącz.',
      'Cebulę pokrój w cienkie piórka i zalej sokiem z cytryny na 5 minut, żeby złagodniała.',
      'Pomidorki przekrój na pół, natkę posiekaj, czosnek przeciśnij.',
      'W misce wymieszaj fasolę z cebulą razem z sokiem, czosnkiem, oliwą, pomidorkami i natką. Dopraw pieprzem.',
      'Ułóż na rukoli, na wierzch połóż kawałki tuńczyka.',
    ],
    photo:
      'White cannellini beans tossed with thin red onion, halved cherry tomatoes and parsley on arugula, topped with flaked tuna and a drizzle of olive oil',
  },
  {
    plan: 'KO-018',
    title: 'Kurczak z fasolką szparagową i sezamem',
    description:
      'Paski kurczaka smażone z chrupiącą fasolką szparagową, czosnkiem i imbirem, glazurowane miodem z limonką i posypane prażonym sezamem. Lekka kolacja z wokiem, bez sosu sojowego i bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['fasolka szparagowa', 350, 'g'],
      ['sezam', 15, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 10, 'g'],
      ['olej sezamowy', 10, 'ml'],
      ['olej rzepakowy', 10, 'ml'],
      ['miód', 10, 'g'],
      ['limonka', 60, 'g'],
      ['cebula dymka', 30, 'g'],
      ['płatki chili', 1, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Fasolce odetnij końce i blanszuj ją 3 minuty we wrzątku, potem przelej zimną wodą.',
      'Kurczaka pokrój w paski i posól. Czosnek posiekaj, imbir zetrzyj, dymkę pokrój w krążki.',
      'Rozgrzej olej rzepakowy w woku lub na dużej patelni i smaż kurczaka na dużym ogniu 5 minut.',
      'Dodaj fasolkę, czosnek, imbir i płatki chili, smaż 3 minuty, mieszając.',
      'Wlej olej sezamowy, miód i sok z limonki, smaż jeszcze minutę, aż sos oblepi składniki. Posyp prażonym sezamem i dymką.',
    ],
    photo:
      'Wok-fried chicken strips with glossy green beans, sliced garlic, spring onion and toasted sesame seeds, lime wedge on the side',
  },
  {
    plan: 'KO-019',
    title: 'Zupa z pieczonych pomidorów i papryki',
    description:
      'Pomidory, czerwona papryka, cebula i czosnek upieczone do lekkiego przypalenia i zmiksowane na gęstą, dymną zupę, podaną z chrupiącą ciecierzycą. Letnia, lekka i wegańska kolacja.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 55,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    seasons: ['SUMMER'],
    equipment: ['OVEN', 'BLENDER'],
    ingredients: [
      ['pomidor', 800, 'g'],
      ['papryka czerwona', 320, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['czosnek', 4, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ciecierzyca z puszki', 120, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['bazylia', 10, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 210°C. Pomidory przekrój na pół, paprykę pokrój w paski, cebulę w ćwiartki.',
      'Ułóż warzywa i nieobrany czosnek na blasze, skrop 15 ml oliwy, posyp tymiankiem i solą. Ciecierzycę osusz, wymieszaj z resztą oliwy i wędzoną papryką i rozłóż na brzegu blachy.',
      'Piecz 35 minut, aż warzywa się zrumienią, a ciecierzyca będzie chrupiąca. Ciecierzycę odłóż.',
      'Przełóż warzywa do garnka, wyciśnij czosnek ze skórek, wlej 300 ml gorącej wody i zmiksuj blenderem. Podgrzewaj 3 minuty.',
      'Podawaj zupę posypaną chrupiącą ciecierzycą i listkami bazylii.',
    ],
    photo:
      'Thick deep red roasted tomato and pepper soup topped with crunchy smoky roasted chickpeas and fresh basil leaves',
    vessel: 'bowl',
  },
  {
    plan: 'KO-020',
    title: 'Makaron ryżowy z warzywami i jajkiem',
    description:
      'Makaron ryżowy smażony z marchewką, papryką i kapustą pekińską, z jajecznicą, słodkim chili, limonką i prażonymi orzeszkami. Szybka kolacja z woka bez glutenu i bez nabiału.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    ingredients: [
      ['makaron ryżowy', 140, 'g'],
      ['jajko', 3, 'szt'],
      ['marchew', 100, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['kapusta pekińska', 150, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['sos chili słodki', 30, 'g'],
      ['limonka', 60, 'g'],
      ['orzeszek ziemny', 20, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Makaron ryżowy zalej wrzątkiem na 5 minut, odcedź i przelej zimną wodą.',
      'Marchew pokrój w cienkie słupki, paprykę w paski, kapustę poszatkuj, dymkę pokrój w krążki. Czosnek i imbir posiekaj.',
      'Rozgrzej połowę oleju w woku, wbij jajka, posól i usmaż jajecznicę, rwąc ją łopatką. Zdejmij na talerz.',
      'Wlej resztę oleju, smaż czosnek z imbirem 30 sekund, dodaj marchew i paprykę i smaż 3 minuty, potem kapustę jeszcze 2 minuty.',
      'Dodaj makaron, jajko, sos chili i sok z limonki, wymieszaj i podgrzewaj 2 minuty. Posyp posiekanymi orzeszkami i dymką.',
    ],
    photo:
      'Stir-fried rice noodles with scrambled egg, carrot sticks, red pepper strips and napa cabbage, topped with chopped peanuts, spring onion and a lime wedge',
    vessel: 'bowl',
  },
  {
    plan: 'KO-021',
    title: 'Ryba po hiszpańsku z papryką i pomidorami',
    description:
      'Kawałki dorsza duszone w sosie z pomidorów, dwóch papryk, czosnku i wędzonej papryki, z zielonymi oliwkami i natką. Lekka, aromatyczna kolacja w stylu hiszpańskiego wybrzeża.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'MAIN',
    ingredients: [
      ['dorsz', 350, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['papryka żółta', 160, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['oliwka zielona', 30, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę pokrój w piórka, papryki w paski, czosnek w plasterki. Dorsza pokrój na 4 kawałki, posól i popieprz.',
      'Rozgrzej oliwę na głębokiej patelni i duś cebulę z papryką 8 minut, aż zmiękną. Dodaj czosnek i wędzoną paprykę i smaż minutę.',
      'Wlej pomidory z puszki, dodaj oliwki i gotuj sos 10 minut na małym ogniu.',
      'Włóż kawałki dorsza w sos, przykryj i duś 8–10 minut, aż ryba zacznie się rozdzielać na płatki.',
      'Posyp posiekaną natką i podawaj prosto z patelni.',
    ],
    photo:
      'Pan of white cod pieces nestled in a rich tomato sauce with red and yellow pepper strips, green olives and chopped parsley',
  },
  {
    plan: 'KO-022',
    title: 'Cukinia faszerowana kaszą jaglaną i warzywami',
    description:
      'Łódki z cukinii wypełnione kaszą jaglaną z pieczarkami, papryką i pomidorami, zapieczone i posypane prażonym słonecznikiem. Lekka wegańska kolacja, w której nic się nie marnuje.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 55,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['cukinia', 800, 'g'],
      ['kasza jaglana', 70, 'g'],
      ['pieczarka', 150, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['oregano', 1, 'g'],
      ['słonecznik łuszczony', 20, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz gorącą wodą, zalej 150 ml wrzątku i gotuj pod przykryciem 15 minut. Rozgrzej piekarnik do 190°C.',
      'Cukinie przekrój wzdłuż i wydrąż łyżką środek, zostawiając ścianki grubości 1 cm. Miąższ posiekaj.',
      'Cebulę, czosnek, pieczarki i paprykę pokrój w drobną kostkę. Rozgrzej oliwę na patelni i smaż je z miąższem cukinii 8 minut.',
      'Dodaj pomidory z puszki, oregano, sól i pieprz, gotuj 3 minuty, potem wmieszaj kaszę.',
      'Napełnij łódki farszem, ułóż w naczyniu żaroodpornym i piecz 25 minut, aż cukinia zmięknie.',
      'Posyp podprażonym słonecznikiem i posiekaną natką.',
    ],
    photo:
      'Halved zucchini boats stuffed with golden millet, mushrooms, red pepper and tomato, baked and sprinkled with toasted sunflower seeds and parsley',
  },
  {
    plan: 'KO-023',
    title: 'Placki z mąki z ciecierzycy z warzywami',
    description:
      'Złote placki z mąki z ciecierzycy z tartą cukinią, marchewką, szpinakiem i kminem, podane z czosnkowym jogurtem kokosowym i pomidorem. Wegańska kolacja bez glutenu, która dobrze syci.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    ingredients: [
      ['mąka z ciecierzycy', 150, 'g'],
      ['cukinia', 150, 'g'],
      ['marchew', 100, 'g'],
      ['szpinak', 60, 'g'],
      ['cebula dymka', 30, 'g'],
      ['kurkuma', 1, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['jogurt kokosowy', 100, 'g'],
      ['czosnek', 1, 'szt'],
      ['pomidor', 200, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Mąkę z ciecierzycy wymieszaj z kurkumą, kminem i solą, wlej 180 ml zimnej wody i roztrzep na gładkie ciasto. Odstaw na 10 minut.',
      'Cukinię i marchew zetrzyj na tarce o grubych oczkach, cukinię odciśnij. Szpinak i dymkę posiekaj.',
      'Wmieszaj warzywa do ciasta.',
      'Rozgrzej olej na patelni, nakładaj po 2 łyżki ciasta i rozpłaszczaj. Smaż na średnim ogniu po 3–4 minuty z każdej strony, aż placki będą złote i ścięte.',
      'Jogurt kokosowy wymieszaj z przeciśniętym czosnkiem. Podawaj placki z sosem i pomidorem pokrojonym w ćwiartki.',
    ],
    photo:
      'Golden chickpea flour fritters speckled with grated zucchini, carrot and spinach, with a bowl of white garlic coconut yogurt and tomato wedges',
  },
  {
    plan: 'KO-024',
    title: 'Jajka w koszulce na szpinaku z pomidorami',
    description:
      'Jajka w koszulce z płynnym żółtkiem na czosnkowym szpinaku z pomidorkami, podane z chrupiącą grzanką z chleba bezglutenowego. Delikatna, lekka kolacja gotowa w dwadzieścia minut.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 4, 'szt'],
      ['szpinak', 300, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['ocet jabłkowy', 20, 'ml'],
      ['chleb bezglutenowy', 80, 'g'],
      ['płatki chili', 0.5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej oliwę na patelni, wrzuć przekrojone pomidorki i smaż 3 minuty. Dodaj posiekany czosnek i szpinak, smaż 2–3 minuty, aż liście zwiędną. Dopraw solą i pieprzem.',
      'W szerokim garnku zagotuj około 1,5 litra wody z octem i zmniejsz ogień tak, żeby woda tylko lekko drgała.',
      'Każde jajko wbij do miseczki, zakręć wodę łyżką i delikatnie wlej jajko w środek wiru. Gotuj 3 minuty i wyjmij łyżką cedzakową.',
      'Chleb opiecz w tosterze albo na suchej patelni.',
      'Ułóż szpinak z pomidorkami na talerzach, połóż na nich jajka, posyp płatkami chili i podawaj z grzanką.',
    ],
    photo:
      'Two poached eggs with runny yolks on a bed of wilted garlicky spinach and blistered cherry tomatoes, chili flakes, toasted bread on the side',
  },
  {
    plan: 'KO-025',
    title: 'Kurczak pieczony z pomidorkami i oliwkami',
    description:
      'Kurczak pieczony z cukinią, pomidorkami koktajlowymi, czarnymi oliwkami i czerwoną cebulą, z oregano i cytryną. Grecka kolacja z jednej blachy, lekka i bardzo sycąca.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['pomidor koktajlowy', 300, 'g'],
      ['cukinia', 200, 'g'],
      ['oliwka czarna', 50, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['oregano', 2, 'g'],
      ['cytryna', 50, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Kurczaka pokrój na duże kawałki i wymieszaj z oliwą, oregano, przeciśniętym czosnkiem, solą i pieprzem.',
      'Cukinię pokrój w półplasterki, cebulę w ósemki, pomidorki zostaw w całości.',
      'Rozłóż kurczaka i warzywa na blasze lub w naczyniu żaroodpornym, dołóż oliwki i plasterki cytryny.',
      'Piecz 25 minut, w połowie mieszając, aż kurczak się zrumieni, a pomidorki popękają.',
      'Skrop sokiem z pieczonej cytryny i podawaj prosto z blachy.',
    ],
    photo:
      'Roasting dish of golden chicken pieces with blistered cherry tomatoes, zucchini, red onion wedges, black olives and roasted lemon slices sprinkled with oregano',
  },
  {
    plan: 'KO-026',
    title: 'Tofu z warzywami z patelni w sosie sojowym',
    description:
      'Chrupiące kostki tofu smażone z brokułem, papryką i edamame w gęstym sosie sojowym z imbirem i czosnkiem, posypane sezamem. Szybka wegańska kolacja z dużą porcją roślinnego białka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    ingredients: [
      ['tofu', 400, 'g'],
      ['brokuł', 250, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['edamame', 100, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos sojowy', 25, 'ml'],
      ['mąka ziemniaczana', 10, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sezam', 10, 'g'],
    ],
    steps: [
      'Tofu odsącz, osusz ręcznikiem papierowym i pokrój w kostkę. Obtocz w połowie mąki ziemniaczanej.',
      'Rozgrzej olej na dużej patelni i smaż tofu 8 minut, obracając, aż będzie złote z każdej strony. Zdejmij na talerz.',
      'Na tę samą patelnię wrzuć różyczki brokułu, paprykę w paskach i edamame, dodaj 3 łyżki wody i smaż pod przykryciem 5 minut.',
      'Sos sojowy wymieszaj z resztą mąki, startym imbirem, przeciśniętym czosnkiem i 80 ml wody. Wlej na patelnię, dodaj tofu i gotuj 1–2 minuty, aż sos zgęstnieje.',
      'Posyp sezamem i posiekaną dymką.',
    ],
    photo:
      'Golden crispy tofu cubes with broccoli florets, red pepper strips and green edamame in a glossy soy ginger sauce, sprinkled with sesame and spring onion',
    vessel: 'bowl',
  },
  {
    plan: 'KO-027',
    title: 'Kotlety z soczewicy z sosem pomidorowym',
    description:
      'Miękkie w środku kotlety z czerwonej soczewicy z marchewką, kminem i natką, podane w gęstym sosie pomidorowym z oregano. Wegańska, sycąca kolacja, która smakuje też następnego dnia.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica czerwona', 200, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['marchew', 75, 'g'],
      ['mąka z ciecierzycy', 30, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['passata pomidorowa', 400, 'ml'],
      ['oregano', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Soczewicę przepłucz, zalej 400 ml wody i gotuj 12–15 minut, aż zmięknie i wchłonie wodę. Odstaw do przestygnięcia.',
      'Połowę cebuli i marchew zetrzyj na drobnej tarce, dwa ząbki czosnku przeciśnij, natkę posiekaj.',
      'Wymieszaj soczewicę z warzywami, mąką z ciecierzycy, kminem, wędzoną papryką i połową soli. Uformuj 8 kotletów.',
      'Rozgrzej olej na patelni i smaż kotlety na średnim ogniu po 4 minuty z każdej strony. Zdejmij na talerz.',
      'Na tej samej patelni podsmaż resztę posiekanej cebuli i czosnku przez 3 minuty, wlej passatę, dodaj oregano i resztę soli i gotuj 8 minut.',
      'Włóż kotlety do sosu, podgrzej razem 2 minuty i podawaj.',
    ],
    photo:
      'Golden red lentil patties resting in a thick tomato sauce with oregano, sprinkled with chopped parsley',
  },
  {
    plan: 'KO-028',
    title: 'Placki z kalafiora z sosem czosnkowym',
    description:
      'Chrupiące placki z drobno posiekanego kalafiora z parmezanem i dymką, podane z gęstym czosnkowo-koperkowym sosem jogurtowym. Pomysł na kalafiora, który przekona nawet niejadków.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    ingredients: [
      ['kalafior', 500, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 60, 'g'],
      ['ser parmezan', 30, 'g'],
      ['cebula dymka', 20, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['jogurt grecki', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kalafior podziel na różyczki i gotuj w osolonej wodzie 8 minut. Odcedź, ostudź i posiekaj drobno lub rozgnieć tłuczkiem.',
      'Dodaj jajka, mąkę, starty parmezan, posiekaną dymkę i pieprz, wymieszaj na gęstą masę.',
      'Rozgrzej olej na patelni, nakładaj po łyżce masy i spłaszczaj. Smaż na średnim ogniu po 3–4 minuty z każdej strony, aż placki będą złote.',
      'Jogurt wymieszaj z przeciśniętym czosnkiem i posiekanym koperkiem.',
      'Podawaj placki gorące z sosem czosnkowym.',
    ],
    photo:
      'Golden crispy cauliflower fritters flecked with parmesan and spring onion, served with thick white garlic dill yogurt sauce',
  },
  {
    plan: 'KO-029',
    title: 'Cukinia zapiekana z serem i pomidorami',
    description:
      'Plastry cukinii i pomidorów ułożone na przemian w naczyniu, z czosnkiem, oregano i mozzarellą, zapieczone pod parmezanem na złoto. Lekka letnia kolacja bez glutenu, prosto z piekarnika.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    seasons: ['SUMMER'],
    equipment: ['OVEN'],
    ingredients: [
      ['cukinia', 700, 'g'],
      ['pomidor', 400, 'g'],
      ['mozzarella', 125, 'g'],
      ['ser parmezan', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['bazylia', 10, 'g'],
      ['oregano', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Cukinię i pomidory pokrój w plastry grubości 5 mm.',
      'Oliwę wymieszaj z przeciśniętym czosnkiem, oregano, solą i pieprzem, posmaruj nią dno naczynia żaroodpornego.',
      'Układaj plastry cukinii i pomidorów na zmianę, lekko na zakładkę, i skrop resztą czosnkowej oliwy.',
      'Piecz 20 minut, potem rozłóż porwaną mozzarellę, posyp startym parmezanem i zapiekaj jeszcze 10–12 minut, aż ser się zrumieni.',
      'Posyp listkami bazylii i podawaj na ciepło.',
    ],
    photo:
      'Baking dish of overlapping zucchini and tomato slices covered with melted golden mozzarella and parmesan, topped with fresh basil leaves',
  },
];
