/**
 * Katalog 1000 — część KO-b: kolacje KO-030 … KO-058 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'KO-030',
    title: 'Makaron ryżowy z tofu, marchewką i sosem limonkowym',
    description:
      'Makaron ryżowy z chrupiącym tofu, marchewką i dymką w kwaśno-słodkim sosie z limonki, imbiru i sosu sojowego, posypany orzeszkami i kolendrą. Szybka tajska kolacja z jednego woka, w pełni roślinna.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'PASTA',
    ingredients: [
      ['makaron ryżowy', 140, 'g'],
      ['tofu', 200, 'g'],
      ['marchew', 150, 'g'],
      ['cebula dymka', 30, 'g'],
      ['limonka', 60, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['syrop klonowy', 10, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['orzeszek ziemny', 25, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Zalej makaron ryżowy gorącą wodą i odstaw na 8–10 minut, a potem odcedź i przelej zimną wodą.',
      'Tofu osusz ręcznikiem papierowym i pokrój w kostkę. Marchew zetrzyj na grubych oczkach albo pokrój w cienkie paski, dymkę posiekaj.',
      'Przygotuj sos: wymieszaj sok i skórkę z limonki, sos sojowy, syrop klonowy, starty imbir i przeciśnięty czosnek.',
      'Rozgrzej olej w woku i smaż tofu 6–7 minut, aż zezłoci się z każdej strony. Dodaj marchew i białą część dymki, smaż 2 minuty.',
      'Wrzuć makaron, wlej sos i mieszaj na dużym ogniu 2 minuty, aż makaron go wchłonie.',
      'Orzeszki ziemne upraż na suchej patelni i posiekaj. Podawaj makaron posypany orzeszkami, zieloną dymką i kolendrą.',
    ],
    photo:
      'Glossy rice noodles tossed with golden tofu cubes, shredded orange carrot and spring onion, topped with chopped peanuts, cilantro and lime wedges',
    vessel: 'bowl',
  },
  {
    plan: 'KO-031',
    title: 'Tarta z porem i kozim serem',
    description:
      'Chrupiące ciasto francuskie wypełnione duszonym na maśle porem, jajeczno-śmietanową masą i kawałkami koziego sera z tymiankiem. Elegancka, a prosta kolacja, która smakuje także na zimno.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['ciasto francuskie', 150, 'g'],
      ['por', 250, 'g'],
      ['ser kozi', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['śmietanka 18', 100, 'ml'],
      ['masło', 10, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Wyłóż ciastem francuskim małą formę do tarty (ok. 20 cm), nakłuj spód widelcem i podpiecz 10 minut.',
      'Por przekrój wzdłuż, dokładnie opłucz i pokrój w półplasterki. Duś go na maśle 8–10 minut, aż zmięknie.',
      'Roztrzep jajka ze śmietanką, tymiankiem i pieprzem.',
      'Rozłóż por na podpieczonym spodzie, wlej masę jajeczną i ułóż na wierzchu pokruszony kozi ser.',
      'Piecz tartę 20–25 minut w 180°C, aż masa się zetnie, a ser lekko zarumieni. Odstaw na 5 minut przed krojeniem.',
    ],
    photo:
      'Golden puff pastry tart filled with soft pale green leek, set egg custard and browned crumbles of goat cheese sprinkled with thyme',
  },
  {
    plan: 'KO-032',
    title: 'Miska z hummusem i pieczonymi warzywami',
    description:
      'Komosa ryżowa, pieczony batat, cukinia i papryka z chrupiącą ciecierzycą na kremowym hummusie z cytryną. Kolorowa, sycąca miska, która dobrze znosi pudełko i nie ma w sobie nic odzwierzęcego.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['komosa ryżowa', 80, 'g'],
      ['hummus', 150, 'g'],
      ['batat', 300, 'g'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['ciecierzyca z puszki', 120, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 210°C (termoobieg 200°C). Batat pokrój w kostkę, cukinię w półplasterki, paprykę w paski, cebulę w ósemki.',
      'Odsącz i osusz ciecierzycę. Wymieszaj warzywa i ciecierzycę z oliwą, papryką wędzoną, kminem i solą, rozłóż na blasze z papierem.',
      'Piecz 25–30 minut, w połowie przemieszaj, aż batat zmięknie, a ciecierzyca zrobi się chrupiąca.',
      'W tym czasie przepłucz komosę ryżową i ugotuj ją w podwójnej ilości wody pod przykryciem przez 15 minut.',
      'Rozsmaruj hummus na dnie misek, dołóż komosę i pieczone warzywa z ciecierzycą.',
      'Skrop sokiem z cytryny i posyp posiekaną natką pietruszki.',
    ],
    photo:
      'Bowl with a swirl of creamy hummus, fluffy quinoa, roasted orange sweet potato cubes, red pepper strips, zucchini and crispy chickpeas, topped with parsley',
    vessel: 'bowl',
  },
  {
    plan: 'KO-033',
    title: 'Zapiekanka z ziemniakami, brokułem i serem',
    description:
      'Plasterki ziemniaków i różyczki brokuła zapieczone w czosnkowej śmietance pod złotą warstwą sera. Domowa, rozgrzewająca kolacja, którą chętnie zjedzą też dzieci.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 55,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['brokuł', 300, 'g'],
      ['ser żółty', 80, 'g'],
      ['śmietanka 18', 150, 'ml'],
      ['jajko', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['masło', 10, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C. Ziemniaki obierz, pokrój w plasterki grubości 3 mm i gotuj w osolonej wodzie 6 minut, a potem odcedź.',
      'Brokuł podziel na różyczki i blanszuj 2 minuty we wrzątku.',
      'Roztrzep śmietankę z jajkiem, przeciśniętym czosnkiem, gałką muszkatołową, solą i pieprzem.',
      'Natłuść naczynie żaroodporne masłem, układaj warstwami ziemniaki i brokuł, zalej masą śmietanową i posyp startym serem.',
      'Piecz 30 minut, aż ziemniaki będą miękkie, a ser złocisty.',
    ],
    photo:
      'Bubbling potato and broccoli bake with thin potato slices, bright green florets and a golden melted cheese crust in a white baking dish',
  },
  {
    plan: 'KO-034',
    title: 'Kasza z fasolą i warzywami po meksykańsku z jednej patelni',
    description:
      'Kasza jaglana duszona w pomidorach z czerwoną fasolą, kukurydzą, papryką i kminem, podana z awokado i limonką. Rozgrzewające danie z jednej patelni, bez glutenu i w pełni roślinne.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza jaglana', 120, 'g'],
      ['fasola czerwona z puszki', 200, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula', 110, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 300, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['awokado', 1, 'szt'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Przepłucz kaszę jaglaną na sitku gorącą wodą.',
      'Na głębokiej patelni rozgrzej oliwę, zeszklij posiekaną cebulę przez 4 minuty, dodaj pokrojoną paprykę i czosnek, smaż 3 minuty.',
      'Wsyp kmin rzymski i paprykę wędzoną, a po 30 sekundach dodaj kaszę, passatę, 250 ml wody i sól.',
      'Przykryj i duś na małym ogniu 15 minut, mieszając od czasu do czasu.',
      'Dodaj odsączoną fasolę i kukurydzę, podgrzewaj 3 minuty, aż kasza wchłonie płyn.',
      'Podawaj z plastrami awokado, sokiem z limonki i posiekaną kolendrą.',
    ],
    photo:
      'Skillet of tomato-red millet with kidney beans, sweet corn and red pepper, topped with sliced avocado, cilantro and lime wedges',
  },
  {
    plan: 'KO-035',
    title: 'Pasta z pieczonego łososia z twarożkiem na chlebie',
    description:
      'Łosoś upieczony z cytryną i rozgnieciony z twarożkiem, koperkiem i dymką na puszystą pastę, podany na żytnim chlebie z ogórkiem i rzodkiewką. Sycąca kolacja pełna białka i kwasów omega-3.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SANDWICH',
    equipment: ['OVEN'],
    ingredients: [
      ['łosoś', 150, 'g'],
      ['twarożek', 150, 'g'],
      ['cebula dymka', 20, 'g'],
      ['koperek', 5, 'g'],
      ['cytryna', 20, 'g'],
      ['chleb żytni', 160, 'g'],
      ['ogórek', 150, 'g'],
      ['rzodkiewka', 60, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Łososia połóż na papierze do pieczenia, skrop sokiem z cytryny, popieprz i piecz 12–15 minut.',
      'Przestudzonego łososia zdejmij ze skóry i rozdrobnij widelcem.',
      'Wymieszaj łososia z twarożkiem, posiekanym koperkiem i dymką, dopraw pieprzem i odrobiną skórki z cytryny.',
      'Ogórek i rzodkiewki pokrój w cienkie plasterki.',
      'Posmaruj kromki chleba pastą i ułóż na nich ogórek i rzodkiewkę.',
    ],
    photo:
      'Slices of dark rye bread spread with pale pink salmon and cottage cheese paste, topped with cucumber and radish slices and fresh dill',
    vessel: 'board',
  },
  {
    plan: 'KO-036',
    title: 'Sałatka z wędzoną makrelą, ziemniakami i jajkiem',
    description:
      'Ciepłe ziemniaki, jajka na twardo i kawałki wędzonej makreli z ogórkiem i czerwoną cebulą w lekkim sosie jogurtowo-musztardowym. Treściwa sałatka na kolację, która dobrze smakuje też następnego dnia.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SALAD',
    ingredients: [
      ['makrela wędzona', 120, 'g'],
      ['ziemniak', 300, 'g'],
      ['jajko', 2, 'szt'],
      ['ogórek', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['sałata rzymska', 80, 'g'],
      ['szczypiorek', 10, 'g'],
      ['jogurt naturalny', 80, 'g'],
      ['musztarda', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki umyj i ugotuj w mundurkach do miękkości przez 20 minut. Jajka gotuj 9 minut, przelej zimną wodą i obierz.',
      'Makrelę obierz ze skóry i ości, rozdziel na kawałki.',
      'Ziemniaki obierz i pokrój w kostkę, jajka w ćwiartki, ogórek w półplasterki, cebulę w cienkie piórka.',
      'Wymieszaj jogurt z musztardą, pieprzem i połową posiekanego szczypiorku.',
      'Na porwanej sałacie ułóż ziemniaki, ogórek, cebulę i makrelę, polej sosem, dołóż jajka i posyp resztą szczypiorku.',
    ],
    photo:
      'Salad of warm potato cubes, flaked golden smoked mackerel, egg quarters, cucumber and red onion on romaine, drizzled with creamy mustard dressing and chives',
  },
  {
    plan: 'KO-037',
    title: 'Tatar z wędzonego łososia z awokado',
    description:
      'Drobno siekany wędzony łosoś z szalotką, koperkiem i cytryną, podany na warstwie awokado z jajkiem i rukolą. Efektowna kolacja bez gotowania, gotowa w kwadrans i prawie bez węglowodanów.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    ingredients: [
      ['łosoś wędzony', 160, 'g'],
      ['awokado', 2, 'szt'],
      ['szalotka', 30, 'g'],
      ['jajko', 2, 'szt'],
      ['cytryna', 20, 'g'],
      ['koperek', 5, 'g'],
      ['szczypiorek', 5, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Jajka ugotuj na twardo przez 9 minut, przelej zimną wodą, obierz i posiekaj.',
      'Łososia posiekaj ostrym nożem w drobną kostkę, szalotkę i koperek posiekaj bardzo drobno.',
      'Wymieszaj łososia z szalotką, koperkiem, oliwą, połową soku z cytryny i pieprzem.',
      'Awokado rozgnieć widelcem z resztą soku z cytryny.',
      'Na talerzach ułóż w pierścieniu warstwę awokado, a na niej tatar. Posyp jajkiem i szczypiorkiem, obok połóż rukolę.',
    ],
    photo:
      'Neat round tower of finely diced pink smoked salmon tartare on a layer of mashed green avocado, topped with chopped egg and chives, with arugula on the side',
  },
  {
    plan: 'KO-038',
    title: 'Kanapki ze szprotkami, jajkiem i szczypiorkiem',
    description:
      'Żytni chleb z masłem, szprotkami w oleju, jajkiem na twardo, pomidorem i cienko krojoną cebulą, posypany szczypiorkiem. Klasyczna, tania kolacja z puszki, gotowa w kwadrans.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SANDWICH',
    ingredients: [
      ['chleb żytni', 160, 'g'],
      ['szproty w oleju', 120, 'g'],
      ['jajko', 2, 'szt'],
      ['masło', 15, 'g'],
      ['pomidor', 150, 'g'],
      ['cebula czerwona', 30, 'g'],
      ['szczypiorek', 15, 'g'],
      ['cytryna', 10, 'g'],
    ],
    steps: [
      'Jajka gotuj 9 minut, przelej zimną wodą, obierz i pokrój w plasterki.',
      'Szprotki odsącz z oleju. Pomidor pokrój w plastry, cebulę w cienkie krążki, szczypiorek posiekaj.',
      'Posmaruj kromki chleba cienko masłem, ułóż plastry pomidora i jajka.',
      'Na wierzchu połóż szprotki, skrop je sokiem z cytryny, dodaj cebulę i obficie posyp szczypiorkiem.',
    ],
    photo:
      'Open rye bread sandwiches with glistening golden sprats, sliced boiled egg, tomato rounds, thin red onion rings and plenty of chopped chives',
    vessel: 'board',
  },
  {
    plan: 'KO-039',
    title: 'Wędzony pstrąg z sałatką z buraka i chrzanem',
    description:
      'Delikatny wędzony pstrąg z ciepłymi ziemniakami i sałatką z gotowanego buraka, jabłka i roszponki, podany z kremowym sosem chrzanowym. Zimowa kolacja o wyrazistym, lekko pikantnym smaku.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['WINTER'],
    ingredients: [
      ['pstrąg wędzony', 150, 'g'],
      ['burak', 300, 'g'],
      ['ziemniak', 300, 'g'],
      ['jabłko', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['roszponka', 50, 'g'],
      ['chrzan tarty', 30, 'g'],
      ['śmietana 18', 60, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['ocet jabłkowy', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Buraki umyj i gotuj w całości 40 minut do miękkości. W osobnym garnku ugotuj ziemniaki w mundurkach przez 20 minut.',
      'Ostudzone buraki obierz i pokrój w kostkę, jabłko w cienkie słupki, cebulę w piórka.',
      'Wymieszaj buraki z jabłkiem i cebulą, dopraw oliwą, octem jabłkowym i pieprzem.',
      'Połącz śmietanę z chrzanem na gładki sos.',
      'Pstrąga zdejmij ze skóry i podziel na duże kawałki. Na talerzach ułóż roszponkę, sałatkę z buraka, obrane ziemniaki i pstrąga, obok podaj sos chrzanowy.',
    ],
    photo:
      'Flaked golden smoked trout beside deep magenta beet and apple salad on lamb lettuce, halved boiled potatoes and a dollop of white horseradish cream',
  },
  {
    plan: 'KO-040',
    title: 'Sardynki na grzankach z pomidorem',
    description:
      'Chrupiące grzanki z ciabatty natarte czosnkiem i świeżym pomidorem, z sardynkami, czerwoną cebulą i natką. Hiszpańska kolacja w stylu tapas, gotowa w kwadrans z produktów ze spiżarni.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'SANDWICH',
    ingredients: [
      ['ciabatta', 160, 'g'],
      ['sardynka w oleju', 120, 'g'],
      ['pomidor', 250, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cebula czerwona', 40, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['cytryna', 20, 'g'],
      ['papryka wędzona mielona', 1, 'g'],
    ],
    steps: [
      'Ciabattę pokrój wzdłuż i w poprzek na 4 kawałki, skrop oliwą i opiecz na suchej patelni po 2 minuty z każdej strony.',
      'Gorące grzanki natrzyj przekrojonym ząbkiem czosnku.',
      'Połowę pomidora zetrzyj na tarce i rozsmaruj miąższ na grzankach, resztę pokrój w plasterki.',
      'Ułóż na grzankach plastry pomidora i odsączone sardynki, skrop sokiem z cytryny, posyp papryką wędzoną, cienko pokrojoną cebulą i natką.',
    ],
    photo:
      'Crusty toasted ciabatta slices rubbed with grated tomato, topped with silver sardines, tomato slices, red onion rings, parsley and a pinch of smoked paprika',
    vessel: 'board',
  },
  {
    plan: 'KO-041',
    title: 'Krewetki w maśle czosnkowym z bagietką',
    description:
      'Krewetki smażone krótko na maśle i oliwie z dużą ilością czosnku, chili i natki, podane z bagietką do maczania w sosie. Hiszpańska klasyka z tapas barów, gotowa w 20 minut.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'MAIN',
    ingredients: [
      ['krewetka', 250, 'g'],
      ['masło', 40, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['czosnek', 5, 'szt'],
      ['papryczka chili', 15, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['cytryna', 30, 'g'],
      ['bagietka', 140, 'g'],
    ],
    steps: [
      'Krewetki rozmroź, jeśli są mrożone, i dokładnie osusz ręcznikiem papierowym.',
      'Czosnek pokrój w cienkie plasterki, chili w krążki, natkę posiekaj.',
      'Na szerokiej patelni rozgrzej oliwę z masłem, wrzuć czosnek i chili i smaż 1 minutę na średnim ogniu, aż czosnek zacznie się złocić.',
      'Dodaj krewetki, posyp papryką i smaż po 1–2 minuty z każdej strony, aż staną się różowe.',
      'Zdejmij z ognia, skrop sokiem z cytryny i posyp natką. Podawaj od razu z pokrojoną bagietką do maczania w maśle.',
    ],
    photo:
      'Sizzling pink shrimp in golden garlic butter with sliced garlic, red chili rings and chopped parsley in a small pan, with baguette slices and lemon wedges',
  },
  {
    plan: 'KO-042',
    title: 'Sałatka z krewetkami, awokado i mango',
    description:
      'Soczyste krewetki z patelni z kremowym awokado, słodkim mango i chrupiącą sałatą w dressingu z limonki i chili. Świeża, kolorowa kolacja bez glutenu i nabiału, lekka, a sycąca.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    ingredients: [
      ['krewetka', 200, 'g'],
      ['awokado', 1, 'szt'],
      ['mango', 200, 'g'],
      ['sałata rzymska', 100, 'g'],
      ['ogórek', 100, 'g'],
      ['cebula czerwona', 30, 'g'],
      ['limonka', 30, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryczka chili', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Krewetki osusz. Rozgrzej połowę oliwy z przeciśniętym czosnkiem i smaż krewetki po 1–2 minuty z każdej strony.',
      'Mango i awokado obierz i pokrój w kostkę, ogórek w półplasterki, cebulę w cienkie piórka.',
      'Przygotuj dressing: sok z limonki, resztę oliwy i drobno posiekane chili.',
      'Na porwanej sałacie ułóż mango, awokado, ogórek i cebulę, dodaj krewetki, polej dressingiem i posyp kolendrą.',
    ],
    photo:
      'Fresh salad of pink seared shrimp, bright yellow mango cubes, green avocado and cucumber on crisp romaine with red onion, chili and cilantro',
    vessel: 'bowl',
  },
  {
    plan: 'KO-043',
    title: 'Wrap z krewetkami, sałatą i sosem jogurtowym',
    description:
      'Pszenna tortilla z krewetkami z patelni, chrupiącą sałatą, pomidorem, awokado i czosnkowym sosem jogurtowym z koperkiem. Szybka kolacja do ręki, gotowa w niecałe 20 minut.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['krewetka', 200, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 1, 'g'],
      ['sałata lodowa', 80, 'g'],
      ['pomidor', 120, 'g'],
      ['ogórek', 100, 'g'],
      ['awokado', 1, 'szt'],
      ['jogurt grecki', 100, 'g'],
      ['czosnek', 1, 'szt'],
      ['koperek', 5, 'g'],
      ['cytryna', 10, 'g'],
    ],
    steps: [
      'Wymieszaj jogurt grecki z przeciśniętym czosnkiem, posiekanym koperkiem i sokiem z cytryny.',
      'Krewetki osusz, obtocz w papryce i smaż na rozgrzanym oleju po 1–2 minuty z każdej strony.',
      'Sałatę poszatkuj, pomidor i ogórek pokrój w słupki, awokado w plastry.',
      'Tortille podgrzej 30 sekund na suchej patelni, posmaruj sosem jogurtowym, ułóż warzywa i krewetki.',
      'Zawiń ciasno, przekrój na pół i podawaj od razu.',
    ],
    photo:
      'Wheat tortilla wrap cut in half showing pink paprika shrimp, crisp iceberg lettuce, tomato, avocado slices and white yogurt dill sauce',
  },
  {
    plan: 'KO-044',
    title: 'Makaron ryżowy z krewetkami i warzywami z patelni',
    description:
      'Makaron ryżowy smażony z krewetkami, papryką, cukinią i marchewką w sosie z limonki, sosu rybnego i słodkiego chili. Aromatyczna kolacja z woka w 25 minut, bez glutenu i nabiału.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    ingredients: [
      ['makaron ryżowy', 140, 'g'],
      ['krewetka', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cukinia', 150, 'g'],
      ['marchew', 100, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos rybny', 8, 'ml'],
      ['sos chili słodki', 20, 'g'],
      ['limonka', 30, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Zalej makaron ryżowy gorącą wodą na 8 minut, odcedź i przelej zimną wodą.',
      'Paprykę, cukinię i marchew pokrój w cienkie paski, dymkę w ukośne kawałki, czosnek i imbir posiekaj.',
      'Wymieszaj sos rybny, sos chili słodki i sok z limonki.',
      'W woku rozgrzej olej, smaż krewetki 2 minuty i odłóż je na talerz.',
      'Na tym samym tłuszczu smaż czosnek, imbir i warzywa 3–4 minuty, aby zostały chrupiące.',
      'Dodaj makaron, krewetki i sos, mieszaj na dużym ogniu 2 minuty. Podawaj posypane kolendrą i dymką.',
    ],
    photo:
      'Stir-fried rice noodles with pink shrimp, red pepper, zucchini and carrot ribbons, glossy sweet chili sauce, spring onion and cilantro',
    vessel: 'bowl',
  },
  {
    plan: 'KO-045',
    title: 'Omlet z krewetkami i szczypiorkiem',
    description:
      'Puszysty omlet z trzech jajek na osobę z czosnkowymi krewetkami, chili i dużą ilością szczypiorku, podany z pomidorkami i rukolą. Szybka, białkowa kolacja prawie bez węglowodanów.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 6, 'szt'],
      ['krewetka', 150, 'g'],
      ['szczypiorek', 15, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['czosnek', 1, 'szt'],
      ['papryczka chili', 10, 'g'],
      ['pomidor koktajlowy', 100, 'g'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Roztrzep jajka z pieprzem i połową posiekanego szczypiorku.',
      'Na patelni rozgrzej 5 ml oleju, smaż krewetki z czosnkiem i drobno pokrojonym chili przez 2 minuty i przełóż je na talerz.',
      'Rozgrzej połowę reszty oleju, wlej połowę masy jajecznej i smaż na średnim ogniu 2–3 minuty, aż spód się zetnie.',
      'Na połowę omletu połóż połowę krewetek, złóż go na pół i smaż jeszcze minutę. Tak samo usmaż drugi omlet.',
      'Podawaj posypane resztą szczypiorku, z przekrojonymi pomidorkami i rukolą.',
    ],
    photo:
      'Fluffy golden folded omelette filled with pink shrimp and red chili, sprinkled with chopped chives, with halved cherry tomatoes and arugula',
  },
  {
    plan: 'KO-046',
    title: 'Krewetki z brokułem i czosnkiem',
    description:
      'Krewetki i chrupiący brokuł smażone na oliwie z czosnkiem, imbirem i chili, skropione cytryną i posypane prażonym sezamem. Lekka kolacja z jednej patelni, gotowa w 20 minut.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    ingredients: [
      ['krewetka', 300, 'g'],
      ['brokuł', 400, 'g'],
      ['czosnek', 4, 'szt'],
      ['imbir', 5, 'g'],
      ['papryczka chili', 10, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 30, 'g'],
      ['sezam', 10, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Brokuł podziel na małe różyczki i blanszuj 2 minuty we wrzątku, a potem odcedź.',
      'Sezam upraż na suchej patelni na złoto i odłóż.',
      'Na dużej patelni rozgrzej oliwę, wrzuć posiekany czosnek, starty imbir i chili, smaż 30 sekund.',
      'Dodaj brokuł i smaż 3 minuty, a potem krewetki i smaż jeszcze 3 minuty, aż staną się różowe. Dopraw solą.',
      'Skrop sokiem z cytryny i posyp sezamem.',
    ],
    photo:
      'Pan of pink sauteed shrimp with bright green broccoli florets, sliced garlic and red chili, sprinkled with toasted sesame seeds and lemon wedges',
  },
  {
    plan: 'KO-047',
    title: 'Szaszłyki z krewetek z grilla z sosem czosnkowym',
    description:
      'Krewetki w marynacie z czosnku, cytryny i papryki wędzonej nabite na patyczki z cukinią, papryką i cebulą, podane z kukurydzą i jogurtowym sosem czosnkowym. Szybkie danie na majówkowy grill.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['krewetka', 300, 'g'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['kukurydza', 300, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['czosnek', 3, 'szt'],
      ['cytryna', 30, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['koperek', 5, 'g'],
    ],
    steps: [
      'Wymieszaj oliwę, 2 przeciśnięte ząbki czosnku, sok z połowy cytryny i paprykę wędzoną. Obtocz krewetki w marynacie i odstaw na 15 minut.',
      'Cukinię pokrój w grube półplasterki, paprykę i cebulę w kwadraty. Nabijaj na patyczki na przemian z krewetkami.',
      'Kolby kukurydzy obgotuj 10 minut we wrzątku.',
      'Rozpal grill (węglowy, gazowy albo elektryczny) do średnio wysokiej temperatury. Grilluj kukurydzę 8 minut, obracając, a szaszłyki po 2–3 minuty z każdej strony, aż krewetki staną się różowe.',
      'Na patelni grillowej: rozgrzej ją mocno i smaż szaszłyki po 3 minuty z każdej strony.',
      'Wymieszaj jogurt grecki z resztą czosnku, posiekanym koperkiem i sokiem z cytryny. Podawaj szaszłyki z kukurydzą i sosem.',
    ],
    photo:
      'Grilled skewers of charred pink shrimp, zucchini, red pepper and red onion with grilled corn on the cob and a bowl of white garlic yogurt sauce with dill',
  },
  {
    plan: 'KO-048',
    title: 'Pizza na cienkim cieście z pieczarkami i szynką',
    description:
      'Domowa pizza na cienkim, chrupiącym cieście z sosem pomidorowym, mozzarellą, pieczarkami i szynką, wykończona świeżą rukolą. Lepsza od zamawianej i gotowa w godzinę.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['drożdże instant', 4, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['sól', 1, 'g'],
      ['passata pomidorowa', 100, 'ml'],
      ['oregano', 1, 'g'],
      ['mozzarella', 125, 'g'],
      ['pieczarka', 150, 'g'],
      ['szynka', 60, 'g'],
      ['rukola', 20, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z drożdżami i solą, dodaj oliwę i 130 ml ciepłej wody. Wyrabiaj 5 minut na gładkie ciasto i odstaw pod ściereczką na 30 minut.',
      'Nagrzej piekarnik do maksymalnej temperatury (250°C) razem z blachą.',
      'Pieczarki pokrój w cienkie plasterki, szynkę porwij na kawałki, mozzarellę odsącz i porwij.',
      'Rozwałkuj ciasto na cienki placek na papierze do pieczenia, posmaruj passatą wymieszaną z oregano.',
      'Rozłóż mozzarellę, pieczarki i szynkę, przełóż pizzę z papierem na gorącą blachę i piecz 10–12 minut, aż brzegi się zarumienią.',
      'Po wyjęciu posyp rukolą i od razu krój.',
    ],
    photo:
      'Thin crispy homemade pizza with tomato sauce, melted mozzarella, sliced mushrooms and torn ham, topped with fresh arugula on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'KO-049',
    title: 'Panzanella — sałatka z pomidorów i chleba',
    description:
      'Toskańska sałatka z dojrzałych pomidorów, ogórka, papryki i czerwonej cebuli z chrupiącymi kawałkami ciabatty, które piją sok z pomidorów, oliwę i ocet. Letnia kolacja z prostych produktów.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SALAD',
    seasons: ['SUMMER'],
    ingredients: [
      ['ciabatta', 150, 'g'],
      ['pomidor', 500, 'g'],
      ['ogórek', 150, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['bazylia', 15, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['ocet winny', 15, 'ml'],
      ['czosnek', 1, 'szt'],
      ['kapary', 10, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Ciabattę pokrój w kostkę 2 cm i podpraż na suchej patelni 6–8 minut, aż będzie chrupiąca.',
      'Pomidory pokrój w duże kawałki, przełóż do miski, posól i odstaw na 10 minut, żeby puściły sok.',
      'Ogórek pokrój w półplasterki, paprykę w kostkę, cebulę w cienkie piórka.',
      'Wymieszaj oliwę, ocet winny i przeciśnięty czosnek, polej pomidory razem z sokiem.',
      'Dodaj grzanki, warzywa, kapary i porwaną bazylię, wymieszaj i odstaw na 5 minut, aż chleb lekko nasiąknie.',
    ],
    photo:
      'Rustic salad of juicy red tomato chunks, toasted ciabatta cubes, cucumber, red pepper, thin red onion, capers and torn basil leaves glistening with olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'KO-050',
    title: 'Tarta z boczkiem i cebulą',
    description:
      'Kruchy spód wypełniony karmelizowaną cebulą, chrupiącym boczkiem i gładką masą jajeczno-śmietanową z gałką muszkatołową. Sycąca kolacja, która świetnie smakuje na zimno i nadaje się do pudełka.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['ciasto kruche', 150, 'g'],
      ['boczek', 70, 'g'],
      ['cebula', 220, 'g'],
      ['jajko', 2, 'szt'],
      ['śmietanka 18', 100, 'ml'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra–dół). Wyłóż kruchym ciastem małą formę do tarty (ok. 20 cm), nakłuj widelcem i podpiecz 12 minut.',
      'Boczek pokrój w paski i wytop na suchej patelni przez 4 minuty.',
      'Dodaj cebulę pokrojoną w piórka i smaż na małym ogniu 12–15 minut, aż się zeszkli i lekko skarmelizuje.',
      'Roztrzep jajka ze śmietanką, gałką muszkatołową, tymiankiem i pieprzem.',
      'Rozłóż cebulę z boczkiem na podpieczonym spodzie, zalej masą jajeczną i piecz 25 minut, aż środek się zetnie.',
      'Odstaw tartę na 10 minut przed krojeniem. Do pudełka pakuj po całkowitym ostudzeniu.',
    ],
    photo:
      'Slice of golden shortcrust tart filled with caramelized onion, crispy bacon bits and set creamy egg custard flecked with thyme',
  },
  {
    plan: 'KO-051',
    title: 'Zupa z zielonej soczewicy z marchewką i tymiankiem',
    description:
      'Gęsta zupa z zielonej soczewicy, marchewki, selera naciowego i pomidorów, doprawiona tymiankiem i liściem laurowym. Rozgrzewająca, sycąca kolacja na zimowe wieczory, w pełni roślinna.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    seasons: ['WINTER'],
    ingredients: [
      ['soczewica zielona', 150, 'g'],
      ['marchew', 200, 'g'],
      ['cebula', 110, 'g'],
      ['seler naciowy', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['tymianek suszony', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przepłucz soczewicę na sitku. Cebulę posiekaj, marchew pokrój w kostkę, seler naciowy w plasterki.',
      'W garnku rozgrzej oliwę i smaż cebulę, marchew i seler 6 minut, dodaj posiekany czosnek i tymianek na ostatnią minutę.',
      'Wsyp soczewicę, dodaj pomidory z puszki, liść laurowy i 1 l wody. Zagotuj.',
      'Gotuj pod przykryciem na małym ogniu 30–35 minut, aż soczewica będzie miękka.',
      'Usuń liść laurowy, dopraw solą i pieprzem. Podawaj posypaną posiekaną natką pietruszki.',
    ],
    photo:
      'Hearty brown-green lentil soup with orange carrot cubes, celery and tomato, garnished with fresh parsley and a sprig of thyme',
    vessel: 'bowl',
  },
  {
    plan: 'KO-052',
    title: 'Patatas bravas z jajkiem sadzonym',
    description:
      'Pieczone na chrupko kostki ziemniaków z pikantnym sosem pomidorowym z papryką wędzoną, podane z jajkami sadzonymi. Hiszpańska tapas zamieniona w pełną, sycącą kolację.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'POTATOES',
    equipment: ['OVEN'],
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['sól', 1.5, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 150, 'ml'],
      ['ocet winny', 5, 'ml'],
      ['jajko', 4, 'szt'],
      ['natka pietruszki', 5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C (termoobieg 200°C). Ziemniaki pokrój w kostkę 2–3 cm i gotuj 5 minut w osolonej wodzie, potem odcedź i osusz.',
      'Wymieszaj ziemniaki z 20 ml oliwy, połową papryki wędzonej i solą, rozłóż na blasze i piecz 30–35 minut, aż będą chrupiące.',
      'Na 5 ml oliwy zeszklij drobno posiekaną cebulę i czosnek, dodaj resztę papryki wędzonej i paprykę ostrą.',
      'Wlej passatę i ocet winny, gotuj 8 minut, aż sos zgęstnieje.',
      'Na końcu usmaż jajka sadzone na reszcie oliwy.',
      'Polej ziemniaki sosem, połóż na nich jajka i posyp natką.',
    ],
    photo:
      'Crispy golden roasted potato cubes drizzled with spicy red smoked paprika tomato sauce, topped with two sunny-side-up eggs and chopped parsley',
  },
  {
    plan: 'KO-053',
    title: 'Salmorejo z jajkiem i szynką',
    description:
      'Gęsty, aksamitny chłodnik z Andaluzji z dojrzałych pomidorów, chleba, czosnku i oliwy, podany z jajkiem na twardo i paskami szynki dojrzewającej. Orzeźwiająca kolacja na upalne wieczory.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'SOUP',
    seasons: ['SUMMER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['pomidor', 800, 'g'],
      ['bagietka', 80, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 40, 'ml'],
      ['ocet winny', 10, 'ml'],
      ['jajko', 2, 'szt'],
      ['szynka dojrzewająca', 40, 'g'],
    ],
    steps: [
      'Jajka gotuj na twardo przez 10 minut, przelej zimną wodą i obierz.',
      'Pomidory pokrój na ćwiartki, bagietkę porwij na kawałki.',
      'Zmiksuj pomidory w blenderze na gładko, dodaj bagietkę, czosnek i ocet i odstaw na 5 minut, żeby chleb namókł.',
      'Miksuj ponownie, powoli wlewając 30 ml oliwy, aż krem będzie gęsty i aksamitny. Schłodź w lodówce co najmniej 10 minut.',
      'Podawaj w miseczkach, posypane posiekanym jajkiem i paskami szynki, skropione resztą oliwy.',
    ],
    photo:
      'Thick velvety orange-red cold tomato soup topped with chopped hard-boiled egg, thin strips of cured ham and a drizzle of olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'KO-054',
    title: 'Halloumi z grilla z sałatką z arbuza',
    description:
      'Grillowany ser halloumi z brązowymi paskami podany z sałatką z soczystego arbuza, ogórka, czerwonej cebuli, mięty i prażonych pestek dyni. Słono-słodkie połączenie na letnie wieczory przy grillu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'SALAD',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['ser halloumi', 140, 'g'],
      ['arbuz', 400, 'g'],
      ['ogórek', 150, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['mięta', 5, 'g'],
      ['rukola', 40, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['limonka', 30, 'g'],
      ['pestki dyni', 20, 'g'],
    ],
    steps: [
      'Arbuz pokrój w kostkę, ogórek w półplasterki, cebulę w cienkie piórka. Pestki dyni upraż na suchej patelni.',
      'Halloumi pokrój w plastry grubości 1 cm i posmaruj cienko połową oliwy.',
      'Rozgrzej grill (węglowy, gazowy albo elektryczny) i grilluj ser po 2 minuty z każdej strony, aż pojawią się brązowe paski.',
      'Na patelni grillowej: rozgrzej ją mocno i smaż halloumi po 1–2 minuty z każdej strony.',
      'Wymieszaj arbuza, ogórek, cebulę i rukolę z resztą oliwy i sokiem z limonki. Ułóż na wierzchu gorący halloumi, posyp miętą i pestkami dyni.',
    ],
    photo:
      'Golden grill-marked halloumi slices on a salad of juicy red watermelon cubes, cucumber, thin red onion, arugula, fresh mint leaves and toasted pumpkin seeds',
  },
  {
    plan: 'KO-055',
    title: 'Pakory warzywne z raitą',
    description:
      'Chrupiące kawałki cebuli, kalafiora i szpinaku w pikantnym cieście z mąki z ciecierzycy z garam masalą, podane z chłodzącą raitą z jogurtu, ogórka i mięty. Indyjski street food na kolację.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'PANCAKES',
    ingredients: [
      ['mąka z ciecierzycy', 120, 'g'],
      ['cebula', 150, 'g'],
      ['kalafior', 200, 'g'],
      ['szpinak', 60, 'g'],
      ['papryczka chili', 10, 'g'],
      ['garam masala', 3, 'g'],
      ['kurkuma', 2, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['sól', 1.5, 'g'],
      ['olej rzepakowy', 40, 'ml'],
      ['jogurt naturalny', 200, 'g'],
      ['ogórek', 150, 'g'],
      ['mięta', 5, 'g'],
      ['czosnek', 1, 'szt'],
    ],
    steps: [
      'Przygotuj raitę: zetrzyj ogórek, odciśnij sok i wymieszaj go z jogurtem, przeciśniętym czosnkiem i posiekaną miętą. Wstaw do lodówki.',
      'Cebulę pokrój w cienkie piórka, kalafior w bardzo małe różyczki, szpinak posiekaj, chili drobno pokrój.',
      'W misce wymieszaj mąkę z ciecierzycy z garam masalą, kurkumą, kminem i solą, dodaj ok. 100 ml wody i wymieszaj na gęste ciasto.',
      'Wmieszaj warzywa, tak żeby każdy kawałek był oblepiony ciastem.',
      'Na patelni rozgrzej olej na wysokość ok. 0,5 cm. Nakładaj łyżką niewielkie kupki ciasta i smaż partiami po 3 minuty z każdej strony na złoty kolor.',
      'Odsącz pakory na ręczniku papierowym i podawaj gorące z raitą.',
    ],
    photo:
      'Pile of crispy golden-orange vegetable pakoras with visible onion and cauliflower pieces next to a bowl of creamy white cucumber mint raita',
  },
  {
    plan: 'KO-056',
    title: 'Tostadas z fasolą, awokado i fetą',
    description:
      'Chrupiące, zapieczone tortille kukurydziane z pastą z czarnej fasoli z kminem, awokado, pomidorem, sałatą i pokruszoną fetą. Meksykańska kolacja pełna tekstur i świeżych smaków.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    equipment: ['OVEN'],
    ingredients: [
      ['tortilla kukurydziana', 6, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['fasola czarna z puszki', 240, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['awokado', 1, 'szt'],
      ['ser feta', 60, 'g'],
      ['pomidor', 150, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['sałata lodowa', 60, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Tortille posmaruj cienko olejem z obu stron i piecz na blasze 8–10 minut, aż będą chrupiące.',
      'Fasolę odsącz, podgrzej w rondelku z kminem i 2 łyżkami wody, a potem rozgnieć widelcem na gęstą pastę.',
      'Awokado rozgnieć z połową soku z limonki. Pomidor pokrój w kostkę, cebulę posiekaj drobno, sałatę poszatkuj.',
      'Na każdą tostadę nałóż pastę z fasoli, awokado, sałatę, pomidor i cebulę.',
      'Posyp pokruszoną fetą i kolendrą, skrop resztą soku z limonki i podawaj od razu.',
    ],
    photo:
      'Crispy corn tostadas layered with black bean spread, mashed avocado, shredded lettuce, diced tomato, red onion, crumbled white feta and cilantro',
  },
  {
    plan: 'KO-057',
    title: 'Kanapka z kurczakiem BBQ i coleslawem',
    description:
      'Miękka bułka z szarpanym kurczakiem w sosie barbecue i chrupiącą surówką coleslaw z kapusty i marchewki. Amerykańska kanapka na sycącą kolację, zrobiona w domu w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['bułka do hamburgera', 150, 'g'],
      ['filet z kurczaka', 250, 'g'],
      ['sos barbecue', 40, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka wędzona mielona', 2, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['kapusta biała', 150, 'g'],
      ['marchew', 75, 'g'],
      ['majonez', 20, 'g'],
      ['jogurt naturalny', 40, 'g'],
      ['ocet jabłkowy', 5, 'ml'],
    ],
    steps: [
      'Przygotuj coleslaw: kapustę poszatkuj bardzo cienko, marchew zetrzyj, wymieszaj z majonezem, jogurtem i octem jabłkowym. Odstaw na 15 minut.',
      'Filet z kurczaka natrzyj papryką wędzoną i czosnkiem granulowanym.',
      'Smaż kurczaka na rozgrzanym oleju po 5–6 minut z każdej strony, aż będzie upieczony w środku.',
      'Rozszarp mięso dwoma widelcami, wymieszaj z sosem barbecue i podgrzewaj minutę na patelni.',
      'Przekrój bułki i opiecz je krótko na suchej patelni. Nałóż kurczaka BBQ, na wierzch coleslaw i przykryj drugą połówką.',
    ],
    photo:
      'Soft burger bun filled with glossy shredded barbecue chicken and creamy white cabbage and carrot coleslaw, served on a wooden board',
    vessel: 'board',
  },
  {
    plan: 'KO-058',
    title: 'Kurczak z ananasem i orzeszkami po tajsku z ryżem',
    description:
      'Kawałki kurczaka smażone z ananasem, papryką i cebulą w słodko-kwaśnym sosie z limonki, sosu rybnego i chili, posypane prażonymi orzeszkami. Tajska kolacja z woka podana z ryżem jaśminowym.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'GRAINS',
    ingredients: [
      ['ryż jaśminowy', 140, 'g'],
      ['filet z kurczaka', 300, 'g'],
      ['ananas', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula', 110, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos rybny', 10, 'ml'],
      ['sos chili słodki', 20, 'g'],
      ['limonka', 30, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['orzeszek ziemny', 30, 'g'],
      ['cebula dymka', 20, 'g'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Przepłucz ryż jaśminowy i ugotuj go pod przykryciem w 250 ml wody przez 12 minut, potem odstaw na 5 minut.',
      'Kurczaka pokrój w kostkę, ananasa obierz i pokrój w kawałki, paprykę i cebulę w kwadraty, czosnek i imbir posiekaj.',
      'Orzeszki upraż na suchym woku i odłóż.',
      'Rozgrzej olej w woku i smaż kurczaka 5 minut na dużym ogniu. Dodaj cebulę, paprykę, czosnek i imbir, smaż 3 minuty.',
      'Wrzuć ananasa, wlej sos rybny, sos chili słodki i sok z limonki, smaż 2 minuty, aż sos oblepi składniki.',
      'Podawaj z ryżem, posypane orzeszkami, dymką i kolendrą.',
    ],
    photo:
      'Stir-fried chicken pieces with golden pineapple chunks, red pepper and onion in glossy sweet chili sauce, topped with roasted peanuts and spring onion, beside jasmine rice',
  },
];
