/**
 * Katalog 1000 — część KO-c: kolacje KO-059 … KO-087 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'KO-059',
    title: 'Chana chaat — sałatka z ciecierzycy po indyjsku',
    description:
      'Indyjska uliczna sałatka z ciecierzycy i gotowanych ziemniaków z pomidorem, czerwoną cebulą, ogórkiem, kolendrą i pestkami granatu, doprawiona kminem, garam masalą i limonką. Świeża, pikantna i lekka kolacja bez gotowania na długo.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'SALAD',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ciecierzyca z puszki', 400, 'g'],
      ['ziemniak', 200, 'g'],
      ['pomidor', 200, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['ogórek', 150, 'g'],
      ['granat', 60, 'g'],
      ['kolendra', 10, 'g'],
      ['limonka', 30, 'g'],
      ['papryczka chili', 10, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['garam masala', 2, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Ziemniaki umyj i ugotuj w mundurkach 20 minut do miękkości. Ostudź, obierz i pokrój w kostkę 1 cm.',
      'W tym czasie odcedź i przepłucz ciecierzycę. Kmin rzymski upraż na suchej patelni przez 1 minutę, aż zapachnie.',
      'Pomidor i ogórek pokrój w drobną kostkę, cebulę i papryczkę chili posiekaj drobno, a z granatu wyłuskaj pestki.',
      'W dużej misce wymieszaj ciecierzycę, ziemniaki i warzywa. Dopraw kminem, garam masalą, solą i sokiem z limonki.',
      'Posyp posiekaną kolendrą i pestkami granatu, odstaw na 5 minut, żeby smaki się przegryzły.',
    ],
    photo:
      'Colorful chickpea salad with diced boiled potato, tomato, cucumber, red onion, bright ruby pomegranate seeds and fresh cilantro leaves',
    vessel: 'bowl',
  },
  {
    plan: 'KO-060',
    title: 'Piadina z szynką, rukolą i mozzarellą',
    description:
      'Cienkie włoskie placki z mąki i oliwy, pieczone na suchej patelni i złożone z szynką dojrzewającą, mozzarellą, pomidorem i rukolą. Szybka kolacja z Emilii-Romanii, która robi się sama w pół godziny, bez drożdży i czekania.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['sól', 0.5, 'g'],
      ['szynka dojrzewająca', 40, 'g'],
      ['mozzarella', 125, 'g'],
      ['pomidor', 150, 'g'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z solą, oliwą i około 100 ml ciepłej wody, zagnieć gładkie, elastyczne ciasto przez 3 minuty i odstaw pod miską na 10 minut.',
      'W tym czasie pokrój mozzarellę i pomidor w plastry, rukolę opłucz i osusz.',
      'Podziel ciasto na 2 części i rozwałkuj każdą na cienki placek o średnicy 25 cm.',
      'Rozgrzej suchą patelnię i piecz placki po 2 minuty z każdej strony, aż pojawią się brązowe plamki.',
      'Na połowie każdej ciepłej piadiny ułóż mozzarellę, pomidor, szynkę i rukolę, oprósz pieprzem, złóż na pół i od razu podawaj.',
    ],
    photo:
      'Folded warm Italian flatbread with brown toasted spots, filled with thin prosciutto slices, melting mozzarella, tomato slices and fresh arugula',
    vessel: 'board',
  },
  {
    plan: 'KO-061',
    title: 'Szparagi z jajkiem w koszulce i sosem holenderskim',
    description:
      'Zielone szparagi ugotowane al dente, podane z jajkiem w koszulce i aksamitnym sosem holenderskim na maśle i cytrynie. Klasyka wiosennej kuchni, elegancka, a gotowa w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    seasons: ['SPRING'],
    ingredients: [
      ['szparagi', 500, 'g'],
      ['jajko', 4, 'szt'],
      ['żółtko', 1, 'szt'],
      ['masło', 60, 'g'],
      ['cytryna', 15, 'g'],
      ['ocet winny', 10, 'ml'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Odłam zdrewniałe końcówki szparagów. Gotuj je w osolonej wodzie 4–5 minut, aż będą miękkie, ale jędrne, i odcedź.',
      'Masło roztop w rondelku. Żółtko ubij w metalowej misce nad garnkiem z gotującą się wodą z sokiem z cytryny i łyżką wody przez 3 minuty, aż zgęstnieje.',
      'Wlewaj do żółtka cienką strużką ciepłe masło, cały czas ubijając, aż sos będzie gęsty i lśniący. Dopraw pieprzem.',
      'W szerokim garnku zagotuj wodę z octem, zmniejsz ogień, zamieszaj wir i wpuść po jednym 4 jajka. Gotuj 3 minuty i wyjmij łyżką cedzakową.',
      'Ułóż szparagi na talerzach, na nich jajka w koszulce, polej sosem holenderskim i posyp posiekanym szczypiorkiem.',
    ],
    photo:
      'Bright green asparagus spears topped with two soft poached eggs, covered with glossy pale yellow hollandaise sauce and chopped chives',
  },
  {
    plan: 'KO-062',
    title: 'Zupa krem z młodego groszku z miętą',
    description:
      'Aksamitny, intensywnie zielony krem z groszku z odrobiną mleka kokosowego, świeżą miętą i cytryną, posypany prażonymi pestkami dyni. Wiosenna, roślinna kolacja gotowa w pół godziny.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    seasons: ['SPRING'],
    equipment: ['BLENDER'],
    ingredients: [
      ['groszek mrożony', 450, 'g'],
      ['ziemniak', 150, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['mleko kokosowe z puszki', 80, 'ml'],
      ['mięta', 10, 'g'],
      ['cytryna', 10, 'g'],
      ['pestki dyni', 20, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, ziemniak obierz i pokrój w drobną kostkę.',
      'Rozgrzej oliwę w garnku i zeszklij cebulę z czosnkiem przez 4 minuty. Dodaj ziemniak, wlej 700 ml wody, posól i gotuj 12 minut.',
      'Wsyp groszek i gotuj jeszcze 5 minut, krótko, żeby zachował jasnozielony kolor.',
      'Zdejmij garnek z ognia, dodaj listki mięty i mleko kokosowe, zmiksuj blenderem na gładki krem. Dopraw sokiem z cytryny i pieprzem.',
      'Pestki dyni upraż na suchej patelni przez 2–3 minuty i posyp nimi zupę w miskach.',
    ],
    photo:
      'Vivid green smooth pea soup with a swirl of coconut milk, fresh mint leaves and toasted pumpkin seeds on top',
    vessel: 'bowl',
  },
  {
    plan: 'KO-063',
    title: 'Szparagi zapiekane z szynką i serem',
    description:
      'Zielone szparagi zawinięte w plastry szynki, zapiekane pod kołderką z sera i śmietany, aż ser się zezłoci. Wiosenna kolacja z piekarnika na niskich węglowodanach, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    seasons: ['SPRING'],
    equipment: ['OVEN'],
    ingredients: [
      ['szparagi', 500, 'g'],
      ['szynka', 90, 'g'],
      ['ser żółty', 70, 'g'],
      ['śmietana 18', 60, 'g'],
      ['masło', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Odłam zdrewniałe końcówki szparagów i blanszuj je 3 minuty we wrzątku, potem odcedź.',
      'Naczynie żaroodporne posmaruj masłem. Zawiń po 2–3 szparagi w plaster szynki i ułóż ciasno w naczyniu.',
      'Wymieszaj śmietanę z przeciśniętym czosnkiem i pieprzem, polej nią szparagi i posyp startym serem żółtym.',
      'Zapiekaj 12–15 minut, aż ser się roztopi i zezłoci. Podawaj od razu.',
    ],
    photo:
      'Baking dish of green asparagus bundles wrapped in pink ham slices under a bubbling golden melted cheese crust',
  },
  {
    plan: 'KO-064',
    title: 'Bób z masłem i koperkiem',
    description:
      'Młody bób ugotowany do miękkości i obtoczony w roztopionym maśle z czosnkiem i świeżym koperkiem. Letni klasyk na szybką kolację, sycący dzięki roślinnemu białku.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SUMMER'],
    ingredients: [
      ['bób', 800, 'g'],
      ['masło', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['koperek', 15, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zagotuj w dużym garnku 2 litry wody z solą.',
      'Wrzuć bób i gotuj 12–15 minut, aż ziarna będą miękkie; młody bób wystarczy 10 minut.',
      'W tym czasie posiekaj koperek, a czosnek przeciśnij przez praskę.',
      'Odcedź bób, a w tym samym garnku roztop masło z czosnkiem przez 1 minutę. Wsyp bób, dodaj koperek i pieprz, wymieszaj i podawaj na ciepło.',
    ],
    photo:
      'Bowl of glossy green boiled broad beans coated in melted butter with plenty of chopped fresh dill',
    vessel: 'bowl',
  },
  {
    plan: 'KO-065',
    title: 'Młode ziemniaki pieczone z czosnkiem i sosem ziołowym',
    description:
      'Młode ziemniaki pieczone w skórce z czosnkiem i rozmarynem, aż będą chrupiące z zewnątrz i kremowe w środku, podane z gęstym jogurtowym sosem z koperkiem, szczypiorkiem i natką. Smak lata na talerzu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'POTATOES',
    seasons: ['SUMMER'],
    equipment: ['OVEN'],
    ingredients: [
      ['ziemniak młody', 900, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['czosnek', 4, 'szt'],
      ['rozmaryn suszony', 1, 'g'],
      ['jogurt grecki', 200, 'g'],
      ['koperek', 10, 'g'],
      ['szczypiorek', 10, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C. Młode ziemniaki wyszoruj szczoteczką i przekrój większe na pół.',
      'Wymieszaj ziemniaki z oliwą, rozmarynem, solą i pieprzem, dodaj 3 nieobrane, zgniecione ząbki czosnku i rozłóż na blasze.',
      'Piecz 30–35 minut, raz przewracając, aż ziemniaki będą złote i miękkie w środku.',
      'W tym czasie posiekaj koperek, szczypiorek i natkę, wymieszaj z jogurtem greckim i ostatnim, przeciśniętym ząbkiem czosnku.',
      'Podawaj gorące ziemniaki z sosem ziołowym; upieczony czosnek wyciśnij ze skórki na ziemniaki.',
    ],
    photo:
      'Golden roasted baby potatoes with crispy skins and whole roasted garlic cloves, served with a bowl of thick white yogurt herb sauce flecked with dill and chives',
  },
  {
    plan: 'KO-066',
    title: 'Kalafior z bułką tartą i masłem',
    description:
      'Cały kalafior ugotowany na miękko i polany zrumienioną na maśle bułką tartą z posiekanym jajkiem i koperkiem, czyli kalafior po polsku. Prosta, letnia kolacja, którą uwielbiają dzieci i dorośli.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SUMMER'],
    ingredients: [
      ['kalafior', 800, 'g'],
      ['masło', 40, 'g'],
      ['bułka tarta', 40, 'g'],
      ['jajko', 2, 'szt'],
      ['koperek', 5, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Jajka ugotuj na twardo przez 10 minut, przełóż do zimnej wody, obierz i posiekaj drobno.',
      'Kalafior podziel na duże różyczki albo zostaw w całości. Gotuj w osolonej wodzie 10–12 minut, aż będzie miękki, ale nie rozpadający się, i odcedź.',
      'Na patelni roztop masło, wsyp bułkę tartą i praż na średnim ogniu 3–4 minuty, mieszając, aż się zezłoci.',
      'Zdejmij patelnię z ognia i wmieszaj posiekane jajka oraz koperek.',
      'Ułóż kalafior na talerzach i obficie posyp go masłem z bułką tartą.',
    ],
    photo:
      'Whole boiled white cauliflower topped with golden buttery toasted breadcrumbs, chopped hard-boiled egg and fresh dill',
  },
  {
    plan: 'KO-067',
    title: 'Omlet z młodymi warzywami i koperkiem',
    description:
      'Puszysty omlet na oliwie z młodą cukinią, groszkiem, marchewką i dymką, obsypany świeżym koperkiem. Letnia kolacja w kwadrans, lekka, bez nabiału i bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    seasons: ['SUMMER'],
    ingredients: [
      ['jajko', 6, 'szt'],
      ['cukinia', 150, 'g'],
      ['groszek', 100, 'g'],
      ['marchew', 80, 'g'],
      ['cebula dymka', 40, 'g'],
      ['koperek', 10, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Marchewkę zetrzyj na tarce o dużych oczkach, cukinię pokrój w drobną kostkę, dymkę posiekaj razem ze szczypiorem.',
      'Rozgrzej połowę oliwy na patelni i smaż marchew, cukinię, groszek i dymkę przez 5 minut, aż zmiękną.',
      'Roztrzep jajka z solą, pieprzem i większością posiekanego koperku.',
      'Przełóż połowę warzyw na talerz. Dolej na patelnię resztę oliwy, wlej połowę jajek na warzywa i smaż pod przykryciem na małym ogniu 4–5 minut, aż wierzch się zetnie. Tak samo usmaż drugi omlet.',
      'Złóż omlety na pół i posyp resztą koperku.',
    ],
    photo:
      'Fluffy golden folded omelette filled with diced zucchini, green peas, grated carrot and spring onion, sprinkled with fresh dill',
  },
  {
    plan: 'KO-068',
    title: 'Placki ziemniaczane z sosem grzybowym',
    description:
      'Chrupiące placki ziemniaczane usmażone na złoto, polane gęstym sosem z pieczarek i suszonych grzybów leśnych ze śmietaną. Jesienny, rozgrzewający klasyk, który pachnie całym domem.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DUMPLINGS',
    seasons: ['AUTUMN'],
    ingredients: [
      ['ziemniak', 800, 'g'],
      ['cebula', 150, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 40, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['pieczarka', 250, 'g'],
      ['grzyb suszony', 10, 'g'],
      ['masło', 15, 'g'],
      ['śmietana 18', 100, 'g'],
      ['majeranek', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Suszone grzyby zalej 150 ml wrzątku i odstaw na 20 minut, potem odsącz, zachowując wywar, i posiekaj.',
      'Pieczarki pokrój w plasterki, a 100 g cebuli w kostkę. Podsmaż je na maśle przez 8 minut, dodaj suszone grzyby z wywarem i duś 5 minut. Zdejmij z ognia, wmieszaj śmietanę, dopraw połową soli i pieprzem, podgrzej, nie gotując.',
      'Ziemniaki obierz i zetrzyj na drobnej tarce razem z resztą cebuli, odlej nadmiar soku.',
      'Wymieszaj masę z jajkiem, mąką, majerankiem, resztą soli i pieprzem.',
      'Rozgrzej olej na dużej patelni, nakładaj łyżką porcje ciasta, spłaszczaj i smaż placki po 3–4 minuty z każdej strony, aż będą złote i chrupiące. Odsącz na ręczniku papierowym.',
      'Podawaj placki od razu, polane gorącym sosem grzybowym.',
    ],
    photo:
      'Crispy golden potato pancakes smothered with creamy beige mushroom sauce with sliced champignons and bits of dark forest mushrooms',
  },
  {
    plan: 'KO-069',
    title: 'Sałatka z jarmużem, jabłkiem i orzechami',
    description:
      'Wymasowany jarmuż z chrupiącym jabłkiem, ciecierzycą, prażonymi orzechami włoskimi i suszoną żurawiną, polany winegretem z musztardą i syropem klonowym. Jesienna, roślinna sałatka, która dobrze znosi drogę w pudełku.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    seasons: ['AUTUMN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['jarmuż', 150, 'g'],
      ['jabłko', 200, 'g'],
      ['ciecierzyca z puszki', 200, 'g'],
      ['orzech włoski', 40, 'g'],
      ['żurawina suszona', 20, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ocet jabłkowy', 10, 'ml'],
      ['musztarda', 5, 'g'],
      ['syrop klonowy', 10, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Jarmuż opłucz, oberwij liście z twardych łodyg i porwij na mniejsze kawałki.',
      'Wymieszaj oliwę, ocet jabłkowy, musztardę, syrop klonowy i sól. Polej jarmuż połową sosu i masuj dłońmi 2 minuty, aż liście zmiękną i ściemnieją.',
      'Orzechy włoskie upraż na suchej patelni przez 3 minuty i połam. Ciecierzycę odcedź i przepłucz.',
      'Jabłko pokrój w cienkie plasterki, a cebulę w piórka.',
      'Dodaj do jarmużu jabłko, cebulę, ciecierzycę i żurawinę, polej resztą sosu, wymieszaj i posyp orzechami.',
    ],
    photo:
      'Dark green massaged kale salad with thin apple slices, chickpeas, red onion, toasted walnuts and ruby dried cranberries',
    vessel: 'bowl',
  },
  {
    plan: 'KO-070',
    title: 'Sałatka z pieczonych buraków, pomarańczy i fety',
    description:
      'Słodkie pieczone buraki z soczystą pomarańczą, słoną fetą, roszponką i orzechami włoskimi, polane miodowym winegretem balsamicznym. Kolorowa, zimowa sałatka, która cieszy oko w najciemniejsze wieczory.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SALAD',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['burak', 500, 'g'],
      ['pomarańcza', 1, 'szt'],
      ['ser feta', 80, 'g'],
      ['roszponka', 50, 'g'],
      ['orzech włoski', 30, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['miód', 10, 'g'],
      ['ocet balsamiczny', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Buraki umyj, zawiń każdy w folię aluminiową i piecz 45–50 minut, aż nóż wejdzie gładko.',
      'Ostudź buraki, obierz i pokrój w ósemki.',
      'Pomarańczę obierz ze skórki i białej błonki, pokrój w plastry lub cząstki. Orzechy upraż na suchej patelni 3 minuty.',
      'Wymieszaj oliwę, miód, ocet balsamiczny i pieprz na winegret.',
      'Na talerzach rozłóż roszponkę, buraki i pomarańczę, pokrusz fetę, posyp orzechami i polej winegretem.',
    ],
    photo:
      'Deep magenta roasted beet wedges with bright orange slices, crumbled white feta, lamb lettuce and toasted walnuts with a glossy balsamic drizzle',
  },
  {
    plan: 'KO-071',
    title: 'Zupa krem z pietruszki z grzankami',
    description:
      'Kremowa, lekko słodka zupa z korzenia pietruszki i ziemniaków ze śmietanką i szczyptą gałki muszkatołowej, podana z chrupiącymi grzankami z bagietki. Rozgrzewająca zimowa kolacja z najprostszych warzyw.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['WINTER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['pietruszka korzeń', 400, 'g'],
      ['ziemniak', 200, 'g'],
      ['cebula', 80, 'g'],
      ['masło', 20, 'g'],
      ['śmietanka 18', 80, 'ml'],
      ['bagietka', 80, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['gałka muszkatołowa', 1, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pietruszkę i ziemniaki obierz i pokrój w plastry, cebulę posiekaj.',
      'Roztop masło w garnku i zeszklij cebulę przez 3 minuty. Dodaj pietruszkę i ziemniaki, smaż 3 minuty, wlej 800 ml wody, posól i gotuj pod przykryciem 20 minut.',
      'Zmiksuj zupę blenderem na gładki krem, wlej śmietankę, dopraw gałką muszkatołową i pieprzem, podgrzej, nie gotując.',
      'Bagietkę pokrój w kostkę, skrop oliwą i praż na suchej patelni 4–5 minut, aż grzanki będą złote i chrupiące.',
      'Nalej zupę do misek, posyp grzankami i posiekaną natką.',
    ],
    photo:
      'Smooth ivory parsley root cream soup topped with golden crunchy bread croutons, a swirl of cream and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'KO-072',
    title: 'Pieczone ziemniaki z twarożkiem i kiszonym ogórkiem',
    description:
      'Rumiane ćwiartki ziemniaków z piekarnika z puszystym twarożkiem ze szczypiorkiem i rzodkiewką oraz chrupiącym ogórkiem kiszonym. Swojska, sycąca kolacja na zimowy wieczór, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'POTATOES',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['ziemniak', 800, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['ser twaróg półtłusty', 200, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['ogórek kiszony', 120, 'g'],
      ['rzodkiewka', 80, 'g'],
      ['szczypiorek', 10, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C. Ziemniaki wyszoruj i pokrój wzdłuż na ćwiartki.',
      'Wymieszaj ziemniaki z oliwą, papryką, solą i pieprzem, rozłóż skórką do dołu na blasze z papierem i piecz 30–35 minut, aż się zrumienią.',
      'Twaróg rozgnieć widelcem z jogurtem naturalnym na puszystą masę. Wmieszaj posiekany szczypiorek i drobno pokrojoną rzodkiewkę, dopraw pieprzem.',
      'Ogórki kiszone pokrój w plastry lub słupki.',
      'Podawaj gorące ziemniaki z twarożkiem i ogórkiem kiszonym.',
    ],
    photo:
      'Golden roasted potato wedges with a dollop of white cottage cheese mixed with chives and radish, and sliced green pickled cucumbers on the side',
  },
  {
    plan: 'KO-073',
    title: 'Tosty z kurczakiem i serem',
    description:
      'Chrupiące tosty z pieczoną piersią z kurczaka, mozzarellą, pomidorem i szpinakiem, zapiekane w airfryerze bez grama masła. Szybka, białkowa kolacja, która smakuje jak z budki, a jest dużo lżejsza.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['filet z kurczaka', 250, 'g'],
      ['chleb tostowy', 160, 'g'],
      ['mozzarella', 80, 'g'],
      ['pomidor', 120, 'g'],
      ['szpinak', 30, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['oregano', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filet z kurczaka przekrój poziomo na cienkie kotlety, natrzyj oliwą, papryką, oregano i pieprzem.',
      'Piecz kurczaka w airfryerze w 190°C przez 10–12 minut, obracając w połowie. Odstaw na 2 minuty i pokrój w plastry.',
      'Mozzarellę i pomidor pokrój w plastry. Na połowie kromek chleba ułóż szpinak, kurczaka, pomidor i mozzarellę, przykryj resztą kromek.',
      'Opiekaj tosty w airfryerze w 180°C przez 5–6 minut, aż pieczywo będzie złote, a ser się roztopi. W piekarniku: piecz kurczaka w 200°C przez 18–20 minut, a tosty 8–10 minut z termoobiegiem.',
      'Przekrój tosty na trójkąty i podawaj od razu.',
    ],
    photo:
      'Golden toasted sandwich triangles filled with sliced grilled chicken breast, melting mozzarella, tomato and green spinach leaves',
    vessel: 'board',
  },
  {
    plan: 'KO-074',
    title: 'Kotleciki z cukinii z dipem jogurtowym',
    description:
      'Chrupiące kotleciki z tartej cukinii, fety i koperku, zapieczone w airfryerze na złoto i podane z chłodnym dipem z jogurtu greckiego z czosnkiem. Letnie danie na sezon cukinii, lżejsze niż smażone placki.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    seasons: ['SUMMER'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['cukinia', 600, 'g'],
      ['jajko', 2, 'szt'],
      ['bułka tarta', 50, 'g'],
      ['ser feta', 80, 'g'],
      ['koperek', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['jogurt grecki', 150, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cukinię zetrzyj na tarce o dużych oczkach, odstaw na 10 minut i mocno odciśnij z soku w ściereczce.',
      'Wymieszaj cukinię z jajkami, bułką tartą, pokruszoną fetą, połową koperku, 1 przeciśniętym ząbkiem czosnku i pieprzem. Uformuj 8 płaskich kotlecików.',
      'Posmaruj kosz airfryera i kotleciki olejem, piecz w 190°C przez 14–16 minut, obracając w połowie, aż będą złote. W piekarniku: 200°C, termoobieg, 20–25 minut na blasze z papierem.',
      'Wymieszaj jogurt grecki z resztą koperku i drugim przeciśniętym ząbkiem czosnku.',
      'Podawaj ciepłe kotleciki z dipem jogurtowym.',
    ],
    photo:
      'Golden crispy zucchini fritters flecked with green zucchini and dill, served with a bowl of thick white garlic yogurt dip',
  },
  {
    plan: 'KO-075',
    title: 'Pierożki z ciasta francuskiego z mięsem',
    description:
      'Chrupiące, złote pierożki z ciasta francuskiego z soczystym farszem z mięsa mielonego, cebuli i majeranku, upieczone w airfryerze. Podane ze świeżą sałatką z pomidora i ogórka to sycąca, domowa kolacja.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ciasto francuskie', 275, 'g'],
      ['wieprzowina mielona chuda', 200, 'g'],
      ['cebula', 80, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['majeranek', 2, 'g'],
      ['jajko', 1, 'szt'],
      ['olej rzepakowy', 5, 'ml'],
      ['pomidor', 200, 'g'],
      ['ogórek', 150, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę posiekaj i zeszklij na oleju przez 3 minuty. Dodaj mięso i smaż 7–8 minut, rozbijając grudki, aż się zrumieni. Wmieszaj koncentrat, majeranek i pieprz, ostudź.',
      'Ciasto francuskie rozwiń i pokrój na 8 kwadratów. Na każdy nałóż łyżkę farszu, złóż w trójkąt i dociśnij brzegi widelcem.',
      'Posmaruj pierożki roztrzepanym jajkiem i ponakłuwaj wierzch.',
      'Piecz w airfryerze w 180°C przez 12–14 minut, partiami, aż będą złote i wyrośnięte. W piekarniku: 200°C, termoobieg, 18–20 minut na blasze z papierem.',
      'Pomidor i ogórek pokrój w plastry i podawaj jako sałatkę do ciepłych pierożków.',
    ],
    photo:
      'Golden flaky puff pastry triangles with fork-crimped edges, one cut open to show savory minced meat filling, with fresh tomato and cucumber slices',
  },
  {
    plan: 'KO-076',
    title: 'Kotlety z kaszy gryczanej',
    description:
      'Sycące kotlety z kaszy gryczanej, podsmażonych pieczarek, cebuli i sera, z chrupiącą panierką, upieczone w airfryerze bez głębokiego smażenia. Podane z jogurtowym sosem koperkowym to pełnowartościowa, bezmięsna kolacja.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['kasza gryczana', 120, 'g'],
      ['pieczarka', 150, 'g'],
      ['cebula', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['ser żółty', 40, 'g'],
      ['bułka tarta', 40, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['majeranek', 1, 'g'],
      ['jogurt naturalny', 150, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę gryczaną ugotuj w 250 ml osolonej wody pod przykryciem przez 15 minut i lekko ostudź.',
      'Cebulę i pieczarki posiekaj drobno, podsmaż na 5 ml oleju przez 7 minut, aż odparują.',
      'Wymieszaj kaszę z pieczarkami, jajkami, startym serem, majerankiem i pieprzem, lekko rozgnieć tłuczkiem, żeby masa się kleiła. Uformuj 6 kotletów i obtocz je w bułce tartej.',
      'Posmaruj kotlety resztą oleju i piecz w airfryerze w 190°C przez 15 minut, obracając w połowie. W piekarniku: 200°C, termoobieg, 20–25 minut na blasze z papierem.',
      'Wymieszaj jogurt z posiekanym koperkiem i podawaj do kotletów.',
    ],
    photo:
      'Golden breaded buckwheat patties with visible grains and mushroom bits, served with a white yogurt dill sauce',
  },
  {
    plan: 'KO-077',
    title: 'Kalafior w panierce z ostrym sosem',
    description:
      'Różyczki kalafiora w chrupiącej panierce z bułki tartej i wędzonej papryki, upieczone w airfryerze i polane ostrym maślanym sosem sriracha, z chłodnym dipem jogurtowym. Bezmięsna wersja skrzydełek buffalo.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['kalafior', 700, 'g'],
      ['mąka pszenna', 60, 'g'],
      ['mleko', 120, 'ml'],
      ['bułka tarta', 60, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sos sriracha', 30, 'g'],
      ['masło', 20, 'g'],
      ['miód', 10, 'g'],
      ['jogurt grecki', 120, 'g'],
      ['szczypiorek', 5, 'g'],
    ],
    steps: [
      'Kalafior podziel na średnie różyczki. Wymieszaj mąkę z mlekiem, czosnkiem granulowanym i połową papryki na gęste ciasto.',
      'Bułkę tartą wymieszaj z resztą wędzonej papryki. Obtaczaj różyczki w cieście, a potem w bułce tartej.',
      'Ułóż kalafior w koszu airfryera, skrop olejem i piecz w 200°C przez 15–18 minut, potrząsając w połowie, aż panierka będzie chrupiąca. W piekarniku: 220°C, termoobieg, 25 minut na blasze z papierem.',
      'W rondelku roztop masło z sosem sriracha i miodem, wymieszaj.',
      'Przełóż kalafior do miski, polej ostrym sosem, posyp szczypiorkiem i podawaj z jogurtem greckim jako dipem.',
    ],
    photo:
      'Crispy breaded cauliflower florets glazed with glossy red-orange spicy sriracha butter sauce, sprinkled with chives, with a bowl of white yogurt dip',
  },
  {
    plan: 'KO-078',
    title: 'Szaszłyki z halloumi i warzyw',
    description:
      'Kolorowe szaszłyki z kostek halloumi, cukinii, papryki, czerwonej cebuli i pomidorków, skropione oliwą z oregano i cytryną, upieczone w airfryerze. Ser się rumieni, ale nie topi, a warzywa łapią lekko przypieczony smak.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ser halloumi', 140, 'g'],
      ['cukinia', 250, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 15, 'g'],
      ['oregano', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Jeśli używasz drewnianych patyczków, namocz je w wodzie na 15 minut.',
      'Halloumi pokrój w kostkę 2 cm, cukinię w grube półplastry, paprykę w kwadraty, a cebulę w ósemki.',
      'Wymieszaj oliwę z sokiem z cytryny, oregano i pieprzem, obtocz w niej ser i warzywa, a potem nabijaj je na przemian z pomidorkami na patyczki.',
      'Piecz szaszłyki w airfryerze w 200°C przez 10–12 minut, obracając w połowie, aż warzywa i ser się przyrumienią. W piekarniku: 220°C, termoobieg, 15–18 minut na kratce nad blachą.',
      'Podawaj od razu, polane resztą ziołowej oliwy.',
    ],
    photo:
      'Skewers of golden seared halloumi cubes with charred zucchini, red pepper, red onion and blistered cherry tomatoes, sprinkled with oregano',
  },
  {
    plan: 'KO-079',
    title: 'Brokuł i kalafior z sosem sezamowym',
    description:
      'Różyczki brokuła i kalafiora upieczone w airfryerze z olejem sezamowym, aż brzegi się przypieką, polane kremowym sosem z tahini, sosu sojowego, imbiru i limonki. Lekka, roślinna kolacja w azjatyckim stylu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['brokuł', 400, 'g'],
      ['kalafior', 400, 'g'],
      ['olej sezamowy', 10, 'ml'],
      ['tahini', 30, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['syrop klonowy', 10, 'g'],
      ['limonka', 20, 'g'],
      ['imbir', 5, 'g'],
      ['czosnek', 1, 'szt'],
      ['sezam', 10, 'g'],
      ['cebula dymka', 20, 'g'],
    ],
    steps: [
      'Brokuł i kalafior podziel na różyczki, wymieszaj z olejem sezamowym.',
      'Piecz w airfryerze w 200°C przez 12–14 minut, potrząsając koszem w połowie, aż różyczki będą miękkie z przypieczonymi brzegami. W piekarniku: 220°C, termoobieg, 20–25 minut na blasze.',
      'Wymieszaj tahini z sosem sojowym, syropem klonowym, sokiem z limonki, startym imbirem, przeciśniętym czosnkiem i 2–3 łyżkami ciepłej wody na gładki sos.',
      'Sezam upraż na suchej patelni przez 2 minuty, a dymkę pokrój w cienkie krążki.',
      'Przełóż warzywa do misek, polej sosem sezamowym i posyp sezamem oraz dymką.',
    ],
    photo:
      'Roasted broccoli and cauliflower florets with charred edges drizzled with creamy beige tahini sesame sauce, toasted sesame seeds and sliced spring onion',
    vessel: 'bowl',
  },
  {
    plan: 'KO-080',
    title: 'Pieczarki faszerowane serem i szczypiorkiem',
    description:
      'Duże kapelusze pieczarek nadziane kremowym serkiem z posiekanymi nóżkami, czosnkiem i szczypiorkiem, pod złotą warstwą sera, upieczone w airfryerze. Aromatyczna, niskowęglowodanowa kolacja bez mięsa i bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['pieczarka', 500, 'g'],
      ['serek kremowy', 100, 'g'],
      ['ser żółty', 60, 'g'],
      ['masło', 10, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['szczypiorek', 10, 'g'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pieczarki oczyść, wykręć nóżki i posiekaj je drobno razem z dymką i czosnkiem.',
      'Podsmaż posiekane nóżki na maśle przez 5 minut, aż odparują. Ostudź i wymieszaj z serkiem kremowym, większością szczypiorku i pieprzem.',
      'Nafaszeruj kapelusze pieczarek farszem i posyp startym serem żółtym.',
      'Piecz w airfryerze w 180°C przez 10–12 minut, aż pieczarki zmiękną, a ser się zezłoci. W piekarniku: 200°C, termoobieg, 15–18 minut.',
      'Podawaj na rukoli, posypane resztą szczypiorku.',
    ],
    photo:
      'Large baked stuffed mushroom caps with creamy herb filling under a golden melted cheese crust, sprinkled with chives, on a bed of arugula',
  },
  {
    plan: 'KO-081',
    title: 'Pierogi pieczone z sosem czosnkowym',
    description:
      'Domowe pierogi ruskie z ziemniakami, twarogiem i cebulką, najpierw krótko ugotowane, a potem zapieczone w airfryerze na chrupiąco. Podane z chłodnym sosem jogurtowym z czosnkiem i koperkiem to pierogi w nowym, złocistym wydaniu.',
    mealType: 'DINNER',
    difficulty: 'HARD',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DUMPLINGS',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['ziemniak', 300, 'g'],
      ['ser twaróg półtłusty', 150, 'g'],
      ['cebula', 100, 'g'],
      ['jogurt naturalny', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 5, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i ugotuj w osolonej wodzie 20 minut, odcedź i przeciśnij przez praskę. Cebulę posiekaj i zeszklij na 5 ml oleju.',
      'Wymieszaj ziemniaki z twarogiem, połową cebuli, pieprzem i szczyptą soli na farsz.',
      'Mąkę wymieszaj z resztą soli, 10 ml oleju i około 110 ml ciepłej wody, zagnieć gładkie ciasto i odstaw pod miską na 15 minut.',
      'Rozwałkuj ciasto na 2 mm, wykrawaj krążki szklanką, nakładaj farsz i dokładnie sklejaj brzegi. Gotuj pierogi partiami 2 minuty od wypłynięcia i osącz.',
      'Posmaruj pierogi resztą oleju i piecz w airfryerze w 200°C przez 10–12 minut, obracając w połowie, aż będą złote i chrupiące. W piekarniku: 220°C, termoobieg, 15–18 minut na blasze z papierem.',
      'Wymieszaj jogurt z przeciśniętym czosnkiem i posiekanym koperkiem. Podawaj pierogi z sosem czosnkowym i resztą cebulki.',
    ],
    photo:
      'Golden crispy baked half-moon pierogi with blistered edges, topped with fried onion, served with a bowl of white garlic dill yogurt sauce',
  },
  {
    plan: 'KO-082',
    title: 'Tacos z kurczakiem i kapustą',
    description:
      'Miękkie tortille kukurydziane z przyprawionym kurczakiem z airfryera, chrupiącą czerwoną kapustą z limonką, kolendrą i jogurtowym sosem. Meksykańska kolacja pełna białka, którą każdy składa sobie sam przy stole.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['tortilla kukurydziana', 6, 'szt'],
      ['kapusta czerwona', 150, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
      ['jogurt grecki', 100, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka wędzona mielona', 2, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Pokrój kurczaka w paski i wymieszaj z oliwą, wędzoną papryką, kminem, czosnkiem granulowanym i solą.',
      'Piecz kurczaka w airfryerze w 200°C przez 10–12 minut, potrząsając koszem w połowie, aż się zrumieni. W piekarniku: 220°C, termoobieg, 15–18 minut na blasze.',
      'Kapustę poszatkuj bardzo cienko i wymieszaj z połową soku z limonki. Jogurt wymieszaj z resztą soku.',
      'Tortille podgrzej po 1–2 minuty w airfryerze albo na suchej patelni, żeby zmiękły.',
      'Na każdą tortillę nałóż kapustę i kurczaka, polej sosem jogurtowym i posyp kolendrą.',
    ],
    photo:
      'Three soft corn tortilla tacos filled with smoky seared chicken strips, shredded purple cabbage, white yogurt sauce, cilantro and lime wedges',
    vessel: 'board',
  },
  {
    plan: 'KO-083',
    title: 'Pizza na tortilli z warzywami',
    description:
      'Chrupiąca pizza na cienkiej tortilli z passatą, mozzarellą, papryką, pieczarkami i kukurydzą, gotowa w airfryerze w kilka minut. Dzieci mogą same układać dodatki, a kolacja jest na stole w kwadrans.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'BAKE',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['passata pomidorowa', 100, 'ml'],
      ['mozzarella tarta', 100, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['pieczarka', 80, 'g'],
      ['kukurydza z puszki', 50, 'g'],
      ['oregano', 1, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Paprykę pokrój w cienkie paski, a pieczarki w plasterki. Kukurydzę odsącz.',
      'Wymieszaj passatę z oregano i posmaruj nią cienko tortille, zostawiając 1 cm brzegu.',
      'Posyp tortille połową mozzarelli, ułóż paprykę, pieczarki i kukurydzę, a na wierzch resztę sera.',
      'Piecz każdą pizzę w airfryerze w 180°C przez 5–6 minut, aż ser się roztopi, a brzegi będą chrupiące. W piekarniku: 220°C, termoobieg, 8–10 minut na blasze.',
      'Posyp listkami bazylii, pokrój na trójkąty i podawaj od razu.',
    ],
    photo:
      'Thin crispy tortilla pizza cut into wedges, topped with melted mozzarella, red pepper strips, sliced mushrooms, sweet corn and fresh basil leaves',
    vessel: 'board',
  },
  {
    plan: 'KO-084',
    title: 'Bataty z serkiem i szczypiorkiem',
    description:
      'Połówki batatów upieczone w airfryerze do miękkości, z karmelizowanym miąższem, nadziane chłodnym serkiem twarogowym z jogurtem, czosnkiem i szczypiorkiem. Lekka, słodko-słona kolacja bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'POTATOES',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['batat', 550, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['ser twaróg półtłusty', 150, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['szczypiorek', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['papryka słodka mielona', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Bataty wyszoruj, przekrój wzdłuż na pół i natnij miąższ w kratkę. Posmaruj oliwą i oprósz papryką i połową soli.',
      'Piecz w airfryerze miąższem do góry w 190°C przez 25–30 minut, aż będą miękkie. W piekarniku: 200°C, termoobieg, 35–40 minut na blasze z papierem.',
      'W tym czasie rozgnieć twaróg z jogurtem na gładki serek, wmieszaj przeciśnięty czosnek, większość posiekanego szczypiorku, resztę soli i pieprz.',
      'Rozgnieć lekko widelcem miąższ batatów, nałóż na nie serek i posyp resztą szczypiorku.',
    ],
    photo:
      'Roasted orange sweet potato halves with scored caramelized flesh, topped with a generous dollop of white herbed cream cheese and chopped chives',
  },
  {
    plan: 'KO-085',
    title: 'Pierś z indyka w ziołach z sałatką',
    description:
      'Soczysta pierś z indyka w ziołach prowansalskich, czosnku i cytrynie, upieczona w airfryerze i podana z chrupiącą sałatką z pomidorków, ogórka i rzodkiewki. Lekka, bardzo białkowa kolacja bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['filet z indyka', 350, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['zioła prowansalskie', 2, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['sałata rzymska', 100, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['ogórek', 150, 'g'],
      ['rzodkiewka', 60, 'g'],
      ['ocet balsamiczny', 5, 'ml'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filet z indyka przekrój na 2 równe kawałki. Natrzyj 10 ml oliwy, przeciśniętym czosnkiem, ziołami prowansalskimi, sokiem z połowy cytryny, solą i pieprzem, odstaw na 10 minut.',
      'Piecz indyka w airfryerze w 190°C przez 14–16 minut, obracając w połowie, aż sok będzie przezroczysty. W piekarniku: 200°C, termoobieg, 22–25 minut. Odstaw na 3 minuty.',
      'Sałatę porwij, pomidorki przekrój na pół, ogórek i rzodkiewki pokrój w plasterki.',
      'Wymieszaj warzywa z resztą oliwy, octem balsamicznym i resztą soku z cytryny.',
      'Pokrój indyka w plastry i podawaj na sałatce.',
    ],
    photo:
      'Sliced golden herb-crusted turkey breast on a fresh salad of romaine, halved cherry tomatoes, cucumber and radish slices',
  },
  {
    plan: 'KO-086',
    title: 'Kiełbasa z grilla z sałatką ziemniaczaną',
    description:
      'Nacinana kiełbasa śląska z grilla ogrodowego, z przypieczoną skórką, podana z chłodną sałatką z młodych ziemniaków, ogórka, rzodkiewki i dymki w lekkim sosie z majonezu i jogurtu. Smak majówki na działce.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['kiełbasa śląska', 180, 'g'],
      ['ziemniak młody', 600, 'g'],
      ['ogórek', 150, 'g'],
      ['rzodkiewka', 80, 'g'],
      ['cebula dymka', 40, 'g'],
      ['majonez', 30, 'g'],
      ['jogurt naturalny', 60, 'g'],
      ['ocet jabłkowy', 5, 'ml'],
      ['koperek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki wyszoruj i ugotuj w mundurkach 18–20 minut, ostudź i pokrój w plastry lub ćwiartki.',
      'Ogórek i rzodkiewki pokrój w półplasterki, dymkę i koperek posiekaj.',
      'Wymieszaj majonez z jogurtem, octem i pieprzem, połącz z ziemniakami i warzywami, odstaw do lodówki.',
      'Rozpal grill i poczekaj, aż ruszt się nagrzeje. Kiełbasę natnij ukośnie co 1 cm i grilluj nad średnim żarem 8–10 minut, obracając, aż skórka się przypiecze.',
      'Wariant na patelni grillowej: smaż kiełbasę na rozgrzanej patelni grillowej 8 minut, obracając co 2 minuty.',
      'Podawaj gorącą kiełbasę z chłodną sałatką ziemniaczaną.',
    ],
    photo:
      'Grilled scored sausage with charred crispy edges next to a creamy potato salad with cucumber, radish, spring onion and dill',
  },
  {
    plan: 'KO-087',
    title: 'Biała kiełbasa z grilla z chrzanem',
    description:
      'Biała kiełbasa podpiekana na grillu ogrodowym, aż skórka się zrumieni, podana z młodymi ziemniakami z rusztu, grillowaną czerwoną cebulą i ostrym chrzanem. Majówkowa kolacja bez glutenu i nabiału.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['kiełbasa biała', 200, 'g'],
      ['ziemniak młody', 500, 'g'],
      ['cebula czerwona', 150, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['chrzan tarty', 20, 'g'],
      ['majeranek', 1, 'g'],
      ['szczypiorek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Młode ziemniaki wyszoruj i podgotuj 10 minut w wodzie, odcedź i przekrój na pół.',
      'Cebulę pokrój w grube plastry. Ziemniaki i cebulę wymieszaj z olejem, majerankiem i pieprzem.',
      'Rozpal grill. Kiełbasę sparz wrzątkiem na 5 minut, osusz i grilluj nad średnim żarem 10–12 minut, obracając, aż skórka się zrumieni. Obok grilluj ziemniaki i cebulę w tacce lub na ruszcie 10 minut.',
      'Wariant na patelni grillowej: kiełbasę, ziemniaki i cebulę smaż na rozgrzanej patelni grillowej po 10–12 minut, obracając.',
      'Podawaj kiełbasę z ziemniakami i cebulą, z chrzanem do smaku i posypane szczypiorkiem.',
    ],
    photo:
      'Grilled pale white sausages with golden charred marks, halved grilled baby potatoes, charred red onion rings and a small bowl of grated horseradish',
  },
];
