/**
 * Katalog 1000 — część KO-d: kolacje KO-088 … KO-116 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Grill i majówka ──
  {
    plan: 'KO-088',
    title: 'Grillowana cukinia i bakłażan z sosem czosnkowym',
    description:
      'Plastry cukinii i bakłażana z grilla ogrodowego, z przypieczonymi paskami i dymnym aromatem, polane gęstym sosem czosnkowym z jogurtu sojowego i tahini. Lekka, roślinna kolacja na letni wieczór, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['cukinia', 400, 'g'],
      ['bakłażan', 400, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['jogurt sojowy', 200, 'g'],
      ['tahini', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['cytryna', 30, 'g'],
      ['koperek', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozpal grill i poczekaj, aż ruszt dobrze się nagrzeje (średnio-wysoka temperatura).',
      'Cukinię i bakłażana pokrój wzdłuż w plastry grubości 1 cm. Posmaruj je oliwą, oprósz papryką słodką, solą i pieprzem.',
      'Wymieszaj jogurt sojowy z tahini, przeciśniętym czosnkiem, sokiem z cytryny i posiekanym koperkiem, odstaw do lodówki.',
      'Grilluj bakłażana po 4–5 minut z każdej strony, a cukinię po 3 minuty, aż warzywa zmiękną i będą miały wyraźne paski.',
      'Na patelni grillowej: rozgrzej ją mocno i grilluj warzywa partiami w tym samym czasie.',
      'Ułóż warzywa na półmisku i polej sosem czosnkowym.',
    ],
    photo:
      'Overlapping slices of charred zucchini and eggplant with dark grill marks, drizzled with creamy white garlic sauce and sprinkled with fresh dill',
  },
  {
    plan: 'KO-089',
    title: 'Oscypek z grilla z żurawiną',
    description:
      'Wędzony oscypek przypieczony na ruszcie, aż zmięknie w środku i zrumieni się z zewnątrz, podany z sosem żurawinowym i rukolą z pomidorkami. Góralski klasyk grillowych wieczorów, gotowy w kwadrans.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['oscypek', 220, 'g'],
      ['sos żurawinowy', 80, 'g'],
      ['rukola', 60, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozpal grill i nagrzej ruszt do średniej temperatury.',
      'Oscypki pokrój wzdłuż na plastry grubości 1,5 cm albo grilluj w całości, jeśli są małe.',
      'Grilluj oscypek po 2–3 minuty z każdej strony, aż zrumieni się i lekko zmięknie. Na patelni grillowej: 2 minuty z każdej strony na średnim ogniu.',
      'Rukolę i przekrojone pomidorki wymieszaj z oliwą i pieprzem.',
      'Podawaj gorący oscypek z sosem żurawinowym i sałatką.',
    ],
    photo:
      'Golden grilled smoked oscypek cheese slices with grill marks topped with glossy red cranberry sauce, next to arugula and halved cherry tomatoes',
  },
  {
    plan: 'KO-090',
    title: 'Ziemniaki z grilla w folii z twarożkiem',
    description:
      'Ziemniaki pieczone w folii prosto w żarze grilla, rozkrojone i nadziane twarożkiem ze szczypiorkiem, rzodkiewką i czosnkiem. Sycąca, bezmięsna kolacja z majówkowego rusztu, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'POTATOES',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ser twaróg półtłusty', 150, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['szczypiorek', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozpal grill. Umyj dokładnie cztery duże ziemniaki, osusz, natrzyj olejem i szczyptą soli, a potem owiń każdy szczelnie folią aluminiową.',
      'Połóż ziemniaki na ruszcie nad żarem albo bezpośrednio w rozżarzonych węglach i piecz 40–50 minut, obracając co 10 minut, aż będą miękkie w środku.',
      'W tym czasie rozgnieć twaróg z jogurtem, dodaj pokrojoną w kostkę rzodkiewkę, posiekany szczypiorek, przeciśnięty czosnek, resztę soli i pieprz.',
      'Na patelni grillowej: ugotuj ziemniaki w mundurkach 15 minut, przekrój na pół i grilluj po 5 minut z każdej strony.',
      'Rozchyl folię, natnij ziemniaki na krzyż, lekko ściśnij i nałóż do środka twarożek.',
    ],
    photo:
      'Foil-wrapped baked potatoes split open with a cross cut, filled with herbed cottage cheese spread, diced radish and chopped chives',
  },
  {
    plan: 'KO-091',
    title: 'Burgery z indyka z grilla',
    description:
      'Soczyste kotlety z mielonego indyka z czosnkiem i papryką, grillowane na ruszcie i podane w bułce z sałatą, pomidorem i jogurtowym sosem musztardowym. Lżejsza, bogata w białko wersja klasycznego burgera.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['indyk mielony', 300, 'g'],
      ['bułka do hamburgera', 150, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['pomidor', 120, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['jogurt grecki', 60, 'g'],
      ['musztarda', 10, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozpal grill i nagrzej ruszt do średnio-wysokiej temperatury.',
      'Mięso wymieszaj z czosnkiem granulowanym, papryką, solą i pieprzem, uformuj dwa płaskie kotlety grubości 1,5 cm.',
      'Grilluj kotlety po 5–6 minut z każdej strony, aż będą całkowicie ścięte w środku. Pod koniec połóż przekrojone bułki na ruszcie na 1 minutę. Na patelni grillowej: kotlety po 5 minut z każdej strony na średnim ogniu.',
      'Jogurt grecki wymieszaj z musztardą. Pomidor pokrój w plastry, a cebulę w cienkie krążki.',
      'Posmaruj bułki sosem, ułóż sałatę, kotlet, pomidor i cebulę, przykryj wierzchem bułki.',
    ],
    photo:
      'Two grilled turkey burgers in toasted sesame buns with crisp iceberg lettuce, tomato slices, red onion rings and creamy mustard yogurt sauce',
  },
  {
    plan: 'KO-092',
    title: 'Kukurydza z grilla z masłem ziołowym',
    description:
      'Słodkie kolby kukurydzy przypieczone na ruszcie i posmarowane masłem z czosnkiem, natką i szczypiorkiem. Letni klasyk grilla, który smakuje dzieciom i dorosłym, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['kukurydza', 4, 'szt'],
      ['masło', 40, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['szczypiorek', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Masło wyjmij wcześniej z lodówki, żeby zmiękło. Utrzyj je z drobno posiekaną natką, szczypiorkiem, przeciśniętym czosnkiem, solą i pieprzem.',
      'Kolby kukurydzy oczyść z liści i włosków, a potem gotuj 8 minut we wrzącej wodzie.',
      'Rozpal grill i grilluj kolby 8–10 minut, obracając co 2 minuty, aż ziarna się przypieką. Na patelni grillowej: 10 minut na średnim ogniu, z obracaniem.',
      'Zdejmij kolby z rusztu i od razu posmaruj je masłem ziołowym.',
    ],
    photo:
      'Four charred corn on the cob with golden kernels and dark grill spots, glistening with melting herb butter flecked with parsley and chives',
  },
  {
    plan: 'KO-093',
    title: 'Łosoś z grilla z cytryną i ziołami',
    description:
      'Filety łososia marynowane w oliwie, cytrynie, czosnku i koperku, grillowane na skórze, aż ta zrobi się chrupiąca. Podane z rukolą i pomidorkami to szybka, lekka kolacja z grilla bez glutenu i nabiału.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['łosoś', 300, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 100, 'g'],
      ['czosnek', 1, 'szt'],
      ['koperek', 10, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['rukola', 50, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wymieszaj oliwę z sokiem z połowy cytryny, przeciśniętym czosnkiem, połową posiekanego koperku, tymiankiem, solą i pieprzem. Natrzyj łososia i odstaw na 15 minut.',
      'Rozpal grill, dobrze wyczyść i naoliw ruszt albo połóż rybę na tacce grillowej.',
      'Grilluj łososia skórą do dołu 6 minut, obróć i grilluj jeszcze 2–3 minuty, aż mięso zacznie się rozdzielać na płatki. Na patelni grillowej: 5 minut na skórze i 3 minuty z drugiej strony.',
      'Drugą połowę cytryny pokrój w plasterki i przypiecz krótko na ruszcie.',
      'Podawaj łososia z rukolą, przekrojonymi pomidorkami, grillowaną cytryną i resztą koperku.',
    ],
    photo:
      'Grilled salmon fillets with crispy skin and grill marks, charred lemon slices and fresh dill, served with arugula and halved cherry tomatoes',
  },
  {
    plan: 'KO-094',
    title: 'Pieczarki z grilla faszerowane serem i czosnkiem',
    description:
      'Duże kapelusze pieczarek wypełnione serkiem kremowym z czosnkiem i natką, zapieczone na ruszcie pod roztopioną mozzarellą. Aromatyczna, niskowęglowodanowa kolacja z grilla, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['pieczarka', 500, 'g'],
      ['serek kremowy', 100, 'g'],
      ['mozzarella tarta', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wybierz 10–12 dużych pieczarek, oczyść je, wykręć nóżki i posiekaj je drobno.',
      'Wymieszaj posiekane nóżki z serkiem kremowym, przeciśniętym czosnkiem, połową posiekanej natki i pieprzem.',
      'Kapelusze posmaruj z zewnątrz oliwą, napełnij farszem i posyp mozzarellą.',
      'Ułóż pieczarki na tacce grillowej, przykryj grill pokrywą i piecz 10–12 minut, aż kapelusze zmiękną, a ser się roztopi. Na patelni grillowej: 10 minut pod przykryciem na średnim ogniu.',
      'Podawaj od razu, posypane resztą natki.',
    ],
    photo:
      'Large grilled mushroom caps filled with creamy garlic cheese stuffing under bubbling melted mozzarella, sprinkled with chopped parsley',
  },
  {
    plan: 'KO-095',
    title: 'Camembert z grilla z żurawiną i bagietką',
    description:
      'Krążek camemberta zapieczony na ruszcie z rozmarynem, aż środek zrobi się płynny, podany z żurawiną, orzechami, gruszką i chrupiącą bagietką do maczania. Efektowna, a banalnie prosta kolacja na grillowe spotkanie.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE', 'PARTY'],
    equipment: ['GRILL'],
    ingredients: [
      ['ser camembert', 150, 'g'],
      ['sos żurawinowy', 60, 'g'],
      ['bagietka', 90, 'g'],
      ['orzech włoski', 20, 'g'],
      ['gruszka', 150, 'g'],
      ['rukola', 40, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['rozmaryn suszony', 1, 'g'],
    ],
    steps: [
      'Rozpal grill. Ser natnij na wierzchu w kratkę, posyp rozmarynem i skrop połową oliwy.',
      'Połóż camembert na tacce grillowej albo w małej foremce z folii, przykryj grill i piecz 8–10 minut, aż ser zmięknie i zacznie się rozpływać w środku. Na patelni grillowej: 3 minuty z każdej strony pod przykryciem.',
      'Bagietkę pokrój ukośnie w kromki, skrop resztą oliwy i przypiecz na ruszcie po 1 minucie z każdej strony.',
      'Gruszkę pokrój w cienkie plastry, a orzechy grubo posiekaj.',
      'Przełóż camembert na deskę, nałóż sos żurawinowy, posyp orzechami i podawaj z bagietką, gruszką i rukolą.',
    ],
    photo:
      'Whole grilled camembert with molten center topped with glossy cranberry sauce and chopped walnuts, surrounded by toasted baguette slices, pear slices and arugula',
    vessel: 'board',
  },
  {
    plan: 'KO-096',
    title: 'Szaszłyki z tofu i warzyw z grilla',
    description:
      'Kostki tofu marynowane w sosie sojowym z czosnkiem i wędzoną papryką, nadziane na patyczki z papryką, cukinią, cebulą i pieczarkami. Kolorowa, roślinna kolacja z grilla z dużą porcją białka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['tofu', 400, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['czosnek', 2, 'szt'],
      ['papryka wędzona mielona', 2, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['cukinia', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['pieczarka', 150, 'g'],
    ],
    steps: [
      'Tofu odsącz, owiń ręcznikiem papierowym i dociśnij na 10 minut, potem pokrój w kostkę 2,5 cm.',
      'Wymieszaj sos sojowy z olejem, przeciśniętym czosnkiem i wędzoną papryką. Zalej tofu i marynuj 15 minut.',
      'Paprykę i cebulę pokrój w kwadraty, cukinię w grube półplastry, a większe pieczarki przekrój na pół. Nadziewaj na patyczki na przemian z tofu i posmaruj resztą marynaty.',
      'Rozpal grill i grilluj szaszłyki 10–12 minut, obracając co 3 minuty, aż warzywa się przypieką. Na patelni grillowej: 10 minut na średnim ogniu, z obracaniem.',
    ],
    photo:
      'Colorful skewers of golden grilled tofu cubes, red pepper, zucchini, red onion and mushrooms with charred edges on a platter',
  },
  {
    plan: 'KO-097',
    title: 'Papryka z grilla faszerowana fetą',
    description:
      'Połówki czerwonej papryki wypełnione fetą z ricottą, suszonymi pomidorami i oregano, pieczone na ruszcie, aż ser się rozpuści, a skórka przypiecze. Śródziemnomorska kolacja z grilla, bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['papryka czerwona', 640, 'g'],
      ['ser feta', 100, 'g'],
      ['ser ricotta', 130, 'g'],
      ['pomidor suszony w oleju', 30, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['czosnek', 1, 'szt'],
      ['oregano', 2, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Przekrój cztery papryki wzdłuż na pół, razem z ogonkiem, i usuń gniazda nasienne.',
      'Pokrusz fetę, wymieszaj z ricottą, posiekanymi suszonymi pomidorami, przeciśniętym czosnkiem i oregano.',
      'Posmaruj papryki z zewnątrz oliwą i napełnij farszem.',
      'Rozpal grill, ułóż papryki farszem do góry, przykryj pokrywą i grilluj 12–15 minut, aż papryka zmięknie, a spód się przypiecze. Na patelni grillowej: 12 minut pod przykryciem na średnim ogniu.',
      'Podawaj posypane listkami bazylii.',
    ],
    photo:
      'Grilled red bell pepper halves with blistered skin filled with creamy crumbled feta, ricotta and sun-dried tomatoes, topped with fresh basil leaves',
  },
  {
    plan: 'KO-098',
    title: 'Sałatka z grillowanych warzyw i bulguru',
    description:
      'Bulgur z grillowaną cukinią, bakłażanem, papryką i czerwoną cebulą, z pomidorkami, oliwkami, miętą i cytrynowo-oregano dressingiem. Roślinna sałatka w greckim stylu, dobra na ciepło i następnego dnia do pudełka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'SALAD',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['bulgur', 120, 'g'],
      ['cukinia', 250, 'g'],
      ['bakłażan', 250, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['cytryna', 40, 'g'],
      ['mięta', 10, 'g'],
      ['oregano', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Bulgur zalej 250 ml wrzącej wody, przykryj i odstaw na 15 minut, potem spulchnij widelcem.',
      'Cukinię i bakłażana pokrój w plastry 1 cm, paprykę w szerokie paski, a cebulę w grube krążki. Posmaruj warzywa połową oliwy.',
      'Rozpal grill i grilluj warzywa po 3–5 minut z każdej strony, aż zmiękną i będą miały paski. Na patelni grillowej: grilluj je partiami w tym samym czasie.',
      'Pokrój grillowane warzywa w kostkę, pomidorki przekrój na pół, a oliwki na plasterki.',
      'Resztę oliwy wymieszaj z sokiem z cytryny, oregano, solą i pieprzem. Połącz bulgur z warzywami, oliwkami, posiekaną miętą i dressingiem.',
    ],
    photo:
      'Bowl of fluffy bulgur salad with diced charred zucchini, eggplant, red pepper and onion, halved cherry tomatoes, black olive slices and fresh mint',
    vessel: 'bowl',
  },
  {
    plan: 'KO-099',
    title: 'Kurczak z grilla w ziołach z bagietką czosnkową',
    description:
      'Filety z kurczaka marynowane w oliwie, cytrynie i ziołach prowansalskich, grillowane na soczyście, z chrupiącą bagietką z masłem czosnkowym zapieczoną na ruszcie. Klasyczna, sycąca kolacja z grilla z mnóstwem białka.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['filet z kurczaka', 400, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 30, 'g'],
      ['zioła prowansalskie', 3, 'g'],
      ['bagietka', 120, 'g'],
      ['masło', 25, 'g'],
      ['czosnek', 3, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filety przekrój poziomo na cieńsze płaty. Wymieszaj oliwę z sokiem z cytryny, ziołami prowansalskimi, jednym przeciśniętym ząbkiem czosnku, solą i pieprzem, natrzyj mięso i odstaw na 20 minut.',
      'Masło utrzyj z dwoma przeciśniętymi ząbkami czosnku i połową posiekanej natki.',
      'Bagietkę natnij w poprzek co 2 cm, nie dokrojając do końca, wsmaruj masło między kromki i zawiń w folię aluminiową.',
      'Rozpal grill i grilluj kurczaka po 5–6 minut z każdej strony, aż będzie całkowicie ścięty w środku. Bagietkę w folii połóż z boku rusztu na 8–10 minut. Na patelni grillowej: kurczak po 5 minut z każdej strony, a bagietkę opiecz na suchej patelni po 2 minuty z każdej strony.',
      'Pokrój kurczaka w plastry, posyp resztą natki i podawaj z gorącą bagietką czosnkową.',
    ],
    photo:
      'Sliced herb-marinated grilled chicken breast with grill marks and chopped parsley, next to a golden garlic butter baguette cut into slices',
  },
  {
    plan: 'KO-100',
    title: 'Bakłażan z grilla z mozzarellą i pomidorami',
    description:
      'Grube plastry grillowanego bakłażana przełożone mozzarellą i dojrzałymi pomidorami, skropione oliwą z bazylią i octem balsamicznym. Włoska, wegetariańska kolacja z grilla bez glutenu, prosta i bardzo wakacyjna.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['bakłażan', 500, 'g'],
      ['mozzarella', 250, 'g'],
      ['pomidor', 300, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['ocet balsamiczny', 15, 'ml'],
      ['bazylia', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Bakłażana pokrój w plastry grubości 1,5 cm, oprósz solą i odstaw na 10 minut, potem osusz ręcznikiem.',
      'Wymieszaj oliwę z przeciśniętym czosnkiem i pieprzem, posmaruj nią plastry bakłażana.',
      'Rozpal grill i grilluj bakłażana po 4 minuty z każdej strony. Na każdym plastrze połóż kawałek mozzarelli, przykryj grill pokrywą i trzymaj jeszcze 2 minuty, aż ser zmięknie. Na patelni grillowej: tak samo, pod przykryciem.',
      'Pomidory pokrój w plastry i ułóż na przemian z bakłażanem na półmisku.',
      'Skrop octem balsamicznym i posyp listkami bazylii.',
    ],
    photo:
      'Layered grilled eggplant slices with charred grill marks, melting mozzarella and ripe tomato slices, drizzled with balsamic glaze and fresh basil leaves',
  },
  {
    plan: 'KO-101',
    title: 'Szaszłyki z kiełbasy, cebuli i papryki',
    description:
      'Kawałki kiełbasy nadziane na patyczki na przemian z kolorową papryką, cebulą, cukinią i pieczarkami, przypieczone na ruszcie i podane z ketchupem. Najprostsze szaszłyki na majówkę, które dzieci chętnie składają same.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['kiełbasa śląska', 180, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['papryka żółta', 150, 'g'],
      ['cebula', 150, 'g'],
      ['cukinia', 200, 'g'],
      ['pieczarka', 150, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['ketchup', 30, 'g'],
    ],
    steps: [
      'Jeśli używasz drewnianych patyczków, namocz je w wodzie na 20 minut.',
      'Kiełbasę pokrój w plastry grubości 2 cm, paprykę w kwadraty, cebulę w ćwiartki rozdzielone na płatki, cukinię w grube półplastry, a pieczarki zostaw w całości.',
      'Nadziewaj składniki na patyczki na przemian, posmaruj olejem wymieszanym ze słodką papryką.',
      'Rozpal grill i grilluj szaszłyki 10–12 minut, obracając co 3 minuty, aż kiełbasa się zrumieni, a warzywa zmiękną. Na patelni grillowej: 10 minut na średnim ogniu, z obracaniem.',
      'Podawaj z ketchupem.',
    ],
    photo:
      'Grilled skewers of browned sausage chunks alternating with red and yellow pepper, onion petals, zucchini and whole mushrooms, with a small bowl of ketchup',
  },

  // ── Wigilia ──
  {
    plan: 'KO-102',
    title: 'Barszcz czerwony z uszkami z grzybami',
    description:
      'Klarowny, lekko kwaśny barszcz na burakach i zakwasie, z domowymi uszkami nadziewanymi suszonymi grzybami i pieczarkami. Serce wigilijnej kolacji, które warto zrobić samemu choć raz w roku.',
    mealType: 'DINNER',
    difficulty: 'HARD',
    prepTimeMinutes: 150,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['burak', 800, 'g'],
      ['cebula', 80, 'g'],
      ['grzyb suszony', 40, 'g'],
      ['zakwas buraczany', 300, 'ml'],
      ['czosnek', 2, 'szt'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['majeranek', 2, 'g'],
      ['cukier', 5, 'g'],
      ['mąka pszenna', 200, 'g'],
      ['jajko', 1, 'szt'],
      ['pieczarka', 150, 'g'],
      ['masło', 15, 'g'],
      ['bułka tarta', 15, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby suszone zalej 500 ml ciepłej wody i odstaw na noc albo na co najmniej 2 godziny, potem ugotuj w tej wodzie 20 minut. Odcedź, wywar zachowaj.',
      'Buraki obierz i pokrój w cienkie plastry. Zalej 1,5 l wody, dodaj liść laurowy i ziele angielskie, gotuj na małym ogniu 40 minut, aż wywar nabierze głębokiego koloru.',
      'Na farsz posiekaj drobno ugotowane grzyby, cebulę i pieczarki. Zeszklij cebulę na maśle, dodaj pieczarki i grzyby, smaż 8 minut, aż odparuje woda. Dopraw pieprzem i szczyptą soli, zagęść bułką tartą i ostudź.',
      'Z mąki, jajka, szczypty soli i około 90 ml ciepłej wody zagnieć elastyczne ciasto. Rozwałkuj cienko, wytnij kwadraty 4 cm, nałóż po trochę farszu, złóż w trójkąty i zlep rogi w uszka.',
      'Wywar buraczany przecedź, dodaj wywar grzybowy, zakwas buraczany, przeciśnięty czosnek i majeranek. Dopraw solą, pieprzem i cukrem, podgrzej, nie doprowadzając do wrzenia, żeby barszcz nie stracił koloru.',
      'Uszka gotuj partiami w osolonej wodzie 3 minuty od wypłynięcia. Podawaj w talerzach zalane gorącym barszczem.',
    ],
    photo:
      'Deep ruby-red clear borscht with small folded mushroom dumplings floating in the soup, garnished with a sprig of fresh marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'KO-103',
    title: 'Zupa grzybowa wigilijna',
    description:
      'Aromatyczna zupa na suszonych grzybach leśnych i warzywach, zagęszczona zasmażką i podana z drobnym makaronem. Wigilijna klasyka w wersji całkowicie roślinnej, z głębokim, leśnym smakiem.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['grzyb suszony', 40, 'g'],
      ['pieczarka', 250, 'g'],
      ['marchew', 150, 'g'],
      ['pietruszka korzeń', 100, 'g'],
      ['seler korzeniowy', 80, 'g'],
      ['cebula', 120, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['mąka pszenna', 20, 'g'],
      ['makaron kolanka', 160, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby suszone zalej 500 ml ciepłej wody i namaczaj co najmniej 2 godziny, najlepiej przez noc.',
      'Marchew, pietruszkę i seler obierz, zalej 1,5 l wody, dodaj liść laurowy i ziele angielskie, gotuj 20 minut.',
      'Grzyby wyjmij z wody, pokrój w paski i wrzuć do wywaru razem z wodą z moczenia (przelaną przez sitko). Gotuj 30 minut.',
      'Na oleju zeszklij posiekaną cebulę, dodaj pokrojone pieczarki i smaż 6 minut. Oprósz mąką, smaż minutę, rozprowadź chochlą wywaru i przelej do zupy.',
      'Warzywa wyjmij, marchew i pietruszkę pokrój w plasterki, seler w drobną kostkę i wrzuć z powrotem do zupy. Dopraw solą i pieprzem, gotuj jeszcze 10 minut.',
      'Makaron ugotuj osobno al dente według opisu na opakowaniu. Nałóż do talerzy, zalej zupą i posyp natką.',
    ],
    photo:
      'Bowl of dark golden-brown mushroom soup with strips of dried forest mushrooms, sliced carrots, small elbow pasta and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'KO-104',
    title: 'Dorsz w sosie chrzanowym',
    description:
      'Delikatne filety dorsza duszone w kremowym sosie ze śmietany i tartego chrzanu, z koperkiem i młodymi ziemniakami. Łagodna ryba na Wigilię albo zwykły wieczór, szybsza od karpia i bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS_EVE'],
    ingredients: [
      ['dorsz', 400, 'g'],
      ['ziemniak', 500, 'g'],
      ['śmietana 18', 150, 'g'],
      ['chrzan tarty', 40, 'g'],
      ['masło', 15, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['cytryna', 20, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i gotuj w osolonej wodzie 20 minut do miękkości.',
      'Dorsza pokrój na 4 kawałki, skrop sokiem z cytryny i oprósz pieprzem oraz szczyptą soli.',
      'Na dużej patelni roztop masło, połóż rybę i duś pod przykryciem na małym ogniu 4 minuty.',
      'Śmietanę wymieszaj z chrzanem, mąką ziemniaczaną i 50 ml wody, wlej wokół ryby i duś jeszcze 5–6 minut, aż sos zgęstnieje, a dorsz zacznie się rozdzielać na płatki.',
      'Podawaj rybę z ziemniakami, polaną sosem i posypaną posiekanym koperkiem.',
    ],
    photo:
      'White cod fillets in a creamy pale horseradish sauce sprinkled with fresh dill, served with boiled potatoes',
  },
  {
    plan: 'KO-105',
    title: 'Karp smażony',
    description:
      'Dzwonka karpia oprószone mąką i usmażone na złoto, z chrupiącą skórką i soczystym mięsem, podane z cytryną. Tradycyjne danie wigilijnego stołu, bez nabiału.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['karp', 1000, 'g'],
      ['mąka pszenna', 60, 'g'],
      ['olej rzepakowy', 60, 'ml'],
      ['cytryna', 50, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Karpia oczyść, opłucz i pokrój w dzwonka grubości 2–3 cm. Osusz ręcznikiem papierowym.',
      'Natrzyj dzwonka solą i pieprzem, skrop sokiem z połowy cytryny i odstaw do lodówki na 30 minut.',
      'Obtocz rybę dokładnie w mące i strzepnij nadmiar.',
      'Rozgrzej olej na dużej patelni i smaż karpia na średnim ogniu po 5–6 minut z każdej strony, aż będzie złoty i przesmażony przy ości.',
      'Odsącz na ręczniku papierowym i podawaj z ćwiartkami reszty cytryny.',
    ],
    photo:
      'Golden pan-fried carp steaks with crispy floured skin arranged on a plate with lemon wedges',
  },
  {
    plan: 'KO-106',
    title: 'Karp pieczony z ziołami',
    description:
      'Karp pieczony w całości albo w dzwonkach na cebuli, z masłem czosnkowym, cytryną, tymiankiem i rozmarynem. Mniej zachodu niż przy smażeniu i bez tłustej patelni, a ryba zostaje soczysta. Bez glutenu.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    equipment: ['OVEN'],
    ingredients: [
      ['karp', 1000, 'g'],
      ['cebula', 150, 'g'],
      ['masło', 40, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['czosnek', 4, 'szt'],
      ['cytryna', 100, 'g'],
      ['tymianek suszony', 2, 'g'],
      ['rozmaryn suszony', 2, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Karpia oczyść, opłucz, osusz i natnij skórę ukośnie co 3 cm po obu stronach.',
      'Utrzyj miękkie masło z przeciśniętym czosnkiem, tymiankiem, rozmarynem i połową posiekanej natki.',
      'Natrzyj rybę solą i pieprzem, wsmaruj masło ziołowe w nacięcia i do środka. Wsuń do brzucha kilka plasterków cytryny.',
      'Cebulę pokrój w plastry, ułóż w naczyniu żaroodpornym, skrop olejem i połóż na niej karpia. Obłóż resztą plasterków cytryny.',
      'Piecz 35–40 minut (dzwonka 25 minut), polewając rybę w połowie pieczenia sosem z naczynia, aż skórka się zrumieni.',
      'Posyp resztą natki i podawaj z pieczoną cebulą.',
    ],
    photo:
      'Whole roasted carp with golden scored skin, lemon slices and herbs on a bed of soft roasted onion rings, sprinkled with chopped parsley',
  },
  {
    plan: 'KO-107',
    title: 'Śledzie w oleju z cebulą',
    description:
      'Filety śledziowe zalane olejem z cebulą, zielem angielskim i liściem laurowym, które po nocy w lodówce stają się miękkie i pełne smaku. Wigilijna przystawka, którą robi się dzień wcześniej.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 600,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['śledź', 280, 'g'],
      ['cebula', 200, 'g'],
      ['olej rzepakowy', 80, 'ml'],
      ['zioło angielskie', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 120, 'g'],
    ],
    steps: [
      'Jeśli śledzie są mocno solone, namocz je w zimnej wodzie na 1–2 godziny, zmieniając wodę co 30 minut, potem osusz.',
      'Pokrój filety na kawałki szerokości 3 cm, a cebulę w cienkie piórka.',
      'Układaj w słoiku albo szklanym naczyniu warstwami śledzie i cebulę, przekładając zielem angielskim, liściem laurowym i świeżo zmielonym pieprzem.',
      'Zalej wszystko olejem tak, żeby przykrył rybę, zamknij i wstaw do lodówki na co najmniej 8 godzin, najlepiej na noc.',
      'Podawaj śledzie z cebulą i kromkami chleba żytniego.',
    ],
    photo:
      'Pieces of silver herring fillets layered with thin white onion slices in golden oil with allspice and bay leaves, with slices of rye bread',
  },
  {
    plan: 'KO-108',
    title: 'Śledzie w śmietanie z jabłkiem',
    description:
      'Kawałki śledzia w gęstej śmietanie z kwaskowym jabłkiem, cebulą i koperkiem, podane z gotowanymi ziemniakami. Łagodniejsza, kremowa wersja wigilijnych śledzi, którą lubią nawet sceptycy.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 180,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['śledź', 300, 'g'],
      ['śmietana 18', 250, 'g'],
      ['jabłko', 250, 'g'],
      ['cebula', 100, 'g'],
      ['koperek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['ziemniak', 900, 'g'],
    ],
    steps: [
      'Jeśli śledzie są mocno solone, namocz je w zimnej wodzie na 1–2 godziny, potem osusz i pokrój na kawałki szerokości 2–3 cm.',
      'Jabłko obierz i pokrój w drobną kostkę, cebulę posiekaj drobno.',
      'Wymieszaj śmietanę z jabłkiem, cebulą, połową posiekanego koperku i pieprzem. Połącz delikatnie ze śledziami i wstaw do lodówki na co najmniej 1 godzinę.',
      'Ziemniaki obierz i gotuj w wodzie 20 minut do miękkości.',
      'Podawaj śledzie posypane resztą koperku, z ciepłymi ziemniakami.',
    ],
    photo:
      'Herring pieces in thick white sour cream sauce with diced green apple, onion and dill, served with boiled potatoes',
  },
  {
    plan: 'KO-109',
    title: 'Kapusta z grzybami',
    description:
      'Kapusta kiszona i biała duszona z suszonymi grzybami, pieczarkami i zeszkloną cebulą, z zielem angielskim i pieprzem. Wigilijna klasyka w wersji roślinnej i bez glutenu, jeszcze lepsza odgrzana następnego dnia.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    occasions: ['CHRISTMAS_EVE'],
    ingredients: [
      ['kapusta kiszona', 200, 'g'],
      ['kapusta biała', 400, 'g'],
      ['grzyb suszony', 20, 'g'],
      ['pieczarka', 200, 'g'],
      ['cebula', 150, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['zioło angielskie', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby suszone zalej 300 ml ciepłej wody i namaczaj co najmniej 2 godziny, potem ugotuj w tej wodzie 20 minut i pokrój w paski. Wywar zachowaj.',
      'Kapustę kiszoną posiekaj, białą poszatkuj. Włóż obie do garnka z zielem angielskim i liściem laurowym, podlej 200 ml wody i duś pod przykryciem 30 minut.',
      'Na oleju zeszklij posiekaną cebulę, dodaj pokrojone pieczarki i smaż 8 minut, aż się zrumienią.',
      'Dodaj do kapusty grzyby z wywarem oraz cebulę z pieczarkami. Duś bez przykrycia jeszcze 20 minut, aż płyn odparuje, a kapusta zmięknie.',
      'Dopraw pieprzem, wyjmij liść laurowy i podawaj na ciepło.',
    ],
    photo:
      'Bowl of braised sauerkraut and white cabbage with strips of dark forest mushrooms, browned button mushrooms and soft onion',
    vessel: 'bowl',
  },
  {
    plan: 'KO-110',
    title: 'Łazanki z kapustą i grzybami',
    description:
      'Kwadratowe łazanki wymieszane z duszoną kapustą białą i kiszoną, suszonymi grzybami, pieczarkami i cebulą zrumienioną na maśle. Syte, wigilijne danie, które sprawdza się też jako zwykła zimowa kolacja.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PASTA',
    occasions: ['CHRISTMAS_EVE'],
    ingredients: [
      ['makaron łazanki', 200, 'g'],
      ['kapusta biała', 400, 'g'],
      ['kapusta kiszona', 150, 'g'],
      ['grzyb suszony', 20, 'g'],
      ['pieczarka', 200, 'g'],
      ['cebula', 150, 'g'],
      ['masło', 20, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kminek', 1, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby suszone zalej 200 ml gorącej wody i odstaw na 30 minut, potem pokrój w paski. Wodę z moczenia zachowaj.',
      'Kapustę białą poszatkuj, kiszoną posiekaj. Duś obie w garnku z wodą z grzybów, grzybami i kminkiem pod przykryciem 25 minut.',
      'Na patelni rozgrzej olej z masłem, zeszklij posiekaną cebulę, dodaj pokrojone pieczarki i smaż 8 minut na złoto.',
      'Łazanki ugotuj w osolonej wodzie według opisu na opakowaniu i odcedź.',
      'Połącz makaron z kapustą, grzybami i pieczarkami z cebulą, dopraw solą i pieprzem, podsmaż razem 3 minuty.',
    ],
    photo:
      'Square egg noodle pieces tossed with braised cabbage, sauerkraut, dark mushroom strips and golden sautéed button mushrooms and onion',
  },
  {
    plan: 'KO-111',
    title: 'Paszteciki z grzybami do barszczu',
    description:
      'Chrupiące paszteciki z ciasta francuskiego z farszem z suszonych grzybów, pieczarek i cebuli, doprawionym majerankiem. Idealne do czerwonego barszczu na Wigilię, a z gotowym ciastem robi się je w godzinę.',
    mealType: 'DINNER',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 70,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    equipment: ['OVEN'],
    ingredients: [
      ['ciasto francuskie', 375, 'g'],
      ['grzyb suszony', 30, 'g'],
      ['pieczarka', 300, 'g'],
      ['cebula', 150, 'g'],
      ['masło', 15, 'g'],
      ['bułka tarta', 20, 'g'],
      ['jajko', 1, 'szt'],
      ['majeranek', 1, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby suszone zalej gorącą wodą i namaczaj 30 minut, potem ugotuj je 15 minut i posiekaj drobno.',
      'Na maśle zeszklij posiekaną cebulę, dodaj drobno pokrojone pieczarki i smaż 10 minut, aż odparuje woda. Dodaj grzyby, majeranek, sól i pieprz, zagęść bułką tartą i ostudź.',
      'Nagrzej piekarnik do 200°C. Rozwiń ciasto francuskie i przekrój wzdłuż na dwa pasy.',
      'Rozłóż farsz wzdłuż każdego pasa, zwiń w rulon i sklej brzeg od spodu. Pokrój rulony ukośnie na kawałki szerokości 4 cm i ułóż na blasze z papierem.',
      'Posmaruj paszteciki roztrzepanym jajkiem i piecz 20–25 minut, aż będą złote i wyrośnięte. Podawaj ciepłe do barszczu.',
    ],
    photo:
      'Golden flaky puff pastry rolls cut diagonally showing dark mushroom filling, arranged on a plate beside a cup of red borscht',
  },
  {
    plan: 'KO-112',
    title: 'Kulebiak z kapustą i grzybami',
    description:
      'Drożdżowy kulebiak zawijany z farszem z kapusty kiszonej, suszonych grzybów i pieczarek, upieczony na złoty, błyszczący kolor. Tradycyjne wigilijne danie, które pokrojone w plastry podaje się z barszczem albo samo.',
    mealType: 'DINNER',
    difficulty: 'HARD',
    prepTimeMinutes: 180,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    occasions: ['CHRISTMAS_EVE'],
    features: ['OCCASIONAL'],
    equipment: ['OVEN'],
    ingredients: [
      ['mąka pszenna', 400, 'g'],
      ['drożdże', 20, 'g'],
      ['mleko', 200, 'ml'],
      ['masło', 60, 'g'],
      ['jajko', 3, 'szt'],
      ['cukier', 10, 'g'],
      ['kapusta kiszona', 400, 'g'],
      ['grzyb suszony', 30, 'g'],
      ['pieczarka', 250, 'g'],
      ['cebula', 150, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Grzyby suszone namocz w ciepłej wodzie na 2 godziny, ugotuj w niej 20 minut i posiekaj. Kapustę kiszoną posiekaj, zalej wywarem z grzybów i duś 40 minut, aż odparuje.',
      'Drożdże rozpuść w letnim mleku z cukrem i 2 łyżkami mąki, odstaw na 10 minut. Dodaj resztę mąki, 2 jajka, roztopione masło i sól, wyrabiaj 8 minut na gładkie ciasto. Przykryj i zostaw w ciepłym miejscu na 1 godzinę do podwojenia objętości.',
      'Na oleju zeszklij posiekaną cebulę, dodaj pokrojone pieczarki i smaż 8 minut. Połącz z kapustą i grzybami, dopraw pieprzem i ostudź całkowicie.',
      'Rozwałkuj ciasto na prostokąt 30 × 40 cm, rozłóż farsz, zostawiając wolne brzegi, i zwiń ciasno w rulon. Ułóż łączeniem do dołu na blasze z papierem i odstaw na 20 minut.',
      'Nagrzej piekarnik do 180°C. Posmaruj kulebiak roztrzepanym jajkiem, nakłuj widelcem w kilku miejscach i piecz 40–45 minut na złoty kolor.',
      'Ostudź 15 minut i pokrój w grube plastry.',
    ],
    photo:
      'Golden glossy rolled yeast loaf sliced to reveal a spiral of sauerkraut and mushroom filling, on a wooden board',
    vessel: 'board',
  },

  // ── Impreza ──
  {
    plan: 'KO-113',
    title: 'Tacos z mieloną wołowiną i serem',
    description:
      'Kukurydziane tortille z wołowiną podsmażoną z kminem i wędzoną papryką, z cheddarem, sałatą, pomidorem i salsą. Każdy składa swoje tacos sam, więc to świetne danie na wieczór ze znajomymi.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    occasions: ['PARTY'],
    ingredients: [
      ['tortilla kukurydziana', 6, 'szt'],
      ['wołowina mielona', 250, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['ser cheddar', 70, 'g'],
      ['sałata lodowa', 60, 'g'],
      ['pomidor', 150, 'g'],
      ['salsa pomidorowa', 80, 'g'],
      ['limonka', 30, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Na oleju zeszklij posiekaną cebulę, dodaj przeciśnięty czosnek i wołowinę. Smaż 8 minut, rozbijając mięso łopatką, aż się zrumieni.',
      'Dodaj kmin rzymski, wędzoną paprykę i sól, wlej 3 łyżki wody i smaż jeszcze 2 minuty.',
      'Sałatę poszatkuj, pomidor pokrój w kostkę, ser zetrzyj na tarce, a limonkę pokrój w ćwiartki.',
      'Tortille podgrzej na suchej patelni po 30 sekund z każdej strony.',
      'Nakładaj na tortille mięso, ser, sałatę i pomidor, polej salsą i skrop sokiem z limonki.',
    ],
    photo:
      'Three soft corn tortilla tacos filled with browned spiced ground beef, shredded cheddar, lettuce, diced tomato and salsa, with lime wedges',
  },
  {
    plan: 'KO-114',
    title: 'Sałatka meksykańska warstwowa z fasolą i kukurydzą',
    description:
      'Warstwy czerwonej fasoli, kukurydzy, sałaty, pomidorów, papryki i awokado z jogurtowym sosem limonkowym i cheddarem, zwieńczone pokruszonymi nachosami. Efektowna sałatka w szklanej misie na każdą imprezę.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 4,
    cuisine: 'MEXICAN',
    dishType: 'SALAD',
    occasions: ['PARTY'],
    ingredients: [
      ['fasola czerwona z puszki', 400, 'g'],
      ['kukurydza z puszki', 300, 'g'],
      ['sałata lodowa', 200, 'g'],
      ['pomidor', 300, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['awokado', 2, 'szt'],
      ['ser cheddar', 100, 'g'],
      ['jogurt grecki', 200, 'g'],
      ['limonka', 30, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['chips kukurydziany', 60, 'g'],
    ],
    steps: [
      'Fasolę i kukurydzę odsącz i przepłucz. Fasolę wymieszaj z kminem rzymskim.',
      'Sałatę poszatkuj, pomidory i paprykę pokrój w kostkę, a cebulę posiekaj drobno. Awokado pokrój w kostkę i skrop połową soku z limonki.',
      'Jogurt grecki wymieszaj z resztą soku z limonki.',
      'W szklanej misie układaj warstwami: fasolę, sałatę, kukurydzę, pomidory z cebulą, paprykę i awokado. Na wierzch wyłóż sos jogurtowy i posyp startym cheddarem.',
      'Tuż przed podaniem posyp pokruszonymi chipsami kukurydzianymi, żeby zostały chrupiące.',
    ],
    photo:
      'Glass bowl showing colorful layers of red kidney beans, shredded lettuce, sweet corn, diced tomato, pepper and avocado, topped with white yogurt dressing, grated cheddar and crushed tortilla chips',
    vessel: 'bowl',
  },
  {
    plan: 'KO-115',
    title: 'Sałatka z tortellini, szynką i kukurydzą',
    description:
      'Tortellini z serem wymieszane z szynką, kukurydzą, papryką, ogórkiem i szczypiorkiem w lekkim sosie majonezowo-jogurtowym. Sycąca sałatka na imprezę, którą można przygotować dzień wcześniej.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'SALAD',
    occasions: ['PARTY'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortellini z serem', 300, 'g'],
      ['szynka', 80, 'g'],
      ['kukurydza z puszki', 150, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['ogórek', 200, 'g'],
      ['majonez', 40, 'g'],
      ['jogurt naturalny', 150, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Tortellini ugotuj według opisu na opakowaniu, odcedź, przelej zimną wodą i ostudź.',
      'Szynkę pokrój w paski, paprykę i ogórek w kostkę, kukurydzę odsącz, a szczypiorek posiekaj.',
      'Wymieszaj majonez z jogurtem i pieprzem.',
      'Połącz tortellini z szynką i warzywami, dodaj sos i delikatnie wymieszaj. Schłodź w lodówce co najmniej 30 minut przed podaniem.',
    ],
    photo:
      'Bowl of cheese tortellini salad with ham strips, sweet corn, diced red pepper and cucumber in a light creamy dressing, sprinkled with chives',
    vessel: 'bowl',
  },
  {
    plan: 'KO-116',
    title: 'Mini burgery z wołowiną',
    description:
      'Małe wołowe burgery z cheddarem, pomidorkiem, ogórkiem konserwowym i sosem, zamknięte w niewielkich bułkach i spięte wykałaczką. Łatwe do zjedzenia w dwóch kęsach, więc znikają z imprezowego stołu pierwsze.',
    mealType: 'DINNER',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 4,
    cuisine: 'AMERICAN',
    dishType: 'SANDWICH',
    occasions: ['PARTY'],
    ingredients: [
      ['wołowina mielona', 400, 'g'],
      ['bułka', 240, 'g'],
      ['ser cheddar', 80, 'g'],
      ['pomidor koktajlowy', 120, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['ogórek konserwowy', 60, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['ketchup', 40, 'g'],
      ['musztarda', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wołowinę dopraw pieprzem, podziel na 8 części i uformuj małe, płaskie kotleciki średnicy trochę większej niż bułki.',
      'Rozgrzej patelnię grillową albo zwykłą i smaż kotleciki po 3 minuty z każdej strony. Pod koniec połóż na każdym plasterek cheddara i przykryj patelnię na minutę, aż ser się roztopi.',
      'Małe bułki przekrój i przypiecz przekrojem do dołu na suchej patelni przez minutę.',
      'Wymieszaj ketchup z musztardą. Pomidorki i ogórek pokrój w plasterki, a cebulę w cienkie krążki.',
      'Posmaruj bułki sosem, ułóż sałatę, kotlecik z serem, pomidorek, ogórek i cebulę, przykryj i spnij wykałaczką.',
    ],
    photo:
      'Eight mini beef sliders with melted cheddar, cherry tomato slices, pickles and lettuce in small toasted buns pierced with wooden skewers',
    vessel: 'board',
  },
];
