/**
 * Katalog 1000 — część NA: napoje NA-001 … NA-029 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Smoothie i koktajle ──
  {
    plan: 'NA-001',
    title: 'Koktajl proteinowy z kefirem, truskawkami i owsem',
    description:
      'Gęsty koktajl z kefiru, truskawek i płatków owsianych, wzmocniony porcją białka w proszku. Sycące drugie śniadanie albo szybki posiłek po treningu, gotowy w pięć minut.',
    mealType: 'SECOND_BREAKFAST',
    extraMealTypes: ['BREAKFAST'],
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['kefir', 400, 'ml'],
      ['truskawka', 250, 'g'],
      ['płatki owsiane', 40, 'g'],
      ['białko w proszku', 25, 'g'],
    ],
    steps: [
      'Truskawki umyj i oderwij szypułki; większe przekrój na pół.',
      'Wsyp do kielicha blendera płatki owsiane, wlej kefir i odstaw na 2 minuty, żeby płatki lekko zmiękły.',
      'Dodaj truskawki i białko w proszku, zmiksuj na najwyższych obrotach przez 40–60 sekund na gładki koktajl.',
      'Rozlej do szklanek i podawaj od razu.',
    ],
    photo:
      'Thick pale pink strawberry kefir shake with tiny oat flecks, topped with a halved fresh strawberry',
    vessel: 'cup',
  },
  {
    plan: 'NA-002',
    title: 'Zielone smoothie z jarmużem, gruszką i imbirem',
    description:
      'Soczysta gruszka i banan łagodzą smak jarmużu, a świeży imbir i cytryna dodają orzeźwienia. Roślinne smoothie z błonnikiem z siemienia lnianego, które syci aż do obiadu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['jarmuż', 60, 'g'],
      ['gruszka', 300, 'g'],
      ['banan', 1, 'szt'],
      ['imbir', 10, 'g'],
      ['mleko sojowe', 300, 'ml'],
      ['cytryna', 20, 'g'],
      ['siemię lniane', 10, 'g'],
    ],
    steps: [
      'Jarmuż umyj, oderwij liście od twardych łodyg i porwij na mniejsze kawałki.',
      'Gruszkę umyj, usuń gniazdo nasienne i pokrój w kostkę. Banana obierz, imbir obierz i drobno zetrzyj, z cytryny wyciśnij sok.',
      'Włóż do blendera jarmuż, gruszkę, banana, imbir i siemię lniane, wlej mleko sojowe i sok z cytryny.',
      'Miksuj 1–2 minuty, aż liście jarmużu całkiem się rozdrobnią, a smoothie będzie gładkie.',
      'Rozlej do szklanek i wypij od razu, póki kolor jest intensywnie zielony.',
    ],
    photo:
      'Vibrant green kale and pear smoothie with a smooth creamy surface, a thin pear slice on the rim',
    vessel: 'cup',
  },
  {
    plan: 'NA-003',
    title: 'Smoothie z mango, marchewką i jogurtem',
    description:
      'Pomarańczowe smoothie z dojrzałego mango, słodkiej marchewki i jogurtu naturalnego z sokiem pomarańczowym. Pełne beta-karotenu, kremowe i na tyle sycące, że zastępuje drugie śniadanie.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['mango', 300, 'g'],
      ['marchew', 150, 'g'],
      ['jogurt naturalny', 300, 'g'],
      ['sok pomarańczowy', 150, 'ml'],
      ['płatki owsiane', 30, 'g'],
    ],
    steps: [
      'Marchew obierz i zetrzyj na drobnych oczkach, żeby koktajl wyszedł gładki.',
      'Mango obierz, odkrój miąższ od pestki i pokrój w kostkę.',
      'Włóż do blendera marchew, mango i płatki owsiane, dodaj jogurt naturalny i wlej sok pomarańczowy.',
      'Miksuj około minuty na gładkie, kremowe smoothie i rozlej do szklanek.',
    ],
    photo:
      'Bright orange mango and carrot yogurt smoothie with a creamy texture and a few mango cubes on top',
    vessel: 'cup',
  },
  {
    plan: 'NA-004',
    title:
      'Koktajl czekoladowy z bananem i masłem orzechowym na napoju sojowym',
    description:
      'Czekoladowy koktajl z bananem, masłem orzechowym i tofu zmiksowanym na napoju sojowym. Smakuje jak deser, a daje solidną porcję roślinnego białka — dobry po treningu albo zamiast drugiego śniadania.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['mleko sojowe', 500, 'ml'],
      ['tofu', 150, 'g'],
      ['banan', 1, 'szt'],
      ['masło orzechowe', 30, 'g'],
      ['kakao', 15, 'g'],
    ],
    steps: [
      'Tofu odsącz z zalewy i pokrój w kostkę, banana obierz i pokrój w plasterki.',
      'Włóż do blendera tofu, banana, masło orzechowe i kakao, wlej napój sojowy.',
      'Miksuj na najwyższych obrotach 1 minutę, aż tofu zniknie bez śladu, a koktajl będzie aksamitny.',
      'Rozlej do szklanek i podawaj schłodzone.',
    ],
    photo:
      'Thick cocoa banana peanut butter shake with a velvety chocolate-brown surface, dusted with cocoa powder',
    vessel: 'cup',
  },
  {
    plan: 'NA-005',
    title: 'Smoothie jagodowe z jogurtem sojowym i owsem',
    description:
      'Fioletowe smoothie z mrożonych jagód, banana i jogurtu sojowego, zagęszczone płatkami owsianymi. Roślinne, gęste i lekko kwaskowe — pasuje na drugie śniadanie przez cały rok.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['jagoda mrożona', 250, 'g'],
      ['jogurt sojowy', 300, 'g'],
      ['płatki owsiane', 40, 'g'],
      ['banan', 1, 'szt'],
      ['mleko sojowe', 200, 'ml'],
    ],
    steps: [
      'Wsyp płatki owsiane do blendera, zalej napojem sojowym i odstaw na 2 minuty.',
      'Banana obierz i pokrój w plasterki.',
      'Dodaj do blendera banana, jogurt sojowy i mrożone jagody.',
      'Miksuj około minuty na gęste, gładkie smoothie i od razu rozlej do szklanek.',
    ],
    photo:
      'Deep purple blueberry smoothie with a thick creamy texture, a few whole blueberries and oat flakes on top',
    vessel: 'cup',
  },
  {
    plan: 'NA-006',
    title: 'Koktajl owsiany z jabłkiem i cynamonem',
    description:
      'Jesienny koktajl, który smakuje jak szarlotka: soczyste jabłko, płatki owsiane, migdały i cynamon zmiksowane z napojem owsianym. Roślinny, sycący i lekko słodki od syropu klonowego.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    seasons: ['AUTUMN'],
    equipment: ['BLENDER'],
    ingredients: [
      ['mleko owsiane', 400, 'ml'],
      ['płatki owsiane', 50, 'g'],
      ['jabłko', 300, 'g'],
      ['migdał', 20, 'g'],
      ['syrop klonowy', 10, 'g'],
      ['cynamon', 3, 'g'],
    ],
    steps: [
      'Płatki owsiane i migdały wsyp do blendera, zalej napojem owsianym i odstaw na 5 minut.',
      'Jabłko umyj, usuń gniazdo nasienne i pokrój w kostkę razem ze skórką.',
      'Dodaj jabłko, cynamon i syrop klonowy do blendera.',
      'Miksuj 1–2 minuty, aż migdały się rozdrobnią, a koktajl będzie gładki. Rozlej do szklanek i oprósz szczyptą cynamonu.',
    ],
    photo:
      'Creamy beige apple oat shake dusted with cinnamon, a thin red-skinned apple slice resting on the rim',
    vessel: 'cup',
  },
  {
    plan: 'NA-007',
    title: 'Smoothie z burakiem, malinami i bananem',
    description:
      'Rubinowe smoothie z surowego buraka, mrożonych malin i banana na napoju sojowym. Zimowa porcja warzyw i owoców w jednej szklance — słodkie, lekko kwaskowe i bez wyczuwalnej ziemistości.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    seasons: ['WINTER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['burak', 150, 'g'],
      ['malina mrożona', 200, 'g'],
      ['banan', 2, 'szt'],
      ['mleko sojowe', 300, 'ml'],
      ['siemię lniane', 10, 'g'],
    ],
    steps: [
      'Buraka obierz i zetrzyj na drobnych oczkach.',
      'Banany obierz i pokrój w plasterki.',
      'Włóż do blendera buraka, banany, mrożone maliny i siemię lniane, wlej napój sojowy.',
      'Miksuj 1–2 minuty na gładkie smoothie, rozlej do szklanek i podawaj od razu.',
    ],
    photo:
      'Deep ruby red beetroot and raspberry smoothie with a smooth glossy surface, topped with a few frozen raspberries',
    vessel: 'cup',
  },
  {
    plan: 'NA-008',
    title: 'Koktajl z twarogiem i wiśniami',
    description:
      'Kwaskowe wiśnie zmiksowane z twarogiem i mlekiem, osłodzone odrobiną miodu. Gęsty, różowy koktajl z dużą porcją białka — sprawdza się jako drugie śniadanie i szybki posiłek po treningu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['ser twaróg półtłusty', 200, 'g'],
      ['wiśnia mrożona', 250, 'g'],
      ['mleko', 300, 'ml'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Twaróg rozkrusz widelcem i włóż do blendera.',
      'Dodaj mrożone wiśnie bez pestek i miód, wlej mleko.',
      'Miksuj około minuty, aż twaróg całkiem się rozpuści, a koktajl będzie gładki.',
      'Rozlej do szklanek i podawaj od razu.',
    ],
    photo:
      'Thick pink cherry and quark shake with a creamy surface, a few dark red cherries on top',
    vessel: 'cup',
  },
  {
    plan: 'NA-009',
    title: 'Smoothie tropikalne z ananasem i kokosem',
    description:
      'Ananas, mango i banan zmiksowane z mlekiem kokosowym i sokiem z limonki. Kremowe smoothie o smaku wakacji, całkowicie roślinne i gotowe w pięć minut.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['ananas', 300, 'g'],
      ['mango', 150, 'g'],
      ['banan', 1, 'szt'],
      ['mleko kokosowe z puszki', 100, 'ml'],
      ['mleko migdałowe', 200, 'ml'],
      ['limonka', 20, 'g'],
    ],
    steps: [
      'Ananasa obierz, usuń twardy środek i pokrój miąższ w kostkę. Mango obierz i pokrój, banana obierz.',
      'Z limonki wyciśnij sok.',
      'Włóż owoce do blendera, wlej mleko kokosowe, napój migdałowy i sok z limonki.',
      'Miksuj około minuty na gładkie smoothie, rozlej do szklanek i podawaj schłodzone.',
    ],
    photo:
      'Creamy pale yellow pineapple, mango and coconut smoothie with a thick smooth surface and a small pineapple wedge on the rim',
    vessel: 'cup',
  },
  {
    plan: 'NA-010',
    title: 'Frappe proteinowe ze skyrem i kawą',
    description:
      'Mrożona kawa zmiksowana ze skyrem, mlekiem i bananem na gęste, spienione frappe. Kofeina i solidna porcja białka w jednym — idealne na drugie śniadanie w ciepły dzień.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['skyr naturalny', 300, 'g'],
      ['mleko', 200, 'ml'],
      ['kawa rozpuszczalna', 6, 'g'],
      ['banan', 1, 'szt'],
      ['kakao', 5, 'g'],
    ],
    steps: [
      'Rozpuść kawę w 50 ml gorącej wody i ostudź; najszybciej wstaw kubek na 5 minut do zamrażarki.',
      'Banana obierz i pokrój w plasterki.',
      'Włóż do blendera skyr, banana i kakao, wlej mleko i ostudzoną kawę, dodaj garść kostek lodu.',
      'Miksuj około minuty, aż frappe się spieni, i rozlej do wysokich szklanek.',
    ],
    photo:
      'Frothy light brown coffee frappe with a thick foam top and a light dusting of cocoa powder',
    vessel: 'cup',
  },
  {
    plan: 'NA-011',
    title: 'Koktajl dyniowy z cynamonem',
    description:
      'Kremowy koktajl z ugotowanej dyni, banana i jogurtu, doprawiony cynamonem, imbirem i gałką muszkatołową. Smakuje jak jesienny deser, a jest pełnowartościowym drugim śniadaniem.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    seasons: ['AUTUMN'],
    equipment: ['BLENDER'],
    ingredients: [
      ['dynia', 300, 'g'],
      ['mleko', 300, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['banan', 1, 'szt'],
      ['płatki owsiane', 30, 'g'],
      ['syrop klonowy', 20, 'g'],
      ['cynamon', 3, 'g'],
      ['imbir mielony', 1, 'g'],
      ['gałka muszkatołowa', 0.5, 'g'],
    ],
    steps: [
      'Dynię obierz, usuń pestki i pokrój w kostkę. Gotuj na parze albo w niewielkiej ilości wody 12–15 minut, aż będzie miękka.',
      'Odcedź dynię i ostudź ją 10 minut; możesz przyspieszyć, rozkładając kostki na talerzu.',
      'Banana obierz. Włóż do blendera dynię, banana, jogurt, płatki owsiane, syrop klonowy, cynamon, imbir i gałkę muszkatołową.',
      'Wlej zimne mleko i miksuj 1–2 minuty na gładki, gęsty koktajl.',
      'Rozlej do szklanek i oprósz szczyptą cynamonu.',
    ],
    photo:
      'Thick creamy orange pumpkin spice shake with a smooth surface, dusted with a pinch of ground cinnamon',
    vessel: 'cup',
  },
  {
    plan: 'NA-012',
    title: 'Smoothie truskawkowo-rabarbarowe',
    description:
      'Wiosenne smoothie z krótko podduszonego rabarbaru i świeżych truskawek z jogurtem naturalnym. Rabarbar dodaje przyjemnej kwaskowości, a miód i płatki owsiane równoważą smak i sycą.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DRINK',
    seasons: ['SPRING'],
    equipment: ['BLENDER'],
    ingredients: [
      ['rabarbar', 200, 'g'],
      ['truskawka', 300, 'g'],
      ['jogurt naturalny', 250, 'g'],
      ['płatki owsiane', 30, 'g'],
      ['miód', 20, 'g'],
    ],
    steps: [
      'Rabarbar umyj, obierz z włókien i pokrój w kawałki. Duś w małym garnku z 3 łyżkami wody przez 8 minut, aż się rozpadnie.',
      'Wmieszaj do rabarbaru miód i ostudź go przez 10 minut.',
      'Truskawki umyj i oderwij szypułki.',
      'Włóż do blendera rabarbar, truskawki, jogurt i płatki owsiane, miksuj około minuty na gładko.',
      'Rozlej do szklanek i podawaj schłodzone.',
    ],
    photo:
      'Thick pastel pink strawberry rhubarb smoothie with a creamy surface and tiny oat flecks, topped with a halved fresh strawberry',
    vessel: 'cup',
  },
  {
    plan: 'NA-013',
    title: 'Koktajl malinowy z maślanką',
    description:
      'Klasyczny letni koktajl z maślanki i świeżych malin z bananem i odrobiną miodu. Orzeźwiający, lekko kwaskowy i lekki — dobry na upalne przedpołudnie.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DRINK',
    seasons: ['SUMMER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['maślanka', 500, 'ml'],
      ['malina', 250, 'g'],
      ['banan', 1, 'szt'],
      ['miód', 10, 'g'],
    ],
    steps: [
      'Maliny delikatnie przepłucz i osącz na sitku.',
      'Banana obierz i pokrój w plasterki.',
      'Włóż maliny, banana i miód do blendera, wlej schłodzoną maślankę.',
      'Miksuj 30–40 sekund, rozlej do szklanek i podawaj od razu.',
    ],
    photo:
      'Light pink raspberry buttermilk shake with a frothy top and a few whole fresh raspberries floating on it',
    vessel: 'cup',
  },
  {
    plan: 'NA-014',
    title: 'Lassi z mango',
    description:
      'Indyjski napój jogurtowy z dojrzałego mango, jogurtu naturalnego i mleka, z nutą kardamonu. Gęsty, aksamitny i orzeźwiający, pasuje na drugie śniadanie i do ostrych potraw.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['mango', 300, 'g'],
      ['jogurt naturalny', 300, 'g'],
      ['mleko', 150, 'ml'],
      ['miód', 15, 'g'],
      ['kardamon mielony', 1, 'g'],
    ],
    steps: [
      'Mango obierz, odkrój miąższ od pestki i pokrój w kostkę.',
      'Włóż mango do blendera, dodaj jogurt, miód i kardamon, wlej zimne mleko.',
      'Miksuj około minuty na gładki, gęsty napój.',
      'Rozlej do szklanek, oprósz szczyptą kardamonu i podawaj mocno schłodzone.',
    ],
    photo:
      'Thick golden yellow mango lassi with a silky surface, sprinkled with a pinch of ground cardamom',
    vessel: 'cup',
  },
  {
    plan: 'NA-015',
    title: 'Smoothie ze szpinakiem, awokado i kiwi',
    description:
      'Zielone smoothie ze szpinaku, kremowego awokado, kiwi i banana na napoju migdałowym. Roślinne, pełne zdrowych tłuszczów i witaminy C, z orzeźwiającą nutą limonki.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['szpinak', 60, 'g'],
      ['awokado', 1, 'szt'],
      ['kiwi', 200, 'g'],
      ['banan', 1, 'szt'],
      ['mleko migdałowe', 300, 'ml'],
      ['limonka', 20, 'g'],
      ['syrop klonowy', 10, 'g'],
    ],
    steps: [
      'Szpinak umyj i osącz. Awokado przekrój, usuń pestkę i wydrąż miąższ łyżką.',
      'Kiwi i banana obierz i pokrój, z limonki wyciśnij sok.',
      'Włóż do blendera szpinak, awokado, kiwi i banana, wlej napój migdałowy, sok z limonki i syrop klonowy.',
      'Miksuj 1–2 minuty na gładkie smoothie i od razu rozlej do szklanek.',
    ],
    photo:
      'Creamy bright green spinach avocado kiwi smoothie with a kiwi slice on the rim',
    vessel: 'cup',
  },
  {
    plan: 'NA-016',
    title: 'Koktajl śniadaniowy z owsem, jogurtem i borówkami',
    description:
      'Owsianka do picia: płatki owsiane, jogurt naturalny i borówki zmiksowane z mlekiem. Szybkie, lekkie śniadanie na wynos, które syci do południa.',
    mealType: 'BREAKFAST',
    extraMealTypes: ['SECOND_BREAKFAST'],
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['płatki owsiane', 60, 'g'],
      ['jogurt naturalny', 300, 'g'],
      ['borówka', 200, 'g'],
      ['mleko', 200, 'ml'],
      ['miód', 10, 'g'],
    ],
    steps: [
      'Wsyp płatki owsiane do blendera, zalej mlekiem i odstaw na 5 minut, żeby napęczniały.',
      'Borówki przepłucz i osącz.',
      'Dodaj do blendera jogurt, borówki i miód.',
      'Miksuj około minuty na gęsty koktajl, rozlej do szklanek albo butelki na wynos.',
    ],
    photo:
      'Thick lavender blueberry oat yogurt shake with visible oat flecks and fresh blueberries on top',
    vessel: 'cup',
  },
  {
    plan: 'NA-017',
    title: 'Koktajl z kefiru, banana i siemienia lnianego',
    description:
      'Prosty koktajl z kefiru i dojrzałych bananów z mielonym siemieniem lnianym i cynamonem. Lekki, dobry dla trawienia i gotowy w kilka minut z tego, co zwykle jest w domu.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['kefir', 500, 'ml'],
      ['banan', 2, 'szt'],
      ['siemię lniane', 15, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Siemię lniane zmiel w młynku albo kup od razu mielone.',
      'Banany obierz i pokrój w plasterki.',
      'Włóż banany, siemię i cynamon do blendera, wlej kefir.',
      'Miksuj 30–40 sekund, rozlej do szklanek i wypij od razu, zanim siemię zgęstnieje.',
    ],
    photo:
      'Creamy off-white banana kefir shake with specks of ground flaxseed and a light dusting of cinnamon',
    vessel: 'cup',
  },
  {
    plan: 'NA-018',
    title: 'Koktajl morelowy ze skyrem',
    description:
      'Letni koktajl z soczystych moreli i skyru, osłodzony miodem. Aksamitny, pomarańczowy i bogaty w białko, więc spokojnie zastąpi drugie śniadanie.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    seasons: ['SUMMER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['morela', 300, 'g'],
      ['skyr naturalny', 300, 'g'],
      ['mleko', 150, 'ml'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Morele umyj, przekrój na pół i usuń pestki.',
      'Włóż morele do blendera, dodaj skyr i miód, wlej zimne mleko.',
      'Miksuj około minuty na gładki, gęsty koktajl.',
      'Rozlej do szklanek i podawaj schłodzone.',
    ],
    photo:
      'Smooth apricot orange skyr shake with a creamy thick texture and a fresh apricot half on the rim',
    vessel: 'cup',
  },
  {
    plan: 'NA-019',
    title: 'Koktajl malinowo-bananowy na napoju owsianym',
    description:
      'Słodki od bananów, różowy od malin koktajl na napoju owsianym, który dzieci wypijają do dna. Roślinny, bez dodatku cukru poza odrobiną syropu klonowego.',
    mealType: 'SECOND_BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['BLENDER'],
    ingredients: [
      ['malina', 200, 'g'],
      ['banan', 2, 'szt'],
      ['mleko owsiane', 400, 'ml'],
      ['syrop klonowy', 10, 'g'],
    ],
    steps: [
      'Maliny delikatnie przepłucz i osącz na sitku.',
      'Banany obierz i pokrój w plasterki.',
      'Włóż owoce do blendera, dodaj syrop klonowy i wlej napój owsiany.',
      'Miksuj około minuty na gładki koktajl i rozlej do kubków.',
    ],
    photo:
      'Pastel pink raspberry banana oat milk shake with a smooth surface, a few raspberries and banana slices on top',
    vessel: 'cup',
  },

  // ── Soki i napoje zimne ──
  {
    plan: 'NA-020',
    title: 'Sok z buraka, marchewki i jabłka',
    description:
      'Świeżo wyciskany sok z buraka, marchwi i jabłka z odrobiną cytryny i imbiru. Słodki, intensywnie bordowy i rozgrzewający — zimowa porcja witamin do posiłku.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    seasons: ['WINTER'],
    equipment: ['JUICER'],
    features: ['SIDE'],
    ingredients: [
      ['burak', 200, 'g'],
      ['marchew', 250, 'g'],
      ['jabłko', 250, 'g'],
      ['cytryna', 30, 'g'],
      ['imbir', 10, 'g'],
    ],
    steps: [
      'Buraka i marchew dokładnie umyj i obierz, pokrój na kawałki pasujące do otworu sokowirówki.',
      'Jabłka umyj i pokrój na ćwiartki, cytrynę i imbir obierz.',
      'Przepuść przez sokowirówkę na przemian buraka, marchew, jabłka, imbir i cytrynę.',
      'Wymieszaj sok, rozlej do szklanek i wypij od razu, póki jest świeży.',
    ],
    photo:
      'Deep burgundy beet carrot apple juice with a light foam on top, an apple slice on the rim',
    vessel: 'cup',
  },
  {
    plan: 'NA-021',
    title: 'Sok z marchwi, pomarańczy i imbiru',
    description:
      'Pomarańczowy sok ze świeżej marchwi i soczystych pomarańczy z wyraźną nutą imbiru. Słodki, orzeźwiający i gotowy w kwadrans — dobry dodatek do śniadania.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['JUICER'],
    features: ['SIDE'],
    ingredients: [
      ['marchew', 400, 'g'],
      ['pomarańcza', 400, 'g'],
      ['imbir', 20, 'g'],
    ],
    steps: [
      'Marchew umyj, obierz i pokrój na kawałki pasujące do sokowirówki.',
      'Pomarańcze obierz ze skórki i podziel na cząstki, imbir obierz.',
      'Przepuść przez sokowirówkę marchew, pomarańcze i imbir.',
      'Wymieszaj sok, rozlej do szklanek i podawaj od razu, najlepiej schłodzony.',
    ],
    photo:
      'Vivid orange carrot, orange and ginger juice with a thin pale foam layer on top',
    vessel: 'cup',
  },
  {
    plan: 'NA-022',
    title: 'Zielony sok z selerem naciowym, ogórkiem i jabłkiem',
    description:
      'Orzeźwiający zielony sok z selera naciowego, ogórka i jabłka z sokiem z cytryny i natką. Lekki, wytrawny w smaku i dobrze gasi pragnienie przy posiłku.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    equipment: ['JUICER'],
    features: ['SIDE'],
    ingredients: [
      ['seler naciowy', 200, 'g'],
      ['ogórek', 300, 'g'],
      ['jabłko', 300, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Seler naciowy, ogórek i natkę umyj; seler i ogórek pokrój na kawałki.',
      'Jabłka umyj i pokrój na ćwiartki, cytrynę obierz.',
      'Przepuść przez sokowirówkę seler, ogórek, natkę, jabłka i cytrynę.',
      'Wymieszaj, rozlej do szklanek i wypij od razu.',
    ],
    photo:
      'Bright green celery, cucumber and apple juice with a light foam top, a short leafy celery stalk standing in the drink',
    vessel: 'cup',
  },
  {
    plan: 'NA-023',
    title: 'Kompot z suszu',
    description:
      'Tradycyjny wigilijny kompot z suszonych śliwek, moreli, fig i rodzynek, doprawiony goździkami i cynamonem. Lekko wędzony w smaku, słodki i aromatyczny — nieodłączny napój świątecznej kolacji.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'DRINK',
    occasions: ['CHRISTMAS_EVE'],
    features: ['SIDE', 'OCCASIONAL'],
    ingredients: [
      ['śliwka suszona', 100, 'g'],
      ['morela suszona', 50, 'g'],
      ['figi suszone', 50, 'g'],
      ['rodzynka', 30, 'g'],
      ['cukier', 20, 'g'],
      ['cytryna', 30, 'g'],
      ['goździki', 1, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Susz przepłucz w ciepłej wodzie; większe owoce przekrój na pół.',
      'Wsyp susz do garnka, dodaj goździki i cynamon, wlej 1,5 litra zimnej wody.',
      'Zagotuj i gotuj pod przykryciem na małym ogniu 25 minut, aż owoce zmiękną.',
      'Zdejmij z ognia, dodaj cukier i sok wyciśnięty z cytryny, wymieszaj.',
      'Odstaw na 10 minut, żeby się przegryzło. Podawaj ciepły albo schłodzony, razem z owocami.',
    ],
    photo:
      'Dark amber dried fruit compote with plump stewed prunes, dried apricots, fig halves and raisins floating in it',
    vessel: 'cup',
  },
  {
    plan: 'NA-024',
    title: 'Lemoniada arbuzowa z miętą',
    description:
      'Różowa lemoniada ze zmiksowanego arbuza, limonki i świeżej mięty, dopełniona wodą gazowaną. Orzeźwia w upał i świetnie wygląda w dzbanku na letnim przyjęciu.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    seasons: ['SUMMER'],
    occasions: ['PARTY'],
    equipment: ['BLENDER'],
    features: ['SIDE'],
    ingredients: [
      ['arbuz', 800, 'g'],
      ['limonka', 60, 'g'],
      ['mięta', 10, 'g'],
      ['cukier', 20, 'g'],
      ['woda gazowana', 500, 'ml'],
    ],
    steps: [
      'Arbuza obierz, pokrój w kostkę i usuń większe pestki.',
      'Zmiksuj arbuza blenderem na gładko i przecedź przez sitko do dzbanka.',
      'Z limonki wyciśnij sok, dodaj do dzbanka razem z cukrem i mieszaj, aż cukier się rozpuści.',
      'Liście mięty lekko rozgnieć w dłoniach i włóż do dzbanka, dodaj garść kostek lodu.',
      'Tuż przed podaniem dolej schłodzoną wodę gazowaną i delikatnie wymieszaj.',
    ],
    photo:
      'Bright pink sparkling watermelon lemonade with ice cubes and bruised fresh mint leaves floating on top, tiny bubbles on the surface',
    vessel: 'cup',
  },

  // ── Ciepłe ──
  {
    plan: 'NA-025',
    title: 'Kakao z cynamonem',
    description:
      'Domowe kakao na mleku z prawdziwego kakao, słodzone odrobiną cukru i doprawione cynamonem. Rozgrzewający napój na zimowe popołudnie, który dzieci lubią bardziej niż kupne mieszanki.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DRINK',
    seasons: ['WINTER'],
    ingredients: [
      ['mleko', 500, 'ml'],
      ['kakao', 15, 'g'],
      ['cukier', 15, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Wymieszaj w garnku kakao, cukier i cynamon.',
      'Wlej 100 ml mleka i rozetrzyj trzepaczką na gładką pastę bez grudek.',
      'Dolej resztę mleka i podgrzewaj na średnim ogniu 4–5 minut, stale mieszając, aż kakao będzie gorące, ale nie zacznie kipieć.',
      'Rozlej do kubków i oprósz szczyptą cynamonu.',
    ],
    photo:
      'Steaming hot cocoa with a smooth milky brown surface and a light dusting of ground cinnamon',
    vessel: 'cup',
  },
  {
    plan: 'NA-026',
    title: 'Złote mleko z kurkumą',
    description:
      'Rozgrzewający napój na napoju migdałowym z mlekiem kokosowym, kurkumą, świeżym imbirem i cynamonem. Szczypta pieprzu wydobywa aromat kurkumy, a syrop klonowy łagodzi smak.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'DRINK',
    seasons: ['WINTER'],
    ingredients: [
      ['mleko migdałowe', 400, 'ml'],
      ['mleko kokosowe z puszki', 50, 'ml'],
      ['kurkuma', 3, 'g'],
      ['imbir', 10, 'g'],
      ['cynamon', 2, 'g'],
      ['pieprz czarny', 0.5, 'g'],
      ['syrop klonowy', 15, 'g'],
    ],
    steps: [
      'Imbir obierz i zetrzyj na drobnych oczkach.',
      'Wlej do garnka napój migdałowy i mleko kokosowe, dodaj imbir, kurkumę, cynamon i pieprz.',
      'Podgrzewaj na małym ogniu 5 minut, często mieszając trzepaczką, nie doprowadzając do wrzenia.',
      'Zdejmij z ognia, wmieszaj syrop klonowy i przecedź przez sitko do kubków.',
    ],
    photo: 'Warm golden yellow turmeric latte with a light creamy froth on top',
    vessel: 'cup',
  },
  {
    plan: 'NA-027',
    title: 'Czekolada na gorąco',
    description:
      'Gęsta czekolada do picia z gorzkiej czekolady rozpuszczonej w mleku i zagęszczonej odrobiną skrobi. Aksamitna, intensywna i nie za słodka — mały deser w kubku na zimowe popołudnie.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DRINK',
    seasons: ['WINTER'],
    ingredients: [
      ['mleko', 400, 'ml'],
      ['czekolada gorzka', 60, 'g'],
      ['kakao', 5, 'g'],
      ['cukier', 10, 'g'],
      ['mąka ziemniaczana', 5, 'g'],
    ],
    steps: [
      'Czekoladę gorzką posiekaj drobno.',
      'W kubku wymieszaj 50 ml zimnego mleka z mąką ziemniaczaną, kakao i cukrem na gładką zawiesinę.',
      'Resztę mleka podgrzej w garnku prawie do wrzenia, zdejmij z ognia i wsyp czekoladę; mieszaj, aż się rozpuści.',
      'Wlej zawiesinę i gotuj na małym ogniu 1–2 minuty, stale mieszając, aż czekolada zgęstnieje.',
      'Rozlej do kubków i podawaj od razu.',
    ],
    photo:
      'Thick glossy dark hot chocolate with a rich velvety surface, steaming',
    vessel: 'cup',
  },
  {
    plan: 'NA-028',
    title: 'Chai latte',
    description:
      'Indyjska herbata z mlekiem parzona z cynamonem, kardamonem, imbirem, goździkami i pieprzem, osłodzona miodem. Korzenna, rozgrzewająca i o wiele bardziej aromatyczna niż gotowe mieszanki.',
    mealType: 'AFTERNOON_SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'DRINK',
    seasons: ['WINTER'],
    ingredients: [
      ['herbata czarna', 6, 'g'],
      ['mleko', 400, 'ml'],
      ['imbir', 10, 'g'],
      ['cynamon', 2, 'g'],
      ['kardamon mielony', 1, 'g'],
      ['goździki', 0.5, 'g'],
      ['pieprz czarny', 0.5, 'g'],
      ['miód', 20, 'g'],
    ],
    steps: [
      'Imbir obierz i pokrój w cienkie plasterki.',
      'Zagotuj w garnku 200 ml wody z imbirem, cynamonem, kardamonem, goździkami i pieprzem, gotuj na małym ogniu 5 minut.',
      'Wsyp herbatę, wlej mleko i podgrzewaj 3–4 minuty, nie doprowadzając do wrzenia.',
      'Przecedź przez sitko do kubków i dosłódź miodem.',
      'Jeśli lubisz piankę, spień napój przez kilka sekund trzepaczką albo spieniaczem.',
    ],
    photo:
      'Creamy light caramel-colored chai latte with a soft milky foam top, steaming',
    vessel: 'cup',
  },
  {
    plan: 'NA-029',
    title: 'Bezalkoholowy grzaniec z soku jabłkowego',
    description:
      'Gorący sok jabłkowy z pomarańczą, goździkami, cynamonem, imbirem i kardamonem. Pachnie jak święta, rozgrzewa po spacerze i mogą go pić wszyscy, także dzieci i kierowcy.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'DRINK',
    seasons: ['WINTER'],
    occasions: ['CHRISTMAS'],
    features: ['SIDE'],
    ingredients: [
      ['sok jabłkowy', 1000, 'ml'],
      ['pomarańcza', 180, 'g'],
      ['imbir', 15, 'g'],
      ['cynamon', 3, 'g'],
      ['goździki', 1, 'g'],
      ['kardamon mielony', 1, 'g'],
    ],
    steps: [
      'Pomarańczę sparz wrzątkiem i pokrój w plastry, imbir obierz i pokrój w plasterki.',
      'Wlej sok jabłkowy do garnka, dodaj pomarańczę, imbir, cynamon, goździki i kardamon.',
      'Podgrzewaj na małym ogniu pod przykryciem 15 minut, nie doprowadzając do wrzenia.',
      'Przecedź do kubków lub szklanek do grzańca i udekoruj plasterkiem pomarańczy.',
    ],
    photo:
      'Steaming clear amber mulled apple juice with a thin fresh orange slice floating on top',
    vessel: 'cup',
  },
];
