/**
 * Katalog 1000 — część OB-a: obiady OB-001 … OB-028 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'OB-001',
    title: 'Makaron z kurczakiem, cukinią i pomidorkami',
    description:
      'Świderki z soczystym kurczakiem, podsmażoną cukinią i pomidorkami koktajlowymi, które puszczają sok i tworzą lekki sos. Szybki, sycący obiad z jednej patelni, posypany parmezanem i świeżą bazylią.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron świder', 160, 'g'],
      ['filet z kurczaka', 300, 'g'],
      ['cukinia', 250, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['ser parmezan', 20, 'g'],
      ['bazylia', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nastaw osoloną wodę i ugotuj makaron al dente według instrukcji na opakowaniu, zwykle 9–10 minut. Odlej, zachowując pół szklanki wody z gotowania.',
      'Kurczaka pokrój w kostkę, dopraw solą i pieprzem. Cukinię przekrój wzdłuż i pokrój w półplasterki, pomidorki przekrój na pół, czosnek posiekaj.',
      'Rozgrzej oliwę na dużej patelni i smaż kurczaka 5–6 minut, aż się zrumieni ze wszystkich stron.',
      'Dodaj cukinię i czosnek, smaż 3 minuty, potem wrzuć pomidorki i duś 3–4 minuty, aż zmiękną i puszczą sok.',
      'Wmieszaj makaron i kilka łyżek wody z gotowania, podgrzewaj minutę, aż sos oblepi makaron.',
      'Nałóż na talerze, posyp startym parmezanem i listkami bazylii.',
    ],
    photo:
      'Fusilli pasta tossed with golden seared chicken cubes, green zucchini half-moons and burst cherry tomatoes, topped with grated parmesan and fresh basil leaves',
  },
  {
    plan: 'OB-002',
    title: 'Kotlety z indyka z kaszą i surówką',
    description:
      'Delikatne kotleciki z mielonego indyka z cebulą i majerankiem, podane z kaszą gryczaną i chrupiącą surówką z marchewki i jabłka. Klasyczny domowy obiad, lżejszy od schabowego i gotowy w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['indyk mielony', 300, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 25, 'g'],
      ['cebula', 50, 'g'],
      ['majeranek', 1, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kasza gryczana', 120, 'g'],
      ['marchew', 150, 'g'],
      ['jabłko', 150, 'g'],
      ['jogurt naturalny', 50, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę gryczaną przepłucz, zalej 250 ml wrzącej osolonej wody i gotuj pod przykryciem na małym ogniu 15 minut, potem odstaw na 5 minut.',
      'Cebulę posiekaj bardzo drobno. Wymieszaj indyka z jajkiem, bułką tartą, cebulą, majerankiem, solą i pieprzem, wyrabiaj minutę.',
      'Mokrymi dłońmi uformuj 6 płaskich kotletów. Smaż je na rozgrzanym oleju na średnim ogniu po 4–5 minut z każdej strony, aż będą złote i przepieczone w środku.',
      'Marchew i jabłko zetrzyj na tarce o grubych oczkach, skrop sokiem z cytryny i wymieszaj z jogurtem naturalnym oraz szczyptą soli.',
      'Podawaj kotlety z kaszą i surówką.',
    ],
    photo:
      'Three golden pan-fried turkey patties next to a mound of fluffy brown buckwheat groats and a fresh grated carrot and apple slaw with yogurt',
  },
  {
    plan: 'OB-003',
    title: 'Makaron z brokułem, czosnkiem i parmezanem',
    description:
      'Włoska klasyka z kuchni domowej: penne z brokułem rozgotowanym na aksamitny sos z oliwą, czosnkiem i odrobiną chili, zakończone parmezanem i skórką z cytryny. Tanie, szybkie i pełne smaku.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron penne', 180, 'g'],
      ['brokuł', 400, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 25, 'ml'],
      ['ser parmezan', 40, 'g'],
      ['płatki chili', 1, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Brokuł podziel na małe różyczki, a łodygę obierz i pokrój w plasterki. Czosnek pokrój w cienkie plasterki.',
      'Zagotuj osoloną wodę, wrzuć makaron, a po 4 minutach dorzuć brokuł i gotuj razem jeszcze 6–7 minut. Odlej, zachowując szklankę wody z gotowania.',
      'Na dużej patelni rozgrzej oliwę, podsmaż czosnek z płatkami chili przez minutę, aż zacznie się złocić.',
      'Wrzuć makaron z brokułem, dolej pół szklanki wody z gotowania i mieszaj 2 minuty, rozgniatając część różyczek łyżką na sos.',
      'Zdejmij z ognia, wmieszaj połowę startego parmezanu i skórkę otartą z cytryny, skrop sokiem. Podawaj posypane resztą sera.',
    ],
    photo:
      'Penne pasta coated in a glossy broccoli and garlic sauce with small green florets, flecks of red chili, grated parmesan and lemon zest',
  },
  {
    plan: 'OB-004',
    title: 'Łosoś z patelni z kaszą i fasolką szparagową',
    description:
      'Filet z łososia usmażony na chrupiącą skórkę, podany z puszystą kaszą jaglaną i fasolką szparagową z masłem i koperkiem. Porcja dobrych tłuszczów i białka na obiad gotowy w niecałe pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    ingredients: [
      ['łosoś', 300, 'g'],
      ['kasza jaglana', 100, 'g'],
      ['fasolka szparagowa', 300, 'g'],
      ['masło', 10, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['cytryna', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['koperek', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz gorącą wodą, zalej 250 ml wrzącej osolonej wody i gotuj pod przykryciem 15 minut na małym ogniu.',
      'Fasolce odetnij końcówki i gotuj ją w osolonej wodzie 6–7 minut, odcedź.',
      'Łososia osusz ręcznikiem, dopraw solą i pieprzem. Rozgrzej olej na patelni i połóż rybę skórą do dołu; smaż 4–5 minut, przewróć i smaż jeszcze 2–3 minuty.',
      'Na drugiej patelni rozpuść masło z posiekanym czosnkiem, wrzuć fasolkę i obtocz ją przez minutę, posyp posiekanym koperkiem.',
      'Podawaj łososia z kaszą i fasolką, skrop sokiem z cytryny.',
    ],
    photo:
      'Pan-seared salmon fillet with crispy golden skin beside fluffy yellow millet and buttery green beans sprinkled with dill, with a lemon wedge',
  },
  {
    plan: 'OB-005',
    title: 'Indyk z pieczarkami w sosie śmietanowym z makaronem',
    description:
      'Paski indyka duszone z pieczarkami i cebulą w kremowym sosie śmietanowym, podane ze wstążkami tagliatelle i natką pietruszki. Comfort food na co dzień, które powstaje szybciej, niż zagotuje się woda na drugi raz.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PASTA',
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['pieczarka', 250, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 1, 'szt'],
      ['śmietanka 18', 100, 'ml'],
      ['makaron tagliatelle', 150, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron w osolonej wodzie al dente według opakowania, zwykle 7–8 minut, i odcedź.',
      'Indyka pokrój w cienkie paski, pieczarki w plasterki, cebulę w kostkę, czosnek posiekaj.',
      'Na rozgrzanym oleju smaż indyka 4–5 minut, aż się zrumieni, dopraw solą i pieprzem, zdejmij na talerz.',
      'Na tę samą patelnię wrzuć cebulę i pieczarki, smaż 5–6 minut, aż odparuje woda, dodaj czosnek na ostatnią minutę.',
      'Wlej śmietankę, oddaj indyka, zagotuj i duś 2–3 minuty, aż sos zgęstnieje. Wymieszaj z makaronem i posyp posiekaną natką.',
    ],
    photo:
      'Tagliatelle ribbons in a creamy sauce with golden turkey strips and sliced brown mushrooms, sprinkled with chopped fresh parsley',
  },
  {
    plan: 'OB-006',
    title: 'Makaron z sosem z ciecierzycy i pomidorów',
    description:
      'Gęsty, rozgrzewający sos pomidorowy z ciecierzycą, czosnkiem i oregano, którym oblepia się razowy makaron. Roślinna odpowiedź na makaron z mięsem: sycąca, tania i gotowa w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron razowy', 160, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['oregano', 1, 'g'],
      ['płatki chili', 1, 'g'],
      ['bazylia', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, ciecierzycę odcedź i przepłucz.',
      'Rozgrzej oliwę w rondlu, zeszklij cebulę przez 4 minuty, dodaj czosnek, oregano i płatki chili, smaż minutę.',
      'Wmieszaj koncentrat, wsyp ciecierzycę i wlej pomidory. Gotuj na małym ogniu 12–15 minut, a pod koniec rozgnieć tłuczkiem część ciecierzycy, żeby sos zgęstniał. Dopraw solą.',
      'W tym czasie ugotuj makaron al dente w osolonej wodzie, zwykle 10–11 minut, i odcedź.',
      'Połącz makaron z sosem i podawaj z porwanymi listkami bazylii.',
    ],
    photo:
      'Wholewheat pasta coated in a thick rustic tomato sauce with whole and crushed chickpeas, topped with torn fresh basil leaves and chili flakes',
  },
  {
    plan: 'OB-007',
    title: 'Bulgur z warzywami i halloumi',
    description:
      'Puszysty bulgur z pieczoną na patelni cukinią, papryką i pomidorkami, podany z plastrami złocistego halloumi i cytryną. Obiad w greckim stylu, słony, świeży i sycący, a do tego gotowy w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['bulgur', 140, 'g'],
      ['ser halloumi', 120, 'g'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 30, 'g'],
      ['oregano', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Bulgur zalej 300 ml wrzącej wody, przykryj i odstaw na 15 minut, potem rozdziel widelcem.',
      'Cukinię i paprykę pokrój w kostkę, cebulę w piórka, pomidorki przekrój na pół.',
      'Na dużej patelni rozgrzej połowę oliwy i smaż cukinię, paprykę i cebulę 7–8 minut na mocnym ogniu. Dodaj pomidorki i oregano, smaż jeszcze 2 minuty.',
      'Halloumi pokrój w plastry grubości 1 cm i smaż na suchej patelni po 2 minuty z każdej strony, aż będzie złote.',
      'Wymieszaj bulgur z warzywami, resztą oliwy, sokiem z cytryny i posiekaną natką. Podawaj z plastrami halloumi.',
    ],
    photo:
      'Fluffy bulgur mixed with sauteed zucchini, red pepper, red onion and blistered cherry tomatoes, topped with golden seared halloumi slices and parsley',
    vessel: 'bowl',
  },
  {
    plan: 'OB-008',
    title: 'Quesadilla z czarną fasolą i kukurydzą',
    description:
      'Chrupiące tortille kukurydziane zapiekane na patelni z roztopionym cheddarem, czarną fasolą, kukurydzą i papryką, doprawione kminem i wędzoną papryką. Meksykański obiad na szybko, który zjadają wszyscy.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['tortilla kukurydziana', 8, 'szt'],
      ['fasola czarna z puszki', 200, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['ser cheddar', 100, 'g'],
      ['papryka czerwona', 120, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Fasolę i kukurydzę odcedź. Paprykę i cebulę pokrój w drobną kostkę, ser zetrzyj na tarce.',
      'Na łyżeczce oleju podsmaż cebulę i paprykę 3 minuty, dodaj fasolę, kukurydzę, kmin i wędzoną paprykę, smaż 2 minuty, lekko rozgniatając fasolę widelcem.',
      'Na 4 tortille rozłóż farsz, posyp serem i posiekaną kolendrą, przykryj pozostałymi tortillami.',
      'Smaż quesadille na lekko natłuszczonej patelni na średnim ogniu po 2–3 minuty z każdej strony, aż ser się roztopi, a tortille będą chrupiące.',
      'Pokrój każdą quesadillę na 4 trójkąty i podawaj od razu.',
    ],
    photo:
      'Crispy golden corn tortilla quesadillas cut into triangles, showing melted cheddar, black beans, sweet corn and diced red pepper, garnished with cilantro',
    vessel: 'board',
  },
  {
    plan: 'OB-009',
    title: 'Makaron z sosem pomidorowym i mielonym indykiem',
    description:
      'Spaghetti z gęstym sosem z passaty i chudego mielonego indyka, z czosnkiem, oregano i parmezanem. Lżejsza wersja ulubionego makaronu z mięsem, która smakuje dzieciom i dobrze odgrzewa się następnego dnia.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron spaghetti', 160, 'g'],
      ['indyk mielony', 300, 'g'],
      ['passata pomidorowa', 400, 'ml'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['oregano', 1, 'g'],
      ['bazylia suszona', 1, 'g'],
      ['ser parmezan', 20, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek drobno posiekaj.',
      'Rozgrzej oliwę na głębokiej patelni, zeszklij cebulę przez 3 minuty, dodaj indyka i smaż 6–7 minut, rozbijając go łopatką, aż straci różowy kolor.',
      'Dodaj czosnek, oregano i bazylię, po minucie wlej passatę. Dopraw solą i pieprzem, gotuj na małym ogniu 12–15 minut.',
      'W tym czasie ugotuj spaghetti al dente w osolonej wodzie, zwykle 9–10 minut, i odcedź.',
      'Wymieszaj makaron z sosem i podawaj posypany startym parmezanem.',
    ],
    photo:
      'Spaghetti topped with a thick red tomato sauce with crumbled ground turkey, dusted with grated parmesan and dried herbs',
  },
  {
    plan: 'OB-010',
    title: 'Kurczak z ciecierzycą i szpinakiem w pomidorach',
    description:
      'Kawałki kurczaka duszone z ciecierzycą w pomidorach z kminem i słodką papryką, a na koniec ze świeżym szpinakiem. Jednogarnkowe, rozgrzewające danie bez glutenu i nabiału, pełne białka i błonnika.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['szpinak', 150, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę, dopraw pieprzem i słodką papryką. Cebulę posiekaj, czosnek przeciśnij, ciecierzycę odcedź.',
      'W szerokim garnku rozgrzej oliwę i smaż kurczaka 5 minut, aż się zrumieni. Dodaj cebulę i smaż 3 minuty.',
      'Wsyp czosnek i kmin, po 30 sekundach wlej pomidory i dodaj ciecierzycę. Duś pod przykryciem 12 minut.',
      'Wrzuć szpinak, wymieszaj i gotuj 2 minuty, aż zwiędnie. Spróbuj — ciecierzyca i pomidory z puszki są już słone, więc zwykle nie trzeba dosalać.',
    ],
    photo:
      'Rich tomato stew with tender chicken pieces, whole chickpeas and wilted dark green spinach, dusted with paprika',
    vessel: 'bowl',
  },
  {
    plan: 'OB-011',
    title: 'Dorsz w sezamowej panierce z ryżem i ogórkiem',
    description:
      'Kawałki dorsza w chrupiącej panierce z sezamu, podane z ryżem jaśminowym i szybką sałatką z ogórka w occie z dymką. Lekka ryba w azjatyckim stylu, bez nabiału i gotowa w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    ingredients: [
      ['dorsz', 350, 'g'],
      ['sezam', 40, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka ziemniaczana', 20, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['ryż jaśminowy', 140, 'g'],
      ['ogórek', 250, 'g'],
      ['ocet jabłkowy', 15, 'ml'],
      ['cukier', 5, 'g'],
      ['sos sojowy', 15, 'ml'],
      ['cebula dymka', 20, 'g'],
    ],
    steps: [
      'Ryż przepłucz, zalej 280 ml wody, zagotuj i gotuj pod przykryciem na małym ogniu 12 minut, potem odstaw na 5 minut.',
      'Ogórka pokrój w cienkie plasterki, zalej octem wymieszanym z cukrem i posiekaną dymką, odstaw do podania.',
      'Dorsza osusz i pokrój na 6 kawałków. Obtocz je w mące ziemniaczanej, potem w roztrzepanym jajku, a na koniec w sezamie.',
      'Smaż rybę na rozgrzanym oleju na średnim ogniu po 3 minuty z każdej strony, aż sezam będzie złoty, a ryba biała w środku.',
      'Podawaj dorsza z ryżem i ogórkiem, skrop sosem sojowym.',
    ],
    photo:
      'Golden sesame-crusted cod pieces beside a mound of white jasmine rice and a thinly sliced cucumber salad with green onion',
  },
  {
    plan: 'OB-012',
    title: 'Polędwiczka wieprzowa z kaszą gryczaną i buraczkami',
    description:
      'Medaliony z polędwiczki usmażone na różowo, z kaszą gryczaną i ciepłymi buraczkami z cebulką i cytryną. Tradycyjny smak niedzielnego obiadu w wersji na zwykły dzień, bez glutenu i z dużą porcją białka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    ingredients: [
      ['polędwiczka wieprzowa', 350, 'g'],
      ['kasza gryczana', 120, 'g'],
      ['burak', 400, 'g'],
      ['cebula', 50, 'g'],
      ['cytryna', 20, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['masło', 10, 'g'],
      ['majeranek', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę przepłucz, zalej 250 ml wrzącej osolonej wody i gotuj pod przykryciem 15 minut, potem odstaw na 5 minut.',
      'Buraki obierz i zetrzyj na tarce o dużych oczkach, cebulę posiekaj. Zeszklij cebulę na maśle, dodaj buraki i 3 łyżki wody, duś pod przykryciem 15 minut, mieszając. Dopraw sokiem z cytryny i szczyptą soli.',
      'Polędwiczkę pokrój w medaliony grubości 2 cm, lekko rozpłaszcz dłonią, natrzyj majerankiem, solą i pieprzem.',
      'Smaż medaliony na rozgrzanym oleju po 3 minuty z każdej strony, potem odstaw na 2 minuty pod folią.',
      'Podawaj polędwiczkę z kaszą i buraczkami.',
    ],
    photo:
      'Seared pork tenderloin medallions with a pink center next to brown buckwheat groats and glossy deep-red grated beetroot',
  },
  {
    plan: 'OB-013',
    title: 'Pierś z kurczaka z pesto, ryżem i pomidorami',
    description:
      'Soczysta pierś z kurczaka posmarowana pesto bazyliowym, podana z ryżem basmati, pomidorkami i rukolą. Włoskie smaki w prostym, szybkim obiedzie bez glutenu, który sprawdzi się też w pudełku.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['pesto bazyliowe', 50, 'g'],
      ['ryż basmati', 140, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['rukola', 40, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ryż przepłucz i ugotuj w 280 ml wody pod przykryciem, 12 minut na małym ogniu, potem odstaw na 5 minut.',
      'Filety przekrój poziomo na cieńsze płaty, dopraw solą i pieprzem.',
      'Smaż kurczaka na rozgrzanej oliwie po 4 minuty z każdej strony. Pod koniec dorzuć na patelnię przekrojone pomidorki i smaż 2 minuty.',
      'Zdejmij z ognia i posmaruj kurczaka pesto.',
      'Podawaj z ryżem, pomidorkami i garścią rukoli.',
    ],
    photo:
      'Sliced grilled chicken breast brushed with vibrant green basil pesto, served with white basmati rice, blistered cherry tomatoes and fresh arugula',
  },
  {
    plan: 'OB-014',
    title: 'Kasza jęczmienna z kiełbasą i warzywami z jednego garnka',
    description:
      'Kasza jęczmienna gotowana razem z podsmażoną kiełbasą, papryką, marchewką i pomidorami. Jeden garnek, mało zmywania i rozgrzewający, rustykalny obiad, który równie dobrze smakuje odgrzany.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza jęczmienna', 140, 'g'],
      ['kiełbasa śląska', 120, 'g'],
      ['marchew', 150, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula', 80, 'g'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['majeranek', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Kiełbasę pokrój w półplasterki, cebulę w kostkę, marchew w cienkie plasterki, paprykę w kostkę.',
      'W szerokim garnku rozgrzej olej i smaż kiełbasę z cebulą 4 minuty. Dodaj marchew i paprykę, smaż 2 minuty.',
      'Wsyp przepłukaną kaszę, słodką paprykę i majeranek, wymieszaj. Wlej pomidory i 350 ml gorącej wody.',
      'Zagotuj, przykryj i gotuj na małym ogniu 18–20 minut, aż kasza wchłonie płyn i będzie miękka. Mieszaj raz w połowie.',
      'Odstaw na 2 minuty i podawaj posypane posiekaną natką.',
    ],
    photo:
      'Hearty one-pot pearl barley with browned sausage half-moons, carrot slices and red pepper in a light tomato sauce, sprinkled with parsley',
    vessel: 'bowl',
  },
  {
    plan: 'OB-015',
    title: 'Jajka w sosie chrzanowym z ziemniakami',
    description:
      'Jajka na twardo polane ciepłym, lekko pikantnym sosem chrzanowym z koperkiem, podane z gotowanymi ziemniakami. Skromne, domowe danie jak u babci, bez mięsa i bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 6, 'szt'],
      ['ziemniak', 600, 'g'],
      ['mleko', 200, 'ml'],
      ['śmietana 18', 100, 'g'],
      ['chrzan tarty', 40, 'g'],
      ['masło', 15, 'g'],
      ['mąka ziemniaczana', 15, 'g'],
      ['cukier', 3, 'g'],
      ['koperek', 10, 'g'],
      ['szczypiorek', 10, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, pokrój na podobne kawałki i gotuj w osolonej wodzie 18–20 minut do miękkości.',
      'Jajka włóż do wrzątku i gotuj 9 minut, przełóż do zimnej wody, obierz i przekrój na połówki.',
      'Na sos rozpuść masło w rondelku, wlej mleko wymieszane z mąką ziemniaczaną i gotuj, mieszając, aż zgęstnieje, około 2 minut.',
      'Zdejmij z ognia, wmieszaj śmietanę, chrzan, cukier i szczyptę soli. Dodaj połowę posiekanego koperku.',
      'Ułóż jajka na ziemniakach, polej sosem i posyp resztą koperku i szczypiorkiem.',
    ],
    photo:
      'Halved hard-boiled eggs covered in a creamy white horseradish sauce with dill and chives, next to boiled potatoes',
  },
  {
    plan: 'OB-016',
    title: 'Makaron z soczewicą po bolońsku',
    description:
      'Gęsty sos bolognese, w którym mięso zastępuje czerwona soczewica duszona z marchewką, selerem naciowym i pomidorami. Roślinny obiad pełen białka, który smakuje jak klasyk i świetnie znosi odgrzewanie.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron razowy', 120, 'g'],
      ['soczewica czerwona', 200, 'g'],
      ['passata pomidorowa', 400, 'ml'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['cebula', 80, 'g'],
      ['marchew', 100, 'g'],
      ['seler naciowy', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę, marchew i seler naciowy pokrój w drobną kostkę, czosnek posiekaj. Soczewicę przepłucz na sitku.',
      'Rozgrzej oliwę w garnku i smaż warzywa 5 minut, dodaj czosnek, oregano i koncentrat, smaż minutę.',
      'Wsyp soczewicę, wlej passatę i 300 ml wody. Gotuj na małym ogniu 15 minut, mieszając, aż soczewica się rozpadnie, a sos zgęstnieje. Dopraw solą i pieprzem.',
      'W tym czasie ugotuj makaron al dente w osolonej wodzie, zwykle 10–11 minut, i odcedź.',
      'Podawaj makaron polany gęstym sosem.',
    ],
    photo:
      'Wholewheat spaghetti topped with a thick, rich red lentil bolognese sauce with tiny carrot and celery pieces and a sprinkle of oregano',
  },
  {
    plan: 'OB-017',
    title: 'Kurczak cytrynowy z kuskusem i warzywami',
    description:
      'Kurczak marynowany w soku i skórce z cytryny z czosnkiem i tymiankiem, z kuskusem i podsmażoną cukinią i papryką. Świeży, lekki obiad bez nabiału, który zrobisz w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['kasza kuskus', 120, 'g'],
      ['cukinia', 200, 'g'],
      ['papryka żółta', 160, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['cytryna', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['tymianek suszony', 1, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Z cytryny zetrzyj skórkę i wyciśnij sok. Kurczaka pokrój w paski i wymieszaj z połową soku, skórką, przeciśniętym czosnkiem, tymiankiem, solą i pieprzem; odstaw na 10 minut.',
      'Kuskus zalej 180 ml wrzącej wody, przykryj na 5 minut, potem rozdziel widelcem z łyżką oliwy.',
      'Cukinię i paprykę pokrój w kostkę, cebulę w piórka. Smaż na łyżce oliwy 6 minut na mocnym ogniu i przełóż do kuskusu.',
      'Na tej samej patelni rozgrzej resztę oliwy i smaż kurczaka 6–7 minut, aż się zrumieni.',
      'Wymieszaj kuskus z warzywami, resztą soku z cytryny i natką, a na wierzchu ułóż kurczaka.',
    ],
    photo:
      'Golden lemon-herb chicken strips on fluffy couscous mixed with diced zucchini, yellow pepper and red onion, garnished with parsley and lemon zest',
  },
  {
    plan: 'OB-018',
    title: 'Makaron z cukinią, miętą i fetą',
    description:
      'Letni makaron z cukinią podsmażoną z czosnkiem na oliwie, pokruszoną fetą, świeżą miętą i cytryną. Lekki, orzeźwiający obiad na upały, gdy cukinia jest najtańsza.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    seasons: ['SUMMER'],
    ingredients: [
      ['makaron spaghetti', 180, 'g'],
      ['cukinia', 400, 'g'],
      ['ser feta', 100, 'g'],
      ['mięta', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 25, 'ml'],
      ['cytryna', 30, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj spaghetti al dente w osolonej wodzie, zwykle 9–10 minut. Zachowaj pół szklanki wody z gotowania.',
      'Cukinię zetrzyj na tarce o grubych oczkach albo pokrój w cienkie półplasterki, czosnek posiekaj.',
      'Rozgrzej oliwę na dużej patelni i smaż cukinię na mocnym ogniu 5–6 minut, aż zmięknie i lekko się zrumieni. Dodaj czosnek na ostatnią minutę.',
      'Wrzuć makaron, dolej trochę wody z gotowania, skórkę i sok z cytryny, dopraw pieprzem i wymieszaj.',
      'Podawaj posypane pokruszoną fetą i porwanymi listkami mięty.',
    ],
    photo:
      'Spaghetti tossed with sauteed shredded green zucchini, crumbled white feta, fresh mint leaves and lemon zest, drizzled with olive oil',
  },
  {
    plan: 'OB-019',
    title: 'Bulgur z mielonym indykiem i papryką',
    description:
      'Bulgur duszony razem z mielonym indykiem, kolorową papryką i koncentratem pomidorowym, doprawiony kminem i słodką papryką. Sycący obiad z jednej patelni, bez nabiału i idealny do pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['bulgur', 120, 'g'],
      ['indyk mielony', 350, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['papryka żółta', 160, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Cebulę i paprykę pokrój w kostkę, czosnek posiekaj.',
      'Na głębokiej patelni rozgrzej oliwę, podsmaż cebulę 3 minuty, dodaj indyka i smaż 6 minut, rozbijając go łopatką.',
      'Dodaj paprykę, czosnek, kmin, słodką paprykę i koncentrat, smaż 2 minuty.',
      'Wsyp bulgur, wlej 300 ml gorącej wody, dopraw solą. Przykryj i gotuj na małym ogniu 12–15 minut, aż bulgur wchłonie płyn.',
      'Rozdziel widelcem i podawaj posypane posiekaną natką.',
    ],
    photo:
      'Skillet of tomato-tinted bulgur with crumbled ground turkey and colorful red and yellow pepper pieces, topped with chopped parsley',
  },
  {
    plan: 'OB-020',
    title: 'Penne z kiełbasą i pomidorami',
    description:
      'Penne w pomidorowym sosie z podsmażoną kiełbasą, cebulą, czosnkiem i słodką papryką. Prosty, lubiany przez całą rodzinę obiad z produktów, które zwykle są w lodówce i spiżarni.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PASTA',
    ingredients: [
      ['makaron penne', 180, 'g'],
      ['kiełbasa wędzona', 130, 'g'],
      ['passata pomidorowa', 300, 'ml'],
      ['pomidor koktajlowy', 150, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['bazylia suszona', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Ugotuj penne al dente w osolonej wodzie, zwykle 10–11 minut, i odcedź.',
      'Kiełbasę pokrój w półplasterki, cebulę w kostkę, czosnek posiekaj, pomidorki przekrój na pół.',
      'Na rozgrzanym oleju smaż kiełbasę 4 minuty, aż się zrumieni. Dodaj cebulę i smaż 3 minuty, potem czosnek, słodką paprykę i bazylię na minutę.',
      'Wlej passatę, wrzuć pomidorki i gotuj sos na małym ogniu 8–10 minut, aż zgęstnieje, a pomidorki zmiękną.',
      'Wymieszaj makaron z sosem i podawaj posypany posiekaną natką.',
    ],
    photo:
      'Penne pasta in a rich tomato sauce with browned smoked sausage slices, soft halved cherry tomatoes and onion, sprinkled with fresh chopped parsley',
  },
  {
    plan: 'OB-021',
    title: 'Gnocchi z cukinią i boczkiem',
    description:
      'Gnocchi przysmażone na złoto z chrupiącym boczkiem, cukinią, zielonym groszkiem i czosnkiem, połączone z kremową ricottą i świeżą bazylią. Włoski obiad w 20 minut, w którym gotowe kluseczki robią całą robotę.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'DUMPLINGS',
    ingredients: [
      ['gnocchi', 230, 'g'],
      ['boczek', 40, 'g'],
      ['cukinia', 300, 'g'],
      ['groszek mrożony', 100, 'g'],
      ['ser ricotta', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['bazylia', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Boczek pokrój w paseczki, cukinię w kostkę, czosnek posiekaj.',
      'Na suchej patelni wytop boczek przez 4 minuty, aż będzie chrupiący, i zdejmij go łyżką cedzakową.',
      'Na tłuszczu z boczku z dodatkiem oliwy smaż gnocchi prosto z opakowania 6–7 minut, mieszając, aż się zrumienią.',
      'Dodaj cukinię, groszek prosto z zamrażarki i czosnek, smaż 4–5 minut, dopraw pieprzem. Oddaj boczek.',
      'Zdejmij z ognia, dodaj łyżkami ricottę i porwaną bazylię, delikatnie wymieszaj i podawaj od razu.',
    ],
    photo:
      'Golden pan-fried gnocchi with crispy bacon bits, diced green zucchini and sweet peas, dotted with creamy spoonfuls of ricotta and fresh basil',
  },
  {
    plan: 'OB-022',
    title: 'Ryż z kurczakiem i warzywami po meksykańsku',
    description:
      'Ryż gotowany w pomidorach z kminem i wędzoną papryką, z kurczakiem, kukurydzą, papryką i cukinią, skropiony limonką. Kolorowy, lekko pikantny obiad z jednej patelni, bez glutenu i nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ryż biały', 140, 'g'],
      ['filet z kurczaka', 350, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cukinia', 150, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['papryczka chili', 10, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę, cebulę, paprykę i cukinię w kostkę, czosnek i chili posiekaj. Kukurydzę odcedź.',
      'W szerokim rondlu rozgrzej olej i smaż kurczaka 5 minut, dopraw solą, kminem i wędzoną papryką.',
      'Dodaj cebulę, paprykę, czosnek i chili, smaż 2 minuty. Wmieszaj koncentrat i przepłukany ryż.',
      'Wlej 320 ml gorącej wody, zagotuj, przykryj i gotuj na małym ogniu 12 minut. Dorzuć cukinię i kukurydzę, przykryj i gotuj jeszcze 4–5 minut, aż ryż wchłonie płyn.',
      'Skrop sokiem z limonki i posyp posiekaną kolendrą.',
    ],
    photo:
      'Orange-red Mexican-style rice with chicken cubes, sweet corn, red pepper and zucchini, topped with fresh cilantro and lime wedges',
  },
  {
    plan: 'OB-023',
    title: 'Kurczak w sosie musztardowo-miodowym z kaszą',
    description:
      'Kawałki kurczaka w kremowym sosie z musztardy, miodu i śmietanki, podane z kaszą jęczmienną. Słodko-pikantny sos, który lubią dzieci i dorośli, a wszystko gotowe w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['musztarda', 30, 'g'],
      ['miód', 20, 'g'],
      ['śmietanka 12', 100, 'ml'],
      ['cebula', 60, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['kasza jęczmienna', 120, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę przepłucz, zalej 300 ml wrzącej osolonej wody i gotuj pod przykryciem 18–20 minut, aż wchłonie wodę.',
      'Kurczaka pokrój w kostkę, dopraw solą i pieprzem, cebulę posiekaj. Wymieszaj musztardę z miodem i śmietanką.',
      'Na rozgrzanym oleju smaż kurczaka 5 minut, dodaj cebulę i smaż jeszcze 3 minuty.',
      'Wlej sos musztardowo-miodowy, zagotuj i duś 3–4 minuty, aż zgęstnieje.',
      'Podawaj kurczaka z kaszą, posypanego posiekaną natką.',
    ],
    photo:
      'Chicken pieces in a creamy golden honey mustard sauce served with pearl barley and sprinkled with chopped parsley',
  },
  {
    plan: 'OB-024',
    title: 'Kopytka zapiekane ze szpinakiem i serem',
    description:
      'Gotowe kopytka zapiekane w kremowym sosie z ricotty i szpinaku z czosnkiem i gałką muszkatołową, pod ciągnącą się mozzarellą. Szybka zapiekanka bez mięsa, która wychodzi z piekarnika w niecałe pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['gnocchi', 240, 'g'],
      ['szpinak', 200, 'g'],
      ['ser ricotta', 125, 'g'],
      ['śmietana 18', 50, 'g'],
      ['mozzarella', 50, 'g'],
      ['masło', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 220°C z termoobiegiem.',
      'Kopytka (gnocchi) wrzuć do wrzącej wody i gotuj 2 minuty od wypłynięcia, odcedź.',
      'Na patelni rozpuść masło, podsmaż posiekany czosnek przez 30 sekund, wrzuć szpinak i smaż 2–3 minuty, aż zwiędnie. Zdejmij z ognia, wmieszaj ricottę, śmietanę, gałkę muszkatołową i pieprz.',
      'Połącz kopytka ze szpinakiem, przełóż do naczynia żaroodpornego i przykryj porwaną mozzarellą.',
      'Zapiekaj 10–12 minut, aż ser się roztopi i zrumieni.',
    ],
    photo:
      'Baking dish of potato dumplings in creamy ricotta and spinach sauce under a layer of bubbling golden melted mozzarella',
  },
  {
    plan: 'OB-025',
    title: 'Makaron ze szpinakiem i fetą',
    description:
      'Wstążki tagliatelle w kremowym sosie ze szpinakiem, czosnkiem i suszonymi pomidorami, z pokruszoną fetą na wierzchu. Włoskie danie na każdy dzień: słone, aksamitne i gotowe w 20 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron tagliatelle', 180, 'g'],
      ['szpinak', 250, 'g'],
      ['ser feta', 80, 'g'],
      ['śmietanka 12', 100, 'ml'],
      ['pomidor suszony w oleju', 40, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['gałka muszkatołowa', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj makaron al dente w osolonej wodzie, zwykle 7–8 minut, i odcedź.',
      'Czosnek posiekaj, suszone pomidory pokrój w paski.',
      'Na rozgrzanej oliwie podsmaż czosnek i pomidory przez minutę, wrzuć szpinak i smaż 2–3 minuty, aż zwiędnie.',
      'Wlej śmietankę, dopraw gałką muszkatołową i pieprzem, dodaj połowę pokruszonej fety i gotuj 2 minuty, aż sos zgęstnieje.',
      'Wymieszaj z makaronem i podawaj posypane resztą fety.',
    ],
    photo:
      'Tagliatelle ribbons in a creamy green spinach sauce with strips of sun-dried tomato and crumbled white feta on top',
  },
  {
    plan: 'OB-026',
    title: 'Makaron z tuńczykiem i brokułem w sosie cytrynowym',
    description:
      'Spaghetti z brokułem, tuńczykiem i kaparami w lekkim sosie z oliwy, czosnku i cytryny. Szybki obiad z zapasów spiżarni, bez nabiału, pełen białka i świeżego, cytrusowego smaku.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron spaghetti', 180, 'g'],
      ['tuńczyk w puszce', 160, 'g'],
      ['brokuł', 350, 'g'],
      ['cytryna', 60, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 30, 'ml'],
      ['kapary', 15, 'g'],
      ['płatki chili', 1, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Brokuł podziel na małe różyczki. Zagotuj osoloną wodę, wrzuć spaghetti, a na 4 minuty przed końcem gotowania dorzuć brokuł. Odcedź, zachowując pół szklanki wody.',
      'Tuńczyka odsącz i rozdziel widelcem. Czosnek pokrój w plasterki, z cytryny zetrzyj skórkę i wyciśnij sok.',
      'Na dużej patelni rozgrzej oliwę, podsmaż czosnek z płatkami chili i kaparami przez minutę.',
      'Wrzuć makaron z brokułem, tuńczyka, skórkę i sok z cytryny oraz kilka łyżek wody z gotowania. Mieszaj 1–2 minuty, dopraw pieprzem.',
      'Podawaj posypane posiekaną natką.',
    ],
    photo:
      'Spaghetti with bright green broccoli florets, flaked tuna and capers in a glossy lemon garlic olive oil sauce, topped with parsley and lemon zest',
  },
  {
    plan: 'OB-027',
    title: 'Makaron orzo z kurczakiem i szpinakiem',
    description:
      'Orzo gotowane jak risotto w bulionie z kurczakiem, szpinakiem, czosnkiem i cytryną, wykończone parmezanem. Kremowe, włoskie danie z jednej patelni, bez mieszania przez pół wieczoru.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron orzo', 160, 'g'],
      ['filet z kurczaka', 300, 'g'],
      ['szpinak', 150, 'g'],
      ['bulion drobiowy', 250, 'ml'],
      ['cebula', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['ser parmezan', 20, 'g'],
      ['cytryna', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę, cebulę i czosnek posiekaj.',
      'W głębokiej patelni rozgrzej oliwę i smaż kurczaka 5 minut, aż się zrumieni. Dodaj cebulę i czosnek, smaż 2 minuty.',
      'Wsyp orzo, mieszaj minutę, a potem wlej bulion i 250 ml gorącej wody. Gotuj na małym ogniu 10–12 minut, często mieszając, aż makaron będzie miękki i kremowy.',
      'Wrzuć szpinak i mieszaj, aż zwiędnie. Zdejmij z ognia, wmieszaj starty parmezan, sok z cytryny i pieprz.',
    ],
    photo:
      'Creamy orzo pasta with golden chicken pieces and wilted spinach, finished with grated parmesan and cracked black pepper',
    vessel: 'bowl',
  },
  {
    plan: 'OB-028',
    title: 'Mielona wołowina z ryżem, kukurydzą i fasolą',
    description:
      'Wołowina podsmażona z cebulą, kminem i wędzoną papryką, duszona z czerwoną fasolą, kukurydzą i pomidorami, podana na ryżu basmati. Meksykańska miska na szybko, sycąca, bez glutenu i nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['wołowina mielona', 300, 'g'],
      ['ryż basmati', 120, 'g'],
      ['fasola czerwona z puszki', 200, 'g'],
      ['kukurydza z puszki', 140, 'g'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Ryż przepłucz i ugotuj w 240 ml wody pod przykryciem, 12 minut na małym ogniu, potem odstaw na 5 minut.',
      'Cebulę i czosnek posiekaj, fasolę i kukurydzę odcedź.',
      'Na rozgrzanym oleju smaż wołowinę z cebulą 6–7 minut, rozbijając mięso łopatką. Dodaj czosnek, kmin i obie papryki, smaż minutę.',
      'Wlej pomidory, dodaj fasolę i kukurydzę, duś 8 minut, aż sos zgęstnieje.',
      'Podawaj na ryżu, posypane posiekaną kolendrą.',
    ],
    photo:
      'Bowl of white basmati rice topped with spiced ground beef, red kidney beans and sweet corn in tomato sauce, garnished with fresh cilantro',
    vessel: 'bowl',
  },
];
