/**
 * Katalog 1000 — część OB-b: obiady OB-029 … OB-056 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'OB-029',
    title: 'Makaron ryżowy z wołowiną i warzywami',
    description:
      'Szybko smażone paski wołowiny z chrupiącą papryką, marchewką i cukinią, wymieszane z makaronem ryżowym, imbirem i limonką. Obiad z jednego woka, bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron ryżowy', 140, 'g'],
      ['wołowina', 250, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['marchew', 100, 'g'],
      ['cukinia', 150, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos chili słodki', 30, 'g'],
      ['sos rybny', 10, 'ml'],
      ['limonka', 30, 'g'],
      ['olej rzepakowy', 15, 'ml'],
    ],
    steps: [
      'Zalej makaron ryżowy wrzątkiem i odstaw na 8 minut, potem odcedź i przepłucz zimną wodą.',
      'Wołowinę pokrój w cienkie paski w poprzek włókien. Paprykę i cukinię pokrój w słupki, marchew w cienkie paski, dymkę w krążki, a czosnek i imbir drobno posiekaj.',
      'Rozgrzej olej w woku albo na dużej patelni i smaż wołowinę na mocnym ogniu 2–3 minuty, aż się zrumieni. Zdejmij ją na talerz.',
      'Na tę samą patelnię wrzuć marchew, paprykę i cukinię z czosnkiem i imbirem, smaż 4 minuty, ciągle mieszając.',
      'Dodaj makaron, wołowinę, sos chili i sos rybny, wyciśnij sok z limonki i mieszaj 1–2 minuty, aż wszystko się połączy.',
      'Podawaj od razu, posypane dymką.',
    ],
    photo:
      'Glossy rice noodles tossed with seared beef strips, red pepper, carrot ribbons and zucchini, topped with sliced spring onion and a lime wedge',
    vessel: 'bowl',
  },
  {
    plan: 'OB-030',
    title: 'Mintaj w sosie cytrynowym z ryżem',
    description:
      'Delikatne kawałki mintaja z patelni w lekkim, maślanym sosie cytrynowym z koperkiem, podane z ryżem i brokułem. Szybki rybny obiad, który lubią nawet ci, co ryb nie jedzą.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    ingredients: [
      ['mintaj', 300, 'g'],
      ['ryż biały', 80, 'g'],
      ['brokuł', 200, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['masło', 10, 'g'],
      ['śmietanka 12', 50, 'ml'],
      ['mąka ziemniaczana', 5, 'g'],
      ['cytryna', 50, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż w osolonej wodzie według opakowania, około 15 minut. Brokuł podziel na różyczki i ugotuj na parze albo w wodzie przez 5 minut.',
      'Mintaja osusz, pokrój na 4 kawałki, dopraw solą i pieprzem. Smaż na rozgrzanym oleju po 3 minuty z każdej strony i przełóż na talerz.',
      'Na patelni roztop masło, wlej 100 ml wody i sok z połowy cytryny. Mąkę ziemniaczaną rozmieszaj ze śmietanką, wlej do patelni i gotuj, mieszając, aż sos zgęstnieje.',
      'Wmieszaj posiekany koperek i startą skórkę z cytryny, włóż rybę do sosu i podgrzej 1 minutę.',
      'Podawaj mintaja z ryżem i brokułem, polany sosem, z plasterkiem cytryny.',
    ],
    photo:
      'Pan-fried pollock fillets in a pale creamy lemon-dill sauce served with fluffy white rice, bright green broccoli florets and a lemon slice',
  },
  {
    plan: 'OB-031',
    title: 'Dorsz z pomidorkami i oliwkami z kuskusem',
    description:
      'Dorsz duszony na patelni w pomidorkach koktajlowych z czarnymi oliwkami, czosnkiem i oregano, podany na puszystym kuskusie z natką. Śródziemnomorski obiad bez nabiału w niespełna pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'MAIN',
    ingredients: [
      ['dorsz', 300, 'g'],
      ['kasza kuskus', 120, 'g'],
      ['pomidor koktajlowy', 250, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['oregano', 1, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Wsyp kuskus do miski, zalej 180 ml wrzątku, przykryj i odstaw na 5 minut, potem rozdrobnij widelcem.',
      'Cebulę pokrój w piórka, czosnek w plasterki, pomidorki przekrój na pół, a oliwki na połówki.',
      'Na patelni rozgrzej oliwę i podsmaż cebulę z czosnkiem przez 3 minuty. Dodaj pomidorki, oliwki i oregano i duś 5 minut, aż pomidorki puszczą sok.',
      'Dorsza pokrój na 2 porcje, lekko posól i ułóż w sosie. Przykryj patelnię i duś na małym ogniu 8 minut, aż ryba będzie biała i łatwo się rozdzieli.',
      'Kuskus wymieszaj z sokiem z cytryny i połową posiekanej natki. Podawaj dorsza z sosem na kuskusie, posypanego resztą natki.',
    ],
    photo:
      'White cod fillet nestled in blistered cherry tomatoes with black olive halves and red onion, served over fluffy couscous sprinkled with parsley',
  },
  {
    plan: 'OB-032',
    title: 'Makaron z twarogiem, masłem i cukrem',
    description:
      'Klasyk z dzieciństwa: ciepłe kolanka z roztopionym masłem, pokruszonym twarogiem i odrobiną cukru z wanilią. Proste, słodkie danie obiadowe, które dzieci zjadają do ostatniego kęsa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PASTA',
    ingredients: [
      ['makaron kolanka', 180, 'g'],
      ['ser twaróg półtłusty', 200, 'g'],
      ['masło', 20, 'g'],
      ['śmietana 12', 40, 'g'],
      ['cukier', 20, 'g'],
      ['cukier waniliowy', 8, 'g'],
    ],
    steps: [
      'Ugotuj makaron kolanka w dużym garnku wody według opakowania, około 10 minut, i odcedź.',
      'W tym czasie pokrusz twaróg widelcem w misce i wymieszaj go ze śmietaną.',
      'Gorący makaron przełóż z powrotem do garnka, dodaj masło i mieszaj, aż się roztopi.',
      'Wymieszaj cukier z cukrem waniliowym. Nałóż makaron na talerze, posyp twarogiem i słodkim cukrem.',
    ],
    photo:
      'Warm elbow pasta glossy with melted butter, topped with crumbled white farmer cheese and a light dusting of sugar',
  },
  {
    plan: 'OB-033',
    title: 'Zupa z ciecierzycy i pomidorów',
    description:
      'Gęsta, rozgrzewająca zupa z ciecierzycy, pomidorów i marchewki, doprawiona kuminem i wędzoną papryką. Sycąca, a przy tym lekka, wegańska i gotowa w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ciecierzyca z puszki', 320, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['cebula', 100, 'g'],
      ['marchew', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['szpinak', 60, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, marchew obierz i pokrój w drobną kostkę. Ciecierzycę odcedź i przepłucz.',
      'W garnku rozgrzej oliwę i podsmaż cebulę z marchewką przez 5 minut. Dodaj czosnek, kumin i wędzoną paprykę i smaż jeszcze 1 minutę.',
      'Wlej pomidory z puszki i 500 ml wody, dodaj ciecierzycę i gotuj pod przykryciem 15 minut.',
      'Rozgnieć tłuczkiem część ciecierzycy w garnku, żeby zupa zgęstniała. Wrzuć szpinak i gotuj 1 minutę, aż zwiędnie.',
      'Dopraw pieprzem i podawaj gorącą.',
    ],
    photo:
      'Thick rustic tomato soup with whole chickpeas, diced carrot and wilted spinach leaves, dusted with smoked paprika',
    vessel: 'bowl',
  },
  {
    plan: 'OB-034',
    title: 'Leczo z dynią i kiełbasą',
    description:
      'Jesienne leczo z dynią, papryką i cukinią duszonymi w pomidorach z plasterkami kiełbasy i słodką papryką. Rozgrzewa, syci i następnego dnia smakuje jeszcze lepiej.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    seasons: ['AUTUMN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['kiełbasa', 140, 'g'],
      ['dynia', 400, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['cukinia', 200, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 400, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dynię obierz i pokrój w kostkę 2 cm, paprykę i cukinię w kostkę, cebulę w piórka, a kiełbasę w półplasterki.',
      'W szerokim garnku rozgrzej olej i podsmaż kiełbasę z cebulą przez 4 minuty.',
      'Dodaj dynię i paprykę, posyp słodką papryką i smaż 3 minuty, mieszając.',
      'Wlej passatę, dodaj cukinię i przeciśnięty czosnek. Duś pod przykryciem 15 minut, aż dynia zmięknie.',
      'Dopraw pieprzem i podawaj gorące.',
    ],
    photo:
      'Hearty stew of orange pumpkin cubes, red pepper and zucchini in tomato sauce with browned sausage half-moons',
    vessel: 'bowl',
  },
  {
    plan: 'OB-035',
    title: 'Kurczak z brokułem w sosie sojowo-czosnkowym z ryżem',
    description:
      'Soczyste kawałki kurczaka i chrupiący brokuł w lepkim sosie sojowym z czosnkiem, imbirem i miodem, podane z ryżem jaśminowym. Szybsze niż zamawianie jedzenia na wynos.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['brokuł', 300, 'g'],
      ['ryż jaśminowy', 120, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['czosnek', 4, 'szt'],
      ['imbir', 10, 'g'],
      ['miód', 15, 'g'],
      ['mąka ziemniaczana', 8, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sezam', 5, 'g'],
      ['cebula dymka', 20, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy według opakowania, około 12 minut.',
      'Kurczaka pokrój w kostkę i obtocz w połowie mąki ziemniaczanej. Brokuł podziel na małe różyczki.',
      'Wymieszaj sos sojowy, miód, przeciśnięty czosnek, starty imbir, resztę mąki ziemniaczanej i 80 ml wody.',
      'Na rozgrzanym oleju smaż kurczaka 5–6 minut, aż się zrumieni. Dodaj brokuł i 2 łyżki wody, przykryj i gotuj 3 minuty.',
      'Wlej sos i mieszaj 1–2 minuty, aż zgęstnieje i oblepi kurczaka.',
      'Podawaj z ryżem, posypane sezamem i posiekaną dymką.',
    ],
    photo:
      'Glossy soy-garlic chicken pieces with bright broccoli florets over jasmine rice, sprinkled with sesame seeds and sliced spring onion',
    vessel: 'bowl',
  },
  {
    plan: 'OB-036',
    title: 'Kasza jaglana z kurczakiem i warzywami z jednego garnka',
    description:
      'Kasza jaglana gotowana razem z kurczakiem, papryką, cukinią, marchewką i groszkiem w bulionie z kurkumą. Jeden garnek, mało zmywania i sycący, pełnowartościowy obiad do pudełka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza jaglana', 120, 'g'],
      ['filet z kurczaka', 350, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cukinia', 150, 'g'],
      ['marchew', 100, 'g'],
      ['cebula', 80, 'g'],
      ['groszek mrożony', 80, 'g'],
      ['bulion drobiowy', 300, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['kurkuma', 2, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz na sitku gorącą wodą. Kurczaka pokrój w kostkę, cebulę posiekaj, marchew, paprykę i cukinię pokrój w kostkę.',
      'W szerokim garnku rozgrzej olej i obsmaż kurczaka z cebulą przez 5 minut. Posyp papryką i kurkumą.',
      'Dodaj marchew i paprykę, wsyp kaszę, wlej bulion i 150 ml wody. Zagotuj, przykryj i gotuj na małym ogniu 12 minut.',
      'Dorzuć cukinię i groszek, przykryj i gotuj jeszcze 5 minut, aż kasza wchłonie płyn.',
      'Zdejmij z ognia, odstaw pod przykryciem na 3 minuty i wymieszaj z posiekaną natką.',
    ],
    photo:
      'Golden turmeric millet with tender chicken cubes, red pepper, zucchini, carrot and green peas, garnished with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'OB-037',
    title: 'Mięso mielone z cukinią i ryżem po grecku',
    description:
      'Mielona wołowina duszona z cukinią, pomidorami, oregano i szczyptą cynamonu, podana z ryżem, cytryną i natką. Smaki greckiej kuchni domowej w prostym obiedzie z jednej patelni.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['wołowina mielona', 250, 'g'],
      ['cukinia', 300, 'g'],
      ['ryż basmati', 100, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 2, 'g'],
      ['cynamon', 1, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż basmati według opakowania, około 12 minut.',
      'Cebulę i czosnek posiekaj, cukinię pokrój w kostkę.',
      'Na rozgrzanej oliwie podsmaż cebulę 3 minuty, dodaj mięso i smaż 6 minut, rozbijając je łopatką, aż się zrumieni.',
      'Dodaj czosnek, cukinię, oregano i cynamon, smaż 3 minuty. Wlej pomidory, posól i duś 8 minut bez przykrycia.',
      'Podawaj z ryżem, skropione sokiem z cytryny i posypane natką.',
    ],
    photo:
      'Browned minced beef with zucchini cubes in a light tomato sauce beside white basmati rice, topped with parsley and a lemon wedge',
  },
  {
    plan: 'OB-038',
    title: 'Szpinak z jajkiem sadzonym i ziemniakami',
    description:
      'Domowy obiad jak z dzieciństwa: kremowy szpinak z czosnkiem i gałką muszkatołową, jajko sadzone z płynnym żółtkiem i ziemniaki z koperkiem. Tanio, szybko i bez mięsa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['szpinak mrożony', 400, 'g'],
      ['jajko', 4, 'szt'],
      ['masło', 15, 'g'],
      ['śmietana 18', 40, 'g'],
      ['czosnek', 2, 'szt'],
      ['gałka muszkatołowa', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['koperek', 5, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, pokrój na kawałki i gotuj w osolonej wodzie 18–20 minut do miękkości.',
      'W rondlu roztop masło, dodaj przeciśnięty czosnek i mrożony szpinak. Duś na średnim ogniu 8–10 minut, aż odparuje woda.',
      'Wmieszaj śmietanę, dopraw gałką muszkatołową i szczyptą soli, podgrzej 1 minutę.',
      'Na patelni rozgrzej olej i usmaż jajka sadzone na średnim ogniu przez 3–4 minuty, aż białko się zetnie, a żółtko zostanie płynne.',
      'Ziemniaki odcedź i posyp koperkiem. Podawaj ze szpinakiem i jajkami sadzonymi.',
    ],
    photo:
      'Two sunny-side-up eggs with runny yolks next to creamy garlic spinach and boiled potatoes sprinkled with fresh dill',
  },
  {
    plan: 'OB-039',
    title: 'Kurczak w sosie z suszonych pomidorów z makaronem',
    description:
      'Penne z kurczakiem w kremowym sosie z suszonych pomidorów, czosnku i szpinaku, wykończone parmezanem i bazylią. Restauracyjny smak w domowym obiedzie gotowym w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron penne', 160, 'g'],
      ['filet z kurczaka', 350, 'g'],
      ['pomidor suszony w oleju', 60, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['śmietanka 12', 100, 'ml'],
      ['szpinak', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['ser parmezan', 15, 'g'],
      ['bazylia', 5, 'g'],
      ['oregano', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj penne al dente według opakowania i odlej 100 ml wody z gotowania.',
      'Kurczaka pokrój w paski, suszone pomidory w paseczki, czosnek posiekaj.',
      'Na patelni rozgrzej oliwę i smaż kurczaka 6 minut, aż się zrumieni. Dodaj czosnek, pomidory i oregano, smaż 1 minutę.',
      'Wlej śmietankę i trochę wody z makaronu, gotuj 2 minuty. Wrzuć szpinak i mieszaj, aż zwiędnie.',
      'Dodaj makaron, wymieszaj, dopraw pieprzem. Podawaj posypane startym parmezanem i listkami bazylii.',
    ],
    photo:
      'Penne pasta coated in a creamy orange sun-dried tomato sauce with sliced chicken, wilted spinach, shaved parmesan and fresh basil leaves',
    vessel: 'bowl',
  },
  {
    plan: 'OB-040',
    title: 'Miska z ryżem, fasolą, kukurydzą i awokado',
    description:
      'Kolorowa miska z ryżem limonkowym, czarną fasolą z kuminem, słodką kukurydzą, pomidorem i dojrzałym awokado. Meksykańskie smaki w wegańskim obiedzie, który składa się w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ryż biały', 120, 'g'],
      ['fasola czarna z puszki', 240, 'g'],
      ['kukurydza z puszki', 140, 'g'],
      ['awokado', 1, 'szt'],
      ['pomidor', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['limonka', 60, 'g'],
      ['kolendra', 10, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
    ],
    steps: [
      'Ugotuj ryż według opakowania, około 12 minut. Wymieszaj go z sokiem z połowy limonki i połową posiekanej kolendry.',
      'Fasolę i kukurydzę odcedź. Fasolę podgrzej na patelni z oliwą, kuminem i wędzoną papryką przez 4 minuty.',
      'Pomidora pokrój w kostkę, cebulę drobno posiekaj i wymieszaj z resztą soku z limonki.',
      'Awokado obierz i pokrój w plasterki.',
      'Nałóż do misek ryż, a na nim w osobnych kupkach fasolę, kukurydzę, pomidory z cebulą i awokado. Posyp resztą kolendry.',
    ],
    photo:
      'Colorful burrito bowl with lime rice, spiced black beans, sweet corn, diced tomato with red onion and fanned avocado slices, topped with cilantro',
    vessel: 'bowl',
  },
  {
    plan: 'OB-041',
    title: 'Makaron z soczewicą i szpinakiem w sosie kokosowym',
    description:
      'Pełnoziarnisty makaron w gęstym sosie z czerwonej soczewicy, pomidorów i mleka kokosowego z curry, imbirem i szpinakiem. Wegański obiad po indyjsku, bogaty w białko roślinne.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'PASTA',
    features: ['LUNCHBOX'],
    ingredients: [
      ['makaron razowy', 100, 'g'],
      ['soczewica czerwona', 160, 'g'],
      ['mleko kokosowe z puszki', 60, 'ml'],
      ['szpinak', 250, 'g'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['curry', 4, 'g'],
      ['garam masala', 2, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Soczewicę przepłucz. Cebulę, czosnek i imbir drobno posiekaj.',
      'W garnku rozgrzej olej i podsmaż cebulę 3 minuty, dodaj czosnek, imbir, curry i garam masalę i smaż 1 minutę.',
      'Wsyp soczewicę, wlej pomidory i 400 ml wody. Gotuj 15 minut, mieszając, aż soczewica się rozpadnie w gęsty sos.',
      'W tym czasie ugotuj makaron razowy według opakowania i odcedź.',
      'Do sosu wlej mleko kokosowe, wrzuć szpinak i gotuj 2 minuty, aż zwiędnie. Posól, wymieszaj z makaronem i podawaj.',
    ],
    photo:
      'Whole wheat pasta coated in a thick golden red lentil and coconut curry sauce with wilted spinach leaves',
    vessel: 'bowl',
  },
  {
    plan: 'OB-042',
    title: 'Indyk w sosie curry z brokułem i ryżem',
    description:
      'Kawałki indyka w aromatycznym sosie curry z pomidorami, imbirem i jogurtem, z brokułem i ryżem basmati. Łagodne, kremowe curry, które zrobisz szybciej, niż dojedzie dostawa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z indyka', 350, 'g'],
      ['brokuł', 300, 'g'],
      ['ryż basmati', 110, 'g'],
      ['jogurt naturalny', 150, 'g'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['curry', 6, 'g'],
      ['garam masala', 2, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż basmati według opakowania, około 12 minut.',
      'Indyka pokrój w kostkę, cebulę posiekaj, czosnek i imbir zetrzyj, brokuł podziel na różyczki.',
      'Na rozgrzanym oleju podsmaż cebulę 3 minuty, dodaj indyka i smaż 5 minut. Wsyp curry, garam masalę, czosnek i imbir i smaż 1 minutę.',
      'Wlej pomidory, dodaj brokuł, przykryj i duś 7 minut, aż indyk i brokuł będą miękkie.',
      'Zdejmij z ognia, wmieszaj jogurt i posól. Podawaj z ryżem.',
    ],
    photo:
      'Creamy golden turkey curry with broccoli florets in tomato-yogurt sauce served beside fluffy basmati rice',
    vessel: 'bowl',
  },
  {
    plan: 'OB-043',
    title: 'Łosoś z patelni z makaronem i cukinią',
    description:
      'Kawałki łososia z chrupiącą skórką na spaghetti z cukinią, czosnkiem, cytryną i parmezanem. Lekki w smaku, a bardzo sycący obiad z dużą porcją białka i kwasów omega-3.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    ingredients: [
      ['łosoś', 300, 'g'],
      ['makaron spaghetti', 140, 'g'],
      ['cukinia', 300, 'g'],
      ['czosnek', 2, 'szt'],
      ['cytryna', 40, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['ser parmezan', 10, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj spaghetti al dente według opakowania i odlej 80 ml wody z gotowania.',
      'Łososia pokrój na 2 kawałki, osusz, posól i popieprz. Smaż skórą do dołu na suchej, rozgrzanej patelni 4 minuty, obróć i smaż jeszcze 3 minuty. Zdejmij i rozdziel na duże płatki.',
      'Na tej samej patelni rozgrzej oliwę, wrzuć cukinię pokrojoną w półplasterki i posiekany czosnek, smaż 4 minuty.',
      'Dodaj makaron, wodę z gotowania, sok i startą skórkę z cytryny, wymieszaj.',
      'Rozłóż makaron na talerze, ułóż łososia, posyp startym parmezanem i natką.',
    ],
    photo:
      'Spaghetti tossed with sauteed zucchini half-moons and garlic, topped with flaked crispy-skin salmon, grated parmesan, parsley and lemon zest',
  },
  {
    plan: 'OB-044',
    title: 'Dorsz pieczony z warzywami śródziemnomorskimi',
    description:
      'Dorsz pieczony na jednej blasze z cukinią, papryką, pomidorkami, czerwoną cebulą, oliwkami i młodymi ziemniakami. Lekki, kolorowy obiad, przy którym piekarnik robi całą robotę.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['dorsz', 320, 'g'],
      ['ziemniak młody', 250, 'g'],
      ['cukinia', 250, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['oliwka czarna', 30, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['czosnek', 2, 'szt'],
      ['oregano', 2, 'g'],
      ['cytryna', 40, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Ziemniaki umyj i przekrój na ćwiartki, cukinię i paprykę pokrój w duże kawałki, cebulę w ósemki.',
      'Wyłóż warzywa na blachę, polej większością oliwy, posyp oregano, solą i plasterkami czosnku, wymieszaj. Piecz 20 minut.',
      'Dorsza pokrój na 2 porcje, skrop sokiem z cytryny i resztą oliwy.',
      'Wyjmij blachę, dołóż pomidorki i oliwki, a na wierzchu ułóż rybę. Piecz jeszcze 12–15 minut, aż dorsz będzie biały i łatwo się rozdzieli.',
      'Podawaj od razu z plasterkami cytryny.',
    ],
    photo:
      'Baked white cod fillets on a colorful bed of roasted zucchini, red pepper, red onion, baby potatoes, burst cherry tomatoes and black olives',
  },
  {
    plan: 'OB-045',
    title: 'Zupa krem z brokułów z pestkami',
    description:
      'Aksamitny krem z brokułów z ziemniakiem i odrobiną śmietanki, podany z chrupiącymi, prażonymi pestkami dyni. Zielona, lekka zupa, która gotuje się w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    equipment: ['BLENDER'],
    ingredients: [
      ['brokuł', 500, 'g'],
      ['ziemniak', 200, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 10, 'g'],
      ['śmietanka 12', 80, 'ml'],
      ['pestki dyni', 30, 'g'],
      ['bulion warzywny', 300, 'ml'],
      ['gałka muszkatołowa', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, ziemniak obierz i pokrój w kostkę, brokuł podziel na różyczki, a łodygę obierz i pokrój.',
      'W garnku roztop masło i zeszklij cebulę z czosnkiem przez 3 minuty.',
      'Dodaj ziemniak i brokuł, wlej bulion i 300 ml wody. Gotuj pod przykryciem 15 minut, aż warzywa zmiękną.',
      'W tym czasie upraż pestki dyni na suchej patelni przez 3 minuty.',
      'Zmiksuj zupę blenderem na gładki krem, wlej śmietankę, dopraw gałką muszkatołową i pieprzem. Podawaj posypaną pestkami.',
    ],
    photo:
      'Smooth vibrant green broccoli cream soup with a swirl of cream and toasted pumpkin seeds on top',
    vessel: 'bowl',
  },
  {
    plan: 'OB-046',
    title: 'Kurczak pieczony z warzywami korzeniowymi',
    description:
      'Pierś z kurczaka z czosnkiem, tymiankiem i papryką pieczona na blasze z marchewką, pietruszką, selerem i czerwoną cebulą. Prosty, lekki obiad z jednej blachy, bez nabiału i glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['marchew', 200, 'g'],
      ['pietruszka korzeń', 150, 'g'],
      ['seler korzeniowy', 150, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['czosnek', 3, 'szt'],
      ['tymianek suszony', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Marchew, pietruszkę i seler obierz i pokrój w słupki grubości palca, cebulę w ósemki.',
      'Wymieszaj warzywa z połową oliwy, połową tymianku i szczyptą soli, rozłóż na blasze i piecz 15 minut.',
      'Kurczaka natrzyj resztą oliwy, papryką, resztą tymianku, przeciśniętym czosnkiem, solą i pieprzem.',
      'Ułóż kurczaka między warzywami i piecz 20–22 minuty, aż mięso będzie soczyste, a warzywa zrumienione.',
      'Odstaw na 3 minuty, pokrój kurczaka w plastry i podawaj z warzywami.',
    ],
    photo:
      'Sliced golden paprika-roasted chicken breast on a tray of caramelized carrot, parsnip-like parsley root, celeriac sticks and red onion wedges',
  },
  {
    plan: 'OB-047',
    title: 'Kurczak w sosie pomidorowo-paprykowym z kaszą jaglaną',
    description:
      'Kawałki kurczaka duszone w gęstym sosie z czerwonej papryki i pomidorów z wędzoną papryką, podane z puszystą kaszą jaglaną. Lekki obiad, który dobrze znosi odgrzewanie.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['kasza jaglana', 70, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['pomidor krojony z puszki', 300, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 4, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz gorącą wodą, zalej 160 ml wody, posól szczyptą i gotuj pod przykryciem 15 minut.',
      'Kurczaka pokrój w kostkę, paprykę w paski, cebulę i czosnek posiekaj.',
      'Na rozgrzanym oleju obsmaż kurczaka 5 minut. Dodaj cebulę i paprykę i smaż 4 minuty.',
      'Posyp słodką i wędzoną papryką, dodaj czosnek, wlej pomidory i duś pod przykryciem 12 minut, aż sos zgęstnieje.',
      'Podawaj kurczaka w sosie na kaszy jaglanej, posypanego natką.',
    ],
    photo:
      'Chicken pieces and red pepper strips in a thick smoky tomato sauce served with fluffy yellow millet and chopped parsley',
  },
  {
    plan: 'OB-048',
    title: 'Indyk w sosie cytrynowo-kaparowym z kaszą',
    description:
      'Cienkie sznycle z indyka oprószone mąką i podsmażone na oliwie, w kwaskowym sosie z cytryny i kaparów, podane z kaszą pęczak i rukolą. Włoska piccata w lekkim wydaniu, bez masła i śmietany.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'MAIN',
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['kasza pęczak', 80, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['kapary', 20, 'g'],
      ['cytryna', 60, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['bulion drobiowy', 150, 'ml'],
      ['czosnek', 1, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj kaszę pęczak w 250 ml wody pod przykryciem 20–25 minut, aż wchłonie wodę.',
      'Indyka pokrój na 4 cienkie sznycle, rozbij je lekko przez folię, popieprz i oprósz mąką.',
      'Na rozgrzanej oliwie smaż sznycle po 2–3 minuty z każdej strony i zdejmij na talerz.',
      'Na patelnię wrzuć posiekany czosnek, wlej bulion i sok z cytryny, dodaj kapary i gotuj 3 minuty, aż sos się zredukuje.',
      'Włóż indyka z powrotem, podgrzej w sosie 1 minutę i posyp natką. Podawaj z kaszą i rukolą.',
    ],
    photo:
      'Thin golden turkey cutlets in a glossy lemon-caper sauce with parsley, served with pearl barley and a handful of arugula',
  },
  {
    plan: 'OB-049',
    title: 'Mintaj na parze z kaszą jaglaną i marchewką',
    description:
      'Delikatny mintaj gotowany na parze z koperkiem i cytryną, podany z kaszą jaglaną i marchewką z oliwą. Lekkostrawny, łagodny obiad, dobry także dla dzieci i na trudniejsze dni.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    ingredients: [
      ['mintaj', 320, 'g'],
      ['kasza jaglana', 90, 'g'],
      ['marchew', 250, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['koperek', 10, 'g'],
      ['cytryna', 30, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz gorącą wodą, zalej 200 ml wody, posól szczyptą i gotuj pod przykryciem 15 minut.',
      'Marchew obierz i pokrój w plasterki. Mintaja pokrój na porcje, posól, popieprz i skrop sokiem z cytryny.',
      'Zagotuj wodę w garnku, ustaw na nim sito albo wkład do gotowania na parze. Włóż marchew, przykryj i gotuj 5 minut.',
      'Połóż na marchewce rybę, posyp połową koperku, przykryj i gotuj na parze 8–10 minut, aż mintaj będzie biały.',
      'Marchew wymieszaj z oliwą i resztą koperku. Podawaj rybę z kaszą i marchewką.',
    ],
    photo:
      'Steamed white pollock fillet with fresh dill and a lemon slice, served with golden millet and glazed carrot coins',
  },
  {
    plan: 'OB-050',
    title: 'Cukinia faszerowana indykiem i pomidorami',
    description:
      'Łódeczki z cukinii wypełnione mielonym indykiem duszonym z pomidorami, cebulą i ziołami, zapieczone pod warstwą mozzarelli. Letni, lekki obiad z dużą porcją białka.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    seasons: ['SUMMER'],
    equipment: ['OVEN'],
    ingredients: [
      ['cukinia', 600, 'g'],
      ['indyk mielony', 300, 'g'],
      ['pomidor', 200, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['mozzarella tarta', 40, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['oregano', 1, 'g'],
      ['bazylia', 5, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Cukinie przekrój wzdłuż na pół i wydrąż łyżeczką środek, zostawiając ścianki grubości 1 cm. Miąższ posiekaj.',
      'Na oliwie podsmaż posiekaną cebulę 3 minuty, dodaj indyka i smaż 5 minut, rozbijając go łopatką.',
      'Dodaj czosnek, posiekany miąższ cukinii, pomidora w kostce, koncentrat, oregano i sól. Duś 5 minut, aż farsz zgęstnieje.',
      'Ułóż łódki cukinii w naczyniu żaroodpornym, napełnij farszem i posyp mozzarellą.',
      'Piecz 25 minut, aż cukinia zmięknie, a ser się zrumieni. Podawaj posypane bazylią.',
    ],
    photo:
      'Halved zucchini boats filled with minced turkey and tomato stuffing under bubbly golden melted mozzarella, garnished with fresh basil',
  },
  {
    plan: 'OB-051',
    title: 'Zupa pomidorowa z soczewicą',
    description:
      'Gęsta pomidorówka z czerwoną soczewicą, marchewką i wędzoną papryką, która rozgotowuje się w kremowy wywar. Wegańska, sycąca zupa, która świetnie znosi odgrzewanie.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica czerwona', 120, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['passata pomidorowa', 200, 'ml'],
      ['marchew', 100, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['majeranek', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, marchew zetrzyj na tarce o grubych oczkach. Soczewicę przepłucz.',
      'W garnku rozgrzej oliwę i podsmaż cebulę z marchewką przez 5 minut. Dodaj czosnek i wędzoną paprykę, smaż 1 minutę.',
      'Wsyp soczewicę, wlej pomidory, passatę i 600 ml wody. Gotuj pod przykryciem 20 minut, aż soczewica się rozpadnie.',
      'Dopraw majerankiem i solą. Jeśli wolisz gładką zupę, rozgnieć ją tłuczkiem.',
      'Podawaj gorącą, posypaną posiekaną natką.',
    ],
    photo:
      'Thick deep red tomato and red lentil soup with a sprinkle of chopped parsley and a drizzle of olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'OB-052',
    title: 'Kalafior w czerwonym curry po tajsku',
    description:
      'Różyczki kalafiora i ciecierzyca w pikantnym czerwonym curry z mleka kokosowego, domowej pasty z chili, czosnku i imbiru oraz limonki. Wegańskie, rozgrzewające curry bez sosu rybnego.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kalafior', 500, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['mleko kokosowe z puszki', 100, 'ml'],
      ['papryka czerwona', 150, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 15, 'g'],
      ['papryczka chili', 10, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['curry', 4, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Cebulę, czosnek, imbir i chili posiekaj bardzo drobno, a potem rozetrzyj z koncentratem i curry na gęstą pastę.',
      'Kalafior podziel na małe różyczki, paprykę pokrój w paski, ciecierzycę odcedź.',
      'W głębokiej patelni rozgrzej olej i smaż pastę 2 minuty, aż zapachnie. Dodaj kalafior i paprykę i smaż 3 minuty.',
      'Wlej mleko kokosowe i 200 ml wody, dodaj ciecierzycę, przykryj i gotuj 12 minut, aż kalafior będzie miękki.',
      'Dopraw sokiem z limonki i solą, podawaj posypane kolendrą.',
    ],
    photo:
      'Red coconut curry with cauliflower florets, chickpeas and red pepper strips, topped with fresh cilantro and lime wedges',
    vessel: 'bowl',
  },
  {
    plan: 'OB-053',
    title: 'Kotlety z indyka z cukinią w sosie jogurtowym z kaszą',
    description:
      'Soczyste kotleciki z mielonego indyka z tartą cukinią, podane z kaszą gryczaną i chłodnym sosem jogurtowym z koperkiem i czosnkiem. Lekki, domowy obiad, który smakuje też na zimno.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['indyk mielony', 250, 'g'],
      ['cukinia', 250, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 10, 'g'],
      ['kasza gryczana', 60, 'g'],
      ['jogurt naturalny', 120, 'g'],
      ['koperek', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj kaszę gryczaną w 130 ml wody pod przykryciem przez 15 minut.',
      'Cukinię zetrzyj na tarce o grubych oczkach, posól szczyptą, odstaw na 5 minut i mocno odciśnij z soku.',
      'Wymieszaj indyka z cukinią, jajkiem, bułką tartą, solą i pieprzem. Uformuj mokrymi dłońmi 8 małych kotlecików.',
      'Smaż kotlety na rozgrzanym oleju po 4 minuty z każdej strony na średnim ogniu, aż będą zrumienione i dopieczone w środku.',
      'Jogurt wymieszaj z posiekanym koperkiem i przeciśniętym czosnkiem. Podawaj kotlety z kaszą i sosem.',
    ],
    photo:
      'Small golden turkey and zucchini patties with buckwheat groats and a bowl of creamy dill yogurt sauce',
  },
  {
    plan: 'OB-054',
    title: 'Zupa gulaszowa z indyka',
    description:
      'Gęsta, paprykowa zupa gulaszowa z kawałkami indyka, ziemniakami i czerwoną papryką, doprawiona kminkiem i majerankiem. Rozgrzewający obiad w jednym garnku, a przy tym lekki.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['ziemniak', 250, 'g'],
      ['papryka czerwona', 200, 'g'],
      ['cebula', 100, 'g'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 5, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['kminek', 1, 'g'],
      ['majeranek', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Indyka pokrój w kostkę 2 cm, cebulę posiekaj, ziemniaki i paprykę pokrój w kostkę.',
      'W garnku rozgrzej olej i obsmaż indyka z cebulą przez 6 minut. Dodaj koncentrat, obie papryki mielone, kminek i czosnek i smaż 1 minutę.',
      'Wlej 800 ml wody, dodaj pomidory i ziemniaki, zagotuj i gotuj pod przykryciem 20 minut.',
      'Dorzuć paprykę i gotuj jeszcze 8 minut, aż będzie miękka, a ziemniaki zaczną się rozpadać.',
      'Dopraw majerankiem i solą. Podawaj gorącą.',
    ],
    photo:
      'Rich brick-red goulash soup with tender turkey chunks, potato cubes and red pepper pieces, sprinkled with marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'OB-055',
    title: 'Ryba pieczona w papilotach z cytryną i koperkiem',
    description:
      'Filety z morszczuka pieczone w pergaminowych kopertach z plasterkami cytryny, koperkiem, cukinią i marchewką, podane z młodymi ziemniakami. Ryba paruje we własnym soku i zostaje bardzo soczysta.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['morszczuk', 320, 'g'],
      ['ziemniak młody', 300, 'g'],
      ['cukinia', 150, 'g'],
      ['marchew', 100, 'g'],
      ['cytryna', 60, 'g'],
      ['koperek', 15, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['czosnek', 2, 'szt'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Ziemniaki umyj i gotuj w osolonej wodzie 18–20 minut.',
      'Cukinię i marchew pokrój w cienkie plasterki obieraczką, czosnek w plasterki, cytrynę w półplasterki.',
      'Wytnij 2 duże arkusze papieru do pieczenia. Na środku każdego ułóż warzywa, na nich rybę, posól, popieprz, skrop oliwą i przykryj cytryną, czosnkiem i połową koperku.',
      'Zawiń papier w szczelne koperty, ułóż na blasze i piecz 15–18 minut.',
      'Rozetnij papiloty przy stole i podawaj rybę z ziemniakami posypanymi resztą koperku.',
    ],
    photo:
      'Opened parchment parcel with a flaky white hake fillet on ribbons of zucchini and carrot, topped with lemon slices and fresh dill, baby potatoes on the side',
  },
  {
    plan: 'OB-056',
    title: 'Kurczak tikka z sałatką z ogórka',
    description:
      'Kawałki kurczaka marynowane w jogurcie z garam masalą, kurkumą i imbirem, upieczone na mocnym ogniu i podane z chłodną sałatką z ogórka, czerwonej cebuli i mięty oraz ryżem basmati.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['jogurt naturalny', 200, 'g'],
      ['garam masala', 4, 'g'],
      ['kurkuma', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['cytryna', 20, 'g'],
      ['ryż basmati', 60, 'g'],
      ['ogórek', 250, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['mięta', 5, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Wymieszaj 120 g jogurtu z garam masalą, kurkumą, papryką, kuminem, przeciśniętym czosnkiem, startym imbirem, sokiem z cytryny i solą.',
      'Kurczaka pokrój w duże kawałki, wymieszaj z marynatą i odstaw na 15 minut. Nagrzej piekarnik do 230°C (termoobieg).',
      'Ułóż kurczaka na blasze wyłożonej papierem i piecz 15–18 minut, aż brzegi się przypieką. W tym czasie ugotuj ryż według opakowania.',
      'Ogórka pokrój w półplasterki, cebulę w cienkie piórka, wymieszaj z resztą jogurtu i posiekaną miętą.',
      'Podawaj kurczaka tikka z ryżem i sałatką z ogórka.',
    ],
    photo:
      'Charred orange-red chicken tikka pieces with basmati rice and a cool cucumber, red onion and mint yogurt salad',
  },
];
