/**
 * Katalog 1000 — część OB-c: obiady OB-057 … OB-084 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'OB-057',
    title: 'Zupa jarzynowa z młodych warzyw z koperkiem',
    description:
      'Letnia zupa z młodych ziemniaków, kalarepy, bobu, groszku i fasolki szparagowej, zaprawiona oliwą i dużą garścią koperku. Lekka, a sycąca dzięki strączkom — smakuje jak ogród w lipcu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SUMMER'],
    ingredients: [
      ['ziemniak młody', 250, 'g'],
      ['marchew', 150, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['kalarepa', 150, 'g'],
      ['fasolka szparagowa', 150, 'g'],
      ['groszek', 150, 'g'],
      ['bób', 150, 'g'],
      ['cebula dymka', 50, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['bulion warzywny', 300, 'ml'],
      ['koperek', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz marchew, pietruszkę i kalarepę, pokrój w kostkę. Młode ziemniaki wyszoruj i pokrój w ćwiartki, fasolkę szparagową w 2-centymetrowe kawałki.',
      'Cebulę dymkę posiekaj i zeszklij na oliwie w dużym garnku przez 2 minuty.',
      'Dodaj marchew, pietruszkę, kalarepę i ziemniaki, wlej bulion warzywny i 800 ml wody. Zagotuj i gotuj pod przykryciem 15 minut.',
      'Wrzuć fasolkę szparagową, bób i groszek, gotuj jeszcze 8–10 minut, aż wszystkie warzywa będą miękkie.',
      'Dopraw pieprzem, zdejmij z ognia i wmieszaj posiekany koperek. Podawaj od razu.',
    ],
    photo:
      'Clear golden vegetable soup with new potato chunks, carrot and kohlrabi cubes, green beans, broad beans and peas, generously sprinkled with fresh dill',
    vessel: 'bowl',
  },
  {
    plan: 'OB-058',
    title: 'Pieczony kurczak z ciecierzycą i papryką',
    description:
      'Kawałki kurczaka pieczone na jednej blasze z ciecierzycą, czerwoną papryką i cebulą w wędzonej papryce i kuminie. Mało zmywania, dużo białka i chrupiąca ciecierzyca na brzegach.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['ciecierzyca z puszki', 150, 'g'],
      ['papryka czerwona', 250, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['czosnek', 2, 'szt'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 210°C z termoobiegiem. Ciecierzycę odsącz, przepłucz i osusz ręcznikiem papierowym.',
      'Filet z kurczaka pokrój w duże kawałki, paprykę w paski, a cebulę czerwoną w grube piórka. Czosnek przeciśnij przez praskę.',
      'W misce wymieszaj oliwę, czosnek, wędzoną paprykę, kmin rzymski i sól. Obtocz w tym kurczaka, ciecierzycę i warzywa.',
      'Rozłóż wszystko w jednej warstwie na blasze wyłożonej papierem i piecz 22–25 minut, w połowie mieszając, aż kurczak będzie złoty, a ciecierzyca chrupiąca.',
      'Skrop sokiem z cytryny, posyp posiekaną natką pietruszki i podawaj.',
    ],
    photo:
      'Golden roasted chicken pieces with crispy chickpeas, charred red pepper strips and red onion wedges, scattered with chopped parsley',
  },
  {
    plan: 'OB-059',
    title: 'Kapusta duszona z indykiem i pomidorami',
    description:
      'Biała kapusta duszona z kawałkami indyka, marchewką i pomidorami, doprawiona majerankiem i kminkiem. Domowe, rozgrzewające danie z jednego garnka, lekkie, a bardzo sycące.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    seasons: ['WINTER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['kapusta biała', 600, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['cebula', 100, 'g'],
      ['marchew', 100, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['majeranek', 2, 'g'],
      ['kminek', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Filet z indyka pokrój w kostkę, obsyp słodką papryką i pieprzem. Kapustę poszatkuj, cebulę posiekaj, marchew zetrzyj na grubych oczkach.',
      'Rozgrzej olej w szerokim garnku i obsmaż indyka na dużym ogniu 4–5 minut. Dodaj cebulę i marchew, smaż 3 minuty.',
      'Dołóż kapustę, kminek i liść laurowy, podlej 150 ml wody, przykryj i duś 15 minut, co jakiś czas mieszając.',
      'Wmieszaj pomidory z puszki i koncentrat, duś pod przykryciem jeszcze 15–20 minut, aż kapusta zmięknie.',
      'Dopraw majerankiem i solą, wyjmij liść laurowy i podawaj na gorąco.',
    ],
    photo:
      'Braised shredded white cabbage with tender turkey cubes, carrot and chunky tomato sauce, sprinkled with dried marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'OB-060',
    title: 'Zupa z młodej kapusty z koperkiem',
    description:
      'Wiosenna zupa z młodej kapusty, młodych ziemniaków i pomidorów, z białą fasolą dla sytości i świeżym koperkiem na koniec. Delikatna, lekko słodka i gotowa w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SPRING'],
    ingredients: [
      ['młoda kapusta', 500, 'g'],
      ['ziemniak młody', 300, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['cebula', 80, 'g'],
      ['pomidor', 200, 'g'],
      ['fasola biała z puszki', 240, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['bulion warzywny', 150, 'ml'],
      ['koperek', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Młodą kapustę poszatkuj, ziemniaki wyszoruj i pokrój w kostkę, marchew i pietruszkę zetrzyj na grubych oczkach, cebulę posiekaj.',
      'Na oliwie w garnku zeszklij cebulę, dodaj marchew i pietruszkę, smaż 3 minuty.',
      'Dołóż kapustę i ziemniaki, wlej bulion warzywny i 900 ml wody. Zagotuj i gotuj 15 minut.',
      'Pomidory sparz, obierz ze skórki i pokrój w kostkę. Dodaj do zupy razem z odsączoną fasolą i gotuj jeszcze 5 minut.',
      'Dopraw pieprzem i wmieszaj posiekany koperek tuż przed podaniem.',
    ],
    photo:
      'Pale green young cabbage soup with potato cubes, tomato pieces, white beans and carrot, topped with plenty of chopped fresh dill',
    vessel: 'bowl',
  },
  {
    plan: 'OB-061',
    title: 'Pieczarki faszerowane kaszą i szpinakiem',
    description:
      'Duże pieczarki nadziane kaszą gryczaną ze szpinakiem, cebulą i fetą, zapieczone i podane z koperkowym sosem jogurtowym. Lekki, wegetariański obiad, który wygląda jak danie z restauracji.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['pieczarka', 500, 'g'],
      ['kasza gryczana', 80, 'g'],
      ['szpinak', 150, 'g'],
      ['cebula', 80, 'g'],
      ['ser feta', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['jogurt naturalny', 100, 'g'],
      ['koperek', 10, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj kaszę gryczaną w 170 ml wody pod przykryciem przez 15 minut. Nagrzej piekarnik do 200°C.',
      'Z pieczarek wykręć trzonki i posiekaj je drobno. Kapelusze ułóż na blasze wyłożonej papierem.',
      'Na oliwie zeszklij posiekaną cebulę i czosnek, dodaj posiekane trzonki i smaż 4 minuty. Wrzuć szpinak i trzymaj na ogniu, aż zwiędnie.',
      'Wymieszaj farsz z kaszą, pokruszoną fetą, tymiankiem i pieprzem. Nałóż go z górką do kapeluszy.',
      'Piecz 20 minut, aż pieczarki zmiękną, a wierzch się zrumieni.',
      'Jogurt wymieszaj z posiekanym koperkiem i podawaj jako sos do pieczarek.',
    ],
    photo:
      'Large baked mushroom caps heaped with buckwheat, spinach and crumbled feta stuffing, golden on top, with a dollop of white dill yogurt sauce on the side',
  },
  {
    plan: 'OB-062',
    title: 'Tofu w curry z warzywami i ryżem',
    description:
      'Złociste kostki tofu i edamame w kokosowym sosie curry z brokułem, papryką, imbirem i limonką, podane z ryżem jaśminowym. Roślinne curry w tajskim stylu, pełne białka i aromatu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'STEW',
    ingredients: [
      ['tofu', 400, 'g'],
      ['edamame', 100, 'g'],
      ['ryż jaśminowy', 100, 'g'],
      ['mleko kokosowe z puszki', 100, 'ml'],
      ['bulion warzywny', 200, 'ml'],
      ['brokuł', 200, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cebula', 80, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['curry', 6, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['limonka', 20, 'g'],
      ['kolendra', 10, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy w 200 ml wody pod przykryciem przez 12 minut, potem odstaw na 5 minut.',
      'Tofu odsącz, osusz i pokrój w kostkę. Obsmaż na oleju na dużym ogniu 6–7 minut, aż będzie złote, i odłóż na talerz.',
      'Na tej samej patelni podsmaż pokrojoną cebulę, starty imbir i czosnek przez 2 minuty. Dodaj curry i smaż jeszcze 30 sekund.',
      'Wlej mleko kokosowe i bulion warzywny, dodaj różyczki brokułu i paprykę w paskach. Gotuj 6 minut.',
      'Wrzuć edamame i tofu, gotuj 3 minuty. Dopraw solą i sokiem z limonki.',
      'Podawaj z ryżem, posypane posiekaną kolendrą.',
    ],
    photo:
      'Golden tofu cubes, broccoli florets, red pepper strips and green edamame in a creamy yellow coconut curry sauce next to jasmine rice, topped with coriander',
    vessel: 'bowl',
  },
  {
    plan: 'OB-063',
    title: 'Gulasz z soczewicy i ziemniaków',
    description:
      'Gęsty gulasz z zielonej soczewicy, ziemniaków, papryki i marchewki w pomidorowym sosie z majerankiem i słodką papryką. Gotujesz raz, a na drugi i trzeci dzień smakuje jeszcze lepiej.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica zielona', 220, 'g'],
      ['ziemniak', 250, 'g'],
      ['marchew', 100, 'g'],
      ['cebula', 100, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['passata pomidorowa', 300, 'ml'],
      ['bulion warzywny', 300, 'ml'],
      ['olej rzepakowy', 10, 'ml'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 4, 'g'],
      ['majeranek', 2, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Soczewicę przepłucz na sitku. Ziemniaki i marchew obierz i pokrój w kostkę, paprykę w paski, cebulę i czosnek posiekaj.',
      'Na oleju w dużym garnku zeszklij cebulę, dodaj czosnek, słodką paprykę i kmin rzymski, smaż 1 minutę.',
      'Dodaj soczewicę, ziemniaki, marchew i liść laurowy. Wlej bulion warzywny i 300 ml wody, zagotuj i gotuj pod przykryciem 20 minut.',
      'Wmieszaj paprykę i passatę, gotuj jeszcze 10–15 minut, aż soczewica i ziemniaki będą miękkie, a sos gęsty.',
      'Dopraw majerankiem i solą, wyjmij liść laurowy. Gulasz przechowuj w lodówce do 3 dni i odgrzewaj z łyżką wody.',
    ],
    photo:
      'Thick lentil and potato stew in rich red tomato sauce with carrot and red pepper pieces, sprinkled with dried marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'OB-064',
    title: 'Kotlety z fasoli i kaszy jaglanej z surówką',
    description:
      'Rumiane kotlety z czerwonej fasoli i kaszy jaglanej z wędzoną papryką i natką, podane z chrupiącą surówką z marchewki i jabłka. Roślinny obiad, który smakuje jak klasyczny schabowy z dodatkami.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['fasola czerwona z puszki', 240, 'g'],
      ['kasza jaglana', 80, 'g'],
      ['cebula', 80, 'g'],
      ['mąka z ciecierzycy', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['papryka wędzona mielona', 2, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['marchew', 200, 'g'],
      ['jabłko', 150, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz wrzątkiem i ugotuj w 200 ml wody pod przykryciem przez 15 minut. Przestudź.',
      'Fasolę odsącz, przepłucz i rozgnieć tłuczkiem. Dodaj kaszę, drobno posiekaną cebulę, przeciśnięty czosnek, mąkę z ciecierzycy, wędzoną paprykę, kmin, natkę i połowę soli. Wyrób masę.',
      'Mokrymi dłońmi uformuj 6 kotletów. Smaż je na oleju na średnim ogniu po 4 minuty z każdej strony, aż będą rumiane.',
      'Marchew i jabłko zetrzyj na tarce, skrop sokiem z cytryny i dopraw resztą soli.',
      'Podawaj kotlety z surówką.',
    ],
    photo:
      'Three golden-brown bean and millet patties flecked with parsley next to a fresh grated carrot and apple slaw',
  },
  {
    plan: 'OB-065',
    title: 'Chili z indykiem i czarną fasolą',
    description:
      'Gęste chili z mielonego indyka, czarnej fasoli, kukurydzy i pomidorów, z kuminem, wędzoną papryką i świeżym chili. Podane z łyżką jogurtu i kolendrą, świetnie znosi odgrzewanie przez kilka dni.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['indyk mielony', 350, 'g'],
      ['fasola czarna z puszki', 240, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['cebula', 100, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['papryczka chili', 10, 'g'],
      ['kmin rzymski', 3, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['oregano', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['jogurt naturalny', 100, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Cebulę, czosnek i papryczkę chili posiekaj, paprykę pokrój w kostkę. Fasolę i kukurydzę odsącz.',
      'Na oleju w garnku podsmaż cebulę 3 minuty, dodaj indyka i smaż 6–7 minut, rozbijając go łopatką.',
      'Dodaj czosnek, chili, kmin rzymski, wędzoną paprykę i oregano, smaż 1 minutę. Wrzuć paprykę.',
      'Wlej pomidory z puszki, zagotuj i duś pod przykryciem 15 minut na małym ogniu.',
      'Dodaj fasolę i kukurydzę, gotuj bez przykrycia jeszcze 10 minut, aż chili zgęstnieje.',
      'Podawaj z łyżką jogurtu i posiekaną kolendrą. W lodówce postoi 3 dni.',
    ],
    photo:
      'Thick red turkey chili with black beans, sweetcorn and pepper pieces, topped with a dollop of white yogurt and fresh coriander leaves',
    vessel: 'bowl',
  },
  {
    plan: 'OB-066',
    title: 'Dal z czerwonej soczewicy z ryżem basmati',
    description:
      'Aksamitny dal z czerwonej soczewicy z kurkumą, garam masalą, imbirem i szpinakiem, podany z sypkim ryżem basmati i limonką. Tani, rozgrzewający klasyk kuchni indyjskiej gotowy w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica czerwona', 240, 'g'],
      ['ryż basmati', 80, 'g'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 15, 'g'],
      ['kurkuma', 3, 'g'],
      ['garam masala', 4, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['olej kokosowy', 8, 'g'],
      ['szpinak', 200, 'g'],
      ['kolendra', 10, 'g'],
      ['limonka', 20, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Ugotuj ryż basmati w 160 ml wody pod przykryciem przez 12 minut. Soczewicę przepłucz kilka razy zimną wodą.',
      'Na oleju kokosowym podsmaż posiekaną cebulę 4 minuty, dodaj starty imbir, czosnek, kmin rzymski, kurkumę i garam masalę. Smaż 1 minutę.',
      'Wsyp soczewicę, dodaj pomidory z puszki i 700 ml wody. Gotuj 15–18 minut, często mieszając, aż soczewica się rozpadnie.',
      'Wmieszaj szpinak i gotuj 2 minuty, aż zwiędnie. Dopraw solą i sokiem z limonki.',
      'Podawaj dal z ryżem, posypany posiekaną kolendrą.',
    ],
    photo:
      'Creamy golden-orange red lentil dal with wilted spinach next to fluffy basmati rice, garnished with chopped coriander',
    vessel: 'bowl',
  },
  {
    plan: 'OB-067',
    title: 'Tofu w sosie orzechowym z makaronem ryżowym',
    description:
      'Chrupiące tofu i makaron ryżowy z brokułem i marchewką w kremowym sosie z masła orzechowego, limonki, imbiru i sosu sojowego. Tajskie smaki w szybkim obiedzie z jednego woka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'PASTA',
    ingredients: [
      ['tofu', 400, 'g'],
      ['makaron ryżowy', 100, 'g'],
      ['masło orzechowe', 40, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['limonka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['syrop klonowy', 10, 'g'],
      ['brokuł', 200, 'g'],
      ['marchew', 100, 'g'],
      ['cebula dymka', 30, 'g'],
      ['papryczka chili', 10, 'g'],
      ['olej rzepakowy', 10, 'ml'],
    ],
    steps: [
      'Makaron ryżowy zalej wrzątkiem na 8 minut, potem odcedź i przelej zimną wodą.',
      'Wymieszaj masło orzechowe, sos sojowy, sok z limonki, syrop klonowy, starty imbir, przeciśnięty czosnek i 80 ml ciepłej wody na gładki sos.',
      'Tofu osusz, pokrój w kostkę i obsmaż na oleju w woku 7 minut, aż będzie chrupiące.',
      'Dodaj różyczki brokułu i marchew pokrojoną w słupki, smaż 4 minuty, mieszając.',
      'Wrzuć makaron i sos, podgrzewaj 2 minuty, aż sos oblepi składniki. Posyp dymką i plasterkami chili.',
    ],
    photo:
      'Rice noodles tossed with crispy tofu cubes, broccoli and carrot sticks in creamy peanut sauce, topped with sliced spring onion and red chili rings',
    vessel: 'bowl',
  },
  {
    plan: 'OB-068',
    title: 'Pierogi z kaszą gryczaną i grzybami',
    description:
      'Domowe pierogi nadziane kaszą gryczaną, pieczarkami i suszonymi grzybami leśnymi, podane z zeszkloną cebulką i kwaśną śmietaną. Aromatyczny, jesienny klasyk z polskiej kuchni.',
    mealType: 'LUNCH',
    difficulty: 'HARD',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DUMPLINGS',
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['kasza gryczana', 80, 'g'],
      ['pieczarka', 200, 'g'],
      ['grzyb suszony', 10, 'g'],
      ['cebula', 150, 'g'],
      ['majeranek', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['śmietana 18', 60, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Suszone grzyby zalej 150 ml wrzątku na 20 minut. Kaszę gryczaną ugotuj w 170 ml wody pod przykryciem przez 15 minut.',
      'Mąkę wymieszaj z połową soli, 15 ml oleju i około 110 ml ciepłej wody. Zagnieć gładkie ciasto, przykryj miską i odstaw na 20 minut.',
      'Połowę cebuli i pieczarki posiekaj drobno, odsączone grzyby pokrój. Podsmaż wszystko na 5 ml oleju przez 8 minut, wymieszaj z kaszą, majerankiem, pieprzem i resztą soli.',
      'Rozwałkuj ciasto na 2 mm, wykrawaj krążki szklanką, nakładaj farsz i dokładnie sklejaj brzegi.',
      'Gotuj pierogi partiami w osolonym wrzątku 3 minuty od wypłynięcia.',
      'Resztę cebuli pokrój w piórka i zeszklij na pozostałym oleju. Podawaj pierogi polane cebulką, ze śmietaną.',
    ],
    photo:
      'Boiled half-moon pierogi filled with buckwheat and mushrooms, topped with golden fried onion and a spoonful of sour cream',
  },
  {
    plan: 'OB-069',
    title: 'Makaron z pesto z jarmużu i orzechami',
    description:
      'Spaghetti w intensywnie zielonym pesto z jarmużu, orzechów włoskich, czosnku i cytryny, z pieczonymi pomidorkami koktajlowymi. Jesienna, roślinna odmiana pesto — gotowa w kwadrans od zagotowania wody.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    seasons: ['AUTUMN'],
    equipment: ['BLENDER'],
    ingredients: [
      ['makaron spaghetti', 200, 'g'],
      ['jarmuż', 120, 'g'],
      ['orzech włoski', 40, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['czosnek', 2, 'szt'],
      ['cytryna', 20, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['płatki chili', 1, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Ugotuj spaghetti al dente w osolonej wodzie według opakowania. Przed odcedzeniem odlej 100 ml wody z gotowania.',
      'Jarmuż oderwij od twardych łodyg i blanszuj 1 minutę we wrzątku, potem przelej zimną wodą i odciśnij.',
      'Orzechy włoskie podpraż 3 minuty na suchej patelni. Zmiksuj w blenderze jarmuż, większość orzechów, czosnek, sok z cytryny, 25 ml oliwy i resztę soli na gęste pesto.',
      'Na pozostałej oliwie podsmaż przekrojone pomidorki koktajlowe przez 3 minuty.',
      'Wymieszaj makaron z pesto, rozrzedzając je wodą z gotowania. Podawaj z pomidorkami, resztą posiekanych orzechów i płatkami chili.',
    ],
    photo:
      'Spaghetti coated in vivid green kale pesto with blistered cherry tomatoes, chopped toasted walnuts and a pinch of chili flakes',
    vessel: 'bowl',
  },
  {
    plan: 'OB-070',
    title: 'Burgery z ciecierzycy z frytkami z batatów',
    description:
      'Chrupiące kotlety z ciecierzycy z kuminem i wędzoną papryką w miękkiej bułce z sosem czosnkowym, sałatą i pomidorem, do tego pieczone frytki z batatów. Roślinny burger, który zadowoli też mięsożerców.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['OVEN'],
    ingredients: [
      ['ciecierzyca z puszki', 240, 'g'],
      ['mąka z ciecierzycy', 30, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['batat', 400, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['bułka do hamburgera', 150, 'g'],
      ['jogurt sojowy', 60, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['pomidor', 120, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C. Bataty pokrój w słupki, wymieszaj z 10 ml oleju i połową wędzonej papryki, rozłóż na blasze i piecz 25–30 minut, w połowie przewracając.',
      'Ciecierzycę odsącz, osusz i rozgnieć widelcem. Dodaj drobno posiekaną cebulę, 1 przeciśnięty ząbek czosnku, kmin, resztę wędzonej papryki i mąkę z ciecierzycy. Uformuj 2 kotlety.',
      'Smaż kotlety na pozostałym oleju po 4–5 minut z każdej strony na średnim ogniu, aż będą chrupiące.',
      'Jogurt sojowy wymieszaj z drugim przeciśniętym ząbkiem czosnku. Bułki przekrój i podpiecz krótko w piekarniku, posmaruj sosem czosnkowym, ułóż sałatę, kotlet i plastry pomidora.',
      'Podawaj burgery z frytkami z batatów.',
    ],
    photo:
      'Chickpea burger in a plain toasted bun with lettuce, tomato slices and creamy garlic sauce, served with a pile of orange baked sweet potato fries',
  },
  {
    plan: 'OB-071',
    title: 'Leczo z ciecierzycą',
    description:
      'Letnie leczo z kolorowej papryki, cukinii i dojrzałych pomidorów, duszone z ciecierzycą i słodką papryką. Proste, roślinne danie z jednego garnka, idealne w sezonie warzyw.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    seasons: ['SUMMER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['papryka czerwona', 300, 'g'],
      ['papryka żółta', 200, 'g'],
      ['cukinia', 300, 'g'],
      ['cebula', 150, 'g'],
      ['pomidor', 400, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 4, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Cebulę pokrój w piórka, paprykę w paski, cukinię w półplasterki. Pomidory sparz, obierz i pokrój w kostkę.',
      'Na oleju w szerokim garnku zeszklij cebulę, dodaj posiekany czosnek i paprykę. Smaż 6 minut.',
      'Dodaj cukinię, pomidory, koncentrat, słodką i ostrą paprykę. Duś pod przykryciem 15 minut.',
      'Wmieszaj odsączoną ciecierzycę i duś bez przykrycia jeszcze 8 minut, aż sos zgęstnieje. Dopraw solą.',
    ],
    photo:
      'Colourful lecso stew of red and yellow pepper strips, zucchini half-moons and chickpeas in a glossy paprika tomato sauce',
    vessel: 'bowl',
  },
  {
    plan: 'OB-072',
    title: 'Kasza gryczana z pieczarkami i wędzonym tofu',
    description:
      'Sypka kasza gryczana z podsmażonymi pieczarkami, cebulą i chrupiącymi kostkami wędzonego tofu, doprawiona majerankiem i natką. Swojski, dymny smak i dużo roślinnego białka w 30 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza gryczana', 100, 'g'],
      ['tofu wędzone', 250, 'g'],
      ['pieczarka', 400, 'g'],
      ['cebula', 100, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['majeranek', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę gryczaną ugotuj w 200 ml wody pod przykryciem przez 15 minut, potem odstaw na 5 minut.',
      'Wędzone tofu pokrój w kostkę i obsmaż na połowie oleju 5–6 minut, aż będzie chrupiące. Odłóż.',
      'Na reszcie oleju zeszklij posiekaną cebulę, dodaj pieczarki w plasterkach i smaż 8 minut, aż odparują i się zrumienią.',
      'Wymieszaj kaszę z pieczarkami i tofu, dopraw majerankiem i pieprzem, posyp posiekaną natką.',
    ],
    photo:
      'Brown buckwheat groats mixed with golden sauteed mushroom slices and crispy smoked tofu cubes, topped with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'OB-073',
    title: 'Wegańska fasolka po bretońsku z wędzoną papryką',
    description:
      'Biała fasola w gęstym pomidorowym sosie z majerankiem, wędzoną papryką i kostkami wędzonego tofu zamiast kiełbasy. Smakuje jak klasyczna fasolka po bretońsku, a jest w pełni roślinna.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['fasola biała z puszki', 300, 'g'],
      ['tofu wędzone', 150, 'g'],
      ['passata pomidorowa', 400, 'ml'],
      ['cebula', 100, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['papryka wędzona mielona', 5, 'g'],
      ['majeranek', 2, 'g'],
      ['czosnek', 2, 'szt'],
      ['liść laurowy', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wędzone tofu pokrój w kostkę, cebulę i czosnek posiekaj. Fasolę odsącz i przepłucz.',
      'Na oleju obsmaż tofu 5 minut, dodaj cebulę i smaż jeszcze 4 minuty, aż się zeszkli. Dorzuć czosnek i wędzoną paprykę.',
      'Wlej passatę, dodaj koncentrat, liść laurowy i 100 ml wody. Gotuj 10 minut na małym ogniu.',
      'Dodaj fasolę i duś 10 minut, aż sos zgęstnieje. Dopraw majerankiem i pieprzem, wyjmij liść laurowy.',
    ],
    photo:
      'White beans and smoked tofu cubes in a thick brick-red smoky tomato sauce, sprinkled with dried marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'OB-074',
    title: 'Bataty faszerowane czarną fasolą i salsą',
    description:
      'Pieczone bataty wypełnione czarną fasolą z kuminem, zwieńczone świeżą salsą z pomidorów, kukurydzy, limonki i kolendry oraz kawałkami awokado. Kolorowy, meksykański obiad bez mięsa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['batat', 600, 'g'],
      ['fasola czarna z puszki', 240, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['pomidor', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['papryczka chili', 10, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
      ['awokado', 1, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Bataty umyj, nakłuj widelcem i piecz w całości na blasze 45–50 minut, aż będą miękkie.',
      'Fasolę odsącz i podgrzej na oliwie z kuminem i wędzoną papryką przez 5 minut, lekko rozgniatając część ziaren.',
      'Pomidor pokrój w kostkę, cebulę i chili posiekaj drobno. Wymieszaj z odsączoną kukurydzą, sokiem z limonki, posiekaną kolendrą i solą.',
      'Awokado obierz i pokrój w kostkę.',
      'Bataty przekrój wzdłuż, lekko rozgnieć miąższ widelcem, nałóż fasolę, salsę i awokado.',
    ],
    photo:
      'A baked sweet potato split lengthwise, its soft orange flesh stuffed with black beans, topped with fresh tomato and corn salsa, avocado cubes and coriander',
  },
  {
    plan: 'OB-075',
    title: 'Gołąbki z kaszą i grzybami w sosie pomidorowym',
    description:
      'Liście białej kapusty zawinięte z kaszą gryczaną, pieczarkami i suszonymi grzybami, zapiekane w gęstym sosie pomidorowym z majerankiem. Zimowe, roślinne gołąbki pełne leśnego aromatu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['kapusta biała', 700, 'g'],
      ['kasza gryczana', 100, 'g'],
      ['pieczarka', 300, 'g'],
      ['grzyb suszony', 15, 'g'],
      ['cebula', 150, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['passata pomidorowa', 500, 'ml'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['majeranek', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Suszone grzyby zalej 150 ml wrzątku na 20 minut. Kaszę ugotuj w 200 ml wody pod przykryciem przez 15 minut.',
      'Z kapusty wytnij głąb i sparz główkę we wrzątku 5–8 minut, zdejmując kolejne zmiękłe liście. Zetnij zgrubienia z nerwów.',
      'Na oleju podsmaż posiekaną cebulę i pieczarki przez 8 minut, dodaj pokrojone grzyby. Wymieszaj z kaszą, majerankiem, pieprzem i połową soli.',
      'Na każdy liść nałóż łyżkę farszu i zwiń ciasno, zakładając boki. Ułóż gołąbki ciasno w naczyniu żaroodpornym.',
      'Passatę wymieszaj z koncentratem, wodą z grzybów i resztą soli, zalej gołąbki i dołóż liść laurowy. Przykryj i piecz w piekarniku w 180°C przez 50 minut.',
      'Podawaj polane sosem i posypane natką pietruszki.',
    ],
    photo:
      'Plump cabbage rolls stuffed with buckwheat and mushrooms, baked in a thick red tomato sauce and sprinkled with chopped parsley',
  },
  {
    plan: 'OB-076',
    title: 'Kotlety sojowe w sosie grzybowym z ziemniakami',
    description:
      'Kotlety sojowe namoczone w bulionie i usmażone na złoto, podane w kremowym sosie z pieczarek i suszonych grzybów z gotowanymi ziemniakami i koperkiem. Roślinna wersja niedzielnego obiadu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    ingredients: [
      ['kotlety sojowe', 120, 'g'],
      ['bulion warzywny', 300, 'ml'],
      ['ziemniak', 500, 'g'],
      ['pieczarka', 300, 'g'],
      ['grzyb suszony', 10, 'g'],
      ['cebula', 100, 'g'],
      ['mąka pszenna', 15, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['mleko sojowe', 150, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['majeranek', 1, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Zagotuj bulion warzywny, zalej nim kotlety sojowe i suszone grzyby, odstaw na 15 minut. Ziemniaki obierz i ugotuj w osolonej wodzie przez 20 minut.',
      'Kotlety odciśnij, zachowując płyn. Obtocz je w słodkiej papryce i majeranku, smaż na 15 ml oleju po 3–4 minuty z każdej strony.',
      'Na reszcie oleju podsmaż posiekaną cebulę i pieczarki w plasterkach przez 8 minut. Dodaj posiekane grzyby i oprósz mąką.',
      'Wlej płyn z moczenia i mleko sojowe, gotuj 3–4 minuty, aż sos zgęstnieje. Włóż kotlety do sosu i podgrzewaj 3 minuty.',
      'Podawaj z ziemniakami posypanymi koperkiem.',
    ],
    photo:
      'Golden soy cutlets in a creamy mushroom sauce with sliced mushrooms, next to boiled potatoes sprinkled with fresh dill',
  },
  {
    plan: 'OB-077',
    title: 'Curry z dynią i ciecierzycą',
    description:
      'Kremowe curry z pieczonej w garnku dyni, ciecierzycy i szpinaku w mleku kokosowym z imbirem i garam masalą, podane z ryżem basmati. Jesienne, rozgrzewające i w pełni roślinne.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    seasons: ['AUTUMN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['dynia', 500, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['mleko kokosowe z puszki', 150, 'ml'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['curry', 6, 'g'],
      ['garam masala', 3, 'g'],
      ['kurkuma', 2, 'g'],
      ['olej kokosowy', 10, 'g'],
      ['szpinak', 100, 'g'],
      ['ryż basmati', 120, 'g'],
      ['kolendra', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż basmati w 240 ml wody pod przykryciem przez 12 minut. Dynię obierz i pokrój w 2-centymetrową kostkę.',
      'Na oleju kokosowym zeszklij posiekaną cebulę, dodaj starty imbir, czosnek, curry, garam masalę i kurkumę. Smaż 1 minutę.',
      'Dodaj dynię, pomidory z puszki i 150 ml wody, gotuj pod przykryciem 12 minut.',
      'Wlej mleko kokosowe, dodaj odsączoną ciecierzycę i gotuj 8 minut, aż dynia będzie miękka. Wmieszaj szpinak i dopraw solą.',
      'Podawaj z ryżem, posypane kolendrą.',
    ],
    photo:
      'Creamy orange pumpkin and chickpea curry with wilted spinach, served with white basmati rice and fresh coriander leaves',
    vessel: 'bowl',
  },
  {
    plan: 'OB-078',
    title: 'Bigos wegetariański z grzybami',
    description:
      'Bigos z kiszonej i świeżej kapusty, pieczarek, suszonych grzybów i śliwek, z wędzonym tofu i wędzoną papryką zamiast mięsa. Długo duszony, głęboki w smaku — prawdziwie zimowe danie.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    seasons: ['WINTER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['kapusta kiszona', 150, 'g'],
      ['kapusta biała', 450, 'g'],
      ['pieczarka', 300, 'g'],
      ['grzyb suszony', 20, 'g'],
      ['cebula', 150, 'g'],
      ['śliwka suszona', 50, 'g'],
      ['koncentrat pomidorowy', 40, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['tofu wędzone', 100, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['majeranek', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['kminek', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Suszone grzyby zalej 200 ml wrzątku na 20 minut, potem pokrój, zachowując wodę. Kapustę kiszoną posiekaj, białą poszatkuj.',
      'Obie kapusty włóż do garnka, wlej wodę z grzybów, dodaj liść laurowy i kminek. Duś pod przykryciem 30 minut.',
      'Na połowie oleju zeszklij posiekaną cebulę, dodaj pieczarki w plasterkach i smaż 8 minut. Na reszcie oleju obsmaż pokrojone w kostkę wędzone tofu.',
      'Dodaj do kapusty pieczarki z cebulą, tofu, grzyby, pokrojone śliwki, koncentrat i wędzoną paprykę.',
      'Duś na małym ogniu jeszcze 30 minut, co jakiś czas mieszając. Dopraw majerankiem i pieprzem.',
    ],
    photo:
      'Rich brown vegetarian bigos with braised sauerkraut and cabbage, mushroom slices, smoked tofu cubes and dark prune pieces',
    vessel: 'bowl',
  },
  {
    plan: 'OB-079',
    title: 'Risotto z grzybami i groszkiem bez sera',
    description:
      'Kremowe risotto na ryżu arborio z pieczarkami, suszonymi grzybami i zielonym groszkiem, wykończone oliwą, cytryną i natką zamiast parmezanu. Włoski klasyk w wersji roślinnej.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'GRAINS',
    ingredients: [
      ['ryż arborio', 160, 'g'],
      ['pieczarka', 250, 'g'],
      ['grzyb suszony', 10, 'g'],
      ['groszek mrożony', 150, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['bulion warzywny', 400, 'ml'],
      ['tymianek suszony', 1, 'g'],
      ['cytryna', 20, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Suszone grzyby zalej 300 ml wrzątku na 15 minut, potem pokrój. Wodę z grzybów połącz z bulionem i trzymaj gorącą na małym ogniu.',
      'Na połowie oliwy zeszklij posiekaną cebulę i czosnek, dodaj pieczarki w plasterkach i tymianek, smaż 6 minut.',
      'Wsyp ryż arborio i mieszaj 2 minuty, aż ziarna staną się szkliste. Dodaj pokrojone grzyby.',
      'Wlewaj gorący bulion po jednej chochli, mieszając, i dodawaj kolejną, gdy ryż wchłonie poprzednią. Gotuj tak 18 minut.',
      'Na ostatnie 3 minuty wsyp groszek. Zdejmij z ognia, wmieszaj resztę oliwy, sok z cytryny, pieprz i posiekaną natkę. Odstaw na 2 minuty i podawaj.',
    ],
    photo:
      'Creamy risotto with sliced mushrooms, bits of dried porcini and bright green peas, sprinkled with chopped parsley and cracked black pepper',
    vessel: 'bowl',
  },
  {
    plan: 'OB-080',
    title: 'Tofu pieczone z warzywami korzeniowymi i sosem tahini',
    description:
      'Kostki tofu pieczone na jednej blasze z marchewką, burakiem, pietruszką i pasternakiem w wędzonej papryce, polane cytrynowym sosem tahini. Kolorowy, sycący obiad z piekarnika.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['tofu', 400, 'g'],
      ['marchew', 200, 'g'],
      ['pietruszka korzeń', 150, 'g'],
      ['burak', 200, 'g'],
      ['pasternak', 150, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['tahini', 30, 'g'],
      ['cytryna', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 210°C z termoobiegiem. Marchew, pietruszkę, pasternak i burak obierz i pokrój w grube słupki.',
      'Tofu odsącz, osusz i pokrój w kostkę. Wymieszaj z warzywami, oliwą, wędzoną papryką, kminem, tymiankiem i solą.',
      'Rozłóż na blasze wyłożonej papierem, buraki osobno z boku, żeby nie zabarwiły reszty. Piecz 30–35 minut, w połowie mieszając.',
      'Tahini wymieszaj z sokiem z cytryny, przeciśniętym czosnkiem i 40 ml zimnej wody na gładki, lejący sos.',
      'Podawaj tofu z warzywami polane sosem tahini i posypane natką pietruszki.',
    ],
    photo:
      'Roasted tofu cubes with caramelised carrot, beetroot, parsnip and parsley root batons, drizzled with creamy tahini sauce and chopped parsley',
  },
  {
    plan: 'OB-081',
    title: 'Łosoś pieczony z pesto i ziemniakami',
    description:
      'Filet z łososia pieczony pod warstwą bazyliowego pesto, z chrupiącymi ziemniakami z rozmarynem i pomidorkami koktajlowymi z tej samej blachy. Elegancki obiad, który robi się prawie sam.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['łosoś', 300, 'g'],
      ['pesto bazyliowe', 40, 'g'],
      ['ziemniak', 500, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['rozmaryn suszony', 1, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['cytryna', 30, 'g'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Ziemniaki pokrój w ćwiartki, wymieszaj z oliwą, rozmarynem i solą, rozłóż na blasze i piecz 20 minut.',
      'Łososia pokrój na 2 porcje, oprósz pieprzem i posmaruj wierzch pesto.',
      'Przesuń ziemniaki na bok, ułóż łososia i pomidorki koktajlowe. Piecz jeszcze 15 minut, aż ryba zacznie się rozdzielać na płatki.',
      'Podawaj z rukolą i ćwiartką cytryny do skropienia ryby.',
    ],
    photo:
      'Baked salmon fillet topped with green basil pesto, golden rosemary-roasted potato quarters, roasted cherry tomatoes, rocket and a lemon wedge',
  },
  {
    plan: 'OB-082',
    title: 'Dorsz w sosie curry z ryżem',
    description:
      'Delikatne kawałki dorsza gotowane w kokosowym sosie z czerwoną pastą curry, papryką i fasolką szparagową, podane z ryżem jaśminowym i limonką. Tajski obiad bez nabiału w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'STEW',
    ingredients: [
      ['dorsz', 350, 'g'],
      ['ryż jaśminowy', 140, 'g'],
      ['mleko kokosowe z puszki', 200, 'ml'],
      ['pasta curry', 30, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['fasolka szparagowa', 150, 'g'],
      ['cebula dymka', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy w 280 ml wody pod przykryciem przez 12 minut, potem odstaw na 5 minut.',
      'Na oleju podsmaż posiekany czosnek, starty imbir i białą część dymki przez 1 minutę. Dodaj pastę curry i smaż 1 minutę.',
      'Wlej mleko kokosowe i 100 ml wody, dodaj paprykę w paskach i fasolkę szparagową. Gotuj 6 minut.',
      'Włóż dorsza pokrojonego w duże kawałki i gotuj pod przykryciem 5–6 minut, aż ryba będzie biała i krucha. Skrop sokiem z limonki.',
      'Podawaj z ryżem, posypane zieloną częścią dymki i kolendrą.',
    ],
    photo:
      'Chunks of flaky white cod in a smooth orange-red coconut curry sauce with bright red bell pepper strips and green beans, beside a neat mound of jasmine rice, topped with sliced spring onion and fresh coriander',
    vessel: 'bowl',
  },
  {
    plan: 'OB-083',
    title: 'Pstrąg w migdałach z młodymi ziemniakami',
    description:
      'Całe pstrągi smażone na patelni i polane masłem ze złotymi płatkami migdałów, z młodymi ziemniakami z koperkiem i mizerią na jogurcie. Letni obiad z nutą klasycznej kuchni.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SUMMER'],
    ingredients: [
      ['pstrąg', 600, 'g'],
      ['migdał', 30, 'g'],
      ['masło', 20, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['ziemniak młody', 500, 'g'],
      ['koperek', 15, 'g'],
      ['cytryna', 40, 'g'],
      ['ogórek', 200, 'g'],
      ['jogurt naturalny', 80, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Młode ziemniaki wyszoruj i ugotuj w osolonej wodzie przez 15–18 minut.',
      'Ogórek pokrój w cienkie plasterki, wymieszaj z jogurtem, połową koperku i szczyptą soli.',
      'Sprawione pstrągi (2 sztuki) opłucz, osusz i natnij skórę w 2 miejscach, oprósz resztą soli i pieprzem. Smaż na oleju po 5–6 minut z każdej strony, aż mięso zacznie odchodzić od ości. Przełóż na talerze.',
      'Na tej samej patelni roztop masło, wsyp płatki migdałów i praż 2 minuty, aż się zezłocą. Dodaj sok z połowy cytryny.',
      'Polej pstrągi masłem z migdałami, podawaj z ziemniakami posypanymi resztą koperku, mizerią i cząstką cytryny.',
    ],
    photo:
      'Whole pan-fried trout topped with golden toasted almond flakes in butter, with dill new potatoes, creamy cucumber and yogurt salad and a lemon wedge',
  },
  {
    plan: 'OB-084',
    title: 'Makrela z grilla z sałatką z pomidorów i cebuli',
    description:
      'Cała makrela z grilla ogrodowego z czosnkiem, cytryną i tymiankiem, z chrupiącą skórką, podana z soczystą sałatką z pomidorów i czerwonej cebuli. Najprostsza majówkowa ryba na ruszt.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['makrela', 600, 'g'],
      ['czosnek', 2, 'szt'],
      ['cytryna', 50, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['pomidor', 400, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['ocet winny', 10, 'ml'],
      ['natka pietruszki', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Rozpal grill i doprowadź go do średniej temperatury (ok. 200°C). Makrele wypatrosz, opłucz i osusz, na bokach natnij skórę w 3 miejscach.',
      'Natrzyj ryby 10 ml oliwy, słodką papryką, tymiankiem, połową soli i pieprzem. Do środka włóż plasterki czosnku i połowę cytryny w plasterkach.',
      'Grilluj makrele na czystym, dobrze rozgrzanym ruszcie albo w koszyku do ryb po 6–8 minut z każdej strony, aż skórka będzie chrupiąca, a mięso odchodzi od ości. Na patelni grillowej smaż je po 6–7 minut z każdej strony na średnim ogniu.',
      'Pomidory pokrój w ósemki, czerwoną cebulę w cienkie piórka. Wymieszaj z resztą oliwy, octem winnym, resztą soli i posiekaną natką.',
      'Podawaj makrele z sałatką i resztą cytryny.',
    ],
    photo:
      'One whole grilled mackerel with charred striped skin and lemon slices tucked inside, beside a juicy tomato and red onion salad with parsley',
  },
];
