/**
 * Katalog 1000 — część OB-d: obiady OB-085 … OB-112 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Ryby ──
  {
    plan: 'OB-085',
    title: 'Mintaj zapiekany pod pierzynką z warzyw',
    description:
      'Delikatny mintaj zapiekany pod warstwą duszonej marchewki, pora i cebuli ze śmietaną i odrobiną żółtego sera, podany z ziemniakami. Domowy, łagodny obiad rybny, który smakuje także dzieciom.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['mintaj', 400, 'g'],
      ['marchew', 150, 'g'],
      ['por', 100, 'g'],
      ['cebula', 100, 'g'],
      ['śmietana 12', 80, 'g'],
      ['ser żółty', 40, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['ziemniak', 500, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 190°C (góra–dół). Ziemniaki obierz, pokrój na części i gotuj w osolonej wodzie 20 minut.',
      'Marchew zetrzyj na grubych oczkach, por i cebulę pokrój w cienkie półplasterki. Duś warzywa na oleju pod przykryciem 8–10 minut, aż zmiękną.',
      'Zdejmij warzywa z ognia, wmieszaj śmietanę, dopraw pieprzem i szczyptą soli.',
      'Filety mintaja osusz, oprósz resztą soli i pieprzem, ułóż w natłuszczonym naczyniu żaroodpornym.',
      'Przykryj rybę warstwą warzyw, posyp startym żółtym serem i zapiekaj 20 minut, aż ser się zezłoci.',
      'Podawaj z ugotowanymi ziemniakami.',
    ],
    photo:
      'Baked white pollock fillet under a golden layer of grated carrot, leek and melted cheese, served with boiled potatoes',
  },
  {
    plan: 'OB-086',
    title: 'Morszczuk w sosie pomidorowym z oliwkami i kaszą',
    description:
      'Kawałki morszczuka duszone w sosie z pomidorów, czosnku, oregano i czarnych oliwek, podane z sypką kaszą bulgur. Śródziemnomorski obiad z jednej patelni, lekki i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'MAIN',
    ingredients: [
      ['morszczuk', 400, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['oliwka czarna', 40, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['oregano', 2, 'g'],
      ['bulgur', 140, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Bulgur wsyp do garnka, zalej 300 ml osolonej wody, zagotuj i gotuj pod przykryciem 12 minut, potem odstaw na 5 minut.',
      'Cebulę posiekaj, czosnek przeciśnij. Zeszklij je na oliwie na dużej patelni przez 4 minuty.',
      'Dodaj pomidory z puszki, oregano i pokrojone na pół oliwki, gotuj sos 8 minut.',
      'Morszczuka pokrój na 4 kawałki, oprósz solą i włóż do sosu. Duś pod przykryciem 8–10 minut, aż ryba zacznie się rozpadać.',
      'Podawaj rybę z sosem na kaszy, posypaną posiekaną natką pietruszki.',
    ],
    photo:
      'Flaky hake pieces in a rich red tomato sauce with black olives and oregano, next to fluffy bulgur sprinkled with parsley',
  },
  {
    plan: 'OB-087',
    title: 'Pulpety z dorsza w sosie koperkowym',
    description:
      'Miękkie pulpety z mielonego dorsza gotowane w bulionie i podane w kremowym sosie koperkowym z ziemniakami. Klasyczny, łagodny obiad, dobry sposób na rybę dla całej rodziny.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    ingredients: [
      ['dorsz', 400, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 30, 'g'],
      ['cebula', 60, 'g'],
      ['koperek', 20, 'g'],
      ['bulion warzywny', 250, 'ml'],
      ['śmietana 18', 100, 'g'],
      ['mąka pszenna', 15, 'g'],
      ['masło', 10, 'g'],
      ['ziemniak', 500, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i gotuj w wodzie 20 minut.',
      'Dorsza pokrój i zmiel w malakserze albo drobno posiekaj nożem. Dodaj jajko, bułkę tartą, bardzo drobno startą cebulę, połowę koperku i pieprz, wyrób masę.',
      'Mokrymi dłońmi uformuj 10–12 pulpetów. Zagotuj bulion z 250 ml wody, włóż pulpety i gotuj na małym ogniu 12 minut.',
      'Masło rozpuść w rondelku, dodaj mąkę i smaż 1 minutę. Wlej stopniowo 250 ml wywaru z pulpetów, mieszając, i gotuj 3 minuty, aż sos zgęstnieje.',
      'Zdejmij sos z ognia, wmieszaj śmietanę i resztę posiekanego koperku, włóż pulpety i podgrzej 2 minuty bez gotowania.',
      'Podawaj pulpety w sosie z ziemniakami.',
    ],
    photo:
      'Round white cod meatballs in a creamy pale dill sauce flecked with green herbs, with boiled potatoes on the side',
  },
  {
    plan: 'OB-088',
    title: 'Zupa rybna z pomidorami po śródziemnomorsku',
    description:
      'Rozgrzewająca zupa z kawałkami dorsza, pomidorami, ziemniakami i selerem naciowym, doprawiona oregano i cytryną. Lekka, a sycąca — pełny obiad w jednej misce.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'SOUP',
    ingredients: [
      ['dorsz', 350, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['ziemniak', 200, 'g'],
      ['cebula', 100, 'g'],
      ['seler naciowy', 80, 'g'],
      ['marchew', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['bulion warzywny', 200, 'ml'],
      ['oregano', 2, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Cebulę, seler naciowy i marchew pokrój w drobną kostkę, czosnek posiekaj. Podsmaż je na oliwie w garnku przez 5 minut.',
      'Dodaj obrane ziemniaki pokrojone w kostkę, pomidory z puszki, oregano, bulion i 550 ml wody. Gotuj 15 minut, aż ziemniaki zmiękną.',
      'Dorsza pokrój w duże kawałki, włóż do zupy i gotuj na małym ogniu 6–8 minut, nie mieszając zbyt mocno.',
      'Dopraw zupę sokiem z cytryny i podawaj posypaną posiekaną natką pietruszki.',
    ],
    photo:
      'Bowl of red Mediterranean tomato fish soup with chunks of white cod, diced potato, carrot and celery, topped with parsley and a lemon wedge',
    vessel: 'bowl',
  },
  {
    plan: 'OB-089',
    title: 'Fish and chips',
    description:
      'Chrupiący dorsz w złotej panierce i grube frytki z ziemniaków, oba z airfryera, z cytryną i szybkim sosem jogurtowym z ogórkiem i koperkiem. Brytyjska klasyka bez głębokiego tłuszczu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['dorsz', 400, 'g'],
      ['mąka pszenna', 40, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 60, 'g'],
      ['ziemniak', 600, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1, 'g'],
      ['cytryna', 50, 'g'],
      ['jogurt naturalny', 80, 'g'],
      ['ogórek kiszony', 40, 'g'],
      ['koperek', 5, 'g'],
    ],
    steps: [
      'Ziemniaki umyj i pokrój w grube słupki, namocz 10 minut w zimnej wodzie, osusz i wymieszaj z połową oleju, papryką i połową soli.',
      'Piecz frytki w airfryerze w 200°C przez 20–22 minuty, potrząsając koszem co 7 minut. Przełóż do naczynia i przykryj.',
      'Dorsza pokrój na 4 kawałki, oprósz resztą soli. Obtaczaj kolejno w mące, roztrzepanym jajku i bułce tartej, skrop resztą oleju.',
      'Piecz rybę w airfryerze w 190°C przez 10–12 minut, obracając w połowie, aż panierka będzie złota i chrupiąca.',
      'W piekarniku: frytki 220°C, termoobieg, 30–35 minut, a rybę dołóż na ostatnie 15 minut.',
      'Ogórek kiszony i koperek posiekaj, wymieszaj z jogurtem. Podawaj rybę z frytkami, sosem i ćwiartkami cytryny.',
    ],
    photo:
      'Golden crumbed cod fillets with thick-cut crispy potato chips, lemon wedges and a small bowl of creamy dill pickle sauce',
  },
  {
    plan: 'OB-090',
    title: 'Miska burrito z łososiem i fasolą',
    description:
      'Ryż z limonką i kolendrą, czarna fasola, kukurydza, pomidory i awokado, a na wierzchu łosoś pieczony w kminie i wędzonej papryce. Kolorowa miska w stylu meksykańskim, sycąca i bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['łosoś', 250, 'g'],
      ['ryż biały', 120, 'g'],
      ['fasola czarna z puszki', 200, 'g'],
      ['kukurydza z puszki', 100, 'g'],
      ['pomidor', 150, 'g'],
      ['awokado', 1, 'szt'],
      ['limonka', 60, 'g'],
      ['kolendra', 10, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj ryż w osolonej wodzie według opakowania, około 15 minut. Wymieszaj z sokiem z połowy limonki i połową posiekanej kolendry.',
      'Łososia pokrój w kostkę 3 cm, obtocz w kminie, wędzonej papryce i oleju. Smaż na rozgrzanej patelni 5–6 minut, obracając, aż się zrumieni.',
      'Fasolę i kukurydzę odsącz i przepłucz, podgrzej krótko na patelni po rybie.',
      'Pomidor i awokado pokrój w kostkę, skrop resztą soku z limonki.',
      'Nałóż do misek ryż, obok fasolę, kukurydzę, pomidory, awokado i łososia. Posyp resztą kolendry.',
    ],
    photo:
      'Burrito bowl with lime cilantro rice, black beans, sweet corn, diced tomato, avocado cubes and spiced seared salmon chunks',
    vessel: 'bowl',
  },
  {
    plan: 'OB-091',
    title: 'Łosoś z warzywami z jednej blachy',
    description:
      'Filety łososia pieczone na jednej blasze z brokułem, papryką, cukinią, czerwoną cebulą i pomidorkami, z cytryną i ziołami. Mało zmywania, dużo warzyw i lekki obiad w pół godziny pieczenia.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['łosoś', 240, 'g'],
      ['brokuł', 250, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cukinia', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['cytryna', 50, 'g'],
      ['czosnek', 2, 'szt'],
      ['zioła prowansalskie', 2, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Brokuł podziel na różyczki, paprykę i cukinię pokrój w kawałki, cebulę w ósemki.',
      'Wymieszaj warzywa na blasze z oliwą, przeciśniętym czosnkiem, połową ziół i połową soli. Piecz 12 minut.',
      'Łososia oprósz resztą soli i ziół. Zsuń warzywa na boki, ułóż łososia i pomidorki, na rybę połóż plasterki cytryny.',
      'Piecz jeszcze 12–15 minut, aż łosoś będzie różowy w środku i łatwo się rozdzieli.',
      'Podawaj prosto z blachy, skropione sokiem z pozostałej cytryny.',
    ],
    photo:
      'Sheet pan with two roasted salmon fillets topped with lemon slices among charred broccoli, red pepper, zucchini, red onion and cherry tomatoes',
  },
  {
    plan: 'OB-092',
    title: 'Spaghetti z sardynkami, pomidorami i kaparami',
    description:
      'Spaghetti w sosie z pomidorów, czosnku i chili z kawałkami sardynek, kaparami i skórką z cytryny. Szybki, wyrazisty makaron w stylu południowych Włoch, zrobiony z produktów ze spiżarni.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron spaghetti', 180, 'g'],
      ['sardynka w oleju', 120, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['kapary', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['płatki chili', 1, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Ugotuj spaghetti al dente w lekko osolonej wodzie, około 9 minut. Odlej pół szklanki wody z gotowania.',
      'Na oliwie podsmaż posiekany czosnek i płatki chili przez 1 minutę, dodaj pomidory z puszki i gotuj 8 minut.',
      'Wmieszaj odsączone kapary i sardynki połamane na duże kawałki, podgrzewaj 2 minuty.',
      'Dodaj makaron, skórkę otartą z cytryny i odrobinę wody z gotowania, wymieszaj, żeby sos oblepił spaghetti.',
      'Podawaj posypane posiekaną natką pietruszki i skropione sokiem z cytryny.',
    ],
    photo:
      'Spaghetti tossed in chunky tomato sauce with pieces of sardine, capers, chili flakes, lemon zest and chopped parsley',
  },
  {
    plan: 'OB-093',
    title: 'Kedgeree — ryż z wędzoną makrelą, jajkiem i groszkiem',
    description:
      'Ryż basmati duszony z cebulą, masłem i łagodnym curry, wymieszany z wędzoną makrelą i groszkiem, podany z jajkiem na twardo. Anglo-indyjska klasyka, która świetnie wykorzystuje wędzoną rybę.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    ingredients: [
      ['ryż basmati', 140, 'g'],
      ['makrela wędzona', 160, 'g'],
      ['jajko', 2, 'szt'],
      ['groszek mrożony', 150, 'g'],
      ['cebula', 100, 'g'],
      ['masło', 20, 'g'],
      ['curry', 4, 'g'],
      ['kurkuma', 1, 'g'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Jajka ugotuj na twardo przez 9 minut, ostudź w zimnej wodzie i obierz.',
      'Cebulę posiekaj i zeszklij na maśle w garnku przez 5 minut. Dodaj curry i kurkumę, smaż 30 sekund.',
      'Wsyp przepłukany ryż, wymieszaj, wlej 300 ml wody, przykryj i gotuj na małym ogniu 12 minut.',
      'Dosyp groszek, przykryj i trzymaj na ogniu jeszcze 3 minuty. Makrelę obierz ze skóry i ości, rozdrobnij na płatki.',
      'Wmieszaj delikatnie makrelę i sok z cytryny, nałóż na talerze, ułóż ćwiartki jajek i posyp natką pietruszki.',
    ],
    photo:
      'Golden curried basmati rice with flakes of smoked mackerel, green peas, quartered hard-boiled eggs and chopped parsley',
  },
  {
    plan: 'OB-094',
    title: 'Łosoś z kaszą jaglaną, szpinakiem i sosem cytrynowym',
    description:
      'Rumiany łosoś z patelni na puszystej kaszy jaglanej ze szpinakiem, polany jogurtowym sosem z cytryną, czosnkiem i koperkiem. Pełnowartościowy obiad bez glutenu, gotowy w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    ingredients: [
      ['łosoś', 250, 'g'],
      ['kasza jaglana', 120, 'g'],
      ['szpinak', 200, 'g'],
      ['cytryna', 60, 'g'],
      ['jogurt grecki', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 10, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz gorącą wodą, zalej 300 ml osolonej wody i gotuj pod przykryciem 15 minut.',
      'Jogurt wymieszaj z sokiem i skórką z połowy cytryny, jednym przeciśniętym ząbkiem czosnku i posiekanym koperkiem.',
      'Łososia oprósz solą i pieprzem, smaż na oleju skórą do dołu 4 minuty, obróć i smaż jeszcze 3 minuty.',
      'Na tej samej patelni podsmaż drugi ząbek czosnku, dodaj szpinak i duś 2 minuty, aż zwiędnie. Wmieszaj do kaszy.',
      'Nałóż kaszę ze szpinakiem, połóż łososia, polej sosem cytrynowym i podawaj z resztą cytryny.',
    ],
    photo:
      'Pan-seared salmon fillet with crispy skin on fluffy millet mixed with wilted spinach, drizzled with lemon dill yogurt sauce',
  },
  {
    plan: 'OB-095',
    title: 'Rybna tikka masala z mintajem i ryżem',
    description:
      'Kawałki mintaja marynowane w jogurcie i przyprawach, duszone w aromatycznym sosie pomidorowym z imbirem i garam masalą, podane z ryżem basmati. Łagodne indyjskie curry bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    ingredients: [
      ['mintaj', 400, 'g'],
      ['jogurt naturalny', 150, 'g'],
      ['garam masala', 6, 'g'],
      ['kurkuma', 2, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 3, 'szt'],
      ['cebula', 150, 'g'],
      ['passata pomidorowa', 300, 'ml'],
      ['śmietanka 12', 60, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['ryż basmati', 140, 'g'],
      ['kolendra', 10, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Mintaja pokrój w kostkę 4 cm, wymieszaj z połową jogurtu, połową garam masali, kurkumą i szczyptą soli. Odstaw na 15 minut.',
      'W tym czasie ugotuj ryż basmati w osolonej wodzie, około 12 minut.',
      'Cebulę posiekaj drobno, smaż na oleju 7 minut, aż się zrumieni. Dodaj starty imbir, przeciśnięty czosnek i resztę garam masali, smaż 1 minutę.',
      'Wlej passatę i gotuj sos 8 minut. Zmniejsz ogień, wmieszaj śmietankę i resztę jogurtu.',
      'Włóż rybę z marynatą i duś pod przykryciem 7–8 minut, delikatnie mieszając, żeby się nie rozpadła.',
      'Podawaj z ryżem, posypane posiekaną kolendrą.',
    ],
    photo:
      'Creamy orange tikka masala sauce with tender white pollock chunks and fresh cilantro, beside a mound of basmati rice',
    vessel: 'bowl',
  },
  // ── Krewetki ──
  {
    plan: 'OB-096',
    title: 'Makaron z krewetkami, czosnkiem i chili',
    description:
      'Spaghetti z krewetkami smażonymi na oliwie z dużą ilością czosnku, świeżym chili i pomidorkami koktajlowymi, z natką i cytryną. Prosty włoski obiad gotowy w 20 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron spaghetti', 180, 'g'],
      ['krewetka', 250, 'g'],
      ['czosnek', 4, 'szt'],
      ['papryczka chili', 15, 'g'],
      ['oliwa z oliwek', 25, 'ml'],
      ['pomidor koktajlowy', 150, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['cytryna', 30, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj spaghetti al dente w osolonej wodzie, około 9 minut. Zachowaj pół szklanki wody z gotowania.',
      'Czosnek pokrój w cienkie plasterki, chili w krążki, pomidorki przekrój na pół.',
      'Na oliwie podsmaż czosnek i chili przez 1 minutę, dodaj osuszone krewetki i smaż 2 minuty z każdej strony, aż zróżowieją.',
      'Dodaj pomidorki i smaż 2 minuty, wrzuć makaron i trochę wody z gotowania, wymieszaj energicznie.',
      'Dopraw sokiem z cytryny i posyp posiekaną natką pietruszki.',
    ],
    photo:
      'Spaghetti with pink sautéed shrimp, sliced garlic, red chili rings, halved cherry tomatoes and chopped parsley glistening with olive oil',
  },
  {
    plan: 'OB-097',
    title: 'Makaron z krewetkami w sosie śmietanowo-cytrynowym',
    description:
      'Wstążki tagliatelle w jedwabistym sosie ze śmietanki, cytryny i parmezanu, z krewetkami i świeżym szpinakiem. Elegancki, a szybki obiad na co dzień i na przyjęcie.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron tagliatelle', 180, 'g'],
      ['krewetka', 250, 'g'],
      ['śmietanka 18', 150, 'ml'],
      ['cytryna', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['masło', 10, 'g'],
      ['ser parmezan', 20, 'g'],
      ['szpinak', 80, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj tagliatelle al dente w osolonej wodzie według opakowania.',
      'Na maśle podsmaż przeciśnięty czosnek przez 30 sekund, dodaj krewetki i smaż po 2 minuty z każdej strony. Zdejmij je na talerz.',
      'Na patelnię wlej śmietankę, dodaj skórkę otartą z cytryny i gotuj 3 minuty, aż lekko zgęstnieje. Wmieszaj szpinak i poczekaj, aż zwiędnie.',
      'Dodaj makaron, krewetki, starty parmezan i sok z połowy cytryny, wymieszaj i dopraw pieprzem.',
      'Podawaj od razu, z cząstkami pozostałej cytryny.',
    ],
    photo:
      'Tagliatelle ribbons in a pale creamy lemon sauce with pink shrimp, wilted spinach, grated parmesan and lemon zest',
  },
  {
    plan: 'OB-098',
    title: 'Risotto z krewetkami i cukinią',
    description:
      'Kremowe risotto z ryżu arborio z cukinią, skórką cytryny i odrobiną parmezanu, z krewetkami podsmażonymi na maśle. Włoskie danie, które wymaga tylko cierpliwego mieszania.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'GRAINS',
    ingredients: [
      ['ryż arborio', 160, 'g'],
      ['krewetka', 220, 'g'],
      ['cukinia', 300, 'g'],
      ['szalotka', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['bulion warzywny', 150, 'ml'],
      ['masło', 20, 'g'],
      ['ser parmezan', 15, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Bulion połącz w garnku z 650 ml wody i trzymaj gorący na małym ogniu. Cukinię pokrój w drobną kostkę, szalotkę posiekaj.',
      'Na oliwie zeszklij szalotkę i czosnek przez 3 minuty, wsyp ryż i smaż 1 minutę, aż się zeszkli.',
      'Wlewaj gorący bulion po jednej chochli, mieszając i czekając, aż ryż go wchłonie. Po 10 minutach dodaj cukinię. Gotuj łącznie 18–20 minut.',
      'W tym czasie na połowie masła smaż krewetki po 2 minuty z każdej strony.',
      'Zdejmij risotto z ognia, wmieszaj resztę masła, starty parmezan i skórkę z cytryny, przykryj na 2 minuty.',
      'Nałóż risotto, ułóż krewetki, skrop sokiem z cytryny i posyp natką pietruszki.',
    ],
    photo:
      'Creamy risotto with small green zucchini cubes topped with buttery seared shrimp, lemon zest and chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'OB-099',
    title: 'Paella z krewetkami i kurczakiem',
    description:
      'Ryż z patelni barwiony kurkumą i wędzoną papryką, z kurczakiem, krewetkami, papryką i groszkiem, podany z cytryną. Hiszpańska paella w domowej wersji, bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'GRAINS',
    ingredients: [
      ['ryż arborio', 160, 'g'],
      ['krewetka', 150, 'g'],
      ['filet z kurczaka', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['groszek mrożony', 100, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['kurkuma', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['bulion drobiowy', 150, 'ml'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 50, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę, obsmaż na oliwie na dużej, szerokiej patelni przez 5 minut i zdejmij.',
      'Na tę samą patelnię wrzuć posiekaną cebulę, czosnek i paprykę w paskach, smaż 5 minut. Dodaj kurkumę i wędzoną paprykę, a potem pomidory i gotuj 3 minuty.',
      'Wsyp ryż, wymieszaj, wlej bulion i 450 ml gorącej wody. Rozprowadź ryż równo i gotuj bez mieszania na średnim ogniu 15 minut.',
      'Wciśnij w ryż kurczaka i krewetki, rozsyp groszek. Gotuj jeszcze 6–8 minut, aż płyn się wchłonie, a krewetki zróżowieją.',
      'Zdejmij z ognia, przykryj ściereczką na 5 minut. Podawaj z natką pietruszki i ćwiartkami cytryny.',
    ],
    photo:
      'Wide pan of golden saffron-coloured paella rice with pink shrimp, chicken pieces, red pepper strips, green peas and lemon wedges',
  },
  {
    plan: 'OB-100',
    title: 'Krewetki w curry z mlekiem kokosowym i ryżem',
    description:
      'Krewetki, papryka i fasolka szparagowa w kremowym sosie z czerwonej pasty curry i mleka kokosowego, z limonką i kolendrą, podane z ryżem jaśminowym. Tajski obiad w 30 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'STEW',
    ingredients: [
      ['krewetka', 250, 'g'],
      ['pasta curry', 25, 'g'],
      ['mleko kokosowe z puszki', 200, 'ml'],
      ['ryż jaśminowy', 140, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['fasolka szparagowa', 150, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['limonka', 30, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy według opakowania, około 12 minut.',
      'Paprykę pokrój w paski, fasolkę przekrój na pół.',
      'Na oleju smaż pastę curry przez 1 minutę, wlej mleko kokosowe i zagotuj. Dodaj fasolkę i paprykę, gotuj 6 minut.',
      'Włóż krewetki i gotuj 3–4 minuty, aż zróżowieją. Dopraw sokiem z limonki.',
      'Podawaj z ryżem, posypane posiekaną kolendrą.',
    ],
    photo:
      'Red Thai coconut curry with pink shrimp, red pepper strips and green beans, garnished with cilantro, next to jasmine rice',
    vessel: 'bowl',
  },
  {
    plan: 'OB-101',
    title: 'Pad thai z krewetkami',
    description:
      'Smażony makaron ryżowy z krewetkami, jajkiem, kiełkami i dymką w słodko-kwaśnym sosie z limonki, posypany prażonymi orzeszkami. Najsłynniejsze danie z tajskiego street foodu w domowej kuchni.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'PASTA',
    ingredients: [
      ['makaron ryżowy', 160, 'g'],
      ['krewetka', 200, 'g'],
      ['jajko', 2, 'szt'],
      ['kiełki', 100, 'g'],
      ['cebula dymka', 40, 'g'],
      ['orzeszek ziemny', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 20, 'ml'],
      ['sos rybny', 8, 'ml'],
      ['cukier brązowy', 15, 'g'],
      ['limonka', 60, 'g'],
      ['sos sriracha', 5, 'g'],
    ],
    steps: [
      'Makaron ryżowy namocz w gorącej wodzie na 8–10 minut, aż zmięknie, i odcedź.',
      'Wymieszaj sos: sok z połowy limonki, sos rybny, cukier brązowy, srirachę i 2 łyżki wody.',
      'Orzeszki upraż na suchym woku i posiekaj. Na oleju smaż posiekany czosnek i krewetki przez 2 minuty.',
      'Zsuń krewetki na bok, wbij jajka i mieszaj, aż się zetną. Dodaj makaron i sos, smaż 2–3 minuty, mieszając.',
      'Wrzuć kiełki i pokrojoną dymkę, wymieszaj przez 30 sekund. Podawaj posypane orzeszkami, z ćwiartkami limonki.',
    ],
    photo:
      'Stir-fried rice noodles with pink shrimp, scrambled egg, bean sprouts and spring onion, topped with crushed peanuts and lime wedges',
  },
  {
    plan: 'OB-102',
    title: 'Zupa kokosowa z krewetkami i makaronem ryżowym',
    description:
      'Aromatyczna zupa na mleku kokosowym z imbirem, chili i limonką, z krewetkami, pieczarkami i makaronem ryżowym. Lekki, rozgrzewający obiad w tajskim stylu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'SOUP',
    ingredients: [
      ['mleko kokosowe z puszki', 180, 'ml'],
      ['krewetka', 200, 'g'],
      ['makaron ryżowy', 60, 'g'],
      ['pieczarka', 150, 'g'],
      ['pomidor koktajlowy', 100, 'g'],
      ['imbir', 15, 'g'],
      ['papryczka chili', 10, 'g'],
      ['limonka', 40, 'g'],
      ['sos rybny', 10, 'ml'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Makaron ryżowy zalej wrzątkiem na 8 minut, odcedź i rozłóż do misek.',
      'Imbir pokrój w cienkie plasterki, chili w krążki, pieczarki w plastry. Zagotuj 600 ml wody z imbirem i chili, gotuj 5 minut.',
      'Wlej mleko kokosowe, dodaj pieczarki i przekrojone pomidorki, gotuj 5 minut na małym ogniu.',
      'Włóż krewetki i gotuj 3 minuty. Dopraw sosem rybnym i sokiem z limonki.',
      'Zalej makaron w miskach gorącą zupą i posyp kolendrą.',
    ],
    photo:
      'Bowl of creamy white coconut soup with pink shrimp, rice noodles, sliced mushrooms, cherry tomatoes, red chili and cilantro',
    vessel: 'bowl',
  },
  {
    plan: 'OB-103',
    title: 'Krewetki saganaki w sosie pomidorowym z fetą i orzo',
    description:
      'Makaron orzo ugotowany wprost w gęstym sosie pomidorowym z oregano, z krewetkami i zapieczoną kruszoną fetą. Greckie danie z jednej patelni, które pachnie wakacjami.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'PASTA',
    ingredients: [
      ['krewetka', 250, 'g'],
      ['ser feta', 70, 'g'],
      ['makaron orzo', 160, 'g'],
      ['pomidor', 400, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['oregano', 2, 'g'],
      ['płatki chili', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Cebulę i czosnek posiekaj, zeszklij na oliwie na głębokiej patelni przez 4 minuty.',
      'Dodaj pokrojone w kostkę pomidory, oregano, płatki chili i 400 ml wody, zagotuj. Wsyp orzo i gotuj 10 minut, często mieszając, aż makaron będzie prawie miękki.',
      'Wciśnij krewetki w sos, posyp pokruszoną fetą i gotuj pod przykryciem 4–5 minut, aż krewetki zróżowieją, a feta zmięknie.',
      'Posyp posiekaną natką pietruszki i podawaj prosto z patelni.',
    ],
    photo:
      'Skillet of orzo in thick tomato sauce with pink shrimp and softened crumbled feta, sprinkled with oregano and parsley',
  },
  {
    plan: 'OB-104',
    title: 'Krewetki tikka masala z ryżem basmati',
    description:
      'Krewetki marynowane w jogurcie z przyprawami, obsmażone i dokończone w maślanym sosie pomidorowym ze śmietanką i garam masalą, podane z ryżem basmati. Kremowe curry bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    ingredients: [
      ['krewetka', 250, 'g'],
      ['jogurt naturalny', 80, 'g'],
      ['garam masala', 6, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 3, 'szt'],
      ['cebula', 120, 'g'],
      ['pomidor krojony z puszki', 300, 'g'],
      ['śmietanka 18', 80, 'ml'],
      ['masło', 15, 'g'],
      ['ryż basmati', 140, 'g'],
      ['kolendra', 10, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Krewetki wymieszaj z jogurtem, połową garam masali i papryką, odstaw na 15 minut.',
      'Ugotuj ryż basmati w osolonej wodzie, około 12 minut.',
      'Na maśle smaż posiekaną cebulę 6 minut, dodaj starty imbir, czosnek, kmin i resztę garam masali, smaż 1 minutę. Wlej pomidory i gotuj 10 minut, aż sos zgęstnieje.',
      'Krewetki strząśnij z nadmiaru marynaty i obsmaż na suchej, bardzo gorącej patelni 1 minutę z każdej strony.',
      'Wmieszaj do sosu śmietankę, włóż krewetki i gotuj 2–3 minuty. Podawaj z ryżem, posypane kolendrą.',
    ],
    photo:
      'Smooth orange butter tikka masala sauce with charred pink shrimp and cilantro leaves, served with fluffy basmati rice',
    vessel: 'bowl',
  },
  {
    plan: 'OB-105',
    title: 'Tacos z krewetkami i salsą z mango',
    description:
      'Kukurydziane tortille z krewetkami w wędzonej papryce i kminie, chrupiącą czerwoną kapustą, awokado i słodko-pikantną salsą z mango i limonki. Kolorowy meksykański obiad do jedzenia rękami.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['tortilla kukurydziana', 6, 'szt'],
      ['krewetka', 250, 'g'],
      ['mango', 200, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['limonka', 60, 'g'],
      ['kolendra', 10, 'g'],
      ['papryczka chili', 10, 'g'],
      ['kapusta czerwona', 100, 'g'],
      ['awokado', 1, 'szt'],
      ['jogurt naturalny', 80, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
    ],
    steps: [
      'Mango obierz i pokrój w drobną kostkę, wymieszaj z posiekaną czerwoną cebulą, chili, połową kolendry i sokiem z połowy limonki.',
      'Kapustę poszatkuj bardzo cienko, awokado pokrój w plasterki. Jogurt wymieszaj z odrobiną soku z limonki.',
      'Krewetki wymieszaj z wędzoną papryką, kminem i olejem. Smaż na rozgrzanej patelni 2 minuty z każdej strony.',
      'Tortille podgrzej na suchej patelni po 30 sekund z każdej strony.',
      'Na tortille nałóż kapustę, krewetki, awokado i salsę z mango, polej sosem jogurtowym i posyp resztą kolendry.',
    ],
    photo:
      'Three corn tortilla tacos filled with spiced shrimp, shredded purple cabbage, avocado slices and bright mango salsa with lime and cilantro',
  },
  {
    plan: 'OB-106',
    title: 'Krewetki po cajuńsku z ryżem i kukurydzą',
    description:
      'Krewetki w pikantnej przyprawie cajun z wędzoną papryką, czosnkiem i tymiankiem, smażone z papryką, cebulą i selerem naciowym, na ryżu z kukurydzą. Smak Luizjany bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'MAIN',
    ingredients: [
      ['krewetka', 250, 'g'],
      ['ryż biały', 140, 'g'],
      ['kukurydza z puszki', 150, 'g'],
      ['papryka zielona', 150, 'g'],
      ['cebula', 100, 'g'],
      ['seler naciowy', 80, 'g'],
      ['czosnek', 3, 'szt'],
      ['papryka wędzona mielona', 4, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['oregano', 1, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['cebula dymka', 30, 'g'],
    ],
    steps: [
      'Ugotuj ryż według opakowania, około 15 minut. Pod koniec wmieszaj odsączoną kukurydzę i przykryj.',
      'Wymieszaj przyprawę cajun: wędzoną i ostrą paprykę, tymianek, oregano i czosnek granulowany. Obtocz w niej krewetki.',
      'Na połowie oleju smaż pokrojoną w kostkę paprykę, cebulę, seler naciowy i posiekany czosnek przez 6 minut. Przełóż do miski.',
      'Na reszcie oleju smaż krewetki na mocnym ogniu po 2 minuty z każdej strony. Dodaj z powrotem warzywa i wymieszaj.',
      'Podawaj krewetki z warzywami na ryżu z kukurydzą, posypane pokrojoną dymką.',
    ],
    photo:
      'Cajun spiced red-coated shrimp with sautéed green pepper, onion and celery over white rice with sweet corn, topped with sliced scallions',
  },
  {
    plan: 'OB-107',
    title: 'Ryż smażony z krewetkami i groszkiem',
    description:
      'Ryż jaśminowy smażony na mocnym ogniu z krewetkami, jajkiem, groszkiem, marchewką, imbirem i sosem sojowym. Szybki obiad z woka, najlepszy z ryżu ugotowanego wcześniej.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ryż jaśminowy', 140, 'g'],
      ['krewetka', 200, 'g'],
      ['groszek mrożony', 150, 'g'],
      ['jajko', 2, 'szt'],
      ['marchew', 80, 'g'],
      ['cebula dymka', 40, 'g'],
      ['czosnek', 2, 'szt'],
      ['imbir', 10, 'g'],
      ['sos sojowy', 12, 'ml'],
      ['olej sezamowy', 5, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
    ],
    steps: [
      'Ugotuj ryż według opakowania, około 12 minut, rozłóż na blasze i ostudź. Najlepszy będzie ryż ugotowany dzień wcześniej.',
      'Marchew pokrój w drobną kostkę, dymkę w krążki, czosnek i imbir posiekaj.',
      'Na rozgrzanym woku z olejem rzepakowym smaż krewetki 2 minuty i zdejmij. Wrzuć marchew, czosnek i imbir, smaż 2 minuty, dodaj groszek.',
      'Zsuń warzywa na bok, wbij jajka i mieszaj, aż się zetną. Wsyp ryż i smaż na mocnym ogniu 3–4 minuty, mieszając.',
      'Dodaj krewetki, sos sojowy, olej sezamowy i dymkę, wymieszaj i podawaj.',
    ],
    photo:
      'Wok-fried jasmine rice with pink shrimp, green peas, diced carrot, scrambled egg and scallion rings',
    vessel: 'bowl',
  },
  {
    plan: 'OB-108',
    title: 'Krewetki z cukinią i pomidorkami z kaszą jaglaną',
    description:
      'Krewetki smażone z cukinią, pomidorkami koktajlowymi, czosnkiem i chili, podane na kaszy jaglanej z bazylią i cytryną. Lekki, świeży obiad bez glutenu gotowy w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    ingredients: [
      ['krewetka', 250, 'g'],
      ['cukinia', 300, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['kasza jaglana', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 30, 'g'],
      ['bazylia', 10, 'g'],
      ['płatki chili', 1, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz gorącą wodą, zalej 250 ml osolonej wody i gotuj pod przykryciem 15 minut.',
      'Cukinię pokrój w półplasterki, pomidorki przekrój na pół, czosnek posiekaj.',
      'Na oliwie smaż cukinię 4 minuty na mocnym ogniu, dodaj czosnek, płatki chili i pomidorki, smaż 2 minuty.',
      'Dodaj krewetki i smaż 3–4 minuty, aż zróżowieją. Skrop sokiem z cytryny.',
      'Podawaj na kaszy jaglanej, posypane listkami bazylii.',
    ],
    photo:
      'Pink shrimp sautéed with zucchini half-moons and blistered cherry tomatoes over fluffy yellow millet, garnished with fresh basil',
  },
  {
    plan: 'OB-109',
    title: 'Krewetki w panierce kokosowej z ryżem i sosem chili',
    description:
      'Duże krewetki w chrupiącej panierce z wiórków kokosowych, upieczone w airfryerze, podane z ryżem jaśminowym, ogórkiem i słodkim sosem chili. Smak tajskiej ulicy bez smażenia w głębokim tłuszczu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['krewetka', 300, 'g'],
      ['mąka pszenna', 30, 'g'],
      ['jajko', 1, 'szt'],
      ['wiórki kokosowe', 40, 'g'],
      ['bułka tarta', 30, 'g'],
      ['ryż jaśminowy', 140, 'g'],
      ['sos chili słodki', 40, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['limonka', 30, 'g'],
      ['ogórek', 150, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy według opakowania, około 12 minut.',
      'Wiórki kokosowe wymieszaj z bułką tartą. Krewetki osusz, obtaczaj kolejno w mące, roztrzepanym jajku i mieszance kokosowej.',
      'Ułóż krewetki w koszu airfryera w jednej warstwie, spryskaj olejem i piecz w 190°C przez 7–8 minut, obracając w połowie, aż panierka się zezłoci.',
      'W piekarniku: 210°C, termoobieg, 10–12 minut na blasze z papierem, obracając w połowie.',
      'Ogórek pokrój w cienkie plasterki. Sos chili wymieszaj z sokiem z limonki.',
      'Podawaj krewetki z ryżem, ogórkiem i sosem chili do maczania.',
    ],
    photo:
      'Golden coconut-crusted shrimp with jasmine rice, thin cucumber slices, lime wedge and a small bowl of sweet chili sauce',
  },
  // ── Kuchnie świata ──
  {
    plan: 'OB-110',
    title: 'Pasta alla Norma z bakłażanem i ricottą',
    description:
      'Sycylijski makaron z podsmażonym bakłażanem w sosie pomidorowym z czosnkiem i bazylią, wykończony łyżką kremowej ricotty. Letni klasyk, w którym bakłażan gra pierwsze skrzypce.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    seasons: ['SUMMER'],
    ingredients: [
      ['makaron penne', 180, 'g'],
      ['bakłażan', 350, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['ser ricotta', 120, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 30, 'ml'],
      ['bazylia', 15, 'g'],
      ['płatki chili', 1, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Bakłażana pokrój w kostkę 2 cm, posyp połową soli i odstaw na 10 minut, potem osusz ręcznikiem.',
      'Smaż bakłażana na oliwie na dużej patelni 8–10 minut, aż będzie złoty i miękki. Przełóż na talerz.',
      'Na tej samej patelni podsmaż posiekany czosnek i płatki chili przez 30 sekund, dodaj pomidory i gotuj 10 minut.',
      'W tym czasie ugotuj penne al dente w wodzie z resztą soli.',
      'Wmieszaj do sosu bakłażana, makaron i połowę porwanej bazylii. Podawaj z łyżką ricotty i resztą bazylii na wierzchu.',
    ],
    photo:
      'Penne in rich tomato sauce with golden fried eggplant cubes, topped with a dollop of white ricotta and fresh basil leaves',
  },
  {
    plan: 'OB-111',
    title: 'Kaszotto z pęczaku z dynią i szałwią',
    description:
      'Kremowe kaszotto z pęczaku z pieczoną dynią, szałwią i masłem, wykończone parmezanem, kozim serem i prażonymi pestkami dyni. Polska odpowiedź na risotto, idealna na jesienny obiad.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'GRAINS',
    seasons: ['AUTUMN'],
    equipment: ['OVEN'],
    ingredients: [
      ['kasza pęczak', 160, 'g'],
      ['dynia', 400, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['bulion warzywny', 250, 'ml'],
      ['masło', 20, 'g'],
      ['szałwia suszona', 2, 'g'],
      ['ser parmezan', 15, 'g'],
      ['ser kozi', 60, 'g'],
      ['pestki dyni', 20, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Dynię pokrój w kostkę, wymieszaj z oliwą i piecz na blasze 25 minut.',
      'Bulion połącz z 550 ml wody i podgrzej. Cebulę i czosnek posiekaj, zeszklij na połowie masła przez 4 minuty.',
      'Wsyp przepłukany pęczak, smaż 1 minutę, a potem wlewaj gorący bulion po chochli, mieszając. Gotuj 30–35 minut, aż kasza będzie miękka i kremowa.',
      'Resztę masła roztop z szałwią na małej patelni przez 1 minutę. Pestki dyni upraż na suchej patelni.',
      'Wmieszaj do kaszotta połowę dyni, masło szałwiowe i starty parmezan. Nałóż, ułóż resztę dyni, pokruszony kozi ser i pestki.',
    ],
    photo:
      'Creamy pearl barley risotto with roasted orange pumpkin cubes, crumbled goat cheese, toasted pumpkin seeds and sage butter',
    vessel: 'bowl',
  },
  {
    plan: 'OB-112',
    title: 'Kurczak cacciatore z polentą',
    description:
      'Kurczak duszony po myśliwsku w sosie z pomidorów, papryki, pieczarek i czarnych oliwek z rozmarynem, podany na miękkiej polencie z oliwą. Sycący włoski obiad, bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'STEW',
    ingredients: [
      ['filet z kurczaka', 400, 'g'],
      ['kasza kukurydziana', 120, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['pieczarka', 150, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwka czarna', 30, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['rozmaryn suszony', 1, 'g'],
      ['oregano', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Kurczaka pokrój na duże kawałki, oprósz szczyptą soli i obsmaż na połowie oliwy w głębokiej patelni 5 minut. Zdejmij.',
      'Na tę samą patelnię wrzuć pokrojoną cebulę, paprykę, pieczarki i czosnek, smaż 6 minut.',
      'Dodaj pomidory, rozmaryn, oregano i oliwki, włóż kurczaka i duś pod przykryciem 20 minut na małym ogniu.',
      'W tym czasie zagotuj 500 ml wody z resztą soli, wsypuj kaszę kukurydzianą cienkim strumieniem, mieszając, i gotuj 5–8 minut, aż zgęstnieje. Wmieszaj resztę oliwy.',
      'Nałóż polentę na talerze, obok kurczaka z sosem i posyp posiekaną natką pietruszki.',
    ],
    photo:
      'Braised chicken pieces in chunky tomato sauce with red pepper, mushrooms and black olives, served over soft yellow polenta with parsley',
  },
];
