/**
 * Katalog 1000 — część OB-e: obiady OB-113 … OB-140 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'OB-113',
    title: 'Saltimbocca z indyka z szałwią i szynką',
    description:
      'Cienkie sznycle z indyka owinięte szynką dojrzewającą z szałwią, smażone na maśle i podlane cytrynowym sosem. Podane z ziemniakami i rukolą — szybki, bardzo białkowy obiad po rzymsku.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'MAIN',
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['szynka dojrzewająca', 40, 'g'],
      ['szałwia suszona', 2, 'g'],
      ['mąka pszenna', 10, 'g'],
      ['masło', 15, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['bulion drobiowy', 100, 'ml'],
      ['cytryna', 30, 'g'],
      ['ziemniak', 400, 'g'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz ziemniaki, pokrój na ćwiartki i gotuj w osolonej wodzie 20 minut do miękkości.',
      'Filet z indyka przekrój na 4 cienkie plastry i rozbij tłuczkiem przez folię na grubość ok. 5 mm. Oprósz pieprzem.',
      'Na każdy plaster połóż szczyptę szałwii i plaster szynki dojrzewającej, dociśnij dłonią, a spód lekko oprósz mąką.',
      'Rozgrzej na patelni oliwę z połową masła. Smaż mięso najpierw stroną z szynką 2 minuty, potem odwróć i smaż jeszcze 2–3 minuty. Przełóż na talerz.',
      'Na patelnię wlej bulion i sok z cytryny, zeskrob przysmażone resztki i gotuj 2 minuty. Zdejmij z ognia i wmieszaj resztę masła.',
      'Podawaj saltimboccę polaną sosem, z ziemniakami i garścią rukoli.',
    ],
    photo:
      'Two thin golden turkey escalopes topped with crisp cured ham and sage in a glossy lemon butter sauce, with boiled potato quarters and fresh rocket on the side',
  },
  {
    plan: 'OB-114',
    title: 'Ribollita — toskańska zupa z fasolą i jarmużem',
    description:
      'Gęsta toskańska zupa z białej fasoli, jarmużu i warzyw, zagęszczona kawałkami chleba i skropiona oliwą. Rozgrzewająca, sycąca i w pełni roślinna — na drugi dzień smakuje jeszcze lepiej.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SOUP',
    seasons: ['WINTER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['fasola biała z puszki', 320, 'g'],
      ['jarmuż', 200, 'g'],
      ['marchew', 100, 'g'],
      ['seler naciowy', 60, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 250, 'ml'],
      ['chleb', 60, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['tymianek suszony', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cebulę, marchew i seler naciowy pokrój w drobną kostkę, czosnek posiekaj.',
      'W garnku rozgrzej połowę oliwy i podsmaż warzywa z tymiankiem przez 8 minut, aż zmiękną.',
      'Dodaj passatę, odsączoną fasolę i 700 ml wody. Zagotuj i gotuj pod przykryciem 15 minut.',
      'Jarmuż oderwij od twardych łodyg, porwij na kawałki i wrzuć do zupy. Gotuj 10 minut.',
      'Chleb porwij na kawałki, wrzuć do garnka i gotuj jeszcze 5 minut, mieszając, aż zupa zgęstnieje. Dopraw pieprzem.',
      'Nalej do misek i skrop resztą oliwy tuż przed podaniem.',
    ],
    photo:
      'Thick rustic Tuscan soup with white beans, dark green kale, carrot pieces and soaked bread chunks, drizzled with golden olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'OB-115',
    title: 'Makaron amatriciana z boczkiem',
    description:
      'Klasyczny rzymski makaron w sosie pomidorowym z chrupiącym boczkiem, cebulą i szczyptą chili, posypany tartym serem. Prosty obiad z kilku składników, gotowy w niecałe pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'PASTA',
    ingredients: [
      ['makaron spaghetti', 200, 'g'],
      ['boczek', 80, 'g'],
      ['pomidor krojony z puszki', 300, 'g'],
      ['cebula', 60, 'g'],
      ['ser parmezan', 25, 'g'],
      ['płatki chili', 1, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zagotuj dużą ilość osolonej wody na makaron.',
      'Boczek pokrój w paski i smaż na oliwie na średnim ogniu 5 minut, aż się wytopi i zrumieni.',
      'Dodaj drobno pokrojoną cebulę i płatki chili, smaż 3 minuty. Wlej pomidory i gotuj sos 10 minut.',
      'W tym czasie ugotuj spaghetti al dente według opakowania, odlej, zachowując pół szklanki wody z gotowania.',
      'Przełóż makaron do sosu, dodaj trochę wody z gotowania i mieszaj na ogniu 1 minutę.',
      'Podawaj posypane tartym parmezanem i świeżo mielonym pieprzem.',
    ],
    photo:
      'Spaghetti coated in rich tomato and onion sauce with crispy bacon strips and a few red chili flakes, topped with grated parmesan and cracked black pepper',
    vessel: 'bowl',
  },
  {
    plan: 'OB-116',
    title: 'Musaka z bakłażanem i mięsem mielonym',
    description:
      'Grecka zapiekanka z warstw pieczonego bakłażana i mięsnego sosu pomidorowego z nutą cynamonu, pod złotym beszamelem. Syte, aromatyczne danie na niedzielny obiad.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['bakłażan', 500, 'g'],
      ['wołowina mielona', 300, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 300, 'g'],
      ['cynamon', 1, 'g'],
      ['oregano', 1, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['masło', 20, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['mleko', 300, 'ml'],
      ['jajko', 1, 'szt'],
      ['ser parmezan', 20, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Bakłażana pokrój w plastry grubości 1 cm, ułóż na blasze z papierem, posmaruj połową oliwy i piecz 20 minut.',
      'Na reszcie oliwy podsmaż posiekaną cebulę i czosnek, dodaj mięso i smaż 8 minut, rozbijając grudki.',
      'Wlej pomidory, dodaj cynamon, oregano i sól, duś sos 15 minut, aż zgęstnieje.',
      'Beszamel: roztop masło, wmieszaj mąkę, a potem stopniowo wlewaj mleko, cały czas mieszając, aż sos zgęstnieje. Zdejmij z ognia, dodaj gałkę muszkatołową, połowę parmezanu i roztrzepane jajko.',
      'W naczyniu żaroodpornym układaj warstwy: bakłażan, sos mięsny, bakłażan, sos mięsny. Wierzch zalej beszamelem i posyp resztą parmezanu.',
      'Zmniejsz temperaturę do 180°C i piecz musakę 35 minut, aż wierzch się zrumieni. Odstaw na 10 minut przed krojeniem.',
    ],
    photo:
      'Square slice of moussaka showing layers of roasted eggplant and cinnamon-scented meat sauce under a thick golden browned bechamel top',
  },
  {
    plan: 'OB-117',
    title: 'Pastitsio — grecka zapiekanka makaronowa',
    description:
      'Grecka zapiekanka z rurek makaronu przełożonych wołowym ragù z cynamonem i zapieczonych pod grubą warstwą beszamelu. Kroi się ją jak ciasto — idealna na rodzinny obiad.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 75,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['makaron penne', 140, 'g'],
      ['wołowina mielona', 220, 'g'],
      ['cebula', 80, 'g'],
      ['passata pomidorowa', 200, 'ml'],
      ['cynamon', 1, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['masło', 20, 'g'],
      ['mąka pszenna', 20, 'g'],
      ['mleko', 300, 'ml'],
      ['jajko', 1, 'szt'],
      ['ser parmezan', 30, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ugotuj penne 2 minuty krócej niż podaje opakowanie i odcedź. Rozgrzej piekarnik do 180°C.',
      'Na oliwie podsmaż posiekaną cebulę, dodaj mięso i smaż 8 minut. Wlej passatę, dodaj cynamon i sól, duś 15 minut.',
      'Beszamel: roztop masło, wmieszaj mąkę, stopniowo wlewaj mleko i gotuj, mieszając, aż zgęstnieje. Zdejmij z ognia, dodaj gałkę, połowę parmezanu i roztrzepane jajko.',
      'Połowę makaronu wymieszaj z 3 łyżkami beszamelu i wyłóż na dno małego naczynia żaroodpornego. Rozprowadź na nim sos mięsny, przykryj resztą makaronu.',
      'Zalej wierzch pozostałym beszamelem i posyp resztą parmezanu.',
      'Piecz 35 minut, aż wierzch będzie złoty. Odstaw na 10 minut, żeby zapiekanka dała się ładnie pokroić.',
    ],
    photo:
      'Neat square of Greek pasta bake with visible layers of tube pasta and meat ragu under a thick golden bechamel crust',
  },
  {
    plan: 'OB-118',
    title: 'Gemista — pomidory i papryki faszerowane ryżem',
    description:
      'Greckie pomidory i papryki faszerowane ryżem z ziołami, miętą i ciecierzycą, pieczone w oliwie razem z ziemniakami. Letni, roślinny obiad, który sam robi się w piekarniku.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'BAKE',
    seasons: ['SUMMER'],
    equipment: ['OVEN'],
    ingredients: [
      ['pomidor', 600, 'g'],
      ['papryka czerwona', 320, 'g'],
      ['ryż biały', 120, 'g'],
      ['ciecierzyca z puszki', 150, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['natka pietruszki', 15, 'g'],
      ['mięta', 5, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['oregano', 1, 'g'],
      ['oliwa z oliwek', 40, 'ml'],
      ['ziemniak', 300, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 190°C. Pomidorom odetnij wierzchy i wydrąż miąższ łyżeczką, paprykom odetnij czapki i usuń gniazda nasienne. Miąższ pomidorów posiekaj.',
      'Na połowie oliwy zeszklij posiekaną cebulę i czosnek, dodaj miąższ pomidorów, koncentrat, oregano, sól i pieprz, gotuj 5 minut.',
      'Wsyp surowy ryż i odsączoną ciecierzycę, mieszaj 2 minuty, zdejmij z ognia i dodaj posiekaną natkę oraz miętę.',
      'Napełnij warzywa farszem do trzech czwartych wysokości i przykryj odciętymi czapkami. Ustaw ciasno w naczyniu żaroodpornym.',
      'Ziemniaki obierz, pokrój w łódki i poukładaj między warzywami. Wlej 150 ml wody, skrop wszystko resztą oliwy.',
      'Piecz pod folią 40 minut, potem bez folii 25–30 minut, aż ryż będzie miękki, a skórki warzyw lekko przypieczone.',
    ],
    photo:
      'Two baked stuffed tomatoes and one stuffed red pepper with lightly charred skins and lids, herbed rice and chickpea filling, roasted potato wedges glistening with olive oil around them',
  },
  {
    plan: 'OB-119',
    title: 'Butter chicken z ryżem basmati',
    description:
      'Kawałki kurczaka marynowane w jogurcie i przyprawach, duszone w aksamitnym sosie pomidorowo-maślanym ze śmietanką. Łagodne indyjskie curry, które smakuje dorosłym i dzieciom, podane z ryżem basmati.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['garam masala', 4, 'g'],
      ['kurkuma', 1, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 3, 'szt'],
      ['masło', 25, 'g'],
      ['cebula', 100, 'g'],
      ['passata pomidorowa', 250, 'ml'],
      ['śmietanka 30', 60, 'ml'],
      ['ryż basmati', 140, 'g'],
      ['kolendra', 5, 'g'],
      ['sól', 1.5, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w kostkę i wymieszaj z jogurtem, połową garam masali, kurkumą, ostrą papryką i solą. Odstaw na 20 minut.',
      'Ugotuj ryż basmati według opakowania.',
      'Na patelni roztop połowę masła i obsmaż kurczaka z marynatą na dużym ogniu 5 minut. Przełóż na talerz.',
      'Na reszcie masła zeszklij drobno pokrojoną cebulę z tartym imbirem i czosnkiem przez 5 minut. Dodaj resztę garam masali i passatę, gotuj 8 minut.',
      'Wlej śmietankę, włóż kurczaka z powrotem i duś 8 minut, aż mięso będzie miękkie, a sos gęsty.',
      'Podawaj z ryżem basmati, posypane posiekaną kolendrą.',
    ],
    photo:
      'Tender chicken pieces in creamy orange tomato butter sauce next to fluffy white basmati rice, garnished with fresh coriander leaves',
    vessel: 'bowl',
  },
  {
    plan: 'OB-120',
    title: 'Aloo gobi — ziemniaki z kalafiorem po indyjsku',
    description:
      'Ziemniaki i różyczki kalafiora smażone z kuminem, kurkumą, imbirem i pomidorem, z dodatkiem zielonego groszku. Rozgrzewające, roślinne danie z jednej patelni pachnące indyjskimi przyprawami.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'POTATOES',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['kalafior', 500, 'g'],
      ['groszek mrożony', 150, 'g'],
      ['cebula', 100, 'g'],
      ['pomidor', 200, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 10, 'g'],
      ['kurkuma', 2, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['garam masala', 3, 'g'],
      ['olej rzepakowy', 30, 'ml'],
      ['kolendra', 10, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i pokrój w kostkę 2 cm, kalafior podziel na małe różyczki.',
      'W dużej patelni rozgrzej olej i praż kmin rzymski 30 sekund. Dodaj posiekaną cebulę i smaż 5 minut.',
      'Dodaj starty imbir, czosnek i kurkumę, a po minucie ziemniaki. Smaż 5 minut, mieszając.',
      'Dołóż kalafior, pokrojone pomidory i sól, wlej 100 ml wody. Przykryj i duś na małym ogniu 15 minut.',
      'Wsyp groszek i garam masalę, duś bez przykrycia jeszcze 5 minut, aż warzywa będą miękkie, a płyn odparuje.',
      'Podawaj posypane posiekaną kolendrą.',
    ],
    photo:
      'Golden turmeric-coated potato cubes and cauliflower florets with green peas and tomato, sprinkled with fresh coriander',
    vessel: 'bowl',
  },
  {
    plan: 'OB-121',
    title: 'Chana masala z ryżem',
    description:
      'Ciecierzyca z czerwoną soczewicą i przypieczonym tofu w roli paneeru, duszona w pikantnym sosie pomidorowym z imbirem i garam masalą. Podana z ryżem i sojowym jogurtem z miętą — sycące roślinne curry pełne białka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'STEW',
    features: ['LUNCHBOX'],
    ingredients: [
      ['ciecierzyca z puszki', 320, 'g'],
      ['soczewica czerwona', 60, 'g'],
      ['tofu', 200, 'g'],
      ['ryż basmati', 80, 'g'],
      ['cebula', 100, 'g'],
      ['pomidor', 300, 'g'],
      ['czosnek', 3, 'szt'],
      ['imbir', 10, 'g'],
      ['garam masala', 4, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['kurkuma', 1, 'g'],
      ['papryka ostra mielona', 1, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['jogurt sojowy', 150, 'g'],
      ['mięta', 5, 'g'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Ugotuj ryż basmati według opakowania. Soczewicę przepłucz na sitku, tofu osusz i pokrój w kostkę 2 cm.',
      'Na patelni rozgrzej 5 ml oleju i przypiecz tofu ze wszystkich stron przez 6 minut. Odłóż.',
      'W garnku na reszcie oleju podsmaż kmin rzymski przez 30 sekund, dodaj posiekaną cebulę i smaż 6 minut na złoto.',
      'Dodaj starty imbir, czosnek, kurkumę, ostrą paprykę i garam masalę, smaż 1 minutę. Wrzuć pokrojone pomidory i gotuj 5 minut.',
      'Dodaj odsączoną ciecierzycę, soczewicę i 300 ml wody. Duś pod przykryciem 15 minut, aż soczewica się rozpadnie, a sos zgęstnieje. Część ciecierzycy rozgnieć łyżką, a na koniec wmieszaj tofu.',
      'Jogurt sojowy wymieszaj z posiekaną miętą.',
      'Podawaj curry z ryżem i jogurtem, posypane kolendrą.',
    ],
    photo:
      'Thick spiced chickpea curry with golden seared tofu cubes in rich tomato sauce beside basmati rice, a dollop of mint yogurt and coriander',
    vessel: 'bowl',
  },
  {
    plan: 'OB-122',
    title: 'Kurczak z bazylią i chili po tajsku z ryżem i jajkiem',
    description:
      'Tajski street food: kurczak smażony z czosnkiem, chili i bazylią w sosie sojowo-rybnym, podany z ryżem jaśminowym i jajkiem sadzonym z chrupiącym brzegiem. Ostry, aromatyczny i gotowy w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'MAIN',
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['czosnek', 4, 'szt'],
      ['papryczka chili', 15, 'g'],
      ['fasolka szparagowa', 100, 'g'],
      ['bazylia', 20, 'g'],
      ['sos sojowy', 10, 'ml'],
      ['sos rybny', 5, 'ml'],
      ['cukier brązowy', 5, 'g'],
      ['olej rzepakowy', 25, 'ml'],
      ['jajko', 2, 'szt'],
      ['ryż jaśminowy', 140, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy według opakowania.',
      'Kurczaka posiekaj nożem na drobne kawałki. Czosnek i chili utłucz w moździerzu albo drobno posiekaj. Fasolkę pokrój na 2-centymetrowe kawałki.',
      'Wymieszaj sos sojowy, sos rybny i cukier z 2 łyżkami wody.',
      'W woku rozgrzej 15 ml oleju, smaż czosnek z chili 30 sekund, dodaj kurczaka i smaż na dużym ogniu 4 minuty.',
      'Dodaj fasolkę i sos, smaż 2 minuty. Zdejmij z ognia i wmieszaj liście bazylii.',
      'Na osobnej patelni rozgrzej resztę oleju i usmaż 2 jajka sadzone z chrupiącym brzegiem. Podawaj kurczaka z ryżem i jajkiem na wierzchu.',
    ],
    photo:
      'Stir-fried minced chicken with basil leaves, red chili and green beans next to jasmine rice topped with a crispy-edged fried egg',
  },
  {
    plan: 'OB-123',
    title: 'Zielone curry z kurczakiem',
    description:
      'Kurczak i chrupiące warzywa duszone w mleku kokosowym z zieloną pastą curry, limonką i bazylią. Aromatyczne tajskie curry bez nabiału, podane z ryżem jaśminowym.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'STEW',
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['pasta curry', 30, 'g'],
      ['mleko kokosowe z puszki', 250, 'ml'],
      ['cukinia', 150, 'g'],
      ['fasolka szparagowa', 120, 'g'],
      ['bazylia', 10, 'g'],
      ['sos rybny', 5, 'ml'],
      ['limonka', 30, 'g'],
      ['cukier brązowy', 5, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ryż jaśminowy', 140, 'g'],
    ],
    steps: [
      'Ugotuj ryż jaśminowy według opakowania.',
      'Kurczaka pokrój w cienkie paski, cukinię w półplasterki, fasolkę na 3-centymetrowe kawałki.',
      'W garnku rozgrzej olej i smaż zieloną pastę curry z 3 łyżkami mleka kokosowego przez 2 minuty, aż zacznie pachnieć.',
      'Dodaj kurczaka i smaż 3 minuty, potem wlej resztę mleka kokosowego i 100 ml wody. Zagotuj.',
      'Wrzuć fasolkę i cukinię, gotuj 6–7 minut, aż warzywa będą miękkie, ale jędrne. Dopraw sosem rybnym, cukrem i sokiem z limonki.',
      'Zdejmij z ognia, wmieszaj liście bazylii i podawaj z ryżem.',
    ],
    photo:
      'Pale green coconut curry with chicken strips, zucchini and green beans, basil leaves on top, with jasmine rice alongside',
    vessel: 'bowl',
  },
  {
    plan: 'OB-124',
    title: 'Zupa kokosowa z kurczakiem i czerwoną pastą curry',
    description:
      'Lekka tajska zupa na mleku kokosowym z czerwoną pastą curry, kurczakiem, pieczarkami i papryką, doprawiona limonką i imbirem. Rozgrzewa, syci i nie obciąża.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'SOUP',
    ingredients: [
      ['filet z kurczaka', 250, 'g'],
      ['mleko kokosowe z puszki', 200, 'ml'],
      ['bulion drobiowy', 200, 'ml'],
      ['pasta curry', 20, 'g'],
      ['pieczarka', 150, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['imbir', 10, 'g'],
      ['limonka', 30, 'g'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w cienkie paski, pieczarki w plasterki, paprykę w paski, imbir w cienkie słupki.',
      'W garnku podgrzej 3 łyżki mleka kokosowego i smaż w nim czerwoną pastę curry z imbirem przez 2 minuty.',
      'Wlej bulion, resztę mleka kokosowego i 300 ml wody, zagotuj.',
      'Wrzuć kurczaka i pieczarki, gotuj na małym ogniu 8 minut. Dodaj paprykę i gotuj jeszcze 3 minuty.',
      'Dopraw sokiem z limonki i podawaj posypane posiekaną kolendrą.',
    ],
    photo:
      'Orange-tinted coconut curry soup with chicken strips, sliced mushrooms and red pepper, topped with chopped coriander',
    vessel: 'bowl',
  },
  {
    plan: 'OB-125',
    title: 'Burrito z wołowiną i ryżem',
    description:
      'Duże pszenne tortille zawinięte z wołowiną z kuminem i wędzoną papryką, ryżem, czarną fasolą, salsą i serem. Sycący meksykański obiad, który łatwo zabrać ze sobą.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['wołowina mielona', 220, 'g'],
      ['ryż biały', 80, 'g'],
      ['fasola czarna z puszki', 120, 'g'],
      ['cebula', 60, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['salsa pomidorowa', 40, 'g'],
      ['ser cheddar', 30, 'g'],
      ['śmietana 18', 40, 'g'],
      ['olej rzepakowy', 10, 'ml'],
    ],
    steps: [
      'Ugotuj ryż według opakowania.',
      'Na oleju podsmaż posiekaną cebulę i pokrojoną w kostkę paprykę przez 4 minuty.',
      'Dodaj wołowinę, kmin i wędzoną paprykę, smaż 8 minut, rozbijając mięso. Wmieszaj odsączoną fasolę i podgrzej 2 minuty.',
      'Tortille podgrzej chwilę na suchej patelni, żeby zmiękły.',
      'Na środek każdej tortilli nałóż ryż, farsz mięsny, salsę, łyżkę śmietany i starty cheddar.',
      'Zawiń boki do środka, a potem zroluj ciasno. Przyrumień burrito łączeniem w dół na suchej patelni 1–2 minuty z każdej strony.',
    ],
    photo:
      'One large golden wheat tortilla burrito cut in half, showing spiced ground beef, rice, black beans, melted cheddar, salsa and sour cream inside',
    vessel: 'board',
  },
  {
    plan: 'OB-126',
    title: 'Tinga de pollo w tortillach',
    description:
      'Szarpany kurczak duszony w wędzonym sosie pomidorowym z jalapeño, podany w kukurydzianych tortillach z sałatą, śmietaną i limonką. Meksykańska klasyka pełna białka, ostra w sam raz.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    equipment: ['BLENDER'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 300, 'g'],
      ['papryczki jalapeño', 20, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['oregano', 1, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['tortilla kukurydziana', 6, 'szt'],
      ['śmietana 12', 40, 'g'],
      ['sałata lodowa', 60, 'g'],
      ['kolendra', 5, 'g'],
      ['limonka', 20, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Włóż filet do garnka, zalej wodą, zagotuj i gotuj na małym ogniu 15 minut. Wyjmij i rozszarp dwoma widelcami.',
      'Na oleju zeszklij cebulę pokrojoną w piórka z posiekanym czosnkiem przez 5 minut.',
      'Dodaj pomidory, posiekane jalapeño, wędzoną paprykę, oregano, kmin i sól. Gotuj 5 minut, a potem zmiksuj sos blenderem ręcznym na gładko.',
      'Włóż rozszarpanego kurczaka do sosu i duś 8 minut, aż sos zgęstnieje i oblepi mięso.',
      'Tortille podgrzej na suchej patelni po 30 sekund z każdej strony.',
      'Nakładaj tingę na tortille, dodaj poszatkowaną sałatę, łyżkę śmietany i kolendrę. Podawaj z ćwiartkami limonki.',
    ],
    photo:
      'Soft corn tortillas filled with shredded chicken in smoky red tomato sauce, shredded lettuce, a dollop of sour cream, coriander and lime wedges',
    vessel: 'board',
  },
  {
    plan: 'OB-127',
    title: 'Carnitas z wieprzowiny z tortillami',
    description:
      'Łopatka wieprzowa powoli duszona z pomarańczą, czosnkiem i kuminem, rozszarpana i przypieczona na chrupko, podana w tortillach z pomidorową salsą. Mięso spokojnie postoi w lodówce do 4 dni.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 180,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['łopatka wieprzowa', 400, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['pomarańcza', 150, 'g'],
      ['limonka', 30, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['oregano', 1, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 3, 'g'],
      ['tortilla kukurydziana', 6, 'szt'],
      ['pomidor', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Łopatkę pokrój w kostkę 4 cm i natrzyj solą, kminem, oregano i wędzoną papryką.',
      'W ciężkim garnku rozgrzej olej i obsmaż mięso ze wszystkich stron przez 6 minut.',
      'Dodaj cebulę w ćwiartkach, zgnieciony czosnek, sok z pomarańczy i 250 ml wody. Przykryj i duś na bardzo małym ogniu 2 godziny 15 minut, aż mięso będzie się rozpadać.',
      'Rozgrzej piekarnik do 220°C z grzałką górną. Mięso rozszarp widelcami, rozłóż na blasze, polej odrobiną wywaru i piecz 10–12 minut, aż brzegi się przypieką.',
      'Salsa: pomidora i czerwoną cebulę pokrój w drobną kostkę, wymieszaj z posiekaną kolendrą i sokiem z limonki.',
      'Podgrzej tortille na suchej patelni i nakładaj na nie chrupiące carnitas z salsą.',
    ],
    photo:
      'Corn tortillas piled with crispy-edged shredded pork, fresh diced tomato and red onion salsa and coriander leaves',
    vessel: 'board',
  },
  {
    plan: 'OB-128',
    title: 'Kurczak BBQ z pieczoną kukurydzą i ziemniakami',
    description:
      'Filety z kurczaka glazurowane sosem barbecue, upieczone na jednej blasze z kolbami kukurydzy i wędzonymi ziemniakami. Amerykański obiad bez grilla — kolorowy, sycący i bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['sos barbecue', 60, 'g'],
      ['kukurydza', 300, 'g'],
      ['ziemniak', 400, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['papryka wędzona mielona', 2, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['masło', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 210°C. Ziemniaki umyj i pokrój w łódki, wymieszaj z połową oleju, wędzoną papryką, czosnkiem granulowanym i solą.',
      'Rozłóż ziemniaki na blasze z papierem i piecz 15 minut.',
      'Kolby kukurydzy przekrój na pół i posmaruj resztą oleju. Filety natrzyj połową sosu barbecue.',
      'Połóż kurczaka i kukurydzę na blachę obok ziemniaków i piecz 20 minut.',
      'Posmaruj kurczaka resztą sosu barbecue i piecz jeszcze 5 minut, aż glazura się skarmelizuje.',
      'Kukurydzę posmaruj masłem i podawaj z pokrojonym kurczakiem i ziemniakami.',
    ],
    photo:
      'Sliced sticky glazed barbecue chicken breast with a buttery roasted half corn on the cob and smoky paprika potato wedges',
  },
  {
    plan: 'OB-129',
    title: 'Meatloaf — pieczeń z mielonego z puree',
    description:
      'Amerykańska pieczeń z mielonego mięsa z cebulą i ziołami, pieczona pod słodko-pikantną glazurą z ketchupu i musztardy. Podana z maślanym puree ziemniaczanym — domowe comfort food.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 75,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['wieprzowina i wołowina mielona', 300, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 2, 'szt'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 30, 'g'],
      ['mleko', 110, 'ml'],
      ['ketchup', 30, 'g'],
      ['musztarda', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['sól', 1.5, 'g'],
      ['ziemniak', 500, 'g'],
      ['masło', 15, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 190°C. Cebulę i czosnek drobno posiekaj.',
      'Bułkę tartą namocz w 30 ml mleka. Wymieszaj mięso z cebulą, czosnkiem, jajkiem, namoczoną bułką, papryką, tymiankiem i 1 g soli.',
      'Uformuj zwarty bochenek i ułóż go w małej keksówce albo na blasze z papierem.',
      'Wymieszaj ketchup z musztardą i posmaruj wierzch pieczeni. Piecz 45 minut.',
      'W tym czasie ugotuj obrane ziemniaki w wodzie z resztą soli przez 20 minut. Odcedź i utłucz z masłem i ciepłym pozostałym mlekiem na gładkie puree.',
      'Odstaw pieczeń na 5 minut, pokrój w grube plastry i podawaj z puree.',
    ],
    photo:
      'Thick slices of glazed meatloaf with a shiny red ketchup crust next to a mound of creamy buttery mashed potatoes',
  },
  {
    plan: 'OB-130',
    title: 'Paella warzywna z ciecierzycą',
    description:
      'Hiszpańska paella z jednej patelni: ryż z wędzoną papryką i kurkumą, papryką, fasolką, groszkiem i ciecierzycą, podana z cytryną. Kolorowe, roślinne danie, które zna każdy, kto był w Walencji.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'GRAINS',
    ingredients: [
      ['ryż arborio', 150, 'g'],
      ['ciecierzyca z puszki', 240, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['fasolka szparagowa', 100, 'g'],
      ['groszek mrożony', 80, 'g'],
      ['pomidor', 150, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 3, 'szt'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kurkuma', 1, 'g'],
      ['bulion warzywny', 250, 'ml'],
      ['oliwa z oliwek', 25, 'ml'],
      ['cytryna', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Paprykę pokrój w paski, fasolkę na kawałki, cebulę i czosnek posiekaj, pomidora zetrzyj na tarce, wyrzucając skórkę.',
      'Na szerokiej patelni rozgrzej oliwę i smaż paprykę z fasolką 5 minut. Dodaj cebulę i czosnek, smaż 3 minuty.',
      'Wmieszaj starty pomidor, wędzoną paprykę i kurkumę, smaż 2 minuty. Wsyp ryż i mieszaj minutę, aż ziarna pokryją się sosem.',
      'Wlej bulion i 250 ml gorącej wody, dodaj odsączoną ciecierzycę i rozprowadź równo. Gotuj bez mieszania 15 minut na średnim ogniu.',
      'Rozsyp groszek na wierzchu i gotuj jeszcze 5 minut, aż ryż wchłonie płyn, a na dnie zacznie się przypiekać.',
      'Zdejmij z ognia, przykryj ściereczką na 5 minut. Podawaj z natką i ćwiartkami cytryny.',
    ],
    photo:
      'A portion of golden turmeric-tinted paella rice with red pepper strips, green beans, peas and chickpeas, topped with chopped parsley and a lemon wedge',
  },
  {
    plan: 'OB-131',
    title: 'Lasagne ze szpinakiem i ricottą',
    description:
      'Warstwy makaronu przełożone kremowym farszem ze szpinaku, ricotty i czosnku, sosem pomidorowym i roztopioną mozzarellą. Bezmięsna lasagne, która zadowoli każdego przy stole.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 70,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['makaron lasagne', 120, 'g'],
      ['szpinak mrożony', 400, 'g'],
      ['ser ricotta', 200, 'g'],
      ['mozzarella', 100, 'g'],
      ['ser parmezan', 20, 'g'],
      ['passata pomidorowa', 400, 'ml'],
      ['cebula', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['jajko', 1, 'szt'],
      ['bazylia suszona', 1, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 190°C. Szpinak rozmroź i mocno odciśnij z wody.',
      'Na oliwie zeszklij posiekaną cebulę, dodaj połowę czosnku i passatę z bazylią, gotuj sos 10 minut.',
      'Szpinak wymieszaj z ricottą, jajkiem, resztą przeciśniętego czosnku, gałką muszkatołową i połową parmezanu.',
      'Na dno małego naczynia żaroodpornego wlej trochę sosu, połóż płaty makaronu, rozsmaruj farsz szpinakowy i polej sosem. Powtórz warstwy, kończąc makaronem i sosem.',
      'Wierzch posyp porwaną mozzarellą i resztą parmezanu. Przykryj folią i piecz 25 minut, potem bez folii 15 minut, aż ser się zrumieni.',
      'Odstaw na 10 minut przed krojeniem.',
    ],
    photo:
      'Square slice of spinach and ricotta lasagna with visible green spinach ricotta layers, red tomato sauce and a bubbling browned mozzarella top',
  },
  {
    plan: 'OB-132',
    title: 'Arroz con pollo — ryż z kurczakiem po hiszpańsku',
    description:
      'Kurczak i ryż gotowane razem w jednym garnku z papryką, pomidorem, wędzoną papryką i groszkiem. Domowe hiszpańskie danie jednogarnkowe, sycące i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'GRAINS',
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['ryż biały', 130, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cebula', 80, 'g'],
      ['czosnek', 3, 'szt'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['groszek mrożony', 80, 'g'],
      ['bulion drobiowy', 250, 'ml'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['kurkuma', 1, 'g'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w duże kawałki i natrzyj połową wędzonej papryki.',
      'W szerokim garnku rozgrzej oliwę i obsmaż kurczaka po 2 minuty z każdej strony. Wyjmij.',
      'Na tym samym tłuszczu smaż pokrojoną paprykę, cebulę i czosnek przez 5 minut. Dodaj resztę wędzonej papryki, kurkumę i pomidory, gotuj 3 minuty.',
      'Wsyp ryż, wymieszaj, wlej bulion i 100 ml wody. Połóż kurczaka na wierzchu, przykryj i gotuj na małym ogniu 15 minut.',
      'Rozsyp groszek, przykryj i gotuj jeszcze 5 minut, aż ryż wchłonie płyn. Odstaw na 5 minut.',
      'Podawaj posypane posiekaną natką pietruszki.',
    ],
    photo:
      'Golden-orange rice cooked with seared chicken pieces, red pepper, green peas and tomato, sprinkled with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'OB-133',
    title: 'Kurczak satay z sosem orzechowym i ryżem',
    description:
      'Paski kurczaka w marynacie z kurkumą i curry, przypieczone na patelni grillowej i podane z kremowym sosem z masła orzechowego i mleka kokosowego. Do tego ryż jaśminowy i chłodzący ogórek.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'MAIN',
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['sos sojowy', 15, 'ml'],
      ['curry', 2, 'g'],
      ['kurkuma', 1, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['masło orzechowe', 40, 'g'],
      ['mleko kokosowe z puszki', 80, 'ml'],
      ['limonka', 20, 'g'],
      ['cukier brązowy', 5, 'g'],
      ['płatki chili', 1, 'g'],
      ['ryż jaśminowy', 130, 'g'],
      ['ogórek', 150, 'g'],
    ],
    steps: [
      'Kurczaka pokrój w długie paski. Wymieszaj z połową sosu sojowego, curry, kurkumą, przeciśniętym czosnkiem i olejem. Odstaw na 15 minut i nadziej na patyczki do szaszłyków.',
      'Ugotuj ryż jaśminowy według opakowania.',
      'Sos: w rondelku podgrzej masło orzechowe z mlekiem kokosowym, resztą sosu sojowego, cukrem, płatkami chili i sokiem z limonki. Mieszaj 2 minuty, aż będzie gładki; w razie potrzeby rozrzedź łyżką wody.',
      'Rozgrzej patelnię grillową i smaż szaszłyki po 3–4 minuty z każdej strony, aż będą przypieczone i soczyste.',
      'Ogórek pokrój w cienkie plasterki.',
      'Podawaj szaszłyki z ryżem, ogórkiem i sosem orzechowym do maczania.',
    ],
    photo:
      'Chargrilled yellow chicken satay skewers with jasmine rice, thin cucumber slices and a small pool of creamy peanut sauce for dipping',
  },
  {
    plan: 'OB-134',
    title: 'Giouvetsi — wołowina z makaronem orzo w pomidorach',
    description:
      'Wołowina duszona w pomidorach z cynamonem i liściem laurowym, zapieczona z makaronem orzo i posypana fetą. Greckie danie niedzielne, w którym makaron wchłania cały smak sosu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 120,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'PASTA',
    equipment: ['OVEN'],
    ingredients: [
      ['wołowina', 300, 'g'],
      ['makaron orzo', 140, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['cynamon', 1, 'g'],
      ['liść laurowy', 1, 'g'],
      ['oregano', 1, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ser feta', 40, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wołowinę pokrój w kostkę 3 cm. W naczyniu żaroodpornym nadającym się na palnik (albo w garnku) rozgrzej oliwę i obsmaż mięso partiami przez 5 minut.',
      'Dodaj posiekaną cebulę i czosnek, smaż 3 minuty. Wmieszaj koncentrat, pomidory, cynamon, liść laurowy, oregano, sól i pieprz, wlej 300 ml wody.',
      'Przykryj i duś na małym ogniu 1 godzinę 15 minut, aż mięso zmięknie.',
      'Rozgrzej piekarnik do 190°C. Przełóż mięso z sosem do naczynia żaroodpornego, dolej 300 ml wrzącej wody i wsyp orzo, mieszając.',
      'Piecz bez przykrycia 25 minut, mieszając w połowie, aż makaron wchłonie sos i będzie miękki.',
      'Wyjmij liść laurowy i podawaj posypane pokruszoną fetą.',
    ],
    photo:
      'Rice-shaped orzo pasta baked in rich red tomato sauce with tender beef chunks, crumbled white feta and a pinch of oregano on top',
    vessel: 'bowl',
  },
  {
    plan: 'OB-135',
    title: 'Pollo asado — pieczony kurczak po meksykańsku z salsą',
    description:
      'Udka kurczaka marynowane w soku z pomarańczy i limonki z czosnkiem, kuminem i wędzoną papryką, upieczone na chrupko. Podane z czarną fasolą i świeżą salsą pomidorową z kolendrą.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['udko z kurczaka', 500, 'g'],
      ['pomarańcza', 150, 'g'],
      ['limonka', 40, 'g'],
      ['czosnek', 3, 'szt'],
      ['kmin rzymski', 2, 'g'],
      ['oregano', 1, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sól', 1.5, 'g'],
      ['fasola czarna z puszki', 200, 'g'],
      ['pomidor', 250, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['papryczka chili', 10, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Wymieszaj sok z pomarańczy, połowę soku z limonki, przeciśnięty czosnek, kmin, oregano, wędzoną paprykę, olej i sól. Natrzyj udka marynatą i odstaw na 30 minut.',
      'Rozgrzej piekarnik do 200°C. Ułóż udka skórą do góry w naczyniu żaroodpornym i piecz 40–45 minut, aż skórka będzie chrupiąca, a mięso przy kości nie będzie różowe.',
      'Salsa: pomidory, czerwoną cebulę i chili pokrój w drobną kostkę, wymieszaj z posiekaną kolendrą i resztą soku z limonki.',
      'Fasolę odsącz i podgrzej w rondelku z 2 łyżkami sosu spod kurczaka przez 5 minut.',
      'Podawaj udka z fasolą i świeżą salsą.',
    ],
    photo:
      'Roasted chicken thighs with crispy red-orange citrus-spiced skin, black beans and fresh tomato, red onion and coriander salsa',
  },
  {
    plan: 'OB-136',
    title: 'Zupa krem ze szparagów z groszkiem',
    description:
      'Aksamitny krem z zielonych szparagów i groszku z odrobiną śmietanki, podany z prażonymi pestkami dyni. Wiosenna zupa o świeżym, lekko słodkim smaku, gotowa w pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SPRING'],
    equipment: ['BLENDER'],
    ingredients: [
      ['szparagi', 500, 'g'],
      ['groszek mrożony', 200, 'g'],
      ['ziemniak', 200, 'g'],
      ['cebula', 80, 'g'],
      ['masło', 20, 'g'],
      ['bulion warzywny', 400, 'ml'],
      ['śmietanka 18', 80, 'ml'],
      ['pestki dyni', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Szparagom odłam zdrewniałe końce, odetnij 6 główek do dekoracji, resztę pokrój na kawałki. Ziemniaki obierz i pokrój w kostkę.',
      'W garnku roztop masło i zeszklij posiekaną cebulę przez 4 minuty.',
      'Dodaj ziemniaki, szparagi, bulion i 300 ml wody. Gotuj 15 minut. Na ostatnie 3 minuty wrzuć groszek i odłożone główki szparagów.',
      'Wyjmij główki szparagów, a zupę zmiksuj blenderem na gładki krem. Wlej śmietankę, dopraw pieprzem i podgrzej, nie gotując.',
      'Pestki dyni upraż na suchej patelni przez 3 minuty.',
      'Podawaj krem z główkami szparagów i pestkami dyni.',
    ],
    photo:
      'Smooth bright green asparagus and pea cream soup topped with tender asparagus tips and toasted pumpkin seeds',
    vessel: 'bowl',
  },
  {
    plan: 'OB-137',
    title: 'Kurczak ze szparagami i młodymi ziemniakami',
    description:
      'Wiosenny obiad z jednej blachy: cytrynowo-czosnkowy kurczak, zielone szparagi i młode ziemniaki z koperkiem i masłem. Prosty, lekki i pełen białka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING'],
    equipment: ['OVEN'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['szparagi', 300, 'g'],
      ['ziemniak młody', 500, 'g'],
      ['masło', 15, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['czosnek', 2, 'szt'],
      ['cytryna', 30, 'g'],
      ['koperek', 10, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C. Młode ziemniaki wyszoruj i przekrój na pół, wymieszaj z połową oliwy i połową soli.',
      'Rozłóż ziemniaki na blasze i piecz 15 minut.',
      'Kurczaka natrzyj resztą oliwy, przeciśniętym czosnkiem, tymiankiem, pieprzem, resztą soli i skórką otartą z cytryny.',
      'Szparagom odłam zdrewniałe końce. Ułóż kurczaka i szparagi na blasze obok ziemniaków i piecz 20 minut.',
      'Ziemniaki przełóż do miski i wymieszaj z masłem i posiekanym koperkiem. Kurczaka skrop sokiem z cytryny i pokrój.',
      'Podawaj kurczaka z ziemniakami i szparagami.',
    ],
    photo:
      'Sliced lemon garlic roasted chicken breast with bright green roasted asparagus and halved new potatoes glossy with butter and dill',
  },
  {
    plan: 'OB-138',
    title: 'Risotto ze szparagami i groszkiem',
    description:
      'Kremowe risotto na bulionie warzywnym z zielonymi szparagami, groszkiem, cytryną i parmezanem. Wiosna na talerzu — delikatne, a jednocześnie sycące danie bez mięsa.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'GRAINS',
    seasons: ['SPRING'],
    ingredients: [
      ['ryż arborio', 160, 'g'],
      ['szparagi', 300, 'g'],
      ['groszek mrożony', 150, 'g'],
      ['cebula', 60, 'g'],
      ['masło', 20, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['bulion warzywny', 300, 'ml'],
      ['ser parmezan', 30, 'g'],
      ['cytryna', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Szparagom odłam zdrewniałe końce, łodygi pokrój na 2-centymetrowe kawałki, główki odłóż. Końce zalej 600 ml wody, dodaj bulion i gotuj 10 minut, potem wyjmij — to wywar do risotto. Trzymaj go gorący.',
      'W szerokim garnku rozgrzej oliwę z połową masła i zeszklij drobno posiekaną cebulę przez 4 minuty.',
      'Wsyp ryż i mieszaj 2 minuty, aż ziarna zrobią się szkliste na brzegach.',
      'Wlewaj wywar po chochli, mieszając i dolewając następną porcję, gdy poprzednia się wchłonie. Po 10 minutach dodaj kawałki szparagów.',
      'Po kolejnych 6 minutach dodaj główki szparagów i groszek, gotuj jeszcze 3–4 minuty, aż ryż będzie kremowy i al dente.',
      'Zdejmij z ognia, wmieszaj resztę masła, starty parmezan, skórkę i łyżkę soku z cytryny. Dopraw pieprzem i odstaw na 2 minuty przed podaniem.',
    ],
    photo:
      'Creamy parmesan risotto studded with bright green asparagus pieces and peas, topped with asparagus tips and cracked black pepper',
    vessel: 'bowl',
  },
  {
    plan: 'OB-139',
    title: 'Botwinka z młodymi ziemniakami',
    description:
      'Lekka wiosenna zupa z młodych buraczków z liśćmi, młodych ziemniaków i koperku, zabielana śmietaną i podana z jajkiem na twardo. Kwaskowata, kolorowa i sezonowa jak mało co.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SPRING'],
    ingredients: [
      ['botwina', 500, 'g'],
      ['ziemniak młody', 400, 'g'],
      ['marchew', 80, 'g'],
      ['pietruszka korzeń', 60, 'g'],
      ['cebula', 60, 'g'],
      ['bulion warzywny', 200, 'ml'],
      ['śmietana 18', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['koperek', 10, 'g'],
      ['cytryna', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Botwinę umyj dokładnie. Buraczki obierz i pokrój w cienkie słupki, łodygi w plasterki, liście posiekaj.',
      'Marchew i pietruszkę pokrój w półplasterki, cebulę w kostkę. Zalej bulionem i 800 ml wody, zagotuj.',
      'Dodaj buraczki i łodygi oraz młode ziemniaki pokrojone w kostkę. Gotuj 15 minut.',
      'Wrzuć posiekane liście i gotuj jeszcze 3 minuty. Dopraw sokiem z cytryny i pieprzem.',
      'Jajka ugotuj na twardo przez 9 minut, ostudź i przekrój na połówki.',
      'Śmietanę zahartuj chochlą gorącej zupy i wlej do garnka. Podawaj z jajkiem i posiekanym koperkiem.',
    ],
    photo:
      'Creamy pink young beetroot soup with thin beet sticks, beet greens, new potato cubes and carrot, topped with two halves of a hard-boiled egg and fresh dill',
    vessel: 'bowl',
  },
  {
    plan: 'OB-140',
    title: 'Młoda kapusta duszona z koperkiem i kiełbasą',
    description:
      'Młoda kapusta duszona na maśle z cebulą, podsmażoną kiełbasą i dużą ilością koperku, lekko zaostrzona cytryną. Podana z młodymi ziemniakami — smak polskiego lata.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    seasons: ['SPRING', 'SUMMER'],
    ingredients: [
      ['młoda kapusta', 800, 'g'],
      ['kiełbasa', 130, 'g'],
      ['cebula', 80, 'g'],
      ['masło', 20, 'g'],
      ['koperek', 20, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['cytryna', 20, 'g'],
      ['cukier', 5, 'g'],
      ['ziemniak młody', 400, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kapustę poszatkuj, cebulę pokrój w kostkę, kiełbasę w półplasterki.',
      'W szerokim garnku podsmaż kiełbasę na połowie masła przez 4 minuty, dodaj cebulę i smaż 3 minuty.',
      'Dodaj kapustę, resztę masła i 150 ml wody. Przykryj i duś 20 minut, mieszając od czasu do czasu, aż kapusta zmięknie.',
      'W tym czasie ugotuj młode ziemniaki w mundurkach przez 20 minut.',
      'Mąkę ziemniaczaną rozmieszaj z 3 łyżkami zimnej wody, wlej do kapusty i zagotuj, aż sos lekko zgęstnieje. Dopraw sokiem z cytryny, cukrem i pieprzem.',
      'Wmieszaj posiekany koperek i podawaj z młodymi ziemniakami.',
    ],
    photo:
      'Tender braised young cabbage with golden sausage half-moons and plenty of fresh dill, boiled new potatoes in their skins on the side',
  },
];
