/**
 * Katalog 1000 — część OB-f: obiady OB-141 … OB-168 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Sezonowe ──
  {
    plan: 'OB-141',
    title: 'Chłodnik ogórkowy z jogurtem i koperkiem',
    description:
      'Orzeźwiający chłodnik na jogurcie i kefirze z tartym ogórkiem, rzodkiewką, czosnkiem i dużą ilością koperku, podany z jajkiem na twardo i młodymi ziemniakami. Lekki obiad na upalne dni, gotowy bez gotowania zupy.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SUMMER'],
    ingredients: [
      ['ogórek', 400, 'g'],
      ['jogurt naturalny', 300, 'g'],
      ['kefir', 300, 'ml'],
      ['rzodkiewka', 100, 'g'],
      ['koperek', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['jajko', 3, 'szt'],
      ['ziemniak młody', 300, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Młode ziemniaki wyszoruj i ugotuj w osolonej wodzie do miękkości, około 20 minut. Jajka ugotuj na twardo przez 9 minut i przelej zimną wodą.',
      'Ogórki umyj i zetrzyj na tarce o grubych oczkach razem ze skórką. Rzodkiewki pokrój w cienkie plasterki, a koperek drobno posiekaj.',
      'W dużej misce wymieszaj jogurt z kefirem, dodaj przeciśnięty czosnek, ogórki z sokiem, rzodkiewki i koperek.',
      'Dopraw chłodnik solą i pieprzem, przykryj i wstaw do lodówki na co najmniej 15 minut.',
      'Rozlej chłodnik do misek, ułóż połówki jajek, a ziemniaki podaj obok, posypane resztą koperku.',
    ],
    photo:
      'Pale green cold cucumber yogurt soup with grated cucumber, pink radish slices, chopped dill and halved hard-boiled eggs, small boiled new potatoes on the side',
    vessel: 'bowl',
  },
  {
    plan: 'OB-142',
    title: 'Makaron z bobem, boczkiem i śmietaną',
    description:
      'Makaron penne w kremowym sosie śmietanowym z młodym bobem, chrupiącym boczkiem i parmezanem. Sezonowe danie z początku lata, gotowe w pół godziny i bardzo sycące.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PASTA',
    seasons: ['SUMMER'],
    ingredients: [
      ['makaron penne', 180, 'g'],
      ['bób', 300, 'g'],
      ['boczek', 70, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['śmietanka 18', 150, 'ml'],
      ['ser parmezan', 20, 'g'],
      ['koperek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Bób ugotuj w osolonej wodzie przez 5 minut, odcedź, przelej zimną wodą i obierz ze skórek.',
      'Makaron ugotuj al dente według instrukcji na opakowaniu, zachowaj pół szklanki wody z gotowania.',
      'Boczek pokrój w kostkę i wytop na suchej patelni przez 5 minut, aż będzie chrupiący. Dodaj posiekaną cebulę i czosnek, smaż 3 minuty.',
      'Wlej śmietankę, dodaj bób i gotuj 2 minuty, aż sos lekko zgęstnieje. W razie potrzeby rozrzedź go wodą z makaronu.',
      'Wmieszaj makaron, połowę startego parmezanu i pieprz. Podawaj posypane resztą parmezanu i posiekanym koperkiem.',
    ],
    photo:
      'Penne pasta in creamy sauce with bright green peeled broad beans, crispy bacon cubes, grated parmesan and fresh dill',
  },
  {
    plan: 'OB-143',
    title: 'Zupa truskawkowa z makaronem',
    description:
      'Schłodzona zupa z dojrzałych truskawek zmiksowanych ze śmietaną, podana z makaronem świderki. Klasyk wakacyjnych obiadów z dzieciństwa, który zrobisz w kwadrans z sezonowych owoców.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SUMMER'],
    equipment: ['BLENDER'],
    ingredients: [
      ['truskawka', 500, 'g'],
      ['śmietana 18', 120, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['cukier', 25, 'g'],
      ['makaron świder', 160, 'g'],
      ['cukier waniliowy', 8, 'g'],
    ],
    steps: [
      'Truskawki umyj, odszypułkuj i wrzuć do garnka z 400 ml wody, cukrem i cukrem waniliowym. Zagotuj i gotuj 5 minut.',
      'Zdejmij garnek z ognia, zostaw kilka truskawek do dekoracji, a resztę zmiksuj blenderem na gładką zupę.',
      'Śmietanę wymieszaj z jogurtem greckim i kilkoma łyżkami gorącej zupy, a potem wlej do garnka i dokładnie połącz.',
      'Makaron ugotuj według instrukcji na opakowaniu, odcedź i przelej zimną wodą.',
      'Zupę schłodź w lodówce, rozlej do misek z makaronem i udekoruj pokrojonymi truskawkami.',
    ],
    photo:
      'Pink creamy strawberry soup with spiral pasta and halved fresh strawberries on top',
    vessel: 'bowl',
  },
  {
    plan: 'OB-144',
    title: 'Knedle ze śliwkami',
    description:
      'Miękkie knedle z ciasta ziemniaczanego z całymi węgierkami w środku, polane masłem z bułką tartą i posypane cukrem z cynamonem. Słodki obiad na koniec lata i jesień, gdy śliwki są najsłodsze.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 70,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DUMPLINGS',
    seasons: ['SUMMER', 'AUTUMN'],
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['mąka pszenna', 150, 'g'],
      ['mąka ziemniaczana', 30, 'g'],
      ['jajko', 1, 'szt'],
      ['śliwka', 300, 'g'],
      ['masło', 30, 'g'],
      ['bułka tarta', 30, 'g'],
      ['cukier', 20, 'g'],
      ['cynamon', 2, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, ugotuj w osolonej wodzie do miękkości (około 20 minut), odcedź i przeciśnij przez praskę. Odstaw do wystygnięcia.',
      'Do ziemniaków dodaj mąkę pszenną, mąkę ziemniaczaną i jajko, zagnieć gładkie, elastyczne ciasto.',
      'Śliwki umyj, natnij z boku i wyjmij pestki, pozostawiając owoce w całości.',
      'Odrywaj kawałki ciasta, spłaszczaj je w dłoni, owijaj każdą śliwkę i formuj gładkie kule.',
      'Wrzucaj knedle do osolonego wrzątku, a po wypłynięciu gotuj jeszcze 5 minut. Wyjmuj łyżką cedzakową.',
      'Na patelni roztop masło, zrumień na nim bułkę tartą przez 2 minuty. Polej knedle, posyp cukrem wymieszanym z cynamonem.',
    ],
    photo:
      'Round potato dumplings on a plate, one cut open to reveal a dark purple plum inside, topped with golden buttery breadcrumbs and cinnamon sugar',
  },
  {
    plan: 'OB-145',
    title: 'Fasolka szparagowa z czosnkiem i kurczakiem',
    description:
      'Chrupiąca fasolka szparagowa podsmażona z kawałkami kurczaka, dużą ilością czosnku i cytryną, podana z młodymi ziemniakami. Szybki, lekki i sycący obiad z sezonowych warzyw, bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SUMMER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['fasolka szparagowa', 400, 'g'],
      ['czosnek', 4, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 20, 'g'],
      ['ziemniak młody', 400, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Młode ziemniaki wyszoruj i ugotuj w osolonej wodzie do miękkości, około 20 minut.',
      'Fasolce odetnij końcówki i gotuj ją w osolonym wrzątku 5 minut, a potem odcedź i przelej zimną wodą.',
      'Kurczaka pokrój w paski, dopraw papryką, solą i pieprzem. Rozgrzej oliwę na dużej patelni i smaż mięso 6 minut, aż się zrumieni.',
      'Dodaj fasolkę i pokrojony w plasterki czosnek, smaż razem 3–4 minuty, często mieszając.',
      'Skrop sokiem z cytryny, posyp posiekaną natką i podawaj z ziemniakami.',
    ],
    photo:
      'Sauteed green beans with golden chicken strips, sliced garlic and chopped parsley, boiled new potatoes and a lemon wedge on the side',
  },
  {
    plan: 'OB-146',
    title: 'Kurki w sosie śmietanowym z kopytkami',
    description:
      'Domowe kopytka z ziemniaków podane z kurkami duszonymi na maśle z cebulką w gęstym sosie śmietanowym z koperkiem. Leśny smak lata w klasycznym polskim wydaniu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DUMPLINGS',
    seasons: ['SUMMER'],
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['mąka pszenna', 140, 'g'],
      ['jajko', 1, 'szt'],
      ['kurki', 400, 'g'],
      ['cebula', 80, 'g'],
      ['masło', 20, 'g'],
      ['śmietanka 18', 150, 'ml'],
      ['ser parmezan', 20, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki obierz, ugotuj do miękkości (około 20 minut), odcedź i przeciśnij przez praskę. Ostudź.',
      'Dodaj mąkę i jajko, zagnieć ciasto, podziel na wałki grubości kciuka i pokrój ukośnie na kopytka.',
      'Kurki dokładnie oczyść i opłucz, większe przekrój. Cebulę posiekaj.',
      'Na maśle zeszklij cebulę przez 3 minuty, dodaj kurki i duś 8 minut, aż odparuje woda.',
      'Wlej śmietankę, dopraw solą i pieprzem, gotuj 3 minuty, aż sos zgęstnieje, i wmieszaj posiekany koperek.',
      'Kopytka gotuj partiami w osolonym wrzątku 2 minuty od wypłynięcia. Podawaj z sosem kurkowym posypane startym parmezanem.',
    ],
    photo:
      'Potato kopytka dumplings covered with creamy golden chanterelle mushroom sauce, fresh dill and grated parmesan',
  },
  {
    plan: 'OB-147',
    title: 'Zupa krem z dyni z imbirem',
    description:
      'Aksamitny krem z dyni z czerwoną soczewicą, marchewką, świeżym imbirem i mlekiem kokosowym, posypany prażonymi pestkami dyni. Rozgrzewająca jesienna zupa, w pełni roślinna i bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['AUTUMN'],
    equipment: ['BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['dynia', 700, 'g'],
      ['marchew', 150, 'g'],
      ['cebula', 100, 'g'],
      ['soczewica czerwona', 70, 'g'],
      ['imbir', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['mleko kokosowe z puszki', 120, 'ml'],
      ['oliwa z oliwek', 15, 'ml'],
      ['pestki dyni', 25, 'g'],
      ['kurkuma', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Dynię obierz i pokrój w kostkę, marchew w plastry, cebulę w piórka. Imbir obierz i zetrzyj.',
      'Na oliwie w garnku zeszklij cebulę przez 3 minuty, dodaj czosnek, imbir i kurkumę, smaż 1 minutę.',
      'Dodaj dynię, marchew i przepłukaną soczewicę, wlej 800 ml wody i gotuj pod przykryciem 20 minut, aż warzywa będą miękkie.',
      'Wlej mleko kokosowe i zmiksuj zupę blenderem na gładki krem. Dopraw solą i pieprzem.',
      'Pestki dyni upraż na suchej patelni przez 3 minuty i posyp nimi zupę przed podaniem.',
    ],
    photo:
      'Bright orange velvety pumpkin cream soup with a swirl of coconut milk, toasted pumpkin seeds and a pinch of black pepper',
    vessel: 'bowl',
  },
  {
    plan: 'OB-148',
    title: 'Pieczona dynia z kaszą, fetą i pestkami',
    description:
      'Karmelizowana w piekarniku dynia z czerwoną cebulą na kaszy gryczanej, z pokruszoną fetą, rukolą i prażonymi pestkami dyni. Kolorowy jesienny obiad z miski, bez glutenu i bez mięsa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    seasons: ['AUTUMN'],
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['dynia', 600, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['kasza gryczana', 120, 'g'],
      ['ser feta', 100, 'g'],
      ['pestki dyni', 25, 'g'],
      ['rukola', 40, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['miód', 10, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C (termoobieg). Dynię obierz i pokrój w kostkę 2 cm, cebulę w ósemki.',
      'Wymieszaj warzywa z 15 ml oliwy, miodem, tymiankiem i pieprzem, rozłóż na blasze i piecz 25–30 minut, aż dynia się skarmelizuje.',
      'W tym czasie ugotuj kaszę gryczaną w 250 ml osolonej wody pod przykryciem przez 15 minut.',
      'Pestki dyni upraż na suchej patelni przez 3 minuty.',
      'Wymieszaj kaszę z rukolą i resztą oliwy, ułóż na wierzchu pieczoną dynię, pokruszoną fetę i pestki.',
    ],
    photo:
      'Caramelized roasted pumpkin cubes and red onion wedges on buckwheat groats with crumbled white feta, arugula and toasted pumpkin seeds',
    vessel: 'bowl',
  },
  {
    plan: 'OB-149',
    title: 'Gulasz z grzybów leśnych z kaszą gryczaną',
    description:
      'Gęsty gulasz z grzybów leśnych i pieczarek duszonych z cebulą, papryką i majerankiem, zabielony śmietaną i podany z kaszą gryczaną. Aromatyczne jesienne danie bez mięsa, które syci jak klasyczny gulasz.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'STEW',
    seasons: ['AUTUMN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['grzyby leśne mrożone', 400, 'g'],
      ['pieczarka', 250, 'g'],
      ['cebula', 120, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['mąka pszenna', 10, 'g'],
      ['śmietana 18', 100, 'g'],
      ['kasza gryczana', 140, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['majeranek', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj kaszę gryczaną w 300 ml osolonej wody pod przykryciem przez 15 minut i odstaw na 5 minut.',
      'Cebulę posiekaj, paprykę pokrój w kostkę, a pieczarki w plastry.',
      'Na oleju w szerokim garnku zeszklij cebulę przez 3 minuty, dodaj pieczarki i grzyby leśne prosto z zamrażarki. Smaż 10 minut, aż odparuje woda.',
      'Dodaj paprykę, słodką paprykę mieloną i majeranek, wlej 200 ml wody i duś pod przykryciem 15 minut.',
      'Śmietanę wymieszaj z mąką, wlej do gulaszu i gotuj 2 minuty, aż sos zgęstnieje. Dopraw solą i pieprzem.',
      'Podawaj gulasz na kaszy gryczanej.',
    ],
    photo:
      'Thick creamy forest mushroom goulash with red pepper pieces and paprika-tinted sauce served over brown buckwheat groats',
  },
  {
    plan: 'OB-150',
    title: 'Udka z kurczaka pieczone z jabłkami i śliwkami',
    description:
      'Soczyste udka z kurczaka pieczone na jednej blasze z jabłkami, śliwkami, czerwoną cebulą i ziemniakami, z nutą miodu i majeranku. Jesienne danie bez glutenu i bez nabiału, w którym owoce robią sos.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['AUTUMN'],
    equipment: ['OVEN'],
    ingredients: [
      ['udko z kurczaka', 2, 'szt'],
      ['ziemniak', 400, 'g'],
      ['jabłko', 300, 'g'],
      ['śliwka', 200, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['miód', 15, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['majeranek', 2, 'g'],
      ['rozmaryn suszony', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C (termoobieg). Udka natrzyj solą, pieprzem, majerankiem i rozmarynem.',
      'Ziemniaki obierz i pokrój w ćwiartki, jabłka w ósemki bez gniazd, śliwki przekrój i wyjmij pestki, cebulę pokrój w cząstki.',
      'Wymieszaj ziemniaki i cebulę z oliwą, rozłóż na blasze, a na wierzchu ułóż udka skórą do góry.',
      'Piecz 25 minut, potem dołóż jabłka i śliwki, posmaruj udka miodem i piecz jeszcze 20–25 minut, aż skórka będzie złota i chrupiąca.',
      'Podawaj udka z ziemniakami i owocami, polane sosem z blachy.',
    ],
    photo:
      'Golden roasted chicken thighs on a baking tray with roasted apple wedges, soft purple plums, red onion and potato quarters glazed in pan juices',
  },
  {
    plan: 'OB-151',
    title: 'Zupa z kurkami i ziemniakami',
    description:
      'Aromatyczna zupa z kurek duszonych na maśle, z ziemniakami, marchewką i koperkiem, zabielona śmietaną i podana z jajkiem na twardo. Letnio-jesienny klasyk, gdy kurki są najtańsze.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['SUMMER', 'AUTUMN'],
    ingredients: [
      ['kurki', 300, 'g'],
      ['ziemniak', 350, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['cebula', 80, 'g'],
      ['masło', 20, 'g'],
      ['śmietana 18', 100, 'g'],
      ['jajko', 2, 'szt'],
      ['koperek', 10, 'g'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Marchew i pietruszkę obierz i pokrój w plasterki, ziemniaki w kostkę. Zalej 1 l wody, dodaj liść laurowy i ziele angielskie, gotuj 15 minut.',
      'Kurki oczyść i opłucz. Na maśle zeszklij posiekaną cebulę, dodaj kurki i duś 8 minut.',
      'Przełóż kurki do zupy i gotuj razem 10 minut, aż ziemniaki będą miękkie.',
      'Jajka ugotuj na twardo przez 9 minut, ostudź i obierz.',
      'Śmietanę zahartuj kilkoma łyżkami gorącej zupy i wlej do garnka. Dopraw solą i pieprzem, dodaj posiekany koperek.',
      'Rozlej zupę do misek i podawaj z połówkami jajek.',
    ],
    photo:
      'Creamy golden soup with chanterelle mushrooms, potato cubes, carrot slices, chopped dill and a halved hard-boiled egg',
    vessel: 'bowl',
  },
  {
    plan: 'OB-152',
    title: 'Kotlety z kaszy jaglanej z dynią',
    description:
      'Złociste kotlety z kaszy jaglanej, tartej dyni i żółtego sera, smażone na chrupko i podane z sosem jogurtowo-czosnkowym i ogórkiem. Jesienny obiad bez mięsa, dobry także na zimno do pudełka.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'GRAINS',
    seasons: ['AUTUMN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza jaglana', 110, 'g'],
      ['dynia', 250, 'g'],
      ['cebula', 80, 'g'],
      ['jajko', 2, 'szt'],
      ['ser żółty', 60, 'g'],
      ['bułka tarta', 40, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['czosnek', 1, 'szt'],
      ['ogórek', 200, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz wrzątkiem, ugotuj w 300 ml osolonej wody pod przykryciem przez 15 minut i ostudź.',
      'Dynię zetrzyj na tarce o drobnych oczkach i odciśnij. Cebulę posiekaj drobno, ser zetrzyj.',
      'Połącz kaszę z dynią, cebulą, serem, jajkami i połową bułki tartej, dopraw pieprzem. Formuj 8 kotletów i obtocz je w reszcie bułki.',
      'Smaż kotlety na rozgrzanym oleju po 4 minuty z każdej strony na średnim ogniu, aż będą złote.',
      'Jogurt wymieszaj z przeciśniętym czosnkiem i posiekanym koperkiem. Podawaj kotlety z sosem i ogórkiem pokrojonym w plasterki.',
    ],
    photo:
      'Golden crispy millet and pumpkin patties with a bowl of garlic dill yogurt sauce and fresh cucumber slices',
  },
  {
    plan: 'OB-153',
    title: 'Kwaśnica z żeberkami',
    description:
      'Góralska zupa na kiszonej kapuście gotowana z wieprzowymi żeberkami, ziemniakami, kminkiem i majerankiem. Kwaśna, rozgrzewająca i treściwa, idealna na mroźny dzień.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 120,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['WINTER'],
    ingredients: [
      ['żeberko wieprzowe', 400, 'g'],
      ['kapusta kiszona', 180, 'g'],
      ['ziemniak', 300, 'g'],
      ['marchew', 100, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['liść laurowy', 1, 'g'],
      ['zioło angielskie', 1, 'g'],
      ['kminek', 1, 'g'],
      ['majeranek', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Żeberka podziel na kawałki, zalej 1,2 l zimnej wody, dodaj liść laurowy i ziele angielskie. Gotuj na małym ogniu 60 minut, zbierając szumowiny.',
      'Kapustę kiszoną posiekaj, dodaj do wywaru z kminkiem i gotuj 20 minut.',
      'Ziemniaki obierz i pokrój w kostkę, marchew w plasterki, dodaj do zupy i gotuj 15 minut.',
      'Cebulę posiekaj i zeszklij na suchej patelni z odrobiną tłuszczu zebranego z wywaru, dodaj czosnek i paprykę, przełóż do zupy.',
      'Dopraw majerankiem i pieprzem, gotuj jeszcze 5 minut. Podawaj z kawałkami żeberek w każdej misce.',
    ],
    photo:
      'Hearty sauerkraut soup with pork rib pieces, potato cubes, carrot slices and a sprinkle of marjoram in a rustic bowl',
    vessel: 'bowl',
  },
  {
    plan: 'OB-154',
    title: 'Pieczone warzywa korzeniowe z kaszą i jajkiem',
    description:
      'Pieczone buraki, marchew, pasternak i pietruszka z tymiankiem, podane na kaszy gryczanej z jajkiem na miękko i jogurtowym sosem. Zimowy obiad z tanich warzyw, bez glutenu i bez mięsa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['burak', 250, 'g'],
      ['marchew', 200, 'g'],
      ['pasternak', 150, 'g'],
      ['pietruszka korzeń', 100, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['kasza gryczana', 120, 'g'],
      ['jajko', 4, 'szt'],
      ['jogurt grecki', 100, 'g'],
      ['tymianek suszony', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C (termoobieg). Warzywa obierz, buraki pokrój w ósemki, marchew, pasternak i pietruszkę w słupki, cebulę w cząstki.',
      'Wymieszaj warzywa z oliwą, tymiankiem, solą i pieprzem, rozłóż na blasze i piecz 35 minut, raz przewracając.',
      'W tym czasie ugotuj kaszę gryczaną w 250 ml osolonej wody pod przykryciem przez 15 minut.',
      'Jajka włóż do wrzątku i gotuj 6 minut, przelej zimną wodą i obierz.',
      'Nałóż kaszę na talerze, ułóż pieczone warzywa, przekrojone jajka i łyżkę jogurtu greckiego, posyp pieprzem.',
    ],
    photo:
      'Roasted beet wedges, carrot and parsnip sticks and red onion on buckwheat groats with halved soft-boiled eggs with jammy yolks and a dollop of thick yogurt',
  },
  {
    plan: 'OB-155',
    title: 'Zupa fasolowa z wędzonką',
    description:
      'Gęsta zupa z białej fasoli z wędzonym boczkiem, warzywami, koncentratem pomidorowym i majerankiem. Tradycyjna, rozgrzewająca i bardzo sycąca, a następnego dnia smakuje jeszcze lepiej.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    seasons: ['WINTER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['fasola biała z puszki', 320, 'g'],
      ['boczek', 50, 'g'],
      ['ziemniak', 300, 'g'],
      ['marchew', 100, 'g'],
      ['pietruszka korzeń', 80, 'g'],
      ['seler korzeniowy', 60, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['koncentrat pomidorowy', 30, 'g'],
      ['majeranek', 3, 'g'],
      ['liść laurowy', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Boczek pokrój w kostkę i wytop w garnku przez 5 minut. Dodaj posiekaną cebulę i czosnek, smaż 3 minuty.',
      'Marchew, pietruszkę, seler i ziemniaki obierz i pokrój w kostkę. Wrzuć do garnka, wlej 1 l wody, dodaj liść laurowy i gotuj 20 minut.',
      'Fasolę odcedź i przepłucz, dodaj do zupy razem z koncentratem pomidorowym i gotuj 10 minut.',
      'Chochlę zupy z fasolą zmiksuj lub rozgnieć i wlej z powrotem, żeby zupa zgęstniała.',
      'Dopraw majerankiem i pieprzem, gotuj jeszcze 3 minuty i podawaj gorącą.',
    ],
    photo:
      'Thick reddish white bean soup with smoked bacon cubes, diced potatoes and carrots, sprinkled with dried marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'OB-156',
    title: 'Zupa krem z pieczonych buraków z kozim serem',
    description:
      'Głęboko rubinowy krem z buraków pieczonych z jabłkiem i czosnkiem, zagęszczony białą fasolą i podany z kozim serem oraz orzechami. Elegancka zimowa zupa bez glutenu, słodko-kwaśna i kremowa.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 70,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SOUP',
    seasons: ['WINTER'],
    equipment: ['OVEN', 'BLENDER'],
    ingredients: [
      ['burak', 600, 'g'],
      ['jabłko', 150, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['fasola biała z puszki', 240, 'g'],
      ['ser kozi', 80, 'g'],
      ['orzech włoski', 20, 'g'],
      ['cytryna', 20, 'g'],
      ['tymianek suszony', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C (termoobieg). Buraki obierz i pokrój w ćwiartki, jabłko i cebulę w ósemki.',
      'Wymieszaj warzywa i nieobrane ząbki czosnku z oliwą i tymiankiem, przykryj folią i piecz 45 minut, aż buraki zmiękną.',
      'Przełóż warzywa do garnka, wyciśnij czosnek ze skórek, dodaj odcedzoną fasolę i 700 ml wody. Gotuj 5 minut.',
      'Zmiksuj blenderem na gładki krem, dopraw pieprzem i sokiem z cytryny.',
      'Orzechy posiekaj i upraż na suchej patelni. Rozlej zupę, pokrusz na wierzch kozi ser i posyp orzechami.',
    ],
    photo:
      'Deep ruby-red beetroot cream soup topped with crumbled white goat cheese, toasted chopped walnuts and a drizzle of olive oil',
    vessel: 'bowl',
  },
  {
    plan: 'OB-157',
    title: 'Pęczak z kiszoną kapustą i grzybami',
    description:
      'Kasza pęczak duszona z kiszoną kapustą, pieczarkami, suszonymi grzybami i cebulą, z chrupiącym tofu w wędzonej papryce. Roślinne danie w smaku wigilijnym, sycące i idealne na zimowy obiad.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'GRAINS',
    seasons: ['WINTER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['kasza pęczak', 140, 'g'],
      ['kapusta kiszona', 200, 'g'],
      ['pieczarka', 300, 'g'],
      ['grzyb suszony', 10, 'g'],
      ['cebula', 120, 'g'],
      ['tofu', 200, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['papryka wędzona mielona', 2, 'g'],
      ['majeranek', 2, 'g'],
      ['kminek', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Suszone grzyby zalej 200 ml wrzątku i odstaw na 15 minut, potem pokrój, a wodę zachowaj.',
      'Pęczak ugotuj w 400 ml wody pod przykryciem przez 25 minut, aż wchłonie płyn.',
      'Na 10 ml oleju zeszklij posiekaną cebulę, dodaj pokrojone pieczarki i smaż 6 minut. Dodaj posiekaną kapustę, suszone grzyby z wodą, kminek i majeranek, duś 15 minut.',
      'Tofu osusz, pokrój w kostkę, obtocz w wędzonej papryce i usmaż na reszcie oleju na chrupko przez 6–8 minut.',
      'Wmieszaj pęczak do kapusty z grzybami, dopraw pieprzem i podawaj z tofu na wierzchu.',
    ],
    photo:
      'Pearl barley stewed with sauerkraut, sliced mushrooms and onion, topped with crispy golden smoked-paprika tofu cubes and dried marjoram',
  },
  // ── Airfryer ──
  {
    plan: 'OB-158',
    title: 'Udka z kurczaka z ziemniakami',
    description:
      'Chrupiące udka z kurczaka w papryce i czosnku pieczone w airfryerze razem z ćwiartkami ziemniaków. Proste, sycące danie z jednego kosza, bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['udko z kurczaka', 600, 'g'],
      ['ziemniak', 350, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['majeranek', 1, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Udka osusz ręcznikiem papierowym i natrzyj papryką, czosnkiem granulowanym, majerankiem, połową soli i pieprzem.',
      'Ziemniaki umyj, pokrój w ćwiartki, wymieszaj z oliwą i resztą soli.',
      'Ułóż udka skórą do dołu w koszu airfryera rozgrzanego do 190°C i piecz 12 minut.',
      'Odwróć udka, dołóż ziemniaki i piecz jeszcze 18–20 minut, potrząsając koszem w połowie, aż skórka będzie chrupiąca, a ziemniaki złote.',
      'W piekarniku: 200°C, termoobieg, 40–45 minut na jednej blasze, w połowie przewracając.',
    ],
    photo:
      'Crispy paprika-rubbed golden chicken thighs with roasted potato wedges and a sprinkle of dried marjoram',
  },
  {
    plan: 'OB-159',
    title: 'Burgery wołowe z frytkami',
    description:
      'Soczyste burgery z mielonej wołowiny z cheddarem, pomidorem, sałatą i ogórkiem w miękkiej bułce, z chrupiącymi frytkami z airfryera. Amerykański klasyk w domowym wydaniu, bez głębokiego tłuszczu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'SANDWICH',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['wołowina mielona', 300, 'g'],
      ['bułka do hamburgera', 2, 'szt'],
      ['ser cheddar', 30, 'g'],
      ['pomidor', 120, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['ogórek konserwowy', 30, 'g'],
      ['ketchup', 15, 'g'],
      ['frytka mrożona', 300, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wołowinę dopraw pieprzem, uformuj dwa płaskie kotlety nieco większe od bułki i zrób kciukiem wgłębienie na środku.',
      'Frytki piecz w airfryerze w 200°C przez 15–18 minut, potrząsając koszem co 5 minut. Wyjmij i trzymaj w cieple.',
      'Kotlety piecz w airfryerze w 190°C przez 10–12 minut, w połowie odwracając. Na ostatnią minutę połóż na nich cheddar.',
      'Bułki przekrój i podpiecz w koszu 1 minutę. Pomidor i cebulę pokrój w plastry, ogórki w plasterki.',
      'Posmaruj bułki ketchupem, ułóż sałatę, kotlet z serem, pomidor, cebulę i ogórek. Podawaj z frytkami.',
      'W piekarniku: frytki 220°C, termoobieg, 20–25 minut; kotlety 200°C, 15 minut na kratce.',
    ],
    photo:
      'Beef cheeseburger with melted cheddar, lettuce, tomato, red onion and pickles in a soft sesame bun, golden fries on the side',
    vessel: 'board',
  },
  {
    plan: 'OB-160',
    title: 'Kurczak w panierce z płatków kukurydzianych',
    description:
      'Chrupiące paski kurczaka w panierce z pokruszonych płatków kukurydzianych, upieczone w airfryerze, z ziemniakami i mizerią. Ulubiony obiad dzieci, a przy tym dużo białka i mało tłuszczu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['filet z kurczaka', 400, 'g'],
      ['płatki kukurydziane', 60, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 20, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['ziemniak', 400, 'g'],
      ['ogórek', 250, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Ziemniaki obierz i ugotuj w osolonej wodzie do miękkości, około 20 minut.',
      'Kurczaka pokrój w paski, dopraw papryką i odrobiną soli. Płatki kukurydziane pokrusz w dłoniach lub w woreczku.',
      'Obtaczaj paski kolejno w mące, roztrzepanym jajku i płatkach, dociskając panierkę. Skrop olejem.',
      'Piecz w airfryerze w 190°C przez 12–14 minut, w połowie odwracając, aż panierka będzie złota i chrupiąca.',
      'Ogórek pokrój w cienkie plasterki, wymieszaj z jogurtem, posiekanym koperkiem i szczyptą soli. Podawaj kurczaka z ziemniakami i mizerią.',
      'W piekarniku: 200°C, termoobieg, 20–22 minuty na blasze z papierem, w połowie odwracając.',
    ],
    photo:
      'Golden crunchy cornflake-crusted chicken strips with boiled potatoes sprinkled with dill and a bowl of creamy cucumber salad',
  },
  {
    plan: 'OB-161',
    title: 'Żeberka BBQ z ziemniakami',
    description:
      'Wieprzowe żeberka w wędzonej papryce i czosnku, upieczone w airfryerze i glazurowane sosem barbecue, z chrupiącymi ziemniakami. Lepkie, soczyste i bez godzin czekania przy piekarniku.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['żeberko wieprzowe', 600, 'g'],
      ['sos barbecue', 60, 'g'],
      ['ziemniak', 500, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Żeberka pokrój na kawałki po 2–3 kości, natrzyj wędzoną papryką, czosnkiem granulowanym, solą i pieprzem.',
      'Piecz żeberka w airfryerze w 170°C przez 25 minut, w połowie odwracając.',
      'Ziemniaki pokrój w łódeczki i wymieszaj z oliwą. Wyjmij żeberka, a ziemniaki piecz w 200°C przez 18 minut, potrząsając koszem.',
      'Posmaruj żeberka sosem barbecue, włóż z powrotem do kosza i piecz w 200°C jeszcze 6–8 minut, aż glazura się skarmelizuje.',
      'W piekarniku: żeberka pod folią 170°C przez 60 minut, potem z sosem 10 minut w 220°C; ziemniaki obok na blasze 200°C, 35 minut.',
    ],
    photo:
      'Sticky glazed barbecue pork ribs with a dark caramelized sauce next to crispy golden potato wedges',
  },
  {
    plan: 'OB-162',
    title: 'Łosoś z batatami i fasolką',
    description:
      'Filet z łososia z cytryną i czosnkiem, pieczony w airfryerze razem z kostkami batata i zieloną fasolką szparagową. Pełnowartościowy obiad z jednego kosza, bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['łosoś', 300, 'g'],
      ['batat', 400, 'g'],
      ['fasolka szparagowa', 250, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Bataty obierz i pokrój w kostkę 2 cm, wymieszaj z 10 ml oliwy, papryką i szczyptą soli.',
      'Piecz bataty w airfryerze w 200°C przez 10 minut.',
      'Łososia pokrój na dwie porcje, natrzyj przeciśniętym czosnkiem, skórką z cytryny, solą i pieprzem. Fasolce odetnij końcówki i wymieszaj z resztą oliwy.',
      'Dołóż do kosza fasolkę i łososia skórą do dołu, piecz w 190°C jeszcze 10–12 minut, aż ryba będzie różowa w środku.',
      'Skrop wszystko sokiem z cytryny i podawaj od razu.',
      'W piekarniku: 200°C, termoobieg; bataty 15 minut, potem z łososiem i fasolką jeszcze 15 minut.',
    ],
    photo:
      'Pink roasted salmon fillet with golden sweet potato cubes, bright green beans and lemon wedges',
  },
  {
    plan: 'OB-163',
    title: 'Cordon bleu z sałatą',
    description:
      'Rozbite filety z kurczaka zawinięte z szynką i żółtym serem, w chrupiącej panierce upieczonej w airfryerze, z miską sałaty z pomidorkami i ogórkiem. Klasyk restauracyjny bez smażenia w głębokim tłuszczu.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['szynka', 40, 'g'],
      ['ser żółty', 40, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka pszenna', 20, 'g'],
      ['bułka tarta', 50, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sałata rzymska', 150, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['ogórek', 150, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filety przekrój poziomo na płaty, przykryj folią i rozbij tłuczkiem na cienkie kotlety. Dopraw pieprzem.',
      'Na każdym kotlecie ułóż plaster szynki i sera, zwiń ciasno lub złóż na pół i dociśnij brzegi.',
      'Obtocz cordon bleu w mące, roztrzepanym jajku i bułce tartej, skrop olejem.',
      'Piecz w airfryerze w 180°C przez 18–20 minut, w połowie odwracając, aż panierka będzie złota, a ser się roztopi.',
      'Sałatę porwij, pomidorki przekrój, ogórek pokrój w plasterki. Polej oliwą z sokiem z cytryny i podawaj z mięsem.',
      'W piekarniku: 200°C, termoobieg, 25–30 minut na blasze z papierem, w połowie odwracając.',
    ],
    photo:
      'Golden breaded chicken cordon bleu cut in half showing ham and melted cheese inside, with a fresh salad of romaine, cherry tomatoes and cucumber',
  },
  {
    plan: 'OB-164',
    title: 'Chrupiące tofu z ryżem i warzywami',
    description:
      'Kostki tofu w cienkiej skrobiowej panierce upieczone w airfryerze na chrupko, z ryżem jaśminowym, edamame i warzywami w sosie sojowo-imbirowym. Roślinny obiad z dużą porcją białka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'GRAINS',
    equipment: ['AIRFRYER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['tofu', 360, 'g'],
      ['mąka ziemniaczana', 15, 'g'],
      ['ryż jaśminowy', 90, 'g'],
      ['edamame', 120, 'g'],
      ['brokuł', 200, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['olej sezamowy', 10, 'ml'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Ugotuj ryż w 180 ml wody pod przykryciem przez 12 minut i odstaw na 5 minut.',
      'Tofu odsącz, osusz ręcznikiem i pokrój w kostkę. Skrop 10 ml sosu sojowego i obtocz w mące ziemniaczanej.',
      'Piecz tofu w airfryerze w 200°C przez 15 minut, potrząsając koszem co 5 minut, aż będzie chrupiące.',
      'Na oleju sezamowym smaż różyczki brokułu, pokrojoną paprykę i edamame przez 5 minut. Dodaj starty imbir, czosnek i resztę sosu sojowego, smaż 1 minutę.',
      'Podawaj ryż z warzywami i chrupiącym tofu, posypane sezamem.',
      'W piekarniku: tofu na blasze z papierem, 210°C, termoobieg, 25 minut, w połowie przewracając.',
    ],
    photo:
      'Crispy golden tofu cubes on jasmine rice with bright green broccoli, edamame beans and red pepper strips glazed in soy ginger sauce, sprinkled with sesame seeds',
    vessel: 'bowl',
  },
  {
    plan: 'OB-165',
    title: 'Skrzydełka BBQ z coleslawem',
    description:
      'Chrupiące skrzydełka z kurczaka w wędzonej papryce, upieczone w airfryerze i obtoczone w sosie barbecue, z kremową surówką coleslaw. Amerykański klasyk na wspólny obiad, bez głębokiego tłuszczu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['skrzydełko z kurczaka', 700, 'g'],
      ['sos barbecue', 50, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['kapusta biała', 250, 'g'],
      ['marchew', 100, 'g'],
      ['majonez', 30, 'g'],
      ['jogurt naturalny', 60, 'g'],
      ['ocet jabłkowy', 5, 'ml'],
      ['cukier', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Skrzydełka osusz, przekrój w stawie i natrzyj wędzoną papryką, czosnkiem granulowanym, solą i pieprzem.',
      'Piecz w airfryerze w 180°C przez 20 minut, potem zwiększ do 200°C i piecz jeszcze 5 minut, aż skórka będzie chrupiąca.',
      'W tym czasie poszatkuj cienko kapustę, zetrzyj marchew. Wymieszaj majonez z jogurtem, octem i cukrem, połącz z warzywami.',
      'Gorące skrzydełka wymieszaj w misce z sosem barbecue i piecz jeszcze 2–3 minuty w 200°C, żeby sos się przykleił.',
      'Podawaj skrzydełka z coleslawem.',
      'W piekarniku: 220°C, termoobieg, 35–40 minut na kratce nad blachą, po obtoczeniu w sosie jeszcze 5 minut.',
    ],
    photo:
      'Sticky glossy barbecue chicken wings with a bowl of creamy white cabbage and carrot coleslaw',
  },
  {
    plan: 'OB-166',
    title: 'Karkówka z ziemniakami i surówką',
    description:
      'Plastry karkówki marynowane w czosnku, majeranku i musztardzie, upieczone w airfryerze z ziemniakami i podane z surówką z marchewki i jabłka. Niedzielny obiad w wersji bez patelni, bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['karkówka', 350, 'g'],
      ['musztarda', 15, 'g'],
      ['czosnek', 2, 'szt'],
      ['majeranek', 2, 'g'],
      ['ziemniak', 450, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['marchew', 200, 'g'],
      ['jabłko', 150, 'g'],
      ['cytryna', 15, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Karkówkę pokrój na 4 plastry grubości 1,5 cm, lekko rozbij. Natrzyj musztardą, przeciśniętym czosnkiem, majerankiem, połową soli i pieprzem, odstaw na 15 minut.',
      'Ziemniaki pokrój w łódeczki, wymieszaj z oliwą i resztą soli. Piecz w airfryerze w 200°C przez 20 minut, potrząsając koszem.',
      'Wyjmij ziemniaki, włóż karkówkę i piecz w 190°C przez 14–16 minut, w połowie odwracając. Na ostatnie 3 minuty dołóż ziemniaki, żeby się podgrzały.',
      'Marchew i jabłko zetrzyj na tarce, skrop sokiem z cytryny i olejem, wymieszaj.',
      'Podawaj karkówkę z ziemniakami i surówką.',
      'W piekarniku: 200°C, termoobieg, ziemniaki 35 minut, karkówka obok na blasze 25 minut, w połowie przewracając.',
    ],
    photo:
      'Juicy golden roasted pork neck slices with crispy potato wedges and a bright orange grated carrot and apple salad',
  },
  {
    plan: 'OB-167',
    title: 'Papryki faszerowane kaszą jaglaną i fetą',
    description:
      'Kolorowe papryki nadziewane kaszą jaglaną z fetą, cukinią, czosnkiem i oregano, upieczone w airfryerze do miękkości. Wegetariański obiad bez glutenu, który zrobisz z tego, co zwykle jest w lodówce.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['papryka czerwona', 4, 'szt'],
      ['kasza jaglana', 100, 'g'],
      ['ser feta', 120, 'g'],
      ['cukinia', 150, 'g'],
      ['cebula', 60, 'g'],
      ['jajko', 1, 'szt'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 2, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszę jaglaną przepłucz wrzątkiem i ugotuj w 250 ml wody pod przykryciem przez 15 minut.',
      'Cebulę i cukinię pokrój w drobną kostkę, podsmaż na oliwie z czosnkiem przez 5 minut.',
      'Wymieszaj kaszę z warzywami, pokruszoną fetą, jajkiem, oregano i pieprzem.',
      'Paprykom odetnij górę, usuń gniazda nasienne i napełnij farszem. Przykryj odciętymi kapeluszami.',
      'Piecz w airfryerze w 180°C przez 18–20 minut, aż papryki zmiękną i lekko się przypieką. Posyp posiekaną natką.',
      'W piekarniku: 190°C, termoobieg, 30–35 minut w naczyniu żaroodpornym.',
    ],
    photo:
      'Four roasted red bell peppers stuffed with golden millet, crumbled feta and zucchini, lightly charred skins and chopped parsley on top',
  },
  {
    plan: 'OB-168',
    title: 'Pierś z indyka z kaszą i brokułem',
    description:
      'Soczysta pierś z indyka w ziołach i papryce, upieczona w airfryerze, z kaszą gryczaną i brokułem z czosnkiem. Lekki, bardzo białkowy obiad, idealny do pudełka na kolejny dzień.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z indyka', 300, 'g'],
      ['kasza gryczana', 80, 'g'],
      ['brokuł', 300, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['czosnek', 2, 'szt'],
      ['cytryna', 15, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['zioła prowansalskie', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ugotuj kaszę gryczaną w 170 ml osolonej wody pod przykryciem przez 15 minut.',
      'Filet z indyka natrzyj 5 ml oliwy, papryką, ziołami prowansalskimi, solą i pieprzem.',
      'Piecz indyka w airfryerze w 190°C przez 14–16 minut, w połowie odwracając. Odstaw na 3 minuty i pokrój w plastry.',
      'Brokuł podziel na różyczki, wymieszaj z resztą oliwy i przeciśniętym czosnkiem, piecz w airfryerze w 190°C przez 7 minut.',
      'Podawaj indyka z kaszą i brokułem, skropionym sokiem z cytryny.',
      'W piekarniku: 200°C, termoobieg, indyk 22–25 minut, brokuł obok przez ostatnie 12 minut.',
    ],
    photo:
      'Sliced golden herb-crusted turkey breast with brown buckwheat groats and roasted broccoli florets, lemon wedge on the side',
  },
];
