/**
 * Katalog 1000 — część OB-g: obiady OB-169 … OB-195 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Airfryer ──
  {
    plan: 'OB-169',
    title: 'Pałki z kurczaka w miodzie i musztardzie z ryżem',
    description:
      'Soczyste pałki z kurczaka w lepkiej glazurze z miodu, musztardy i czosnku, upieczone w airfryerze na rumiano i podane z sypkim ryżem basmati i świeżym ogórkiem. Obiad, który lubią dorośli i dzieci.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['podudzie z kurczaka', 700, 'g'],
      ['miód', 25, 'g'],
      ['musztarda', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['sól', 1.5, 'g'],
      ['ryż basmati', 120, 'g'],
      ['ogórek', 200, 'g'],
    ],
    steps: [
      'Wymieszaj miód, musztardę, przeciśnięty czosnek, olej, paprykę i sól. Pałki osusz, natnij skórę w 2–3 miejscach i dokładnie obtocz w połowie glazury.',
      'Ułóż pałki w koszu airfryera w jednej warstwie i piecz w 190°C przez 12 minut.',
      'Odwróć pałki, posmaruj resztą glazury i piecz jeszcze 10–13 minut, aż skórka się skarmelizuje, a sok przy kości będzie przejrzysty. W piekarniku: 200°C, termoobieg, 35–40 minut z odwróceniem w połowie.',
      'W tym czasie przepłucz ryż i ugotuj go w 240 ml wody pod przykryciem na małym ogniu przez 12 minut, potem odstaw na 5 minut.',
      'Ogórek pokrój w półplasterki. Podawaj pałki z ryżem i ogórkiem, polane sosem z dna kosza.',
    ],
    photo:
      'Glossy honey-mustard glazed chicken drumsticks with caramelized skin, fluffy white basmati rice and fresh cucumber half-moons',
  },
  {
    plan: 'OB-170',
    title: 'Polędwiczka wieprzowa z batatami',
    description:
      'Chuda polędwiczka wieprzowa w wędzonej papryce i rozmarynie, upieczona w airfryerze razem z kawałkami batatów, które karmelizują się na brzegach. Podana na rukoli, bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['polędwiczka wieprzowa', 400, 'g'],
      ['batat', 450, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['rozmaryn suszony', 2, 'g'],
      ['czosnek', 2, 'szt'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['rukola', 50, 'g'],
    ],
    steps: [
      'Bataty obierz i pokrój w kostkę 2 cm. Wymieszaj z połową oliwy, połową rozmarynu i szczyptą soli.',
      'Polędwiczkę oczyść z błon, natrzyj resztą oliwy, przeciśniętym czosnkiem, wędzoną papryką, rozmarynem, solą i pieprzem.',
      'Piecz bataty w airfryerze w 200°C przez 8 minut. Dołóż polędwiczkę i piecz razem w 190°C przez 15–17 minut, w połowie potrząsając koszem i obracając mięso.',
      'W piekarniku: 200°C, termoobieg, bataty 10 minut, potem z polędwiczką jeszcze 20–25 minut.',
      'Odstaw mięso na 5 minut, pokrój w plastry i podawaj z batatami na rukoli.',
    ],
    photo:
      'Sliced juicy pork tenderloin with a smoky paprika crust, caramelized orange sweet potato cubes and a handful of fresh rocket',
  },
  {
    plan: 'OB-171',
    title: 'Kurczak tandoori z ryżem',
    description:
      'Kawałki kurczaka marynowane w jogurcie z garam masalą, kurkumą, imbirem i limonką, upieczone w airfryerze z przypaloną krawędzią jak z pieca tandoor. Podane z ryżem basmati, czerwoną cebulą i kolendrą.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['filet z kurczaka', 400, 'g'],
      ['jogurt naturalny', 100, 'g'],
      ['garam masala', 5, 'g'],
      ['kurkuma', 2, 'g'],
      ['papryka słodka mielona', 3, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['limonka', 40, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 2, 'g'],
      ['ryż basmati', 120, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Wymieszaj jogurt z garam masalą, kurkumą, papryką, startym imbirem, przeciśniętym czosnkiem, sokiem z połowy limonki, olejem i solą.',
      'Kurczaka pokrój w duże kawałki, obtocz w marynacie i odstaw do lodówki na co najmniej 30 minut.',
      'Ułóż kurczaka w koszu airfryera i piecz w 200°C przez 14–16 minut, w połowie obracając, aż brzegi lekko się przypalą. W piekarniku: 220°C, termoobieg, 20–25 minut na kratce nad blachą.',
      'W tym czasie ugotuj przepłukany ryż w 240 ml wody pod przykryciem przez 12 minut i odstaw na 5 minut.',
      'Cebulę pokrój w cienkie piórka i skrop resztą soku z limonki. Podawaj kurczaka z ryżem, cebulą i posiekaną kolendrą.',
    ],
    photo:
      'Charred orange-red tandoori chicken pieces with basmati rice, thin lime-dressed red onion slices and chopped fresh coriander',
  },
  {
    plan: 'OB-172',
    title: 'Gnocchi z warzywami i pesto',
    description:
      'Gnocchi upieczone w airfryerze na chrupko razem z cukinią, papryką, cebulą i pomidorkami, wymieszane z pesto bazyliowym i podane z łyżkami kremowej ricotty. Szybki wegetariański obiad bez gotowania wody.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'DUMPLINGS',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['gnocchi', 300, 'g'],
      ['cukinia', 250, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['pomidor koktajlowy', 200, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['pesto bazyliowe', 40, 'g'],
      ['ser ricotta', 150, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cukinię i paprykę pokrój w kostkę 2 cm, cebulę w ósemki. Wymieszaj warzywa i surowe gnocchi z oliwą i pieprzem.',
      'Piecz w koszu airfryera w 200°C przez 10 minut, potrząśnij koszem, dołóż pomidorki i piecz jeszcze 6–8 minut, aż gnocchi będą złote i chrupiące. W piekarniku: 220°C, termoobieg, 25 minut na blasze, z przemieszaniem w połowie.',
      'Ricottę rozmieszaj widelcem z odrobiną pieprzu na gładki krem.',
      'Przełóż gorące gnocchi z warzywami do miski, wymieszaj z pesto i od razu podawaj z łyżkami ricotty na wierzchu.',
    ],
    photo:
      'Golden crispy gnocchi tossed with roasted zucchini, red pepper, red onion and blistered cherry tomatoes in green basil pesto with dollops of creamy white ricotta',
    vessel: 'bowl',
  },
  {
    plan: 'OB-173',
    title: 'Kotlety z łososia z kaszą i ogórkiem',
    description:
      'Delikatne kotlety z siekanego łososia z koperkiem i cytryną, upieczone w airfryerze bez smażenia. Podane z kaszą gryczaną i chłodną mizerią na jogurcie — rybny obiad, który smakuje nawet niejadkom.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['łosoś', 350, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 30, 'g'],
      ['koperek', 15, 'g'],
      ['cytryna', 20, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['kasza gryczana', 100, 'g'],
      ['ogórek', 250, 'g'],
      ['jogurt naturalny', 100, 'g'],
    ],
    steps: [
      'Kaszę przepłucz i gotuj w 200 ml osolonej wody pod przykryciem 15 minut, potem odstaw.',
      'Łososia bez skóry posiekaj drobno nożem. Wymieszaj z jajkiem, bułką tartą, połową koperku, skórką i sokiem z cytryny, solą i pieprzem. Uformuj 6 kotletów.',
      'Posmaruj kotlety olejem i piecz w airfryerze w 190°C przez 12–14 minut, w połowie ostrożnie odwracając. W piekarniku: 200°C, termoobieg, 18–20 minut na blasze z papierem.',
      'Ogórek pokrój w cienkie plasterki, wymieszaj z jogurtem, resztą koperku i szczyptą pieprzu.',
      'Podawaj kotlety z kaszą i mizerią.',
    ],
    photo:
      'Golden salmon patties flecked with dill, a mound of brown buckwheat groats and creamy cucumber salad with yogurt and fresh dill',
  },
  {
    plan: 'OB-174',
    title: 'Ziemniaki hasselback z twarożkiem i boczkiem',
    description:
      'Ziemniaki nacięte w harmonijkę, upieczone w airfryerze z masłem czosnkowym i chrupiącym boczkiem, podane z twarożkiem ze szczypiorkiem. Złote brzegi, miękki środek i domowy smak bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'POTATOES',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ziemniak', 700, 'g'],
      ['boczek', 60, 'g'],
      ['masło', 15, 'g'],
      ['czosnek', 1, 'szt'],
      ['papryka słodka mielona', 2, 'g'],
      ['twarożek', 250, 'g'],
      ['szczypiorek', 15, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Ziemniaki dokładnie wyszoruj. Połóż każdy między dwiema drewnianymi łyżkami i natnij w poprzek co 3 mm, nie dokrajając do spodu.',
      'Roztop masło z przeciśniętym czosnkiem i papryką, posmaruj ziemniaki, rozchylając nacięcia, i posyp solą.',
      'Piecz w airfryerze w 190°C przez 25 minut. Boczek pokrój w cienkie paski, wsuń część w nacięcia, resztę rozsyp obok i piecz jeszcze 8–10 minut, aż ziemniaki będą miękkie, a boczek chrupiący. W piekarniku: 200°C, termoobieg, 45–50 minut, boczek na ostatnie 12 minut.',
      'Twarożek wymieszaj z posiekanym szczypiorkiem i pieprzem.',
      'Podawaj gorące ziemniaki z boczkiem i dużą łyżką twarożku.',
    ],
    photo:
      'Golden accordion-sliced hasselback potatoes with crispy bacon strips tucked into the cuts and a dollop of cottage cheese with chives',
  },
  {
    plan: 'OB-175',
    title: 'Klopsiki z indyka z kaszą i sosem jogurtowym',
    description:
      'Lekkie klopsiki z mielonego indyka z koperkiem, upieczone w airfryerze bez grama tłuszczu, podane z kaszą gryczaną i sosem z jogurtu, ogórka i czosnku. Dużo białka w lekkim obiedzie.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    equipment: ['AIRFRYER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['indyk mielony', 300, 'g'],
      ['jajko', 1, 'szt'],
      ['cebula', 50, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 15, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['kasza gryczana', 70, 'g'],
      ['jogurt naturalny', 150, 'g'],
      ['ogórek', 150, 'g'],
    ],
    steps: [
      'Kaszę przepłucz i gotuj w 140 ml osolonej wody pod przykryciem 15 minut, potem odstaw.',
      'Cebulę zetrzyj na drobnych oczkach. Wymieszaj indyka z jajkiem, cebulą, 1 przeciśniętym ząbkiem czosnku, połową koperku, papryką, solą i pieprzem. Uformuj 12 klopsików.',
      'Piecz klopsiki w airfryerze w 190°C przez 12–14 minut, w połowie potrząsając koszem. W piekarniku: 200°C, termoobieg, 18–20 minut na blasze z papierem.',
      'Ogórek zetrzyj, odciśnij i wymieszaj z jogurtem, resztą czosnku i koperku.',
      'Podawaj klopsiki z kaszą, polane sosem jogurtowym.',
    ],
    photo:
      'Browned turkey meatballs on a bed of buckwheat groats, topped with a creamy grated cucumber and yogurt sauce flecked with dill',
  },
  // ── Keto i low-carb ──
  {
    plan: 'OB-176',
    title: 'Udka z kurczaka w sosie musztardowym z fasolką',
    description:
      'Udka z kurczaka z chrupiącą skórką upieczone w piekarniku i podane w kremowym sosie ze śmietanki i musztardy z tymiankiem. Do tego fasolka szparagowa z masłem — sycący obiad keto bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    equipment: ['OVEN'],
    ingredients: [
      ['udko z kurczaka', 600, 'g'],
      ['musztarda', 30, 'g'],
      ['śmietanka 30', 100, 'ml'],
      ['czosnek', 2, 'szt'],
      ['tymianek suszony', 1, 'g'],
      ['fasolka szparagowa', 300, 'g'],
      ['masło', 10, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Udka osusz, natrzyj solą, pieprzem i tymiankiem, ułóż skórą do góry w naczyniu żaroodpornym.',
      'Piecz udka 35–40 minut, aż skórka będzie chrupiąca, a sok przy kości przejrzysty.',
      'Fasolkę obierz z końcówek i gotuj w osolonej wodzie 7 minut, odcedź i wymieszaj z masłem.',
      'Zlej tłuszcz z naczynia do rondelka, dodaj przeciśnięty czosnek i podsmaż 30 sekund. Wlej śmietankę, dodaj musztardę i gotuj 3 minuty, aż sos zgęstnieje.',
      'Podawaj udka polane sosem musztardowym, z fasolką obok.',
    ],
    photo:
      'Roasted chicken thighs with crispy golden skin in creamy pale-yellow mustard sauce with thyme, beside buttered green beans',
  },
  {
    plan: 'OB-177',
    title: 'Zapiekanka z kalafiora z mięsem mielonym i serem',
    description:
      'Różyczki kalafiora przełożone mięsem mielonym duszonym z cebulą, czosnkiem i odrobiną passaty, zapieczone pod warstwą śmietanki i cheddaru. Sycąca zapiekanka keto, która zastępuje lasagne.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['kalafior', 500, 'g'],
      ['wołowina mielona', 300, 'g'],
      ['cebula', 50, 'g'],
      ['czosnek', 2, 'szt'],
      ['passata pomidorowa', 100, 'ml'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 2, 'g'],
      ['śmietanka 30', 80, 'ml'],
      ['ser cheddar', 80, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Kalafior podziel na różyczki i gotuj w osolonej wodzie 5 minut, odcedź i dobrze osusz.',
      'Na oliwie zeszklij posiekaną cebulę, dodaj czosnek i mięso, smaż 8 minut, rozbijając grudki. Wlej passatę, dodaj oregano, sól i pieprz, duś 5 minut.',
      'W naczyniu żaroodpornym ułóż połowę kalafiora, na nim mięso, a na wierzchu resztę kalafiora.',
      'Polej śmietanką i posyp startym cheddarem.',
      'Zapiekaj 20 minut, aż ser się rozpuści i zarumieni. Odstaw na 5 minut przed krojeniem.',
    ],
    photo:
      'A square portion of cauliflower bake showing layers of cauliflower florets and tomato-rich minced beef under a bubbling golden browned cheddar crust',
  },
  {
    plan: 'OB-178',
    title: 'Karkówka z grilla z sałatką z ogórka',
    description:
      'Plastry karkówki w marynacie z czosnku, papryki i majeranku, upieczone na grillu ogrodowym, aż są soczyste i przypieczone. Do tego chłodna sałatka z ogórka ze śmietaną i koperkiem — klasyk majówki w wersji keto.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['karkówka', 450, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 3, 'g'],
      ['majeranek', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['ogórek', 300, 'g'],
      ['śmietana 18', 80, 'g'],
      ['koperek', 10, 'g'],
    ],
    steps: [
      'Karkówkę pokrój w plastry grubości 1,5 cm i lekko rozbij. Natrzyj oliwą wymieszaną z przeciśniętym czosnkiem, papryką, majerankiem i pieprzem, odstaw do lodówki na co najmniej 1 godzinę.',
      'Rozgrzej grill ogrodowy (węglowy, gazowy albo elektryczny) do wysokiej temperatury i natłuść ruszt.',
      'Posól mięso tuż przed grillowaniem i grilluj po 5–6 minut z każdej strony, aż będzie przypieczone i dopieczone w środku. Na patelni grillowej smaż plastry na średnim ogniu po 6–7 minut z każdej strony.',
      'Ogórek pokrój w cienkie plasterki, wymieszaj ze śmietaną, posiekanym koperkiem i szczyptą pieprzu.',
      'Odstaw karkówkę na 3 minuty i podawaj z sałatką z ogórka.',
    ],
    photo:
      'Chargrilled paprika-rubbed pork neck steaks with dark grill marks, next to a creamy cucumber salad with sour cream and fresh dill',
  },
  {
    plan: 'OB-179',
    title: 'Łosoś z sosem koperkowym i szparagami',
    description:
      'Filet z łososia usmażony na chrupiącą skórkę, podany z zielonymi szparagami z masłem i kremowym sosem koperkowym z cytryną. Wiosenny obiad keto gotowy w niecałe pół godziny.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING'],
    ingredients: [
      ['łosoś', 350, 'g'],
      ['szparagi', 400, 'g'],
      ['masło', 15, 'g'],
      ['śmietanka 30', 100, 'ml'],
      ['koperek', 15, 'g'],
      ['cytryna', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Szparagom odłam zdrewniałe końce. Łososia podziel na 2 kawałki, osusz i posyp solą i pieprzem.',
      'Połóż łososia skórą w dół na rozgrzanej suchej patelni i smaż 5 minut, odwróć i smaż jeszcze 2–3 minuty. Przełóż na talerz.',
      'Na tę samą patelnię dodaj masło i szparagi, smaż 5–6 minut, obracając, aż będą jasnozielone i chrupkie.',
      'W rondelku podgrzej śmietankę z przeciśniętym czosnkiem, gotuj 2 minuty, zdejmij z ognia i wmieszaj posiekany koperek oraz 1 łyżkę soku z cytryny.',
      'Podawaj łososia ze szparagami, polanego sosem koperkowym, z plasterkiem cytryny.',
    ],
    photo:
      'Pan-seared salmon fillet with crispy skin on bright green asparagus spears, drizzled with creamy dill sauce and a lemon slice',
  },
  {
    plan: 'OB-180',
    title: 'Makaron z cukinii z pesto i kurczakiem',
    description:
      'Spaghetti z cukinii krótko podsmażone i wymieszane z pesto bazyliowym, pomidorkami i plastrami złocistego kurczaka, posypane parmezanem. Lekki, wysokobiałkowy obiad keto w 25 minut.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PASTA',
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['cukinia', 600, 'g'],
      ['pesto bazyliowe', 50, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['ser parmezan', 20, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['czosnek', 1, 'szt'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Cukinię pokrój spiralizerem albo obieraczką do julienne w długie nitki. Pomidorki przekrój na połówki.',
      'Kurczaka przekrój wzdłuż na cieńsze płaty, posyp solą i pieprzem i smaż na oliwie po 4–5 minut z każdej strony. Odstaw i pokrój w paski.',
      'Na tę samą patelnię wrzuć przeciśnięty czosnek i nitki cukinii, smaż 2–3 minuty, tylko aż zmiękną.',
      'Zdejmij z ognia, wmieszaj pesto i pomidorki.',
      'Przełóż na talerze, ułóż kurczaka i posyp startym parmezanem.',
    ],
    photo:
      'Green zucchini noodles coated in basil pesto with halved cherry tomatoes, golden sliced chicken breast and grated parmesan',
  },
  {
    plan: 'OB-181',
    title: 'Pieczeń wieprzowa z kapustą kiszoną',
    description:
      'Łopatka wieprzowa powoli pieczona na łożu z kapusty kiszonej i świeżej z kminkiem, majerankiem i zielem angielskim, aż mięso rozpada się pod widelcem. Zimowy, rozgrzewający obiad keto bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 130,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['łopatka wieprzowa', 500, 'g'],
      ['kapusta kiszona', 150, 'g'],
      ['kapusta biała', 250, 'g'],
      ['cebula', 60, 'g'],
      ['smalec', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['majeranek', 2, 'g'],
      ['kminek', 2, 'g'],
      ['liść laurowy', 1, 'g'],
      ['ziele angielskie', 1, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 170°C (góra–dół). Łopatkę natrzyj przeciśniętym czosnkiem, majerankiem, solą i pieprzem.',
      'Na smalcu w brytfannie obsmaż mięso ze wszystkich stron na mocnym ogniu, po 2 minuty na stronę. Wyjmij.',
      'Na tym samym tłuszczu podsmaż pokrojoną cebulę, dodaj odciśniętą, posiekaną kapustę kiszoną i poszatkowaną kapustę białą, kminek, liść laurowy, ziele angielskie i 150 ml wody. Wymieszaj.',
      'Połóż łopatkę na kapuście, przykryj pokrywką i piecz w piekarniku 100 minut, w połowie polewając mięso sosem.',
      'Zdejmij pokrywkę na ostatnie 15 minut, żeby mięso się zarumieniło. Odstaw na 10 minut, pokrój w plastry i podawaj z kapustą.',
    ],
    photo:
      'Thick slices of slow-roasted pork shoulder with a browned crust resting on braised sauerkraut and cabbage with caraway seeds',
  },
  {
    plan: 'OB-182',
    title: 'Sałatka cobb z kurczakiem, jajkiem, boczkiem i awokado',
    description:
      'Amerykańska sałatka ułożona w rzędach: grillowany kurczak, jajko na twardo, chrupiący boczek, awokado, pomidorki i gorgonzola na sałacie rzymskiej, z musztardowym winegretem. Sycąca, pełna białka i bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'SALAD',
    ingredients: [
      ['filet z kurczaka', 300, 'g'],
      ['jajko', 2, 'szt'],
      ['boczek', 50, 'g'],
      ['awokado', 1, 'szt'],
      ['sałata rzymska', 150, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['ser gorgonzola', 40, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['ocet winny', 10, 'ml'],
      ['musztarda', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Jajka ugotuj na twardo przez 9 minut, przelej zimną wodą, obierz i pokrój w ćwiartki.',
      'Boczek pokrój w paski i wysmaż na suchej patelni na chrupko, odsącz na ręczniku papierowym.',
      'Kurczaka posyp pieprzem i smaż na tłuszczu z boczku po 5–6 minut z każdej strony, odstaw na 3 minuty i pokrój w kostkę.',
      'Wymieszaj oliwę, ocet i musztardę na winegret.',
      'Na posiekanej sałacie ułóż w rzędach kurczaka, jajka, boczek, awokado i połówki pomidorków, pokruszoną gorgonzolę. Polej winegretem tuż przed podaniem.',
    ],
    photo:
      'Cobb salad arranged in neat rows on romaine: diced chicken, quartered boiled eggs, crispy bacon, avocado, halved cherry tomatoes and crumbled gorgonzola, drizzled with mustard vinaigrette',
    vessel: 'bowl',
  },
  {
    plan: 'OB-183',
    title: 'Pulpety wołowe w sosie pomidorowym z cukinią',
    description:
      'Soczyste pulpety z wołowiny z parmezanem i czosnkiem, duszone w gęstym sosie pomidorowym z bazylią, podane na podsmażonej cukinii zamiast makaronu. Rozgrzewający obiad keto bez glutenu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['wołowina mielona', 400, 'g'],
      ['jajko', 1, 'szt'],
      ['ser parmezan', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['cebula', 40, 'g'],
      ['passata pomidorowa', 300, 'ml'],
      ['cukinia', 300, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['oregano', 2, 'g'],
      ['bazylia', 10, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wymieszaj mięso z jajkiem, startym parmezanem, 1 przeciśniętym ząbkiem czosnku, solą i pieprzem. Uformuj 10 pulpetów.',
      'Obsmaż pulpety na połowie oliwy ze wszystkich stron, 5 minut. Dodaj posiekaną cebulę i resztę czosnku, smaż 1 minutę.',
      'Wlej passatę, dodaj oregano, przykryj i duś na małym ogniu 20 minut.',
      'Cukinię pokrój w półplasterki i podsmaż na reszcie oliwy 4–5 minut, aż się lekko zrumieni.',
      'Podawaj pulpety w sosie na cukinii, posypane porwaną bazylią.',
    ],
    photo:
      'Browned beef meatballs in thick rich tomato sauce with fresh basil leaves, over golden sautéed zucchini half-moons',
  },
  {
    plan: 'OB-184',
    title: 'Stek z masłem ziołowym i pieczarkami',
    description:
      'Stek z polędwicy wołowej usmażony na mocno rozgrzanej patelni, podany z plasterkiem masła z natką i czosnkiem, podsmażanymi pieczarkami i rukolą. Obiad od święta w wersji keto, gotowy w 30 minut.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    ingredients: [
      ['polędwica wołowa', 400, 'g'],
      ['masło', 30, 'g'],
      ['natka pietruszki', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['tymianek suszony', 1, 'g'],
      ['pieczarka', 300, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['rukola', 60, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Wyjmij mięso z lodówki 20 minut przed smażeniem. Miękkie masło wymieszaj z posiekaną natką, 1 przeciśniętym ząbkiem czosnku i szczyptą soli, schłodź.',
      'Pieczarki pokrój w plastry i smaż na połowie oliwy 6–7 minut, aż odparują i się zrumienią. Dopraw tymiankiem, resztą czosnku i pieprzem.',
      'Steki osusz, natrzyj resztą oliwy, solą i pieprzem. Smaż na mocno rozgrzanej patelni po 3 minuty z każdej strony (średnio wysmażone).',
      'Odstaw steki na 5 minut na deskę.',
      'Podawaj z masłem ziołowym na wierzchu, pieczarkami i rukolą.',
    ],
    photo:
      'Seared beef tenderloin steak with a melting pat of herb butter, golden sautéed mushrooms and fresh rocket leaves',
  },
  {
    plan: 'OB-185',
    title: 'Tofu z warzywami w sosie orzechowym',
    description:
      'Chrupiące kostki tofu z brokułem, cukinią i papryką w kremowym sosie z masła orzechowego, imbiru, limonki i sosu sojowego. Wegański obiad keto z jednej patelni, sycący dzięki białku z soi.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tofu', 400, 'g'],
      ['brokuł', 250, 'g'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['masło orzechowe', 40, 'g'],
      ['sos sojowy', 20, 'ml'],
      ['limonka', 30, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej sezamowy', 15, 'ml'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Tofu odsącz, owiń ręcznikiem i dociśnij na 10 minut, potem pokrój w kostkę 2 cm.',
      'Smaż tofu na połowie oleju sezamowego 8 minut, obracając, aż będzie złote ze wszystkich stron. Przełóż na talerz.',
      'Na reszcie oleju smaż różyczki brokułu, pokrojoną cukinię i paprykę 5–6 minut, żeby zostały chrupkie.',
      'Wymieszaj masło orzechowe z sosem sojowym, sokiem z limonki, startym imbirem, przeciśniętym czosnkiem i 60 ml ciepłej wody.',
      'Wlej sos do warzyw, dodaj tofu i podgrzewaj 2 minuty, mieszając. Podawaj posypane sezamem.',
    ],
    photo:
      'Golden crispy tofu cubes with broccoli florets, zucchini and red pepper in a glossy creamy peanut sauce sprinkled with sesame seeds',
    vessel: 'bowl',
  },
  // ── Święta i okazje ──
  {
    plan: 'OB-186',
    title: 'Kaczka pieczona z jabłkami i żurawiną',
    description:
      'Świąteczna kaczka natarta majerankiem i czosnkiem, pieczona powoli z kwaśnymi jabłkami, aż skórka jest chrupiąca, a mięso miękkie. Podana z żurawiną duszoną z miodem — polski klasyk na Boże Narodzenie.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 200,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['kaczka', 2000, 'g'],
      ['jabłko', 800, 'g'],
      ['żurawina', 200, 'g'],
      ['miód', 40, 'g'],
      ['majeranek', 5, 'g'],
      ['czosnek', 5, 'szt'],
      ['sól', 6, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Kaczkę umyj, osusz, odetnij nadmiar tłuszczu przy kuprze. Natrzyj w środku i na zewnątrz solą, pieprzem, majerankiem i przeciśniętym czosnkiem, odstaw na co najmniej 1 godzinę.',
      'Nagrzej piekarnik do 160°C (góra–dół). Połowę jabłek pokrój w ćwiartki i napełnij nimi kaczkę, resztę jabłek ułóż wokół w brytfannie.',
      'Piecz kaczkę piersią do góry pod przykryciem 1,5 godziny, co 30 minut polewając wytopionym tłuszczem.',
      'Zdejmij przykrycie, zwiększ temperaturę do 200°C i piecz jeszcze 25–30 minut, aż skórka będzie ciemnozłota i chrupiąca.',
      'W tym czasie duś żurawinę z miodem i 2 łyżkami wody 8–10 minut, aż owoce popękają.',
      'Odstaw kaczkę na 10 minut, podziel na porcje i podawaj z pieczonymi jabłkami i żurawiną.',
    ],
    photo:
      'A portion of roast duck, a leg and slices of breast with glossy crisp mahogany skin, with soft baked apple quarters and a spoonful of glistening red honey-stewed cranberries',
  },
  {
    plan: 'OB-187',
    title: 'Rolada wołowa z ogórkiem kiszonym i kluskami śląskimi',
    description:
      'Zrazy wołowe zwinięte z musztardą, boczkiem, ogórkiem kiszonym i cebulą, duszone do miękkości w ciemnym sosie. Podane z domowymi kluskami śląskimi z dziurką — świąteczny obiad jak u babci.',
    mealType: 'LUNCH',
    difficulty: 'HARD',
    prepTimeMinutes: 150,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['wołowina', 600, 'g'],
      ['musztarda', 20, 'g'],
      ['boczek', 60, 'g'],
      ['ogórek kiszony', 120, 'g'],
      ['cebula', 150, 'g'],
      ['mąka pszenna', 15, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['liść laurowy', 1, 'g'],
      ['ziele angielskie', 1, 'g'],
      ['ziemniak', 800, 'g'],
      ['mąka ziemniaczana', 150, 'g'],
      ['jajko', 1, 'szt'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Wołowinę pokrój w 4 plastry w poprzek włókien i rozbij tłuczkiem na cienko. Posmaruj musztardą, oprósz pieprzem, ułóż paski boczku, ćwiartki ogórka i połowę cebuli w piórkach.',
      'Zwiń rolady ciasno, spnij wykałaczkami, obtocz w mące i obsmaż na oleju ze wszystkich stron, 6–8 minut.',
      'Dodaj resztę cebuli, liść laurowy, ziele angielskie i 400 ml gorącej wody. Duś pod przykryciem na małym ogniu 90 minut, aż mięso będzie miękkie, uzupełniając wodę.',
      'W tym czasie ugotuj obrane ziemniaki w osolonej wodzie do miękkości, odcedź i przeciśnij przez praskę. Ostudź.',
      'Wyrównaj ziemniaki w misce, wyjmij ćwiartkę i w to miejsce wsyp mąkę ziemniaczaną. Dodaj jajko i szczyptę soli, zagnieć gładkie ciasto.',
      'Formuj kulki wielkości orzecha włoskiego, spłaszcz je i zrób kciukiem wgłębienie. Gotuj partiami w osolonej wodzie 2–3 minuty od wypłynięcia.',
      'Wyjmij wykałaczki, dopraw sos solą i pieprzem. Podawaj rolady z kluskami polanymi sosem.',
    ],
    photo:
      'A braised beef roulade cut in half to show the pickle, bacon and onion filling, in dark glossy gravy, with round Silesian potato dumplings with a dimple',
  },
  {
    plan: 'OB-188',
    title: 'Indyk pieczony z nadzieniem z żurawiną',
    description:
      'Udziec z indyka nadziany farszem z bułki, masła, suszonej żurawiny, jabłka i majeranku, pieczony do złotej skórki. Podany z sosem żurawinowym — świąteczna pieczeń, która starczy dla całej rodziny.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 170,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['udziec z indyka', 1500, 'g'],
      ['bułka', 150, 'g'],
      ['żurawina suszona', 60, 'g'],
      ['jabłko', 150, 'g'],
      ['cebula', 100, 'g'],
      ['masło', 50, 'g'],
      ['jajko', 2, 'szt'],
      ['natka pietruszki', 15, 'g'],
      ['majeranek', 3, 'g'],
      ['bulion drobiowy', 200, 'ml'],
      ['sos żurawinowy', 120, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Udziec natrzyj solą, pieprzem i majerankiem, odstaw na 30 minut. Nagrzej piekarnik do 180°C (góra–dół).',
      'Bułkę pokrój w kostkę i namocz w 100 ml bulionu. Na połowie masła zeszklij posiekaną cebulę, dodaj starte kwaśne jabłko i smaż 3 minuty.',
      'Wymieszaj odciśniętą bułkę z cebulą i jabłkiem, jajkami, żurawiną, posiekaną natką i szczyptą pieprzu.',
      'Natnij udziec wzdłuż kości, tworząc głęboką kieszeń, napełnij ją nadzieniem i spnij wykałaczkami. Nadmiar farszu przełóż do małego natłuszczonego naczynia.',
      'Ułóż udziec w brytfannie, posmaruj resztą masła, podlej resztą bulionu i piecz przykryty 80 minut.',
      'Odkryj, dołóż naczynie z farszem i piecz jeszcze 30–40 minut, polewając sosem z brytfanny, aż skórka się zezłoci.',
      'Odstaw indyka na 15 minut, pokrój w plastry z nadzieniem i podawaj z sosem żurawinowym.',
    ],
    photo:
      'Two thick slices of golden roast turkey leg with a ring of bread, apple and dried cranberry stuffing inside, glossy pan juices and a spoonful of red cranberry sauce',
  },
  {
    plan: 'OB-189',
    title: 'Barszcz biały z jajkiem i kiełbasą',
    description:
      'Wielkanocny barszcz biały na zakwasie, gotowany z białą kiełbasą, ziemniakami, czosnkiem i majerankiem, zabielony śmietaną i doprawiony chrzanem. Podany z połówkami jajka na twardo — smak świątecznego stołu.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'SOUP',
    occasions: ['EASTER'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['kiełbasa biała', 250, 'g'],
      ['zakwas na żurek', 400, 'ml'],
      ['ziemniak', 500, 'g'],
      ['jajko', 4, 'szt'],
      ['czosnek', 3, 'szt'],
      ['majeranek', 3, 'g'],
      ['liść laurowy', 1, 'g'],
      ['ziele angielskie', 1, 'g'],
      ['chrzan tarty', 30, 'g'],
      ['śmietana 18', 100, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kiełbasę włóż do garnka z 1 l zimnej wody, dodaj liść laurowy i ziele angielskie, gotuj na małym ogniu 20 minut. Wyjmij kiełbasę.',
      'Do wywaru wrzuć obrane ziemniaki pokrojone w kostkę i gotuj 12 minut.',
      'W tym czasie ugotuj jajka na twardo przez 9 minut, ostudź i obierz.',
      'Wlej zakwas, dodaj przeciśnięty czosnek i majeranek, zagotuj i gotuj 5 minut. Wmieszaj chrzan.',
      'Śmietanę zahartuj kilkoma łyżkami gorącej zupy i wlej do garnka. Dopraw pieprzem.',
      'Kiełbasę pokrój w plastry i włóż do zupy. Podawaj z połówkami jajek.',
    ],
    photo:
      'Creamy pale white Easter sour soup with sliced white sausage, potato cubes and halved hard-boiled eggs, sprinkled with marjoram',
    vessel: 'bowl',
  },
  {
    plan: 'OB-190',
    title: 'Szaszłyki z kurczaka i warzyw z grilla',
    description:
      'Kawałki kurczaka w cytrynowej marynacie z czosnkiem i oregano, nadziane na patyczki na zmianę z papryką, czerwoną cebulą i pieczarkami, upieczone na grillu ogrodowym. Lekkie i pełne białka.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 60,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['filet z kurczaka', 450, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['papryka żółta', 160, 'g'],
      ['cebula czerwona', 100, 'g'],
      ['pieczarka', 150, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['cytryna', 30, 'g'],
      ['czosnek', 2, 'szt'],
      ['papryka słodka mielona', 3, 'g'],
      ['oregano', 2, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wymieszaj oliwę, sok z cytryny, przeciśnięty czosnek, paprykę, oregano, sól i pieprz. Kurczaka pokrój w kostkę 3 cm i obtocz w marynacie, odstaw na 30 minut.',
      'Papryki pokrój w kwadraty, cebulę w ósemki, pieczarki zostaw w całości. Drewniane patyczki namocz w wodzie na 20 minut.',
      'Nadziewaj na patyczki na zmianę kurczaka i warzywa, warzywa posmaruj resztą marynaty.',
      'Grilluj szaszłyki na rozgrzanym grillu ogrodowym (węglowym, gazowym albo elektrycznym) 12–14 minut, obracając co 3 minuty, aż kurczak będzie dopieczony. Na patelni grillowej smaż je na średnim ogniu 14–16 minut, często obracając.',
    ],
    photo:
      'Grilled chicken skewers alternating with charred red and yellow pepper, red onion and whole mushrooms, glistening with oregano and paprika marinade',
  },
  // ── Grill i majówka ──
  {
    plan: 'OB-191',
    title: 'Żeberka z grilla w sosie BBQ z kukurydzą',
    description:
      'Żeberka wieprzowe najpierw podgotowane z przyprawami do miękkości, a potem przypieczone na grillu w lepkim sosie barbecue. Do tego kolby kukurydzy z wędzoną papryką — amerykański klasyk bez glutenu i bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 100,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['żeberko wieprzowe', 650, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 3, 'szt'],
      ['liść laurowy', 1, 'g'],
      ['ziele angielskie', 1, 'g'],
      ['sos barbecue', 80, 'g'],
      ['kukurydza', 300, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['papryka wędzona mielona', 3, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Żeberka podziel na kawałki po 2–3 kości. Włóż do garnka z cebulą w ćwiartkach, czosnkiem, liściem laurowym, zielem angielskim i solą, zalej wodą i gotuj na małym ogniu 60 minut.',
      'Wyjmij żeberka, osusz i posmaruj połową sosu barbecue wymieszanego z pieprzem.',
      'Kolby kukurydzy posmaruj olejem wymieszanym z wędzoną papryką.',
      'Grilluj żeberka i kukurydzę na rozgrzanym grillu ogrodowym (węglowym, gazowym albo elektrycznym) 12–15 minut, obracając i smarując żeberka resztą sosu, aż się skarmelizują, a kukurydza przypiecze. Na patelni grillowej: żeberka 8–10 minut, kukurydza 12–15 minut, często obracając.',
      'Podawaj od razu, gdy sos jest jeszcze lepki.',
    ],
    photo:
      'Sticky glazed pork ribs with dark caramelized barbecue sauce and grill marks next to charred corn on the cob dusted with smoked paprika',
  },
  {
    plan: 'OB-192',
    title: 'Pierś z kurczaka z grilla z cukinią i sosem jogurtowym',
    description:
      'Pierś z kurczaka w ziołach prowansalskich i cytrynie, upieczona na grillu razem z plastrami cukinii i pomidorkami. Podana z chłodnym sosem jogurtowym z miętą i czosnkiem — lekki obiad na majówkę.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['filet z kurczaka', 350, 'g'],
      ['cukinia', 400, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['cytryna', 30, 'g'],
      ['zioła prowansalskie', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['jogurt naturalny', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['mięta', 5, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kurczaka przekrój wzdłuż na cieńsze płaty. Natrzyj połową oliwy, sokiem z połowy cytryny, ziołami, papryką, 1 przeciśniętym ząbkiem czosnku, solą i pieprzem, odstaw na 20 minut.',
      'Cukinię pokrój wzdłuż w plastry grubości 1 cm i posmaruj resztą oliwy.',
      'Grilluj kurczaka na rozgrzanym grillu ogrodowym (węglowym, gazowym albo elektrycznym) po 5–6 minut z każdej strony, a cukinię i pomidorki na tacce po 3–4 minuty. Na patelni grillowej smaż kurczaka po 6 minut z każdej strony, a warzywa po 3 minuty.',
      'Jogurt wymieszaj z resztą czosnku, posiekaną miętą, resztą soku z cytryny i szczyptą soli.',
      'Pokrój kurczaka w plastry i podawaj z cukinią, pomidorkami i sosem jogurtowym.',
    ],
    photo:
      'Sliced grilled herb chicken breast with char marks, grilled lengthwise zucchini slices and blistered cherry tomatoes with a dollop of white mint yogurt sauce',
  },
  {
    plan: 'OB-193',
    title: 'Udka z kurczaka z grilla w marynacie paprykowej',
    description:
      'Udka z kurczaka w czerwonej marynacie z papryki słodkiej i wędzonej, czosnku i cytryny, upieczone na grillu na chrupiącą skórkę. Do tego młode ziemniaki z rusztu i sałatka z pomidorów z cebulą.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['udko z kurczaka', 700, 'g'],
      ['papryka słodka mielona', 5, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['koncentrat pomidorowy', 20, 'g'],
      ['czosnek', 3, 'szt'],
      ['cytryna', 30, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['ziemniak młody', 400, 'g'],
      ['pomidor', 250, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wymieszaj obie papryki, koncentrat, przeciśnięty czosnek, sok z cytryny, połowę oleju, sól i pieprz. Natrzyj udka marynatą, także pod skórą, i odstaw do lodówki na co najmniej 1 godzinę.',
      'Młode ziemniaki wyszoruj, ugotuj w osolonej wodzie 12 minut, odcedź, przekrój na połówki i posmaruj resztą oleju.',
      'Grilluj udka na rozgrzanym grillu ogrodowym (węglowym, gazowym albo elektrycznym) w pośredniej strefie 30–35 minut, obracając co 5 minut, a na koniec 2–3 minuty nad żarem dla chrupiącej skórki. Ziemniaki przypiecz na ruszcie 6–8 minut. Na patelni grillowej smaż udka pod przykryciem 30 minut na średnim ogniu, często obracając.',
      'Pomidory pokrój w ósemki, cebulę w cienkie piórka, wymieszaj z pieprzem.',
      'Podawaj udka z ziemniakami i sałatką z pomidorów.',
    ],
    photo:
      'Grilled chicken thighs with deep red paprika marinade and crispy charred skin, halved grilled baby potatoes and a tomato-red onion salad',
  },
  {
    plan: 'OB-194',
    title: 'Pstrąg z grilla z masłem czosnkowym',
    description:
      'Cały pstrąg nadziany cytryną i natką, upieczony na grillu w koszyku do ryb, aż skórka jest chrupiąca, a mięso delikatne. Podany z roztopionym masłem czosnkowym i młodymi ziemniakami z koperkiem.',
    mealType: 'LUNCH',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['pstrąg', 600, 'g'],
      ['cytryna', 60, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['masło', 40, 'g'],
      ['czosnek', 3, 'szt'],
      ['ziemniak młody', 500, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Młode ziemniaki wyszoruj i gotuj w osolonej wodzie 18–20 minut.',
      'Oczyszczone pstrągi osusz, natnij skórę 3 razy z każdej strony, posól i popieprz w środku i na zewnątrz. Włóż do środka plasterki połowy cytryny i połowę natki, posmaruj olejem.',
      'Grilluj pstrągi w koszyku do ryb na rozgrzanym grillu ogrodowym (węglowym, gazowym albo elektrycznym) po 6–7 minut z każdej strony, aż mięso będzie odchodzić od ości. Na patelni grillowej smaż je po 6–7 minut z każdej strony na średnim ogniu.',
      'Roztop masło z przeciśniętym czosnkiem i resztą posiekanej natki, nie dopuszczając do zrumienienia.',
      'Podawaj pstrągi polane masłem czosnkowym, z ziemniakami posypanymi koperkiem i ćwiartkami cytryny.',
    ],
    photo:
      'Whole grilled trout with crisp striped skin, drizzled with garlic parsley butter, with baby potatoes sprinkled with dill and lemon wedges',
  },
  {
    plan: 'OB-195',
    title: 'Kaszanka z grilla z cebulą i chlebem',
    description:
      'Kaszanka upieczona na grillu w tacce, aż skórka zrobi się chrupiąca, podana ze słodką cebulą duszoną z majerankiem, pomidorami i pajdą żytniego chleba. Prosty, swojski klasyk polskiej majówki bez nabiału.',
    mealType: 'LUNCH',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE'],
    equipment: ['GRILL'],
    ingredients: [
      ['kaszanka', 220, 'g'],
      ['cebula', 250, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['majeranek', 2, 'g'],
      ['chleb żytni', 80, 'g'],
      ['pomidor', 200, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Kaszankę natnij na ukos co 2 cm, nie przecinając do końca.',
      'Cebulę pokrój w grube piórka, wymieszaj z olejem i majerankiem i przełóż do aluminiowej tacki.',
      'Postaw tackę z cebulą na rozgrzanym grillu ogrodowym (węglowym, gazowym albo elektrycznym) i piecz 10 minut, mieszając. Dołóż kaszankę na cebulę i grilluj jeszcze 12–15 minut, obracając, aż skórka będzie chrupiąca. Na patelni grillowej smaż cebulę 10 minut, a kaszankę 10–12 minut pod przykryciem.',
      'Kromki chleba opiecz na ruszcie po minucie z każdej strony. Pomidory pokrój w plastry i posyp pieprzem.',
      'Podawaj kaszankę na cebuli z chlebem i pomidorami.',
    ],
    photo:
      'Grilled black pudding sausage with crispy split skin on a bed of soft golden onions, with toasted rye bread slices and tomato slices',
  },
];
