/**
 * Katalog 1000 — część PR: przekąski PR-001 … PR-040 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [
  {
    name: 'kukurydza do popcornu',
    category: 'zboza-i-makarony',
    allergens: [],
    dietTags: ['GRAIN'],
    note: 'Suche ziarno do prażenia (Lidl, Biedronka — paczka 400–500 g); popcorn gotowy to osobny składnik.',
    nutrition: {
      unit: 'g',
      kcal: 375,
      protein: 12.9,
      carbs: 63.3,
      sugars: 0.9,
      fat: 4.5,
      saturatedFat: 0.6,
      fiber: 14.5,
      sodiumMg: 8,
    },
  },
  {
    name: 'kiełbaska koktajlowa',
    category: 'mieso',
    allergens: ['mustard', 'soy', 'celery'],
    dietTags: ['MEAT', 'LEGUME', 'PROCESSED'],
    note: 'Małe kiełbaski party/koktajlowe z lady chłodniczej (Biedronka, Lidl, Makro).',
    nutrition: {
      unit: 'g',
      kcal: 290,
      protein: 12,
      carbs: 2,
      sugars: 1,
      fat: 26,
      saturatedFat: 10,
      fiber: 0,
      sodiumMg: 800,
    },
  },
];

export const DEFS: Def[] = [
  // ─── Impreza i Sylwester ───
  {
    plan: 'PR-001',
    title: 'Taquitos z kurczakiem',
    description:
      'Ciasno zwinięte tortille kukurydziane z pikantnym kurczakiem i roztopionym cheddarem, zapieczone w airfryerze na chrupko. Meksykańska przekąska na imprezę, którą je się palcami i macza w salsie.',
    mealType: 'SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 4,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['tortilla kukurydziana', 8, 'szt'],
      ['filet z kurczaka', 300, 'g'],
      ['ser cheddar', 60, 'g'],
      ['cebula', 60, 'g'],
      ['czosnek', 1, 'szt'],
      ['kmin rzymski', 2, 'g'],
      ['papryka wędzona mielona', 3, 'g'],
      ['salsa pomidorowa', 120, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['limonka', 30, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Pokrój filet z kurczaka w drobną kostkę, cebulę posiekaj, a czosnek przeciśnij przez praskę.',
      'Rozgrzej połowę oleju na patelni i smaż kurczaka z cebulą 6–8 minut. Dodaj czosnek, kmin rzymski, wędzoną paprykę i sól, smaż jeszcze minutę.',
      'Zdejmij farsz z ognia, wmieszaj 3 łyżki salsy i zetrzyj do niego cheddar.',
      'Podgrzej tortille w mikrofalówce przez 20 sekund, żeby się nie łamały. Nałóż farsz na brzeg każdej, zwiń ciasno i ułóż złączeniem w dół.',
      'Posmaruj taquitos resztą oleju i piecz w airfryerze w 200°C przez 8–10 minut, aż będą złote i chrupiące. W piekarniku: 220°C, termoobieg, 12–15 minut.',
      'Podawaj od razu z resztą salsy i ćwiartkami limonki.',
    ],
    photo:
      'Two golden crispy rolled corn taquitos with chicken and cheddar filling peeking out of the ends, with a small mound of red tomato salsa and a lime wedge on the side',
  },
  {
    plan: 'PR-002',
    title: 'Tortilla chipsy z guacamole',
    description:
      'Domowe chipsy z tortilli kukurydzianych wypieczone w airfryerze i świeże guacamole z awokado, pomidora i limonki. Chrupiąca meksykańska przekąska na imprezę, lżejsza od chipsów ze sklepu.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 4,
    cuisine: 'MEXICAN',
    dishType: 'CRUNCHY',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['tortilla kukurydziana', 6, 'szt'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['awokado', 2, 'szt'],
      ['pomidor', 120, 'g'],
      ['cebula czerwona', 40, 'g'],
      ['limonka', 40, 'g'],
      ['kolendra', 10, 'g'],
      ['papryczka chili', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Posmaruj tortille cienko oliwą, posyp słodką papryką i szczyptą soli, a potem pokrój każdą na 8 trójkątów.',
      'Piecz trójkąty w airfryerze w 180°C przez 5–7 minut, w dwóch turach, potrząsając koszem w połowie. W piekarniku: 190°C, termoobieg, 8–10 minut na blasze.',
      'Rozgnieć miąższ awokado widelcem z sokiem z limonki i resztą soli.',
      'Pomidor pokrój w drobną kostkę, cebulę, chili i kolendrę posiekaj, czosnek przeciśnij przez praskę. Wmieszaj wszystko do awokado.',
      'Przełóż guacamole do miseczki i podawaj z ostudzonymi chipsami.',
    ],
    photo:
      'A mound of chunky green guacamole with diced tomato, red onion, chili and cilantro on one side of the board, with crispy golden paprika corn tortilla chips arranged beside it',
    vessel: 'board',
  },
  {
    plan: 'PR-003',
    title: 'Tartaletki z kozim serem i żurawiną',
    description:
      'Chrupiące koszyczki z ciasta francuskiego z kremowym kozim serem, sosem żurawinowym, orzechami i kroplą miodu. Elegancka świąteczna przekąska na przyjęcie, gotowa w pół godziny.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'BITES',
    occasions: ['PARTY', 'CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['ciasto francuskie', 275, 'g'],
      ['ser kozi', 150, 'g'],
      ['sos żurawinowy', 60, 'g'],
      ['orzech włoski', 30, 'g'],
      ['miód', 15, 'g'],
      ['tymianek suszony', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Rozwiń ciasto francuskie i wytnij szklanką 12 kółek.',
      'Wyłóż kółkami foremkę na muffiny, dociśnij do ścianek i nakłuj dno widelcem. Piecz 10 minut, aż ciasto lekko się zezłoci.',
      'Pokrusz ser kozi, a orzechy włoskie posiekaj grubo.',
      'Do każdego koszyczka nałóż łyżeczkę sosu żurawinowego, kawałek sera i kilka orzechów. Piecz jeszcze 6–8 minut, aż ser zmięknie.',
      'Wyjmij tartaletki z foremki, skrop miodem i posyp tymiankiem. Podawaj ciepłe albo letnie.',
    ],
    photo:
      'Two golden puff pastry tartlets filled with glossy red cranberry sauce, soft goat cheese and chopped walnuts, drizzled with honey and sprinkled with thyme',
    vessel: 'board',
  },
  {
    plan: 'PR-004',
    title: 'Paluchy drożdżowe z sezamem',
    description:
      'Chrupiące na zewnątrz, lekko ciągnące w środku paluchy z ciasta drożdżowego na oliwie, obsypane sezamem. Robią się z kilku składników ze spiżarni i znikają z talerza na każdej imprezie.',
    mealType: 'SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    occasions: ['PARTY'],
    equipment: ['OVEN'],
    ingredients: [
      ['mąka pszenna', 300, 'g'],
      ['drożdże instant', 7, 'g'],
      ['cukier', 5, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['sól', 5, 'g'],
      ['sezam', 25, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z drożdżami, cukrem i solą. Wlej 180 ml ciepłej wody i 2 łyżki oliwy, zagnieć gładkie, elastyczne ciasto przez 8 minut.',
      'Przykryj miskę ściereczką i odstaw w ciepłe miejsce na 45 minut, aż ciasto podwoi objętość.',
      'Nagrzej piekarnik do 210°C (góra–dół). Podziel ciasto na 24 kawałki i rozwałkuj każdy dłońmi na wałek długości około 20 cm.',
      'Ułóż paluchy na blasze z papierem, posmaruj resztą oliwy wymieszaną z łyżką wody i obficie posyp sezamem.',
      'Piecz 14–16 minut, aż będą złociste i chrupiące. Ostudź na kratce.',
    ],
    photo:
      'Four golden crispy breadsticks coated in toasted sesame seeds, lying loosely side by side',
    vessel: 'board',
  },
  {
    plan: 'PR-005',
    title: 'Kulki mozzarelli w panierce',
    description:
      'Małe kulki mozzarelli w podwójnej chrupiącej panierce, które w środku ciągną się jak w pizzy. Z airfryera wychodzą złote bez głębokiego tłuszczu, a pomidorowy sos z bazylią dopełnia imprezową przekąskę.',
    mealType: 'SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['mozzarella', 250, 'g'],
      ['mąka pszenna', 30, 'g'],
      ['jajko', 2, 'szt'],
      ['bułka tarta', 70, 'g'],
      ['oregano', 1, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['passata pomidorowa', 150, 'ml'],
      ['czosnek', 1, 'szt'],
      ['bazylia suszona', 1, 'g'],
    ],
    steps: [
      'Odsącz mini kulki mozzarelli i osusz je dokładnie ręcznikiem papierowym.',
      'Przygotuj trzy miski: mąkę, roztrzepane jajka i bułkę tartą wymieszaną z oregano i słodką papryką. Obtocz każdą kulkę w mące, jajku i bułce, a potem jeszcze raz w jajku i bułce.',
      'Włóż panierowane kulki na 15 minut do zamrażarki, żeby ser nie wypłynął podczas pieczenia.',
      'Skrop kulki olejem i piecz w airfryerze w 200°C przez 6–8 minut, aż panierka się zrumieni. W piekarniku: 220°C, termoobieg, 10–12 minut na blasze z papierem.',
      'W tym czasie zagotuj passatę z przeciśniętym czosnkiem i bazylią, gotuj 5 minut na małym ogniu.',
      'Podawaj kulki od razu, z ciepłym sosem pomidorowym do maczania.',
    ],
    photo:
      'A few golden breaded mozzarella balls, one broken open with stretchy melted cheese, with a small pool of warm red tomato sauce on the side',
  },
  {
    plan: 'PR-006',
    title: 'Deska serów z owocami i orzechami',
    description:
      'Cztery sery o różnym charakterze — camembert, gouda, ser pleśniowy i kozi — z winogronami, gruszką, suszonymi figami, orzechami i miodem. Efektowna przekąska na przyjęcie, którą składa się w kwadrans.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'BITES',
    occasions: ['PARTY'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['ser camembert', 120, 'g'],
      ['ser gouda', 150, 'g'],
      ['ser pleśniowy', 100, 'g'],
      ['ser kozi', 100, 'g'],
      ['winogrono czerwone', 250, 'g'],
      ['gruszka', 150, 'g'],
      ['figi suszone', 60, 'g'],
      ['orzech włoski', 50, 'g'],
      ['miód', 30, 'g'],
    ],
    steps: [
      'Wyjmij sery z lodówki 30 minut przed podaniem, żeby nabrały pełnego smaku.',
      'Camembert pokrój w kliny, goudę w słupki, a ser pleśniowy i kozi w grube plastry.',
      'Umyj winogrona i podziel na małe kiście. Gruszkę pokrój w cienkie ósemki, figi przekrój na pół.',
      'Rozłóż sery na dużej desce w odstępach, a między nimi owoce, figi i orzechy włoskie.',
      'Przelej miód do małej miseczki, postaw na desce i podawaj od razu.',
    ],
    photo:
      'Wedges of camembert, gouda sticks, thick slices of blue cheese and goat cheese with small clusters of red grapes, thin pear slices, halved dried figs and walnuts, the goat cheese drizzled with honey',
    vessel: 'board',
  },
  {
    plan: 'PR-007',
    title: 'Samosy z ziemniakami i groszkiem',
    description:
      'Trójkątne pierożki z chrupiącego ciasta nadziewane ziemniakami z groszkiem, imbirem i garam masalą. Klasyczna indyjska przekąska, tu upieczona w airfryerze zamiast smażenia w głębokim oleju.',
    mealType: 'SNACK',
    difficulty: 'HARD',
    prepTimeMinutes: 70,
    servings: 4,
    cuisine: 'INDIAN',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['mąka pszenna', 200, 'g'],
      ['olej rzepakowy', 50, 'ml'],
      ['kminek', 1, 'g'],
      ['ziemniak', 400, 'g'],
      ['groszek mrożony', 100, 'g'],
      ['cebula', 80, 'g'],
      ['imbir', 10, 'g'],
      ['czosnek', 2, 'szt'],
      ['papryczka chili', 10, 'g'],
      ['garam masala', 4, 'g'],
      ['kmin rzymski', 2, 'g'],
      ['kurkuma', 1, 'g'],
      ['kolendra', 10, 'g'],
      ['cytryna', 20, 'g'],
      ['sól', 3, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z kminkiem, 1 g soli i 2 łyżkami oleju (30 ml), rozcieraj palcami na kruszonkę. Dolewaj około 80 ml zimnej wody i zagnieć twarde ciasto. Odstaw pod przykryciem na 30 minut.',
      'Ugotuj ziemniaki w mundurkach do miękkości (około 20 minut), obierz i pokrój w małą kostkę.',
      'Na łyżce oleju zeszklij posiekaną cebulę, dodaj starty imbir, czosnek, chili, kmin rzymski, kurkumę i garam masalę. Po minucie dodaj ziemniaki, groszek i resztę soli, smaż 3 minuty. Wmieszaj sok z cytryny i posiekaną kolendrę, ostudź.',
      'Podziel ciasto na 6 kul, rozwałkuj każdą na owal i przekrój na pół. Z każdej połówki zwiń stożek, sklej brzeg wodą, napełnij farszem i zlep górę w trójkąt.',
      'Posmaruj samosy resztą oleju i piecz w airfryerze w 180°C przez 12–15 minut, obracając w połowie, aż będą złote. W piekarniku: 200°C, termoobieg, 20–25 minut.',
      'Podawaj ciepłe, najlepiej od razu po upieczeniu.',
    ],
    photo:
      'Three golden crispy baked triangular samosas, one cut open to show yellow spiced potato and green pea filling flecked with cilantro',
  },
  {
    plan: 'PR-008',
    title: 'Popcorn domowy z masłem',
    description:
      'Prażony w garnku popcorn z prawdziwego ziarna, polany roztopionym masłem i lekko posolony. Bez dodatków z torebki do mikrofalówki — idealny na wieczór filmowy z dziećmi i na imprezę.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 3,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    occasions: ['PARTY'],
    ingredients: [
      ['kukurydza do popcornu', 80, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['masło', 25, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Wlej olej do dużego garnka z pokrywką, wrzuć 3 ziarna kukurydzy i rozgrzej na średnim ogniu, aż pękną.',
      'Wsyp resztę ziaren, przykryj i potrząsaj garnkiem co kilka sekund. Gdy strzelanie zwolni do 2–3 sekund przerwy (po około 3 minutach), zdejmij z ognia.',
      'W małym rondelku roztop masło.',
      'Przesyp popcorn do dużej miski, polej masłem, posól i wymieszaj rękami albo potrząsając miską.',
    ],
    photo:
      'A heap of fluffy white popcorn glistening with melted butter and sprinkled with salt',
    vessel: 'bowl',
  },
  {
    plan: 'PR-009',
    title: 'Pieczone ziemniaczki z dipem czosnkowym',
    description:
      'Małe ziemniaki pieczone w skórce z rozmarynem i papryką, chrupiące z wierzchu i miękkie w środku. Do maczania gęsty jogurtowy dip z czosnkiem i koperkiem — prosta przekąska na każdą imprezę.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'POTATOES',
    occasions: ['PARTY'],
    equipment: ['OVEN'],
    ingredients: [
      ['ziemniak', 800, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['rozmaryn suszony', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 3, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 10, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (termoobieg). Wyszoruj małe ziemniaki i przekrój większe na pół.',
      'Wymieszaj ziemniaki z oliwą, rozmarynem, papryką i 2 g soli, rozłóż na blasze przekrojem w dół.',
      'Piecz 35–40 minut, aż będą złote i miękkie w środku, w połowie pieczenia przemieszaj.',
      'Wymieszaj jogurt grecki z przeciśniętym czosnkiem, posiekanym koperkiem i resztą soli. Odstaw do lodówki.',
      'Podawaj gorące ziemniaczki z dipem czosnkowym.',
    ],
    photo:
      'Golden roasted baby potatoes with crispy paprika skins flecked with rosemary, with a generous dollop of thick white garlic yogurt dip with dill',
  },
  {
    plan: 'PR-010',
    title: 'Śliwki zawijane w boczku',
    description:
      'Suszone śliwki z migdałem w środku, owinięte plasterkiem wędzonego boczku i zapieczone na chrupko. Słodko-słona klasyka świątecznych i karnawałowych stołów, gotowa w pół godziny.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'BITES',
    occasions: ['CHRISTMAS', 'PARTY'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['śliwka suszona', 100, 'g'],
      ['migdał', 16, 'g'],
      ['boczek', 160, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C (góra–dół). Do każdej śliwki wciśnij jeden migdał.',
      'Pokrój plastry boczku na pół w poprzek, żeby wystarczyły na jedno owinięcie.',
      'Owiń każdą śliwkę kawałkiem boczku, zepnij wykałaczką i ułóż na blasze z papierem. Oprósz pieprzem.',
      'Piecz 15–18 minut, aż boczek się wytopi i zrumieni. Podawaj ciepłe.',
    ],
    photo:
      'Three crispy browned bacon-wrapped prunes, each held with a wooden toothpick, dusted with black pepper',
  },
  {
    plan: 'PR-011',
    title: 'Bagietka z masłem czosnkowym z grilla',
    description:
      'Nacięta bagietka przełożona masłem z czosnkiem i natką, zapieczona w folii na grillu, aż środek zrobi się miękki, a skórka chrupiąca. Obowiązkowy dodatek do majówki i ogrodowej imprezy.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    seasons: ['SPRING', 'SUMMER'],
    occasions: ['BARBECUE', 'PARTY'],
    equipment: ['GRILL'],
    ingredients: [
      ['bagietka', 250, 'g'],
      ['masło', 60, 'g'],
      ['czosnek', 3, 'szt'],
      ['natka pietruszki', 10, 'g'],
    ],
    steps: [
      'Wymieszaj miękkie masło z przeciśniętym czosnkiem i drobno posiekaną natką pietruszki.',
      'Natnij bagietkę co 2 cm, nie przecinając jej do końca, i posmaruj masłem każde nacięcie.',
      'Zawiń bagietkę szczelnie w folię aluminiową i połóż na rozgrzanym grillu ogrodowym (węglowym, gazowym albo elektrycznym) na 10–12 minut, obracając co kilka minut.',
      'Rozwiń folię i opiecz bagietkę bezpośrednio na ruszcie jeszcze 2 minuty, żeby skórka była chrupiąca.',
      'Na patelni grillowej: przekrój bagietkę wzdłuż, posmaruj masłem i opiekaj po 3–4 minuty z każdej strony. Podawaj ciepłą.',
    ],
    photo:
      'A short section of golden grilled baguette with grill marks, cut into thick slices almost all the way through, with melted garlic butter and green parsley between the slices',
    vessel: 'board',
  },
  {
    plan: 'PR-012',
    title: 'Szaszłyki owocowe z czekoladą',
    description:
      'Kolorowe szaszłyki z truskawek, winogron, ananasa i banana polane gorzką czekoladą. Dzieci składają je same, a na imprezie znikają jako pierwsze — owocowa przekąska bez pieczenia.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'BITES',
    occasions: ['PARTY'],
    ingredients: [
      ['truskawka', 200, 'g'],
      ['winogrono białe', 150, 'g'],
      ['ananas', 200, 'g'],
      ['banan', 1, 'szt'],
      ['czekolada gorzka', 60, 'g'],
      ['olej kokosowy', 5, 'g'],
    ],
    steps: [
      'Umyj truskawki i winogrona, osusz. Ananasa obierz i pokrój w kostkę, banana w grube plasterki.',
      'Nabijaj owoce na patyczki do szaszłyków na zmianę, po 5–6 kawałków na każdy.',
      'Roztop czekoladę z olejem kokosowym w kąpieli wodnej albo w mikrofalówce w 20-sekundowych seriach.',
      'Ułóż szaszłyki na papierze do pieczenia i polej je cienkimi strużkami czekolady.',
      'Wstaw na 10 minut do lodówki, aż czekolada stężeje, i podawaj.',
    ],
    photo:
      'Three short colorful fruit skewers with strawberries, green grapes, pineapple cubes and banana slices, drizzled with thin set streaks of dark chocolate',
    vessel: 'board',
  },
  {
    plan: 'PR-013',
    title: 'Kąski kurczaka w sezamie z sosem słodko-ostrym',
    description:
      'Soczyste kawałki kurczaka w chrupiącej sezamowej panierce, pieczone zamiast smażone, z sosem słodko-ostrym do maczania. Sycąca, bogata w białko przekąska na imprezę i do meczu.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['OVEN'],
    ingredients: [
      ['filet z kurczaka', 500, 'g'],
      ['sos sojowy', 10, 'ml'],
      ['czosnek granulowany', 2, 'g'],
      ['jajko', 1, 'szt'],
      ['mąka ziemniaczana', 20, 'g'],
      ['sezam', 40, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sos chili słodki', 60, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C (termoobieg). Pokrój filet w kostkę około 3 cm i wymieszaj z sosem sojowym i czosnkiem granulowanym.',
      'Roztrzep jajko z mąką ziemniaczaną, wmieszaj kurczaka, a potem obtocz każdy kawałek w sezamie.',
      'Ułóż kąski na blasze z papierem i skrop olejem.',
      'Piecz 12–15 minut, w połowie przewracając, aż sezam się zezłoci, a mięso będzie upieczone w środku.',
      'Podawaj gorące na wykałaczkach, z sosem chili słodkim do maczania.',
    ],
    photo:
      'Golden sesame-crusted chicken bites, a few with wooden toothpicks, with a small pool of glossy orange sweet chili sauce on the side',
  },
  {
    plan: 'PR-014',
    title: 'Dip serowy z jalapeño do nachos',
    description:
      'Gładki, ciągnący się sos z cheddaru z pikantnymi plasterkami jalapeño i szczyptą wędzonej papryki, podany na ciepło z chipsami kukurydzianymi. Meksykańska klasyka imprez i wieczorów przy meczu.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 4,
    cuisine: 'MEXICAN',
    dishType: 'DIP',
    occasions: ['PARTY'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['masło', 15, 'g'],
      ['mąka ziemniaczana', 10, 'g'],
      ['mleko', 200, 'ml'],
      ['ser cheddar', 150, 'g'],
      ['papryczki jalapeño', 40, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['papryka wędzona mielona', 1, 'g'],
      ['chips kukurydziany', 150, 'g'],
    ],
    steps: [
      'Zetrzyj cheddar na drobnych oczkach, a jalapeño odsącz i posiekaj, zostawiając kilka plasterków do dekoracji.',
      'Rozmieszaj mąkę ziemniaczaną w 3 łyżkach zimnego mleka.',
      'W rondelku roztop masło, wlej resztę mleka i podgrzej. Wlej rozmieszaną mąkę i gotuj, mieszając, 1–2 minuty, aż sos zgęstnieje.',
      'Zmniejsz ogień, dodawaj ser garściami i mieszaj, aż się rozpuści. Wmieszaj jalapeño, kmin rzymski i wędzoną paprykę.',
      'Przelej dip do miseczki, udekoruj plasterkami jalapeño i podawaj ciepły z chipsami kukurydzianymi.',
    ],
    photo:
      'Smooth glossy golden cheddar cheese dip topped with green jalapeno slices, with a few crunchy corn tortilla chips tucked into the edge of the dip',
    vessel: 'bowl',
  },
  {
    plan: 'PR-015',
    title: 'Salsa pomidorowa z kukurydzą i chipsami',
    description:
      'Świeża, lekko pikantna salsa z pomidorów, słodkiej kukurydzy, czerwonej cebuli i kolendry, doprawiona limonką. Podana z chipsami kukurydzianymi to szybka meksykańska przekąska na imprezę.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 4,
    cuisine: 'MEXICAN',
    dishType: 'DIP',
    occasions: ['PARTY'],
    ingredients: [
      ['pomidor', 400, 'g'],
      ['kukurydza z puszki', 150, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['papryczka chili', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['kolendra', 15, 'g'],
      ['limonka', 40, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 2, 'g'],
      ['chips kukurydziany', 120, 'g'],
    ],
    steps: [
      'Przekrój pomidory, usuń wodniste gniazda nasienne i pokrój miąższ w drobną kostkę.',
      'Odsącz kukurydzę. Cebulę i chili posiekaj drobno, czosnek przeciśnij przez praskę, kolendrę posiekaj.',
      'Wymieszaj warzywa w misce z sokiem z limonki, oliwą i solą.',
      'Odstaw salsę na 10 minut, żeby smaki się połączyły, i podawaj z chipsami kukurydzianymi.',
    ],
    photo:
      'Colorful fresh diced tomato salsa with yellow sweet corn, red onion, chili and green cilantro, with a few corn tortilla chips tucked into the edge of the salsa',
    vessel: 'bowl',
  },
  {
    plan: 'PR-016',
    title: 'Precle drożdżowe z solą i sosem serowym',
    description:
      'Miękkie w środku, rumiane z wierzchu precle z ciasta drożdżowego na mleku i maśle, posypane grubą solą. Do maczania kremowy sos z cheddaru — przekąska, przy której zbiera się całe towarzystwo.',
    mealType: 'SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 90,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    occasions: ['PARTY'],
    equipment: ['OVEN'],
    ingredients: [
      ['mąka pszenna', 310, 'g'],
      ['drożdże instant', 7, 'g'],
      ['cukier', 5, 'g'],
      ['mleko', 330, 'ml'],
      ['masło', 40, 'g'],
      ['jajko', 1, 'szt'],
      ['sól', 6, 'g'],
      ['ser cheddar', 100, 'g'],
    ],
    steps: [
      'Wymieszaj 300 g mąki z drożdżami, cukrem i 2 g soli. Dodaj 180 ml ciepłego mleka i 30 g roztopionego masła, zagnieć gładkie ciasto przez 8 minut.',
      'Przykryj i odstaw na 45 minut, aż ciasto podwoi objętość.',
      'Nagrzej piekarnik do 200°C (góra–dół). Podziel ciasto na 12 części, z każdej rozwałkuj wałek długości 40 cm i zwiń w precel.',
      'Ułóż precle na blasze z papierem, posmaruj roztrzepanym jajkiem i posyp resztą soli (grubej). Piecz 14–16 minut, aż będą ciemnozłote.',
      'W rondelku roztop resztę masła, wmieszaj 10 g mąki i wlej 150 ml mleka. Gotuj, mieszając, aż zgęstnieje, zdejmij z ognia i rozpuść w sosie starty cheddar.',
      'Podawaj ciepłe precle z sosem serowym do maczania.',
    ],
    photo:
      'Two shiny dark golden soft pretzels sprinkled with coarse salt, with a small pool of creamy yellow cheddar cheese sauce on the side',
  },
  {
    plan: 'PR-017',
    title: 'Krewetki w cieście z sosem słodko-chili',
    description:
      'Krewetki w chrupiącej panierce z bułki tartej z nutą czosnku i papryki, upieczone w airfryerze. Podane z sosem słodko-chili i limonką to imprezowa przekąska, która znika w kilka minut.',
    mealType: 'SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['krewetka', 400, 'g'],
      ['mąka pszenna', 30, 'g'],
      ['jajko', 2, 'szt'],
      ['bułka tarta', 60, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sos chili słodki', 80, 'g'],
      ['limonka', 30, 'g'],
    ],
    steps: [
      'Rozmroź krewetki, obierz je, zostawiając ogonki, i osusz ręcznikiem papierowym.',
      'Wymieszaj bułkę tartą z czosnkiem granulowanym i papryką. Obtocz każdą krewetkę w mące, roztrzepanych jajkach i bułce.',
      'Ułóż krewetki w koszu airfryera w jednej warstwie i skrop olejem.',
      'Piecz w 200°C przez 6–8 minut, obracając w połowie, aż panierka się zezłoci. W piekarniku: 220°C, termoobieg, 10–12 minut na blasze z papierem.',
      'Podawaj od razu z sosem chili słodkim i ćwiartkami limonki.',
    ],
    photo:
      'Six crispy golden breaded shrimp with tails on, with a small pool of glossy sweet chili sauce and a lime wedge on the side',
  },
  {
    plan: 'PR-018',
    title: 'Koktajl krewetkowy z sosem koktajlowym',
    description:
      'Schłodzone krewetki na chrupiącej sałacie lodowej z awokado, polane różowym sosem z majonezu, ketchupu i chrzanu. Amerykańska klasyka przyjęć, która świetnie sprawdza się jako świąteczna przystawka.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 4,
    cuisine: 'AMERICAN',
    dishType: 'SALAD',
    occasions: ['PARTY', 'CHRISTMAS'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['krewetka', 300, 'g'],
      ['cytryna', 40, 'g'],
      ['majonez', 50, 'g'],
      ['ketchup', 25, 'g'],
      ['chrzan tarty', 10, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['sałata lodowa', 100, 'g'],
      ['awokado', 1, 'szt'],
    ],
    steps: [
      'Wrzuć obrane krewetki do wrzącej wody z plasterkiem cytryny i gotuj 2–3 minuty, aż zróżowieją. Odcedź i przełóż do miski z lodowatą wodą, potem osusz.',
      'Wymieszaj majonez z ketchupem, chrzanem i łyżeczką soku z cytryny.',
      'Poszatkuj drobno sałatę lodową, a awokado pokrój w kostkę i skrop sokiem z cytryny.',
      'Rozłóż sałatę i awokado do czterech pucharków, ułóż na wierzchu krewetki i polej sosem.',
      'Oprósz słodką papryką, udekoruj cząstką cytryny i podawaj schłodzone.',
    ],
    photo:
      'Classic shrimp cocktail: finely shredded iceberg lettuce and avocado cubes topped with pink shrimp and creamy pink cocktail sauce dusted with paprika, with a lemon wedge',
    vessel: 'cup',
  },
  {
    plan: 'PR-019',
    title: 'Krewetki marynowane z czosnkiem i ziołami',
    description:
      'Krewetki marynowane w oliwie z czosnkiem, cytryną, oregano i odrobiną chili, krótko obsmażone na mocnym ogniu. Greckie w duchu, lekkie i aromatyczne — idealne na imprezę z bagietką albo bez niej.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 4,
    cuisine: 'GREEK',
    dishType: 'BITES',
    occasions: ['PARTY'],
    ingredients: [
      ['krewetka', 400, 'g'],
      ['oliwa z oliwek', 40, 'ml'],
      ['czosnek', 4, 'szt'],
      ['cytryna', 50, 'g'],
      ['oregano', 2, 'g'],
      ['płatki chili', 1, 'g'],
      ['natka pietruszki', 15, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Obierz krewetki, zostawiając ogonki, i osusz je ręcznikiem papierowym.',
      'Wymieszaj 2 łyżki oliwy z przeciśniętym czosnkiem, startą skórką i sokiem z połowy cytryny, oregano, płatkami chili i solą. Zalej krewetki marynatą i odstaw do lodówki na 20 minut.',
      'Rozgrzej resztę oliwy na dużej patelni i smaż krewetki na mocnym ogniu po 1–2 minuty z każdej strony, aż zróżowieją.',
      'Przełóż na półmisek, polej sokiem z patelni, posyp posiekaną natką i podawaj z cząstkami cytryny.',
    ],
    photo:
      'Pink seared shrimp with tails on glistening in garlicky lemon olive oil, sprinkled with chopped parsley and chili flakes, with lemon wedges',
  },

  // ─── Chrupiące i fit ───
  {
    plan: 'PR-020',
    title: 'Chrupiące kostki tofu z sosem chili',
    description:
      'Kostki tofu w cienkiej warstwie mąki ziemniaczanej, upieczone w airfryerze na chrupko i obtoczone w pikantno-słodkim sosie chili. Roślinna przekąska pełna białka, która smakuje nawet przeciwnikom tofu.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BITES',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['tofu', 400, 'g'],
      ['sos sojowy', 10, 'ml'],
      ['mąka ziemniaczana', 20, 'g'],
      ['olej sezamowy', 5, 'ml'],
      ['czosnek granulowany', 2, 'g'],
      ['sos sriracha', 15, 'g'],
      ['sos chili słodki', 20, 'g'],
      ['cebula dymka', 20, 'g'],
      ['sezam', 5, 'g'],
    ],
    steps: [
      'Odsącz tofu, zawiń w ręcznik i przyciśnij deską na 10 minut, żeby pozbyć się wody. Pokrój w kostkę 2 cm.',
      'Skrop tofu połową sosu sojowego, oprósz czosnkiem granulowanym i mąką ziemniaczaną, delikatnie wymieszaj, a potem skrop olejem sezamowym.',
      'Piecz w airfryerze w 200°C przez 12–15 minut, potrząsając koszem co 5 minut, aż kostki będą złote i chrupiące. W piekarniku: 220°C, termoobieg, 20–25 minut na blasze z papierem.',
      'Wymieszaj sos sriracha z sosem chili słodkim i resztą sosu sojowego, obtocz w nim gorące tofu.',
      'Posyp posiekaną dymką i sezamem, podawaj od razu.',
    ],
    photo:
      'Crispy golden tofu cubes coated in glossy red chili sauce, sprinkled with sliced green onion and sesame seeds',
    vessel: 'bowl',
  },
  {
    plan: 'PR-021',
    title: 'Dip z białej fasoli z rozmarynem i warzywami',
    description:
      'Aksamitna pasta z białej fasoli z oliwą, czosnkiem, rozmarynem i cytryną, podana z chrupiącymi słupkami warzyw. Toskańska w duchu alternatywa dla hummusu, gotowa w kwadrans.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 4,
    cuisine: 'ITALIAN',
    dishType: 'DIP',
    equipment: ['BLENDER'],
    ingredients: [
      ['fasola biała z puszki', 400, 'g'],
      ['oliwa z oliwek', 30, 'ml'],
      ['czosnek', 1, 'szt'],
      ['rozmaryn suszony', 2, 'g'],
      ['cytryna', 30, 'g'],
      ['sól', 1, 'g'],
      ['marchew', 200, 'g'],
      ['seler naciowy', 150, 'g'],
      ['papryka czerwona', 160, 'g'],
    ],
    steps: [
      'Odsącz i przepłucz fasolę na sitku.',
      'Rozgrzej 1 łyżkę oliwy w małym rondelku z rozmarynem i przeciśniętym czosnkiem, trzymaj na małym ogniu 2 minuty, żeby oliwa przeszła aromatem.',
      'Zmiksuj blenderem fasolę z aromatyczną oliwą, sokiem z cytryny, solą i 2–3 łyżkami zimnej wody na gładki krem.',
      'Pokrój marchew, seler naciowy i paprykę w słupki.',
      'Przełóż dip do miseczki, zrób łyżką zagłębienie, wlej resztę oliwy i podawaj z warzywami.',
    ],
    photo:
      'A thick swoosh of creamy white bean dip spread across one side of the board, with a little pool of golden olive oil in its hollow, and orange carrot sticks, celery sticks and red pepper strips arranged beside it',
    vessel: 'board',
  },
  {
    plan: 'PR-022',
    title: 'Domowy mix orzechów i suszonych owoców',
    description:
      'Podprażone migdały, orzechy laskowe i włoskie z pestkami dyni, wymieszane z żurawiną, morelami i rodzynkami. Zdrowsza od batonika przekąska na kilka dni, idealna do pudełka, torby i szuflady w pracy.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    features: ['LUNCHBOX'],
    ingredients: [
      ['migdał', 60, 'g'],
      ['orzech laskowy', 50, 'g'],
      ['orzech włoski', 50, 'g'],
      ['pestki dyni', 40, 'g'],
      ['żurawina suszona', 40, 'g'],
      ['morela suszona', 50, 'g'],
      ['rodzynka', 40, 'g'],
    ],
    steps: [
      'Praż migdały i orzechy laskowe na suchej patelni na średnim ogniu przez 5 minut, często mieszając.',
      'Dodaj orzechy włoskie i pestki dyni, praż jeszcze 2–3 minuty, aż pestki zaczną strzelać.',
      'Przesyp na talerz i ostudź całkowicie. Morele pokrój w paski.',
      'Wymieszaj orzechy z żurawiną, morelami i rodzynkami, przesyp do szczelnego słoika. Przechowuj do 2 tygodni i odmierzaj po garści (około 40 g) na porcję.',
    ],
    photo:
      'A small handful of mixed roasted almonds, hazelnuts, walnuts and pumpkin seeds with red dried cranberries, orange dried apricot strips and raisins',
    vessel: 'bowl',
  },
  {
    plan: 'PR-023',
    title: 'Oliwki marynowane z czosnkiem i ziołami',
    description:
      'Zielone i czarne oliwki zalane oliwą z czosnkiem, skórką cytryny, oregano, rozmarynem i szczyptą chili. Po kilku godzinach w lodówce smakują jak z greckiej tawerny — gotowe do podania na imprezie.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 135,
    servings: 6,
    cuisine: 'GREEK',
    dishType: 'BITES',
    occasions: ['PARTY'],
    ingredients: [
      ['oliwka zielona', 150, 'g'],
      ['oliwka czarna', 100, 'g'],
      ['oliwa z oliwek', 40, 'ml'],
      ['czosnek', 3, 'szt'],
      ['cytryna', 40, 'g'],
      ['oregano', 2, 'g'],
      ['rozmaryn suszony', 1, 'g'],
      ['płatki chili', 1, 'g'],
    ],
    steps: [
      'Odsącz oliwki z zalewy i przełóż do słoika albo miski.',
      'Czosnek obierz i pokrój w cienkie plasterki. Z cytryny zetrzyj skórkę i wyciśnij 2 łyżki soku.',
      'Wymieszaj oliwę z czosnkiem, skórką i sokiem z cytryny, oregano, rozmarynem i płatkami chili.',
      'Zalej oliwki marynatą, wymieszaj i odstaw do lodówki na co najmniej 2 godziny, najlepiej na noc. Wyjmij 15 minut przed podaniem.',
    ],
    photo:
      'Glossy green and black olives in golden olive oil with thin garlic slices, lemon zest, oregano and red chili flakes',
    vessel: 'bowl',
  },
  {
    plan: 'PR-024',
    title: 'Prażone migdały z wędzoną papryką',
    description:
      'Całe migdały uprażone w piekarniku z oliwą, wędzoną papryką i czosnkiem, lekko posolone. Chrupiąca, sycąca przekąska do wina albo zamiast chipsów, na kilka dni w słoiku.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    equipment: ['OVEN'],
    ingredients: [
      ['migdał', 200, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['papryka wędzona mielona', 4, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 170°C (termoobieg).',
      'Wymieszaj migdały z oliwą, a potem z wędzoną papryką, czosnkiem granulowanym i solą.',
      'Rozłóż migdały na blasze w jednej warstwie i praż 12–15 minut, mieszając w połowie, aż w środku będą jasnozłote.',
      'Ostudź na blasze — migdały stwardnieją i zrobią się chrupiące. Przechowuj w szczelnym słoiku do tygodnia.',
    ],
    photo:
      'A small handful of roasted whole almonds coated in rusty red smoked paprika seasoning',
    vessel: 'bowl',
  },
  {
    plan: 'PR-025',
    title: 'Chipsy z marchewki i pietruszki',
    description:
      'Cieniutkie plasterki marchewki i korzenia pietruszki wysuszone w airfryerze na chrupko z tymiankiem i papryką. Zimowa przekąska z warzyw korzeniowych, słodkawa i chrupiąca jak chipsy.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    seasons: ['WINTER'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['marchew', 300, 'g'],
      ['pietruszka korzeń', 200, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['tymianek suszony', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Obierz marchew i pietruszkę, a potem pokrój je obieraczką albo na mandolinie w cienkie plastry.',
      'Osusz plastry ręcznikiem papierowym i wymieszaj z oliwą, tymiankiem i papryką.',
      'Rozłóż warzywa luźno w koszu airfryera i piecz w 160°C przez 12–16 minut, w 2–3 turach, potrząsając koszem co 4 minuty. W piekarniku: 150°C, termoobieg, 25–30 minut na blasze z papierem.',
      'Wyjmij chipsy, gdy brzegi zaczną się zwijać i rumienić, posól i ostudź — dopiero wtedy zrobią się chrupiące.',
    ],
    photo:
      'Thin crispy orange carrot and pale parsley root chips with curled golden edges, sprinkled with thyme',
    vessel: 'bowl',
  },
  {
    plan: 'PR-026',
    title: 'Frytki z selera z dipem',
    description:
      'Słupki selera korzeniowego upieczone w airfryerze z papryką, rumiane na brzegach i miękkie w środku. Z jogurtowym dipem ze szczypiorkiem to zimowa, lżejsza alternatywa dla ziemniaczanych frytek.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    seasons: ['WINTER'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['seler korzeniowy', 500, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['mąka ziemniaczana', 10, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 2, 'g'],
      ['jogurt grecki', 150, 'g'],
      ['czosnek', 1, 'szt'],
      ['szczypiorek', 10, 'g'],
    ],
    steps: [
      'Obierz seler i pokrój w słupki grubości 1 cm.',
      'Wymieszaj słupki z oliwą, a potem oprósz mąką ziemniaczaną, papryką i połową soli.',
      'Piecz w airfryerze w 200°C przez 18–22 minuty, potrząsając koszem co 6 minut, aż brzegi się zrumienią. W piekarniku: 220°C, termoobieg, 25–30 minut na blasze z papierem.',
      'Wymieszaj jogurt grecki z przeciśniętym czosnkiem, posiekanym szczypiorkiem i resztą soli.',
      'Podawaj gorące frytki z dipem.',
    ],
    photo:
      'Golden roasted celeriac fries with browned edges and a dusting of paprika, with a generous dollop of thick white garlic yogurt dip with chopped chives',
  },
  {
    plan: 'PR-027',
    title: 'Frytki z cukinii z parmezanem',
    description:
      'Słupki młodej cukinii w chrupiącej panierce z bułki tartej, parmezanu i oregano, upieczone w airfryerze. Letnia przekąska, która znika szybciej niż zwykłe frytki.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    seasons: ['SUMMER'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['cukinia', 500, 'g'],
      ['jajko', 1, 'szt'],
      ['bułka tarta', 50, 'g'],
      ['ser parmezan', 30, 'g'],
      ['oregano', 1, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Pokrój cukinię w słupki grubości palca, posól i odstaw na 10 minut, a potem osusz ręcznikiem papierowym.',
      'Wymieszaj bułkę tartą z drobno startym parmezanem, oregano i czosnkiem granulowanym. Jajko roztrzep w misce.',
      'Obtocz słupki w jajku, a potem w panierce, i ułóż w koszu airfryera w jednej warstwie. Skrop olejem.',
      'Piecz w 200°C przez 10–12 minut, obracając w połowie, aż panierka będzie złota. W piekarniku: 220°C, termoobieg, 15–18 minut na blasze z papierem.',
      'Podawaj od razu, póki są chrupiące.',
    ],
    photo:
      'Golden crispy zucchini fries coated in parmesan and oregano breadcrumbs, loosely piled',
  },
  {
    plan: 'PR-028',
    title: 'Warzywa z dipem jogurtowo-ziołowym',
    description:
      'Kolorowe słupki marchewki, ogórka, papryki i rzodkiewki z gęstym jogurtowym dipem z koperkiem, szczypiorkiem i czosnkiem. Lekka, chrupiąca przekąska na popołudnie, gotowa w kwadrans.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'DIP',
    ingredients: [
      ['jogurt grecki', 200, 'g'],
      ['koperek', 10, 'g'],
      ['szczypiorek', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 10, 'g'],
      ['sól', 1, 'g'],
      ['marchew', 150, 'g'],
      ['ogórek', 200, 'g'],
      ['papryka czerwona', 160, 'g'],
      ['rzodkiewka', 100, 'g'],
    ],
    steps: [
      'Posiekaj drobno koperek i szczypiorek, czosnek przeciśnij przez praskę.',
      'Wymieszaj jogurt grecki z ziołami, czosnkiem, łyżeczką soku z cytryny i solą. Odstaw do lodówki.',
      'Obierz marchew i pokrój ją razem z ogórkiem i papryką w słupki. Rzodkiewki przekrój na pół.',
      'Ułóż warzywa wokół miseczki z dipem i podawaj od razu.',
    ],
    photo:
      'A thick swoosh of white herb yogurt dip flecked with dill and chives spread across one side of the board, with carrot, cucumber and red pepper sticks and halved radishes arranged beside it',
    vessel: 'board',
  },
  {
    plan: 'PR-029',
    title: 'Orzechy prażone z rozmarynem i miodem',
    description:
      'Orzechy włoskie, laskowe i migdały uprażone z masłem, rozmarynem i cienką warstwą miodu, lekko posolone. Słodko-słona, pachnąca przekąska do wina albo na drobny prezent w słoiku.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 6,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    equipment: ['OVEN'],
    ingredients: [
      ['orzech włoski', 80, 'g'],
      ['migdał', 80, 'g'],
      ['orzech laskowy', 60, 'g'],
      ['masło', 10, 'g'],
      ['miód', 20, 'g'],
      ['rozmaryn suszony', 2, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 170°C (termoobieg) i wyłóż blachę papierem do pieczenia.',
      'Roztop masło z miodem w rondelku, zdejmij z ognia i wmieszaj roztarty w palcach rozmaryn oraz sól.',
      'Wsyp orzechy i migdały, wymieszaj dokładnie, żeby każdy był pokryty, i rozłóż w jednej warstwie na blasze.',
      'Praż 12–14 minut, mieszając w połowie, aż orzechy się zezłocą. Ostudź na blasze, a potem rozdziel posklejane kawałki.',
    ],
    photo:
      'A small handful of glossy honey-roasted walnuts, hazelnuts and almonds flecked with rosemary',
    vessel: 'bowl',
  },
  {
    plan: 'PR-030',
    title: 'Krakersy z nasion bez mąki',
    description:
      'Cienkie, chrupiące krakersy z siemienia lnianego, chia, słonecznika, pestek dyni i sezamu, związane samym namoczonym ziarnem. Bez grama mąki — świetne do past i serów albo solo.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 90,
    servings: 8,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    equipment: ['OVEN'],
    ingredients: [
      ['siemię lniane', 60, 'g'],
      ['nasiona chia', 40, 'g'],
      ['słonecznik łuszczony', 80, 'g'],
      ['pestki dyni', 60, 'g'],
      ['sezam', 40, 'g'],
      ['zioła prowansalskie', 2, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Wymieszaj wszystkie nasiona z ziołami i solą, zalej 200 ml wody i odstaw na 15 minut, aż masa zgęstnieje i zrobi się kleista.',
      'Nagrzej piekarnik do 160°C (termoobieg).',
      'Rozsmaruj masę na blasze wyłożonej papierem cienko i równo, na grubość 3–4 mm. Ponacinaj nożem na prostokąty.',
      'Piecz 30 minut, potem ostrożnie odwróć płat na drugą stronę i piecz jeszcze 20–25 minut, aż będzie suchy i chrupiący.',
      'Ostudź w uchylonym piekarniku i połam krakersy wzdłuż nacięć. Przechowuj w puszce do tygodnia.',
    ],
    photo:
      'A few rustic crispy rectangular seed crackers packed with flax, chia, sunflower, pumpkin and sesame seeds, loosely stacked',
    vessel: 'board',
  },
  {
    plan: 'PR-031',
    title: 'Pomidorki koktajlowe nadziewane twarożkiem',
    description:
      'Wydrążone pomidorki koktajlowe napełnione twarożkiem z jogurtem, szczypiorkiem, koperkiem i czosnkiem. Kolorowa, lekka przekąska na imprezowy stół, która wygląda świetnie, a robi się bez gotowania.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'BITES',
    occasions: ['PARTY'],
    ingredients: [
      ['pomidor koktajlowy', 300, 'g'],
      ['ser twaróg półtłusty', 150, 'g'],
      ['jogurt grecki', 30, 'g'],
      ['szczypiorek', 10, 'g'],
      ['koperek', 5, 'g'],
      ['czosnek', 1, 'szt'],
      ['pieprz czarny', 1, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Odetnij wierzchy pomidorków i wydrąż miąższ łyżeczką. Odwróć je do góry dnem na ręcznik papierowy na 10 minut.',
      'Rozgnieć twaróg widelcem z jogurtem greckim na gładką pastę.',
      'Wmieszaj posiekany szczypiorek i koperek, przeciśnięty czosnek, sól i pieprz.',
      'Napełnij pomidorki pastą za pomocą łyżeczki albo woreczka z odciętym rogiem i ułóż na półmisku. Podawaj schłodzone.',
    ],
    photo:
      'Five hollowed red cherry tomatoes filled with smooth white curd cheese paste flecked with chives and dill',
  },
  {
    plan: 'PR-032',
    title: 'Jabłka z masłem orzechowym i cynamonem',
    description:
      'Chrupiące plastry jabłka z kremowym masłem orzechowym, cynamonem i posiekanymi orzeszkami. Przekąska w pięć minut, którą dzieci jedzą z ochotą zamiast słodyczy.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BITES',
    ingredients: [
      ['jabłko', 300, 'g'],
      ['masło orzechowe', 40, 'g'],
      ['orzeszek ziemny', 10, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Umyj jabłka, wytnij gniazda nasienne i pokrój je w krążki albo grube plastry.',
      'Posmaruj każdy plaster cienką warstwą masła orzechowego.',
      'Posiekaj orzeszki ziemne i posyp nimi jabłka, a na koniec oprósz cynamonem.',
      'Podawaj od razu, zanim jabłka ściemnieją.',
    ],
    photo:
      'Crisp cored apple rings spread with a thin layer of creamy peanut butter, sprinkled with chopped peanuts and a dusting of cinnamon',
  },
  {
    plan: 'PR-033',
    title: 'Młoda marchewka z hummusem',
    description:
      'Słodka, chrupiąca młoda marchewka podana z domowym hummusem z ciecierzycy, tahini, cytryny i kminu. Wiosenna, roślinna przekąska, gotowa w kwadrans i dobra także do pudełka.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'DIP',
    seasons: ['SPRING'],
    equipment: ['BLENDER'],
    ingredients: [
      ['ciecierzyca z puszki', 240, 'g'],
      ['tahini', 30, 'g'],
      ['cytryna', 30, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['kmin rzymski', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['sól', 1, 'g'],
      ['marchew', 300, 'g'],
    ],
    steps: [
      'Odsącz ciecierzycę, zachowując 3 łyżki zalewy.',
      'Zmiksuj blenderem ciecierzycę z tahini, sokiem z cytryny, czosnkiem, kminem, solą i zalewą na gładki, puszysty krem.',
      'Przełóż hummus do miseczki, polej oliwą i oprósz słodką papryką.',
      'Wyszoruj młode marchewki, zostawiając kawałek natki, i przekrój grubsze wzdłuż. Podawaj z hummusem.',
    ],
    photo:
      'A thick swoosh of smooth hummus spread across one side of the board, drizzled with olive oil and dusted with paprika, with a few young orange carrots with short green tops arranged beside it',
    vessel: 'board',
  },
  {
    plan: 'PR-034',
    title: 'Pestki dyni prażone z sosem sojowym',
    description:
      'Pestki dyni uprażone na suchej patelni i szkliste od sosu sojowego z czosnkiem i papryką. Jesienna, słono-chrupiąca przekąska na kilka dni i świetna posypka do zup i sałatek.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 5,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    seasons: ['AUTUMN'],
    ingredients: [
      ['pestki dyni', 150, 'g'],
      ['sos sojowy', 15, 'ml'],
      ['czosnek granulowany', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
    ],
    steps: [
      'Rozgrzej suchą patelnię na średnim ogniu i praż pestki dyni 4–5 minut, często mieszając, aż zaczną strzelać i się zaokrąglą.',
      'Wymieszaj sos sojowy z czosnkiem granulowanym i papryką.',
      'Zdejmij patelnię z ognia, wlej sos i mieszaj energicznie przez minutę, aż pestki go wchłoną i zrobią się szkliste.',
      'Rozsyp pestki na talerzu i ostudź — stwardnieją i będą chrupiące. Przechowuj w słoiku do tygodnia.',
    ],
    photo:
      'Roasted pumpkin seeds, olive green and slightly puffed, lightly glazed and shiny with soy sauce and dusted with paprika',
    vessel: 'bowl',
  },

  // ─── Airfryer ───
  {
    plan: 'PR-035',
    title: 'Nuggetsy z kalafiora',
    description:
      'Różyczki kalafiora w chrupiącej panierce z bułki tartej i parmezanu, upieczone w airfryerze na złoto. Warzywna wersja nuggetsów, którą maczają w ketchupie nawet dzieci niechętne warzywom.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 3,
    cuisine: 'OTHER',
    dishType: 'BITES',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['kalafior', 500, 'g'],
      ['mąka pszenna', 30, 'g'],
      ['jajko', 2, 'szt'],
      ['bułka tarta', 60, 'g'],
      ['ser parmezan', 20, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['ketchup', 60, 'g'],
    ],
    steps: [
      'Podziel kalafior na małe różyczki wielkości kęsa. Zblanszuj je 3 minuty we wrzątku, odcedź i osusz.',
      'Wymieszaj bułkę tartą z drobno startym parmezanem, papryką i czosnkiem granulowanym. Jajka roztrzep w misce.',
      'Obtocz różyczki w mące, jajku i panierce, ułóż w koszu airfryera w jednej warstwie i skrop olejem.',
      'Piecz w 190°C przez 12–15 minut, potrząsając koszem w połowie, aż panierka będzie złota. W piekarniku: 210°C, termoobieg, 20–25 minut na blasze z papierem.',
      'Podawaj gorące z ketchupem do maczania.',
    ],
    photo:
      'Golden crispy breaded cauliflower nuggets, loosely piled, with a small pool of red ketchup on the side',
  },
  {
    plan: 'PR-036',
    title: 'Krążki cebulowe',
    description:
      'Grube krążki słodkiej cebuli w podwójnej, chrupiącej panierce z papryką, upieczone w airfryerze zamiast smażone w głębokim tłuszczu. Klasyczna imprezowa przekąska prosto z amerykańskiego baru.',
    mealType: 'SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 4,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['cebula', 400, 'g'],
      ['mąka pszenna', 40, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['sól', 1, 'g'],
      ['jajko', 2, 'szt'],
      ['mleko', 50, 'ml'],
      ['bułka tarta', 80, 'g'],
      ['olej rzepakowy', 10, 'ml'],
    ],
    steps: [
      'Obierz cebule, pokrój w plastry grubości 1 cm i rozdziel na krążki.',
      'Wymieszaj mąkę z papryką i solą. W drugiej misce roztrzep jajka z mlekiem, do trzeciej wsyp bułkę tartą.',
      'Obtocz każdy krążek w mące, w jajku i w bułce, a potem jeszcze raz w jajku i w bułce.',
      'Ułóż krążki w koszu airfryera w jednej warstwie, skrop olejem i piecz w 200°C przez 8–10 minut, obracając w połowie. W piekarniku: 220°C, termoobieg, 12–15 minut na blasze z papierem.',
      'Podawaj od razu, póki panierka jest chrupiąca.',
    ],
    photo:
      'A loose low pile of golden crispy breaded onion rings with a crunchy coating of visible crumbs',
  },
  {
    plan: 'PR-037',
    title: 'Pieczarki w panierce z sosem czosnkowym',
    description:
      'Całe pieczarki w chrupiącej panierce, soczyste w środku, upieczone w airfryerze bez głębokiego tłuszczu. Z kremowym sosem czosnkowym z jogurtu i koperku to przekąska, która robi furorę na imprezie.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 3,
    cuisine: 'POLISH',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['pieczarka', 400, 'g'],
      ['mąka pszenna', 30, 'g'],
      ['jajko', 2, 'szt'],
      ['bułka tarta', 70, 'g'],
      ['papryka słodka mielona', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['majonez', 20, 'g'],
      ['czosnek', 2, 'szt'],
      ['koperek', 5, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Oczyść małe pieczarki suchym pędzelkiem albo ręcznikiem i skróć ogonki.',
      'Wymieszaj bułkę tartą z papryką. Obtocz pieczarki w mące, roztrzepanych jajkach i bułce.',
      'Ułóż je w koszu airfryera w jednej warstwie, skrop olejem i piecz w 200°C przez 10–12 minut, potrząsając koszem w połowie. W piekarniku: 220°C, termoobieg, 15–18 minut na blasze z papierem.',
      'Wymieszaj jogurt z majonezem, przeciśniętym czosnkiem, posiekanym koperkiem i solą.',
      'Podawaj gorące pieczarki z sosem czosnkowym.',
    ],
    photo:
      'Golden breaded whole button mushrooms with a generous dollop of creamy white garlic dill sauce on the side',
  },
  {
    plan: 'PR-038',
    title: 'Frytki z przyprawą paprykową',
    description:
      'Domowe frytki z ziemniaków upieczone w airfryerze na łyżce oleju, obsypane mieszanką słodkiej i wędzonej papryki z czosnkiem. Chrupiące, złote i dużo lżejsze niż z frytkownicy — dzieci je uwielbiają.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 3,
    cuisine: 'OTHER',
    dishType: 'CRUNCHY',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['czosnek granulowany', 1, 'g'],
      ['sól', 2, 'g'],
    ],
    steps: [
      'Obierz ziemniaki i pokrój je w słupki grubości 1 cm.',
      'Zalej słupki zimną wodą na 15 minut, żeby pozbyć się skrobi, a potem bardzo dokładnie osusz ściereczką.',
      'Wymieszaj frytki z olejem, a potem ze słodką i wędzoną papryką oraz czosnkiem granulowanym.',
      'Piecz w airfryerze w 200°C przez 18–22 minuty, potrząsając koszem co 5 minut, aż będą złote i chrupiące. W piekarniku: 220°C, termoobieg, 30–35 minut na blasze z papierem.',
      'Posól frytki zaraz po wyjęciu i podawaj gorące.',
    ],
    photo:
      'A loose pile of golden crispy homemade french fries dusted with red paprika seasoning',
  },
  {
    plan: 'PR-039',
    title: 'Kulki ziemniaczane z serem',
    description:
      'Kulki z tłuczonych ziemniaków ze szczypiorkiem, z kostką ciągnącego się sera w środku, w chrupiącej panierce. Idealny sposób na imprezową przekąskę, a przy okazji na resztki ziemniaków z obiadu.',
    mealType: 'SNACK',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 60,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ziemniak', 600, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka ziemniaczana', 30, 'g'],
      ['szczypiorek', 10, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 2, 'g'],
      ['ser gouda', 80, 'g'],
      ['bułka tarta', 60, 'g'],
      ['olej rzepakowy', 10, 'ml'],
    ],
    steps: [
      'Obierz ziemniaki, ugotuj w wodzie do miękkości (około 20 minut), odcedź i przeciśnij przez praskę. Ostudź.',
      'Wmieszaj do ziemniaków 1 jajko, mąkę ziemniaczaną, posiekany szczypiorek, gałkę muszkatołową i sól.',
      'Pokrój goudę w kostkę 1 cm. Nabieraj łyżkę masy, spłaszcz na dłoni, włóż kostkę sera i uformuj kulkę.',
      'Obtocz kulki w roztrzepanym drugim jajku i bułce tartej, ułóż w koszu airfryera i skrop olejem.',
      'Piecz w 200°C przez 10–12 minut, aż się zezłocą. W piekarniku: 220°C, termoobieg, 15–18 minut na blasze z papierem. Podawaj ciepłe.',
    ],
    photo:
      'Four golden breaded potato balls, one broken open revealing melted stretchy cheese and green chives inside',
  },
  {
    plan: 'PR-040',
    title: 'Kiełbaski koktajlowe w sosie słodko-ostrym',
    description:
      'Małe kiełbaski koktajlowe zapieczone w airfryerze i obtoczone w lepkim sosie z ketchupu, słodkiego chili, miodu i srirachy. Imprezowy klasyk do nabijania na wykałaczki, gotowy w kwadrans.',
    mealType: 'SNACK',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 5,
    cuisine: 'OTHER',
    dishType: 'BITES',
    occasions: ['PARTY'],
    equipment: ['AIRFRYER'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['kiełbaska koktajlowa', 350, 'g'],
      ['ketchup', 40, 'g'],
      ['sos chili słodki', 30, 'g'],
      ['miód', 15, 'g'],
      ['sos sriracha', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['cebula dymka', 15, 'g'],
    ],
    steps: [
      'Natnij każdą kiełbaskę na krzyż z obu końców, żeby ładnie się rozchyliły.',
      'Piecz kiełbaski w airfryerze w 190°C przez 6–8 minut, aż się zrumienią. W piekarniku: 200°C, termoobieg, 12–15 minut w naczyniu żaroodpornym.',
      'Wymieszaj ketchup z sosem chili słodkim, miodem, srirachą i przeciśniętym czosnkiem.',
      'Przełóż kiełbaski do miski, polej sosem i wymieszaj. Włóż z powrotem do airfryera na 2 minuty, żeby sos się zeszklił.',
      'Posyp posiekaną dymką i podawaj z wykałaczkami.',
    ],
    photo:
      'Glossy cocktail sausages with cross-cut splayed ends, coated in sticky red sweet chili glaze and sprinkled with sliced green onion, a few pierced with wooden toothpicks',
    vessel: 'bowl',
  },
];
