/**
 * Katalog 1000 — część SN-a: śniadania SN-001 … SN-030 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  {
    plan: 'SN-001',
    title: 'Kasza gryczana na mleku kokosowym z gruszką i orzechami',
    description:
      'Niepalona kasza gryczana ugotowana na mleku kokosowym, z duszoną gruszką, cynamonem i chrupiącymi orzechami włoskimi. Sycące, rozgrzewające śniadanie bez glutenu i bez nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PORRIDGE',
    ingredients: [
      ['kasza gryczana', 100, 'g'],
      ['mleko kokosowe z puszki', 150, 'ml'],
      ['gruszka', 250, 'g'],
      ['orzech włoski', 30, 'g'],
      ['syrop klonowy', 20, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Przepłucz kaszę gryczaną na sitku pod zimną wodą.',
      'Wsyp kaszę do garnka, wlej mleko kokosowe i 250 ml wody. Zagotuj, zmniejsz ogień i gotuj pod przykryciem 15 minut, aż kasza wchłonie płyn.',
      'W tym czasie umyj gruszkę, usuń gniazdo nasienne i pokrój ją w kostkę. Podduś na suchej patelni z cynamonem i łyżką wody przez 5 minut.',
      'Orzechy włoskie posiekaj grubo i podpraż krótko na suchej patelni.',
      'Przełóż kaszę do misek, ułóż na wierzchu gruszkę, posyp orzechami i polej syropem klonowym.',
    ],
    photo:
      'Creamy buckwheat porridge topped with warm cinnamon-stewed pear cubes, toasted chopped walnuts and a drizzle of maple syrup',
    vessel: 'bowl',
  },
  {
    plan: 'SN-002',
    title: 'Pudding z komosy ryżowej z mlekiem kokosowym i mango',
    description:
      'Kremowy pudding z komosy ryżowej gotowanej na mleku kokosowym i migdałowym, podany z soczystym mango, limonką i wiórkami kokosowymi. Tropikalne śniadanie bez glutenu i bez nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    ingredients: [
      ['komosa ryżowa', 80, 'g'],
      ['mleko kokosowe z puszki', 120, 'ml'],
      ['mleko migdałowe', 200, 'ml'],
      ['mango', 200, 'g'],
      ['syrop klonowy', 15, 'g'],
      ['wiórki kokosowe', 10, 'g'],
      ['limonka', 20, 'g'],
    ],
    steps: [
      'Przepłucz komosę ryżową dokładnie na sitku, żeby zmyć gorzki posmak.',
      'Wsyp komosę do garnka, wlej mleko kokosowe i migdałowe, zagotuj i gotuj na małym ogniu 15–18 minut, często mieszając, aż zrobi się gęsta i kremowa.',
      'Mango obierz i pokrój w kostkę, z limonki zetrzyj skórkę i wyciśnij sok.',
      'Wmieszaj do puddingu syrop klonowy i połowę soku z limonki.',
      'Przełóż do misek, ułóż mango, skrop resztą soku z limonki i posyp wiórkami kokosowymi oraz skórką.',
    ],
    photo:
      'Creamy quinoa pudding topped with bright yellow mango cubes, shredded coconut and fresh lime zest',
    vessel: 'bowl',
  },
  {
    plan: 'SN-003',
    title: 'Placuszki bananowe z mąki gryczanej',
    description:
      'Puszyste placuszki z mąki gryczanej i dojrzałych bananów, usmażone na złoto i podane z jogurtem i borówkami. Naturalnie słodkie śniadanie bez glutenu, które lubią także dzieci.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    ingredients: [
      ['mąka gryczana', 100, 'g'],
      ['banan', 2, 'szt'],
      ['jajko', 2, 'szt'],
      ['mleko', 100, 'ml'],
      ['olej rzepakowy', 10, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['borówka', 100, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Obierz banany i rozgnieć je widelcem na gładką masę.',
      'Dodaj jajka, mleko i cynamon, wymieszaj, a na koniec wsyp mąkę gryczaną i połącz na gęste ciasto.',
      'Rozgrzej patelnię i posmaruj ją cienko olejem. Nakładaj po łyżce ciasta i smaż placuszki po 2 minuty z każdej strony na średnim ogniu.',
      'Podawaj placuszki z jogurtem naturalnym i borówkami.',
    ],
    photo:
      'Stack of small golden buckwheat banana pancakes with a spoonful of natural yogurt and fresh blueberries',
  },
  {
    plan: 'SN-004',
    title: 'Hash z batatów z jajkiem sadzonym i awokado',
    description:
      'Chrupiące kostki batata podsmażone z czerwoną cebulą i papryką, z jajkiem sadzonym i plastrami awokado na wierzchu. Kolorowe, sycące śniadanie z jednej patelni, bez glutenu i nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'POTATOES',
    ingredients: [
      ['batat', 400, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['oliwa z oliwek', 20, 'ml'],
      ['jajko', 4, 'szt'],
      ['awokado', 1, 'szt'],
      ['papryka wędzona mielona', 2, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Obierz bataty i pokrój je w kostkę 1,5 cm. Cebulę pokrój w piórka, a paprykę w kostkę.',
      'Rozgrzej 15 ml oliwy na dużej patelni, wrzuć bataty i smaż na średnim ogniu 12 minut, co kilka minut mieszając, aż się zrumienią i zmiękną.',
      'Dodaj cebulę, paprykę i wędzoną paprykę, dopraw solą i pieprzem, smaż jeszcze 5 minut.',
      'Zrób w warzywach cztery wgłębienia, skrop je resztą oliwy i wbij jajka. Przykryj patelnię i smaż 4–5 minut, aż białka się zetną, a żółtka zostaną płynne.',
      'Awokado przekrój, wyjmij pestkę i pokrój miąższ w plastry. Ułóż na hashu i posyp posiekaną natką pietruszki.',
    ],
    photo:
      'Skillet of golden roasted sweet potato cubes with red onion and bell pepper, two fried eggs with runny yolks, sliced avocado and chopped parsley',
  },
  {
    plan: 'SN-005',
    title: 'Frittata z pieczonymi warzywami bez sera',
    description:
      'Puszysta frittata zapiekana z pieczoną cukinią, papryką, czerwoną cebulą i pomidorkami koktajlowymi, doprawiona ziołami prowansalskimi. Lekka, bez sera i bez glutenu, dobra też na zimno następnego dnia.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    equipment: ['OVEN'],
    ingredients: [
      ['jajko', 6, 'szt'],
      ['cukinia', 200, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cebula czerwona', 80, 'g'],
      ['pomidor koktajlowy', 150, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['zioła prowansalskie', 2, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Cukinię pokrój w półplasterki, paprykę w paski, cebulę w piórka, a pomidorki przekrój na pół.',
      'Wymieszaj cukinię, paprykę i cebulę z oliwą i ziołami prowansalskimi, rozłóż w naczyniu żaroodpornym lub na patelni z metalową rączką i piecz 15 minut.',
      'W misce roztrzep jajka z solą i pieprzem.',
      'Wyjmij warzywa, zmniejsz temperaturę do 180°C, ułóż na nich pomidorki i zalej jajkami.',
      'Piecz frittatę 15–18 minut, aż środek się zetnie, a brzegi lekko zrumienią. Odstaw na 3 minuty i pokrój w kawałki.',
    ],
    photo:
      'Thick golden baked frittata in a skillet studded with roasted zucchini, red pepper strips, red onion and blistered cherry tomato halves',
  },
  {
    plan: 'SN-006',
    title: 'Chleb bezglutenowy z pastą z awokado i jajkiem',
    description:
      'Chrupiące kromki chleba bezglutenowego z kremową pastą z awokado, limonki i szczypiorku, z połówkami jajka na twardo i pomidorkami. Szybkie, sycące śniadanie bez glutenu i nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    ingredients: [
      ['chleb bezglutenowy', 160, 'g'],
      ['awokado', 1, 'szt'],
      ['jajko', 2, 'szt'],
      ['limonka', 20, 'g'],
      ['pomidor koktajlowy', 100, 'g'],
      ['szczypiorek', 5, 'g'],
      ['płatki chili', 1, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Jajka włóż do wrzącej wody i gotuj 9 minut, potem przełóż do zimnej wody, obierz i przekrój na pół.',
      'Awokado przekrój, wyjmij pestkę i wydrąż miąższ do miski. Rozgnieć widelcem z sokiem z limonki, solą, pieprzem i połową posiekanego szczypiorku.',
      'Kromki chleba bezglutenowego opiecz w tosterze albo na suchej patelni po 2 minuty z każdej strony.',
      'Posmaruj pieczywo pastą z awokado, ułóż połówki jajek i przekrojone pomidorki, posyp resztą szczypiorku i płatkami chili.',
    ],
    photo:
      'Toasted gluten-free bread slices spread with chunky green avocado mash, topped with halved hard-boiled eggs, cherry tomato halves, chives and chili flakes',
    vessel: 'board',
  },
  {
    plan: 'SN-007',
    title: 'Ryżanka na napoju migdałowym z jabłkiem i cynamonem',
    description:
      'Kremowy ryż gotowany powoli na napoju migdałowym, z duszonym jabłkiem, cynamonem i prażonymi, posiekanymi migdałami. Smak dzieciństwa w wersji roślinnej, bez glutenu i bez mleka krowiego.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PORRIDGE',
    ingredients: [
      ['ryż biały', 100, 'g'],
      ['mleko migdałowe', 500, 'ml'],
      ['jabłko', 250, 'g'],
      ['migdał', 20, 'g'],
      ['syrop klonowy', 20, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Przepłucz ryż na sitku. Wsyp go do garnka, wlej napój migdałowy i zagotuj, cały czas mieszając.',
      'Zmniejsz ogień i gotuj pod przykryciem 20–25 minut, co kilka minut mieszając, aż ryż będzie miękki i kremowy.',
      'W tym czasie obierz jabłko, pokrój je w kostkę i podduś na małej patelni z połową cynamonu i łyżką wody przez 5–6 minut.',
      'Migdały posiekaj i podpraż na suchej patelni na złoto.',
      'Wmieszaj do ryżu syrop klonowy, przełóż do misek, dodaj jabłko, posyp migdałami i resztą cynamonu.',
    ],
    photo:
      'Creamy rice pudding topped with soft cinnamon-stewed apple cubes, toasted chopped almonds and a dusting of cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'SN-008',
    title: 'Wafle ryżowe z hummusem, ogórkiem i rzodkiewką',
    description:
      'Chrupiące wafle ryżowe posmarowane hummusem, z plasterkami świeżego ogórka, rzodkiewki i prażonymi pestkami dyni. Śniadanie gotowe w dziesięć minut, roślinne i bez glutenu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    ingredients: [
      ['wafel ryżowy', 60, 'g'],
      ['hummus', 100, 'g'],
      ['ogórek', 150, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['pestki dyni', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pestki dyni podpraż na suchej patelni przez 2–3 minuty, aż zaczną strzelać.',
      'Ogórek i rzodkiewki umyj i pokrój w cienkie plasterki.',
      'Posmaruj wafle ryżowe grubą warstwą hummusu.',
      'Ułóż na nich na przemian plasterki ogórka i rzodkiewki, posyp pestkami dyni i świeżo mielonym pieprzem.',
    ],
    photo:
      'Round rice cakes spread with creamy hummus, topped with thin cucumber and pink radish slices and toasted pumpkin seeds',
    vessel: 'board',
  },
  {
    plan: 'SN-009',
    title: 'Placki z kaszy jaglanej z warzywami i jogurtem kokosowym',
    description:
      'Złociste placki z ugotowanej kaszy jaglanej, startej marchewki i cukinii, związane mąką z ciecierzycy i podane z jogurtem kokosowym z koperkiem. Roślinne śniadanie bez glutenu, dobre też na zimno.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    ingredients: [
      ['kasza jaglana', 100, 'g'],
      ['marchew', 100, 'g'],
      ['cukinia', 150, 'g'],
      ['cebula dymka', 30, 'g'],
      ['mąka z ciecierzycy', 40, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['jogurt kokosowy', 120, 'g'],
      ['koperek', 5, 'g'],
      ['sól', 1.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przepłucz kaszę jaglaną gorącą wodą, zalej 250 ml wody i gotuj pod przykryciem 15 minut. Odstaw na 5 minut, żeby lekko przestygła.',
      'Marchew i cukinię zetrzyj na tarce o dużych oczkach, cukinię odciśnij z soku. Dymkę posiekaj.',
      'Wymieszaj kaszę z warzywami, mąką z ciecierzycy, solą i pieprzem, dolej 2–3 łyżki wody, żeby masa była zwarta i lepiąca.',
      'Rozgrzej olej na patelni. Formuj niewielkie placki, spłaszczaj je łyżką i smaż na średnim ogniu po 3–4 minuty z każdej strony, aż będą złociste.',
      'Wymieszaj jogurt kokosowy z posiekanym koperkiem i podawaj z ciepłymi plackami.',
    ],
    photo:
      'Golden millet fritters flecked with grated carrot and zucchini, served with a bowl of white coconut yogurt sprinkled with fresh dill',
  },
  {
    plan: 'SN-010',
    title: 'Omlet z ziołami i wędzonym łososiem',
    description:
      'Delikatny omlet z dużą ilością świeżego szczypiorku, koperku i natki, podany z plastrami wędzonego łososia i rukolą. Eleganckie, sycące śniadanie w kwadrans, bez glutenu i nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 5, 'szt'],
      ['łosoś wędzony', 100, 'g'],
      ['szczypiorek', 5, 'g'],
      ['koperek', 5, 'g'],
      ['natka pietruszki', 5, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Posiekaj drobno szczypiorek, koperek i natkę pietruszki.',
      'Roztrzep jajka z ziołami i pieprzem; nie sól, bo łosoś jest słony.',
      'Rozgrzej połowę oliwy na patelni, wlej połowę masy jajecznej i smaż na średnim ogniu 3–4 minuty, aż spód się zetnie, a wierzch będzie jeszcze wilgotny. Tak samo usmaż drugi omlet.',
      'Na połowie każdego omletu ułóż plastry łososia i garść rukoli, złóż na pół i od razu podawaj.',
    ],
    photo:
      'Folded soft herb omelette speckled with chives and dill, filled with pink smoked salmon slices and fresh arugula',
  },
  {
    plan: 'SN-011',
    title: 'Jajka sadzone na pieczonych ziemniakach z boczkiem',
    description:
      'Rumiane ziemniaki pieczone z chrupiącym boczkiem, cebulą i rozmarynem, z jajkami sadzonymi na wierzchu. Porządne, weekendowe śniadanie na długi dzień, bez glutenu i bez nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 50,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    equipment: ['OVEN'],
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['boczek', 60, 'g'],
      ['cebula', 80, 'g'],
      ['jajko', 4, 'szt'],
      ['olej rzepakowy', 15, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['rozmaryn suszony', 1, 'g'],
      ['szczypiorek', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C. Ziemniaki umyj dokładnie i pokrój w kostkę 2 cm, nie obierając.',
      'Wymieszaj ziemniaki z 10 ml oleju, papryką, rozmarynem, solą i pieprzem, rozłóż na blasze z papierem i piecz 20 minut.',
      'Boczek pokrój w paski, a cebulę w piórka. Dorzuć je do ziemniaków, przemieszaj i piecz jeszcze 12–15 minut, aż ziemniaki będą rumiane, a boczek chrupiący.',
      'Pod koniec pieczenia rozgrzej resztę oleju na patelni i usmaż jajka sadzone, 3–4 minuty, aż białka się zetną.',
      'Rozłóż ziemniaki z boczkiem na talerze, na wierzchu ułóż jajka i posyp posiekanym szczypiorkiem.',
    ],
    photo:
      'Crispy golden roasted potato cubes with bits of bacon and caramelized onion, topped with two sunny-side-up eggs and chopped chives',
  },
  {
    plan: 'SN-012',
    title: 'Pieczone jabłka z płatkami jaglanymi i orzechami',
    description:
      'Całe jabłka faszerowane kruszonką z płatków jaglanych, orzechów włoskich, rodzynek i cynamonu, upieczone do miękkości i podane z jogurtem sojowym. Rozgrzewające, naturalnie słodkie śniadanie na chłodne poranki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 45,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    equipment: ['OVEN'],
    ingredients: [
      ['jabłko', 600, 'g'],
      ['płatki jaglane', 40, 'g'],
      ['orzech włoski', 25, 'g'],
      ['rodzynka', 20, 'g'],
      ['syrop klonowy', 25, 'g'],
      ['olej kokosowy', 10, 'g'],
      ['cynamon', 2, 'g'],
      ['jogurt sojowy', 150, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 180°C. Jabłka umyj, odetnij wierzch i wydrąż gniazda nasienne, zostawiając dno.',
      'Orzechy posiekaj i wymieszaj z płatkami jaglanymi, rodzynkami, cynamonem, syropem klonowym i roztopionym olejem kokosowym.',
      'Nafaszeruj jabłka nadzieniem, resztę rozsyp wokół nich w naczyniu żaroodpornym i wlej na dno 50 ml wody.',
      'Piecz 30–35 minut, aż jabłka zmiękną, a wierzch nadzienia się zrumieni.',
      'Podawaj ciepłe jabłka z łyżką jogurtu sojowego, polane sokiem z dna naczynia.',
    ],
    photo:
      'Two soft baked apples with wrinkled red skin stuffed with golden millet flake, walnut and raisin crumble, with a dollop of white soy yogurt',
  },
  {
    plan: 'SN-013',
    title: 'Jogurt naturalny z otrębami i jabłkiem',
    description:
      'Gęsty jogurt naturalny z otrębami owsianymi, startym jabłkiem, odrobiną miodu i cynamonem. Proste, lekkie śniadanie z błonnikiem, które zrobisz w pięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'YOGURT',
    ingredients: [
      ['jogurt naturalny', 300, 'g'],
      ['otręby owsiane', 30, 'g'],
      ['jabłko', 200, 'g'],
      ['miód', 10, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Jabłko umyj, usuń gniazdo nasienne i zetrzyj na tarce o dużych oczkach albo pokrój w drobną kostkę.',
      'Wymieszaj jogurt z otrębami owsianymi i odstaw na 2–3 minuty, żeby otręby lekko napęczniały.',
      'Przełóż jogurt do miseczek, dodaj jabłko, polej miodem i posyp cynamonem.',
    ],
    photo:
      'Thick white natural yogurt mixed with oat bran, topped with fresh grated apple, a thin drizzle of honey and cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'SN-014',
    title: 'Jajko na miękko z warzywami i kromką chleba',
    description:
      'Jajka ugotowane na miękko z płynnym żółtkiem, podane z kromką chleba żytniego i chrupiącymi warzywami: pomidorem, ogórkiem i rzodkiewką. Klasyczne, lekkie śniadanie bez masła.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 4, 'szt'],
      ['chleb żytni', 80, 'g'],
      ['pomidor', 200, 'g'],
      ['ogórek', 150, 'g'],
      ['rzodkiewka', 60, 'g'],
      ['szczypiorek', 5, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Zagotuj wodę w garnku, delikatnie włóż jajka łyżką i gotuj dokładnie 5 minut od ponownego zawrzenia.',
      'W tym czasie pokrój pomidor w ósemki, ogórek w plastry, a rzodkiewki na połówki. Posiekaj szczypiorek.',
      'Jajka przełóż na chwilę do zimnej wody i wstaw do kieliszków.',
      'Ułóż warzywa i kromki chleba na talerzach, posyp szczypiorkiem, a jajka dopraw solą i pieprzem po ścięciu czubka.',
    ],
    photo:
      'Soft-boiled eggs in egg cups with runny orange yolks, a slice of dark rye bread, tomato wedges, cucumber slices, halved radishes and chives',
  },
  {
    plan: 'SN-015',
    title: 'Grzanka z pomidorem i bazylią',
    description:
      'Chrupiąca ciabatta natarta czosnkiem, z soczystymi pomidorami, świeżą bazylią, oliwą i kroplą octu balsamicznego. Włoskie bruschetta na śniadanie, lekkie i gotowe w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['ciabatta', 120, 'g'],
      ['pomidor', 300, 'g'],
      ['bazylia', 10, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['ocet balsamiczny', 5, 'ml'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pomidory pokrój w drobną kostkę, odlej nadmiar soku. Wymieszaj z porwaną bazylią, 10 ml oliwy, octem balsamicznym, solą i pieprzem.',
      'Ciabattę pokrój ukośnie na kromki i skrop resztą oliwy.',
      'Opiecz kromki na rozgrzanej suchej patelni grillowej po 2 minuty z każdej strony, aż będą chrupiące i w paski.',
      'Przekrój ząbek czosnku i natrzyj nim ciepłe grzanki.',
      'Nałóż na grzanki pomidory z bazylią tuż przed podaniem, żeby pieczywo nie zmiękło.',
    ],
    photo:
      'Grilled ciabatta slices with char marks topped with glistening diced red tomatoes, torn fresh basil leaves and a drizzle of olive oil',
    vessel: 'board',
  },
  {
    plan: 'SN-016',
    title: 'Jogurt grecki z malinami i siemieniem lnianym',
    description:
      'Gęsty jogurt grecki z soczystymi malinami, mielonym siemieniem lnianym i odrobiną miodu. Kremowe, białkowe śniadanie w pięć minut, które trzyma sytość do obiadu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'YOGURT',
    ingredients: [
      ['jogurt grecki', 300, 'g'],
      ['malina', 150, 'g'],
      ['siemię lniane', 15, 'g'],
      ['miód', 10, 'g'],
    ],
    steps: [
      'Siemię lniane zmiel w młynku do kawy albo użyj już mielonego.',
      'Maliny opłucz delikatnie i osusz na ręczniku papierowym. Połowę rozgnieć widelcem.',
      'Wymieszaj jogurt grecki z rozgniecionymi malinami, żeby powstały różowe smugi.',
      'Przełóż do miseczek, ułóż resztę malin, posyp siemieniem lnianym i polej miodem.',
    ],
    photo:
      'Thick white Greek yogurt swirled with pink raspberry streaks, topped with whole fresh raspberries, ground flaxseed and a drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'SN-017',
    title: 'Kefir z płatkami owsianymi i truskawkami',
    description:
      'Chłodny kefir z namoczonymi płatkami owsianymi, świeżymi truskawkami i łyżeczką miodu. Orzeźwiające, lekkie śniadanie, które przygotujesz w dziesięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'YOGURT',
    ingredients: [
      ['kefir', 400, 'ml'],
      ['płatki owsiane', 60, 'g'],
      ['truskawka', 200, 'g'],
      ['miód', 10, 'g'],
    ],
    steps: [
      'Wsyp płatki owsiane do misek, zalej kefirem, wymieszaj i odstaw na 8–10 minut, żeby zmiękły.',
      'Truskawki umyj, usuń szypułki i pokrój na ćwiartki.',
      'Ułóż truskawki na płatkach z kefirem i polej miodem tuż przed podaniem.',
    ],
    photo:
      'Creamy kefir with softened rolled oats topped with bright red quartered strawberries and a thin drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'SN-018',
    title: 'Wafle ryżowe z twarożkiem i rzodkiewką',
    description:
      'Chrupiące wafle ryżowe z puszystym twarożkiem ze szczypiorkiem i świeżą rzodkiewką. Lekkie, wiosenne w smaku śniadanie bez glutenu, gotowe w dziesięć minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SANDWICH',
    ingredients: [
      ['wafel ryżowy', 40, 'g'],
      ['twarożek', 150, 'g'],
      ['jogurt naturalny', 50, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgnieć twarożek widelcem z jogurtem naturalnym na puszystą pastę.',
      'Posiekaj szczypiorek, a rzodkiewki pokrój w cienkie plasterki.',
      'Wmieszaj do twarożku większość szczypiorku i dopraw pieprzem.',
      'Posmaruj wafle ryżowe pastą, ułóż plasterki rzodkiewki i posyp resztą szczypiorku.',
    ],
    photo:
      'Rice cakes spread with fluffy white cottage cheese and chives, topped with overlapping thin pink radish slices',
    vessel: 'board',
  },
  {
    plan: 'SN-019',
    title: 'Jajka zapiekane w papryce',
    description:
      'Połówki czerwonej papryki pieczone z wbitym jajkiem, pomidorkami koktajlowymi i oregano. Efektowne, a proste śniadanie z piekarnika, lekkie, bez glutenu i bez nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    equipment: ['OVEN'],
    ingredients: [
      ['papryka czerwona', 320, 'g'],
      ['jajko', 4, 'szt'],
      ['pomidor koktajlowy', 100, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['oregano', 1, 'g'],
      ['szczypiorek', 5, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Przekrój papryki wzdłuż na pół razem z szypułką i usuń gniazda nasienne.',
      'Ułóż połówki w naczyniu żaroodpornym, posmaruj z zewnątrz oliwą i podpiecz 10 minut.',
      'Wyjmij papryki, wbij do każdej połówki po jajku, dodaj przekrojone pomidorki, posyp oregano, solą i pieprzem.',
      'Piecz w 190°C 12–15 minut, aż białka się zetną, a żółtka pozostaną lekko płynne.',
      'Posyp posiekanym szczypiorkiem i podawaj od razu.',
    ],
    photo:
      'Roasted red bell pepper halves each cradling a baked egg with a glossy yolk, cherry tomato halves, oregano and chopped chives',
  },
  {
    plan: 'SN-020',
    title: 'Omlet z pomidorem i szczypiorkiem',
    description:
      'Puszysty omlet z soczystymi plastrami pomidora i świeżym szczypiorkiem, usmażony na odrobinie oliwy. Lekkie, szybkie śniadanie bez glutenu i nabiału, gotowe w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 5, 'szt'],
      ['pomidor', 200, 'g'],
      ['szczypiorek', 10, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Pomidor pokrój w cienkie plastry, a szczypiorek posiekaj.',
      'Roztrzep jajka z solą, pieprzem i połową szczypiorku.',
      'Rozgrzej połowę oliwy na patelni, wlej połowę masy jajecznej, ułóż na niej połowę plastrów pomidora i smaż pod przykryciem na małym ogniu 4–5 minut, aż wierzch się zetnie.',
      'Zsuń omlet na talerz i tak samo usmaż drugi. Posyp resztą szczypiorku.',
    ],
    photo:
      'Fluffy golden omelette topped with thin red tomato slices and a generous sprinkle of fresh chopped chives',
  },
  {
    plan: 'SN-021',
    title: 'Serek wiejski z jabłkiem i cynamonem',
    description:
      'Serek wiejski z chrupiącym jabłkiem, cynamonem, odrobiną miodu i posiekanymi orzechami włoskimi. Białkowe śniadanie w pięć minut, które smakuje jak deser.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 5,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'YOGURT',
    ingredients: [
      ['serek wiejski', 400, 'g'],
      ['jabłko', 200, 'g'],
      ['orzech włoski', 10, 'g'],
      ['miód', 10, 'g'],
      ['cynamon', 2, 'g'],
    ],
    steps: [
      'Jabłko umyj, usuń gniazdo nasienne i pokrój w drobną kostkę.',
      'Orzechy włoskie posiekaj grubo.',
      'Przełóż serek wiejski do miseczek, dodaj jabłko, posyp cynamonem i orzechami, polej miodem.',
    ],
    photo:
      'Bowl of cottage cheese curds topped with fresh diced apple, chopped walnuts, a dusting of cinnamon and a drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'SN-022',
    title: 'Kanapki z pieczonym indykiem i warzywami na chlebie żytnim',
    description:
      'Kromki chleba żytniego z musztardą, plastrami domowego pieczonego indyka, sałatą, pomidorem i ogórkiem. Białkowa alternatywa dla sklepowej wędliny, lekka i bez nabiału.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SANDWICH',
    equipment: ['OVEN'],
    ingredients: [
      ['filet z indyka', 200, 'g'],
      ['chleb żytni', 120, 'g'],
      ['sałata lodowa', 40, 'g'],
      ['pomidor', 150, 'g'],
      ['ogórek', 100, 'g'],
      ['musztarda', 10, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['majeranek', 1, 'g'],
      ['papryka słodka mielona', 1, 'g'],
      ['sól', 0.5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 200°C. Filet z indyka natrzyj oliwą, majerankiem, papryką, solą i pieprzem.',
      'Piecz indyka w małym naczyniu 18–20 minut, aż sok będzie przezroczysty. Odstaw na 5 minut i pokrój w cienkie plastry.',
      'W tym czasie pokrój pomidor i ogórek w plastry, a sałatę porwij na listki.',
      'Posmaruj kromki chleba żytniego cienko musztardą, ułóż sałatę, indyka, pomidor i ogórek.',
    ],
    photo:
      'Open-faced dark rye bread sandwiches with lettuce, thin slices of roasted turkey breast, tomato and cucumber slices',
    vessel: 'board',
  },
  {
    plan: 'SN-023',
    title: 'Owsianka proteinowa na napoju sojowym z masłem orzechowym',
    description:
      'Gęsta owsianka ugotowana na napoju sojowym z miksowanym tofu, z łyżką masła orzechowego i malinami. Roślinne białko w kremowej, sycącej formie, bez odżywek.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    equipment: ['BLENDER'],
    ingredients: [
      ['płatki owsiane', 80, 'g'],
      ['mleko sojowe', 400, 'ml'],
      ['tofu', 150, 'g'],
      ['masło orzechowe', 30, 'g'],
      ['malina', 100, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Zmiksuj tofu blenderem ze 150 ml napoju sojowego na gładki krem.',
      'Wsyp płatki owsiane do garnka, wlej resztę napoju sojowego i gotuj na małym ogniu 5 minut, mieszając.',
      'Wmieszaj krem z tofu i cynamon, podgrzewaj jeszcze 2 minuty, aż owsianka zgęstnieje, ale nie zagotuj jej gwałtownie.',
      'Przełóż do misek, dodaj po łyżce masła orzechowego i ułóż maliny.',
    ],
    photo:
      'Thick creamy oatmeal topped with a swirl of peanut butter and fresh red raspberries, dusted with cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'SN-024',
    title: 'Owsianka z tahini, bananem i sezamem',
    description:
      'Kremowa owsianka na napoju migdałowym z plasterkami banana, polana pastą tahini i posypana prażonym sezamem. Orzechowa w smaku, sycąca i całkowicie roślinna.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    ingredients: [
      ['płatki owsiane', 80, 'g'],
      ['mleko migdałowe', 400, 'ml'],
      ['banan', 2, 'szt'],
      ['tahini', 30, 'g'],
      ['sezam', 10, 'g'],
      ['syrop klonowy', 15, 'g'],
      ['cynamon', 1, 'g'],
    ],
    steps: [
      'Sezam podpraż na suchej patelni 2–3 minuty na złoty kolor.',
      'Płatki owsiane zalej napojem migdałowym, dodaj cynamon i gotuj na małym ogniu 5–6 minut, mieszając.',
      'Jednego banana rozgnieć widelcem i wmieszaj do owsianki, drugiego pokrój w plasterki.',
      'Przełóż owsiankę do misek, ułóż plasterki banana, polej tahini wymieszanym z syropem klonowym i posyp sezamem.',
    ],
    photo:
      'Creamy oatmeal topped with banana slices, a drizzle of beige tahini and toasted golden sesame seeds',
    vessel: 'bowl',
  },
  {
    plan: 'SN-025',
    title: 'Kanapki z pastą z ciecierzycy i suszonych pomidorów',
    description:
      'Pełnoziarniste pieczywo z aromatyczną pastą z ciecierzycy, suszonych pomidorów, czosnku i cytryny, z garścią rukoli. Roślinne, sycące kanapki, które dobrze znoszą drogę w pudełku.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['ciecierzyca z puszki', 200, 'g'],
      ['pomidor suszony w oleju', 40, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['kmin rzymski', 1, 'g'],
      ['chleb pełnoziarnisty', 140, 'g'],
      ['rukola', 30, 'g'],
    ],
    steps: [
      'Ciecierzycę odcedź i przepłucz. Suszone pomidory odsącz z zalewy i pokrój na mniejsze kawałki.',
      'Zmiksuj blenderem ciecierzycę, pomidory, czosnek, sok z cytryny, oliwę i kmin rzymski na gęstą pastę, w razie potrzeby dodaj 2 łyżki wody.',
      'Pokrój chleb na kromki i grubo posmaruj pastą.',
      'Na wierzchu ułóż rukolę i podawaj od razu albo przełóż kanapki do pudełka.',
    ],
    photo:
      'Wholegrain bread slices spread with thick orange-red chickpea and sun-dried tomato paste, topped with fresh arugula leaves',
    vessel: 'board',
  },
  {
    plan: 'SN-026',
    title: 'Placki bananowo-owsiane bez jajek z musem jabłkowym',
    description:
      'Miękkie placuszki z dojrzałych bananów i płatków owsianych, bez jajek i mleka krowiego, podane z musem jabłkowym. Naturalnie słodkie śniadanie, które dzieci jedzą z ręki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    ingredients: [
      ['banan', 2, 'szt'],
      ['płatki owsiane', 100, 'g'],
      ['mleko sojowe', 150, 'ml'],
      ['proszek do pieczenia', 4, 'g'],
      ['cynamon', 1, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['mus jabłkowy', 150, 'g'],
    ],
    steps: [
      'Płatki owsiane zalej napojem sojowym i odstaw na 10 minut, żeby napęczniały.',
      'Banany obierz i rozgnieć widelcem na gładką masę. Wymieszaj z płatkami, cynamonem i proszkiem do pieczenia.',
      'Rozgrzej patelnię i posmaruj ją cienko olejem. Nakładaj po łyżce ciasta i smaż placki na średnim ogniu po 2–3 minuty z każdej strony, aż się zrumienią.',
      'Podawaj ciepłe placki z musem jabłkowym.',
    ],
    photo:
      'Stack of small golden banana oat pancakes served with a bowl of smooth pale apple sauce',
  },
  {
    plan: 'SN-027',
    title: 'Tost z awokado, ciecierzycą i pestkami dyni',
    description:
      'Chrupiący tost z pełnoziarnistego chleba z pastą z awokado, ciecierzycą podsmażoną z wędzoną papryką i prażonymi pestkami dyni. Roślinne śniadanie pełne białka i dobrych tłuszczów.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    ingredients: [
      ['chleb pełnoziarnisty', 140, 'g'],
      ['awokado', 1, 'szt'],
      ['ciecierzyca z puszki', 120, 'g'],
      ['pestki dyni', 15, 'g'],
      ['cytryna', 20, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['papryka wędzona mielona', 1, 'g'],
      ['płatki chili', 1, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Ciecierzycę odcedź, osusz i podsmaż na oliwie z wędzoną papryką przez 5–6 minut, aż lekko chrupnie. Pod koniec wrzuć na patelnię pestki dyni.',
      'Awokado rozgnieć widelcem z sokiem z cytryny i solą.',
      'Kromki chleba opiecz w tosterze albo na suchej patelni po 2 minuty z każdej strony.',
      'Posmaruj tosty awokado, ułóż ciecierzycę z pestkami dyni i posyp płatkami chili.',
    ],
    photo:
      'Wholegrain toast spread with green avocado mash, topped with smoky golden chickpeas, toasted pumpkin seeds and red chili flakes',
    vessel: 'board',
  },
  {
    plan: 'SN-028',
    title: 'Naleśniki wegańskie z masłem orzechowym i truskawkami',
    description:
      'Cienkie naleśniki na napoju sojowym, bez jajek, posmarowane masłem orzechowym i zawinięte z plastrami truskawek. Roślinna wersja klasyka na leniwy weekend.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    ingredients: [
      ['mąka pszenna', 120, 'g'],
      ['mleko sojowe', 300, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['masło orzechowe', 40, 'g'],
      ['truskawka', 250, 'g'],
      ['syrop klonowy', 15, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z napojem sojowym, 100 ml wody gazowanej i 10 ml oleju na gładkie, rzadkie ciasto. Odstaw na 10 minut.',
      'Truskawki umyj, usuń szypułki i pokrój w plasterki.',
      'Rozgrzej patelnię, posmaruj ją cienko resztą oleju i smaż cienkie naleśniki po 1–2 minuty z każdej strony.',
      'Posmaruj każdy naleśnik masłem orzechowym, ułóż truskawki, zwiń w rulon lub złóż w trójkąt i polej syropem klonowym.',
    ],
    photo:
      'Folded thin crepes spread with peanut butter and filled with fresh sliced strawberries, drizzled with maple syrup',
  },
  {
    plan: 'SN-029',
    title: 'Domowa granola z orzechami i jogurtem sojowym',
    description:
      'Chrupiąca granola z płatków owsianych, orzechów laskowych, migdałów i pestek dyni, pieczona z syropem klonowym, podana z jogurtem sojowym i borówkami. Łatwo upiec na zapas na cały tydzień.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    equipment: ['OVEN'],
    ingredients: [
      ['płatki owsiane', 80, 'g'],
      ['orzech laskowy', 20, 'g'],
      ['migdał', 20, 'g'],
      ['pestki dyni', 10, 'g'],
      ['syrop klonowy', 25, 'g'],
      ['olej kokosowy', 10, 'g'],
      ['cynamon', 1, 'g'],
      ['jogurt sojowy', 300, 'g'],
      ['borówka', 100, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 160°C. Orzechy laskowe i migdały posiekaj grubo.',
      'Roztop olej kokosowy, wymieszaj z syropem klonowym i cynamonem, a potem z płatkami, orzechami i pestkami dyni.',
      'Rozłóż masę cienko na blasze z papierem i piecz 20–25 minut, mieszając w połowie, aż granola będzie złota.',
      'Wystudź granolę na blasze, aż stwardnieje, i połam na grudki.',
      'Podawaj z jogurtem sojowym i borówkami. Granola w szczelnym słoiku zachowa chrupkość do 2 tygodni, więc śmiało upiecz od razu podwójną porcję.',
    ],
    photo:
      'Bowl of white soy yogurt topped with golden clustered homemade granola with hazelnuts, almonds and pumpkin seeds and fresh blueberries',
    vessel: 'bowl',
  },
  {
    plan: 'SN-030',
    title: 'Kanapki z pastą z białej fasoli i pieczonej papryki',
    description:
      'Chleb żytni z kremową pastą z białej fasoli i słodkiej pieczonej papryki z czosnkiem i wędzoną papryką, z listkami roszponki. Roślinne kanapki, które dobrze znoszą drogę w pudełku.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['OVEN', 'BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['fasola biała z puszki', 240, 'g'],
      ['papryka czerwona', 300, 'g'],
      ['czosnek', 1, 'szt'],
      ['cytryna', 15, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka wędzona mielona', 1, 'g'],
      ['chleb żytni', 140, 'g'],
      ['roszponka', 30, 'g'],
      ['sól', 0.5, 'g'],
    ],
    steps: [
      'Nagrzej piekarnik do 220°C. Paprykę przekrój, usuń gniazda nasienne, ułóż skórką do góry na blasze i piecz 20 minut, aż skórka sczernieje.',
      'Przełóż paprykę do miski, przykryj na 5 minut, a potem zdejmij skórkę.',
      'Fasolę odcedź i przepłucz. Zmiksuj blenderem z papryką, czosnkiem, sokiem z cytryny, oliwą, wędzoną papryką i solą na gładką pastę.',
      'Posmaruj kromki chleba żytniego pastą i ułóż na wierzchu roszponkę.',
    ],
    photo:
      'Slices of dark rye bread spread with smooth coral-orange white bean and roasted red pepper paste, topped with fresh lamb lettuce leaves',
    vessel: 'board',
  },
];
