/**
 * Katalog 1000 — część SN-b: śniadania SN-031 … SN-060 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [
  {
    name: 'muffin angielski',
    category: 'piekarnia',
    allergens: ['gluten', 'milk', 'lactose'],
    dietTags: ['GLUTEN_GRAIN', 'GRAIN', 'PROCESSED', 'DAIRY'],
    note: 'Płaska drożdżowa bułeczka do tostowania (English muffin); Selgros, Makro, sezonowo Lidl.',
    nutrition: {
      unit: 'g',
      kcal: 227,
      protein: 8.9,
      carbs: 41.6,
      sugars: 3.5,
      fat: 1.7,
      saturatedFat: 0.3,
      fiber: 2.6,
      sodiumMg: 440,
      gramsPerPiece: 60,
    },
  },
];

export const DEFS: Def[] = [
  // ── Wegańskie ──
  {
    plan: 'SN-031',
    title: 'Owsianka nocna z jabłkiem, cynamonem i jogurtem sojowym',
    description:
      'Płatki owsiane namoczone w napoju sojowym z jogurtem sojowym, tartym jabłkiem i cynamonem, podane z orzechami. Przygotujesz ją wieczorem w słoikach i rano tylko wyjmujesz z lodówki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    features: ['LUNCHBOX'],
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['mleko sojowe', 200, 'ml'],
      ['jogurt sojowy', 200, 'g'],
      ['jabłko', 200, 'g'],
      ['cynamon', 2, 'g'],
      ['syrop klonowy', 20, 'g'],
      ['orzech włoski', 20, 'g'],
    ],
    steps: [
      'Wymieszaj płatki owsiane z mlekiem sojowym, połową jogurtu sojowego, cynamonem i syropem klonowym.',
      'Umyj jabłko, połowę zetrzyj na tarce o grubych oczkach i wmieszaj do płatków, a drugą połowę pokrój w drobną kostkę.',
      'Przełóż owsiankę do dwóch słoików i wstaw do lodówki na noc — jeśli jesz od razu, odstaw ją na co najmniej 15 minut, aż płatki zmiękną.',
      'Przed podaniem nałóż na wierzch resztę jogurtu, kostkę jabłka i posiekane orzechy włoskie, oprósz cynamonem.',
    ],
    photo:
      'Creamy overnight oats with soy yogurt, topped with a dollop of white soy yogurt, diced fresh apple, chopped walnuts and a dusting of cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'SN-032',
    title: 'Kanapki z wędzonym tofu, pomidorem i szczypiorkiem',
    description:
      'Chleb żytni z musztardą, plastrami podsmażonego wędzonego tofu, soczystym pomidorem i szczypiorkiem. Wytrawne, sycące kanapki z dużą porcją roślinnego białka, gotowe w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    ingredients: [
      ['chleb żytni', 120, 'g'],
      ['tofu wędzone', 200, 'g'],
      ['pomidor', 200, 'g'],
      ['szczypiorek', 10, 'g'],
      ['musztarda', 10, 'g'],
      ['rukola', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Osusz tofu wędzone ręcznikiem papierowym i pokrój w plastry grubości około 5 mm.',
      'Rozgrzej suchą patelnię z powłoką i podsmaż plastry tofu po 2 minuty z każdej strony, aż lekko się zrumienią.',
      'Pokrój pomidor w plastry, a szczypiorek drobno posiekaj.',
      'Posmaruj kromki chleba żytniego cienko musztardą, ułóż rukolę, tofu i pomidor.',
      'Posyp kanapki szczypiorkiem i świeżo zmielonym pieprzem.',
    ],
    photo:
      'Open-faced rye bread sandwiches with golden pan-seared smoked tofu slices, red tomato rounds, arugula and chopped chives',
  },
  {
    plan: 'SN-033',
    title: 'Gofry wegańskie z owocami i syropem klonowym',
    description:
      'Chrupiące na zewnątrz, miękkie w środku gofry na napoju sojowym, bez jajek i masła. Podane z truskawkami, borówkami i syropem klonowym to weekendowe śniadanie, które smakuje wszystkim.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    equipment: ['WAFFLE_MAKER'],
    ingredients: [
      ['mąka pszenna', 150, 'g'],
      ['mleko sojowe', 250, 'ml'],
      ['olej rzepakowy', 30, 'ml'],
      ['cukier', 15, 'g'],
      ['cukier waniliowy', 8, 'g'],
      ['proszek do pieczenia', 8, 'g'],
      ['truskawka', 150, 'g'],
      ['borówka', 100, 'g'],
      ['syrop klonowy', 30, 'g'],
    ],
    steps: [
      'Wymieszaj w misce mąkę pszenną, proszek do pieczenia, cukier i cukier waniliowy.',
      'Wlej mleko sojowe i olej, połącz trzepaczką na gładkie, gęste ciasto i odstaw na 5 minut.',
      'Rozgrzej gofrownicę i posmaruj ją cienko olejem, jeśli nie ma powłoki.',
      'Nakładaj ciasto porcjami i piecz każdy gofr 4–5 minut, aż będzie złoty i chrupiący.',
      'W tym czasie umyj truskawki i borówki, truskawki przekrój na połówki.',
      'Podawaj gofry od razu z owocami, polane syropem klonowym.',
    ],
    photo:
      'Two crisp golden waffles topped with halved strawberries, fresh blueberries and a glossy drizzle of maple syrup',
  },
  {
    plan: 'SN-034',
    title: 'Pasta z czerwonej soczewicy z ogórkiem kiszonym na chlebie',
    description:
      'Gęsta pasta z czerwonej soczewicy z podsmażoną cebulą, koncentratem pomidorowym i majerankiem, podana na chlebie z chrupiącym ogórkiem kiszonym. Dobrze znosi drogę w pudełku i smakuje też na zimno.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'DIP',
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica czerwona', 120, 'g'],
      ['cebula', 60, 'g'],
      ['oliwa z oliwek', 5, 'ml'],
      ['koncentrat pomidorowy', 15, 'g'],
      ['majeranek', 1, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 100, 'g'],
      ['ogórek kiszony', 100, 'g'],
    ],
    steps: [
      'Przepłucz soczewicę na sitku, zalej 350 ml wody i gotuj 12–15 minut, aż się rozpadnie i wchłonie wodę.',
      'W tym czasie posiekaj cebulę i zeszklij ją na oliwie przez 5 minut, pod koniec dodaj koncentrat pomidorowy, kmin rzymski i majeranek.',
      'Połącz soczewicę z cebulą, rozgnieć widelcem albo zmiksuj na gładką pastę i dopraw pieprzem. Odstaw na chwilę, żeby zgęstniała.',
      'Pokrój ogórki kiszone w plasterki.',
      'Posmaruj kromki chleba żytniego grubo pastą i ułóż na wierzchu ogórki kiszone.',
    ],
    photo:
      'Rye bread slices thickly spread with orange red lentil paste, topped with thin rounds of pickled cucumber and a pinch of marjoram',
    vessel: 'board',
  },
  {
    plan: 'SN-035',
    title: 'Placki z ciecierzycy na słono z pomidorami',
    description:
      'Złote placki z mąki z ciecierzycy z kurkumą i kminem, podane z pomidorkami koktajlowymi i czosnkowym jogurtem sojowym. Wytrawne, bezglutenowe śniadanie na roślinnym białku.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PANCAKES',
    ingredients: [
      ['mąka z ciecierzycy', 150, 'g'],
      ['proszek do pieczenia', 4, 'g'],
      ['kurkuma', 1, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['cebula dymka', 30, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['pomidor koktajlowy', 200, 'g'],
      ['jogurt sojowy', 150, 'g'],
      ['czosnek', 1, 'szt'],
      ['natka pietruszki', 10, 'g'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Wymieszaj mąkę z ciecierzycy z proszkiem do pieczenia, kurkumą, kminem i solą. Wlej stopniowo około 200 ml wody i ubij trzepaczką na gładkie ciasto jak na naleśniki biszkoptowe.',
      'Posiekaj cebulę dymkę i połowę natki, wmieszaj do ciasta i odstaw na 5 minut.',
      'Rozgrzej patelnię, posmaruj ją cienko oliwą i smaż niewielkie placki po 2–3 minuty z każdej strony na średnim ogniu.',
      'Przeciśnij czosnek do jogurtu sojowego i wymieszaj z resztą posiekanej natki.',
      'Przekrój pomidorki koktajlowe na połówki i podawaj placki z pomidorami i sosem czosnkowym.',
    ],
    photo:
      'Stack of golden turmeric chickpea flour pancakes flecked with spring onion, with halved cherry tomatoes, a dollop of white garlic soy yogurt sauce and chopped parsley',
  },
  {
    plan: 'SN-036',
    title: 'Kanapki z pastą z tofu i szczypiorkiem',
    description:
      'Kremowa pasta z rozgniecionego tofu z jogurtem sojowym, kurkumą, musztardą i dużą ilością szczypiorku, podana na chlebie z rzodkiewką i ogórkiem. Roślinna odpowiedź na pastę jajeczną.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tofu', 200, 'g'],
      ['jogurt sojowy', 50, 'g'],
      ['szczypiorek', 15, 'g'],
      ['musztarda', 5, 'g'],
      ['kurkuma', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb żytni', 100, 'g'],
      ['rzodkiewka', 80, 'g'],
      ['ogórek', 100, 'g'],
    ],
    steps: [
      'Odsącz tofu, osusz je ręcznikiem papierowym i rozgnieć widelcem w misce na drobną kruszonkę.',
      'Dodaj jogurt sojowy, musztardę, kurkumę i pieprz, wymieszaj na kremową pastę.',
      'Posiekaj drobno szczypiorek i wmieszaj większość do pasty.',
      'Pokrój rzodkiewki i ogórek w cienkie plasterki.',
      'Posmaruj kromki chleba żytniego pastą, ułóż rzodkiewkę i ogórek, posyp resztą szczypiorku.',
    ],
    photo:
      'Rye bread slices spread with pale yellow tofu paste flecked with chives, topped with thin radish and cucumber slices',
  },
  // ── Kuchnie świata ──
  {
    plan: 'SN-037',
    title: 'Chilaquiles z jajkiem sadzonym i salsą',
    description:
      'Meksykańskie śniadanie z chrupiących chipsów kukurydzianych obtoczonych w gorącym sosie pomidorowym z chili, z jajkiem sadzonym, kruszoną fetą, awokado i kolendrą. Pikantne i bardzo sycące.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'EGGS',
    ingredients: [
      ['pomidor krojony z puszki', 300, 'g'],
      ['salsa pomidorowa', 50, 'g'],
      ['cebula', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['papryczka chili', 15, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['chips kukurydziany', 70, 'g'],
      ['jajko', 2, 'szt'],
      ['ser feta', 30, 'g'],
      ['awokado', 1, 'szt'],
      ['kolendra', 10, 'g'],
    ],
    steps: [
      'Posiekaj cebulę, czosnek i papryczkę chili. Zeszklij je na połowie oleju w szerokiej patelni przez 3 minuty.',
      'Dodaj pomidory z puszki i salsę pomidorową, gotuj sos 8 minut, aż lekko zgęstnieje.',
      'Na drugiej patelni usmaż na reszcie oleju jajka sadzone, około 3 minut, aż białko się zetnie, a żółtko zostanie płynne.',
      'Wsyp chipsy kukurydziane do sosu i wymieszaj delikatnie, tylko do obtoczenia — mają zostać lekko chrupiące.',
      'Przełóż chilaquiles na talerze, ułóż na nich jajka, pokruszoną fetę, plastry awokado i listki kolendry. Podawaj od razu.',
    ],
    photo:
      'Corn tortilla chips tossed in chunky red tomato chili sauce, topped with a sunny-side-up egg, crumbled white feta, avocado slices and cilantro leaves',
  },
  {
    plan: 'SN-038',
    title: 'Burrito śniadaniowe z jajecznicą, fasolą i serem',
    description:
      'Duża pszenna tortilla zawinięta wokół puszystej jajecznicy z papryką, czarnej fasoli z kminem i roztopionego cheddara. Śniadanie w ręce, które dobrze znosi drogę do pracy w pudełku.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'SANDWICH',
    features: ['LUNCHBOX'],
    ingredients: [
      ['tortilla pszenna', 2, 'szt'],
      ['jajko', 4, 'szt'],
      ['fasola czarna z puszki', 100, 'g'],
      ['ser cheddar', 30, 'g'],
      ['papryka czerwona', 100, 'g'],
      ['cebula dymka', 20, 'g'],
      ['salsa pomidorowa', 30, 'g'],
      ['kmin rzymski', 1, 'g'],
      ['olej rzepakowy', 10, 'ml'],
    ],
    steps: [
      'Pokrój paprykę w drobną kostkę, a dymkę w krążki. Odsącz i przepłucz fasolę.',
      'Podsmaż paprykę na oleju 3 minuty, dodaj fasolę i kmin rzymski, podgrzewaj 2 minuty i lekko rozgnieć część fasoli.',
      'Roztrzep jajka, wlej na patelnię i mieszaj na małym ogniu 2–3 minuty, aż jajecznica się zetnie, ale zostanie wilgotna. Wmieszaj dymkę.',
      'Podgrzej tortille na suchej patelni po 20 sekund z każdej strony.',
      'Rozłóż na tortillach jajecznicę z fasolą, posyp startym cheddarem i dodaj łyżkę salsy.',
      'Zawiń boki do środka i zroluj ciasno. Do pudełka zawiń burrito w papier do pieczenia.',
    ],
    photo:
      'Breakfast burrito in a warm flour tortilla cut in half, showing soft scrambled eggs with spring onion, black beans, diced red pepper, melted cheddar and a streak of red tomato salsa inside',
    vessel: 'board',
  },
  {
    plan: 'SN-039',
    title: 'Pan con tomate z szynką serrano',
    description:
      'Hiszpańskie śniadanie w najprostszej postaci: chrupiące grzanki natarte czosnkiem, pokryte tartym pomidorem i oliwą, z plastrami dojrzewającej szynki. Gotowe w kilka minut, pachnie wakacjami.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'SANDWICH',
    ingredients: [
      ['bagietka', 140, 'g'],
      ['pomidor', 250, 'g'],
      ['czosnek', 1, 'szt'],
      ['oliwa z oliwek', 20, 'ml'],
      ['szynka dojrzewająca', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przekrój bagietkę wzdłuż, a potem na kawałki, i opiecz na suchej patelni grillowej albo w tosterze 2–3 minuty, aż będzie chrupiąca.',
      'Przekrój pomidory na pół i zetrzyj miąższ na tarce o grubych oczkach, skórkę wyrzuć.',
      'Natrzyj ciepłe grzanki przekrojonym ząbkiem czosnku.',
      'Rozsmaruj na grzankach tarty pomidor, skrop je oliwą i oprósz pieprzem.',
      'Ułóż na wierzchu plastry szynki dojrzewającej i podawaj od razu.',
    ],
    photo:
      'Toasted baguette slices covered with fresh grated tomato pulp and olive oil, topped with thin folds of cured serrano ham',
    vessel: 'board',
  },
  {
    plan: 'SN-040',
    title: 'Huevos a la flamenca — jajka zapiekane z chorizo i groszkiem',
    description:
      'Andaluzyjskie jajka zapiekane w gęstym sosie pomidorowym z papryką, wędzoną papryką, chorizo i zielonym groszkiem. Kolorowe danie prosto z żaroodpornego naczynia, idealne na leniwe weekendowe śniadanie.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'SPANISH',
    dishType: 'EGGS',
    equipment: ['OVEN'],
    ingredients: [
      ['oliwa z oliwek', 10, 'ml'],
      ['cebula', 100, 'g'],
      ['czosnek', 1, 'szt'],
      ['papryka czerwona', 150, 'g'],
      ['kiełbasa chorizo', 50, 'g'],
      ['pomidor krojony z puszki', 400, 'g'],
      ['groszek mrożony', 80, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['jajko', 4, 'szt'],
      ['natka pietruszki', 5, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C (góra–dół).',
      'Pokrój cebulę i paprykę w kostkę, chorizo w półplasterki, czosnek posiekaj.',
      'Podsmaż chorizo na oliwie 2 minuty, dodaj cebulę, paprykę i czosnek i smaż 5 minut, aż zmiękną.',
      'Wsyp wędzoną paprykę, wlej pomidory z puszki i gotuj 8 minut. Dodaj groszek i gotuj jeszcze 2 minuty.',
      'Przełóż sos do naczynia żaroodpornego, zrób łyżką 4 wgłębienia i wbij w nie jajka.',
      'Zapiekaj w piekarniku 10–12 minut, aż białka się zetną, a żółtka pozostaną płynne. Posyp natką i podawaj.',
    ],
    photo:
      'Two baked eggs with runny yolks nestled in rich red tomato and pepper sauce with chorizo half-moons and green peas, sprinkled with chopped parsley',
    vessel: 'bowl',
  },
  {
    plan: 'SN-041',
    title: 'Kagianas — greckie jajka z pomidorami i fetą',
    description:
      'Greckie śniadanie z wiejskiej kuchni: dojrzałe pomidory odparowane na oliwie, zmieszane z jajkami na miękką jajecznicę i posypane fetą i oregano. Szybkie, soczyste i bardzo aromatyczne.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'GREEK',
    dishType: 'EGGS',
    ingredients: [
      ['pomidor', 400, 'g'],
      ['oliwa z oliwek', 15, 'ml'],
      ['jajko', 4, 'szt'],
      ['ser feta', 60, 'g'],
      ['oregano', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przekrój pomidory i zetrzyj miąższ na tarce o grubych oczkach, skórki wyrzuć.',
      'Rozgrzej oliwę na patelni, wlej pomidory i gotuj na średnim ogniu 8–10 minut, aż odparują i zgęstnieją.',
      'Roztrzep jajka z pieprzem, wlej do pomidorów i mieszaj delikatnie 2–3 minuty, aż się zetną, ale zostaną kremowe.',
      'Zdejmij z ognia, pokrusz fetę na wierzch i posyp oregano.',
    ],
    photo:
      'Soft creamy scrambled eggs cooked into bright red grated tomato sauce, topped with crumbled white feta and dried oregano',
  },
  {
    plan: 'SN-042',
    title: 'Kanapka z jajkiem, cheddarem i bekonem na angielskiej bułeczce',
    description:
      'Klasyczna amerykańska kanapka śniadaniowa: opieczona angielska bułeczka z chrupiącym bekonem, jajkiem smażonym w kształt krążka i plastrem topiącego się cheddara. Ciepła, konkretna i gotowa w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['muffin angielski', 120, 'g'],
      ['boczek', 40, 'g'],
      ['jajko', 2, 'szt'],
      ['ser cheddar', 40, 'g'],
      ['masło', 5, 'g'],
      ['pomidor', 80, 'g'],
    ],
    steps: [
      'Usmaż plastry boczku na suchej patelni po 2 minuty z każdej strony, aż będą chrupiące. Odłóż na ręcznik papierowy.',
      'Na tym samym tłuszczu usmaż jajka sadzone, przebijając żółtka, żeby smażyły się na płasko, około 3 minut z obu stron.',
      'Przekrój bułeczki na pół, posmaruj cienko masłem i opiecz na patelni przekrojem w dół przez 1–2 minuty.',
      'Połóż na jajkach plastry cheddara, przykryj patelnię na 30 sekund, żeby ser się roztopił.',
      'Złóż kanapki: dolna połówka, plaster pomidora, boczek, jajko z serem i górna połówka. Podawaj na ciepło.',
    ],
    photo:
      'Toasted English muffin sandwich stacked with a fried egg, melting orange cheddar, crispy bacon and a tomato slice, cut to show the layers',
  },
  {
    plan: 'SN-043',
    title: 'Masala omlet z pomidorem i kolendrą',
    description:
      'Indyjski omlet z czerwoną cebulą, pomidorem, zielonym chili, kurkumą i garam masalą, posypany świeżą kolendrą. Aromatyczny i pikantny, gotowy w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 5, 'szt'],
      ['cebula czerwona', 60, 'g'],
      ['pomidor', 100, 'g'],
      ['papryczka chili', 10, 'g'],
      ['kolendra', 10, 'g'],
      ['kurkuma', 1, 'g'],
      ['garam masala', 2, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
    ],
    steps: [
      'Posiekaj drobno czerwoną cebulę, pomidor bez gniazd nasiennych, chili i większość kolendry.',
      'Roztrzep jajka z kurkumą, garam masalą i solą, wmieszaj warzywa i kolendrę.',
      'Rozgrzej połowę oleju na patelni, wlej połowę masy i smaż na średnim ogniu 2–3 minuty, aż spód się zetnie.',
      'Przewróć albo złóż omlet na pół i smaż jeszcze minutę. Tak samo usmaż drugi omlet na reszcie oleju.',
      'Podawaj od razu, posypany resztą kolendry.',
    ],
    photo:
      'Golden folded masala omelette speckled with red onion, tomato, green chili and fresh cilantro leaves',
  },
  {
    plan: 'SN-044',
    title: 'Upma — kasza manna z warzywami po indyjsku',
    description:
      'Południowoindyjskie śniadanie z prażonej kaszy manny ugotowanej z cebulą, marchewką, groszkiem, imbirem i chili, z prażonymi orzeszkami i limonką. Wytrawna, rozgrzewająca alternatywa dla słodkiej kaszy.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'INDIAN',
    dishType: 'GRAINS',
    ingredients: [
      ['kasza manna', 120, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['orzeszek ziemny', 20, 'g'],
      ['cebula', 80, 'g'],
      ['marchew', 80, 'g'],
      ['groszek mrożony', 80, 'g'],
      ['imbir', 10, 'g'],
      ['papryczka chili', 10, 'g'],
      ['kurkuma', 1, 'g'],
      ['sól', 2, 'g'],
      ['kolendra', 10, 'g'],
      ['limonka', 30, 'g'],
    ],
    steps: [
      'Upraż kaszę mannę na suchej patelni, mieszając, przez 3–4 minuty, aż lekko pachnie. Przesyp do miseczki.',
      'Rozgrzej olej w garnku, podsmaż orzeszki ziemne 1 minutę, dodaj posiekaną cebulę, starty imbir i chili, smaż 3 minuty.',
      'Dodaj marchew startą na grubych oczkach, groszek i kurkumę, smaż 2 minuty.',
      'Wlej 500 ml wrzącej wody, dodaj sól i doprowadź do wrzenia. Wsypuj kaszę cienkim strumieniem, cały czas mieszając, żeby nie zrobiły się grudki.',
      'Gotuj na małym ogniu 2–3 minuty, aż upma zgęstnieje, przykryj i odstaw na 2 minuty.',
      'Podawaj posypaną kolendrą, skropioną sokiem z limonki.',
    ],
    photo:
      'Fluffy turmeric-yellow semolina upma with grated carrot, green peas, onion and roasted peanuts, sprinkled with fresh cilantro and glistening with lime juice',
    vessel: 'bowl',
  },
  {
    plan: 'SN-045',
    title: 'Huevos rancheros — jajka z salsą i fasolą na tortilli',
    description:
      'Meksykańskie jajka sadzone na podpieczonych tortillach kukurydzianych, z pikantną salsą pomidorową, fasolą z kminem, awokado i limonką. Kolorowe, sycące śniadanie ranczerów.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'MEXICAN',
    dishType: 'EGGS',
    ingredients: [
      ['tortilla kukurydziana', 4, 'szt'],
      ['jajko', 4, 'szt'],
      ['fasola czarna z puszki', 150, 'g'],
      ['pomidor krojony z puszki', 200, 'g'],
      ['salsa pomidorowa', 100, 'g'],
      ['cebula', 50, 'g'],
      ['czosnek', 1, 'szt'],
      ['kmin rzymski', 1, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['awokado', 1, 'szt'],
      ['kolendra', 5, 'g'],
      ['limonka', 20, 'g'],
    ],
    steps: [
      'Posiekaj cebulę i czosnek, zeszklij na 5 ml oleju przez 3 minuty. Dodaj pomidory z puszki i salsę, gotuj 6–8 minut.',
      'Odsącz fasolę, podgrzej ją w rondelku z kminem i odrobiną wody przez 3 minuty i lekko rozgnieć.',
      'Podpiecz tortille kukurydziane na suchej patelni po 30 sekund z każdej strony, aż zmiękną i lekko się zrumienią.',
      'Na reszcie oleju usmaż 4 jajka sadzone, około 3 minut.',
      'Połóż na talerzach po dwie tortille, rozsmaruj fasolę, ułóż jajka i polej salsą.',
      'Dodaj plastry awokado, kolendrę i skrop sokiem z limonki.',
    ],
    photo:
      'Two fried eggs on two warm corn tortillas spread with smashed black beans, spooned over with chunky red ranchero salsa, with avocado slices and fresh cilantro leaves',
  },
  {
    plan: 'SN-046',
    title: 'Frittata po włosku z suszonymi pomidorami i bazylią',
    description:
      'Puszysta frittata z czerwoną cebulą, suszonymi pomidorami i parmezanem, dopieczona w piekarniku i posypana świeżą bazylią. Podana z rukolą to eleganckie, bezglutenowe śniadanie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'ITALIAN',
    dishType: 'EGGS',
    equipment: ['OVEN'],
    ingredients: [
      ['jajko', 5, 'szt'],
      ['mleko', 50, 'ml'],
      ['pomidor suszony w oleju', 50, 'g'],
      ['cebula czerwona', 60, 'g'],
      ['ser parmezan', 20, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['bazylia', 10, 'g'],
      ['rukola', 40, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 180°C (góra–dół).',
      'Pokrój cebulę w piórka, a suszone pomidory w paski. Zetrzyj parmezan.',
      'Roztrzep jajka z mlekiem, połową parmezanu i pieprzem.',
      'Na patelni nadającej się do piekarnika podsmaż cebulę na oliwie 3 minuty, dodaj pomidory, wlej jajka i smaż na małym ogniu 3 minuty, aż brzegi się zetną.',
      'Posyp resztą parmezanu i wstaw patelnię do piekarnika na 10–12 minut, aż frittata wyrośnie i zetnie się w środku.',
      'Posyp listkami bazylii, pokrój w trójkąty i podawaj z rukolą.',
    ],
    photo:
      'Two golden Italian frittata wedges studded with sun-dried tomato strips and red onion, with a grated parmesan crust and fresh basil leaves, beside a small heap of arugula',
  },
  {
    plan: 'SN-047',
    title: 'Tosty BLT z bekonem, sałatą i pomidorem',
    description:
      'Amerykański klasyk: chrupiący chleb tostowy z majonezem, bekonem, sałatą rzymską i soczystym pomidorem. Prosta kanapka, której chrupkość i słony smak rozbudzą każdego rano.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'SANDWICH',
    ingredients: [
      ['chleb tostowy', 120, 'g'],
      ['boczek', 60, 'g'],
      ['majonez', 20, 'g'],
      ['sałata rzymska', 40, 'g'],
      ['pomidor', 150, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Usmaż plastry boczku na suchej patelni po 2–3 minuty z każdej strony, aż będą chrupiące. Odsącz na ręczniku papierowym.',
      'Opiecz kromki chleba tostowego w tosterze albo na suchej patelni na złoto.',
      'Pokrój pomidor w plastry i oprósz pieprzem, liście sałaty umyj i osusz.',
      'Posmaruj tosty cienko majonezem, ułóż sałatę, pomidor i boczek, przykryj drugą kromką.',
      'Przekrój tosty po przekątnej i podawaj od razu.',
    ],
    photo:
      'Toasted BLT sandwich cut diagonally showing crispy bacon strips, crisp romaine lettuce and juicy red tomato slices',
  },
  {
    plan: 'SN-048',
    title: 'Tajski omlet z ryżem i sosem chili',
    description:
      'Khai jiao — tajski omlet usmażony na mocno rozgrzanym oleju, puszysty w środku i chrupiący na brzegach, podany na ryżu jaśminowym ze słodkim sosem chili i ogórkiem. Szybkie, pełne smaku śniadanie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'THAI',
    dishType: 'EGGS',
    ingredients: [
      ['ryż jaśminowy', 100, 'g'],
      ['jajko', 4, 'szt'],
      ['sos rybny', 10, 'ml'],
      ['cebula dymka', 20, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['sos chili słodki', 30, 'g'],
      ['ogórek', 100, 'g'],
      ['kolendra', 5, 'g'],
    ],
    steps: [
      'Przepłucz ryż jaśminowy, zalej 200 ml wody i gotuj pod przykryciem na małym ogniu 12 minut, potem odstaw na 5 minut.',
      'Roztrzep energicznie jajka z sosem rybnym i posiekaną dymką, aż się spienią.',
      'Rozgrzej połowę oleju w woku albo na małej patelni do mocnego dymienia, wlej połowę jajek z wysokości — omlet napuszy się od razu.',
      'Smaż 1 minutę, przewróć i smaż jeszcze 30 sekund, aż brzegi będą złote i chrupiące. Tak samo usmaż drugi omlet.',
      'Pokrój ogórek w plasterki. Ułóż omlety na ryżu, polej sosem chili, dodaj ogórek i kolendrę.',
    ],
    photo:
      'Puffy golden Thai omelette with crispy lacy edges on a mound of jasmine rice, drizzled with sweet chili sauce, with cucumber slices and cilantro',
  },
  // ── Sezonowe ──
  {
    plan: 'SN-049',
    title: 'Jajecznica ze szparagami i szczypiorkiem',
    description:
      'Kremowa jajecznica na maśle z kawałkami chrupiących zielonych szparagów i świeżym szczypiorkiem. Wiosenne śniadanie, które najlepiej smakuje w maju, gdy szparagi są najtańsze.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    seasons: ['SPRING'],
    ingredients: [
      ['szparagi', 250, 'g'],
      ['masło', 15, 'g'],
      ['jajko', 5, 'szt'],
      ['szczypiorek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Odłam zdrewniałe końce szparagów i pokrój je ukośnie na kawałki około 3 cm, główki zostaw w całości.',
      'Rozgrzej masło na patelni i smaż szparagi 4–5 minut, aż zmiękną, ale pozostaną chrupiące.',
      'Roztrzep jajka z solą i pieprzem, wlej na patelnię i mieszaj szpatułką na małym ogniu 2–3 minuty, aż się zetną.',
      'Zdejmij z ognia, gdy jajecznica jest jeszcze lekko wilgotna, i posyp posiekanym szczypiorkiem.',
    ],
    photo:
      'Creamy soft scrambled eggs with bright green asparagus pieces and tips, sprinkled with fresh chopped chives',
  },
  {
    plan: 'SN-050',
    title: 'Owsianka z rabarbarem i truskawkami',
    description:
      'Kremowa owsianka na mleku z kwaskowym, duszonym rabarbarem i słodkimi truskawkami, dosłodzona miodem i posypana migdałami. Smak wiosny w misce, kiedy rabarbar właśnie pojawia się na targu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PORRIDGE',
    seasons: ['SPRING'],
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['mleko', 400, 'ml'],
      ['rabarbar', 150, 'g'],
      ['truskawka', 150, 'g'],
      ['miód', 20, 'g'],
      ['migdał', 15, 'g'],
    ],
    steps: [
      'Umyj rabarbar, obierz twardsze łodygi z włókien i pokrój w kawałki 1 cm.',
      'Włóż rabarbar do rondelka z połową miodu i 2 łyżkami wody, duś pod przykryciem 5–6 minut, aż się rozpadnie.',
      'Zagotuj mleko, wsyp płatki owsiane i gotuj na małym ogniu 5 minut, mieszając, aż owsianka zgęstnieje.',
      'Pokrój truskawki na ćwiartki, migdały posiekaj grubo.',
      'Przełóż owsiankę do misek, dodaj duszony rabarbar i truskawki, polej resztą miodu i posyp migdałami.',
    ],
    photo:
      'Creamy oatmeal topped with pink stewed rhubarb, quartered fresh strawberries, chopped almonds and a drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'SN-051',
    title: 'Bułki z pastą z awokado i rzodkiewką',
    description:
      'Grahamki z kremową pastą z awokado z cytryną i szczypiorkiem, pokryte plasterkami chrupiącej rzodkiewki i kiełkami. Świeże, wiosenne śniadanie bez gotowania, gotowe w 10 minut.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 10,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    seasons: ['SPRING'],
    ingredients: [
      ['bułka grahamka', 280, 'g'],
      ['awokado', 1, 'szt'],
      ['cytryna', 20, 'g'],
      ['szczypiorek', 10, 'g'],
      ['rzodkiewka', 100, 'g'],
      ['kiełki', 15, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Przekrój awokado, wyjmij pestkę i wydrąż miąższ łyżką do miski.',
      'Rozgnieć awokado widelcem z sokiem z cytryny, pieprzem i połową posiekanego szczypiorku.',
      'Pokrój rzodkiewki w cienkie plasterki.',
      'Przekrój bułki na pół, posmaruj grubo pastą z awokado i ułóż plasterki rzodkiewki.',
      'Posyp resztą szczypiorku i kiełkami.',
    ],
    photo:
      'Halved graham rolls spread with bright green smashed avocado, topped with thin pink-white radish slices, sprouts and chives',
    vessel: 'board',
  },
  {
    plan: 'SN-052',
    title: 'Tost z ricottą, bobem i miętą',
    description:
      'Chrupiące grzanki z kremową ricottą, młodym bobem obranym ze skórek, świeżą miętą, skórką z cytryny i oliwą. Letnie śniadanie, które wykorzystuje krótki sezon na bób.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    seasons: ['SUMMER'],
    ingredients: [
      ['bób', 200, 'g'],
      ['chleb pełnoziarnisty', 120, 'g'],
      ['ser ricotta', 150, 'g'],
      ['cytryna', 30, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['mięta', 5, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wrzuć bób do wrzącej, osolonej wody i gotuj 4–5 minut. Odcedź, przelej zimną wodą i obierz ze skórek.',
      'Wymieszaj bób z oliwą, połową soku z cytryny, pieprzem i porwanymi listkami mięty, część ziaren lekko rozgnieć widelcem.',
      'Wymieszaj ricottę ze startą skórką z cytryny.',
      'Opiecz kromki chleba w tosterze albo na suchej patelni na chrupko.',
      'Rozsmaruj ricottę na grzankach, ułóż bób, skrop resztą soku z cytryny i udekoruj miętą.',
    ],
    photo:
      'Toasted wholegrain bread topped with creamy white ricotta, bright green peeled broad beans, torn mint leaves, lemon zest and olive oil',
  },
  {
    plan: 'SN-053',
    title: 'Frittata z młodą cukinią i miętą',
    description:
      'Lekka frittata z młodą cukinią startą na tarce, dymką, fetą i świeżą miętą, dopieczona w piekarniku. Wakacyjne śniadanie na ciepło albo na zimno, bez glutenu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    seasons: ['SUMMER'],
    equipment: ['OVEN'],
    ingredients: [
      ['cukinia', 300, 'g'],
      ['cebula dymka', 30, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['jajko', 5, 'szt'],
      ['ser feta', 60, 'g'],
      ['mięta', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 180°C (góra–dół).',
      'Zetrzyj cukinię na tarce o grubych oczkach, lekko ją odciśnij z soku. Dymkę pokrój w krążki.',
      'Na patelni nadającej się do piekarnika podsmaż dymkę i cukinię na oliwie przez 5 minut, aż odparują.',
      'Roztrzep jajka z pieprzem i posiekaną połową mięty, wlej na cukinię i pokrusz na wierzch fetę.',
      'Smaż 2 minuty na małym ogniu, a potem piecz w piekarniku 12–15 minut, aż frittata zetnie się w środku.',
      'Posyp resztą mięty i pokrój w kawałki.',
    ],
    photo:
      'Two wedges of golden frittata with pale green grated zucchini and spring onion, baked crumbled white feta on top and fresh mint leaves',
  },
  {
    plan: 'SN-054',
    title: 'Kasza jaglana z czereśniami i jogurtem',
    description:
      'Delikatna kasza jaglana ugotowana na mleku z nutą wanilii, podana z jogurtem naturalnym i soczystymi czereśniami. Lekkie, słodkie śniadanie bez glutenu na czerwcowe poranki.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PORRIDGE',
    seasons: ['SUMMER'],
    ingredients: [
      ['kasza jaglana', 100, 'g'],
      ['mleko', 300, 'ml'],
      ['cukier waniliowy', 8, 'g'],
      ['czereśnia', 250, 'g'],
      ['jogurt naturalny', 200, 'g'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Przepłucz kaszę jaglaną na sitku gorącą wodą, żeby nie była gorzka.',
      'Wsyp kaszę do garnka, wlej mleko, dodaj cukier waniliowy i gotuj pod przykryciem na małym ogniu 15 minut, mieszając od czasu do czasu.',
      'W tym czasie umyj czereśnie i wydryluj je, większe przekrój na połówki.',
      'Przełóż kaszę do misek, nałóż jogurt i czereśnie, polej miodem.',
    ],
    photo:
      'Creamy yellow millet porridge topped with a swirl of natural yogurt, halved dark red cherries and a drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'SN-055',
    title: 'Owsianka nocna z malinami i porzeczkami',
    description:
      'Płatki owsiane z nasionami chia namoczone w jogurcie z mlekiem, przełożone malinami i czerwonymi porzeczkami. Zrobisz kilka słoików naraz i masz gotowe śniadania na następne dni.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    seasons: ['SUMMER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['jogurt naturalny', 200, 'g'],
      ['mleko', 150, 'ml'],
      ['nasiona chia', 15, 'g'],
      ['miód', 20, 'g'],
      ['malina', 150, 'g'],
      ['porzeczka czerwona', 80, 'g'],
    ],
    steps: [
      'Wymieszaj płatki owsiane z nasionami chia, jogurtem naturalnym, mlekiem i miodem.',
      'Oberwij porzeczki z gałązek, maliny i porzeczki opłucz delikatnie.',
      'Rozgnieć widelcem połowę malin i przełóż do słoików na przemian z owsianką.',
      'Wstaw słoiki do lodówki na noc — jeśli jesz od razu, odstaw na co najmniej 20 minut, aż chia napęcznieje.',
      'Przed podaniem ułóż na wierzchu resztę malin i porzeczki.',
    ],
    photo:
      'Creamy overnight oats with chia seeds swirled with crushed pink raspberries, topped with fresh whole raspberries and bright red currants',
    vessel: 'bowl',
  },
  {
    plan: 'SN-056',
    title: 'Jajecznica z kurkami i koperkiem',
    description:
      'Złociste kurki podsmażone na maśle z szalotką, połączone z kremową jajecznicą i świeżym koperkiem. Leśne, sezonowe śniadanie, na które czeka się całe lato.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    seasons: ['SUMMER', 'AUTUMN'],
    ingredients: [
      ['kurki', 200, 'g'],
      ['szalotka', 30, 'g'],
      ['masło', 15, 'g'],
      ['jajko', 5, 'szt'],
      ['koperek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Oczyść kurki: przepłucz je krótko w zimnej wodzie, osusz i większe przekrój na pół.',
      'Rozgrzej masło na patelni, zeszklij posiekaną szalotkę przez 2 minuty.',
      'Dodaj kurki i smaż na mocnym ogniu 6–8 minut, aż odparują i się zrumienią.',
      'Roztrzep jajka z solą i pieprzem, wlej na kurki i mieszaj na małym ogniu 2–3 minuty.',
      'Zdejmij z ognia i posyp posiekanym koperkiem.',
    ],
    photo:
      'Soft golden scrambled eggs mixed with sauteed orange chanterelle mushrooms and sprinkled with fresh chopped dill',
  },
  {
    plan: 'SN-057',
    title: 'Tosty z serem, gruszką i orzechami',
    description:
      'Grzanki z pełnoziarnistego chleba zapieczone z camembertem i plastrami gruszki, posypane orzechami włoskimi i skropione miodem. Jesienne połączenie słodkiego i słonego.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    seasons: ['AUTUMN'],
    equipment: ['OVEN'],
    ingredients: [
      ['chleb pełnoziarnisty', 120, 'g'],
      ['ser camembert', 80, 'g'],
      ['gruszka', 150, 'g'],
      ['orzech włoski', 20, 'g'],
      ['miód', 10, 'g'],
      ['rukola', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C (góra–dół) i wyłóż blachę papierem do pieczenia.',
      'Umyj gruszkę, usuń gniazdo nasienne i pokrój w cienkie plasterki. Camembert pokrój w plastry.',
      'Ułóż kromki chleba na blasze, na każdej połóż gruszkę i ser, posyp posiekanymi orzechami.',
      'Zapiekaj 8–10 minut, aż ser się rozpuści, a brzegi chleba zrumienią.',
      'Skrop tosty miodem, oprósz pieprzem i podawaj z rukolą.',
    ],
    photo:
      'Toasted wholegrain bread with melted camembert, thin pear slices, chopped walnuts and a honey drizzle, with arugula leaves',
    vessel: 'board',
  },
  {
    plan: 'SN-058',
    title: 'Jajka w sosie z grzybów leśnych na grzance',
    description:
      'Jajka ugotowane na półtwardo, podane na chrupiącej grzance w kremowym sosie z grzybów leśnych ze śmietaną i koperkiem. Jesienne, rozgrzewające śniadanie w polskim stylu.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    seasons: ['AUTUMN'],
    ingredients: [
      ['jajko', 4, 'szt'],
      ['grzyby leśne mrożone', 250, 'g'],
      ['cebula', 80, 'g'],
      ['masło', 15, 'g'],
      ['śmietana 18', 100, 'g'],
      ['koperek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb', 100, 'g'],
    ],
    steps: [
      'Włóż jajka do wrzącej wody i gotuj 7 minut, przelej zimną wodą i obierz.',
      'Posiekaj cebulę i zeszklij ją na maśle przez 3 minuty.',
      'Dodaj mrożone grzyby leśne i smaż na średnim ogniu 8–10 minut, aż odparuje woda i lekko się zrumienią. Dopraw solą i pieprzem.',
      'Zmniejsz ogień, wmieszaj śmietanę i podgrzewaj 2 minuty, aż sos zgęstnieje, ale nie zagotuj go. Dodaj posiekany koperek.',
      'Opiecz kromki chleba na suchej patelni albo w tosterze.',
      'Ułóż grzanki na talerzach, polej sosem grzybowym i połóż na wierzchu przekrojone jajka.',
    ],
    photo:
      'Toasted bread slice covered with creamy brown wild mushroom sauce, topped with halved jammy boiled eggs and chopped dill',
  },
  {
    plan: 'SN-059',
    title: 'Owsianka dyniowa z cynamonem i orzechami',
    description:
      'Pomarańczowa owsianka z dynią startą na tarce i ugotowaną w mleku z cynamonem i imbirem, podana z chrupiącymi orzechami i syropem klonowym. Smakuje jak ciasto dyniowe na śniadanie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    seasons: ['AUTUMN'],
    ingredients: [
      ['dynia', 200, 'g'],
      ['mleko', 400, 'ml'],
      ['płatki owsiane', 100, 'g'],
      ['cynamon', 2, 'g'],
      ['imbir mielony', 1, 'g'],
      ['syrop klonowy', 20, 'g'],
      ['orzech włoski', 25, 'g'],
    ],
    steps: [
      'Obierz dynię i zetrzyj ją na tarce o drobnych oczkach.',
      'Włóż dynię do garnka, wlej mleko, dodaj cynamon i imbir, zagotuj i gotuj 5 minut, aż dynia zmięknie.',
      'Wsyp płatki owsiane i gotuj na małym ogniu 5 minut, mieszając, aż owsianka zgęstnieje. Wmieszaj połowę syropu klonowego.',
      'Upraż orzechy włoskie na suchej patelni przez 2–3 minuty i posiekaj grubo.',
      'Przełóż owsiankę do misek, posyp orzechami, polej resztą syropu i oprósz cynamonem.',
    ],
    photo:
      'Bright orange pumpkin oatmeal topped with toasted chopped walnuts, a drizzle of maple syrup and a dusting of cinnamon',
    vessel: 'bowl',
  },
  {
    plan: 'SN-060',
    title: 'Grzanki z pieczonym burakiem, twarożkiem i orzechami',
    description:
      'Chleb żytni z twarogiem, pieczonymi buraczkami z tymiankiem, orzechami włoskimi, miodem i roszponką. Kolorowe, zimowe śniadanie, w którym słodycz buraka łączy się z kremowym serem.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SANDWICH',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['burak', 300, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['tymianek suszony', 1, 'g'],
      ['chleb żytni', 120, 'g'],
      ['ser twaróg półtłusty', 150, 'g'],
      ['orzech włoski', 20, 'g'],
      ['miód', 10, 'g'],
      ['roszponka', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 200°C (termoobieg). Obierz buraki i pokrój je w cienkie plasterki albo kostkę 1 cm.',
      'Wymieszaj buraki z oliwą, tymiankiem i pieprzem, rozłóż na blasze i piecz 25–30 minut, aż zmiękną i się skarmelizują.',
      'Rozgnieć twaróg widelcem na gładką pastę, w razie potrzeby z łyżką wody.',
      'Pod koniec pieczenia połóż kromki chleba na kratce w piekarniku na 3–4 minuty, żeby się zrumieniły.',
      'Posmaruj grzanki twarogiem, ułóż buraki i roszponkę, posyp posiekanymi orzechami i skrop miodem.',
    ],
    photo:
      'Toasted rye bread spread with white farmer cheese, topped with deep purple roasted beetroot, lamb lettuce, chopped walnuts and honey',
    vessel: 'board',
  },
];
