/**
 * Katalog 1000 — część SN-c: śniadania SN-061 … SN-088 z `prisma/catalog/katalog-1000-lista.md`.
 */
import type { Def, IngredientAddition } from './types';

export const ADDITIONS: IngredientAddition[] = [];

export const DEFS: Def[] = [
  // ── Sezonowe (zima) ──
  {
    plan: 'SN-061',
    title: 'Owsianka z pomarańczą i kakao',
    description:
      'Czekoladowa owsianka gotowana na mleku z kakao, podana z soczystymi cząstkami pomarańczy i prażonymi orzechami laskowymi. Rozgrzewające zimowe śniadanie, które smakuje jak deser.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    seasons: ['WINTER'],
    ingredients: [
      ['płatki owsiane', 80, 'g'],
      ['mleko', 400, 'ml'],
      ['kakao', 10, 'g'],
      ['pomarańcza', 250, 'g'],
      ['miód', 20, 'g'],
      ['orzech laskowy', 20, 'g'],
    ],
    steps: [
      'Wlej mleko do garnka, wsyp kakao i rozmieszaj trzepaczką, aż nie będzie grudek.',
      'Dodaj płatki owsiane, zagotuj i gotuj na małym ogniu 5–6 minut, często mieszając, aż owsianka zgęstnieje.',
      'Zetrzyj z pomarańczy odrobinę skórki, a owoc obierz i podziel na cząstki.',
      'Orzechy laskowe posiekaj grubo i podpraż 2–3 minuty na suchej patelni.',
      'Wmieszaj do owsianki miód i skórkę pomarańczową, przełóż do misek i ułóż na wierzchu pomarańczę oraz orzechy.',
    ],
    photo:
      'Dark brown cocoa oat porridge topped with bright orange segments, toasted chopped hazelnuts and a little grated orange zest',
    vessel: 'bowl',
  },
  {
    plan: 'SN-062',
    title: 'Jaglanka z pieczonym jabłkiem i żurawiną',
    description:
      'Kremowa kasza jaglana na mleku migdałowym z pieczonym jabłkiem, cynamonem i suszoną żurawiną. Roślinne, bezglutenowe śniadanie, które pachnie jak zimowa szarlotka.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['kasza jaglana', 90, 'g'],
      ['mleko migdałowe', 400, 'ml'],
      ['jabłko', 300, 'g'],
      ['żurawina suszona', 25, 'g'],
      ['syrop klonowy', 20, 'g'],
      ['cynamon', 2, 'g'],
      ['migdał', 20, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 180°C. Jabłka umyj, usuń gniazda nasienne, pokrój w ósemki, posyp połową cynamonu i piecz na blasze 20 minut, aż zmiękną.',
      'Kaszę jaglaną przepłucz na sitku gorącą wodą, żeby pozbyć się goryczki.',
      'Wsyp kaszę do garnka, wlej mleko migdałowe, zagotuj i gotuj pod przykryciem na małym ogniu 15 minut, aż wchłonie płyn.',
      'Wmieszaj do kaszy resztę cynamonu, syrop klonowy i żurawinę, a migdały posiekaj.',
      'Przełóż jaglankę do misek, ułóż pieczone jabłka i posyp migdałami.',
    ],
    photo:
      'Creamy golden millet porridge topped with soft cinnamon-baked apple wedges, dried cranberries and chopped almonds',
    vessel: 'bowl',
  },
  {
    plan: 'SN-063',
    title: 'Jajka zapiekane z porem i boczkiem',
    description:
      'Jajka zapiekane w kokilkach na podsmażonym porze z chrupiącym boczkiem, śmietaną i odrobiną żółtego sera. Sycące, ciepłe śniadanie na zimowy weekend, gotowe w pół godziny.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    seasons: ['WINTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['jajko', 4, 'szt'],
      ['por', 150, 'g'],
      ['boczek', 60, 'g'],
      ['śmietana 18', 60, 'g'],
      ['ser żółty', 30, 'g'],
      ['masło', 10, 'g'],
      ['szczypiorek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 190°C. Por przekrój wzdłuż, dokładnie opłucz i pokrój w cienkie półplasterki, a boczek w kostkę.',
      'Na patelni podsmaż boczek 3–4 minuty, dodaj masło i por i duś 5 minut, aż por zmięknie.',
      'Przełóż por z boczkiem do dwóch kokilek, zrób w środku zagłębienia i wbij do każdej po dwa jajka.',
      'Wokół żółtek rozłóż śmietanę, posyp startym serem żółtym i pieprzem.',
      'Zapiekaj w piekarniku 12–14 minut, aż białka się zetną, a żółtka pozostaną miękkie. Posyp szczypiorkiem i podawaj od razu.',
    ],
    photo:
      'Two baked eggs with soft runny yolks nestled on a bed of soft sauteed leeks and crispy bacon cubes, ringed with bubbling cream under melted golden cheese, sprinkled with chopped chives',
    vessel: 'bowl',
  },

  // ── Airfryer ──
  {
    plan: 'SN-064',
    title: 'Frittata z papryką i fetą',
    description:
      'Puszysta frittata z czerwoną papryką, czerwoną cebulą i słoną fetą, upieczona w airfryerze bez pilnowania patelni. Szybkie, bezglutenowe śniadanie, które smakuje też na zimno.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 25,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['jajko', 5, 'szt'],
      ['papryka czerwona', 150, 'g'],
      ['cebula czerwona', 50, 'g'],
      ['ser feta', 60, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Paprykę pokrój w drobną kostkę, a cebulę w cienkie piórka.',
      'Posmaruj oliwą okrągłą formę pasującą do kosza airfryera, wrzuć paprykę i cebulę i piecz w 180°C 5 minut, żeby zmiękły.',
      'Jajka roztrzep z oregano i pieprzem, wlej na warzywa i rozkrusz na wierzchu fetę.',
      'Piecz w airfryerze w 160°C 12–15 minut, aż środek się zetnie. W piekarniku: 180°C, 20 minut w małej formie.',
      'Odstaw frittatę na 2 minuty, pokrój w trójkąty i podawaj.',
    ],
    photo:
      'Golden fluffy frittata wedges studded with red pepper, red onion and crumbled white feta, sprinkled with dried oregano',
  },
  {
    plan: 'SN-065',
    title: 'Placuszki twarogowe pieczone z owocami',
    description:
      'Miękkie placuszki z twarogu pieczone w airfryerze zamiast smażenia, podane z jogurtem i borówkami. Mało tłuszczu, dużo nabiału, a upieczone na zapas smakują jeszcze przez trzy dni.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'PANCAKES',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ser twaróg półtłusty', 250, 'g'],
      ['jajko', 2, 'szt'],
      ['mąka pszenna', 60, 'g'],
      ['cukier', 20, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['jogurt naturalny', 150, 'g'],
      ['borówka', 100, 'g'],
    ],
    steps: [
      'Rozgnieć twaróg widelcem, dodaj jajka i cukier i wymieszaj na gładką masę.',
      'Wsyp mąkę i połącz na gęste ciasto, które trzyma kształt na łyżce.',
      'Wyłóż kosz airfryera papierem do pieczenia i posmaruj go cienko olejem. Nakładaj łyżką niewielkie placuszki w odstępach.',
      'Piecz w 180°C 10–12 minut, w połowie ostrożnie przewróć. W piekarniku: 190°C, 15 minut na blasze z papierem.',
      'Podawaj z jogurtem i borówkami. Upieczone placuszki przechowuj w lodówce do 3 dni i odgrzej 3 minuty w airfryerze.',
    ],
    photo:
      'Stack of small golden baked quark pancakes with a dollop of natural yogurt and fresh blueberries',
  },
  {
    plan: 'SN-066',
    title: 'Hash browns z jajkiem sadzonym',
    description:
      'Chrupiące amerykańskie placki z tartych ziemniaków upieczone w airfryerze i podane z jajkiem sadzonym i szczypiorkiem. Śniadanie jak z przydrożnego diner, bez glutenu i bez głębokiego tłuszczu.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'AMERICAN',
    dishType: 'POTATOES',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ziemniak', 400, 'g'],
      ['jajko', 3, 'szt'],
      ['mąka ziemniaczana', 15, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['sól', 2, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['szczypiorek', 5, 'g'],
    ],
    steps: [
      'Obierz ziemniaki, zetrzyj na tarce o grubych oczkach i mocno odciśnij z soku w czystej ściereczce.',
      'Wymieszaj ziemniaki z jednym jajkiem, mąką ziemniaczaną, solą i pieprzem, a potem uformuj 4 płaskie placki.',
      'Posmaruj placki z obu stron olejem, zostawiając łyżeczkę do smażenia jajek. Piecz w airfryerze w 200°C 15–18 minut, w połowie przewróć. W piekarniku: 220°C, termoobieg, 25 minut na blasze z papierem.',
      'Pod koniec pieczenia rozgrzej na patelni resztę oleju i usmaż dwa jajka sadzone, 3 minuty na średnim ogniu.',
      'Ułóż na talerzach po dwa placki, na nich jajko sadzone i posyp szczypiorkiem.',
    ],
    photo:
      'Two crispy golden shredded potato hash browns topped with a sunny-side-up egg and chopped chives',
  },
  {
    plan: 'SN-067',
    title: 'Tosty z mozzarellą i pomidorem',
    description:
      'Chrupiące tosty z roztopioną mozzarellą, plastrami pomidora, oregano i świeżą bazylią, zapieczone w airfryerze w kilka minut. Proste śniadanie o smaku pizzy margherity.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['chleb tostowy', 120, 'g'],
      ['mozzarella', 125, 'g'],
      ['pomidor', 200, 'g'],
      ['oliwa z oliwek', 10, 'ml'],
      ['oregano', 1, 'g'],
      ['bazylia', 5, 'g'],
    ],
    steps: [
      'Posmaruj kromki chleba tostowego cienko oliwą z jednej strony.',
      'Pomidory i odsączoną mozzarellę pokrój w plastry. Ułóż na chlebie na przemian pomidor i ser, posyp oregano.',
      'Piecz tosty w airfryerze w 180°C 6–7 minut, aż ser się roztopi, a brzegi chleba zrumienią. W piekarniku: 200°C, górna grzałka, 8–10 minut.',
      'Przed podaniem udekoruj listkami świeżej bazylii.',
    ],
    photo:
      'Crispy toast slices topped with melted mozzarella and tomato slices, sprinkled with oregano and fresh basil leaves',
    vessel: 'board',
  },
  {
    plan: 'SN-068',
    title: 'Pieczone jabłka z owsianą kruszonką',
    description:
      'Miękkie, cynamonowe jabłka pod chrupiącą kruszonką z płatków owsianych, masła i orzechów, podane z jogurtem greckim. Ciepłe śniadanie o smaku szarlotki, gotowe w airfryerze.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'BAKE',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['jabłko', 500, 'g'],
      ['płatki owsiane', 40, 'g'],
      ['masło', 20, 'g'],
      ['cukier brązowy', 15, 'g'],
      ['cynamon', 2, 'g'],
      ['orzech włoski', 20, 'g'],
      ['jogurt grecki', 150, 'g'],
    ],
    steps: [
      'Jabłka umyj, usuń gniazda nasienne i pokrój w grubą kostkę. Wymieszaj z połową cynamonu i przełóż do małego żaroodpornego naczynia pasującego do airfryera.',
      'Zagnieć palcami płatki owsiane z zimnym masłem, cukrem brązowym, resztą cynamonu i posiekanymi orzechami na grudki.',
      'Rozsyp kruszonkę na jabłkach.',
      'Piecz w airfryerze w 170°C 15–18 minut, aż jabłka zmiękną, a kruszonka się zrumieni. W piekarniku: 180°C, 25–30 minut.',
      'Przełóż na talerze i podawaj na ciepło z jogurtem greckim.',
    ],
    photo:
      'Warm baked cinnamon apple chunks under a golden oat and walnut crumble topping, with a dollop of thick white Greek yogurt',
  },
  {
    plan: 'SN-069',
    title: 'Koszyczki z szynki z jajkiem',
    description:
      'Plastry szynki ułożone w foremkach jak koszyczki, z jajkiem, żółtym serem i szczypiorkiem, upieczone w airfryerze. Białkowe, niskowęglowodanowe śniadanie, które wygląda efektownie.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['szynka', 80, 'g'],
      ['jajko', 4, 'szt'],
      ['ser żółty', 30, 'g'],
      ['pomidor koktajlowy', 100, 'g'],
      ['szczypiorek', 5, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Wyłóż 4 silikonowe foremki do muffinek plastrami szynki tak, żeby powstały koszyczki.',
      'Na dno każdego koszyczka posyp trochę startego sera i wbij po jednym jajku. Oprósz pieprzem.',
      'Piecz w airfryerze w 170°C 10–12 minut, aż białko się zetnie. W piekarniku: 180°C, 15 minut w formie do muffinek.',
      'Wyjmij koszyczki z foremek, posyp szczypiorkiem i podawaj z przekrojonymi pomidorkami koktajlowymi.',
    ],
    photo:
      'Two golden baked ham baskets, each holding a baked egg with a set yolk over melted cheese, sprinkled with chives, with halved cherry tomatoes',
  },
  {
    plan: 'SN-070',
    title: 'Muffinki owsiane z borówkami',
    description:
      'Wilgotne muffinki z płatków owsianych i dojrzałych bananów z borówkami, słodzone odrobiną miodu. Świetne do pudełka i do szkoły, a dzieci jedzą je jak ciastka.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'CAKE',
    equipment: ['AIRFRYER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['płatki owsiane', 100, 'g'],
      ['banan', 2, 'szt'],
      ['jajko', 2, 'szt'],
      ['mleko', 80, 'ml'],
      ['olej rzepakowy', 15, 'ml'],
      ['miód', 15, 'g'],
      ['proszek do pieczenia', 5, 'g'],
      ['borówka', 120, 'g'],
    ],
    steps: [
      'Zmiksuj połowę płatków owsianych na mąkę albo drobno je posiekaj, resztę zostaw w całości.',
      'Rozgnieć banany widelcem, dodaj jajka, mleko, olej i miód i wymieszaj.',
      'Wsyp płatki i proszek do pieczenia, połącz łyżką, a na koniec delikatnie wmieszaj borówki.',
      'Nałóż ciasto do 6 silikonowych foremek i piecz w airfryerze w 160°C 12–14 minut, aż patyczek wyjdzie suchy. W piekarniku: 180°C, 20 minut.',
      'Ostudź muffinki na kratce. W pudełku w lodówce wytrzymają 3 dni.',
    ],
    photo:
      'Three golden oat banana muffins with bursting blueberries, one broken in half to show the moist inside',
    vessel: 'board',
  },
  {
    plan: 'SN-071',
    title: 'Bajgle twarogowe',
    description:
      'Domowe bajgle z ciasta twarogowego bez drożdży, posypane sezamem i upieczone w airfryerze. Podane z pastą ze skyru i szczypiorku oraz pomidorem dają białkowe, sycące śniadanie.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'SANDWICH',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ser twaróg chudy', 200, 'g'],
      ['mąka pszenna', 150, 'g'],
      ['jajko', 1, 'szt'],
      ['proszek do pieczenia', 6, 'g'],
      ['sól', 1, 'g'],
      ['sezam', 8, 'g'],
      ['skyr naturalny', 150, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pomidor', 150, 'g'],
    ],
    steps: [
      'Rozgnieć twaróg widelcem, dodaj niemal całe jajko (zostaw łyżkę do posmarowania), sól, mąkę i proszek do pieczenia. Zagnieć gładkie, lekko klejące się ciasto.',
      'Podziel ciasto na 4 części, z każdej uformuj wałek i sklej końce w obwarzanek.',
      'Posmaruj bajgle resztą jajka i posyp sezamem.',
      'Piecz na papierze w airfryerze w 170°C 12–14 minut, aż się zrumienią. W piekarniku: 190°C, 20–22 minuty na blasze z papierem.',
      'Wymieszaj skyr z posiekanym szczypiorkiem, a pomidor pokrój w plastry.',
      'Przekrój ostudzone bajgle, posmaruj pastą ze skyru i włóż do środka plastry pomidora.',
    ],
    photo:
      'Golden homemade sesame bagels sliced and filled with creamy chive skyr spread and fresh tomato slices',
    vessel: 'board',
  },
  {
    plan: 'SN-072',
    title: 'Ziemniaki śniadaniowe z jajkiem i szczypiorkiem',
    description:
      'Chrupiąca kostka ziemniaczana z papryką i czosnkiem, na której w airfryerze zapiekają się jajka z płynnym żółtkiem. Na koniec jogurt i szczypiorek. Sycące śniadanie na leniwy weekend.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'POTATOES',
    equipment: ['AIRFRYER'],
    ingredients: [
      ['ziemniak', 500, 'g'],
      ['olej rzepakowy', 15, 'ml'],
      ['papryka słodka mielona', 2, 'g'],
      ['czosnek granulowany', 2, 'g'],
      ['sól', 2, 'g'],
      ['jajko', 4, 'szt'],
      ['jogurt naturalny', 100, 'g'],
      ['szczypiorek', 10, 'g'],
    ],
    steps: [
      'Ziemniaki umyj dokładnie i pokrój ze skórką w kostkę 1,5 cm. Wymieszaj z olejem, papryką, czosnkiem granulowanym i solą.',
      'Piecz w airfryerze w 200°C 18–20 minut, dwa razy potrząsając koszem, aż będą złote i chrupiące.',
      'Przełóż ziemniaki do formy pasującej do kosza, zrób 4 zagłębienia i wbij w nie jajka. Piecz w 170°C 6–8 minut, aż białka się zetną. W piekarniku: ziemniaki 220°C, 30 minut, potem z jajkami jeszcze 8–10 minut.',
      'Podawaj z łyżką jogurtu naturalnego i posyp obficie posiekanym szczypiorkiem.',
    ],
    photo:
      'Crispy golden paprika potato cubes with two baked eggs with runny yolks, a dollop of white natural yogurt and plenty of chopped chives',
  },

  // ── Wysokobiałkowe i keto ──
  {
    plan: 'SN-073',
    title: 'Omlet białkowy z indykiem i warzywami',
    description:
      'Lekki omlet na patelni z kawałkami chudego indyka, szpinakiem, papryką i pomidorkami koktajlowymi. Dużo białka przy niewielkiej kaloryczności, idealny po porannym treningu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 4, 'szt'],
      ['filet z indyka', 120, 'g'],
      ['szpinak', 60, 'g'],
      ['papryka czerwona', 80, 'g'],
      ['pomidor koktajlowy', 100, 'g'],
      ['olej rzepakowy', 10, 'ml'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Filet z indyka pokrój w drobną kostkę, paprykę w paski, a pomidorki przekrój na pół.',
      'Rozgrzej olej na patelni i smaż indyka 4–5 minut, aż się zrumieni. Dodaj paprykę i smaż 2 minuty, na koniec wrzuć szpinak, aż zwiędnie.',
      'Jajka roztrzep z solą i pieprzem i wlej na patelnię na mięso z warzywami.',
      'Smaż omlet pod przykryciem na małym ogniu 4–5 minut, aż się zetnie. Ułóż na wierzchu pomidorki, złóż na pół i podziel na dwie porcje.',
    ],
    photo:
      'Folded fluffy omelette filled with golden turkey pieces, wilted spinach and red pepper strips, topped with halved cherry tomatoes',
  },
  {
    plan: 'SN-074',
    title: 'Serek wiejski z jajkiem na twardo i szczypiorkiem',
    description:
      'Twarożek ziarnisty z posiekanym jajkiem na twardo, rzodkiewką, ogórkiem i szczypiorkiem, podany z pieczywem bezglutenowym. Szybkie, chłodne śniadanie pełne białka.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'YOGURT',
    ingredients: [
      ['serek wiejski', 250, 'g'],
      ['jajko', 3, 'szt'],
      ['rzodkiewka', 100, 'g'],
      ['ogórek', 150, 'g'],
      ['szczypiorek', 10, 'g'],
      ['pieprz czarny', 1, 'g'],
      ['chleb bezglutenowy', 80, 'g'],
    ],
    steps: [
      'Jajka włóż do wrzącej wody i gotuj 9 minut, potem przelej zimną wodą i obierz.',
      'Rzodkiewki pokrój w cienkie plasterki, ogórek w kostkę, a szczypiorek posiekaj.',
      'Jajka posiekaj i wymieszaj delikatnie z serkiem wiejskim, połową szczypiorku i pieprzem.',
      'Przełóż do misek, ułóż obok rzodkiewkę i ogórek, posyp resztą szczypiorku i podawaj z pieczywem bezglutenowym.',
    ],
    photo:
      'A mound of cottage cheese mixed with chopped hard-boiled egg, chives and black pepper, beside thin radish slices, diced cucumber and a slice of gluten-free bread',
  },
  {
    plan: 'SN-075',
    title: 'Kanapki z pastą z jajek i tuńczyka',
    description:
      'Kremowa pasta z jajek na twardo i tuńczyka z jogurtem greckim, musztardą i szczypiorkiem na razowym chlebie żytnim z ogórkiem. Białkowe śniadanie, które łatwo zabrać ze sobą.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'SANDWICH',
    ingredients: [
      ['jajko', 3, 'szt'],
      ['tuńczyk w puszce', 120, 'g'],
      ['jogurt grecki', 40, 'g'],
      ['musztarda', 5, 'g'],
      ['szczypiorek', 10, 'g'],
      ['chleb żytni', 120, 'g'],
      ['ogórek', 100, 'g'],
    ],
    steps: [
      'Jajka gotuj 9 minut od zawrzenia wody, przelej zimną wodą i obierz.',
      'Tuńczyka odsącz dokładnie z zalewy i rozdrobnij widelcem.',
      'Jajka posiekaj drobno, wymieszaj z tuńczykiem, jogurtem greckim, musztardą i posiekanym szczypiorkiem.',
      'Posmaruj pastą kromki chleba żytniego i ułóż na nich plasterki ogórka.',
    ],
    photo:
      'Rye bread slices spread with creamy egg and tuna paste, topped with cucumber slices and chopped chives',
    vessel: 'board',
  },
  {
    plan: 'SN-076',
    title: 'Owsianka z twarogiem i jagodami',
    description:
      'Owsianka na mleku wymieszana z chudym twarogiem, który dodaje kremowości i dużo białka, podana z jagodami i miodem. Syci na długo i dobrze sprawdza się przed pracą fizyczną lub treningiem.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'PORRIDGE',
    ingredients: [
      ['płatki owsiane', 70, 'g'],
      ['mleko', 300, 'ml'],
      ['ser twaróg chudy', 150, 'g'],
      ['jagoda', 150, 'g'],
      ['miód', 15, 'g'],
    ],
    steps: [
      'Wsyp płatki owsiane do garnka, wlej mleko, zagotuj i gotuj na małym ogniu 5 minut, mieszając.',
      'Zdejmij garnek z ognia i wmieszaj rozgnieciony widelcem twaróg, aż owsianka zrobi się kremowa.',
      'Dodaj miód i wymieszaj.',
      'Przełóż do misek i ułóż na wierzchu jagody.',
    ],
    photo:
      'Creamy oat porridge enriched with white quark, topped with a generous handful of fresh blueberries and a drizzle of honey',
    vessel: 'bowl',
  },
  {
    plan: 'SN-077',
    title: 'Jajecznica z indykiem i papryką',
    description:
      'Puszysta jajecznica na maśle z podsmażonym filetem z indyka, słodką papryką i dymką. Białkowe śniadanie gotowe w kwadrans, które syci do obiadu.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 5, 'szt'],
      ['filet z indyka', 150, 'g'],
      ['papryka czerwona', 150, 'g'],
      ['cebula dymka', 30, 'g'],
      ['masło', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Indyka pokrój w cienkie paski, paprykę w kostkę, a dymkę w krążki, oddzielając szczypior.',
      'Rozgrzej masło na patelni, smaż indyka 4–5 minut, dodaj paprykę i białą część dymki i smaż jeszcze 3 minuty.',
      'Jajka roztrzep z solą i pieprzem, wlej na patelnię i mieszaj powoli na małym ogniu 2–3 minuty, aż się zetną, ale zostaną wilgotne.',
      'Posyp szczypiorem z dymki i podawaj od razu.',
    ],
    photo:
      'Soft creamy scrambled eggs with golden turkey strips, diced red pepper and sliced green onion',
  },
  {
    plan: 'SN-078',
    title: 'Pudding proteinowy z chia i skyrem',
    description:
      'Gęsty pudding z nasion chia na mleku, wymieszany ze skyrem i podany z malinami. Dużo białka i błonnika, a przygotowany wieczorem w słoikach wystarcza na kilka poranków.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'YOGURT',
    ingredients: [
      ['nasiona chia', 40, 'g'],
      ['mleko', 150, 'ml'],
      ['skyr naturalny', 300, 'g'],
      ['miód', 15, 'g'],
      ['malina', 150, 'g'],
    ],
    steps: [
      'Wymieszaj nasiona chia z mlekiem i miodem, odstaw na 5 minut i wymieszaj ponownie, żeby nie zrobiły się grudki.',
      'Dodaj skyr i dokładnie połącz.',
      'Przełóż pudding do słoików i wstaw do lodówki na co najmniej 30 minut, a najlepiej na noc. Zamknięty wytrzyma w lodówce 3 dni.',
      'Przed podaniem ułóż na wierzchu maliny.',
    ],
    photo:
      'Thick creamy white chia and skyr pudding speckled with dark chia seeds, topped with fresh red raspberries',
    vessel: 'bowl',
  },
  {
    plan: 'SN-079',
    title: 'Omlet z awokado, boczkiem i serem',
    description:
      'Omlet na maśle z chrupiącym boczkiem i roztopionym cheddarem, podany z plastrami awokado i pomidorkami. Tłuste, sycące śniadanie z minimalną ilością węglowodanów.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 20,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 4, 'szt'],
      ['boczek', 60, 'g'],
      ['ser cheddar', 30, 'g'],
      ['awokado', 1, 'szt'],
      ['masło', 10, 'g'],
      ['pomidor koktajlowy', 60, 'g'],
      ['szczypiorek', 5, 'g'],
    ],
    steps: [
      'Boczek pokrój w paski i podsmaż na suchej patelni 4–5 minut na chrupko, a potem przełóż na talerz.',
      'Awokado przekrój, usuń pestkę, obierz i pokrój w plastry. Pomidorki przekrój na pół, a cheddar zetrzyj.',
      'Na patelni roztop masło, wlej roztrzepane jajka i smaż na małym ogniu 3 minuty. Posyp połowę omletu serem i boczkiem, przykryj i smaż jeszcze 2 minuty.',
      'Złóż omlet na pół, podziel na dwie części i podawaj z awokado, pomidorkami i szczypiorkiem.',
    ],
    photo:
      'Folded golden omelette with crispy bacon and melted cheddar peeking out, served with avocado slices, cherry tomatoes and chives',
  },
  {
    plan: 'SN-080',
    title: 'Jajka sadzone z awokado i wędzonym łososiem',
    description:
      'Jajka sadzone na maśle z płynnym żółtkiem, plastry wędzonego łososia, awokado z cytryną i garść rukoli. Eleganckie, niskowęglowodanowe śniadanie gotowe w kwadrans.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 15,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    ingredients: [
      ['jajko', 4, 'szt'],
      ['awokado', 1, 'szt'],
      ['łosoś wędzony', 80, 'g'],
      ['rukola', 40, 'g'],
      ['masło', 10, 'g'],
      ['cytryna', 20, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Awokado przekrój, usuń pestkę, obierz, pokrój w plastry i skrop sokiem z cytryny.',
      'Roztop masło na patelni i usmaż jajka sadzone na małym ogniu przez 3–4 minuty, aż białko się zetnie, a żółtko zostanie płynne.',
      'Rozłóż na talerzach rukolę, awokado i plastry wędzonego łososia.',
      'Dołóż jajka sadzone, oprósz pieprzem i podawaj od razu.',
    ],
    photo:
      'Two sunny-side-up eggs with runny yolks and cracked black pepper, pink smoked salmon ribbons, fanned avocado slices and a handful of arugula',
  },
  {
    plan: 'SN-081',
    title: 'Muffinki jajeczne z brokułem i cheddarem',
    description:
      'Jajeczne muffinki z różyczkami brokułu, dymką i cheddarem, upieczone w foremkach. Pieką się raz, a potem przez kilka dni są gotowym, niskowęglowodanowym śniadaniem do pudełka.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 35,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'EGGS',
    equipment: ['OVEN'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['jajko', 6, 'szt'],
      ['brokuł', 150, 'g'],
      ['ser cheddar', 60, 'g'],
      ['śmietana 18', 50, 'g'],
      ['cebula dymka', 20, 'g'],
      ['olej rzepakowy', 5, 'ml'],
      ['papryka słodka mielona', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Rozgrzej piekarnik do 180°C i posmaruj olejem 6 wgłębień formy do muffinek.',
      'Brokuł podziel na małe różyczki i blanszuj 3 minuty we wrzącej wodzie, a potem odcedź. Dymkę posiekaj, a cheddar zetrzyj.',
      'Roztrzep jajka ze śmietaną, papryką i pieprzem, dodaj dymkę i połowę sera.',
      'Rozłóż brokuł do foremek, zalej masą jajeczną i posyp resztą cheddaru.',
      'Piecz w piekarniku 18–20 minut, aż muffinki urosną i się zetną. Ostudzone przechowuj w lodówce do 3 dni.',
    ],
    photo:
      'Three golden baked egg muffins studded with bright green broccoli florets and spring onion, topped with melted cheddar, one cut in half',
    vessel: 'board',
  },
  {
    plan: 'SN-082',
    title: 'Pudding chia na mleku kokosowym z orzechami bez cukru',
    description:
      'Kremowy pudding z nasion chia na mleku kokosowym i migdałowym z cynamonem, orzechami i kilkoma malinami. Bez cukru i bez nabiału, sycący dzięki zdrowym tłuszczom.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'OTHER',
    dishType: 'YOGURT',
    ingredients: [
      ['nasiona chia', 40, 'g'],
      ['mleko kokosowe z puszki', 200, 'ml'],
      ['mleko migdałowe', 150, 'ml'],
      ['cynamon', 1, 'g'],
      ['orzech włoski', 20, 'g'],
      ['orzech laskowy', 15, 'g'],
      ['malina', 60, 'g'],
    ],
    steps: [
      'Wymieszaj mleko kokosowe z migdałowym i cynamonem, wsyp nasiona chia i dokładnie połącz.',
      'Odstaw na 5 minut, wymieszaj ponownie i wstaw do lodówki na co najmniej 30 minut albo na noc.',
      'Orzechy włoskie i laskowe posiekaj grubo i podpraż 2–3 minuty na suchej patelni.',
      'Przełóż pudding do miseczek, posyp orzechami i udekoruj malinami.',
    ],
    photo:
      'Creamy white coconut chia pudding topped with toasted chopped walnuts and hazelnuts and a few fresh raspberries',
    vessel: 'bowl',
  },

  // ── Śniadanie wielkanocne ──
  {
    plan: 'SN-083',
    title: 'Jajka faszerowane pieczarkami i szczypiorkiem',
    description:
      'Połówki jajek na twardo nadziane farszem z żółtek, podsmażonych pieczarek z cebulą i szczypiorku. Klasyk wielkanocnego stołu, który przygotujesz dzień wcześniej.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    occasions: ['EASTER'],
    ingredients: [
      ['jajko', 6, 'szt'],
      ['pieczarka', 150, 'g'],
      ['cebula', 50, 'g'],
      ['masło', 10, 'g'],
      ['majonez', 20, 'g'],
      ['szczypiorek', 10, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Jajka gotuj 10 minut od zawrzenia wody, przelej zimną wodą i obierz.',
      'Pieczarki i cebulę posiekaj drobno i smaż na maśle 7–8 minut, aż odparuje woda. Ostudź.',
      'Przekrój jajka wzdłuż na pół i wyjmij żółtka. Rozgnieć je widelcem z pieczarkami, majonezem, większością szczypiorku, solą i pieprzem.',
      'Nałóż farsz łyżeczką do połówek białek, posyp resztą szczypiorku i schłódź przed podaniem.',
    ],
    photo:
      'Halved hard-boiled eggs generously filled with a mushroom and yolk stuffing, sprinkled with fresh chopped chives',
  },
  {
    plan: 'SN-084',
    title: 'Jajka faszerowane pastą z tuńczyka',
    description:
      'Połówki jajek nadziane kremową pastą z żółtek, tuńczyka, majonezu i musztardy, posypane koperkiem i papryką. Wyraziste jajka na wielkanocny stół, gotowe w pół godziny.',
    mealType: 'BREAKFAST',
    difficulty: 'EASY',
    prepTimeMinutes: 30,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    occasions: ['EASTER'],
    ingredients: [
      ['jajko', 6, 'szt'],
      ['tuńczyk w puszce', 80, 'g'],
      ['majonez', 20, 'g'],
      ['jogurt grecki', 30, 'g'],
      ['musztarda', 5, 'g'],
      ['koperek', 5, 'g'],
      ['papryka słodka mielona', 1, 'g'],
    ],
    steps: [
      'Jajka gotuj 10 minut od zawrzenia wody, przelej zimną wodą i obierz.',
      'Tuńczyka odsącz dokładnie z zalewy.',
      'Przekrój jajka wzdłuż, wyjmij żółtka i zmiksuj je albo rozgnieć z tuńczykiem, majonezem, jogurtem i musztardą na gładką pastę.',
      'Nałóż pastę do połówek białek, posyp posiekanym koperkiem i oprósz papryką. Schłódź przed podaniem.',
    ],
    photo:
      'Deviled egg halves heaped with smooth creamy tuna and yolk filling, garnished with fresh dill and a dusting of sweet paprika',
  },
  {
    plan: 'SN-085',
    title: 'Jajka faszerowane w skorupkach zapiekane',
    description:
      'Staropolskie jajka przekrojone razem ze skorupką, nadziane masą z żółtek, masła, śmietany i ziół, posypane bułką tartą i zapieczone na złoto. Ciepły akcent wielkanocnego śniadania.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 40,
    servings: 2,
    cuisine: 'POLISH',
    dishType: 'EGGS',
    occasions: ['EASTER'],
    equipment: ['OVEN'],
    ingredients: [
      ['jajko', 6, 'szt'],
      ['masło', 15, 'g'],
      ['śmietana 18', 30, 'g'],
      ['szczypiorek', 10, 'g'],
      ['koperek', 5, 'g'],
      ['bułka tarta', 15, 'g'],
      ['sól', 1, 'g'],
      ['pieprz czarny', 1, 'g'],
    ],
    steps: [
      'Jajka dokładnie umyj i gotuj 10 minut od zawrzenia wody, a potem przelej zimną wodą.',
      'Rozgrzej piekarnik do 200°C. Każde jajko przekrój wzdłuż razem ze skorupką bardzo ostrym nożem i wybierz łyżeczką zawartość, nie uszkadzając skorupek.',
      'Posiekaj białka i żółtka drobno, wymieszaj z połową masła, śmietaną, posiekanym szczypiorkiem i koperkiem, solą i pieprzem.',
      'Napełnij skorupki farszem z górką, wyrównaj i posyp bułką tartą. Na wierzchu połóż wiórki reszty masła.',
      'Ułóż jajka w naczyniu żaroodpornym i zapiekaj w piekarniku 10–12 minut, aż wierzch się zrumieni. Podawaj na ciepło.',
    ],
    photo:
      'Egg halves baked in their lengthwise-cut white shells, heaped with chopped egg filling flecked with chives and dill and topped with a golden buttery breadcrumb crust',
  },
  {
    plan: 'SN-086',
    title: 'Rolada z kurczaka ze szpinakiem na zimno',
    description:
      'Rozbite filety z kurczaka zwinięte z farszem ze szpinaku, czosnku i fety, upieczone i podane w plastrach na zimno. Białkowa wędlina domowej roboty na wielkanocny stół.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 180,
    servings: 4,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['EASTER'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['filet z kurczaka', 600, 'g'],
      ['szpinak', 150, 'g'],
      ['ser feta', 60, 'g'],
      ['czosnek', 2, 'szt'],
      ['oliwa z oliwek', 15, 'ml'],
      ['papryka słodka mielona', 3, 'g'],
      ['sól', 3, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Filety przekrój wzdłuż na płaty, przykryj folią i rozbij tłuczkiem na cienkie kotlety. Oprósz solą, pieprzem i papryką.',
      'Na łyżeczce oliwy podsmaż przeciśnięty czosnek, dodaj szpinak i duś 2–3 minuty, aż zwiędnie i odparuje. Ostudź i wymieszaj z pokruszoną fetą.',
      'Ułóż kotlety na folii aluminiowej zachodząc na siebie w prostokąt, rozsmaruj farsz i zwiń ciasno w roladę. Zawiń w folię i skręć jej końce.',
      'Rozgrzej piekarnik do 190°C. Piecz roladę w folii 30 minut, potem rozwiń, posmaruj resztą oliwy i piecz jeszcze 10 minut, aż się zrumieni.',
      'Ostudź, owiń folią i schłódź w lodówce co najmniej 2 godziny. Kroi się w cienkie plastry ostrym nożem.',
    ],
    photo:
      'Overlapping thin slices of chilled golden paprika-crusted chicken roulade showing a green spinach and white feta spiral in the center',
  },
  {
    plan: 'SN-087',
    title: 'Pasztet z soczewicy i warzyw',
    description:
      'Wilgotny pasztet z czerwonej soczewicy, marchewki, pietruszki i cebuli z majerankiem i wędzoną papryką, upieczony w keksówce. Roślinna propozycja na Wielkanoc, która smakuje też na kanapkach przez kilka dni.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 120,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'BAKE',
    occasions: ['EASTER'],
    equipment: ['OVEN', 'BLENDER'],
    features: ['LUNCHBOX'],
    ingredients: [
      ['soczewica czerwona', 200, 'g'],
      ['marchew', 150, 'g'],
      ['pietruszka korzeń', 100, 'g'],
      ['cebula', 100, 'g'],
      ['czosnek', 2, 'szt'],
      ['olej rzepakowy', 30, 'ml'],
      ['płatki owsiane', 40, 'g'],
      ['siemię lniane', 15, 'g'],
      ['majeranek', 3, 'g'],
      ['papryka wędzona mielona', 2, 'g'],
      ['gałka muszkatołowa', 1, 'g'],
      ['sól', 4, 'g'],
      ['pieprz czarny', 2, 'g'],
    ],
    steps: [
      'Soczewicę przepłucz i ugotuj w 500 ml wody przez 15 minut, aż się rozpadnie i wchłonie wodę.',
      'Marchew i pietruszkę zetrzyj na tarce o grubych oczkach, cebulę i czosnek posiekaj. Duś wszystko na oleju 10 minut, aż warzywa zmiękną.',
      'Siemię lniane zmiel i zalej 50 ml gorącej wody, odstaw na 5 minut, żeby zgęstniało.',
      'Zmiksuj blenderem soczewicę z warzywami, płatkami owsianymi, siemieniem, majerankiem, papryką, gałką, solą i pieprzem na gęstą masę.',
      'Rozgrzej piekarnik do 180°C. Przełóż masę do keksówki wyłożonej papierem, wyrównaj i piecz 50 minut, aż wierzch się zrumieni.',
      'Ostudź pasztet w formie, a przed krojeniem schłódź w lodówce. Przechowuj w lodówce do 4 dni.',
    ],
    photo:
      'Thick slices of rustic orange-brown lentil and vegetable pate with a golden baked crust and a dense, finely flecked crumb',
    vessel: 'board',
  },
  {
    plan: 'SN-088',
    title: 'Schab pieczony ze śliwką na zimno',
    description:
      'Soczysty schab nadziewany suszonymi śliwkami, natarty czosnkiem, majerankiem i musztardą, upieczony i podany w plastrach na zimno. Świąteczna pieczeń, która zastąpi kupną wędlinę.',
    mealType: 'BREAKFAST',
    difficulty: 'MEDIUM',
    prepTimeMinutes: 350,
    servings: 6,
    cuisine: 'POLISH',
    dishType: 'MAIN',
    occasions: ['EASTER', 'CHRISTMAS'],
    equipment: ['OVEN'],
    features: ['OCCASIONAL'],
    ingredients: [
      ['schab wieprzowy', 1200, 'g'],
      ['śliwka suszona', 120, 'g'],
      ['czosnek', 4, 'szt'],
      ['musztarda', 20, 'g'],
      ['majeranek', 4, 'g'],
      ['olej rzepakowy', 20, 'ml'],
      ['sól', 8, 'g'],
      ['pieprz czarny', 3, 'g'],
    ],
    steps: [
      'Wymieszaj przeciśnięty czosnek z musztardą, majerankiem, solą, pieprzem i połową oleju.',
      'Długim, cienkim nożem zrób w schabie wzdłuż tunel na środku i wepchnij do niego śliwki. Natrzyj mięso marynatą i odstaw do lodówki na co najmniej 2 godziny.',
      'Rozgrzej piekarnik do 180°C. Obsmaż schab z każdej strony na reszcie oleju, po 2 minuty.',
      'Przełóż mięso do naczynia żaroodpornego i piecz pod przykryciem 50 minut, potem bez przykrycia jeszcze 25 minut, polewając sosem z dna.',
      'Ostudź schab, a następnie schłódź w lodówce co najmniej 2 godziny. Podawaj w cienkich plastrach.',
    ],
    photo:
      'Overlapping thin slices of cold roast pork loin with a golden-brown mustard and marjoram crust and a dark prune center',
    vessel: 'board',
  },
];
