import { ShoppingDepartment } from '../types/shopping-department.enum';

/// Heuristic keyword rules used to guess a department when an ingredient
/// doesn't have an explicit override. Order matters: first match wins.
/// Keywords are matched against a normalized (lowercased, accent-stripped)
/// version of the ingredient name, so list them without Polish diacritics.
export const DEPARTMENT_KEYWORD_RULES: Array<{
  department: ShoppingDepartment;
  keywords: string[];
}> = [
  {
    department: ShoppingDepartment.VEGETABLES,
    keywords: [
      'warzyw',
      'veget',
      'produce',
      'ziemniak',
      'cebula',
      'czosn',
      'marchew',
      'seler',
      'pomidor',
      'papryk',
      'ogorek',
      'szpinak',
      'salata',
      'kalafior',
      'brokul',
      'cukini',
      'baklazan',
      'burak',
      'por',
      'jarmuz',
      'pietruszk',
    ],
  },
  {
    department: ShoppingDepartment.FRUITS,
    keywords: [
      'owoc',
      'fruit',
      'jablk',
      'banan',
      'cytryn',
      'limonk',
      'pomarancz',
      'gruszk',
      'truskawk',
      'borowk',
      'malin',
      'winogron',
      'ananas',
      'awokado',
    ],
  },
  {
    department: ShoppingDepartment.MEAT,
    keywords: [
      'mies',
      'meat',
      'drob',
      'poultry',
      'kaczk',
      'kurczak',
      'wolowin',
      'wieprz',
      'indyk',
      'kielbas',
      'boczek',
      'schab',
    ],
  },
  {
    department: ShoppingDepartment.FISH,
    keywords: [
      'ryb',
      'fish',
      'seafood',
      'dorsz',
      'losos',
      'tunczyk',
      'krewetk',
      'mintaj',
      'halibut',
      'makrela',
    ],
  },
  {
    department: ShoppingDepartment.DAIRY,
    keywords: [
      'nabial',
      'dairy',
      'milk',
      'mleko',
      'jogurt',
      'kefir',
      'skyr',
      'maslo',
      'smietan',
      'twarog',
      'jajk',
      'ser',
      'sery',
      'sera',
      'serek',
      'gouda',
      'mozzarella',
      'mozarella',
      'feta',
      'parmezan',
      'cheddar',
      'ricotta',
      'brie',
      'camembert',
    ],
  },
  {
    department: ShoppingDepartment.BAKERY,
    keywords: [
      'piekarn',
      'bakery',
      'bread',
      'chleb',
      'bulk',
      'pieczyw',
      'tortill',
      'pita',
      'bagietk',
    ],
  },
  {
    department: ShoppingDepartment.GRAINS,
    keywords: [
      'zboz',
      'grain',
      'pasta',
      'rice',
      'makaron',
      'ryz',
      'kasz',
      'platki',
      'maka',
      'owsian',
      'soczewic',
      'ciecierzyc',
      'quinoa',
      'komosa',
      'fasol',
    ],
  },
  {
    department: ShoppingDepartment.CANNED,
    keywords: [
      'konserw',
      'canned',
      'jar',
      'sloik',
      'puszka',
      'oliwk',
      'passata',
      'bulion',
      'mleko kokosowe',
    ],
  },
  {
    department: ShoppingDepartment.SPICES,
    keywords: [
      'przypraw',
      'spice',
      'herb',
      'sauce',
      'sos',
      'sol',
      'pieprz',
      'papryk',
      'curry',
      'oregano',
      'bazyl',
      'cynamon',
      'musztard',
      'majonez',
      'ocet',
      'ziola',
      'kmink',
      'jalowiec',
      'proszek do pieczenia',
      'soda',
    ],
  },
  {
    department: ShoppingDepartment.OILS,
    keywords: ['olej', 'tluszcz', 'oil', 'fat', 'oliwa', 'smalec'],
  },
  {
    department: ShoppingDepartment.ALCOHOLS,
    keywords: [
      'alkohol',
      'wino',
      'piwo',
      'whisky',
      'whiskey',
      'wodka',
      'rum',
      'gin',
      'tequila',
      'brandy',
      'likier',
      'prosecco',
      'szampan',
      'cydr',
      'riesling',
      'merlot',
      'cabernet',
    ],
  },
  {
    department: ShoppingDepartment.BEVERAGES,
    keywords: ['napoj', 'beverage', 'drink', 'woda', 'kawa', 'herbat', 'sok'],
  },
  {
    department: ShoppingDepartment.SNACKS,
    keywords: [
      'slodycz',
      'przekask',
      'snack',
      'sweet',
      'czekolad',
      'ciastk',
      'chips',
      'orzech',
      'miod',
      'baton',
    ],
  },
  {
    department: ShoppingDepartment.FROZEN,
    keywords: ['mrozon', 'frozen', 'lody'],
  },
  {
    department: ShoppingDepartment.CONFECTIONERY,
    keywords: [
      'cukiern',
      'pastry',
      'dessert',
      'cake',
      'cukier',
      'drozdzowk',
      'biszkopt',
    ],
  },
  {
    department: ShoppingDepartment.HOUSEHOLD,
    keywords: [
      'chemia',
      'household',
      'clean',
      'papier',
      'plyn',
      'proszek do prania',
      'worki na smieci',
      'reczniki papierowe',
    ],
  },
];
