export type AppErrorCode =
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'VALIDATION_ERROR'
  | 'PLAN_SLOT_LIMIT_REACHED'
  | 'PLAN_TOTAL_LIMIT_REACHED'
  | 'SHOPPING_LIST_EMPTY'
  | 'SHOPPING_LIST_NOT_COMPLETED'
  | 'INVITATION_EXPIRED'
  | 'INVITATION_ALREADY_REDEEMED'
  | 'CONFLICT'
  | 'INTERNAL_ERROR';
